### ISSUE TITLE
[Feature] unit testing: dbt should tell me why it couldn't get columns (the model doesn't yet exist)

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#10014]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I tried making my first unit test from scratch (no using the docs!) and got the below error. 

It turns out that the issue was that the models hadn't been built yet, but the error didn't explain _why_ it couldn’t get the columns. 

```
(dbt-dev) joel@Joel-Labes integration_tests % dbt test -s test_type:unit
02:56:57  Running with dbt=1.8.0-b3
02:56:57  Registered adapter: snowflake=1.8.0-b3
02:56:58  Found 22 models, 2 analyses, 24 seeds, 19 data tests, 576 macros, 1 unit test
02:56:58  
02:56:59  Concurrency: 8 threads (target='dev')
02:56:59  
02:56:59  1 of 1 START unit_test unit_compare_queries::identical_records_compare_queries . [RUN]
02:57:01  1 of 1 ERROR unit_compare_queries::identical_records_compare_queries ........... [ERROR in 1.62s]
02:57:01  
02:57:01  Finished running 1 unit test in 0 hours 0 minutes and 3.29 seconds (3.29s).
02:57:01  
02:57:01  Completed with 1 error and 0 warnings:
02:57:01  
02:57:01    Compilation Error in model unit_test_model_a (models/unit_test_wrappers/unit_tests.yml)
  Not able to get columns for unit test 'unit_test_model_a' from relation ANALYTICS_DEV.DBT_JLABES_INT_TESTS.unit_test_model_a
  
  > in macro get_fixture_sql (macros/unit_test_sql/get_fixture_sql.sql)
  > called by model unit_test_model_a (models/unit_test_wrappers/unit_tests.yml)
02:57:01  
02:57:01  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Expected Behavior

Ignoring the fact that there could be other causes for this (ephemeral models? permissions issues? idk), the general thing that I felt was missing was an explanation of what I could do to solve it. Something like 

Not able to get columns for unit test 'unit_test_model_a' from relation ANALYTICS_DEV.DBT_JLABES_INT_TESTS.unit_test_model_a because the relation doesn't exist.

would be plenty to make me go "oh of course I need to do a build (or defer to prod). 

### Steps To Reproduce

1. Add a new model 
2. Add a unit test to that model but don't build the new model 
3. Run `dbt test -s test_type:unit`

### Environment

```markdown
- OS:
- Python:
- dbt: dbt-core@2edd5b3335ddea4ca5e7dd8aaa3bfe3a5d30499a (using Core on main as of about 5 days ago, roughly equivalent to the 1.8 beta)
```

**Comment by dbeatty10** [comment]
> I tried making my first unit test from scratch (no using the docs!) and got the below error.

That's awesome 🤩

Yeah, it would be nice to give more hints to our intrepid hikers on how to get back on the trail.

Re-labeling as a feature request and adding the `refinement` label to consider an alternative error message.

**Comment by graciegoheen** [comment]
Hello! A few thoughts:
- if you're using deferral, you should be fine here! (as long as the relation is built in the environment you're deferring to)
- you can also use the `--empty` flag to build an empty relation, if you don't want to use less warehouse $$$

```
  Not able to get columns for unit test 'unit_test_model_a' from relation ANALYTICS_DEV.DBT_JLABES_INT_TESTS.unit_test_model_a
```
I agree this is a bit vague. You could not be able to get the columns from this relation because:
- the relation doesn't exist (hasn't been built yet)
- the relation doesn't exist (it never will, it's an ephemeral model)

I'm with updating to:
```
  Not able to get columns for unit test 'unit_test_model_a' from relation ANALYTICS_DEV.DBT_JLABES_INT_TESTS.unit_test_model_a because the relation doesn't exist.
```

**Comment by AlejandroBlanco2001** [comment]
Hey @graciegoheen @joellabes, I would like to take this issue to get started in the repository, can I take it ?

**Comment by graciegoheen** [comment]
@AlejandroBlanco2001 That would be great!

**Comment by jtcohen6** [comment]
@AlejandroBlanco2001 Nice detective work! I think this might be a bit simpler though — the compilation error is actually being raised directly by [the `get_fixture_sql` macro in `dbt-adapters`](https://github.com/dbt-labs/dbt-adapters/blob/d831caa33bc1a31d1162f1d1b3ccd6caaec08fd5/dbt/include/global_project/macros/unit_test_sql/get_fixture_sql.sql#L17-L19). It sounds like the proposed resolution is to update the language in that exception message.

**Comment by AlejandroBlanco2001** [comment]
@jtcohen6 Oh, thanks for being even more specific about where the message is. Do you think we should update that error message directly, or should we raise the compilation error inside the other method to keep it more generic? I'm happy to open the PR after that.

**Comment by AlejandroBlanco2001** [comment]
@jtcohen6 @graciegoheen PR opened 🎉
