### ISSUE TITLE
[Bug] print in jinja do not go through event system

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#10030]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If a user uses the [`print`](https://github.com/dbt-labs/dbt-core/blob/37b1fce205c8e7a9945bb780deb4c4764a24f228/core/dbt/context/base.py#L680) in the Jinja context, this print will go to stdout directly instead of going through the dbt-core's event system.

This would lead to things printed in jinja do not follow `--log-format json` config.

### Expected Behavior

`print` in jinja follow dbt-core's flag --log-format

### Steps To Reproduce

Run a run operation with a macro that has `print` inside and use `--log-format json` at the same time.
You will see dbt-core logs are in json but the things printed in jinja is in plain text.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by dichenqiandbt** [comment]
An example
```
{% macro test() %}
    {{ print(1234)}}
    {{ return(1233434) }}
{% endmacro %}
```
When user specify --log-format json, we expect 1234 should be printed in a json format and maybe logged in dbt.log as well?

The customer uses "generate_source" from codegen dbt package.

**Comment by ChenyuLInx** [comment]
Closing in favor of 8756 since it is the same issue and have a more detailed AC.
