### ISSUE TITLE
[Bug] Fail fast behavior not correct when using multiple threads

### ISSUE THREAD

**Issue by gaoshihang** [dbt-labs/dbt-core#10057]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I use fail fast in "dbt run", and using 20 threads to submit some models to Databricks, but when a model failed, others still running.

### Expected Behavior

When a model fails, others fail too.

### Steps To Reproduce

dbt run --select staging --fail-fast

### Environment

```markdown
- OS: macos
- Python: 3.9.6
- dbt: 1.7.11
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

dbt-databricks adaptor

![image](https://github.com/dbt-labs/dbt-core/assets/20013931/7b643de6-6e02-493c-8d86-9bf292c2ac86)

**Comment by gaoshihang** [comment]
Hi @dbeatty10 May I ask another question in this issue?

Can we run multiple “dbt build” at the same time? each “dbt build” handles different part of source data.
For example:
Source data is partitioned by batch_id.
DBT run-1: dbt build --vars ‘{“batch_id”: “1"}’
DBT run-2: dbt build --vars ‘{“batch_id”: “2"}’
DBT run-3: dbt build --vars ‘{“batch_id”: “3"}’

If we can, do we need to executor each command in different dbt project directory?

**Comment by gaoshihang** [comment]
We are using dbt-core, not dbt-cloud

**Comment by dbeatty10** [comment]
> Can we run multiple “dbt build” at the same time? each “dbt build” handles different part of source data.

dbt-core is designed for a single invocation at any given time. If you construct things such that each `dbt build` handles independent portions of data, it may work. But if you run into any issues, we would not consider them a bug since multiple concurrent runs are out of scope for dbt-core.

**Comment by gaoshihang** [comment]
Thanks @dbeatty10 for your reply. Can you give me some guide on this? 
If I run these dbt build in one dbt directory, will the manifest json file will be influenced?

I'm thinking that we use different dbt directory for each "dbt build", handle independent portions of data, then out to different target table, like we add a suffix table_{batch_id}

**Comment by gaoshihang** [comment]
Got it!

Thanks! @dbeatty10
