### ISSUE TITLE
[Bug] Seed properties .yml files compile twice and clash when seed directory is under model directory

### ISSUE THREAD

**Issue by mbarnathan-os** [dbt-labs/dbt-core#10064]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When specifying seed properties via a .yml file and the seed-paths directory is under the model-paths directory, the .yml file will be compiled twice and dbt will error out with "dbt found two schema.yml entries for the same resource" against the same file, even though there is no actual duplication. This doesn't happen if the seed is defined solely by csv; i.e. the yml file is absent.

### Expected Behavior

Nesting seeds under the model directory is a supported use case per the docs, so I would expect the model parsing phase to detect the duplication and omit the seed a second time.

### Steps To Reproduce

1. model-paths: ["models"]
2. seed-paths: ["models/seeds"]
3. Add a .yml file in the seed path with at least one seed
4. Add a csv file for the seed
5. dbt parse yields "dbt found two schema.yml entries for the same resource" with the seed yml from step 3

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reporting this @mbarnathan-os 👍

I was able to reproduce what you described. See details below.

<details>
<summary>

### Reprex
</summary>

`dbt_project.yml`

```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "some_profile"

model-paths: ["models"]
seed-paths: ["models/seeds"]
```

```shell
mkdir -p models
mkdir -p models/seeds
```

Create a seed file:

```shell
cat <<EOF > models/seeds/my_seed.csv
id
1
EOF
```

Add an associated YAML file:

```shell
cat <<EOF > models/seeds/_seeds.yml
seeds:
  - name: my_seed
EOF
```

See that it never works when partial parsing is **disabled** (but may work it certain situations when it is enabled):
```shell
dbt parse --no-partial-parse
dbt list --no-partial-parse
```

#### Side note
For me, I did an initial `dbt parse` prior to adding the YAML file, and dbt commands worked as long as partial parsing was enabled and I didn't `dbt clean` my partial parsing artifacts.

</details>
