### ISSUE TITLE
Looking if we can add the ability to select a Snowflake warehouse for a test that is independent from the warehouse the model tested is built with.

### ISSUE THREAD

**Issue by will-sargent-dbtlabs** [dbt-labs/dbt-core#10089]
Background:
The Snowflake virtual warehouse set for the base model, extends to any data tests run on the model regardless of injecting a {{ config(snowflake_warehouse='XXL') }} into the testing definition.

The challenge with this is that some customers would like to apply a faster warehouse for some test cases (like unique) that are underperforming in their environment.

Or perhaps the 2XL warehouse isn't the one you need to test not_null, even though it's the correct tool for the incremental build..

Today, there is no way around this and I've tried it all:
Test config YAML `snowflake_warehouse` keys,
Config blocks in the test itself, etc..

While we likely don't want to support most normal config options for a test (the database and schema should be the same as the model we want to test), the snowflake_warehouse option should be one we have available in the test config block context in my opinion.

I've scanned some code, but I'm still a bit unclear if this is challenging or not to implement, but it feels like we are adjusting the allowed/parsed parameters of a test config block, and adding the snowflake specific warehouse key as a valid option, then calling the proper function to add the right `use warehouse 2XXL` at the beginning of the compiled test.

You could do this by separating `dbt build` into `dbt run` and `dbt test`, but then you rely on some complex and fragile logic, and lose the ability for tests to be directly tied to a successful or failed model build.   You are testing after the run is done instead.. 

https://github.com/dbt-labs/dbt-core/blob/29b83598e3530e99a441e4b6de51f9f9dace781f/core/dbt/task/test.py#L126

**Comment by jtcohen6** [comment]
Hey @will-sargent-dbtlabs - I think this is a known feature request:
- #5766 

Please add an upvote/comment there (or send us a private message if there's more customer-specific context worth sharing).

**Comment by will-sargent-dbtlabs** [comment]
Thanks @jtcohen6 I agree, that's definitely the same thing. The title of the issue didn't give it away to me initially :) Commented. Thanks!
