### ISSUE TITLE
[Bug] Unit tests fail when input  contain reserved-word-named columns

### ISSUE THREAD

**Issue by mpatek** [dbt-labs/dbt-core#10112]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In BigQuery:

Supposing an input table with a reserved-word-named column like:

```
-- stg
SELECT id, loaded_at, `from` FROM {{ source('some', source') }}
```

And a downstream table like:

```
-- some_model
SELECT id, loaded_at FROM {{ ref('stg') }}
qualify row_number() over (partition by id order by loaded_at desc) = 1
```

And a unit test like:
```
version: 2

unit_tests:
  - name: test__some_model
    model: some_model
    given:
      - input: ref('stg')
        rows:
          - {id: "a", loaded_at: "2024-01-01"}
          - {id: "a", loaded_at: "2024-01-02"}
          - {id: "a", loaded_at: "2024-01-02"}
    expect:
      rows:
        - {id: "a", loaded_at: "2024-01-02"}
```

If I try `dbt test --select test_type:unit`

I get: `Syntax error: Unexpected keyword FROM`

### Expected Behavior

Expect tests to pass without errors.

### Steps To Reproduce

1. Create input model with keyword-named column (e.g. `from`)
2. Create output model that selects from the input model (not necessarily including the reserved-word-named column).
3. Add unit test that puts data into input model and runs expectations on output model
4. Run unit test

### Environment

```markdown
- OS: macOS Monterey
- Python: 3.11.7
- dbt: 1.8.0-rc1 w/ bigquery 1.8.0b2
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reporting this @mpatek !

When I ran your example, I got the same error as you.

When I looked at the compiled SQL (in `target/compiled/my_project/models/_unit.yml/models/test__some_model.sql` for me because my dbt project name in `dbt_project.yml` is "my_project"), it looked like this:

```sql
with __dbt__cte__stg as (

-- Fixture for stg
select safe_cast('''a''' as STRING) as id, safe_cast('''2024-01-01''' as DATETIME) as loaded_at, safe_cast(null as INT64) as from
union all
select safe_cast('''a''' as STRING) as id, safe_cast('''2024-01-02''' as DATETIME) as loaded_at, safe_cast(null as INT64) as from
union all
select safe_cast('''a''' as STRING) as id, safe_cast('''2024-01-02''' as DATETIME) as loaded_at, safe_cast(null as INT64) as from
) -- some_model
SELECT id, loaded_at FROM __dbt__cte__stg
qualify row_number() over (partition by id order by loaded_at desc) = 1
```

And when I copy that compiled output to an analyses file, I get the same error:

```shell
cp target/compiled/my_project/models/_unit.yml/models/test__some_model.sql analyses             
dbt show -s analyses/test__some_model.sql 
```

But if I modify that analysis file to have backticks around all the column names, then it can run successfully:

```sql
with __dbt__cte__stg as (

-- Fixture for stg
select safe_cast('''a''' as STRING) as `id`, safe_cast('''2024-01-01''' as DATETIME) as `loaded_at`, safe_cast(null as INT64) as `from`
union all
select safe_cast('''a''' as STRING) as `id`, safe_cast('''2024-01-02''' as DATETIME) as `loaded_at`, safe_cast(null as INT64) as `from`
union all
select safe_cast('''a''' as STRING) as `id`, safe_cast('''2024-01-02''' as DATETIME) as `loaded_at`, safe_cast(null as INT64) as `from`
) -- some_model
SELECT id, loaded_at FROM __dbt__cte__stg
qualify row_number() over (partition by id order by loaded_at desc) = 1
```

Output
```
21:52:49  Previewing node 'test__some_model':
| id |           loaded_at |
| -- | ------------------- |
| a  | 2024-01-02 00:00:00 |
```

So I'm wondering if we just need to apply [`quoted`](https://github.com/dbt-labs/dbt-adapters/blob/154ca610f67906b0affea9a1e85d29126721cafd/dbt/adapters/base/column.py#L37) in just the right place.

**Comment by jtcohen6** [comment]
@dbeatty10 I think you're right, and I think the right spots might be [here](https://github.com/dbt-labs/dbt-adapters/blob/d831caa33bc1a31d1162f1d1b3ccd6caaec08fd5/dbt/include/global_project/macros/unit_test_sql/get_fixture_sql.sql#L31) and [here](https://github.com/dbt-labs/dbt-adapters/blob/d831caa33bc1a31d1162f1d1b3ccd6caaec08fd5/dbt/include/global_project/macros/unit_test_sql/get_fixture_sql.sql#L40):
```
{%- for column_name, column_value in ... %} {{ column_value }} as {{ adapter.quote(column_name) }}{% if not loop.last -%},{%- endif %}

**Comment by dbeatty10** [comment]
<details>
<summary>

### Minimal reprex
</summary>

``

`models/my_model.sql`

```sql
select 1 as {{ adapter.quote("from") }}
```

`models/_unit.yml`

```yaml
unit_tests:

  - name: test___my___model
    model: my_model
    given: []
    expect:
      rows:
        - {from: 1}
```

Run the model and its tests:
```shell
dbt build -s my_model
```

</details>

### Implementation prototype

We'd probably choose to actually implement it differently than this, but here is a prototype that worked with the reprex above:
- https://github.com/dbt-labs/dbt-adapters/pull/202

**Comment by mpatek** [comment]
Closing, since this should proabably be a `dbt-adapter` issue: https://github.com/dbt-labs/dbt-adapters/issues/205
