### ISSUE TITLE
[Feature] Support deferral of semantic models

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#10166]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We would want to generate the semantic manifest with deferral resolved to make sure the semantic model will point to the deferred node.
This would ensure a consistent experience of developing dbt & semantic model

**Comment by ChenyuLInx** [comment]
I think we need to update `merge_from_artifact` function to make sure semantic model's node relation gets updated?
Or should we include defer relation inside?
Sort of a tradeoff of whether dbt will resolve the deferral or metric flow.

**Comment by ChenyuLInx** [comment]
We also could just include the deferal database /schema for each model inside the semantic manifest?

**Comment by jtcohen6** [comment]
(tbt #8135!)

> We also could just include the deferal database /schema for each model inside the semantic manifest?

a.k.a. the `defer_relation`! However, the `defer_relation` is added at runtime, not at parsing time. I had a proposal to change this, but I undid it because it needs a bit more consideration of potential downstream impact (e.g. partial parsing) before we implement: https://github.com/dbt-labs/dbt-core/pull/9199/commits/6b63e31a4eee3272409eae0417cbad7d94b5384a

**Comment by ChenyuLInx** [comment]
I am thinking maybe during runtime we overwrite the original semantic manifest and add this. Need to think a bit more about how to better encapsulate this.
