### ISSUE TITLE
Should column level `meta` modifications be considered `state:modified`?

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#10189]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

As title, changes to column level `meta` configs aren't considered `state:modified`.

### Expected Behavior

Changes to column level `meta` configs should be considered `state:modified`.

### Steps To Reproduce

1. Setup dbt project.

```yml
# dbt_project.yml
name: my_dbt_project
profile: all
config-version: 2
version: "1.0.0"

models:
 my_dbt_project:
   +materialized: table
```

```yml
# models/schema.yml
version: 2
models:
  - name: foo
    config:
      meta:
        k: v
    columns:
      - name: id
        meta:
         k: v
  - name: bar
    config:
      meta:
        k: v 
    columns:
      - name: id
        meta:
         k: v
```

```sql
-- models/foo.sql
select 1 id

-- models/bar.sql
select 1 id
```

2. Initial build and state storing.

```sh
$ dbt build && mv target target_old
00:00:49  Running with dbt=1.7.14
00:00:49  Registered adapter: postgres=1.7.14
00:00:49  Found 2 models, 0 sources, 0 exposures, 0 metrics, 402 macros, 0 groups, 0 semantic models
00:00:49  
00:00:49  Concurrency: 4 threads (target='dev')
00:00:49  
00:00:49  1 of 2 START sql table model public.bar ........................................ [RUN]
00:00:49  2 of 2 START sql table model public.foo ........................................ [RUN]
00:00:49  1 of 2 OK created sql table model public.bar ................................... [SELECT 1 in 0.08s]
00:00:49  2 of 2 OK created sql table model public.foo ................................... [SELECT 1 in 0.08s]
00:00:49  
00:00:49  Finished running 2 table models in 0 hours 0 minutes and 0.17 seconds (0.17s).
00:00:49  
00:00:49  Completed successfully
00:00:49  
00:00:49  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```

3. Modify `schema.yml` file (a model level change on `foo`, and a column level change on `bar`):

```yml
# models/schema.yml
version: 2
models:
  - name: foo
    config:
      meta:
        k: model_level_change
    columns:
      - name: id
        meta:
         k: v
  - name: bar
    config:
      meta:
        k: v 
    columns:
      - name: id
        meta:
         k: column_level_change
```

4. Deferred build:

```sh
$ dbt build -s state:modified --defer --state target_old
00:02:48  Running with dbt=1.7.14
00:02:48  Registered adapter: postgres=1.7.14
00:02:48  Unable to do partial parsing because saved manifest not found. Starting full parse.
00:02:48  Found 2 models, 0 sources, 0 exposures, 0 metrics, 402 macros, 0 groups, 0 semantic models
00:02:48  
00:02:48  Concurrency: 4 threads (target='dev')
00:02:48  
00:02:48  1 of 1 START sql table model public.foo ........................................ [RUN]
00:02:48  1 of 1 OK created sql table model public.foo ................................... [SELECT 1 in 0.06s]
00:02:48  
00:02:48  Finished running 1 table model in 0 hours 0 minutes and 0.15 seconds (0.15s).
00:02:48  
00:02:48  Completed successfully
00:02:48  
00:02:48  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

> `foo` is built but not `bar`.

### Relevant log output

```shell
Shared above.
```

### Environment

```markdown
- OS: macOS
- Python: 3.11.9
- dbt:

Core:
  - installed: 1.7.14
  - latest:    1.8.0  - Update available!

Plugins:
  - postgres:   1.7.14 - Update available!
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

Not 100% sure if this has ever worked - could be FR like https://github.com/dbt-labs/dbt-core/issues/10020

**Comment by karenderer** [comment]
Interesting that this is considered a bug because I wouldn't expect `bar` to be modified (and wouldn't want it to run) if only the meta config is changed. If this becomes the default behavior of `state:modified` I'd like a way of opting out.

**Comment by jeremyyeo** [comment]
> Interesting that this is considered a bug because I wouldn't expect `bar` to be modified (and wouldn't want it to run) if only the meta config is changed. If this becomes the default behavior of `state:modified` I'd like a way of opting out.

Yeah I don't really know for sure if it's a bug or an FR.

**Comment by jtcohen6** [comment]
Confirming - this isn't a bug, it's an opinionated choice we made long long ago that:
- `tags` + `meta` are not considered "modifications" per se, they are metadata updates only
- `description` is a "modification" if and only if `persist_docs` is enabled, otherwise it's only a metadata update
- any other `config` change _is_ a modification, because that config might be used while materializing the model

In retrospect, I think that can lead to situations like this one, where the outcome is technically correct but less unintuitive. Still, this is how it's been for many years.

**Comment by jmkacz** [comment]
This is a bug from our perspective because of the added interaction of the `dbt_snow_mask` package. If we add masking via `meta.masking_policy`, right now, it will not get applied unless we perform a full build.

**Comment by AmplifyPegPeterson** [comment]
> * `tags` + `meta` are not considered "modifications" per se, they are metadata updates only
> * `description` is a "modification" if and only if `persist_docs` is enabled, otherwise it's only a metadata update

In the example, the only change is to add a meta configs, not description change.  So the way dbt is currently functioning is model level meta tags ARE seen as modifications however column level meta tags are not.  It is still unclear why a metadata update at the model level would be considered different than a column level meta update.

**Comment by pyrobat** [comment]
Hi, I'd like to ask that this be re-opened.

We utilize the dbt-databricks adapter which can set column level tags via something like

```
columns:
  - name: my_column
     databricks_tags: {"tag_name": "tag_value"}
```

These column tags are used for ABAC policies on tables managed by dbt throughout our company. Currently, adding (or changing) just the column level `databricks_tags` in a models .yml will not select that model to run via `state:modified`.

This results in situations where what exists in our production databases does not reflect what's in the latest merge to our repo. The changes will be reflected the next time a model is run, however that leaves a potential access gap where differences exist between our dbt code and what's in production until that point.

**Comment by graciegoheen** [comment]
Hi @pyrobat - you're requesting something slightly different. `databricks_tags` is a documented databricks-specific config (it's not nested under `meta`) - docs [here](https://docs.getdbt.com/reference/resource-configs/databricks-configs?version=1.11#configuring-columns).

Can I ask that you open up a new issue for this in the `dbt-databricks` repo? https://github.com/databricks/dbt-databricks

**Comment by graciegoheen** [comment]
> `tags` + `meta` are not considered "modifications" per se, they are metadata updates only

@jtcohen6 I opened an issue for our documentation to make this more clear -> https://github.com/dbt-labs/docs.getdbt.com/issues/8994

One thing we could consider adding in the future is some sort of flag to _opt-in_ to including `tags` and/or `meta` as part of `state:modified`, but I don't think we should change the default.

**Comment by karenderer** [comment]
@graciegoheen Hello, can this be re-opened due to the dbt_snow_mask issue described above?

**Comment by jeremyyeo** [comment]
I think there's renewed interest around `meta` changes triggering "state:modified" https://getdbt.slack.com/archives/C088YCAB6GH/p1783529654769819
