### ISSUE TITLE
[Bug] A new manifest version should be published for dbt 1.9

### ISSUE THREAD

**Issue by mars-lan** [dbt-labs/dbt-core#10188]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Based on https://docs.getdbt.com/reference/artifacts/manifest-json, v12 is reserved for dbt 1.8. However, it seems that dbt 1.9 has started publishing an incompatible v12 manifest JSON schema (https://schemas.getdbt.com/dbt/manifest/v12.json):

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "WritableManifest",
  "properties": {
    "metadata": {
      "type": "object",
      "title": "ManifestMetadata",
      "description": "Metadata about the manifest",
      "properties": {
        "dbt_schema_version": {
          "type": "string"
        },
        "dbt_version": {
          "type": "string",
          "default": "1.9.0a1"
        },
}
``` 

### Expected Behavior

dbt 1.9 should publish to a new v13 manifest JSON schema.

### Steps To Reproduce

Download and inspect https://schemas.getdbt.com/dbt/manifest/v12.json

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @mars-lan !

Looks like this was changed from `1.8.0b3` to `1.9.0a1` in https://github.com/dbt-labs/schemas.getdbt.com/pull/39.

Would it solve the problem you are reporting if `1.9.0a1` was reverted back to `1.8.0b3`?

**Comment by mars-lan** [comment]
Actually never mind. The issue was unrelated to the version. Closing this now.
