### ISSUE TITLE
[Impl] Call adapter.pre_model_hook + adapter.post_model_hook within TestTask

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#10198]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

Before running models, dbt runs an adapter-specified "hook." Note that this is *different* from user-configured model hooks. In `dbt-snowflake`, this is the mechanism we use for calling `use warehouse {snowflake_warehouse}`, and it's what we should also use for custom secondary roles (and other things in the future).

Here's where that happens within RunTask:
https://github.com/dbt-labs/dbt-core/blob/09243d1e5d178c7e3051bc63d33816cafaa4c98b/core/dbt/task/run.py#L285-L291

We want the same thing to happen within `TestTask`, for both data + unit tests:
https://github.com/dbt-labs/dbt-core/blob/09243d1e5d178c7e3051bc63d33816cafaa4c98b/core/dbt/task/test.py#L143-L146
https://github.com/dbt-labs/dbt-core/blob/09243d1e5d178c7e3051bc63d33816cafaa4c98b/core/dbt/task/test.py#L216-L225

This way, unit + data tests can use custom Snowflake warehouses.

### Acceptance criteria

`adapter.pre_model_hook` + `adapter.post_model_hook` are being called within `TestTask` for unit + data tests.

### Suggested Tests

I don't think we're doing a great job of testing that `pre_model_hook` and `post_model_hook` are called today.

Ideas:
- Patch the adapter to define a `pre_model_hook` and `post_model_hook` that logs, and ensure it logs during test execution.
- After https://github.com/dbt-labs/dbt-core/issues/10197 is complete: Add to [the functional tests in `dbt-snowflake` here](https://github.com/dbt-labs/dbt-snowflake/blob/5da6fdbfd0895cf86c49dd2b95d89d3d2a57aa70/tests/functional/warehouse_test/test_warehouses.py#L8) here. A test configured with a `snowflake_warehouse` that does not exist should fail. Today, it doesn't, because it doesn't actually use this config.

### Impact to Other Teams

Impact: Adapters

### Will backports be required?

no

### Context

Original issue:
- https://github.com/dbt-labs/dbt-adapters/issues/212

However, compilation is out of scope. This issue is focused _only_ on adding these hook calls to `TestTask`.

**Comment by adrian-pasek-prv** [comment]
@jtcohen6 @McKnight-42 I'm not sure it resolved the issue with tests using pre/post hooks. When I configure +snowflake_warehouse under tests, it does not seem to take affect. Tests are still being executed with default WH set in the environment.
