### ISSUE TITLE
[Bug] Running `dbt build --resource-type saved_query` on  1.7 throws an uncaught exception

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/dbt-core#10225]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When on dbt 1.7 running `dbt build --resource-type saved_query` returns the following error when the env var `DBT_INCLUDE_SAVED_QUERY` is not set.
```
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-1.7.0-latest/lib/python3.11/site-packages/dbt/cli/main.py", line 220, in build
    results = task.run()
              ^^^^^^^^^^
  File "/venv/dbt-1.7.0-latest/lib/python3.11/site-packages/dbt/task/runnable.py", line 502, in run
    result = self.execute_with_hooks(selected_uids)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-1.7.0-latest/lib/python3.11/site-packages/dbt/task/runnable.py", line 463, in execute_with_hooks
    res = self.execute_nodes()
          ^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-1.7.0-latest/lib/python3.11/site-packages/dbt/task/runnable.py", line 387, in execute_nodes
    self.run_queue(pool)
  File "/venv/dbt-1.7.0-latest/lib/python3.11/site-packages/dbt/task/runnable.py", line 302, in run_queue
    runner = self.get_runner(node)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-1.7.0-latest/lib/python3.11/site-packages/dbt/task/runnable.py", line 189, in get_runner
    return cls(self.config, adapter, node, run_count, num_nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```
Instead of falling over, we should return an user friendly error with instructions on how to resolve the issue.

### Expected Behavior

We should show a more user friendly error for example:
```
Error: Could not run saved queries. The environment variable {env_var} is set to FALSE. Please set this the env var {env_var} to true in your dbt_project.yml, or include the --include-saved-query flag.
```

### Steps To Reproduce

In 1.7 run `dbt build --resource-type saved_query`.

### Environment

```markdown
- OS: Mac
- Python: 3.9.16
- dbt: 1.7
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @Jstein77 🤩 See "reprex" below for a reproducible example.

Question for you: when using dbt v1.7, does it actually need to raise a friendly like the following?

```
Error: Could not run saved queries. The environment variable {env_var} is set to FALSE. Please set this the env var {env_var} to true in your dbt_project.yml, or include the --include-saved-query flag.
```

Or can it just behave the same way as v1.8 and show it as a `NO-OP`?

### Screenshot from v1.8

```shell
dbt build --resource-type saved_query --no-include-saved-query
```

<img width="904" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/8d4a942a-a62b-4f10-91e1-f55bf98092b1">

<details>
<summary>

### Reprex
</summary>

`models/metricflow_time_spine.sql`

```sql
-- https://docs.getdbt.com/docs/build/metricflow-time-spine

{{ config(materialized='table') }}

with days as (

    {{
        dbt.date_spine(
            'day',
            "to_date('2000-01-01', 'YYYY-MM-DD')",
            "to_date('2000-01-05', 'YYYY-MM-DD')"
        )
    }}

),

final as (
    select cast(date_day as date) as date_day
    from days
)

select * from final
```

`models/_properties.yml`

```yaml
metrics:
  - name: my_metric
    label: my_metric
    type: derived
    type_params:
      expr: revenue - cost

saved_queries:
  - name: my_saved_query
    query_params:
      metrics:
        - my_metric
```

This works fine when using dbt-core v1.7:
```shell
dbt build --resource-type saved_query --include-saved-query
```

But either of these throws an error with a Python stacktrace:
```shell
dbt build --resource-type saved_query --no-include-saved-query
dbt build --resource-type saved_query
```

</details>

**Comment by dbeatty10** [comment]
@rightx2 [Exports](https://docs.getdbt.com/docs/use-dbt-semantic-layer/exports) run [saved queries](https://docs.getdbt.com/docs/build/saved-queries) and write their output to a table or view within your data platform. They are part of the [Semantic Layer](https://docs.getdbt.com/docs/use-dbt-semantic-layer/dbt-sl) and require a Team or Enterprise account in dbt Cloud. So they won't do anything with just dbt-core.

Did you notice a bug with saved queries that you are trying to report?

**Comment by dbeatty10** [comment]
@rightx2 There’s no built-in support in dbt-core to create a table using the Semantic Layer and metrics. You'd need to use saved queries and exports which require a Team or Enterprise account in dbt Cloud.
