### ISSUE TITLE
failures in on_run_end cause the process to not return an error code

### ISSUE THREAD

**Issue by HarlanH** [dbt-labs/dbt-core#1024]
### Issue description

`dbt run`, if there is an issue that causes an error in `on-run-end`, does not return a non-zero error code. I think it returns 0 even if the run itself failed.

### Results

I expect that when either of the models return an error, or `on-run-end` has an error, that the error code for the process as a whole should be non-zero.

### System information
The output of `dbt --version`:
```
0.10.2
```

The operating system you're running on: OS X

The python version you're using: `Python 3.6.3 :: Anaconda, Inc.`

### Steps to reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example models, etc are all very helpful here.

1. Have a task in `on-run-end` that fails. For example, try `DROP TABLE asdf`, where `asdf` is a table that a view depends on. I suspect any SQL syntax error will also work.
2. Run dbt, and note that the process returns an error code of 0.
3. Change a model so that it will fail, re-run, and note that both the error code is 0, and the error in the model is not displayed.

**Comment by ayyoubmaulana** [comment]
@HarlanH hello i have the same issue, is this issue already solved ? can you share to me how to handle it ?
