### ISSUE TITLE
[Bug] dbt test --select "source:*" runs model tests if they reference a source

### ISSUE THREAD

**Issue by mkielar** [dbt-labs/dbt-core#10259]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a generic test based on an SQL Query like below:
```sql
    SELECT DISTINCT m.MeterType
      FROM {{ ref('[MASKED]_meters') }} em
      JOIN {{ source('[MASKED]', 'METER') }} AS m ON m.ElementId = em.element_id_[MASKED]
                                                 AND m.MeterId   = em.meter_id_[MASKED]
                                                 AND m.Serial    = em.serial_number
     WHERE em.type     IS NULL
       AND m.MeterType IS NOT NULL
```

The logic behind this is as follows:
1. I have a CSV file, which is turned into a `seed`. That CSV file contains a dictionary that maps drom `MeterType` (from source table) to `type` (in model). 
2. The source column may be `NULL` in which case the model performs no mapping and the `type` value should also be `NULL`.
3. The test verifies two things:
    1. That for any non-NULL value in the source, I have a corresponding mapping defined in the CSV.
    2. That the SQL used to produce the model did the right thing.

Now, when I run `dbt test --select "source:*"`, this test is evaluated (even though it's defined in `model.yml`, not in `sources.yml` and fails with following error:
```
12:43:01    Runtime Error in test [MY TEST NAME] (models/staging/[MASKED]/models.yml)
  404 Not found: Dataset [MASKED_GCP_PROJECT_ID]:[MASKED_MISSING_DATASET] was not found in location europe-west3; reason: notFound, message: Not found: Dataset [MASKED_GCP_PROJECT_ID]:[MASKED_MISSING_DATASET] was not found in location europe-west3

  Location: europe-west3
  Job ID: 65ea71ed-55f7-4ba5-aa70-72865ee0f05d
```

The error is legitimate, because the neither the model nor the dataset which will contain it has been created yet, because `dbt build` was not executed yet.

The real issue is: Why would DBT try to execute that test, when the test is defined on the model, and I explicitely pass `--select "source:*"`?!

### Expected Behavior

When `dbt test --select "source:*"` is invoked, tests defined on models should not run, regardless if they reference sources or not.

### Steps To Reproduce

1. Create a generic test that references a model and a source at the same time.
   ```
   {% test dummy_test(model) %}
     SELECT * FROM ref('my_model') m JOIN source('xyz', 'my_source') s on m.id = s.id
   {% endtest %}
   ```
3. Use that test on the model:
   ```
     models:
        - name: my_model
          tests:
            - dummy_test:
              name: "my_model_dummy_test"
   ```
4. Run `dbt test --select "source:*"` and observe that DBT attempts to run that test, despite the fact it's a *model* test, not *source* test.

### Relevant log output

```shell
12:43:01    Runtime Error in test [MY TEST NAME] (models/staging/[MASKED]/models.yml)
  404 Not found: Dataset [MASKED_GCP_PROJECT_ID]:[MASKED_MISSING_DATASET] was not found in location europe-west3; reason: notFound, message: Not found: Dataset [MASKED_GCP_PROJECT_ID]:[MASKED_MISSING_DATASET] was not found in location europe-west3

  Location: europe-west3
  Job ID: 65ea71ed-55f7-4ba5-aa70-72865ee0f05d
```

### Environment

```markdown
- OS: Fedoraremix on WSL / Windows 11 and Dockerised `python:3.12`
- Python: 3.12
- dbt: 1.8.1 
- dbt-bigquery: 1.8.1
```

### Which database adapter are you using with dbt?

bigquery

**Comment by mkielar** [comment]
Update:
If I create the BigQuery Dataset manually, the error message changes to this:
```
13:16:16    Runtime Error in test [MY TEST NAME] (models/staging/[MASKED]/models.yml)
  404 Not found: Table [MASKED_GCP_PROJECT_ID]:[MASKED_MISSING_DATASET].[MASKED]_meters was not found in location europe-west3; reason: notFound, message: Not found: Table [MASKED_GCP_PROJECT_ID]:[MASKED_MISSING_DATASET].[MASKED]_meters was not found in location europe-west3

  Location: europe-west3
  Job ID: c8a478f2-620d-4587-aec6-33297daadb11
```

So now the table is missing. But the table is the model on which the test is defined, so we have a chicken/egg scenario.

**Comment by dbeatty10** [comment]
Thanks for reaching out @mkielar !

> The real issue is: Why would DBT try to execute that test, when the test is defined on the model, and I explicitely pass `--select "source:*"`?!
> 
> ### Expected Behavior
> 
> When `dbt test --select "source:*"` is invoked, tests defined on models should not run, regardless if they reference sources or not.

Rather than being a bug, this is actually how dbt tests work:
- By default, dbt indirectly selects all tests if they touch _any_ resource you select.

This is because `eager` is the default behavior for ["indirect selection"](https://docs.getdbt.com/reference/global-configs/indirect-selection). You can see a variety of examples for configuring `indirect_selection` [here](https://docs.getdbt.com/reference/node-selection/test-selection-examples?indirect-selection-mode=eager#indirect-selection).

### Your scenario

It sounds like you want to run all tests that _only_ touch sources (and don't touch any other resources like models, seeds, or snapshots).

If so, here's how you can do that:
```shell
dbt test --select "resource_type:source" --indirect-selection cautious
```

Other folks have found the `buildable` option to to useful when trying to build and a test a model at the same time:
```shell
dbt test --select my_model --indirect-selection buildable
```

### Summary

Since this isn't a bug, I'm going to close this issue. But please reach out if the example for the `cautious` option doesn't work as described for some reason.

**Comment by mkielar** [comment]
Hi @dbeatty10, 

thanks for explanation, however I still have an issue with that:
The `--indirect-selection` in both `buildable` and `cautious` modes removes the problematic test when the model doesn't exist. However, **it also removes another test** that is defined on a `source` table, and is based on several other **sources + a single `seed`** - Note that the seed table exists! If I remove the seed from the test, the test is included in both cases (`buildable` and `cautious`). 

I've read the docs in https://docs.getdbt.com/reference/global-configs/indirect-selection and I think I understand the reason, but is there a way to run DBT so that:
1. It would skip a source test if it relies on seed / model that hasn't been built yet?
2. It would include the test if the tables for given seed / model already exist?

TBH, I'm not entirely sure this is a right approach - changing the test behaviour depending on the database contents is not ideal... Still, I'd like to hear your thoughts on this.

Anyway, in case someone else stumbles upon the same issue, this is what I ended up doing in my DBT Pipeline:
1. I'm populating seeds first, as this is not supposed to cause any harm to the final models.
   ```sh
   dbt seed
   ```
3. Then I follow with running tests, and I include seeds so that tests based on sources and seeds would still run. 
   ```sh
   dbt test --select "source:[MASKED_DATASET].*" \
            --select "resource_type:seed" \
            --indirect-selection buildable
   
   # Or, if I want to use `resource_type:test` **and also** narrow down the selection to specific dataset:
   dbt test --select "resource_type:source,source:[MASKED_DATASET].*" \
            --select "resource_type:seed" \
            --indirect-selection buildable
   ```
4. Then I follow with `dbt build`, but only if `dbt test` passes first.
