### ISSUE TITLE
[Feature] Unit tests should support Gherkin table style inputs

### ISSUE THREAD

**Issue by Dikootje** [dbt-labs/dbt-core#10252]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

It would be really nice if it's possible to support input data for unit tests in a Gherkin data table compatible style [See examples](https://github.com/cucumber/cucumber-jvm/tree/main/datatable)

```
| firstName   | lastName | birthDate  |
| Annie M. G. | Schmidt  | 1911-03-20 |
| Roald       | Dahl     | 1916-09-13 |
| Astrid      | Lindgren | 1907-11-14 |
```

### Who will this benefit?

We have business users who have very little tech skills, but do understand the data that goes into and should come out of the models. They already have experience with Gherkin scripts. 

Additional benefit is that this is more readable to humans than json formatted string. Especially when there's a larger amount of columns in the inputs and outputs

**Comment by graciegoheen** [comment]
Hi! Thanks so much for opening.

> Additional benefit is that this is more readable to humans than json formatted string. Especially when there's a larger amount of columns in the inputs and outputs

This was a lot of our motivation on supporting the `format: csv` - have you given that format a try? I'd be curious to hear how you think Gherkin compares to csv. To me, they seem very similar (csv using `,`, Gherkin using `|` as the delimiter between values), and we want to avoid supporting too many / redundant `format`s.

**Comment by Dikootje** [comment]
The csv could work, but it's hardly readable in it's current implementation. Especially as the number of attributes in a model increase the csv gets harder to read. 

This gets hard to read: 
```csv
firstName,lastName,birthDate
Annie M. G.,Schmidt,1911-03-20
Roald,Dahl,1916-09-13
Astrid,Lindgren,1907-11-14
```
Compared to the Gherkin table: 
```
| firstName   | lastName | birthDate  |
| Annie M. G. | Schmidt  | 1911-03-20 |
| Roald       | Dahl     | 1916-09-13 |
| Astrid      | Lindgren | 1907-11-14 |
```
But I agree that csv could work with some minor tweaks. To increase the readability I tried adding whitespace in the hope it would get trimmed. 
```csv
firstName       ,lastName     ,birthDate
Annie M. G.     ,Schmidt      ,1911-03-20
Roald           ,Dahl         ,1916-09-13
Astrid          ,Lindgren     ,1907-11-14
```

If trimming could be added it would prevent adding another input type but increase user friendliness. Perhaps a boolean to switch trimming on/off for cases where trimming is not desired.

**Comment by graciegoheen** [comment]
That makes sense! I have an issue open to improve the readability of csv files here -> https://github.com/dbt-labs/dbt-core/issues/9280

I'll close this issue out in favor of that one :)
