### ISSUE TITLE
[Feature] Add `--fail-if-nothing-selected` (or something similar) 

### ISSUE THREAD

**Issue by dwreeves** [dbt-labs/dbt-core#10266]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Right now, dbt outputs the following if nothing is selected:

```
Nothing to do. Try checking your model configs and model specification args
```

And also returns an exit code of 0.

It would be helpful if there was a way to turn on a flag so that this situation return a non-zero exit code, something like:

```shell
dbt run --select this-doesnt-exist --fail-if-nothing-selected
```

It's unclear to me what the name of this flag should be. There are many reasonable alternatives:

- `--fail-if-nothing-selected`
- `--fail-if-nothing-selected`
- `--fail-if-no-selection`
- `--fail-if-nothing`
- `--exit-non-zero-on-nothing`
- `--exit-non-zero-if-nothing`
- `--exit-non-zero-if-no-selection`

etc.

### Who will this benefit?

Anyone invoking dbt when not having selected any nodes is considered a failure case.

### Are you interested in contributing this feature?

Yes

**Comment by dbeatty10** [comment]
Thanks for proposing this @dwreeves !

Can you share some scenarios where not having selected any nodes is considered a failure case?

**Comment by dwreeves** [comment]
Sure. Let's say I have the following script:

```shell
#!/usr/bin/env bash

set -o errexit

dbt run --select some_model
python process_some_model.py
```

Where `process_some_model.py` is a Python file that does some work with the dbt model.

Now imagine unbeknownst to me, someone deleted `some_model.sql`. Which means `some_model` was not generated as a side-effect of `dbt run`. Despite that, `process_some_model.py` will still run.

In a worst case scenario, this can cause some nasty situations. Imagine the following:

- `some_model.sql` is an SQL query that writes daily important biz related metrics, like for example a list of suspicious user accounts where the query looks like this: `select current_timestamp() as date_added, user_id from {{ ref("algorithm") }} {% if is_incremental %} where user_id not in (select user_id from {{ this }}) {% endif %}`.
- `some_model` was not deleted _as a table_. It still exists in the database, it's only that the file is no longer available.
  - Alternatively, the `config` for this node could be `enabled: False`. I think my proposed flag should cover both cases and not distinguish (that makes things easier though, not harder.)

Now when `process_some_model.py` runs, it selects the latest data from the SQL files, and determines that there are no new suspicious user accounts.

There are lots of ways to prevent this issue, of course. The user didn't have to design the system like this. But, you can see how a flag that does a nonzero exit would probably be the simplest thing for this user:

```shell
#!/usr/bin/env bash

set -o errexit

dbt run --select some_model --fail-if-nothing-selected
python process_some_model.py
```

^ Here, the user is now alerted to the issue. 😄

**Comment by dbeatty10** [comment]
Thanks for sharing that scenario @dwreeves.

Do you have any workarounds you are using currently to handle it?

**Comment by dreeves-battery** [comment]
@dbeatty10 I am not doing anything right now. If a corresponding feature isn't added on dbt's side, I would run dbt inside a subprocess, read the logs, and check for `Nothing to do. Try checking your model configs and model specification args` then have the parent process exit nonzero if that is seen inside the logs.

**Comment by dwreeves** [comment]
@dbeatty10 I am not doing anything right now. If a corresponding feature isn't added on dbt's side, I would run dbt inside a subprocess, read the logs, and check for `Nothing to do. Try checking your model configs and model specification args` then have the parent process exit nonzero if that is seen inside the logs.

**Comment by dbeatty10** [comment]
In general, we prefer to give a lot of care and consideration before adding new flags. In this case, reading the logs and checking for "Nothing to do" seems like the way to go.

I'm going to close this as "not planned" since this doesn't strike me as a common scenario. But if others are looking for this behavior, please 👍 or add a comment and we can reconsider down the road.

**Comment by dwreeves** [comment]
Fair enough, thanks for taking the time to review!
