### ISSUE TITLE
[Feature] Add a head command to see the first rows of a table

### ISSUE THREAD

**Issue by DrAlexSanz** [dbt-labs/dbt-core#10265]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I think this is the correct place to write this request, please correct me if it's not.

A new dbt command (perhaps dbt head --select MY_MODEL) that would show the first 5 or 10 records in a model. Similar as the .head() method in pandas.

This new command would be just running something like: select * from MY_MODEL limit 5

When I'm developing a complex model, I do it step by step. I do the first part, and then I just want to see that the joins and the logic worked, so I have to run a select * from MY_MODEL limit 5. It would be very convenient if right after the dbt run command, to create my model, I can also just execute a dbt head or something along these lines. Additionally, if you just get access to a new table/view, you can have a quick look with dbt.

I don't know if you want to allow passing several models to this proposed command, the output may become a bit messy.

I also don't know if you want to allow the user to choose how many records they want to see. I just put 5 as an example.

### Describe alternatives you've considered

* Running the select * from MY_MODEL limit 5 myself, which is what I do currently.
* Creating a view on a model, but you need to change it for each model that you create and then do a select * on this second view, which defeats the purpose.
* Creating a view using a macro to do the above. It looks quite cumbersome to me.

### Who will this benefit?

Anyone that wants to check that a model is working properly or exploring new data.

### Are you interested in contributing this feature?

I probably can't contribute, I didn't understand anything in the source code.

**Comment by dbeatty10** [comment]
Have you tried out the [`dbt show` command](https://docs.getdbt.com/reference/commands/show)?

There's a couple ways to use it:

1) Execute the most recent logic in your source code:

```shell
dbt show --select model_name
```

or

2) Query the data as it currently exists in your database:

```
dbt show --inline "select * from {{ ref('model_name') }}"
```

**Comment by DrAlexSanz** [comment]
I was not aware of this command because I use an older version of dbt-core, but it does exactly what I want. Thank you for letting me know, I'll update to the latest version.

Sorry for the inconvenience.

**Comment by dbeatty10** [comment]
No problem @DrAlexSanz -- we'd love to hear any feedback after you give it a try.

**Comment by DrAlexSanz** [comment]
@dbeatty10 the command works great for my use case, specifically with the inline option.

**Comment by dbeatty10** [comment]
@DrAlexSanz awesome that it is working for your use case!

In terms of the inline option, we're considering some more ergonomic ways to specify `--inline "select * from {{ ref('that_model') }}` within https://github.com/dbt-labs/dbt-core/issues/7391
