### ISSUE TITLE
[Bug] Test description empty in manifest.json

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/dbt-core#10272]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have defined a custom test and I have documented the test in YML like this: 
```yml
tests:
  - name: my_custom_test
    description: >
      Some business description about my custom test
    meta:
      owner: '@silja.mardla'
```
However, the description does not show up in the dbt-genarted doc site. 
So I searched the `manifest.json` for this test and it looks like the description and meta are empty in the manifest. I've shortened it a bit, but this is how the relevant parts look like:

```json
"test.common.my_custom_test":{
   "database":"XXX",
   "schema":"dbt_test__audit",
   "name":"my_custom_test",
   "resource_type":"test",
   "package_name":"common",
   "path":"my_custom_test.sql",
   "original_file_path":"tests/my_custom_test.sql",
   "unique_id":"test.common.my_custom_test",

   ...   

      "meta":{
         
      },
      "group":null,
      "materialized":"test",
      "severity":"ERROR",
      "store_failures":null,
      "store_failures_as":null,
      "where":null,
      "limit":null,
      "fail_calc":"count(*)",
      "warn_if":"!= 0",
      "error_if":"!= 0"
   },
   "tags":[
      
   ],
   "description":"",
   "columns":{
      
   },
   "meta":{
      
   },
   "group":null,
   "docs":{
      "show":true,
      "node_color":null
   },
  ...
```

### Expected Behavior

Tests can be documented like any other dbt asset. 

### Steps To Reproduce

Add test description and meta in a YML file and check the manifest to see if the description is there. 

### Environment

```markdown
- OS: MacOS
- Python:
- dbt: 1.7.9
```

### Which database adapter are you using with dbt?

spark

**Comment by dbeatty10** [comment]
Thanks for reaching out about this @siljamardla !

We've already got some similar issues open, so I'm going to close this one as a dupe. Here are the pre-existing issues:
- https://github.com/dbt-labs/dbt-core/issues/2578
- https://github.com/dbt-labs/dbt-core/issues/9005
