### ISSUE TITLE
Use, and extend as necessary, happy path fixture for `tests/functional/artifacts/test_artifacts.py`

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#10286]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description
This ticket should build on the work from #10256. Specifically we want to update the tests in `tests/functional/artifacts/test_artifacts.py` to use the the happy path project fixture where relevant. This may require adding to the happy path fixture.

### Acceptance criteria
- We use the happy path project fixture for tests in `tests/functional/artifacts/test_artifacts.py`

**Comment by ChenyuLInx** [comment]
After looking into this test, it is fairly involved with the models being executed. We decided to not convert it to using happy path fixture.
