### ISSUE TITLE
[Bug] Unhelpful exception occurs with yaml file in list format

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#10284]
### Description

If dbt reads a yaml file in list format such as: 
```
- name: my_name
- name: alt_name
```

then an exception occurs:

  File "/.../core/dbt/parser/schemas.py", line 123, in yaml_from_file
    for source in contents.get("sources", []):

The code in parser/schemas.py is expecting a dictionary and doesn't handle a list in a user-friendly way.

### Acceptance Criteria

Instead of unfriendly exception, we issue a better error message.

**Comment by MichelleArk** [comment]
I've definitely ran into this before and spent too long debugging. Thank you! ❤️
