### ISSUE TITLE
[Bug] Disabled generic tests appear in manifest.nodes

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#10299]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When you have a generic test for a model, it remains in the manifest when disabled.  Other node types are only in the disabled dictionary.

### Expected Behavior

- The generic test is not in in manifest.nodes
- The generic test is in the disabled dict

### Steps To Reproduce

my_model.sql
```
select 1 as id, 'orange' as color, false as is_primary_color
```

schema.yml
```
models:
  - name: column_removed_model
    columns:
      - name: id
        tests:
          - unique
```

1.  `dbt compile` and see the model and the test in manifest.nodes, `disabled` dictionary is empty
2.  delete `my_model.sql`
3.  `dbt compile` and see the test in manifest.nodes but not disabled dictionary
_or_
1.  `dbt compile` and see the model and the test in manifest.nodes, `disabled` dictionary is empty
2.  add the `enabled: false` config `my_model`
3.  `dbt compile` and see the test in manifest.nodes but not disabled dictionary and the model in the disabled dict but not in manifest.nodes

### Relevant log output

```shell
none
```

### Environment

```markdown
- dbt: 1.9a1
```

### Additional Context

TODO: Does this also apply to singular tests?

This may require some tests that verify the number of nodes in the results equals a specific number.  This is an unknown that may add some time to the fix.

More context for how it works now:
In compilation.py we specifically check for disabled tests in the "nodes" dictionary. However, when we do "cleanup_disabled" anything that's disabled ought to be moved to the disabled dictionary.

**Comment by gshank** [comment]
Tests for a disabled model aren't explicitly marked as disabled are they?  We move everything in the "nodes" dictionary that's marked disabled into the "disabled" dictionary as a post-parsing step.
