### ISSUE TITLE
[Bug] Environment variables take precedence over CLI flags that appear after the subcommand

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#10304]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

[As requested by](https://dbt-labs.slack.com/archives/C05CJT5MJF2/p1718202630252599?thread_ts=1718034218.496729&cid=C05CJT5MJF2) @graciegoheen 

[The docs say](https://docs.getdbt.com/reference/global-configs/about-global-configs#setting-flags)
>The most specific setting “wins.” If you set the same flag in all three places, the CLI option will take precedence, followed by the environment variable, and finally, the value in dbt_project.yml. If you set the flag in none of those places, it will use the default value defined within dbt.

But the observed precedence distinguishes between flags before the subcommand vs. after the subcommand

### Acceptance criteria

1. CLI flags take precedence over environment variables regardless if they appear before the subcommand vs. after the subcommand.
2. These commands give identical output:
    ```shell
    DBT_QUIET=0 dbt --quiet list
    DBT_QUIET=0 dbt list --quiet
    ```

### Steps To Reproduce

See Doug's comment below

**Comment by dbeatty10** [comment]
Thanks for reporting this @joellabes 🤩

See below for a simple way to reproduce your report -- even if there's no resources defined in a project.

### Reprex

```shell
DBT_QUIET=0 dbt --quiet list
DBT_QUIET=0 dbt list --quiet
```

```
(dbt_1.8) $ DBT_QUIET=0 dbt --quiet list

(dbt_1.8) $ DBT_QUIET=0 dbt list --quiet

13:44:44  Running with dbt=1.8.1
13:44:44  Registered adapter: duckdb=1.8.1
13:44:44  No nodes selected!
```

Woah! Different output 🤯

### Observed precedence vs. documented precendece

Our documented [order of precedence](https://docs.getdbt.com/reference/global-configs/about-global-configs#setting-flags) is:

1. CLI flag
1. Environment variable
1. Flags in `dbt_project.yml`
1. Default

❌  But the _observed_ precedence distinguishes between flags **before** the subcommand vs. **after** the subcommand:

1. CLI flag _before_ subcommand
1. Environment variable
1. CLI flag _after_ subcommand 👈
1. Flags in `dbt_project.yml`
1. Default

### Affected versions

The reprex above gives the same result for 1.7 and 1.8. Although this example won't work on 1.6 and 1.5, I'd guess those versions are affected as well.

**Comment by dbeatty10** [comment]
### Acceptance criteria

1. CLI flags take precedence over environment variables regardless if they appear before the subcommand vs. after the subcommand.
2. These commands give identical output:
    ```shell
    DBT_QUIET=0 dbt --quiet list
    DBT_QUIET=0 dbt list --quiet
    ```

**Comment by graciegoheen** [comment]
Just to be clear - sounds like it's **not** actually related to whether or not you set the environment variable inline (i.e. `$ SOME_ENV_VAR=value dbt run`) but actually about whether you place the flag before of after the subcommand?

**Comment by dbeatty10** [comment]
Correct @graciegoheen -- I tested out "inline" environment variables vs. exporting environment variables, and they both behaved the same. But when I moved the CLI flag either before or after the subcommand, then I saw the precedence change.

**Comment by dbeatty10** [comment]
### Brief history

The dbt CLI started using the `click` library starting in v1.5 (replacing `argparse`). At this time, [certain flags](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.5#behavior-changes) needed to be passed _before_ the subcommand and other flags that needed to passed after. Additionally, some flags played musical chairs between 1.4 and 1.5. Confusing for end users! 🤯

Then we introduced support supporting flags in any order, either before or after [[1]](https://github.com/dbt-labs/dbt-core/issues/6497) [[2]](https://github.com/dbt-labs/dbt-core/pull/8670). This was released in [dbt-core 1.7.0](https://github.com/dbt-labs/dbt-core/blob/1.7.latest/CHANGELOG.md#dbt-core-170---november-02-2023) and backported to [1.5](https://github.com/dbt-labs/dbt-core/pull/8734) and [1.6](https://github.com/dbt-labs/dbt-core/pull/8732). ✨

Finally, we updated our [CLI documentation](https://docs.getdbt.com/reference/global-configs/command-line-options) to specify that flags should be passed _after_ subcommands. Passing them _before_ is considered legacy functionality that may be removed in the future [[3]](https://github.com/dbt-labs/docs.getdbt.com/issues/4041) [[4]](https://github.com/dbt-labs/docs.getdbt.com/pull/4191).

**Comment by graciegoheen** [comment]
Thanks for that information @dbeatty10 - if this is for legacy behavior, I'm not sure we should spend the effort fixing this

**Comment by dbeatty10** [comment]
It's actually the opposite!

What we've described as legacy behavior is working as expected. But what we've said that people _should_ do is **not** working as expected.
