### ISSUE TITLE
[Investigation] Explore options for providing upgrade or migration paths (for snapshots)

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#10325]
### Description

As we attempt to make additional features backward compatible, there will be situations (several currently known in the snapshot initiative) where we will want users to run upgrade or migration scripts. These may consist of altering tables or modifying other files.

We should think through how we can provide this functionality in a way that works well for both dbt Core OSS and dbt Cloud users.

### Acceptance Criteria

We've identified the path forward and can create tickets to implement the necessary infrastructure.

**Comment by graciegoheen** [comment]
- throw **warning** in CI if config has changed
    - could upgrade these to errors WARN_ERROR_OPTIONS
- provide package with macros to run via run-operation for common migrations
- rely on user to handle migration however they want to (create a new snapshot, run migration script, etc.)
