### ISSUE TITLE
[Feature] Better incremental test with full-expect

### ISSUE THREAD

**Issue by DamienBoue** [dbt-labs/dbt-core#10321]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When we use incremental tests we are not able to test if the merge happen correctly.

Ex:
- I have 2 elements already calculated, A and B
- I need to add one element C and to modify the old element A
- I want to test that my incremental test has only 3 elements, A B and C, with B that has been modified and not duplicated

One solution would be to let us test a `full-expect` that can test the integrality of the data present after the increment.

This could be written as follow:
```
expect:
  full_mode: true
  rows:
    - { all the rows }
```

This would permit us to have non regression test on which someone break the unique key where the merge is done.

### Who will this benefit?

Everyone who intent to make non regression tests in the application

**Comment by dbeatty10** [comment]
Thanks for reaching out @DamienBoue !

This type of functionality for incremental models is already on our radar in https://github.com/dbt-labs/dbt-core/issues/8664, and I'm going to close this one as a duplicate. That one is currently blocked on https://github.com/dbt-labs/dbt-core/issues/8499.

If you have any ideas or feedback, we'd welcome your participation in https://github.com/dbt-labs/dbt-core/issues/8664.
