### ISSUE TITLE
How to read from db1 and write to db2

### ISSUE THREAD

**Issue by han8435762** [dbt-labs/dbt-core#10339]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

db1: pgsql
db2: duckdb

read data from db1,write to db2

**Comment by han8435762** [comment]
I tried to use the source module to bring in the pgsql table
and then write to the default duckdb database
but it gives me an error
I've checked all the documentation, asked ChatGPT, but I can't find an answer.

**Comment by b-per** [comment]
dbt doesn't allow to read from a data warehouse and write to another one.

But, in your situation, DuckDB itself can read from Postgres. There are examples of what you are after in the dbt Slack Community (example [here](https://getdbt.slack.com/archives/C039D1J1LA2/p1718616965224109)) leveraging the [`attach` feature of dbt-duckdb](https://github.com/duckdb/dbt-duckdb#attaching-additional-databases)
