### ISSUE TITLE
issue template for docs.getdbt.com should disambiguate internal docs like CONTRIBUTING and ARCHITECHTURE

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-core#10385]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

#10384 exposed a shortcoming of our current New Issue guidance. There's an entry for "Documentation" with the descritption:

> Problems and issues with dbt documentation

Clicking it redirects you to create a new issue on the docs.getdbt.com repo.

However, in this instance, @farmanp actually wanted to modify a dbt-core internal document: `ARCHITECTURE.md`.

This is how things are currently configured

https://github.com/dbt-labs/dbt-core/blob/c215697a02d7c452c64d4d66f7ba77cf6f2181b6/.github/ISSUE_TEMPLATE/config.yml#L2-L5

<img width="743" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/8158673/b6f98cff-a617-48cb-8a0e-b1071218ce70">

### Expected Behavior

~~Perhaps we modify the link description to say something like~~

> ~~Problems and issues with dbt documentation hosted on `docs.getdbt.com`. Issues with `.md` that live in this repo (`README`, `CONTRIBUTING`, `ARCHITECTURE`) should be opened with `bugs` label~~

Actually I propose a new template option: "code docs" (working title). Issues created with this template would have a specific label applied and the description would say something like:

> Issues with Markdown files that live in this repo (`README`, `CONTRIBUTING`, `ARCHITECTURE`)

#10386 would be a great candidate for this new designation

### Steps To Reproduce

see above

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by mirnawong1** [comment]
@dataders i think your proposal for a new template is spot on! however, i'd also propose updating the existing template to state or specify it's related to docs.getdbt.com (e.g. what you said above:)

Problems and issues with dbt product documentation hosted on docs.getdbt.com. Issues with .md that live in this repo (README, CONTRIBUTING, ARCHITECTURE) should be opened using the "code docs" template.
