### ISSUE TITLE
[Feature] Singular tests in folder structure / support `.test.sql` extension

### ISSUE THREAD

**Issue by d1manson** [dbt-labs/dbt-core#10399]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently singular tests have to go into a specific top level folder, from what i can tell [in the docs](https://docs.getdbt.com/reference/project-configs/test-paths), and from trying. It would be nice if we could put tests alongside implementation, either in a `tests` subdirectory or using `.test.sql` file extension. Co-locating tests and implementation works well in other (non sql) development contexts, and I think it would work well here too.

Why? This makes tests a lot more visible when developing, which means it's easier to understand what kinds of assumptions are explicitly tested and should have the opposite of the "[broken window effect](https://en.wikipedia.org/wiki/Broken_windows_theory)", i.e. if people see lots of tests in the course of other implementation work they are doing they are more likely to consider adding additional tests themselves.

Right now, I find generic tests to be great because: (a) you get a 'clean assertion' statement without requiring readers to wade through implementation guff; and (b) you can see it alongside all the other yaml defining the given model (including other tests). In principle any test could be made generic, but sometimes that feels like an over complication, but it would be nice to try and capture some of (a) and (b) for the singular tests...

So, in addition to the file structure suggestion, perhaps there's also a case for having generic tests be referenced in the yaml on a given model with a description, (and rely on [project evaluator](https://dbt-labs.github.io/dbt-project-evaluator/latest/) checking that this is being used appropriately, perhaps).

**Comment by dbeatty10** [comment]
Thanks for reaching out @d1manson !

While recognizing some of the benefits of co-locating tests very closely with the associated transformation code, we aren't planning to introduce new conventions for subfolder structure or filename extension for [singular data tests](https://docs.getdbt.com/docs/build/data-tests#singular-data-tests). That way, the implementation of dbt can stay as simple and focused as possible.

We have multiple mechanisms quickly show all the tests associated with a particular model. Namely, the [dbt documentation website](https://docs.getdbt.com/docs/build/documentation#navigating-the-documentation-site) or [test_type](https://docs.getdbt.com/reference/node-selection/methods#the-test_type-method) or [`resource_type`](https://docs.getdbt.com/reference/node-selection/methods#the-resource_type-method) selection methods. So we'd recommend using those to get a wholistic view of the testing applied to a particular model.
