### ISSUE TITLE
is_incremental() macro returns false

### ISSUE THREAD

**Issue by jschintz-nytimes** [dbt-labs/dbt-core#10396]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

is_incrmental() macro returns False
![image](https://github.com/dbt-labs/dbt-core/assets/167584907/24f13519-b432-4ac8-9b0d-6aec2adc38c9)

### Expected Behavior

is_incremental() should return true

### Steps To Reproduce

![image](https://github.com/dbt-labs/dbt-core/assets/167584907/3c573fbb-0283-40a3-b318-04a3d1e93f06)

### Environment

```markdown
- OS: dbt-cloud
- Python:
- dbt: latest version
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Hey @jschintz-nytimes 👋 

I saw you just closed this, so I'm assuming that not [all of the following](https://docs.getdbt.com/docs/build/incremental-models#understand-the-is_incremental-macro) held true:

- The model must already exist in the database
- The destination table already exists in the database
- The `full-refresh` flag _is not_ passed
- The running model is configured with `materialized='incremental'`
