### ISSUE TITLE
[Feature] Store dbt commands on database for audit log

### ISSUE THREAD

**Issue by aBBDnGus** [dbt-labs/dbt-core#10401]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We have multiple developers creating dbt models in one datawarehouse. If one developer runs a command like `dbt run ... --target production`, this can change the models and is hard to track for the others.
It would be nice to store all executed dbt commands in a table of the respective data, including timestamp and user. Then, all other developers can understand which commands were executed.
The logging to database could be enabled in the `dbt_project.yml`

### Describe alternatives you've considered

* We have logs for all dbt commands that are executed from the server. But they do not cover the commands that someone executes on a local machine.
* The alternative is to enable database logs to understand all database requests. But sometimes it is hard to understand, where all these database queries come from. It would be easier to see the corresponding dbt command.

### Who will this benefit?

Teams with multiple developers that want some kind of dbt audit log.

**Comment by dbeatty10** [comment]
Thanks for reaching out @aBBDnGus !

Storing logs in a database table is out of scope for dbt-core, so I'm closing this as "not planned".

Rather, this type of functionality is available via the [audit log for dbt Cloud Enterprise](https://docs.getdbt.com/docs/cloud/manage-access/audit-log) or the [dbt Package Hub ecosystem](https://hub.getdbt.com/) (like [`dbt_artifacts`](https://github.com/brooklyn-data/dbt_artifacts)).
