### ISSUE TITLE
[Bug] `--state` flag is not being prioritized over `$DBT_STATE` environment variable

### ISSUE THREAD

**Issue by tweavers** [dbt-labs/dbt-core#10413]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`1.8.3` is not properly setting the `--state` flag if $DBT_STATE has already been set. We ran into this issue when trying to run `dbt ls --select result:success --state target --resource-type model`

I added debugging to [state.py](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/contracts/state.py#L23) to get hte following output. In both examples we have $DBT_STATE set.

### dbt 1.7.14
```
$DBT_STATE: ../docs/dbt-docs
state_path:  target
```

### dbt 1.8.3
```
$DBT_STATE: ../docs/dbt-docs
state_path:  ../docs/dbt-docs
```

### Expected Behavior

`--state` directory should be prioritized over the `$DBT_STATE` environment variable

### Steps To Reproduce

1. Set $DBT_STATE to some arbitrary path that is not `./target`
2. Run any `dbt build` command
3. Run `dbt ls --select result:success --state target`
4. Check the `state_path` variable that is set in `contracts/state.py`

### Environment

```markdown
- OS: MacOS Sonoma 14.5
- Python: Python 3.10.3
- dbt: 1.8.3
```

### Which database adapter are you using with dbt?
Postgres -- `v1.8.2`

_No response_

**Comment by dbeatty10** [comment]
Thanks for raising this issue @tweavers!

This looks the same as https://github.com/dbt-labs/dbt-core/issues/10304, so I'm going to close this one as a duplicate.

### Workaround

In the meantime, the workaround is to add the `--state` flag before the `ls` sub-command like this:
```shell
dbt --state target ls --select result:success
```

Could you let me know if that workaround doesn't behave correctly?

**Comment by tweavers** [comment]
Thanks @dbeatty10 !
