### ISSUE TITLE
[Bug] Cloud CLI --select not working as expected

### ISSUE THREAD

**Issue by jerelehtinen** [dbt-labs/dbt-core#10412]
### Is this a new bug in dbt-core?

- [ ] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hi! 

I'm not sure where to report cloud cli related bugs, so I'm reaching out this way. 

I've noticed that using --select in cli doesn't work if you have list of models. So for example this works:

`dbt list --select +model+`

But this gives error:

`dbt list --select model1 model2`

> Error: unknown argument "model2" for "dbt list"

And if I copy-paste the same command to dbt cloud it works.

Not super urgent for me but figured it's best to report. Also, sorry for reaching out this way - wasn't sure where to list possible cli bugs.

### Expected Behavior

Expected behaviour is that --select clauses work similarly regardless if you are using them from dbt cloud or using cloud cli.

### Steps To Reproduce

1. Run any dbt command with list of models selected: 
`--select model1 model2`
2. Gives you error
3. The same command is working in dbt cloud

### Environment

```markdown
- OS: MacOs Sonoma 14.5
- Python: 3.9.6
- dbt Cloud CLI: 0.38.4
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reporting this @jerelehtinen !

We're using dbt Community Slack for bug reports for the dbt Cloud CLI -- would you mind starting a thread [here](https://getdbt.slack.com/archives/C03SAHKKG2Z) instead?

In the meantime, I'm closing this issue in favor of that (future!) Slack thread since it isn't specifically related to dbt-core.

**Comment by jerelehtinen** [comment]
Will do, thanks for pointing me to right direction!
