### ISSUE TITLE
[Feature] Dynamic model column properties; specifically for contract definition

### ISSUE THREAD

**Issue by GKTheOne** [dbt-labs/dbt-core#10417]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Within a model's template (or called macro) I would like to update `model.columns` to add column properties to the model and have them used in the model contract.

eg,
I have a macro (from a package) `land_from_source` to do a transformation which takes a json/variant column from a source table and flattens it into columns.
It also adds some internal/common columns to the final model, eg, `_landed_timestamp` which defaults to the current timestamp.
To avoid surprises I add columns to the model properties that I expect to come from the source data and set the model contract to enforced.
The contract enforcement fails, and I get a message about the internal/common columns added by the macro.
Since there is a lot of tables to be processed, I don't really want to add the internal/common columns to each model; especially if these columns are subject to (name/type/etc) changes.
Instead I'd rather the macro control the contract expectation by modifying the model columns directly.

```
{%- macro land_from_source(src_relation) -%}
{{- config(contract={'enforced':true}) -}}
{%- set LANDED_TIMESTAMP_NAME = var('landed_timestamp_name') -%}
{%- set LANDED_TIMESTAMP_TYPE = var('landed_timestamp_type') -%}
{%- do model.columns.update({
    LANDED_TIMESTAMP_NAME: {
        'name': LANDED_TIMESTAMP_NAME,
        'data_type': LANDED_TIMESTAMP_TYPE,
    }
}) -%}
{#- -- also other column details such as description, meta, tags, etc -#}
select
    -- actual sql code needed to select from source,
    CURRENT_TIMESTAMP() AS {{ LANDED_TIMESTAMP_NAME }}
from {{ src_relation }}
{%- endmacro -%}
```

### Describe alternatives you've considered

I know the columns can be manually cut-n-paste added to the properties, and variables make it a bit easier. eg,
```
models:
  - name: test_model
    columns:
      - name: "{{ var('landed_timestamp_name') }}"
        data_type: "{{ var('landed_timestamp_type') }}"
      ...
```
But when you add all the extra properties, (ie, description, meta, tags), it does not scale very well.
Especially when other internal/common columns are added or removed (or meta/tags are added or removed).

I can also work around this by using an incremental model with `on_schema_change` set to `fail`, and `contract.enforced` set to `false`.
By defining the existing table, and making sure we truncate instead of dropping, I can control the model contract.
This does allow the removal of model properties (since we are not using the dbt contract feature anymore), but unfortunately I still need to use model properties because my macro uses meta to control column transformations :shrug:
And I would like to make this work for view transformations.

### Who will this benefit?

? Data engineers that use packaged macros to automate pipelines and want to reduce management overhead and surprises

### Are you interested in contributing this feature?

Sorry, but my time is spoken for already

**Comment by dbeatty10** [comment]
Thanks for reaching out about this @GKTheOne !

It sounds like the primary problem you're trying to solve is keeping your YAML files up-to-date and synchronized with the columns + data types of your model.

We're considering this out of scope for dbt-core, so I'm going to close this issue as "not planned". Rather, we'd like to see this type of use case addressed by a separate CLI tool or a dbt package like [`dbt-codegen`](https://github.com/dbt-labs/dbt-codegen).
