### ISSUE TITLE
[Regression] env var `DBT_TARGET` violates the rule of specificity

### ISSUE THREAD

**Issue by owenprough-sift** [dbt-labs/dbt-core#10425]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt improperly ignores the `--target` CLI flag when environment variable `DBT_TARGET` is set.

```
$ export DBT_TARGET=nonvalid_target
$ dbt build --project-dir /dbt --target dev
12:31:08  Running with dbt=1.8.3
12:31:08  Encountered an error:
Runtime Error
  The profile 'xxx' does not have a target named 'nonvalid_target'. The valid target names for this profile are: 
   - dev
   - prod
```

### Expected Behavior

According to the documentation regarding flags ([link](https://docs.getdbt.com/reference/global-configs/about-global-configs#setting-flags)):

> The most specific setting "wins." If you set the same flag in all three places, the CLI option will take precedence, followed by the environment variable, and finally, the value in dbt_project.yml.

So I would expect the `--target` CLI option to be used even though the env var is set.

### Steps To Reproduce

1. Set environment variable `DBT_TARGET`
2. Invoke dbt, passing the `--target` option for a target different than the contents of `DBT_TARGET`
3. Weep when dbt ignores `--target` and uses instead the contents of `DBT_TARGET`

### Environment

```markdown
- OS: Debian 11 (official python docker image `python:3.11-slim-bullseye`)
- Python: 3.11.9
- dbt: 1.8.3
- dbt-snowflake: 1.8.3
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thank you for raising this issue @owenprough-sift -- agreed that dbt should use the value of `--target` instead of `DBT_TARGET` 🎯

This looks like the issue reported in https://github.com/dbt-labs/dbt-core/issues/10304.

What happens when you move `--target` to be _before_ the `build` subcommand?

**Comment by owenprough-sift** [comment]
`dbt --target dev build ...` works as expected. But I'd still like #10304 to be fixed. 😉

**Comment by dbeatty10** [comment]
> But I'd still like #10304 to be fixed. 😉

💯 ! We've got a fix in flight: https://github.com/dbt-labs/dbt-core/pull/10423

In the meantime, I'm going to close this one as a special case of https://github.com/dbt-labs/dbt-core/issues/10304

Thank you as always for your insights on what is/isn't working as it should 🙏

**Comment by dbeatty10** [comment]
@owenprough-sift we just merged https://github.com/dbt-labs/dbt-core/pull/10423. Once https://github.com/dbt-labs/dbt-core/pull/10427 is also merged, then it will go in the next patch release for dbt 1.8.x.
