### ISSUE TITLE
test: add more test cases for listagg macro

### ISSUE THREAD

**Issue by igorvoltaic** [dbt-labs/dbt-core#10444]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

tests does not cover all test cases described in the listagg macro docs

### Who will this benefit?

dbt adapter devs

### Are you interested in contributing this feature?

\+

**Comment by dbeatty10** [comment]
Thanks for opening https://github.com/dbt-labs/dbt-core/pull/10445 @igorvoltaic 🤩

Assuming you noticed these missing test cases while working on https://github.com/ClickHouse/dbt-clickhouse/pull/318 ?

**Comment by igorvoltaic** [comment]
> Thanks for opening #10445 @igorvoltaic 🤩
> 
> Assuming you noticed these missing test cases while working on [ClickHouse/dbt-clickhouse#318](https://github.com/ClickHouse/dbt-clickhouse/pull/318) ?

yeah, exactly :)
