### ISSUE TITLE
[Bug] dbt build with `--empty` flag compiles unit tests with empty mock fixtures

### ISSUE THREAD

**Issue by zendesk-cisenbe** [dbt-labs/dbt-core#10516]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When you perform `dbt build -s <some_model> --empty`, and there are unit tests associated with `<some_model>`, the fixtures for the mocks in the unit test will return 0 records, but the expectations continue to use the full fixture. This always leads to a failure of the unit test.

The compiled code for the fixture looks like this:
```
select * from __dbt__cte__upstream_ref where false limit 0
```

### Expected Behavior

Unit tests should ignore the `--empty` flag. Fixtures for both mocks and expectations should be respected regardless of tags.

### Steps To Reproduce

1. In a dbt project containing a model with unit tests with fixtures (i. e., `ref()` or `source()`)
2. run `dbt build -s <some_model> --empty`
3. The unit test will run first and fail because the fixture will return 0 rows, which will never compare to a populated expectation

### Environment

```markdown
- OS: Ubuntu 22.04.4
- Python: 3.11.9
- dbt: 1.8.3
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reporting this @zendesk-cisenbe.

I was able to reproduce this with the following files and commands:

<details>
<summary>

### Reprex
</summary>

`models/my_upstream_model.sql`

```sql
select 1 as id
```

`models/my_downstream_model.sql`

```sql
select *
from {{ ref("my_upstream_model") }}
```

`models/_unit_tests.yml`

```yaml
unit_tests:
  - name: test_10516

    model: my_downstream_model

    given:
      - input: ref("my_upstream_model")
        rows:
        - {id: 2}

    expect:
      rows:
        - {id: 2}
```

Commands:

```shell
dbt build -s my_downstream_model --empty
```

Output:

```
$ dbt build -s my_downstream_model --empty

23:59:31  Running with dbt=1.8.3
23:59:32  Found 2 models, 444 macros, 1 unit test
23:59:32  
23:59:34  Concurrency: 10 threads (target='snowflake')
23:59:34  
23:59:34  1 of 2 START unit_test my_downstream_model::test_10516 ......................... [RUN]
23:59:37  1 of 2 FAIL 1 my_downstream_model::test_10516 .................................. [FAIL 1 in 2.63s]
23:59:37  2 of 2 SKIP relation dbt_dbeatty.my_downstream_model ........................... [SKIP]
23:59:37  
23:59:37  Finished running 1 unit test, 1 view model in 0 hours 0 minutes and 4.89 seconds (4.89s).
23:59:37  
23:59:37  Completed with 1 error and 0 warnings:
23:59:37  
23:59:37  Failure in unit_test test_10516 (models/_unit_tests.yml)
23:59:37    

actual differs from expected:

@@ ,ID
---,2


23:59:37  
23:59:37    compiled code at target/compiled/my_project/models/_unit_tests.yml/models/test_10516.sql
23:59:37  
23:59:37  Done. PASS=0 WARN=0 ERROR=1 SKIP=1 TOTAL=2
```

<img width="480" alt="image" src="https://github.com/user-attachments/assets/cd6c17ac-db4e-4d40-854c-6d68c6af6b1d">


Take a look at the unit code logic:

`target/run/my_project/models/_unit_tests.yml/models/test_10516.sql `

```
-- Build actual result given inputs
with dbt_internal_unit_test_actual as (
  select
    id, 'actual' as "actual_or_expected"
  from (
    with __dbt__cte__my_upstream_model as (

-- Fixture for my_upstream_model
select 
    
        try_cast('2' as NUMBER(1,0))
     as id
) select *
from (select * from __dbt__cte__my_upstream_model where false limit 0)
  ) _dbt_internal_unit_test_actual
),
-- Build expected result
dbt_internal_unit_test_expected as (
  select
    id, 'expected' as "actual_or_expected"
  from (
    select 
    
        try_cast('2' as NUMBER(1,0))
     as id
  ) _dbt_internal_unit_test_expected
)
-- Union actual and expected results
select * from dbt_internal_unit_test_actual
union all
select * from dbt_internal_unit_test_expected
```

</details>

As mentioned by @zendesk-cisenbe, note in the unit test fixture within the reprex where it is including `(select * from __dbt__cte__my_upstream_model where false limit 0)` instead of just `__dbt__cte__my_upstream_model`.

**Comment by jonathanneo** [comment]
This is affecting my company from running dbt unit tests in CI, as we run our CI pipelines with the `--empty` flag. This is impacting ~350 dbt-core users.
