### ISSUE TITLE
Remove deprecation warnings for tests to data_tests configs

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#10564]
### Description

We are not going to actually deprecate the use of the "tests:" config.  Although we prefer "data_tests:" because it's more precise and less confusing, and contrasts more logically with our newer "unit_tests:" definitions, the use of "tests:" will continue to work, so we should remove the actual deprecation warning.

Instead we will move this to the project auditing feature: https://github.com/dbt-labs/dbt-project-evaluator/issues/489

### Acceptance Criteria

No more warnings are issued and people who have set up a "warn_error_options" config for TestsConfigDeprecation do not get errors.

**Comment by jschintz-nytimes** [comment]
At least make an easy way to identify tests vs data_tests

I'd love to be able to run something like
`dbt ls --resource-type test --exclude-resource-type data_test `
