### ISSUE TITLE
[Bug] SQL compilation error when running `--empty` flag on pre-hook containing macro

### ISSUE THREAD

**Issue by jacqmic** [dbt-labs/dbt-core#10673]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running the simple model below together with the `--empty` flag I get the error `SQL compilation error: syntax error line 1 at position 21 unexpected '('.` and it seems to be linked to calling the `source` macro inside the pre-hook statement.

```sql
-- models/staging/stg_sys__customers.sql
{{ config(
    pre_hook = [
        "alter external table {{ source('sys', 'customers') }} refresh"
    ]
) }}

with cus as (
    select * from {{ source("sys", "customers") }}
)

select * from cus
```

### Expected Behavior

The model should run successfully but somehow the pre-hook statement is not compiled correctly in combination with the `--empty` flag.

### Steps To Reproduce

1. Setup a dbt project with Snowflake
2. Create the model described above
3. Run `dbt run --select stg_sys__customers --empty`

### Relevant log output

```sh
12:19:01  Completed with 1 error and 0 warnings:
12:19:01
12:19:01    Database Error in model stg_sys__customers (models\staging\stg_sys__customers.sql)
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 21 unexpected '('.
12:19:01
12:19:01  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: Windows 11 Enterprise
- Python: 3.10.9
- dbt: dbt-core=1.8.2, dbt-snowflake=1.8.3
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
@jalumi To opt a specific relation (ref / source) out of the automatic filtering that dbt applies in `--empty` runs, you can explicitly call the `.render()` method on that relation.

Try:
```sql
-- models/staging/stg_sys__customers.sql
{{ config(
    pre_hook = [
        "alter external table {{ source('sys', 'customers').render() }} refresh"
    ]
) }}

with cus as (
    select * from {{ source("sys", "customers") }} -- leave this as is!
)

select * from cus
```

**Comment by rrogersiiigen** [comment]
We have 5 dbt projects, which are all inherited in one "final" dbt_central project.

We use `--empty` in dbt_central to refresh lineage for all models across all projects, thereby making dbt_central our "source of truth" for all lineage information. 

However, this new issue (reported here: #10673) is causing 300+ errors to generate across all of our projects -- making the render() solution outlined above not practical.

How else can we get our dbt_central project to refresh all lineage information?

**Comment by MichelleArk** [comment]
Hey @rrogersiiigen - did you mean to post a different link to the new issue? Curious what the errors are!
