### ISSUE TITLE
[Bug] dbt upgrade breaking the elementary dashboard functionality 

### ISSUE THREAD

**Issue by shamleekaranjkar** [dbt-labs/dbt-core#10773]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We were previously able to display the results of test queries on the Elementary dashboard. However, after the dbt version upgrade it is not able to show the results.

 It seems we need to use dbt-bigquery==1.7.4 and dbt-core==1.7.17 for the results to appear on dashboard. If we switch to the latest versions (dbt-bigquery==1.8.2 and dbt-core==1.8.5), the dashboard doesn't show any results from our dbt test queries.

### Expected Behavior

It should be able to show the results as shown below on the elementary dashboard -

![Screenshot 2024-09-25 120050](https://github.com/user-attachments/assets/745c66c3-89f7-4b31-8637-1aeae01665d9)

### Steps To Reproduce

1. pip install dbt-bigquery==1.8.2 and dbt-core==1.8.5
2. dbt run command
3. dbt test command 
4. edr report command - to generate the report 

### Environment

```markdown
- OS: Windows
- Python:3.12.6
- dbt: dbt-bigquery==1.8.2 and dbt-core==1.8.5
- elementary-data==0.15.1
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @shamleekaranjkar !

If there's something _specific_ that dbt changed that is independent of the Elementary Dashboard, then we could assess it. But if all we know is that the Elementary Dashboard isn't working with dbt-bigquery==1.8.2 and dbt-core==1.8.5, then that is something they'll need to assess first.

Could you please [open an issue](https://github.com/elementary-data/elementary/issues/new?assignees=&labels=Bug%2C+Triage+%F0%9F%91%80&projects=&template=bug_report.md&title=) on the `elementary` repo instead?

In the meantime, I'm going to close this as "not planned" until there is something specific and actionable related to dbt-core.
