### ISSUE TITLE
[Bug] Error message on Versionless not helpful for Credential Issue

### ISSUE THREAD

**Issue by jennlw** [dbt-labs/dbt-core#10804]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

On Versionless, while in the IDE, error comes up when trying to run commansd, even 'dbt ls' will not work. 
Encountered an error:
Compilation Error
'None' has no attribute 'endswith'

If you switch version to 1.7 the error becomes:
Encountered an error:
Runtime Error
Credentials in profile "user", target "default" invalid: None is not of type 'string'. 

The 1.7 message helped user to resolve the issue by going to their Credentials and selecting "Connect Snowflake Account"

### Expected Behavior

Error code is helpful in pointing user in the right direction to troubleshoot and resolve. 

### Steps To Reproduce

I have been trying to reproduce, but I'm not able to leave my credentials blank. This may be related to Snowflake Oauth

### Relevant log output

```shell
Logs will be shared internally.
```

### Environment

```markdown
- OS:
- Python:
- dbt: Versionless error not helpful but 1.7 version is a little more helpful
```

### Which database adapter are you using with dbt?

snowflake

**Comment by aranke** [comment]
Response from customer:

> Thanks for getting back to this topic,
> Indeed we have a `generate_schema_name` macro and the error is coming from there. This macro was unchanged and in 1.7 it was not throwing this error.
I will fix it on our side.
> You can mark this ticket as closed.
