### ISSUE TITLE
[Bug] Generate compare changes is showing a "Nothing to do" when only a seed file is changed!!

### ISSUE THREAD

**Issue by gunnava** [dbt-labs/dbt-core#10823]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The "Generate compare changes" step (debug logs for the run step attached) is
 throwing an error for a PR where only a seed is changed and with the warning config as below:
```
flags:
  warn_error_options:
    error: 
      - NoNodesForSelectionCriteria
      - NothingToDo
```
```
15:03:21 Encountered an error:
Compilation Error
Nothing to do. Try checking your model configs and model specification args
```

### Expected Behavior

The expectation is that the Generate compare changes should show the files changed  if any and not throw the warning "Nothing to do" 

### Steps To Reproduce

1. Create a PR where only a seed file data is changed.
2. trigger a CI run/ a run that would defer to another run and the only change is the above seed file entries.
3. The Generate compare changes does not show the files changed(seed file in this case)  and throws the warning "Nothing to do" 
![image (3)](https://github.com/user-attachments/assets/83be0355-4fef-47e5-9b44-f6aa31f39c00)

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

Slack thread: https://dbt-labs.slack.com/archives/C02SRNY2EQ4/p1726685698514849

**Comment by dbeatty10** [comment]
Thanks for reporting this @gunnava!

How large is the seed file? If it is larger than 1 MiB, then it [won't show up during state comparison](https://docs.getdbt.com/reference/node-selection/state-comparison-caveats#seeds).

I wasn't able to reproduce this will a very simple seed file less than 1 MiB. See below for details.

### My project files and commands

I tried the files and commands below, and things worked as expected.

Start with these files:

`dbt_project.yml`

```yaml
flags:
  warn_error_options:
    error: 
      - NoNodesForSelectionCriteria
      - NothingToDo
```

`seeds/my_seed.csv`

```csv
id
1
```

Run this command:

```shell
dbt build --target-path artifacts
```

Then change the seed file to this:

`seeds/my_seed.csv`

```csv
id
2
```

And run this command:

```shell
dbt build --select state:modified+ --state artifacts
```

It all worked as expected for me.

**Comment by gunnava** [comment]
Hi , Thanks for looking at the issue. I am still able to replicate the issue (on cloud version: 2024.11.07+01d725b)
**My project files and commands**
Seed file:

```
employee_id,email,customer_id,add_column
3425, mike@jaffleshop.com, 1 , 1
2354, sarah@jaffleshop.com, 6, 1
2342, frank@jaffleshop.com, 8, 1
1234, jennifer@jaffleshop.com, 9 , 1
1256, jennifer@jaffleshop.com, 9 , 1
1356, jennifer@jaffleshop.com, 3 , 1
789, jennifer@jaffleshop.com, 9 , 1
1189, jennifer@jaffleshop.com, 9 , 1
156, jennifer@jaffleshop.com, 3 , 2
```

dbt_project.yml

```
flags:
  warn_error_options:
    error: 
      - NoNodesForSelectionCriteria
      - NothingToDo
```

run the command:

`dbt build`

update the seed file to 
```
employee_id,email,customer_id,add_column
3425, mike@jaffleshop.com, 1 , 1
2354, sarah@jaffleshop.com, 6, 1
2342, frank@jaffleshop.com, 8, 1
1234, jennifer@jaffleshop.com, 9 , 1
1256, jennifer@jaffleshop.com, 9 , 1
1356, jennifer@jaffleshop.com, 3 , 1
789, jennifer@jaffleshop.com, 9 , 1
1189, jennifer@jaffleshop.com, 9 , 1
156, jennifer@jaffleshop.com, 3 , 2
166, jennifer@jaffleshop.com, 3 , 2
```

and run the step:
`dbt build --select state:modified+ --state artifacts`. --> this is successful and builds only the modified seed file

Now as part of the Advance CI in dbt cloud to generate compare changes this command is executed
` dbt compare -s state:modified` 
and it fails with the error
`Compilation Error
  Nothing to do. Try checking your model configs and model specification args`
  
Debug logs for the dbt build --select state:modified+ and Generate compare changes
  
[debug - 2024-11-08T182440.671.log](https://github.com/user-attachments/files/17683007/debug.-.2024-11-08T182440.671.log)
[debug - 2024-11-08T183315.853.log](https://github.com/user-attachments/files/17683011/debug.-.2024-11-08T183315.853.log)

**Comment by dbeatty10** [comment]
There doesn't appear to be any issue within dbt-core for this, so closing this issue in favor of fixing within dbt Cloud.
