### ISSUE TITLE
[Bug] Fabric adapter wrong limit query

### ISSUE THREAD

**Issue by tabit01** [dbt-labs/dbt-core#10843]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Error message showing that the `dbt-fabric` adapter dispatches wrong query to Fabric Synapse Warehouse
```
select * from source
limit 5
```

### Expected Behavior

The dispatched query should be 
```
select top 5 *
from ..
```

### Steps To Reproduce

1. Activate python venv with DBT in PowerShell terminal within VS Code
2. Run `dbt show --select "stg_source__entity.sql"`

### Relevant log output

```shell
with source as (
	    select * from "Warehouse"."dbo"."source_entity"
),
renamed as (
	  select
	     "column name 1"
	  from source
)
select * from renamed
	
	limit 5
```

```
11:31:22  Encountered an error:
Runtime Error
	Database Error in model stg_source__entity (models\staging\stg_source__entity.sql)
	  ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '5'. (102) (SQLExecDirectW)")
```

### Environment

```
- OS: Windows 11
- Python: 3.12.7
- dbt:1.8.7
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

from `dbt --version`

Plugins:
	- fabric: 1.8.7

**Comment by pmags** [comment]
Downgrading to dbt-core==1.7.18 seems to fix for now

**Comment by dbeatty10** [comment]
Thanks for reaching out @tabit01 !

Closing this one in favor of https://github.com/microsoft/dbt-fabric/issues/216
