### ISSUE TITLE
[Bug] get_columns_in_relation is not working when used in a post hook

### ISSUE THREAD

**Issue by rorydonaldson** [dbt-labs/dbt-core#10851]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am calling a macro in a post hook. Inside the macro, I am using `adapter.get_columns_in_relation`. This returns a list containing the required columns, however, when I go to render or loop through this list, it is showing as empty. Even though immediately before when I log it, I get the appropriate response. 

### Expected Behavior

adapter.get_columns_in_relation to return a list that can be rendered.

### Steps To Reproduce

Macro as follows:

```

{% macro example_macro(relation) %}

{% set cols = adapter.get_columns_in_relation(relation) %}

{{ log("Columns: " ~ cols, info=true) }}

update {{ relation }} set

{% for col in cols %}
     {{ col.column }} = null {%- if not loop.last %},{% endif -%}
{% endfor %}

{% endmacro %}

```

Model with post_hook:

```

{{config(
    materialized='table',
    post_hook = example_macro(this)
)}}

```

### Relevant log output

```shell
`{{ log("Columns: " ~ cols, info=true) }}`

Outputs:


Columns: [SnowflakeColumn(column='ID', dtype='NUMBER', char_size=None, numeric_precision=38, numeric_scale=0),....]
```

Compiled post hook:

```
update EXAMPLE_DB.EXAMPLE_SCHEMA.MODEL_NAME set

```

Missing all column info.

### Environment

```markdown
- OS: MacOS
- Python: Python 3.12.4
- dbt: 1.8.3
  - snowflake: 1.8.3
```

### Which database adapter are you using with dbt?

snowflake

**Comment by aranke** [comment]
Hi @rorydonaldson,

Thanks for taking the time to file this report.

I think you need to wrap your macro in an `{% if execute %}` block, as documented here: https://docs.getdbt.com/reference/dbt-jinja-functions/execute; I was able to get a model to pass once I did this.

If the model hasn't been previously materialized, I see the log line `Columns: []` which indicates that `get_columns_in_relation` is fetching the columns of the already-materialized model before it is rebuilt.

I'm going to close this issue for now, but please don't hesitate to reopen if you have further questions.
