### ISSUE TITLE
[Bug] canceling a run of a microbatch model should cause remaining batches to be skipped

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#10862]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Cancelling a run doesn’t immediately stop all the related batch runs. The remaining batches continue to build.

### Expected Behavior

All the batches cancel out regardless of which batch we initiate the cancellation action/request.

### Steps To Reproduce

See [here](https://www.notion.so/dbtlabs/Testing-out-the-Microbatch-Incrementals-121bb38ebda78066bdeff09870d39d31?pvs=4#121bb38ebda780f4991ed93455bad1c9)

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

snowflake

**Comment by brian-franklin** [comment]
I also found that when an error is encountered in the model logic it does not stop the remaining batches from attempting to run resulting in the same error reporting for all batches.
