### ISSUE TITLE
[Feature] Make `--event-end-time` require `--event-start-time` and vice versa

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#10874]
Currently, we have _five_ ways to run a microbatch model 🥴 
1. creating/recreating the model
    * batches are run from model's defined `begin` to "now"
2. incrementally with no extra args
    * the batches run are determined by the current time and the lookback
    * f.x. if you have a `batch_size=day`, `lookback=2`, and it is "currently" `2024-10-17 13:04:39` then three batches are run: `2024-10-15`, `2024-10-16`, and `2024-10-17`
3. incrementally with both `--event-time-start` and `--event-time-end` specified
    * batches are run >= `--event-time-start` and < `--event-time-end`
    * f.x. if you have a `batch_size=day`, `--event-time-start "2024-10-01"`, and `--event-time-end "2024-10-04"` then three batches will be run: `2024-10-01`, `2024-10-02`, `2024-10-03`
4. incrementally with _only_ `--event-time-start` specified
    * batches will be run from `--event-time-start` to "now"
    * f.x. if you have a `batch_size=day`, `--event-time-start "2024-10-13"`, and it's currently midday on 2024-10-17, then five batches will be run: `2024-10-13`, `2024-10-14`, `2024-10-15`, `2024-10-16`, and `2024-10-17`
5. incrementally with _only_ `--event-time-end` specified
    * batches will run the `--event-time-end` batch plus prior batches according to the `period`
    * f.x. if you have a `batch_size=day`, `lookback=2`, and `--event-time-end "2024-10-04"`, then three batches will be run: `2024-10-01`, `2024-10-02`, `2024-10-03`

Through further discussion, we believe (4) and (5) are confusing, unexpected, and dangerous. Ways (4) and (5) weren't intentional implementations, but accidental realities created by implementations for (1), (2), and (3). As such, we should _require_ that the specification of `--event-time-end` necessitates `--event-time-start` and vice versa.

**Comment by mirnawong1** [comment]
docs pr here to address this: https://github.com/dbt-labs/docs.getdbt.com/pull/6351/files
