### ISSUE TITLE
[Bug] Not possible to add a tag config to a singular test within a yaml file

### ISSUE THREAD

**Issue by cohms** [dbt-labs/dbt-core#10931]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently it's not possible to add a tag to a singular test in YAML, which is possible for generic tests. 

### Expected Behavior

Would like to add tags as a configuration in a yaml file for singular tests, rather than have to add tags separately in each test's SQL file. 

[example](https://files.slack.com/files-pri/T0Z0T0223-F07SCTD94M8/image.png)

### Steps To Reproduce

1. In dev create yaml file under tests for data_tests
2. Add tag to singular test
3. run `dbt test -s tag:carol_fun_test_tag`
4. run succeeds, but logs say nothing to do
![image](https://github.com/user-attachments/assets/4530f753-e684-4bfe-adfd-47774f0ef9fd)
![image](https://github.com/user-attachments/assets/ba2670dc-137b-4c6f-a39e-eabf16a37020)

### Environment

```markdown
- OS:
- Python:
- dbt: versionless
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for opening this @cohms !

Could you try nesting `tags:` under `config:` like below?

```yaml
data_tests:
  - name: stg_tpch_orders_assert_positive_price
    config:
      tags: carol_fun_test_tag
```

### Example singular data test

`tests/stg_tpch_orders_assert_positive_price.sql`

```sql
select 1 as id
where 0 = 1
```

### Log output

```
(dbt_1.9) $ dbt test -s tag:carol_fun_test_tag --no-partial-parse
01:22:08  Running with dbt=1.9.0-b2
01:22:11  Registered adapter: postgres=1.9.0-b1
01:22:12  Found 2 data tests, 424 macros
01:22:12  
01:22:12  Concurrency: 5 threads (target='postgres')
01:22:12  
01:22:13  1 of 1 START test stg_tpch_orders_assert_positive_price ........................ [RUN]
01:22:13  1 of 1 PASS stg_tpch_orders_assert_positive_price .............................. [PASS in 0.10s]
01:22:13  
01:22:13  Finished running 1 test in 0 hours 0 minutes and 1.15 seconds (1.15s).
01:22:13  
01:22:13  Completed successfully
01:22:13  
01:22:13  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

**Comment by cohms** [comment]
thanks Doug, I'd tried that previously, but it turns out it was because the customer and I had both saved the yml file to the tests folder - it worked once we moved the yaml file to the models file. Major face palm!
