### ISSUE TITLE
[Bug] dbt alters cacert.pem file - adding old certs back into file

### ISSUE THREAD

**Issue by DasGinger** [dbt-labs/dbt-core#10935]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior
When DBT is installed (within virtual environment or globally) and a request is made to hub.getdbt.com, the `cacert.pem` file on the local machine is altered. In our case roughly two thousand lines are added to the `cacert.pem` file; one of the certs added by DBT is an old cert that is expired.

### Expected Behavior

Running `dbt deps` will not alter the `cacert.pem` file and accept it as it is.

### Steps To Reproduce

1. Create an environment for DBT (with dbt installed)
2. Locate your `cacert.pem` file (usually located at `C:\Users\{user}\AppData\Local\.certifi` on Windows)
3. Run `dbt deps` or this script for testing purposes
```python
import os
import requests
from requests.utils import DEFAULT_CA_BUNDLE_PATH

url = "https://hub.getdbt.com"

try:
    response = requests.get(url)
    print("It worked")
except Exception as e:
    print("It didn't work\n")

    print(f"HTTPS_PROXY: {os.environ.get('HTTPS_PROXY')}")
    print(f"REQUESTS_CA_BUNDLE: {os.environ.get('REQUESTS_CA_BUNDLE')}")
    print(f"CURL_CA_BUNDLE: {os.environ.get('CURL_CA_BUNDLE')}")
    print(f"DEFAULT_CA_BUNDLE_PATH: {DEFAULT_CA_BUNDLE_PATH}")
```
4. Verify the request succeeds or fails
5. Verify the `cacert.pem` file has been altered.

**NOTE**: If you follow these steps but DO NOT install DBT this issue will not occur when you run the test python script

### Relevant log output

python error we are seeing when running `dbt deps`:

```shell
 connection exception occurred: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
```

### Environment

```markdown
- OS: Windows 10, 22H2, 19045.5011 (build)
- Python: 3.11.0
- dbt: 1.7.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reaching out @DasGinger !

It looks like you might be trying out the troubleshooting steps listed  in https://github.com/dbt-labs/dbt-core/issues/8554#issuecomment-1715874918 ?

Did you happen to try this with any of the following variants?
- on a non-Windows machine
- latest dbt-core (1.8.8)
- a dbt adapter other than dbt-snowflake (e.g. dbt-postgres or dbt-duckdb)

**Comment by DasGinger** [comment]
We have teammates that use MacOS and they do no have this issue...

I'll try the other two variants today.

**Comment by dbeatty10** [comment]
@DasGinger I suspect that you have one (or both) of the following installed, and it is altering the `cacert.pem` file:
- [`python-certifi-win32`](https://pypi.org/project/python-certifi-win32/): On Windows, this package augments `certifi` to use certificates from the Windows system's trust store (Windows Certificate Store) instead of `certifi`'s built-in trust store.
- [`pip-system-certs`](https://pypi.org/project/pip-system-certs/): This package is an alternative replacement for `python-certifi-win32`, and it patches `pip` and `requests` at runtime to use certificates from the default system store.

You can uninstall them like this:

```shell
python -m pip uninstall python-certifi-win32
python -m pip uninstall pip-system-certs
```

**Comment by DasGinger** [comment]
@dbeatty10 I had both of those libraries installed. After removing them, I'm able to use `dbt deps` again!

Thanks for the help!

**Comment by dbeatty10** [comment]
Awesome news, @DasGinger !
