### ISSUE TITLE
[Bug] Creating nonclustered indexes in a SQL Server materialized table is resulting in an orphaned clustered columnstore index

### ISSUE THREAD

**Issue by ianlcassidy** [dbt-labs/dbt-core#10964]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When creating a materialized table and specifying nonclustered indexes in the config post-hook, a clustered columnstore index is created on the dbt tmp table and then the tmp table is renamed. This is resulting in our database backup failing (we use Commvault) because the clustered columnstore index is "orphaned."

### Expected Behavior

We expect the clustered columnstore index to be created _after_ the tmp table is renamed, similar to how the nonclustered indexes are created. We have tested this theory by modifying the execution steps in the `dbt.log` file and our database backup succeeds.

### Steps To Reproduce

1. use dbt to create an arbitrary materialized table using the sql server adaptor
2. specify at least one nonclustered index in the config post-hook
3. run dbt on the single model
4. inspect the DDL or look at the indexes created including the clustered columnstore index

### Relevant log output

```shell
use [DATABASE];
if EXISTS (
   SELECT *
   FROM sys.indexes with (nolock)
   WHERE name = 'SCHEMA_TABLE__dbt_tmp_cci'
   AND object_id=object_id('SCHEMA_TABLE__dbt_tmp')
)
DROP index "SCHEMA"."TABLE__dbt_tmp".SCHEMA_TABLE__dbt_tmp_cci
CREATE CLUSTERED COLUMNSTORE INDEX SCHEMA_TABLE__dbt_tmp_cci    <---- index created on tmp table
ON "SCHEMA"."TABLE__dbt_tmp"

USE [DATABASE];
      EXEC sp_rename 'SCHEMA.TABLE', 'TABLE__dbt_backup'

USE [USB-DataScience];
      EXEC sp_rename 'SCHEMA.TABLE__dbt_tmp', 'TABLE'    <---- tmp table renamed

if not exists(select *
              from sys.indexes with (nolock)
              where name = 'nonclustered_6eb6a6764d9714280e37441d1ac3d5ae'
              and object_id = OBJECT_ID('"DATABASE"."SCHEMA"."TABLE"')
)
begin
create nonclustered index   <--- index created on actual table
       nonclustered_6eb6a6764d9714280e37441d1ac3d5ae
       on "DATABASE"."SCHEMA"."TABLE" ([FIELD])
        
end
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.11.9
- dbt: 1.8.7
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

We are using the dbt SQL Server adapter.

Sample dbt model code:

```sql
{{
    config({
        "materialized": "table",
        "post-hook": [
            "{{ create_nonclustered_index(columns = ['FIELD']) }}",
        ],
    })
}}

select
  *
from
  {{ source('SCHEMA', 'TABLE') }};
```

**Comment by dbeatty10** [comment]
@ianlcassidy this looks to me like it is specific to the `dbt-sqlserver` adapter, specifically, the [`create_nonclustered_index`](https://docs.getdbt.com/reference/resource-configs/mssql-configs#indices) macro it provides.

Could you open an issue [here](https://github.com/dbt-msft/dbt-sqlserver/issues/new) instead?

**Comment by ianlcassidy** [comment]
@dbeatty10 - apologies. will open an issue in the other repo.
