### ISSUE TITLE
[Bug] <title>dbt unit test does not work without external package

### ISSUE THREAD

**Issue by sangee14** [dbt-labs/dbt-core#11081]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am trying to implement dbt unit tests without using any of the external package being installed. But the native dbt unit tests does not work and while executing it using the command `dbt test --select test_name` , it just not picking up the test and executing it. It says, the selection criterion does not match any node.

### Expected Behavior

The test should be get picked up and executed successfully against the model using the `dbt test `command

### Steps To Reproduce

```
tests/test_properties.yml

unit_tests:
  - name: current_student_view_data
    description: "stores students data"
    model: curr_raw_student_view
    given:
    - input: ref('hub_raw_student')
      rows:
        - {student_users_pk: '83E71047', student_id: '3063542d005f'}
 
    - input: ref('sat_raw_student_details')
      rows:
        - {student_users_pk: '83E71047', student_id: '3063542d005f', email: 'abcd@gmail.com', first_name: 'Hello1', last_name: 'Guest'}
   
    expect:
      rows:
        - {student_id: '3063542d005f', email: 'abcd@gmail.com', first_name: 'Hello1', last_name: 'Guest'}
```

Run: `dbt test --select current_student_view_data`
Outcome:
```
root@**********:/usr/app/dbt# dbt test --select current_ajo_view_data
06:54:23  Running with dbt=1.7.3
06:54:24  Registered adapter: snowflake=1.7.1
06:54:34  Found 67 models, 1 snapshot, 5 tests, 87 sources, 0 exposures, 0 metrics, 1017 macros, 0 groups, 0 semantic models
06:54:34  The selection criterion 'current_student_view_data' does not match any nodes
06:54:34
06:54:34  Nothing to do. Try checking your model configs and model specification args
```

### Relevant log output

```shell
root@**********:/usr/app/dbt# dbt test --select current_ajo_view_data
06:54:23  Running with dbt=1.7.3
06:54:24  Registered adapter: snowflake=1.7.1
06:54:34  Found 67 models, 1 snapshot, 5 tests, 87 sources, 0 exposures, 0 metrics, 1017 macros, 0 groups, 0 semantic models
06:54:34  The selection criterion 'current_student_view_data' does not match any nodes
06:54:34
06:54:34  Nothing to do. Try checking your model configs and model specification args
```
```


### Environment

```markdown
- OS: Windows 10
- Python:
- dbt:1.7.3
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
Hey @sangee14 - dbt unit tests were introduced in dbt Core v1.8, so you need to upgrade your version of dbt:
- https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.8#unit-tests

Glad you want to make use of unit tests in your project! I'm going to close this issue, because the resolution is to use a newer version of dbt.

**Comment by sangee14** [comment]
Please re-open this issue. Even after upgrading, it does not work.
```
dbt-core : 1.8.9
dbt-snowflake: 1.8.3
```
