### ISSUE TITLE
Supply RunModelResult in seed and model post-hook context

### ISSUE THREAD

**Issue by sumit0k** [dbt-labs/dbt-core#1195]
### Feature description
is there any way to get count of inserted rows from each model which are materialized as table

I can see it is printed in logs, but I want to access the number and store it in something like audit table using hooks

```
"post-hook" : [
          "insert into {{this.schema}}.dbt_audit (event_name, event_timestamp, event_schema, event_model) values ( 'completed model deployment', getdate(), '{{this.schema}}', '{{this.name}}')"
        ]
```

I was able to find only these context variables https://docs.getdbt.com/v0.12/reference#this

### Who will this benefit?
Any person or company who wants to implement Auditing around DBT with not just logs, but with Metrics

**Comment by drewbanin** [comment]
Thanks for the issue @sumitkumar1209. Will have a think about how we can expose the status from the database back in the dbt context. One challenge will be that different databases handle this differently -- Postgres and Redshift report the number of rows affected by insert/create statements, but I don't believe BQ or Snowflake do. I imagine we can just return the raw status, then let users parse these things out from there.

Interestingly, PG/Redshift return a status line like:
```
INSERT 0 123
```

The first number is the PK of the record that was inserted, if only a single row was inserted. If more than one row was inserted, then the _second_ number represents the number of affected rows.

One other thing to note is that dbt may run a series of statements in pursuit of building a model. An incremental model on Redshift, for instance, involves running a:
- `create temp table as (...)`
- `delete from ...` (if a `unique_key` is provided)
- `insert into ...`

Each of these steps will return a status, so we'd conceivably want to return all of these to the dbt context. Cool request! Thanks for opening :)
