### ISSUE TITLE
Redshift Feature - Support unload/copy paradigm

### ISSUE THREAD

**Issue by TOphelders** [dbt-labs/dbt-core#1270]
## Feature
Support inserting data to Redshift tables using unload and copy

### Feature description
Despite the recommended process of using:
```
INSERT INTO table (SELECT * FROM tmp_table)
```
when transferring data from one table to another, we've found that the performance of Redshift inserts suffers heavily at scale. Rather it becomes much faster to unload the data to s3 first, followed by copying it back into the table using the Redshift unload/copy commands. Of course this shouldn't be the default behavior, but I think it would make sense to allow the user to choose to use this paradigm if it benefits them.

I feel like this could be done fairly easily by allowing the user to configure s3 access parameters in their profiles.yml, and maybe the upload path and any other parameters could be set within the model configs?

### Who will this benefit?
Redshift users processing enough data to be able to take advantage of the parallelization provided by the unload/copy commands.

**Comment by davehowell** [comment]
You can `UNLOAD` by using a post-hook with the Redshift dbt package https://github.com/fishtown-analytics/redshift#unload_table-source

I agree with not supporting `COPY`, that's definitely the responsibility of the `Load` in ELT, not the `T`.

**Comment by howardmalec** [comment]
Flagging that Mamykin has [documented a process](http://mamykin.com/posts/fast-data-load-snowflake-dbt/) for copy commands via DBT for s3 and snowflake. Not sure why we're not able to enable a similar workflow for Redshift?

**Comment by howardmalec** [comment]
Following up, confirmed that COPY also works as a post hook operation, and you can point to s3 as the source. For example:

```
on-run-end:
  - "truncate table dbt.sales"
  - "copy dbt.sales from 's3://analytics/sales/sales.csv' credentials 'aws_iam_role=arn:aws:iam::XXXX:role/XXXX' delimiter ',' removequotes IGNOREHEADER 1"
  - 'GRANT USAGE ON SCHEMA "dbt" TO GROUP ro'
  - 'GRANT SELECT ON ALL TABLES IN SCHEMA "dbt" TO ro_username'
```
