### ISSUE TITLE
dbt should use jinja's StrictUndefined setting

### ISSUE THREAD

**Issue by tconbeer** [dbt-labs/dbt-core#1389]
### Feature description
See the Jinja docs here: http://jinja.pocoo.org/docs/2.10/api/#undefined-types

In dbt versions <= 0.13, a user can invoke an object that hasn't been defined, and it will compile to a falsy empty string. Instead, dbt should raise an exception during compilation, since invoking an undefined object is often the result of a typo or a namespace issue.

For example, the following model file (with a typo `partiion`) compiles and executes:

```
{% set partiion = 'partition by account_id order by deleted_on asc nulls last rows between unbounded preceding and unbounded following' %}
last_value(id) over ({{partition}}) as id,
last_value(address_id) over ({{partition}}) as address_id,
```
Compiles to:
```
last_value(id) over () as id,
last_value(address_id) over () as address_id,
```

### Who will this benefit?
This will benefit any user that sets Jinja objects in their models.

This would be a breaking change for any users intentionally using undefined objects, but I can't think of why that would be desired. Objects that may not be defined could always be checked with `{% if object_name %}`

**Comment by clrcrl** [comment]
More broadly, there have been a couple of times where I've wanted to configure my own Jinja environment, e.g. enabling `trim_blocks` and `lstrip_blocks`. I wonder if maybe providing a way for people to override their jinja environment is a good idea? Even just writing this makes me feel irksome though for some reason. But on the other hand, it might be a way to enable people to build custom filters as per #480 🤷‍♀️ 

I'm sure you've thought about this before Drew so I'll stop thinking any more on it :)

**Comment by cmcarthur** [comment]
@clrcrl we're likely not going to enable `trim_blocks` and `lstrip_blocks` anytime soon because it would break other parts of dbt parsing. other aspects of the environment (e.g. custom filters) are really interesting and worth considering for sure!

**Comment by drewbanin** [comment]
Re-opening, as we chose to revert #1559. The hard part here is all around UX -- let's revisit for a future release!

**Comment by alexmalins** [comment]
Hi, I think this issue should be kept open rather than closed. An undefined variable compiling to an empty string just caught me out too!

**Comment by thejens** [comment]
There is no reason to allow undefined variables to compile, at least having a --strict flag or similar would be very helpful

**Comment by nevdelap** [comment]
This is definitely a source of tiresome, unnecessarily difficult to track down errors that the compiler should just tell you about. I see past discussions about making it a warning so that it doesn't breaking existing code. Having an option to make it an error would be ideal so that people can opt into it. Please re-open this.

**Comment by Neutron-Tom** [comment]
The undefined variable compiling to empty string has just tripped me up as well - would be great to be able to flag this!

**Comment by vergenzt** [comment]
Hey all - I made a simple dbt plugin package to monkey patch this in 🙃🙈 

https://github.com/vergenzt/dbt-strict-undefined
https://pypi.org/project/dbt-strict-undefined/
