### ISSUE TITLE
Making SQLConnectionManager's execute() more resilient

### ISSUE THREAD

**Issue by jacobm001** [dbt-labs/dbt-core#1627]
I'm working on building an adapter for our legacy MSSQL Server 2008 R2 box so we can untangle that box before migrating all of it off to Snowflake. pyodbc is Microsoft's suggested library for interacting with MSSQL, so I'm using that.

If you look at [this](https://github.com/fishtown-analytics/dbt/blob/b7d9eecf86566dd3d86077667bf8c0dc4cf2ef22/core/dbt/adapters/sql/connections.py#L60) line of the SQLConnectionManager, you'll see that the `execute()` statement is always called with the `bindings` variable, even if it's `None`.

Pyodbc doesn't like this behavior, so I have temporarily overloaded this method to make this single line

```python
if bindings is None:
    cursor.execute(sql)
else:
    cursor.execute(sql, bindings)
```

Overloading the whole function seems unnecessary for such a small change, and ODBC is a common enough driver that I imagine this will be a repeated issue. I think it would be wise to add alter the cursor execution in the SQLConnectionManager. 

As far as I can tell, this won't produce any ill effects to existing adapters.

**Comment by beckjake** [comment]
@jacobm001 Thanks for the suggestion, this is a great idea! I guess so far we've been lucky that our adapters all accept `bindings=None`, but I have encountered other adapters with this issue so it must be a common pattern.

The big change here will probably be fixing any unit tests that expect `bindings=None` to get passed to a mock `cursor.execute` - I think there are only a handful in the `test_*_adapter.py` files.

If you're interested in opening a PR for this, the `dev/louisa-may-alcott` branch (v0.15.0-to-be, I think) would probably be the most appropriate.

**Comment by jacobm001** [comment]
Sure, I'll take a stab at it later this week.
