### ISSUE TITLE
Add `difference` filter to Jinja context

### ISSUE THREAD

**Issue by clausherther** [dbt-labs/dbt-core#1894]
Ansible has a few useful [filters](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#list-filters) in their Jinja context that are not part of core Jinja.
It'd be great to expose some of them to macro developers dbt.

For example, `difference` is a helpful filter to get the difference between two lists.

```python
    @contextfilter
    def difference(context, first, second):
        second = set(second)
        return [item for item in first if item not in second]
```
Used like so:

```jinja
{%- set columns = columns | difference(except_columns) -%}
```
Since this would be run in Python, there should be no cross-database issues.

Related to #480 maybe although I don't think it's necessary to do from an end-user perspective, as long as its easy to enough to PR new functions like this.

**Comment by drewbanin** [comment]
Cool idea @clausherther! I've wanted to add `set` to the context for a long time! The currently workflow for finding the set difference/intersection/union is not great.

I can imagine us:
1. Adding `set` to the context (maybe namespaced under `api.types` or something like that)
2. Adding helper methods for obvious use-cases like set differences

I do think in this case if we just supported `api.types.set`, you could do;
```
{% set columns = api.types.set(columns).difference(api.types.set(except_columns)) %}
```

So, maybe we should support:
1. `api.types.set`
2. a `difference` filter
3. a `union` filter
3. an `intersection` filter

You buy that?

**Comment by clausherther** [comment]
Sounds good to me! I like having the option to both use the generic `api.types.set` as well as the filters as shortcuts for the common functions.
Would `api` also be a good namespace to add other base Python functionality in the future? So, something not specific to `types` would be under `api.somethingelse.*`?

**Comment by drewbanin** [comment]
Yeah - I think namespacing is a good idea in general. It's really just useful from an organization point of view - it helps group similar methods, makes methods easier to find in the docs, etc. 

I don't know that `api` is the best possible name for this, but it's what we've used historically. I can equivalently imagine `dbt.types` or `helpers.types` or similar. My default for the moment would be indeed to have these live in `api.types.*` and `api.somethingelse.*`. You buy that, or do you think there's a better way to organize these methods?

**Comment by clausherther** [comment]
I think that's as good a place as any. I'll try to make some time next week to take a crack at this. I'd love to contribute to the dbt Python code more, so this seems like a fairly easy entry point.

**Comment by clausherther** [comment]
I noticed in the latest commit, `api` is no longer a dbt namespace. Where would be a good home for this functionality now?

Also, I found the code where you're creating the jinja environment, but I can't find any place where you're setting jinja `globals` today?
I was expecting to find something along the lines of
```
env = Environment(loader=loader)
env.globals["some_function"] = some_function
env.globals["some_variable"] = some_variable
```

**Comment by kwood16** [comment]
Has there been any progress on this issue? @drewbanin I'm stumbled on this when I was trying to use `set()` and `.intersection()` in Python to intersect columns from multiple tables and that functionality doesn't seem to be supported in dbt Jinja.

**Comment by joellabes** [comment]
Huh! Turns out I created a dupe of this in https://github.com/dbt-labs/dbt-core/issues/4571 - going to close that one and reopen this one. cc @gshank who triaged my one and might be able to provide some pointers of where to add things.
