### ISSUE TITLE
Support adding metadata to json log output

### ISSUE THREAD

**Issue by elexisvenator** [dbt-labs/dbt-core#1948]
### Describe the feature
In 0.15, console logs can be output in json format. It would be great if we could specify some metadata that can be added to log outputs that can be used be consumers of those logs.

Example: [AWS CloudWatch Embedded Metrics][Embedded metrics spec] is a new feature that can read your log streams and convert the data into graphable cloudwatch metrics.
Example graphable metrics that dbt could generate with current logs:
 * Run success/failure
 * Run duration
 * Success/failure/duration per seed, model and test 

### Describe alternatives you've considered
For the AWS Cloudwatch scenario, the workaround would be a Cloudwatch Event on the log stream > Lambda that transforms > Write to another log stream. Does add a (little) $ cost.

### Who will this benefit?
People who self-host their dbt runs and want some extra insights into their tasks.

[Embedded metrics spec]: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html

**Comment by drewbanin** [comment]
cool idea @elexisvenator - I totally buy this. I think logic like this probably doesn't belong in a dbt project -- maybe a good version involves tapping into the dbt logger from a script that wraps dbt? Have you seen other projects do a really good job of things like this before?

**Comment by elexisvenator** [comment]
I think the best approach to this would be to pipe the output into something that transforms the output (a la `sed`). I'll have a look into that
