### ISSUE TITLE
Allow log format to be configured from profiles.yml

### ISSUE THREAD

**Issue by elexisvenator** [dbt-labs/dbt-core#1961]
### Describe the feature
Allow the following in profiles.yml config `log_format: text|json`

### Additional context
Allows this to not need to be set for multiple commands in a single run, while also being disabled in one location for development.

### Who will this benefit?
Devs, people with custom pipelines

Might see if I can land this myself over the weekend :)

**Comment by drewbanin** [comment]
cool idea @elexisvenator :)
