### ISSUE TITLE
Invoking dbt as a module

### ISSUE THREAD

**Issue by gouline** [dbt-labs/dbt-core#2013]
### Describe the feature
It would be nice to have a straightforward way of running dbt as a Python module.

To give some context, I use my own build tool https://github.com/gouline/molot that's written in Python and provides basic support for targets, dependencies and arguments. Something half way between Make and Gradle that helps with CI configuration. Things that can be done in Python (e.g. [boto3](https://github.com/boto/boto3), [snowflake-connector-python](https://github.com/snowflakedb/snowflake-connector-python)) are done natively, everything else it just calls shell commands in a subprocess like a Makefile would.

So I'd like a way to invoke multiple dbt commands (e.g. `run` and `docs generate`) in one target by just importing `dbt.main` and calling a function multiple times. The way things are now, `main()` calls `sys.exit()`, which exists my outer build as well, and `handle_and_check()` requires raw command-line arguments passed manually as a list. Ideally, there should be a function of the form `dbt.main.execute(command='run', profiles_dir=PROFILES_DIR, ...)` that would execute a command and throw any exceptions for the caller to handle.

### Describe alternatives you've considered
My current workaround is just invoking dbt command as a subprocess, but it seems like a backward way of doing it, considering that both are Python applications.

### Additional context
Closest thing I could find on the issue tracker was https://github.com/fishtown-analytics/dbt/issues/1488, but that sounds more complex than what I'm proposing.

### Who will this benefit?
This would benefit anyone who orchestrates their builds with Python scripts.

**Comment by drewbanin** [comment]
Hey @gouline - kind of funny we didn't already have an issue for this one :)

We've kicked around the idea of providing a public API for dbt in Python a couple of times now. I'm happy for us to add a public method like `dbt.main.execute(command='run', profiles_dir=PROFILES_DIR, ...)` which implements logic similar to `handle_and_check`.

I'd still like to provide a rich Python-based interface for running dbt projects in the future. I think that would entail model selection, configuration, execution, etc, etc. In this case though, I think a top-level method like `execute` (or similar) gets us moving in the right direction.

Thanks for raising this!

**Comment by Dandandan** [comment]
Hello I like to help out on this issue.
Any pointers on how this should be implemented?

Should it just pass on the args to the parser?

**Comment by picousse** [comment]
This one is pretty old.
Is there any progress on this?

Is there something I/we could help with?

**Comment by ismailsimsek** [comment]
+1  Is there any progress on this?

**Comment by WillemSFV** [comment]
> +1 Is there any progress on this?

I suspect there won't be much progress on this now that DBT Cloud's a thing.

**Comment by ismailsimsek** [comment]
> Hello I like to help out on this issue. Any pointers on how this should be implemented?
> 
> Should it just pass on the args to the parser?

+1

**Comment by jtcohen6** [comment]
This is a fairly old issue. We are finally making progress in this direction, providing a programmatic API into dbt Core: https://github.com/dbt-labs/dbt-core/issues/5527

The ability to invoke dbt as a module (instead of CLI script) isn't explicitly in scope for that initiative, but the big idea— providing a more sensible "main" method as entry-point to Core execution—certainly is.

**Comment by manugarri** [comment]
any updates on this? Seems like it would be easy to implement given how all of dbt-core is python already.

**Comment by jtcohen6** [comment]
@manugarri Check out:
- #6356
- #6381
- #6550

**Comment by joellabes** [comment]
This issue has better google results than the actual feature's docs, so I'm going to leave a pointer here: https://docs.getdbt.com/reference/programmatic-invocations
