### ISSUE TITLE
Calling config.get() within a config() function.

### ISSUE THREAD

**Issue by rpammeraal** [dbt-labs/dbt-core#2101]
The goal is to set the `unique_key` just **once** and reuse it across.

Example 1:
```
{% set unique_key='borrower_address_id' %}
{{ config(materialized='incremental', unique_key=unique_key) }}
{{ config(post_hook="CREATE UNIQUE INDEX IF NOT EXISTS {{ this.table }}_idx ON {{ this }} ({{ unique_key }})")}}
```

**OR** (even better):

```
{{ config(materialized='incremental', unique_key='borrower_address_id') }}
{{ config(post_hook="CREATE UNIQUE INDEX IF NOT EXISTS {{ this.table }}_idx ON {{ this }} ( config.get('unique_key')")}}
```

The latter code is preferred as it does not mix JINJA with non-JINJA contexts. And, above all, the call to `config.get()` should just work, right?

**Comment by drewbanin** [comment]
Thanks for the report @rpammeraal! The first example would be _pretty_ tricky to implement, as the hook config specifically is evaluated in a different context than the rest of the jinja code shown here!

I think it's totally doable and a very good idea for us to support the second example you've shown above:
```
{{ config(materialized='incremental', unique_key='borrower_address_id') }}
{{ config(post_hook="CREATE UNIQUE INDEX IF NOT EXISTS {{ this.table }}_idx ON {{ this }} ( config.get('unique_key')")}}
```

These context questions are sometimes intertwined in ways that aren't obvious at first-blush. If this is straightforward to implement, we should do it! 

If you're in a pinch though, I did want to suggest a potential workaround:


```
{% set unique_key='borrower_address_id' %}
{{ config(materialized='incremental', unique_key=unique_key) }}
{{ config(post_hook="CREATE UNIQUE INDEX IF NOT EXISTS {{ this.table }}_idx ON {{ this }} (" ~ unique_key ~ ")") }}
```

This "hoists" the interpolation of the `unique_key` out of the hook config and into the wrapping `config` call where it _will_ be in scope!

**Comment by drewbanin** [comment]
Let's use this as an opportunity to rationalize the `SourceConfig` module in dbt. It might be a lot, a lot more work than fixing this acute issue, but it will fundamentally make parsing and configuring objects simpler and more consistent in dbt.
