### ISSUE TITLE
Support a flag to override the target and logs directories on the CLI

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-core#2170]
### Describe the feature
Support `--logs-path` and `--target-path` in all dbt invocations (including `dbt rpc`).

These flags will override the destination path for the `logs/` and `target/` directories, respectively.

I think we should add this as a subcommand to `dbt` itself, eg:
```
$ dbt --logs-path log-dir --target-path target-dir
```

**Comment by gh4n** [comment]
Hey i'd be happy to pick this up, could you point me in the right direction ?

**Comment by beckjake** [comment]
Hi @gh4n, that would be awesome! There are a couple changes you'd have to make:
 - In `core/dbt/main.py`, add `--target-path` and `--logs-path` to [main.py](https://github.com/fishtown-analytics/dbt/blob/e8d321cbab3aa7ea93b6b831de4c0539f6ca02cb/core/dbt/main.py#L797), where we add the other arguments to the root command. It should default to `None`.
 - In `core/dbt/config/runtime.py`, add something to the `from_parts` classmethod, probably around [here](https://github.com/fishtown-analytics/dbt/blob/e8d321cbab3aa7ea93b6b831de4c0539f6ca02cb/core/dbt/config/runtime.py#L48), that sets the `target_path` and `log_path` parameters to `cls` to `args.target_path`/`args.log_path` if they're set, and falls back to the value from `project` if not.
 - Unit tests that make sure `RuntimeConfig.from_parts` behaves appropriately given the various permutations of logs/target path being set or not (I don't see any need for an integration test about this).

That'll probably break a number of existing unit tests as well: I know you'll have to update `test/unit/utils.py` to add those parameters to the `Obj` class, but I have a feeling there's at least one other place we create a fake args object as well.

**Comment by gh4n** [comment]
Cool, I've made the fix, will make some changes to the unit tests tonight and raise a PR soon.

**Comment by sumitkumar1209** [comment]
@gh4n is this fix live in any version? Couldn't find it in documentation and ticket is open.
