### ISSUE TITLE
Better Handling of Datatype Changes In Source for Snapshots

### ISSUE THREAD

**Issue by jrandrews** [dbt-labs/dbt-core#2190]
### Describe the feature
Snapshots currently do minimal handling/detection of changes in schema between sources and destination tables. The only thing that is currently checked/handled is when a VARCHAR/STRING-type column increases in size on platforms like Redshift that specify a size for VARCHAR/STRING datatypes. Other changes in datatypes are ignored. If the database can handle coercion of the datatype, such as how BigQuery can handle coercion of NUMERIC to FLOAT64. snapshots will continue to function but there will be no notification of the datatype change.

This happened to us when our sources tables changed all datatypes that were previously FLOAT64 to NUMERIC in BigQuery. This was a good change, by the way -- they should never have been FLOAT64 -- but now we have to handle cleaning it up in the snapshots and downstream.

Actually changing datatypes in snapshot tables based on changes in source datatypes is a complex operation with many potentially high-risk failure modes around loss of data. Also, datatypes and their subtleties are very different across Redshift vs. BigQuery vs. Snowflake vs. whatever other platforms dbt may support in the future. So I do not think that it is a good idea to try to automate actual changes of datatypes in the schemas of snapshot tables.

What dbt _could_ do, however, is to give a warning when a snapshot command is run, and the column in the source table is not the same datatype as the column in the target table. So there would be a warning if the source table has a column that is NUMERIC and the corresponding column with the same name in the destination is FLOAT64, for example. Something like "WARN: Datatypes in source column(s) X, Y, and Z are different than the relevant columns in the destination snapshot table for snapshot A. It is recommended to review and see if manual updates to destination tables are warranted and what the implications of differing datatypes and potential type coercion mean on your database platform."

### Describe alternatives you've considered
I already described why it isn't a good idea to try to automatically change the datatypes.

### Additional context
This would be relevant to every database platform that dbt handles.

### Who will this benefit?
Anyone who uses snapshots and currently may not realize that source datatypes have changed after they started taking snapshots and the destination tables have been created. It's difficult to know exactly what the impact of this would be in all situations, but it ranges from relatively innocuous to potentially causing significant silent data loss.

**Comment by jrandrews** [comment]
Also, we found that when a DATETIME in a source table was changed to TIMESTAMP that snapshots errored out with this error message:

`Database Error in snapshot bb_employee_all_snapshot(snapshots/bb/bb_employee_all_snapshot.sql)  No matching signature for operator < for argument types: DATETIME, TIMESTAMP. Supported signatures: ANY < ANY at [57:18]`

So in a case where a datatype is not coercible to the new datatype, snapshots will throw an error, which is better than silently coercing with who knows what impact.

**Comment by drewbanin** [comment]
Thanks @jrandrews, I think this is a good idea:

> What dbt could do, however, is to give a warning when a snapshot command is run, and the column in the source table is not the same datatype as the column in the target table.

```
WARN: New data has different types than snapshot table types:
 - X (type is INT64, new data has NUMERIC)
 - Y (type is INT64, new data has NUMERIC)
 - Z (type is INT64, new data has NUMERIC)

If the database does not support this type coercion, the snapshot query will fail.
```

You buy that? I think it should be straightforward to implement based on the code we currently have in place around snapshots

**Comment by jrandrews** [comment]
Sounds great to me @drewbanin . Would dbt cloud also then show the snapshot job set status as yellow/"WARN"?

**Comment by drewbanin** [comment]
@jrandrews that might require a little more work, but i certainly think it's worth doing!
