### ISSUE TITLE
dbt deps ugly-fails on older versions of git

### ISSUE THREAD

**Issue by beckjake** [dbt-labs/dbt-core#2221]
### Describe the bug
On older versions of git (it appears to have changed in git 1.8.4.2), `git clone` writes `Cloning into '%s'...` to stdout. Newer versions write it to stderr, and dbt only checks stderr.

We should either check both stderr and stdout for the message, or do a version sanity check on `git` before attempting to clone deps and document that you have to have a modern-ish version of `git` installed. I assume cloning isn't the only place this is an issue. I don't think requiring git >= 1.9 would be all that unreasonable.

### Steps To Reproduce
- Install an ancient version of `git` (good luck with that! I just looked at the source code) 
- Try to run dbt deps in a way that clones github repositories.
- Get an error that dbt never saw `Cloning into ...`.

### Expected behavior
dbt should either tell me to upgrade `git` or read stdout.

### Screenshots and log output
(trimmed, from a user in slack)
```
$ dbt deps
<snipped>
  File "/usr/xxx/pyenvs/dbt_py369/lib64/python3.6/site-packages/dbt/deps/git.py", line 61, in _checkout
    dirname=self._checkout_name
  File "/usr/xxx/pyenvs/dbt_py369/lib64/python3.6/site-packages/dbt/clients/git.py", line 87, in clone_and_checkout
    directory = matches.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

On dbt 0.16.0+, that error will say `'Error cloning {repo} - never saw "Cloning into ..." from git'` instead - same basic problem though!

### System information
**Which database are you using dbt with?**
N/A, not db-specific

**The output of `dbt --version`:**
0.15.x, 0.16.x

**The operating system you're using:**
Any

**The output of `python --version`:**
Any

### Additional context
Reported by a user in slack.

**Comment by drewbanin** [comment]
I'm happy to throw a warning / error if the installed version of git is down-level from where it needs to be. I bet there are.... some other quirks.... that we're depending on to make all things `dbt deps` work correctly too

**Comment by ilkinulas** [comment]
Hello, I want to share a workaround:
In `packages.yml` replacing 

```
- git: "https://github.com/fishtown-analytics/dbt-utils.git"
```

with

```
package: fishtown-analytics/dbt_utils
```

solves the problem for us.
