### ISSUE TITLE
Adapter quoting should use self.Relation.quote_character

### ISSUE THREAD

**Issue by beckjake** [dbt-labs/dbt-core#2243]
### Describe the feature
Currently adapters each have to implement a `quote` method that returns a quoted form of the given identifier. But adapter plugins already define a Relation class that has a `quote_character`, which is associated with the adapter. The base adapter should implement a default quote that just does `''.join([self.Relation.quote_character, value, self.Relation.quote_character])` or similar.

### Describe alternatives you've considered
Adapters can effectively define quote characters twice.

### Additional context
All databases,sort of

### Who will this benefit?
Plugin developers

**Comment by jtcohen6** [comment]
Adapters also have to implement their quote character _again_ for columns by overriding the `quoted` method on the `Column` class. Ideally, we'd have a single place for an adapter to define its quote character, which is then reused across `Relation.quote_character`, `Column.quoted`, and `adapter.quote()`.
