### ISSUE TITLE
Limit parsing of models to only those included in a run

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-core#2257]
### Describe the feature
If a user executes `dbt run -m my_model`, then dbt will currently parse the entire project before running the single `my_model` model. While it may be necessary to parse some _other_ models (ie. those that are referenced by `my_model`), it is generally not the case that _all_ models must be parsed to execute a single model.

There are a couple of benefits of this approach:
 - it should make running models a lot faster on big projects
 - parsing errors in unrelated models won't impact the `dbt run` with a more specific model selector

There are also a couple of downsides of this approach:
 - it's complicated
 - parsing errors in unrelated models won't impact the `dbt run` with a more specific model selector

The fact that unrelated models won't be parsed is both a good and bad thing. It's good in a development workflow - you can be hacking out some in-progress code in one model, while running another unrelated model at the same time. It's bad though in a production env, as it will be a lot easier for models with syntax or compilation errors to make their way into prod.

I'd like to do some experimentation to see what kind of speedup we could expect for very large projects. What % of time is spent parsing unrelated models that aren't considered in the scope of a run for a single model? And how does this compare to the time spent parsing resources like tests/docs/snapshots that will be comparatively harder to identify without actually.... parsing... them?

### Describe alternatives you've considered
Enabling `--partial-parse`ing could be a really good alternative approach here

**Comment by irudson** [comment]
Hi, few pennies to add.

It seem that the feature to allow using variables (var) would play nicely with that selective compiling/parsing of models.
While `--partial-parse` may be an answer in some cases, it won't account for situation when var's change over time (in between runs). So using one or other option (depending on context) would be pretty useful and complementary to one another in my opinion.

**Comment by kofron** [comment]
@drewbanin did you get to results on the analysis you mention in your post?  I'm wishing for this feature on a daily basis and would love to know if other folks are still interested in it.

**Comment by drewbanin** [comment]
hey @kofron - we've definitely been doing some performance analysis lately. I think this issue is a really good candidate and I'd be excited to ship something that addresses this use case! Also, we're going to take some passes at improving dbt's performance for large projects more broadly over the next couple of releases :)

**Comment by tom-juntunen-adsk** [comment]
Any updates? 

I have 3273 models, 3228 tests, 69 snapshots, 0 analyses, 448 macros, 2 operations, 56 seed files, 1283 sources, 15 exposures, 0 metrics 

and my timing.txt looks like this: 
<img width="1712" alt="Screen Shot 2022-09-01 at 11 01 26 AM" src="https://user-images.githubusercontent.com/109989510/187982225-6a789c95-5c0d-45a7-bd1c-4d1e8df4cf78.png">

I want to improve both the _thread.lock.acquire() time (15s) and the load_manifest() time (25s).

At least when partial parsing occurs, the load_manifest() time goes away. But still I see the _thread.lock.acquire() time between 15 - 20s with 4 threads, and when bumping up to 8 threads it only goes down to ~11s.

When developing new models, that 25s load_manifest() time is where I think we can have the most improvement through limiting the number of files that need to be parsed somehow. 

Are any updates related to load_manifest() on another issue?
