### ISSUE TITLE
Custom data test blocks

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-core#2274]
### Describe the feature
dbt should provide a first-class block for custom data tests. This would allow tests to be configured alongside models, for instance.

Example syntax:
```
{% test my_test_name %}

{{ config(...) }}

select ...

{% endtest %}
```

Beyond the addition of this tag, custom data tests should remain working how they have historically worked.

**Comment by clrcrl** [comment]
Note that this is the same syntax you've described for schema tests in #1173
