### ISSUE TITLE
Make zip function available in Jinja

### ISSUE THREAD

**Issue by friendofasquid** [dbt-labs/dbt-core#2345]
Would like to use zip to loop over some results in a Jinja template

```
{% for j,k in zip(a, b) %
```

Currently zip is not available, but would make my code a much cleaner.

**Comment by drewbanin** [comment]
Thanks for opening this issue @friendofasquid!

I can buy either:
1. Adding `zip` to the context directly, or
2. Adding it under a namespace

I think if we're only going to add `zip`, then adding it to the context directly makes sense. If we're instead going to add other Python builtin functions in the future (like `set()`, `dict()`, `tuple()`, or similar) then we'd be better off namespacing the functions to avoid polluting the global namespace.

I think I'd be in favor of adding `set` at the very least -- maybe we would also benefit from:
 - `all()`
 - `any()`

As far as namespaces go, we already have a `builtins` namespace, so we could probably add `builtins.zip` with a single line of code :D

Do you have any thoughts / preferences / ideas? Curious to hear what you think

**Comment by friendofasquid** [comment]
I don’t know enough about Jinja templating to comment. 

My gut would be to have a set of things that aren’t namespaces, mostly because I think dbt is a lot of people’s first time writing code that isn’t SQL.

**Comment by mathcoder3141** [comment]
@drewbanin bumping this back up to see if this can be done

**Comment by jtcohen6** [comment]
I buy the utility of this one, especially `zip()` + `set()`. There have been a handful of times I'd wanted to use `set` logic in particular ([example](https://github.com/dbt-labs/dbt-core/blob/13571435a319d6237bfc414ef15f27e23f0729db/core/dbt/include/global_project/macros/materializations/models/incremental/column_helpers.sql#L20-L35)).

I also think the initial reservation may not be as much of an issue, given how we construct `builtins`: Every method decorated `@contextmember` gets added to both the global namespace _and_ the `builtins` namespace. If ever a user wanted to customize the `set()` macro, they could do it by writing a macro named `set()` that references `builtins.set()`. That's (my understanding of) how overrides for `ref`, `source`, `config` work today, and : https://docs.getdbt.com/reference/dbt-jinja-functions/builtins.

The code here can be a _little_ bit tricky, but the basic implementation should look a lot like [the `tojson` method](https://github.com/dbt-labs/dbt-core/blob/13571435a319d6237bfc414ef15f27e23f0729db/core/dbt/context/base.py#L394-L417):
- Decorated with `@staticmethod` + `@contextmember`
- Perform the Python operation (`zip()`, `set()`, etc) and return the value
- Tested in [`test/unit/test_context.py`](https://github.com/dbt-labs/dbt-core/blob/13571435a319d6237bfc414ef15f27e23f0729db/test/unit/test_context.py#L181)

I'm going to open this one back up, and mark it as `help_wanted` (a.k.a. "good second issue," for a community contributor who's comfortable writing a bit of Python)
