### ISSUE TITLE
Server closed the connection unexpectedly for Postgres12

### ISSUE THREAD

**Issue by MondeSinxi** [dbt-labs/dbt-core#2352]
### Describe the bug
When running long dbt runs (20 minutes or so) I get an error message that the server has closed the connection unexpectedly after building the last model. The on-run-end hooks also don't run after the last model is built. I'm using dbt to build tables/views for Postgresql 12.

All tables/views are created in the database and there are no errors reported for any of the models run.  

This seems to have been fixed for Snowflake and Redshift in #657

### Steps To Reproduce
A simple `dbt run`  with the following at the on-run-end in the `dbt_project.yml` file.
```  
on-run-end:
  - "{{ log_results(results) }}"
```

### Expected behavior
I expect dbt to run and log results at the end of the run

### Screenshots and log output
```
...
 42 of 42 OK created view model store.funds........ [CREATE VIEW in 0.84s]
Database error while running on-run-end
Encountered an error:
   Database Error
      server closed the connection unexpectedly
          This probably means the server terminated abnormally
          before or while processing the request.
```

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.14.2
```

**The operating system you're using:**

**The output of `python --version`:**
```
Python 2.7.13
```
### Additional context
I'm running dbt in a Docker version 19.03.8

**Comment by drewbanin** [comment]
hey @MondeSinxi - thanks for opening this issue. It sounds like the connection to Postgres is being terminated after some relatively-long timeout. I don't think I've seen reports of this happening before on Postgres!

I do see that dbt is still using the `master` connection, but I could have sworn that we fixed this for _all_ plugins, not just Redshift and Snowflake as you noted above. The fix here would either be to:
- open a new connection for the on-run-end hooks, or
- refresh the connection before running queries in the on-run-end hooks

Do you happen to know if you have any Postgres settings `idle_in_transaction_session_timeout` or `statement_timeout` enabled for your user / database in Postgres?

**Comment by MondeSinxi** [comment]
Hi @Drewbanin, sorry for waiting so long before replying. I've just checked my `postgresql.conf` file that contains all the default configurations and the defaults for both `idle_in_transaction_session_timeout` and `statement_timeout` are set to zero. I'll change these to 1000 milliseconds, `run dbt` and hopefully end up without errors

**Comment by fabiopaiva** [comment]
I'm having the same problem, any update on this?

**Comment by giacomochiarella** [comment]
having the same issue. I've set `keepalives_idle: 10` and (I don't know if this option is available in the profiles.yml) `keepalives_interval: 20` but still gives the same error

**Comment by rm-minus-r-star** [comment]
This is a chronic problem for me. From one identical `dbt run` to the next it can run flawlessly, or fail, sometimes quickly, and sometimes only after hanging for ages midway with
20:53:15    Database Error in XXX (SSS/XXX)
  server closed the connection unexpectedly
  	This probably means the server terminated abnormally
  	before or while processing the request.
  server closed the connection unexpectedly
  	This probably means the server terminated abnormally
  	before or while processing the request.

Doubly irritating is that a failure still qualifies as success when running out of a shell script (within a container), and so far I haven't been able implement a re-run or abort of the sequence as a work-around.

**Comment by mlcruz** [comment]
Same problem here, happens a lot, mostly when we are doing full builds of incremental views or something that takes longer. After like 300s it fails pretty much always.
