### ISSUE TITLE
Add json_schema to validate .yml files

### ISSUE THREAD

**Issue by DmitryMaletin** [dbt-labs/dbt-core#2459]
### Describe the feature 
There are many  editors right now have support of LanguageServiceProtocal (lsp).
As for now Yaml & JSON both have dedicated lsp implemantation.
As an example [VScode has an extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml):  
## Features
![screencast](https://raw.githubusercontent.com/redhat-developer/vscode-yaml/master/images/demo.gif)

1. YAML validation:
    * Detects whether the entire file is valid yaml
    * Detects errors such as:
        * Node is not found
        * Node has an invalid key node type
        * Node has an invalid type
        * Node is not a valid child node
2. Document Outlining (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd>):
    * Provides the document outlining of all completed nodes in the file
3. Auto completion (<kbd>Ctrl</kbd> + <kbd>Space</kbd>):
    * Auto completes on all commands
    * Scalar nodes autocomplete to schema's defaults if they exist
4. Hover support:
    * Hovering over a node shows description *if provided by schema*
5. Formatter:
    * Allows for formatting the current file

*Auto completion and hover support are provided by the schema. Please refer to Language Server Settings to setup a schema*

[Draft version of json schema for DBT ](https://gist.github.com/DmitryMaletin/477d152c1880b45ef41109cc812f750a)

Register schema in vscode:
"yaml.schemas": { "~/schemas/dbt_schema.json": ".schema.yml" },

### Who will this benefit?
Anybody who uses vscode/atom/emacs etc. to edit model.
It will allow to improve productivity of creating and modifying yml/json and avoid a lot of error 
It also allow to have validation and autocomplete  for customized  meta properties.

**Comment by watermanio** [comment]
This would be super useful.

**Comment by drewbanin** [comment]
hey @DmitryMaletin - this is awesome! I spent a couple of mins playing around with something like this evening. I just want to your attention to [a script in the dbt codebase](https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/scripts/collect-artifact-schema.py) that could help with something like this in the future. This script uses dbt's internal dataclasses to generate a json schema for the _artifacts_ produced by dbt.

I don't think we actually have a proper json schema internally that represents the spec for the schema.yml file. Instead, we kind of mix together 1) the input yml provided by users and 2) metadata attached to nodes by dbt as files are parsed.

Here's a _super_ quick version of this. It won't really work for this specific use-case, but I think we're not so far away from being able to automate something like this :)

-----

setup:
```
python3 -m venv env
source env/bin/activate
pip install dbt
```

Then run:
```
#!/usr/bin/env python
from dataclasses import dataclass
from typing import Dict, Any
import json

from hologram import JsonSchemaMixin
from dbt.contracts.graph.unparsed import UnparsedNodeUpdate


model_schema = UnparsedNodeUpdate.json_schema()
print(json.dumps(model_schema))
```

Note the inclusion of fields like `original_file_path` and `yaml_key` in the resulting document. I don't think it will be super hard to build a version of these schemas that omits those dbt-generated fields. We'll also probably want to include human readable descriptions (we can definitely do that).

Thanks for opening this one -- it took me about a month to get around to this. Check out the relevant code [here]https://github.com/fishtown-analytics/dbt/blob/eea51bee30d79054637b2adfffc8d3fb0cf99ce3/core/dbt/contracts/graph/unparsed.py#L119) and let us know what you think :)

**Comment by DmitryMaletin** [comment]
Hi @drewbanin 
Thank you for advice. I will have a look to suggested codes.

**Comment by darrenhaken** [comment]
This looks great to me, any progress on it?

**Comment by kwigley** [comment]
I think this can easily be accomplished for folks using VSCode using https://www.schemastore.org/json/!

**Comment by asm0dey** [comment]
I've found something, but it's rudimentary: https://app.rakam.io/schema/dbt.schema.json
Did anything better appear?

**Comment by joellabes** [comment]
Due to the shape of our YAML it can't be automatically generated, but I'm hoping to spend some time next month fleshing out a more robust schema version 🤞

**Comment by asm0dey** [comment]
Indeed, custom tests can't be checked as well as anything related to file structure. But something can be :)

**Comment by alexrosenfeld10** [comment]
any news on this? Would love to have some intellisense in vs code 😄

**Comment by joellabes** [comment]
@clrcrl and I paired up last week and got the bones of a schema up and going! It's sitting at https://github.com/dbt-labs/dbt-jsonschema for anyone who wants to follow along/contribute

**Comment by joellabes** [comment]
Just published a mostly complete schema to https://github.com/dbt-labs/dbt-jsonschema! 

There's definitely room to keep fleshing it out, especially around descriptions and sample values. Anyone is welcome to open PRs against the repo. 

Demo Loom: https://www.loom.com/share/7dd4dfc67765441b80ff454942f59b63
