### ISSUE TITLE
better dbt error messages

### ISSUE THREAD

**Issue by rameesraja** [dbt-labs/dbt-core#2538]
### Describe the bug
dbt threw an error, after our latest merge into the repository. We later realized that, it was because of missing quotes in cluster by config array. But, to identify this error, we had to remove models in trial and error to isolate the error. We would like more descriptive error message for easier isolation and fix. 

```
Running with dbt=0.16.1
Encountered an error:
cannot pickle '_thread.RLock' object
```

### Steps To Reproduce

1) Using version 0.16.1
2) In the model config give the cluster by config as below
{{  
    config(
        cluster_by = [column1, column2, column3]
    )
}}
3) Run any model and you will get below dbt error.

### Expected behavior

We wanted to error message to clearly say, where the issue was.

### Screenshots and log output
```
Running with dbt=0.16.1
Encountered an error:
cannot pickle '_thread.RLock' object
```

### System information
**Which database are you using dbt with?**

- Snowflake

**The output of `dbt --version`:**
```
0.16.1
```

**The operating system you're using: ** windows

**The output of `python --version`:** 3.8.2

**Comment by drewbanin** [comment]
hey @rameesraja - thanks for opening this issue. When I try running the code you've shown above, I see an error like:
```
Compilation Error in model issue2538 (models/issue2538.sql)
  'column1' is undefined
```

The model I'm running looks like:
```
{{
    config(
    cluster_by = [column1, column2, column3]
    )
}}

select 1 as id
```

Can you tell me what the actual columns you used in your `cluster_by` config were? I suspect this column name might have collided with a dbt internal context variable. I can reproduce the behavior you're seeing if I run something like:
```
{{ config(cluster_by=adapter) }}

select 1 as id
```

So, maybe the fix here is just going to be to add type validation at the config level. I think a great error message here would say:
```
Compilation Error in model issue2538 (models/issue2538.sql)
    Incorrect type provided for cluster_by: expected List[str], got <class 'dbt.adapters.bigquery.impl.BigQueryAdapter>'
```

or something like that, anyway

**Comment by rameesraja** [comment]
This was the config which caused the error. Probably its the column name 'source'
{{  
    config(
        cluster_by = [source, child_entity, dayd]
    )
}}

**Comment by jtcohen6** [comment]
I might be silly for thinking this, but don't the column names need to be passed as strings? They're not Jinja variables:
```sql
{{
config(
cluster_by = ['source', 'child_entity', 'dayd']
)
}}
```

**Comment by rameesraja** [comment]
@jtcohen6 : yes it was a mistakes by one of our developers. But the error message was not descriptive enough and that's why this issue is raised for.

**Comment by drewbanin** [comment]
yep - let's add validation that the args for `cluster_by` are stringy - I think we have type information for all of these configs now, we just need to validate the user-provided info with the type information encoded in the config classes.
