### ISSUE TITLE
Template models for dbt

### ISSUE THREAD

**Issue by rameesraja** [dbt-labs/dbt-core#2551]
### Describe the feature
Template models which lets us pass parameters, which are replaced while deploying.  We usually build aggregated models by frequencies like ('week','month','quarter','year') for our fact tables. To do this we have to build separate models for each frequency. If we can support template models, which will be let us pass frequency as a parameter it will be helpful.

Example:

**{frequency}ly_sales.sql**
```
{{
     config(frequencies = ['week','month']

}}

select 
       date_trunc({frequency}, current_timestamp()) as sales_date,
       sum(sales) as sales
from sales

```
this code should deploy two models in the DW, weekly and monthly repectively.

### Describe alternatives you've considered
We could achieve this using macros. But I believe, these wont be included in the DAG.

### Who will this benefit?
This falls under our strategy of DRY. If there is a change, we will just have to update one model.

**Comment by drewbanin** [comment]
Thanks for opening this issue up @rameesraja. See also #1637 -- I think there's a lot of overlap between these two proposals!

**Comment by z3z1ma** [comment]
You can just use macros for that? Those are templated pieces of
parameterized SQL. I use them for that purpose, not necessarily for a whole
model though you probably could passing the ref.

**Comment by z3z1ma** [comment]
In airflow,
```sh
dbt --run-operation shard '{"template": "file.sql", "shard": "monthly"}' >> monthly_data.sql
dbt --run-operation shard '{"template": "file.sql", "shard": "weekly"}' >> weekly_data.sql
dbt --run-operation shard '{"template": "file.sql", "shard": "daily"}' >> daily_data.sql 
```
here you edit a single file to update all of these yet they still sit in the current design as independent manifested model files.

alternatively, this might work
```bash
for i in $(dbt --run-operation get_shards); do
    dbt --run-operation shard '{"template": "file.sql", "shard": "$i"}'  >> $i_data.sql
done
```
where `get_shards.sql` is a macro that logs unique values from a table to be used in generating shard models

Not optimal, sure. Cool though.
