### ISSUE TITLE
No copyright statement

### ISSUE THREAD

**Issue by stefan-hdt** [dbt-labs/dbt-core#2724]
Hello,

after looking into your project, I could not find any information for copyright holder. So I am wonderung whether this information is missing on purpose or not, and if you require any copyright/author statement when someone uses your code.

Thanks for letting me know.

Stefan

**Comment by jtcohen6** [comment]
Hey @stefan-hdt, dbt is licensed under [Apache License 2.0](https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/License.md). It sounds like you'll want to look at item 4, "Redistribution."

We also require that all external contributors sign a [Contributor License Agreement](https://docs.getdbt.com/docs/contributing/contributor-license-agreements/) before we can merge their code.

Does that answer your question?

**Comment by stefan-hdt** [comment]
Hey @jtcohen6, The question is who the copyright holder of dbt is and whether he or she wants to have a copyright statement mentioned when dbt is used by licensees. The Apache-2.0 license states - from my perspective - that only in the source code version copyright statements in the source code have to be retained.  In binary form, a copyright statement only has to be distributed with the software when found in a NOTICE file.

In file https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/License.md, there is no copyright statement at the end of the license text.
