### ISSUE TITLE
'NoneType' object has no attribute 'type' after running dbt run

### ISSUE THREAD

**Issue by kamleshsinhchauhan** [dbt-labs/dbt-core#2755]
### Describe the bug
I am trying to configure source control with dbt for snowflake. dbt debug is working fine. but when I am trying to do dbt run,

its giving below error,

'NoneType' object has no attribute 'type'

### Steps To Reproduce

Running with dbt=0.17.2
* Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - projectname

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0
Found 1 model, 0 tests, 0 snapshots, 0 analyses, 147 macros, 0 operations, 0 seed files, 2 sources

15:22:39 | Concurrency: 1 threads (target='dev')
15:22:39 |
15:22:39 | 1 of 1 START persistent_table model PUBLIC.CONTACT................... [RUN]
Unhandled error while executing model.datawarehouse_SF.CONTACT
'NoneType' object has no attribute 'type'
15:22:39 | 1 of 1 ERROR creating persistent_table model PUBLIC.CONTACT.......... [ERROR in 0.11s]
15:22:43 |
15:22:43 | Finished running 1 persistent_table model in 14.05s.

Completed with 1 error and 0 warnings:

'NoneType' object has no attribute 'type'

### Expected behavior
It was working fine earlier and suddenly I got this error without any kind of change.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by jtcohen6** [comment]
Hey @kamleshsinhchauhan, it's hard to help here without knowing more about the specific Jinja you're defining + queries you're running. I see that you're using a custom materialization, `persistent_table`.

Errors like `'NoneType' object has no attribute 'type'` are often an indicator that you're using `run_query` or a `statement` block and operating on the result in Jinja. If you're not conditioning that Jinja logic on `execute` ([docs](https://docs.getdbt.com/reference/dbt-jinja-functions/execute/)), you may be getting `None` where you don't expect it.

**Comment by friendofasquid** [comment]
@kamleshsinhchauhan — I ran into a similar issue. Mine was `'NoneType' object has no attribute 'response'` when coding a custom materialisation. My googling led me to this issue.

For me, making sure to name the `statement` block generating the model as `main` seems to have made my problem go away. Not sure if this will be the case for you, but here's hoping.

I wish this was better documented.

**Comment by niravparikh** [comment]
> @kamleshsinhchauhan — I ran into a similar issue. Mine was `'NoneType' object has no attribute 'response'` when coding a custom materialisation. My googling led me to this issue.
> 
> For me, making sure to name the `statement` block generating the model as `main` seems to have made my problem go away. Not sure if this will be the case for you, but here's hoping.
> 
> I wish this was better documented.

this comment saved me a lot of headache, was struggling to get rid of this issue.. Thanks @friendofasquid
