### ISSUE TITLE
Snowflake: empty query causes dbt to fail unhelpfully

### ISSUE THREAD

**Issue by beckjake** [dbt-labs/dbt-core#2770]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

I tried to `dbt compile` a model that had (effectively) `{% if execute %}{% do run_query('') %}{% endif %}` in it. 
dbt crashed with a "cannot unpack" error:

```
Encountered an error:
Runtime Error
  Compilation Error in model model (models/model.sql)
    cannot unpack non-iterable NoneType object

    > in macro run_query (macros/etc/query.sql)
    > called by macro statement (macros/core.sql)
    > called by model model (models/model.sql)
```

It also logs `got empty sql statement, moving on` at debug level, but this is not really what I'd consider "moving on".

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

```
$ cat models/model.sql
{% if execute %}
{% do run_query("") %}
{% endif %}
select 1 as id
$ dbt compile --target=snowflake
```

### Expected behavior

On postgres I get a nice error:
```
Encountered an error:
Runtime Error
  Database Error in model model (models/model.sql)
    can't execute an empty query
```

On bigquery I get this, which is also a reasonably nice error:
```
Encountered an error:
Runtime Error
  Database Error in model model (models/model.sql)
    Syntax error: Unexpected end of statement at [1:134]
```

That seems like pretty reasonable behavior!

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.18.0
```

I believe that on some level, this issue goes back a very long time, possibly as long as snowflake has been supported.

**The operating system you're using:**
macos catalina

**The output of `python --version`:**
Python 3.8.2

### Additional context
I think this is caused by the snowflake exception handler. We have this bit inside the exception handler of the context manager:
```
            if 'Empty SQL statement' in msg:
                logger.debug("got empty sql statement, moving on")
```

But then it never re-raises or raises an exception.

This means that we suppress the exception and return None, but what's the caller supposed to do about this case? I can see a few possibilities:
 - this should result in an error, like in postgres/bigquery
 - if empty queries are expected for some reason, then maybe `exception_handler` should return dummy values?
 - otherwise, I guess users of `exception_handler` need to handle this case

**Comment by jtcohen6** [comment]
Does the "special" handling for empty queries on Snowflake have anything to do with the [need to split queries](https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/plugins/snowflake/dbt/adapters/snowflake/connections.py#L298-L301) that contain `;`?

I agree, I think this should result in a more straightforward error.

**Comment by eugenetian** [comment]
Was this ever solved?

**Comment by Koning92** [comment]
Having the same issue still
