### ISSUE TITLE
Structured Logging (for JSON)

### ISSUE THREAD

**Issue by steffkes** [dbt-labs/dbt-core#2915]
Hey all, this is my very first issue - so please bear with me :) I've checked open as well as closed issues around the keywords I'd suspect to match and blame'd the files in question to get an idea what previous ones could be relevant.

### Describe the feature

The logging that is currently in place seems to be mainly tailored for human beings reading the output, which is absolutely okay - but makes it way harder to process the generated logs programmatically.

**In the end I'd like to present proper error reasons around failed models with all the relevant information in one record.**

running the tests with `dbt --log-format=json test` for example generates the following in `logs/dbt.log`:

```
2020-11-24 09:09:04.745841 (MainThread): Warning in test not_null_finance__some_statuses_per_day_pan (models/marts/finance/finance__some_statuses_per_day.yml)
2020-11-24 09:09:04.750021 (MainThread):   Got 55169 results, expected 0.
2020-11-24 09:09:04.755953 (MainThread):
2020-11-24 09:09:04.758927 (MainThread):   compiled SQL at target/compiled/project/models/marts/finance/finance__some_statuses_per_day.yml/schema_test/not_null_finance__some_statuses_per_day_pan.sql
```

while on `STDOUT` we get (pretty printed for easier reading):

```json
{
  "timestamp": "2020-11-24T09:09:04.745841Z",
  "message": "\u001b[33mWarning in test not_null_finance__some_statuses_per_day_pan (models/marts/finance/finance__some_statuses_per_day.yml)\u001b[0m",
  "channel": "dbt",
  "level": 13,
  "levelname": "WARNING",
  "thread_name": "MainThread",
  "process": 5382,
  "extra": {
    "run_started_at": "2020-11-23T14:42:09.667614+00:00",
    "invocation_id": "0ccc471d-b39e-4387-ae44-362094d1ad0a",
    "is_status_message": true,
    "run_state": "internal"
  }
}
{
  "timestamp": "2020-11-24T09:09:04.750021Z",
  "message": "  Got 55169 results, expected 0.",
  "channel": "dbt",
  "level": 14,
  "levelname": "ERROR",
  "thread_name": "MainThread",
  "process": 5382,
  "extra": {
    "run_started_at": "2020-11-23T14:42:09.667614+00:00",
    "invocation_id": "0ccc471d-b39e-4387-ae44-362094d1ad0a",
    "is_status_message": true,
    "run_state": "internal"
  }
}
{
  "timestamp": "2020-11-24T09:09:04.758927Z",
  "message": "  compiled SQL at target/compiled/project/models/marts/finance/finance__some_statuses_per_day.yml/schema_test/not_null_finance__some_statuses_per_day_pan.sql",
  "channel": "dbt",
  "level": 11,
  "levelname": "INFO",
  "thread_name": "MainThread",
  "process": 5382,
  "extra": {
    "run_started_at": "2020-11-23T14:42:09.667614+00:00",
    "invocation_id": "0ccc471d-b39e-4387-ae44-362094d1ad0a",
    "is_status_message": true,
    "run_state": "internal"
  }
}
```

it originates from those lines:

https://github.com/fishtown-analytics/dbt/blob/daff0badc82362d805bce0a2cc8a59701ab1fefb/core/dbt/task/printer.py#L290-L302

and i cannot even relate those lines because they have no common property. 

I was toying around with the idea to refactor the way that this logging works. Which would allow the log output stay unchanged while the structure output in json could receive way more information. For the first shot probably just all available information in Logbook's `extra` dict - nothing too fancy.

### Describe alternatives you've considered

Nothing that comes to mind initially, while I'm open for different ideas to get the information I'm looking for

### Additional context

To my understanding this could/should be a very generic thing, that is - depending on the implementation - not changing much for anyone using the default configuration.

### Who will this benefit?

Everyone consuming logs in a different format that primarily is interesting for accessing it programmatically. Also everyone who is using any kind of logging service - it would allow people to access aggregated information in one record, rather than splattered over multiple lines

### Are you interested in contributing this feature?

I've been in touch with dbt only as a User/Admin until now, but have already started to dig into the code base and would like to help - given your assistance and feedback.

**Comment by jtcohen6** [comment]
Hey @steffkes, thanks for the thorough writeup! This is a totally reasonable desire.

Have you tried running with:
```
dbt --debug --log-format=json test
```
From the [docs](https://docs.getdbt.com/reference/global-cli-flags/#log-formatting):
> Use the json formatting value in conjunction with the `--debug` flag to produce rich log information which can be piped into monitoring tools for analysis.

You can also write those logs to a file:
```
dbt --debug --log-format=json > logs.json test
```
Then parse that file by `extra.unique_id` to split out debug-level logs for each model/test/resource. This is more or less the mechanism by which the dbt Cloud IDE displays detailed logs to users.

**Comment by steffkes** [comment]
Hey @jtcohen6,

thanks for getting back to me that quick, appreciate it! I've been running the task again with an additional `--debug` flag and have to say I'm seeing nothing different - at least not for the lines where i would assume interesting information are outputted:

```json
{
  "timestamp": "2020-11-26T10:23:07.082450Z",
  "message": "\u001b[33mWarning in test not_null_finance__some_statuses_per_day_pan (models/marts/finance/finance__some_statuses_per_day.yml)\u001b[0m",
  "channel": "dbt",
  "level": 13,
  "levelname": "WARNING",
  "thread_name": "MainThread",
  "process": 59,
  "extra": {
    "run_started_at": "2020-11-26T09:59:10.769456+00:00",
    "invocation_id": "5b0ebb92-6637-44bd-9e0c-ec673f121555",
    "is_status_message": true,
    "run_state": "internal"
  }
}
{
  "timestamp": "2020-11-26T10:23:07.084797Z",
  "message": "  Got 55169 results, expected 0.",
  "channel": "dbt",
  "level": 14,
  "levelname": "ERROR",
  "thread_name": "MainThread",
  "process": 59,
  "extra": {
    "run_started_at": "2020-11-26T09:59:10.769456+00:00",
    "invocation_id": "5b0ebb92-6637-44bd-9e0c-ec673f121555",
    "is_status_message": true,
    "run_state": "internal"
  }
}
{
  "timestamp": "2020-11-26T10:23:07.094965Z",
  "message": "  compiled SQL at target/compiled/project/models/marts/finance/finance__some_statuses_per_day.yml/schema_test/not_null_finance__some_statuses_per_day_pan.sql",
  "channel": "dbt",
  "level": 11,
  "levelname": "INFO",
  "thread_name": "MainThread",
  "process": 59,
  "extra": {
    "run_started_at": "2020-11-26T09:59:10.769456+00:00",
    "invocation_id": "5b0ebb92-6637-44bd-9e0c-ec673f121555",
    "is_status_message": true,
    "run_state": "internal"
  }
}
```

While i do see some `.extra.uniqe_id` i have an overwhelming amount of `null`s there: the original log contained 1609 lines, the debug one 8319, 641 of them `null` .. the remaining ones are ranging between eleven to thirteen lines per test (I assume).

Given our (and i think others as well) logging the issue is still the same - i see one entity/record/information splattered over multiple lines, even having different `LEVEL`s assigned to them. I don't really see how this would be fixed running it with `debug` enabled?

As i understand logging:

1) the highest log-level should be used for everything (either it's an error or not? and if it is, everything of it should be)
2) human readable output is absolutely great (but it's only about the format you display, not the events you emit)
3) events are supposed to be atomic (everything related to the "thing" that happened in one place)

And i'm curious to understand the way the dbt Cloud does handle it!

> Then parse that file by `extra.unique_id` to split out debug-level logs for each model/test/resource. This is more or less the mechanism by which the dbt Cloud IDE displays detailed logs to users.
> 
> E.g.:
> 
> ```shell
> dbt -d --log-format json > logs.json run -m stg_orders
> cat logs.json | jq '. | select(.extra.unique_id=="model.jaffle_shop.stg_orders")'
> ```
> 
> I'm going to close this issue, but please continue to comment here if there are pieces missing from JSON-formatted debug logs that you'd like to see added.

this helps to select one single model, how do you find the relevant models in the first place? The way I look at it, it starts below the line saying:

```
Completed with N warnings
```

where you typically have no timestamps anymore, but a summary of relevant things. everything above is nice to have, but given the way it's formatted & displayed even harder to parse out relevant information

**Comment by steffkes** [comment]
Don't want to get lost in the details ... I've tuck a stab at this https://github.com/fishtown-analytics/dbt/compare/dev/kiyoshi-kuromiya...steffkes:feature/2915-structured-logging :

```diff
--- a/core/dbt/task/printer.py
+++ b/core/dbt/task/printer.py
@@ -281,26 +281,37 @@ def print_run_result_error(
             color = ui.red
             info = 'Failure'
             logger_fn = logger.error
-        logger_fn(color("{} in {} {} ({})").format(
+
+        messages = [color("{} in {} {} ({})").format(
             info,
             result.node.resource_type,
             result.node.name,
-            result.node.original_file_path))
+            result.node.original_file_path
+        )]
+
+        extra = {
+            'info': info,
+            'name': result.node.name,
+            'file_path': result.node.original_file_path,
+            'resource_type': result.node.resource_type,
+        }
 
         try:
             int(result.status)
         except ValueError:
-            logger.error("  Status: {}".format(result.status))
+            logger_fn = logger.error
+            messages.append("  Status: {}".format(result.status))
         else:
             status = utils.pluralize(result.status, 'result')
-            logger.error("  Got {}, expected 0.".format(status))
+            messages.append("  Got {}, expected 0.".format(status))
 
         if result.node.build_path is not None:
-            with TextOnly():
-                logger.info("")
-            logger.info("  compiled SQL at {}".format(
+            extra["build_path"] = result.node.build_path
+            messages.append("  compiled SQL at {}".format(
                 result.node.build_path))
 
+        logger_fn("\n".join(messages), extra=extra)
+
     else:
         first = True
         for line in result.error.split("\n"):
```

that doesn't change the `logs/dbt.log` not by much:

```
2020-11-26 12:50:56.665579 (MainThread): Warning in test not_null_finance__some_statuses_per_day_pan (models/marts/finance/finance__some_statuses_per_day.yml)
  Got 55169 results, expected 0.
  compiled SQL at target/compiled/project/models/marts/finance/finance__some_statuses_per_day.yml/schema_test/not_null_finance__some_statuses_per_day_pan.sql
```

but would generate one log entry like this:

```json
{
  "timestamp": "2020-11-26T12:50:56.665579Z",
  "message": "\u001b[33mWarning in test not_null_finance__some_statuses_per_day_pan (models/marts/finance/finance__some_statuses_per_day.yml)\u001b[0m\n  Got 55169 results, expected 0.\n  compiled SQL at target/compiled/project/models/marts/finance/finance__some_statuses_per_day.yml/schema_test/not_null_finance__some_statuses_per_day_pan.sql",
  "channel": "dbt",
  "level": 13,
  "levelname": "WARNING",
  "thread_name": "MainThread",
  "process": 22851,
  "extra": {
    "info": "Warning",
    "name": "not_null_finance__some_statuses_per_day_pan",
    "file_path": "models/marts/finance/finance__some_statuses_per_day.yml",
    "resource_type": "test",
    "build_path": "target/compiled/project/models/marts/finance/finance__some_statuses_per_day.yml/schema_test/not_null_finance__card_statuses_per_day_pan.sql",
    "run_started_at": "2020-11-26T12:49:34.410019+00:00",
    "invocation_id": "e83ba4af-a60b-4229-aca2-433230436a2b",
    "is_status_message": true,
    "run_state": "internal"
  }
}
```

which would allow you way more in terms of aggregating and filtering stuff, don't you think @jtcohen6 ?

It's probably not the way it should/would be implemented in the end, more like a quick way to demonstrate the idea i had in mind - without changing to much of the existing code, making it easy/easier to follow it.

**Comment by jtcohen6** [comment]
@steffkes Thanks for that sample code and those snippets, I have a better sense now of what you're after. Have you looked at using `run_results.json` (likely saved in your `target/` directory)? After you run `dbt test`, that file offers a highly structured JSON blob with one record per test, including status, error message, timing, file paths, etc. It should offer you much by way of aggregation and filtering.

My only word of caution there would be that we're in the process of reworking its structure (#2493); in so doing, we're committed to maintaining and versioning it in future releases.

**Comment by steffkes** [comment]
Thanks for pointing to #2493 @jtcohen6 , I've discovered that along the `run_results.json` file itself. While i would be able to get all the relevant information for what i need right now from there as well:

my initial question about structured logging is still valid.

because in the current situation there is close to no additional value in logging json. the `message` is exactly the same and the provided attributes are .. well, they are there, but not really helping in my opinion. they probably even fulfill a different use case, when I'm thinking about logging.

Does referencing the `run_results` mean that there's no interest in improving the structured logging? If so, I'm okay with that (kind of) rather like to know now than later; because than I'm not working on it any longer. Solving my current thing and be done with it - no offense.

**Comment by jtcohen6** [comment]
@steffkes Here's how I'm thinking about this:

**dbt artifacts** should be the go-to place for metadata about specific dbt resources, both to inspect specific runs and to power longitudinal analysis of that metadata. In dbt v0.19.0 and all releases to follow, we are committed to versioning, documenting, and maintaining [dbt artifacts](https://next.docs.getdbt.com/reference/artifacts/dbt-artifacts/) (`manifest.json`, `catalog.json`, `run_results.json`, `sources.json`).

By contrast, **dbt logs** should be the go-to source of operational information about a specific run. A human being or an orchestration tool should be able to inspect the exit code and logs to answer:
- Did the overall run succeed or fail?
- Did this run have any errors? Any warnings? If so, how many?
- What is the exact compilation or database error? What's the stacktrace?
- What is _all_ the SQL that dbt ran against the database? On a specific thread? For a specific model?

So while I'm not opposed to improving our JSON-formatted logs, I don't think we can commit to maintaining that structured logging as the go-to place to answer rich questions about dbt resources—I'd actually prefer that you use `run_results` for that purpose.

**Comment by steffkes** [comment]
Hey @jtcohen6,

thanks for this response, especially the details you've provided around your idea of what's going to be there. 

I definitely need to read more about the artifacts and what the idea behind is - because from what you're describing it sounds like there could (even should?) be at least some overlap between the artifacts and the logs .. finally we're talking about the same kind of information that is generated during the run.

What I'd like to ask is: have you done any monitoring/logging given the current information of dbt? I would tend to say: it's pretty hard - because you get separate lines of a complete message that kinda belong together and with them you try to get an idea what is actually happening. Involving `--log-format=json` does not much besides adding a bunch of attributes. I'd be happy to contribute a few scenarios from current logging results which I find pretty hard to act on.

> So while I'm not opposed to improving our JSON-formatted logs, I don't think we can commit to maintaining that structured logging as the go-to place to answer rich questions about dbt resources—I'd actually prefer that you use run_results for that purpose.

How does that work in your opinion? the run results are only available at the end of the whole process - so either we end up with a lot of duplicate information (because we ingest `STDOUT` and `STDERR` as usual) and afterwards we push whatever we find in the run results .. or we completely ignore the usual output and only rely on the run results - which again are not available until everything is done. Depending on the total time needed to be done, might be rather long.

**Comment by steffkes** [comment]
Hey again @jtcohen6,

> By contrast, **dbt logs** should be the go-to source of operational information about a specific run. A human being or an orchestration tool should be able to inspect the exit code and logs to answer:
> 
> * Did this run have any errors? Any warnings? If so, how many?

I've been looking at some logs and tried to answer that question .. and it's kinda hard, wondering how that works for you:

```json
{
    "timestamp": "2020-11-10T13:03:24.063Z",
    "message": "[33mWarning in test not_null_stg_comp__service_some_created_at (models/staging/comp/stg_comp__service_some.yml)\u001b[0m",
    "attributes": {
        "levelname": "WARNING"
    }
}
{
    "timestamp": "2020-11-10T13:03:24.064Z",
    "message": "compiled SQL at target/compiled/dbt_core/models/staging/comp/stg_comp__service_some.yml/schema_test/not_null_stg_comp__service_some_created_at.sql",
    "attributes": {
        "levelname": "INFO"
    }
}
{
    "timestamp": "2020-11-10T13:03:24.064Z",
    "message": "Got 2 results, expected 0.",
    "attributes": {
        "levelname": "ERROR"
    }
}
```

So what is this supposed to be? it's three entries all saying something different, but they are all related to the same test. The text is saying it's a warning - so at least the first level would be accurate, the next is okay (could probably even classify as `DEBUG`?) but the third would raise the bar to an `ERROR`

No matter what it actually means (for the sake of this example at least), if we have some monitoring on `levelname = ERROR` we get something which is entirely out of context with no further information to it. we have to guess based on surrounding entries around the timestamp in question which other entries are related to that.

I'm trying to understand why you seem to be opposed to extending the logging for it (It could use the very same information that is already present in one way or another), would you mind shedding some light on this? I'd really like to understand your point of view on this

**Comment by jtcohen6** [comment]
@steffkes you raise some fair points! After rereading above, I also see that I missed some of the specific details in the scenarios you were laying out—sorry about that.

To explain my rationale here, I'd like to draw a distinction between:
1. Information about each resource (model/test/etc) while it's running
2. Summary information about the entire run after it's completed

In the standard CLI output, this separation occurs between the `Finished` and `Completed` lines:
```
$ dbt test
Running with dbt=0.18.1
Found 1 model, 2 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 1 seed file, 0 sources

19:10:50 | Concurrency: 1 threads (target='dev')
19:10:50 |
19:10:50 | 1 of 2 START test not_null_my_model_id............................... [RUN]
19:10:50 | 1 of 2 WARN 1 not_null_my_model_id................................... [WARN 1 in 0.04s]
19:10:50 | 2 of 2 START test unique_my_model_id................................. [RUN]
19:10:50 | 2 of 2 PASS unique_my_model_id....................................... [PASS in 0.03s]
19:10:50 |
19:10:50 | Finished running 2 tests in 0.25s.
------------------------ <<< this is the separation I mean
Completed with 1 warning:

Warning in test not_null_my_model_id (models/resources.yml)
  Got 1 result, expected 0.

  compiled SQL at target/compiled/testy/models/resources.yml/schema_test/not_null_my_model_id.sql

Done. PASS=1 WARN=1 ERROR=0 SKIP=0 TOTAL=2
```

## 1. Real-time statuses

Up to the word "Finished," the logs populate in real time, and they can provide useful information about which models are running, whether tests are passing, and so on. Here's one of the same log lines as above, now JSON-formatted:
```bash
dbt --debug --no-use-colors --log-format json test
```

```json
{
    "timestamp": "2020-12-04T00:04:21.609075Z",
    "message": "19:04:21 | 1 of 2 WARN 1 not_null_my_model_id................................... [WARN 1 in 0.03s]",
    "channel": "dbt",
    "level": 13,
    "levelname": "WARNING",
    "thread_name": "Thread-1",
    "process": 97168,
    "extra": {
        "unique_id": "test.testy.not_null_my_model_id",
        "run_state": "running"
    }
}
```

And here's the same line for the same test, now configured with error-level severity:

```json
{
    "timestamp": "2020-12-04T00:00:04.723733Z",
    "message": "19:00:04 | 1 of 2 FAIL 1 not_null_my_model_id................................... [FAIL 1 in 0.04s]",
    "channel": "dbt",
    "level": 14,
    "levelname": "ERROR",
    "thread_name": "Thread-1",
    "process": 97097,
    "extra": {
        "unique_id": "test.testy.not_null_my_model_id",
        "run_state": "running"
    }
}
```

Those are the lines that we'd hope monitoring would catch by checking the level/levelname for `WARNING` and `ERROR`. The `extra.unique_id` is what you can use to identify the specific resource that's running.

You can use that `unique_id` to look up more information about the test in the `nodes` object in `manifest.json`, which includes its config, parents, and compiled SQL. Based on your feedback above, it sounds like that's the contextual info you want in the `extra` dict, and I am open to the feedback that we could surface more information there.

## 2. Invocation-level summary

Aggregating, filtering, and summarizing what happened in a given run _after_ the run is over is where the JSON artifacts really come into play. The combination of `run_results.json` and `manifest.json` will have a richer, better-organized, and more stable set of information than what's available in the logs. Here's a subset of the information about that one test from `run_results.json`:
```json
{
    "results": [
        {
            "node": {
                "unique_id": "test.testy.not_null_my_model_id",
                ...
            },
            "error": null,
            "status": 1,
            "execution_time": 0.03606009483337402,
            "thread_id": "Thread-1",
            "timing": [
                {
                    "name": "compile",
                    "started_at": "2020-12-04T00:10:50.542076Z",
                    "completed_at": "2020-12-04T00:10:50.567851Z"
                },
                {
                    "name": "execute",
                    "started_at": "2020-12-04T00:10:50.568134Z",
                    "completed_at": "2020-12-04T00:10:50.576844Z"
                }
            ],
            "fail": null,
            "warn": true,
            "skip": false
        },
```
Granted, it's still not as good as it could be; we are reorganizing that information to be more straightforward and intuitive in the next release of dbt (#2493).

That being said, you've got a really good point: the JSON representation of the summary lines starting with `Completed` are not all that helpful, since these are _definitely_ optimized for human readability in stdout. These are the lines produced for me (running with dbt v0.18.1):
```json
{
   "timestamp":"2020-12-04T00:00:04.737233Z",
   "message":"Failure in test not_null_my_model_id (models/resources.yml)",
   "channel":"dbt",
   "level":14,
   "levelname":"ERROR",
   "thread_name":"MainThread",
   "process":97097,
   "extra":{
      "run_started_at":"2020-12-04T00:00:03.887409+00:00",
      "invocation_id":"eb53b311-18a6-4a1d-bd51-4cc978f59512",
      "is_status_message":true,
      "run_state":"internal"
   }
}
{
   "timestamp":"2020-12-04T00:00:04.737620Z",
   "message":"  Got 1 result, expected 0.",
   "channel":"dbt",
   "level":14,
   "levelname":"ERROR",
   "thread_name":"MainThread",
   "process":97097,
   "extra":{
      "run_started_at":"2020-12-04T00:00:03.887409+00:00",
      "invocation_id":"eb53b311-18a6-4a1d-bd51-4cc978f59512",
      "is_status_message":true,
      "run_state":"internal"
   }
}
{
   "timestamp":"2020-12-04T00:00:04.738136Z",
   "message":"  compiled SQL at target/compiled/testy/models/resources.yml/schema_test/not_null_my_model_id.sql",
   "channel":"dbt",
   "level":11,
   "levelname":"INFO",
   "thread_name":"MainThread",
   "process":97097,
   "extra":{
      "run_started_at":"2020-12-04T00:00:03.887409+00:00",
      "invocation_id":"eb53b311-18a6-4a1d-bd51-4cc978f59512",
      "is_status_message":true,
      "run_state":"internal"
   }
}
```
I'd welcome some changes to better coordinate those "summary" log lines in their JSON output, something like:
```json
{
   "timestamp":"2020-12-04T00:00:04.737233Z",
   "message":"Failure in test not_null_my_model_id (models/resources.yml)\n  Got 1 result, expected 0.\n  compiled SQL at target/compiled/testy/models/resources.yml/schema_test/not_null_my_model_id.sql",
   "channel":"dbt",
   "level":14,
   "levelname":"ERROR",
   "thread_name":"MainThread",
   "process":97097,
   "extra":{
      "run_started_at":"2020-12-04T00:00:03.887409+00:00",
      "invocation_id":"eb53b311-18a6-4a1d-bd51-4cc978f59512",
      "is_status_message":true,
      "run_state":"internal"
   }
}
```

Let me know what you think, and if the distinction I've drawn above makes sense for your needs.

**Comment by steffkes** [comment]
Thanks @jtcohen6, appreciate it!

> You can use that `unique_id` to look up more information about the test in the `nodes` object in `manifest.json`, which includes its config, parents, and compiled SQL. Based on your feedback above, it sounds like that's the contextual info you want in the `extra` dict, and I am open to the feedback that we could surface more information there.

Absolutely this! I've tried something there at https://github.com/fishtown-analytics/dbt/issues/2915#issuecomment-734331997 - if you like to have a look.

While it could be way more sophisticated, I'd say - especially for the first try - it's enough to expose the information we already have there anyway: just not hide it within a stringed message.

To give you more context about where I'm coming from: Assume dbt running in a scheduled workflow, output attached to DataLog for monitoring. Different monitors configured there, finally ending up in Slack, hopefully notifying the relevant people. 

`STDOUT` and  `STDERR` are the go-to options in this scenario i'd say. We're not talking about aggregating historical information or something like this (I agree, this is a different avenue) - but in the process outlined above, i have no really chance to access `run_results` or the `manifest` to enrich data (at least not without a fair amount of custom work). I'd hope that we have an atomic entity where any tool would be able to act standalone, without doing any lookups for more information.

**Comment by steffkes** [comment]
Hey @jtcohen6 , just avoiding this ticket gets lost somewhere :) 

Would you be open to be working on this? I'm happy to continue to the conversation to work out what seems to be feasible for the project, try several things and reflect from our usage of the project how we see things panning out.

**Comment by jtcohen6** [comment]
@steffkes Yes, ok! I've had this on my mind for the last several weeks, and I think I've come around to what you're proposing. The "summary" log-lines could really use some help :)

I'm going to re-open this issue, let's take your code suggestion above as a starting point and iterate from there.

**Comment by steffkes** [comment]
I'd still love to see this .. there have been multiple situations where a proper log would have helped! But as it's the case every so often - I'm not working anymore actively on projects that involve dbt. So I can't offer any help around implementing the suggested changes, at least not right now and not for the foreseeable future.

**Comment by jtcohen6** [comment]
@steffkes I'm appreciative of your thoughtful comments in this issue, as it's continued to inform my thinking in the months since. We're actually hard at work on structured logging ahead of dbt-core v1 as we speak! You can check out https://github.com/dbt-labs/dbt-core/pull/4055 if you're interested to see some of this in action.

I'm going to close this issue in favor of the #3359 / the work over there :)
