### ISSUE TITLE
Ambiguous catalog matching when analysis + model have same name

### ISSUE THREAD

**Issue by prithvisathiya** [dbt-labs/dbt-core#2919]
### Describe the bug
After running `dbt docs [generate|serve] <options>`, the resulting generated documentation shows inconsistent information between the different tables. Certain tables are missing almost all of the table details (ex. owner, package, row count, etc.) and only includes a subset of the columns that are actually produced. This has been narrowed down to only occur when there is a file in the `analysis/` directory with the same name as one in either of the `models/` or `snapshots/` directories. 

### Steps To Reproduce
1. Create a file `models/foo.sql` with the following SELECT statement
```sql
select '1' as id, 'foo' as first_name, 'bar' as last_name
```
2. Run the model and materialize in Data Warehouse (Redshift)
3. View the documentation by running `dbt docs [generate|serve]`. The full details for the `foo` model will be displayed
4. Create a new file with the same contents as step 1, but under `analysis/foo.sql`.
5. Repeat step 3, but this time, the documentation will be missing almost all of the important information

### Expected behavior
The full documentation should be displayed, regardless of whether a file in the `[models|snapshots]/` and `analysis/` directories have identical names. Analysis is only used for local debugging purposes, and should not affect documentation, which typically reflects the remote production state. 

### Screenshots and log output
Screenshot showing the missing details
<img width="981" alt="Screen Shot 2020-11-26 at 1 49 07 AM" src="https://user-images.githubusercontent.com/4993988/100335892-57cd5980-2f8a-11eb-9483-24c608c9fd54.png">

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.2
   latest version: 0.18.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.17.2
  - snowflake: 0.17.2
  - redshift: 0.17.2
  - postgres: 0.17.2
```

**The operating system you're using:**
Mac
**The output of `python --version`:**
Python 3.7.3

**Comment by jtcohen6** [comment]
Thanks for writing this up after our conversation in slack, @prithvisathiya! The underlying issue here is that dbt associates catalog entries with analyses rather than models if they have the same name. We should fix that; since dbt does not materialize analyses in the database, I think it could exclude them from catalog matching altogether.

I believe the relevant bit of code is here:
https://github.com/fishtown-analytics/dbt/blob/fec0e31a25d5b922cb1833cffcb5095eb4ee642b/core/dbt/task/generate.py#L98-L122

**Comment by jtcohen6** [comment]
It's probably fair to say that only [`refable` nodes](https://github.com/dbt-labs/dbt/blob/f460d275baa4df8cf8713f27e198a3577d6ea71c/core/dbt/node_types.py#L32-L38) should be matched up to catalog objects. So this could be as simple as filtering the [`node_map` used here](https://github.com/dbt-labs/dbt/blob/fec0e31a25d5b922cb1833cffcb5095eb4ee642b/core/dbt/task/generate.py#L108-L110).

(That would exclude tests stored in the database, newly viable for cataloging in v0.20.0—but tests aren't exactly documented today as it is, and I don't think database metadata about tests persisted as objects is particularly interesting.)

With that direction in mind, I'm going to call this one a good first issue.
