### ISSUE TITLE
Allow documenting custom materializations in `.yml` files

### ISSUE THREAD

**Issue by ilmari-aalto** [dbt-labs/dbt-core#2944]
### Describe the feature
Allow documenting custom materializations in `.yml` files

### Describe alternatives you've considered
Currently I'm defining materializations as a list of `materializations` in a `.yml` file to have it documented in the same pull request as my code.

### Additional context
There are no specs about materialization documentation as far as I know. There are for macros, for example: https://docs.getdbt.com/reference/macro-properties/. But if you define materializations as macros then dbt will warn you with: `WARNING: Found documentation for macro "your_materialization" which was not found`.

### Who will this benefit?
All dbt users will benefit if all object types in dbt can be documented in a consistent way.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

**Comment by jtcohen6** [comment]
This seems reasonable to me!

It also raises an interesting line of questions, which can be summed up as: Is dbt documentation primarily for data modelers / dbt developers or for stakeholders / data consumers?

Ultimately, I think the answer should be both; when we finally have the time to sit down and redesign the docs site, we'd likely want to provide different views, or expose different information, based on the persona of the viewer.

Even more than macros (which can be called inline, alongside model SQL), materializations exist _just_ below the surface of information that is relevant for data consumers. In the modeler's version of the docs, though, this is really important information! I'd want to document the most important node configs of a model, including `materialized`; that config could link to the page with the description and Jinja code of that materialization.

Anyway, that's a bit further off in the future. In the meantime, I think a fair version of this would extend the existing mechanism for documenting macros.
