### ISSUE TITLE
[CT-1635] Populate adapter_response for tests + sources

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#2964]
### Describe the feature
#2747 requested that dbt log bytes processed for _all_ query types, including tests, source-freshness, and run-operations. This prompted the first part of a solution in #2961: adding an `adapter_response` dict to record database-specific information about the queries dbt has run. In v0.19.0, that will include `bytes_processed` for all materializations (model runs, seeds, snapshots).

We'd like to record bytes processed for tests and source snapshots, too. What does this really mean?
- `dbt test` should populate `adapter_response` in `run_results.json`
- `dbt source snapshot-freshness` should populate `adapter_response` in `sources.json` 

(I'm less clear on how we'd manage this in `run-operation`, since it doesn't write to `run_results`.)

Eventually, this has the potential to dovetail nicely with:
- #2079: add a new log line to the "summary" stdout, with the total bytes processed from the invocation. In an ideal world, users could get a human-friendly rounded number in stdout and the raw numbers in `run_results.json` for analysis/aggregation.
- #2580: the ability to define which result information is populated to `message` in stdout (maybe via Jinja macro??)

### Describe alternatives you've considered
- Not doing this

### Additional context
- Most immediately relevant to BigQuery (bytes processed)
- Useful for any database which sends back significant information in its response

### Who will this benefit?
- Projects with larger datasets, where filtering is important to limit cost of test queries

**Comment by jtcohen6** [comment]
I think this may be as simple as using `result.adapter_response` to populate the `RunResult` for tests + freshness results, where currently we're setting them to just `{}`:

https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/models/table/create_table_as.sql

https://github.com/dbt-labs/dbt-core/blob/75f3e8cb749c7b52d226844394ecb34c1e0070a4/core/dbt/task/freshness.py#L123

We can look to the `run` task for the reference implementation:

https://github.com/dbt-labs/dbt-core/blob/75f3e8cb749c7b52d226844394ecb34c1e0070a4/core/dbt/task/run.py#L221-L223

**Comment by jtcohen6** [comment]
One thing we'd need to change to get this working for `dbt source freshness`: Currently, the `collect_freshness` macro returns _just_ its `table` result. We need it to return the `response` object as well, which we can then serialize into an `adapter_response` dictionary.

To illustrate the changes that I think would be needed: https://github.com/dbt-labs/dbt-core/commit/a066c1e8bbdd54d7b8d658b1c3eb905d756606bf

**Comment by sebas-bdr** [comment]
hey @jtcohen6, this feature would be great.
I noticed the `help_wanted` label was recently removed, not sure (from reading [the docs](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md)) whether this means contributions won't be accepted. But if possible I'd like to contribute.

> To illustrate the changes that I think would be needed: https://github.com/dbt-labs/dbt-core/commit/a066c1e8bbdd54d7b8d658b1c3eb905d756606bf

Regarding testing, would the following code change suffice (specifically for source freshness)? https://github.com/sebas-bdr/dbt-core/commit/572f1439efa17e096d6a53b866c37cd2cd43f213

**Comment by jamwalla** [comment]
I would love to have this feature to see how much my tests are costing!

I was able to get it working pretty easily for tests by returning the adapter response alongside the `TestResultData` object in `TestRunner.execute_test`:

https://github.com/dbt-labs/dbt-core/blob/89d111a5f6b0ddf925f3cb62c90164f6a038a1e3/core/dbt/task/test.py#L94
Same way that the ModelRunner does it: https://github.com/dbt-labs/dbt-core/blob/89d111a5f6b0ddf925f3cb62c90164f6a038a1e3/core/dbt/task/run.py#L219 Then the adapter response can get passed up through `TestRunner.execute`.

Maybe not the prettiest solution but wanted to advocate for this being very useful + straightforward! thx dbt devs <3
