### ISSUE TITLE
Warn, don't error, for disabled models when using --models

### ISSUE THREAD

**Issue by friendofasquid** [dbt-labs/dbt-core#2973]
### Describe the feature

Not sure if this is a bug or feature request. If I target a multiple models like so

```
dbt run --models models/a.sql models/b.sql
```

, and one of them is disabled—say `b.sql`—then I received the error

```
The selector 'models/a.sql models/b.sql' does not match any nodes and will be ignored
```

It's a little misleading. A warning that one of them was disabled would be much more helpful.

### Describe alternatives you've considered

N/A

### Additional context

This was with `dbt-spark` but I assume this doesn't matter.

### Who will this benefit?

Anyone targeting individual SQL files. (We doing this to only build models that Git said have changed)

### Are you interested in contributing this feature?

Not in the near future.

**Comment by ugurozata** [comment]
It would be great to run disabled models when specifically select that model. dbt run --model {{ disabled_model_name }}.

**Comment by jtcohen6** [comment]
Hey @friendofasquid, just want to clarify a few points here. When I create two models `a` and `b`, disable `b`, and `dbt run --models models/a.sql models/b.sql`, I see the log message:

`The selector 'models/b.sql' does not match any nodes and will be ignored`

Here's the [JSON logline](https://docs.getdbt.com/reference/global-cli-flags/#log-formatting) for that same message:
```
{"timestamp": "2021-01-04T11:19:52.546676Z", "message": "The selector 'models/b.sql' does not match any nodes and will be ignored", "channel": "dbt", "level": 13, "levelname": "WARNING", "thread_name": "MainThread", "process": 20724, "extra": {"run_state": "internal"}}
```
It is `WARNING`-level, which makes sense to me: dbt returns a `0` exit code. Of course, if you pass the `--warn-error` flag, dbt raises a compilation error before running any models and returns an exit code of `2`.

Those points established, I do see in merit in arguments for:
- Rewording this warning message: `The following selection criteria do not match any enabled nodes: 'models/b.sql'`
- Changing this from `WARNING` level to `INFO` level, especially given the existence of pseudo-selectors / "dynamic" selection criteria, for which it's not uncommon to swing and miss selecting any nodes.

> (We doing this to only build models that Git said have changed)

Speaking of... have you heard of [`state:modified`](https://docs.getdbt.com/reference/node-selection/methods/#the-state-method)? :)

> It would be great to run disabled models when specifically select that model. `dbt run --model {{ disabled_model_name }}.

@ugurozata I don't think we're going to change the current behavior. If a model is disabled, it _really_ doesn't participate in your project at all: neither the DAG nor the docs nor any runnable tasks. Using existing dbt constructs, you can furnish yourself with an override switch:

**models/b.sql**
```
{{ config(enabled = var('manual_override', false)) }}

select * from {{ ref('a') }} 
```
```
$ dbt run --models models/a.sql models/b.sql --vars 'manual_override: true'
```

**Comment by friendofasquid** [comment]
Interesting. I have to rely on my original post here instead of my memory, but I believe it flagged that _both_ models didn't match, whereas your error message correctly flags that only `models/b.sql` did not match. So either I got this wrong initially—completely likely—or there has been a change. 

> Speaking of... have you heard of state:modified? :)

I've seen this, but I'm not 100% sure given our setup (AWS Batch, Buildkite) how to persist manifests and check for changes. Git seems easier for a first pass.
