### ISSUE TITLE
OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by RoniFinTech** [dbt-labs/dbt-core#2992]
### Describe the bug
Using the DBT Python API, I run by using this function:
`dbt.main.handle_and_check()`

I'm also using it with an AWS Lambda that gets deployed (zipped and then gets unzipped by serverless-python-requirements).

I'm setting the argument `--profiles-dir` to `os.path.dirname(__file__)` and `--project-dir` to `os.path.dirname(__file__)`. Both of the profiles.yml and dbt_project.yml are located in the same location under `./data_warehouse/snowflake_dbt`

The error I'm getting: `OSError: [Errno 38] Function not implemented`

Any idea how to solve the issue?
when I run the lambda locally, everything works fine. 
I think it's due to the combination of AWS Lambda and DBT...

### Screenshots and log output

```
Running with dbt=0.18.1
--- Logging error ---
Traceback (most recent call last):
  File "/var/task/data_warehouse/snowflake_dbt/main.py", line 62, in handler
    results, success = run_dbt(e.name.value, e.macro, e.event_vars, e.event_args)
  File "/var/task/data_warehouse/snowflake_dbt/main.py", line 94, in run_dbt
    results, success = dbt.main.handle_and_check(params)  # pylint: disable=maybe-no-member
  File "/tmp/sls-py-req/dbt/main.py", line 202, in handle_and_check
    task, res = run_from_args(parsed)
  File "/tmp/sls-py-req/dbt/main.py", line 241, in run_from_args
    task = parsed.cls.from_args(args=parsed)
  File "/tmp/sls-py-req/dbt/task/base.py", line 156, in from_args
    return super().from_args(args)
  File "/tmp/sls-py-req/dbt/task/base.py", line 103, in from_args
    return cls(args, config)
  File "/tmp/sls-py-req/dbt/task/runnable.py", line 55, in __init__
    super().__init__(args, config)
  File "/tmp/sls-py-req/dbt/task/base.py", line 151, in __init__
    register_adapter(self.config)
  File "/tmp/sls-py-req/dbt/adapters/factory.py", line 182, in register_adapter
    FACTORY.register_adapter(config)
  File "/tmp/sls-py-req/dbt/adapters/factory.py", line 105, in register_adapter
    adapter: Adapter = adapter_type(config)  # type: ignore
  File "/tmp/sls-py-req/dbt/adapters/base/impl.py", line 162, in __init__
    self.connections = self.ConnectionManager(config)
  File "/tmp/sls-py-req/dbt/adapters/base/connections.py", line 42, in __init__
    self.lock: RLock = flags.MP_CONTEXT.RLock()
  File "/var/lang/lib/python3.7/multiprocessing/context.py", line 72, in RLock
    return RLock(ctx=self.get_context())
  File "/var/lang/lib/python3.7/multiprocessing/synchronize.py", line 187, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
OSError: [Errno 38] Function not implemented
```
I also set the `threads` to `1` in `profiles.yml` but no help...

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1
```

**The operating system you're using:**

**The output of `python --version`:**
Python 3.7

**Comment by kwigley** [comment]
> I think it's due to the combination of AWS Lambda and DBT

That sounds right to me! Unfortunately, AWS lambda does not support python multiprocessing as intended and as used by dbt. (https://aws.amazon.com/blogs/compute/parallel-processing-in-python-with-aws-lambda/)

**Comment by RoniFinTech** [comment]
> > I think it's due to the combination of AWS Lambda and DBT
> 
> That sounds right to me! Unfortunately, AWS lambda does not support python multiprocessing as intended and as used by dbt. (https://aws.amazon.com/blogs/compute/parallel-processing-in-python-with-aws-lambda/)

Any way to bypass it? maybe by running dbt in a single processor fashion?

**Comment by RoniFinTech** [comment]
Maybe the method suggested by AWS can be used to overcome this for lambdas?
https://aws.amazon.com/blogs/compute/parallel-processing-in-python-with-aws-lambda/
`On the other hand, you can use multiprocessing.Pipe instead of multiprocessing.Queue to accomplish what you need without getting any errors during the execution of the Lambda function.`

**Comment by hiattp** [comment]
It seems safe to say given this thread that dbt cannot currently be run on AWS Lambda? Is the same true for Azure Functions? It might be useful to document this somewhere, dbt seems perfect for ELT orchestration based on the kind of ephemeral serverless model that Lambda/Functions promote but at least for AWS this appears to be a showstopper unless I'm misreading?

**Comment by vchetyrkine** [comment]
Perhaps avoiding the synchronization altogether when setting `threads: 1` would somewhat mitigate the issue ?

**Comment by vchetyrkine** [comment]
A possible workaround is to move to a thread execution context which does work inside AWS Lambdas. The following seems to work for my use cases, but very likely needs more testing:
```python
import queue
import threading
from concurrent.futures import ThreadPoolExecutor

import dbt.flags as dbt_flags


# Override multiprocessing ThreadPool with a ThreadPoolExecutor that doesn't use any
# shared memory semaphore locks
class CustomThreadPool:
    def __init__(self, num_threads):
        self.pool = ThreadPoolExecutor(max_workers=num_threads)
    
    # provide the same interface expected by dbt.task.runnable
    def apply_async(self, func, args, callback):
         
        def future_callback(fut): 
            result = fut.result()
            return callback(fut.result())
        
        self.pool.submit(func, *args).add_done_callback(future_callback)
    
    # we would need to actually keep a "closed" attribute lying around and properly check it
    def close(self):
        pass
    
    # shutdown(wait=True) mimics "join", whereas shutdown(wait=False) mimics "terminate"
    def join(self):
        self.pool.shutdown(wait=True)


import multiprocessing.dummy
multiprocessing.dummy.Pool = CustomThreadPool


# Replace Multiprocessing context with threaded context
# The objects mostly have the same api
class ThreadedContext:
    Process = threading.Thread
    Lock = threading.Lock
    RLock = threading.RLock
    Queue = queue.Queue

def get_threaded_context():
    return ThreadedContext()

# override both just in case :)
dbt_flags._get_context = get_threaded_context
dbt_flags.MP_CONTEXT = ThreadedContext()


def handler(event, context):
    # when imported here, we're pretty sure the monkey-patching above already took place
    # it also made testing easier (as AWS Lambda keeps old imports around on warm starts)
    import dbt.main as dbt_main
    dbt_main.log_manager._file_handler.disabled = True
    dbt_args = ["--no-write-json", "--no-use-colors", "run"]
    
    try:
        # main uses sys.exit which doesn't play well with the AWS Lambda handler
        results, succeeded = dbt_main.handle_and_check(dbt_args)
    except Exception as e:
        # This is to ease debugging, the exception catching should be rewritten properly
        traceback.print_exc()
        results = None
        succeeded = False
    else:
        message = "OK"
    # default lambda template
    return {
        'statusCode': 200,
        'body': {
            'message': message,
            'results': str(results),
            'succeeded': succeeded
        }
    }

```

**Comment by Gunnnn** [comment]
Hello!
I also have the same issue when trying to run DBT on Databricks cluster.
`dbt` command itself runs smoothly, but `dbt debug` gives error, mentioned in this thread.

**Comment by sungchun12** [comment]
I'm experiencing the same in Databricks

![image](https://user-images.githubusercontent.com/19176976/165379177-f96126f6-b9a5-4c22-98f1-de6cc943f2bf.png)

**Comment by AndrewLane** [comment]
@RoniFinTech I know it's a long time since you posted this, but just curious if you ever had luck orchestrating dbt via lambda without having to do any unwanted workarounds?

**Comment by thinkbigdatanalytics** [comment]
I am also looking for the options to run dbt in AWS Lambda, curious to know if there is any workaround available ?

**Comment by AndrewLaneAtPowerSchool** [comment]
I attempted to use the new programmatic invocations API available in newly-release dbt v1.5.0: https://docs.getdbt.com/reference/programmatic-invocations

I was hoping perhaps I could get around this "Function not implemented" issue.  However, what I found is that not only do I still get the same failure, the workarounds previously discussed in this issue no longer seem to work.  I'm not sure if they just need a small tweak for the error, but I'm putting my stack trace below.  The workarounds I'm referring to are the ones mentioned by @vchetyrkine earlier in the issue and (this is what I'm actualy using) some work by @tomsej found here: https://github.com/tomsej/jaffle_shop_duckdb/commit/a850eaa986167e9bbdc858c870f00ec45b4eca40

Does anyone know how to work around that SemLock issue below with v1.5.0 dbt code?

```
20:17:53  Traceback (most recent call last):
  File \"/var/lang/lib/python3.9/site-packages/dbt/cli/requires.py\", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File \"/var/lang/lib/python3.9/site-packages/dbt/cli/requires.py\", line 71, in wrapper
    return func(*args, **kwargs)
  File \"/var/lang/lib/python3.9/site-packages/dbt/cli/requires.py\", line 142, in wrapper
    return func(*args, **kwargs)
  File \"/var/lang/lib/python3.9/site-packages/dbt/cli/requires.py\", line 168, in wrapper
    return func(*args, **kwargs)
  File \"/var/lang/lib/python3.9/site-packages/dbt/cli/requires.py\", line 215, in wrapper
    return func(*args, **kwargs)
  File \"/var/lang/lib/python3.9/site-packages/dbt/cli/requires.py\", line 242, in wrapper
    manifest = ManifestLoader.get_full_manifest(
  File \"/var/lang/lib/python3.9/site-packages/dbt/parser/manifest.py\", line 225, in get_full_manifest
    loader = cls(config, projects, macro_hook=macro_hook, file_diff=file_diff)
  File \"/var/lang/lib/python3.9/site-packages/dbt/parser/manifest.py\", line 166, in __init__
    self.manifest: Manifest = Manifest()
  File \"<string>\", line 25, in __init__
  File \"/var/lang/lib/python3.9/multiprocessing/context.py\", line 68, in Lock
    return Lock(ctx=self.get_context())
  File \"/var/lang/lib/python3.9/multiprocessing/synchronize.py\", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File \"/var/lang/lib/python3.9/multiprocessing/synchronize.py\", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 38] Function not implemented
```

**Comment by oli5679** [comment]
I'm also stuck on this, and interested if there is a workaround?

**Comment by oli5679** [comment]
I managed to use snippets from vchetyrkine, reconfiguring some multiprocessing adjustments that I don't fully understand. I also had to move my dbt project into /tmp directory to get it to work. 

```
from dbt.cli.main import dbtRunner, dbtRunnerResult

# copying to /tmp so DBT can write to files
shutil.copytree('./src/moneycast_dbt', '/tmp/moneycast_dbt',dirs_exist_ok = True)

logger.info('beginning execution')
logger.info(f'event {event} context {context}')
logger.info('running DBT model')
dbt = dbtRunner()
dbt_target = event.get('stage', 'dev')
cli_args = ["run","--profiles-dir", "/tmp/moneycast_dbt", "--project-dir", "/tmp/moneycast_dbt","--target-path", "/tmp/moneycast_dbt","--target",dbt_target]
res = dbt.invoke(cli_args)
```

**Comment by AndrewLaneAtPowerSchool** [comment]
> I managed to use snippets from vchetyrkine higher up in this thread, reconfiguring some multiprocessing adjustments that I don't fully understand. I also had to move my dbt repo, and all the components that are created/edited into /tmp directory to get it to work.
> 
> ```
> from dbt.cli.main import dbtRunner, dbtRunnerResult
> 
> # copying to /tmp so DBT can write to files
> shutil.copytree('./src/moneycast_dbt', '/tmp/moneycast_dbt',dirs_exist_ok = True)
> 
> logger.info('beginning execution')
> logger.info(f'event {event} context {context}')
> logger.info('running DBT model')
> dbt = dbtRunner()
> dbt_target = event.get('stage', 'dev')
> cli_args = ["run","--profiles-dir", "/tmp/moneycast_dbt", "--project-dir", "/tmp/moneycast_dbt","--target-path", "/tmp/moneycast_dbt","--target",dbt_target]
> res = dbt.invoke(cli_args)
> ```

@oli5679 could you share those multiprocessing adjustments in a gist or something?

**Comment by dandexcare** [comment]
> Referenc

@oli5679 Let me know if you are willing to share your solution for running dbt on a lambda

**Comment by vchetyrkine** [comment]
Sorry I've no longer been working on dbt + AWS at my company :/ 

Instead of moving the whole project, you could probably set alternative logging and target paths for dbt, I don't think it tries to write anywhere else.
```yml
# in dbt_project.yml
# These output directories are overridden in Lambda to /tmp/target
target-path: "{{ env_var('DBT_TARGET_OUTPUT_DIR', 'target') }}"
log-path: "{{ env_var('DBT_LOG_OUTPUT_DIR', 'logs') }}"
```

@AndrewLaneAtPowerSchool notice I'm quite careful to `import dbt` as late as possible. Once the various contexts have been setup, it's very annoying to monkeypatch. Your stack trace is trying to init synchronization primitives (`SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)`, ...), which may indicate the monkey patching with `CustomThreadPool` did **not** happen.

**Comment by SilasCrosby** [comment]
After Spending about 16 hours with Grok/ChatGPT, I think I finally have a working Way to do this. 

You can attach a container to the lambda function that patches the multiprocessing libraries in Python and use all threads, Below is my lambda docker file. I ran sam init for python with a containerized lambda function. 

This works for 16 threads, but its dangerous, as a new Rlock file is created for each thread, and the threads don't communicate creating something called a "DAG Race Condition", Basically if 2 threads try to build the same upstream table they depend on at the same time conflicts will occur. 

And could lead to silent failures and inconsistent runs. 

Since lambda has access to 1024 threads on each run, you could run each table at each dbt "level" start with src, then staging, then  intermediate.... etc. you build each level at a time. vertical parallelism, rather than horizontal parallelism per se. Using python's concurrent.executions library, kind of like Node.js Promise.all().

I need someone who knows python better than me to validate this. 

1. Here is my dockerfile :

```
-----

# Lambda Python 3.12 base image
FROM public.ecr.aws/lambda/python:3.13

# Install git (needed for dbt packages)
RUN microdnf install -y git && microdnf clean all

# Install dbt CLI globally with Snowflake adapter
RUN python3.13 -m pip install dbt-core dbt-snowflake boto3

# Set Python path
ENV PYTHONPATH=/var/task

# Copy Lambda handler
COPY app.py profiles.yml ./

# Lambda entrypoint
CMD ["app.lambda_handler"]

-----
```


2. Here is the top part of my python lambda function:
```

import os
import json
import subprocess
import boto3
import threading
import multiprocessing as mp
import multiprocessing.synchronize as sync
import shutil

# Define wrapper classes unconditionally (no inheritance to avoid import errors)
class ThreadingRLock:
    """Wrapper for threading.RLock – ignores ctx, provides reentrant locking API."""
    def __init__(self, *args, ctx=None, **kwargs):
        self._lock = threading.RLock()

    def acquire(self, blocking=True, timeout=-1):
        return self._lock.acquire(blocking=blocking, timeout=timeout)

    def release(self):
        self._lock.release()

    def __enter__(self):
        self.acquire()
        return self

    def __exit__(self, *args):
        self.release()

class ThreadingLock:
    """Wrapper for threading.Lock – ignores ctx, provides basic locking API."""
    def __init__(self, *args, ctx=None, **kwargs):
        self._lock = threading.Lock()

    def acquire(self, blocking=True, timeout=-1):
        return self._lock.acquire(blocking=blocking, timeout=timeout)

    def release(self):
        self._lock.release()

    def __enter__(self):
        self.acquire()
        return self

    def __exit__(self, *args):
        self.release()

class ThreadingSemaphore:
    """Wrapper for threading.Semaphore – ignores ctx."""
    def __init__(self, value=1, ctx=None, **kwargs):
        self._sem = threading.Semaphore(value=value)

    def acquire(self, blocking=True, timeout=None):
        return self._sem.acquire(blocking=blocking, timeout=timeout)

    def release(self):
        self._sem.release()

class ThreadingBoundedSemaphore:
    """Wrapper for threading.BoundedSemaphore – ignores ctx."""
    def __init__(self, value=1, ctx=None, **kwargs):
        self._sem = threading.BoundedSemaphore(value=value)

    def acquire(self, blocking=True, timeout=None):
        return self._sem.acquire(blocking=blocking, timeout=timeout)

    def release(self):
        self._sem.release()

class DummyBarrier:
    """No-op for Barrier (not used by dbt adapters)."""
    def __init__(self, *args, **kwargs):
        pass
    def wait(self, timeout=None):
        pass
    def abort(self):
        pass
    def reset(self):
        pass
    def parties(self):
        return 0

# Monkey-patch ONLY if in AWS Lambda (runtime check, after module load)
if os.environ.get('AWS_LAMBDA_FUNCTION_NAME'):
    # Apply patches
    mp.RLock = ThreadingRLock
    mp.Lock = ThreadingLock
    mp.Semaphore = ThreadingSemaphore
    mp.BoundedSemaphore = ThreadingBoundedSemaphore
    mp.Barrier = DummyBarrier

    # Also patch the synchronize module directly (dbt may import it explicitly)
    sync.RLock = ThreadingRLock
    sync.Lock = ThreadingLock
    sync.Semaphore = ThreadingSemaphore
    sync.BoundedSemaphore = ThreadingBoundedSemaphore
    sync.Barrier = DummyBarrier

    print("✅ Multiprocessing sync primitives patched for AWS Lambda (wrappers)")

from dbt.cli.main import dbtRunner  # Safe now

```
3. 

To get this working, I cloned the Dbt project from github into the lambda function /tmp directory using a personal access token and sub process like below:

    # Overwrite: Remove existing dir (ignores errors if missing)
    # check if this exists if lambda shares the execution environment, and don't clone
    if os.path.exists(clone_dir):
        try:
            shutil.rmtree(clone_dir)
            print(f"🗑️ Cleared existing {clone_dir}")
        except OSError as e:
            print(f"⚠️ Warning: Failed to clear {clone_dir}: {e}")
        
    clone_result = subprocess.run(
        ["git", "clone", repo_url, clone_dir],
        capture_output=True,
        text=True,
        cwd="/tmp"
    )


I used os.environ, and ssm to set the DBT Environment variables directly in the lambda function. 

4. Here is the lambda Handler:
\
```
ssm = boto3.client('ssm')

def lambda_handler(event, context):

   #SET ENV VARIBLES FOR PROFILES.yml, SET 
      
    # Run dbt deps (installs dependencies from packages.yml)
    deps_result = subprocess.run(
        ["dbt", "deps", "--target", "staging"],
        capture_output=True,
        text=True
    )

   Now you can run debug and using the dbtRunner() 

      # Now run dbt debug via Python API
    runner = dbtRunner()

    res = runner.invoke(["debug", "--target", "environment", "--no-write-json"])

    res2 = runner.invoke(["run", "--target", "environment", "--selector", "model"])

    #Check the results here/look at the lambda cloudwatch Logs for more info. 

     if res2.success:
        print("✅ dbt run completed successfully")
        print("Models executed: Check logs for details")
    else:
        print("❌ dbt run failed")
        print("Error details:", str(res2.result))  

```
