### ISSUE TITLE
Add argument to dbt clean for logs

### ISSUE THREAD

**Issue by emilieschario** [dbt-labs/dbt-core#2993]
### Describe the feature
What are the circumstances in which someone runs `dbt clean`? Usually when troubleshooting or trying to understand what is going on that doesn't look right. When troubleshooting you often want to see your logs to match what you're looking for. You might look at logs, then run clean, then want run the thing, then look at your logs again. If you forgot to clear or cycle your logs, though, now you might have to dig to find the info you're looking for. 

My proposal: add an argument to` dbt clean` that also wipes your logs, e.g. `dbt clean --include logs` or something similar.

### Describe alternatives you've considered

This tip from @clrcrl on cycling logs is what I use: https://discourse.getdbt.com/t/tips-and-tricks-about-working-with-dbt/287/4 but sometimes I forget to run it. 

### Additional context
Is this feature database-specific? Which database(s) is/are relevant? Please include any other relevant context here.

I don't think so. 

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

Anyone who is troubleshooting dbt models.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

👶 🍼  in theory yes, but unlikely

I guess my first question would be: is this something that other people think would be useful in dbt?

**Comment by jtcohen6** [comment]
Fair points @emilieschario! A version of this is possible today, by adding the log path to the `clean-targets` in `dbt_project.yml`:
```yml
clean-targets:
  - target
  - dbt_modules
  - logs
```

The questions in my mind are:
- Should dbt have a mechanism for _cycling_ instead of _clearing_, for `clean-targets` in general or logs in particular?
- If dbt had the ability to cycle, should logs be included by default?

**Comment by emilieschario** [comment]
> A version of this is possible today, by adding the log path to the clean-targets in dbt_project.yml

Yes, but that means you'd always clear the logs. Is that something you always want to do? I'm trying to think of a "no" use case and almost all of them are answered with "I want to cycle them".

I hadn't considered cycling the other things but can see a use case of wanting to see before after and/or wanting to compare using something like diffchecker.com
