### ISSUE TITLE
AssertionError: set_path called after being set

### ISSUE THREAD

**Issue by RoniFinTech** [dbt-labs/dbt-core#2997]
### Describe the bug
I'm trying to run two `run-operation` sequentially in the same function run and I get an error:
`AssertionError: set_path called after being set`

### Steps To Reproduce
I run two different macros by running `run-operation`.

I basically have a list of operations:
```
[
        {"name":"run-operation","macro":"macro1","event_args":str({"username":snowflake_user})},
        {"name":"run-operation","macro":"macro2","event_args": str({"username":snowflake_user})},
]
```
each element in the list gets passed to handle_and_check in the format it accepts.
dbt.main.handle_and_check(params)

The first one is fine but the second one fails. 

Looks like this is something inside logger.py. I believe it doesn't like the fact that two events are run in one go.
This is the line that fails:

`assert not self.initialized, 'set_path called after being set'`
I believe initialized is set to True in the second fun because the log file already exists.

### Expected behavior
the second run appends to the log file all outputs.

The way I bypassed the blocker for me: 
I commented out `assert not self.initialized, 'set_path called after being set'`
and then I slightly modified this:

```
def _replay_buffered(self):
        # assert self._msg_buffer is not None, \
        #     '_msg_buffer should never be None in _replay_buffered'
        if self._msg_buffer is not None:
            for record in self._msg_buffer:
                super().emit(record)
            self._msg_buffer = None
```
Probably incorrect for all the cases though...

At the end I still got this message which is strange:
`sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('...', ...), raddr=(...', ...)>`

Could be a new Snowflake connection starts without the old one closing? even though it says connection closed in the logs.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1

```

**The operating system you're using:**
MacOS

**The output of `python --version`:**
Python3.7

**Comment by jtcohen6** [comment]
Thanks for the detailed explanation @RoniFinTech. I'm afraid I have to give you a similar answer to your other recent question: we aren't currently able to document or maintain dbt's [python API](https://docs.getdbt.com/docs/running-a-dbt-project/dbt-api/). That said, I'd love to get there someday.

Of course, we are committed to supporting  the same functionality by other means (CLI):
```
dbt run-operation macro1 --args 'username: snowflake_user'
dbt run-operation macro2 --args 'username: snowflake_user'
```

**Comment by abudata** [comment]
Thanks for raising this here @RoniFinTech . We are also using dbt's Python API. After upgrading dbt version to 0.17 , we get the same error ->  `assert not self.initialized, set_path called after being set`.
@jtcohen6 @RoniFinTech I appreciate if you can share how you fixed this issue on your side.

**Comment by y-ken** [comment]
Thank you. I was getting this error when calling dbt from python sequentially. As it suggested, I was able to solve it by putting the code that initializes the logger for each loop before calling.
