### ISSUE TITLE
Add a --continue-after-error option

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#3015]
### Describe the feature
A new flag to attach to a specific step(s) of a run whose failure should not block the rest of the job from completing.
Consider this job in our project, which separates fragile from non-fragile tests - if a normally robust test starts failing, I'm much more concerned compared to the fragile ones which tend to self-heal once the pipelines catch up. 

```
dbt run
dbt test --exclude tag:fragile
dbt test -m tag:fragile
```

If a robust test fails, the fragile tests don't get a chance to be tested at all. 

### Describe alternatives you've considered
The current workaround is to make multiple jobs. This doesn't work with the exposure metadata tile beta, which needs all steps to be in a single dbt Cloud job: 
```
dbt source snapshot-freshness
dbt test -m +exposure:*
```
If a single source is stale, all tests will be skipped. The workaround to _that_ would be to make a separate job for each exposure, something like: 
```
dbt source snapshot-freshness --select +exposure:my_first_exposure
dbt test -m +exposure:my_first_exposure
```
but that would get intractable after more than a few exposures. 

### Additional context
In my heart, I think of this as the `--soldier-on` flag, but something like `--continue-after-error` is a more practical name

### Who will this benefit?
* People using the new metadata tiles
* People running separate jobs who could flatten them down to a single job again, which simplifies scheduling to avoid race conditions (currently I schedule the second test step like an hour after the first job, to make completely sure that everything I'm testing is actually finished building)

### Are you interested in contributing this feature?
_Interested_, but unlikely to make a move on it anytime soon

**Comment by joellabes** [comment]
Thanks @jtcohen6! I didn’t realise that exit on error was a Cloud construct, but now that you mention it, it seems obvious. Happy for this to become a Cloud feature request (although I’d make it a step config, not a job-wide config), so if you want to close this out go for it. 

This also makes for a much better test case of the [question i was asking in Slack](https://getdbt.slack.com/archives/C01HEF6JC81/p1610739641038700?thread_ts=1610650970.028000&channel=C01HEF6JC81&message_ts=1610739641.038700) about how Cloud vs Core features interact!

**Comment by es617** [comment]
> Happy for this to become a Cloud feature request (although I’d make it a step config, not a job-wide config)

+1 

Any plan on getting this feature into dbt Cloud?

**Comment by joellabes** [comment]
@mrogove you're welcome to re-open issues! Closed doesn't mean "we'll never do this", it just helps to prevent issues whose moment has passed from sticking around forever. 

In this case though, it's not actually a change that can be made in dbt core, so it makes more sense for you to submit a feature request to the dbt Cloud support team using the chat bubble inside the app

**Comment by Crimsonabyss** [comment]
hi, just following up this issue. has anyone raised the feature request yet? if not I am happy to do it.

**Comment by leoebfolsom** [comment]
@Crimsonabyss hi there, did you end up raising a feature request for this?

**Comment by Crimsonabyss** [comment]
@leoebfolsom not yet, i will do it this week!

**Comment by leoebfolsom** [comment]
Amazing, thank you! @Crimsonabyss

**Comment by polmonso** [comment]
@Crimsonabyss can you link it here? This issue still pops up on search.

**Comment by joellabes** [comment]
@polmonso if you're a dbt Cloud customer, please submit this feedback to the Cloud support team through the in-app messaging or by email (support@dbtlabs.com)

**Comment by wanalytics8** [comment]
Thanks for providing interesting possible workaround.
Hope this can be reopened~~ for dbt-core..

**Comment by joellabes** [comment]
It's now possible to configure a model's `on_error` config: https://docs.getdbt.com/reference/resource-configs/on_error
