### ISSUE TITLE
dbt docs browser tab crashes with ~100K source tables

### ISSUE THREAD

**Issue by panasenco** [dbt-labs/dbt-core#3026]
### Describe the bug
dbt docs browser tab crashes when trying to load all ~100K source tables in our data warehouse.

### Steps To Reproduce
We have 200 source applications and some applications have thousands of tables. See model yml file inside [big.zip](https://github.com/fishtown-analytics/dbt/files/5859807/big.zip), which approximately replicates the size of our data warehouse.

After adding the above yml file to models folder, run `dbt docs generate` and then `dbt docs serve`.

### Expected behavior
Expected to be able to navigate the docs site. 

### Screenshots and log output
Firefox:
![image](https://user-images.githubusercontent.com/5506411/105571563-b4888e80-5d05-11eb-889a-509111a9647d.png)

Chrome:
![image](https://user-images.githubusercontent.com/5506411/105571638-7c358000-5d06-11eb-951b-587c72cc2fd4.png)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [X] other (specify: SQL Server)

**The output of `dbt --version`:**
```
installed version: 0.19.0-rc2
   latest version: 0.18.1

Your version of dbt is ahead of the latest release!

Plugins:
  - bigquery: 0.19.0rc2
  - postgres: 0.19.0rc2
  - redshift: 0.19.0rc2
  - snowflake: 0.19.0rc2
  - sqlserver: 0.19.0rc2
```

**The operating system you're using:**
Windows 10

**The output of `python --version`:**
Python 3.8.3

### Additional context
40,000 tables eventually loads...

How difficult would it be to add a docs generation mode where each table gets its own html page and we avoid loading the entire manifest.json into browser memory?

**Comment by jtcohen6** [comment]
Hey @panasenco, thanks for raising this! I'm going to transfer this issue to the dbt-docs repo. As you can see in https://github.com/fishtown-analytics/dbt-docs/issues/170 as well, the docs site is due for a refactor, now that there exist projects orders-of-magnitude bigger than it was initially designed to support a few years ago.

**Comment by panasenco** [comment]
Thanks @jtcohen6!

The file `manifest.json` is 89MB with ~100k tables and 38MB with ~40k tables, so approximately 1KB/table.

I'm considering taking a stab at this (currently browsing through the source code). Thinking back to the conversations you had, could you share what refactoring approach you liked the most? What's the most ideal way forward?

**Comment by panasenco** [comment]
Looking at the source code, the quickest hack would be to:

- Generate multiple `manifest.json` files by redefining the `write()` method of [WritableManifest](https://github.com/fishtown-analytics/dbt/blob/cb460a797c5cf73567fb42f17fba165e12facd80/core/dbt/contracts/graph/manifest.py#L949)
- Somehow rewriting [loadProject](https://github.com/fishtown-analytics/dbt-docs/blob/master/src/app/services/project_service.js#L106) to only call one manifest at a time and then calling loadProject on every table or database change.

However, this hack wouldn't be pretty and would probably break countless things. I'll just wait for you guys to implement it properly.

In the meantime, I'll write a script to generate dbt doc sites for each of my source databases separately as a workaround. Then people can refer to these individual static sites when discovering data, and use a separate site for actual models.

**Comment by panasenco** [comment]
For anyone looking for a workaround, I just wrote the first version of my Python script that generates an index of multiple dbt documentation sites:

https://github.com/panasenco/dbt-docs-index

You can now split your dbt documentation into multiple separate sites and use this script to build an index of them.
