### ISSUE TITLE
Macro postgres_get_relations makes dbt run slow

### ISSUE THREAD

**Issue by evehmane** [dbt-labs/dbt-core#3058]
### Describe the bug
I have a Postgres database with about 200 tables in 10 different schemas. When I run `dbt run` it gets stuck for about 20 seconds in macro `postgres_get_relations`.

Even if I select just one model and the actual data transformation takes less than a second,  I have to wait extra 20 seconds. This makes development really slow.

There's a possible solution at the end of this issue description.

### Steps To Reproduce

- Create Postgres database with multiple schemas and tables (difficult to give exact sample data)
- Run `dbt --debug run`
- Wait until the following is printed (this is the SQL of `postgres_get_relations` macro):
```
with relation as (
    select
        pg_rewrite.ev_class as class,
        pg_rewrite.oid as id
    from pg_rewrite
),
class as (
    select
        oid as id,
        relname as name,
        relnamespace as schema,
        relkind as kind
    from pg_class
),
dependency as (
    select
        pg_depend.objid as id,
        pg_depend.refobjid as ref
    from pg_depend
),
schema as (
    select
        pg_namespace.oid as id,
        pg_namespace.nspname as name
    from pg_namespace
    where nspname != 'information_schema' and nspname not like 'pg\_%'
),
referenced as (
    select
        relation.id AS id,
        referenced_class.name ,
        referenced_class.schema ,
        referenced_class.kind
    from relation
    join class as referenced_class on relation.class=referenced_class.id
    where referenced_class.kind in ('r', 'v')
),
relationships as (
    select
        referenced.name as referenced_name,
        referenced.schema as referenced_schema_id,
        dependent_class.name as dependent_name,
        dependent_class.schema as dependent_schema_id,
        referenced.kind as kind
    from referenced
    join dependency on referenced.id=dependency.id
    join class as dependent_class on dependency.ref=dependent_class.id
    where
        (referenced.name != dependent_class.name or
         referenced.schema != dependent_class.schema)
)

select
    referenced_schema.name as referenced_schema,
    relationships.referenced_name as referenced_name,
    dependent_schema.name as dependent_schema,
    relationships.dependent_name as dependent_name
from relationships
join schema as dependent_schema on relationships.dependent_schema_id=dependent_schema.id
join schema as referenced_schema on relationships.referenced_schema_id=referenced_schema.id
group by referenced_schema, referenced_name, dependent_schema, dependent_name
order by referenced_schema, referenced_name, dependent_schema, dependent_name;
```
- After many seconds (20 seconds with my data) the following is printed and the run continues:
```
2021-02-09 08:34:31.093759 (MainThread): SQL status: SELECT 0 in 20.47 seconds
```

### Expected behavior
The run should be completed much faster. Macro `postgres_get_relations` should be completed in close to zero seconds.

### System information
**Which database are you using dbt with?**
Postgres 12

**The output of `dbt --version`:**
```
installed version: 0.19.0
   latest version: 0.19.0

Up to date!

Plugins:
  - bigquery: 0.19.0
  - snowflake: 0.19.0
  - redshift: 0.19.0
  - postgres: 0.19.0
```

**The operating system you're using:**
macOS Catalina (10.15)

**The output of `python --version`:**
Python 3.8.0

### Additional context

I debugged this by running the SQL of `postgres_get_relations` in psql and noticed that `relationships` CTE had duplicate rows and joining them to `schema` CTE twice made the query slow.

I am able to fix this issue in my local dbt code by changing https://github.com/fishtown-analytics/dbt/blob/2b48152da66dbd7f07272983bbc261f1b6924f20/plugins/postgres/dbt/include/postgres/macros/relations.sql#L48 from
```
select
```
to
```
select distinct
```

**Comment by jtcohen6** [comment]
Thanks for the detailed writeup @evehmane!

I'm glad to hear you were able to resolve this by tinkering around with `postgres_get_relations()`. You mentioned in your "local dbt code," and I'm not sure if you mean a cloned/forked version of dbt or the code in your dbt project. I just want to make sure you know that, if you add a macro to your dbt project called `postgres_get_relations()`, it will override the builtin behavior and dbt will use yours instead.

A couple clarifying questions, to inform whether we should make this change for all dbt users:

1. Have you been able to identify _why_ there are exact duplicates in the `relationships` CTE?
2. It sounds like adding `select distinct` to the `relationships` CTE significantly reduced the query time. How much faster did it become? What is the total row count before and after?

**Comment by evehmane** [comment]
Thanks for your response!

I meant my cloned version of dbt. I didn't realize I could add this modified macro to my dbt project so thanks for pointing that out!

1. I think `dependency` CTE is actually the cause for duplicates because it seems there can be many `pg_depend` rows per table. So instead of writing `select distinct` in `relationships` CTE I can do it in `dependency` to get the same effect.
2. The query time dropped from 20 seconds to 0.02 seconds and the row count of `relationships` from 273 to 43.

**Comment by vergenzt** [comment]
Just wanted to chime in and say I'm experiencing this too, except it's adding ~3.5 minutes of startup lag instead of 20 seconds. 😬 

After applying @evehmane's substitution to a project-local copy of the macro, runtime for that specific macro according to debug logs went from `SQL status: SELECT 318 in 214.11 seconds` to `SQL status: SELECT 318 in 0.15 second`.

**Comment by jtcohen6** [comment]
Wow! That's a pretty compelling difference @vergenzt. I'd welcome a PR to update the macro within the `dbt-postgres` adapter.
