### ISSUE TITLE
add a jinja filer `quote`

### ISSUE THREAD

**Issue by hui-zheng** [dbt-labs/dbt-core#3113]
### Describe the feature

In dbt Jinja, it would be great to have a custom filter for quote.
for example,
```
{% set jinja_var = "a hard-coded label" %}
SELECT {{ jinja_var | quote }}  as label
```

would render to
```
SELECT "a hard-coded label" AS label
```

It's similar to the [jinja quote filer in Ansible](https://ansible-docs.readthedocs.io/zh/stable-2.0/rst/playbooks_filters.html#other-useful-filters)

### Describe alternatives you've considered
currently I use a custom macro, 

```
{% macro s_quote (str, quote="'") %}
  {% set quoted = quote ~ str ~ quote %}
  {% do return(quoted) %}
{% endmacro %}
```

However, It doesn't support nice chaining as a filter does.

### Who will this benefit?
I think anyone who uses jinja to render hardcode string in SQL statements

### Are you interested in contributing this feature?
yes, I am interested

**Comment by jtcohen6** [comment]
Hey @hui-zheng! I don't think we do much with custom Jinja filters today—in fact, I think we've gotten away without implementing any. I appreciate that the syntax of chaining together filters feels nicer:
```sql
SELECT {{ jinja_var | capitalize | quote | length }}  as label
```
But this is still very much possible with custom macros:
```sql
SELECT {{ s_quote(jinja_var | capitalize) | length  }}  as label
```

In particular, when it comes to something as sensitive as quoting, I find myself agreeing with Dylan's recommendation in [the Slack thread](https://getdbt.slack.com/archives/C2JRTGLLS/p1613597838043900), and adding the quotes within the SQL layer:
> Is there a reason you want it to be in the Jinja itself? i.e. would the following work?
> `SELECT "{{ jinja_var }}"  as label`

**Comment by kd7vrc** [comment]
While quoting a single string is simple enough without the jinja filter, mapping over a list requires the filter.
```
{% set my_strings = ['a', 'b', 'c'] %}
{{ my_strings | map('quote') |  join(',') }}
```
would render as
`"a","b","c"`

**Comment by mroy-seedbox** [comment]
@kd7vrc: Just do `"{{ my_strings |  join('","') }}"`.

**Comment by victorrgez** [comment]
as a workaround, you can do this:
```
{%- for s in my_strings -%}
     '{{ s }}'{% if not loop.last %}, {% endif %}
{%- endfor -%}
```
