### ISSUE TITLE
[CT-105] use black code formatter

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3195]
Let's introduce the automated code formatting to dbt as long as it does not sacrifice readability. As the codebase matures, it will be nice to not have to think about formatting, generate clean diffs, and maintain a single code style.

[black code formatter docs](https://black.readthedocs.io/en/stable/)

First, run on a subset of files and get feedback from contributors about stylistic decisions. We may need to tweak line length and other knobs to our liking.
Then:
- Add `black` as a dev dependency
- Update `tox.ini` and where tox code checks are run in CI and Makefile. May need 2 different tox envs, one to check formatting and one to actually run the formatter
- Get the changes above reviewed
- Finally, create a commit that runs the formatter on the whole repo and set the author of the commit to a machine user so we can easily determine blame history.

**Comment by leahwicz** [comment]
Closing as dupe to #4635
