### ISSUE TITLE
[CT-104] use pre-commit to manage code checks (enforce styleguide, code formatting, type checks)

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3196]
[pre-commit](https://pre-commit.com/) is a tool to manage git hooks and run code checks in an isolated, reproducible environment. I suggest we use this tool to manage code formatting, code linting, and static type checking. We can optionally allow developers to allow pre-commit to manage git hooks for the repository.

- Add a pre-commit config
- Update `tox.ini` to use pre-commit in place of other code checks
https://github.com/pre-commit/pre-commit/blob/a1b462c94a94aa15af3d676700c834f79d2b2b7e/tox.ini#L12-L15
- update CI to use new tox envs
- update Makefile to use new tox envs
- update any relevant documentation, provide instructions to install git hooks, and provide instructions how to skip checks (`SKIP=mypy`)

**Comment by iknox-fa** [comment]
Awaiting clarification in slack:
https://dbt-labs.slack.com/archives/C02UT9M9613/p1643323532290579
