### ISSUE TITLE
Sharpen our Python tooling

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3199]
### Describe the feature
We have a lot of room to sharpen our Python tooling to improve the developer experience as well as lessen the cognitive of doing trivial code checks on our code base. I will suggest a few changes.

### Describe alternatives you've considered
We could continue on the path we are on until. Folks who don't have a deep understanding of how tox, pytest, our integration tests, flake8, mypy work and how they are configured for `dbt` will (and currently) have a difficult time contributing.

### Who will this benefit?
All current and future devs!

**Comment by jtcohen6** [comment]
We've been making some progress in this direction. I'm going to close this issue for logistical reasons: we're no longer using the `Epic`-based workflow tool, and we've been doing a better job of labelling issues in this vein with `tech_debt`.
