### ISSUE TITLE
Truncate data in table

### ISSUE THREAD

**Issue by HardRock4Life** [dbt-labs/dbt-core#3223]
Hello everyone!

My question might be a duplicate, but I had found no issue matching my request:

Is there an approach to truncate/overwrite data in the final table?

**Comment by jtcohen6** [comment]
Hey @HardRock4Life! Could you say a bit more about what you're after, and your intended use case?

I'm not sure if you're asking for:
1. [Incremental models](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models), which seek to only add/overwrite new and updated records
2. Atomic replacement of tables: `create or replace table` on adapters that support it, alter-rename-swap within a transaction on other adapters

dbt used to have a "non-destructive" mode for running that would skip views and truncate + insert all tables. This mainly existed to work around cascade-dropped views on Postgres and Redshift (ameliorated by the advent of late-binding views on the latter). We removed that (https://github.com/fishtown-analytics/dbt/issues/1415) in favor of better implementing 2 for all analytical databases. It's still an issue on Postgres (https://github.com/fishtown-analytics/dbt/issues/2185), which is a known limitation.
