### ISSUE TITLE
Allow lineage relation display from existing dbt models to dbt sources table

### ISSUE THREAD

**Issue by Shadowsong27** [dbt-labs/dbt-core#3331]
### Describe the feature

The general use case: 

we have data transformation pipelines in different styles mainly pure SQL and non-SQL (Python, Spark, ML models etc).

I am aware that `dbt` is supposed to focus just on the PURE SQL transformations.

However, i feel its reasonable that we want to observe the data lineage (because this is so cool and informative for the team, and we use this to validate our Airflow Task dependencies) between the input and output of such Non-SQL transformations, whose inputs could be themselves existing dbt models, and output a table in data warehouse.

I am currently defining these output as `source` table, but apparenly the lineage is lost from the input to the output. I am not sure whether there are some existing solutions, tried to search for something similar failed. 

So is describing such lineage in the interest of the dbt? 

Note I am not requesting an actual bridge for the external data, nor the dynamic schema templating for the Python code, just the lineage description starting from a `source` to some other existing models.

### Describe alternatives you've considered

It does not have to be `source`, it could be something completely new as `external` data set, which generically handles the output of any types of transformation.

### Additional context

Not database specific.

### Who will this benefit?

It helps cover more aspects of the pipeline in documentation

### Are you interested in contributing this feature?

Probably when I am more familiar with the tool since I am new.

**Comment by Shadowsong27** [comment]
@jtcohen6  

After reading thru the coversations, I think this is a wonderful solution, at least to my problem, it supplements the lineage and documentation features without much structural changes. Since I am new to dbt, I am unable to provide much more in-depth insights / feedback to the solution above, but based on my intuition this is the way to go, and I am more inclined to vote against the triggering of external transformation from dbt since 

1. it is kinda against dbt's original design?
2. we already have Airflow and stuff to handle the orchestration
3. it is hard to handle the dynamic schema issue (which is another highlight for dbt IMO) generically for external service, not completely undoable but indeed a big step - it requires the user to agree on certain setup in the CLI and the inner piece of the code

So for lightweight users who use purely SQLs, dbt is sufficient and most likely they don't even need a full-fledge orchestration tool like Airflow, they can simply use DBT cloud for that.

For heavy users with a varied types of transformation, I feel you can't escape Airflow these days, so what Airflow is bad but DBT is extremely good at is the lineage - exposure + docs display.

Just one suggestion, unless I really missed it: Although you guys already have a wonderful documentation, I think this piece of information should be added in as well. It can be put under some sort of special use cases or best practice sections.

And another immature thought: would it be useful to have the type of exposure, source displayed on the lineage graph too? I know in this case the source is a `pass-through` SQL, but in terms of information display it might be useful to show it originated from, say `ML models`. but yeah of course we can work-around it with the source name.

**Comment by BenoitLF** [comment]
Commenting to remove the stale status because it corresponds to one of our needs
