### ISSUE TITLE
Better node identification

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#3348]
### Describe the feature
As proven by the necessity to add a hash to a test node's `unique_id`, the current model of node identification could use some tweaking.

This was discussed in previous ticket comments:
https://github.com/fishtown-analytics/dbt/pull/3335#discussion_r631213752
https://github.com/fishtown-analytics/dbt/pull/3335#discussion_r629693671

### Describe alternatives you've considered
This isn't well fleshed out yet, but the ideas that come immediately to mind are:
- re-work the existing human readable unique_id so the naming scheme is actually unique
- replace the unique_id with a full hash and include enough tooling that we don't have to manage hashes by hand in tests, etc.

### Who will this benefit?
This will make development simpler and eliminate the need for [post-parsing checks like this](https://github.com/fishtown-analytics/dbt/blob/bfdf7f01b55a90ea8292e1c537b6cf44faa412ab/core/dbt/contracts/graph/manifest.py#L1262).

### Are you interested in contributing this feature?
![image](https://user-images.githubusercontent.com/81931810/118032134-eb25fb80-b32c-11eb-8052-e47a8c00ead6.png)

**Comment by jtcohen6** [comment]
Thanks for this @iknox-fa! I'm tagging this `tests` because this is most relevant to schema/generic test nodes, for which the node `name` is auto-generated. (Every other node name is user-specified, often based on the file name.)

There was a great [thread over in Slack just now](https://getdbt.slack.com/archives/C01UM2N7814/p1620843008122800) about what might make sense from a user's point of view.

**Comment by iknox-fa** [comment]
@jtcohen6 I see where you're coming from, but it's actually more about the `unique_id` than the `name`.  For that reason I'm thinking we should keep all nodes in-play here.

Right now we have three+ ways to ID a node: `unique_id` `unique_id` + hash, and `name`.  I'd love it if we could get that down to one human readable identifier, but I rather doubt it will stay human readable* as we add more to the node content.

If that is the case, uniform logic to handle `unique_id`s as a hash and `name` as a human readable label seems like a likely solution and would include all nodes.

*unless you want a Donaudampfschifffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaft

**Comment by leahwicz** [comment]
* Human readable vs hash? 
* If we do a hash we should be able to translate it back to the original name
* We need a design discussion on this

**Comment by leahwicz** [comment]
Let's do a design doc on this first and then scope

Also we need to talk to the metadata team to see if this would impact them

**Comment by jtcohen6** [comment]
@nathaniel-may Thank you again for this excellent comment. While thinking about this on the train, I realized that the code to fix this one is super straightforward and self-contained, so I gave it a go in https://github.com/dbt-labs/dbt-core/pull/4898
