### ISSUE TITLE
Stabilize structured logging

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#3359]
dbt can output structured JSON logs via:
- `dbt --log-output json` (CLI)
- `logs` parameter (RPC)

These logs include a lot of information _similar to_ dbt's JSON artifacts, with the crucial differences being that logs are written/returned in real time, whereas JSON artifacts are only written at the end of invocations.

As of v0.19, JSON artifacts are contracted and documented, but JSON logs are _not_ contracted and [barely documented](https://docs.getdbt.com/reference/global-cli-flags#log-formatting). We should change this ahead of v1.0. There are other technologies and community members who want to build on top of stable logs (e.g. dbt Cloud IDE, https://github.com/fishtown-analytics/dbt/issues/2915).

As I see it, the scope of this issue is to:
- Document structured (JSON) logs as they work today
- Communicate which components are stable (statuses, log-levels, node-level information) and which components are liable to change in future versions (exact language of info-level messages)
- Identify discrepancies between the information available in structure logs and the information included in JSON artifacts, and (if very slight) bring them into consistency

**Comment by kwigley** [comment]
### today
- stdout logging -> just log message
- debug logging -> time, thread, message
- json logging -> time, thread, channel, level, levelname, thread, process, **extra**
	- extra is just arbitrary data at the moment, added by using a context manager
		- node index
		- node count
		- unique id
		- is status message

### future
- implement pattern for logging to support better structured logging
- turn all logging into structured logs -> https://github.com/hynek/structlog

**Comment by leahwicz** [comment]
* LogBook isn't great to keep using (seems abandoned) 

* We need to see what we want to do for events (pub/sub) b/c ppl use our logs as a way to see events which is not what the logs should be used for (not needed for v1)

Open questions:
* What are the big painpoints in the logs for Cloud/consumers?
* Need to see where we are doing logging

**Comment by jtcohen6** [comment]
- Stabilizing, rationalizing, documenting the content of structured logs: this issue!
- How we push the contents of those logs for real observability/integration: pubsub issue for the future

**Comment by jtcohen6** [comment]
To make this even more concrete, I see a bug like https://github.com/dbt-labs/dbt/issues/3603 to be right square within the scope of this issue

**Comment by drewbanin** [comment]
This is a great thread!  [structlog](https://github.com/hynek/structlog) looks fantastic, and it would be a _really_ good idea to move away from logbook -- do we think we can do that pre-1.0?

Here's my braindump on structured logging:

**Format of json log lines**
Right now, all "structured" info in our json logs gets shoved into an `extra` key in the log line. Here's an example:

```
{"timestamp": "2021-10-05T13:17:28.018538Z", "message": "Finished running node model.my_new_project.my_model", "channel": "dbt", "level": 10, "levelname": "DEBUG", "thread_name": "Thread-2", "process": 19949, "extra": {"node_status": "passed", "node_finished_at": "2021-10-05T13:17:28.018543", "unique_id": "model.my_new_project.my_model", "run_state": "running"}}
```

This log line contains a fragment of information related to the `model.my_new_project.my_model` model. The big idea with our current logging is that _if you capture all of the log lines emitted for a model_ then you can "know" its state at any point in time. Further, you can collect all of the logs for a model together by selecting all of the log lines with a matching `log.extra.unique_id` value.

I think that a better approach to structured logging would have contracted fields in each log line. These fields would represent the state of a specific entity. This would be simpler for clients to consume than a kitchen-sink style "extra" field.

**Log/event names**

The "message" in each log line is not semantically useful. The example above has a message like `Finished running node model.my_new_project.my_model`, which isn't really suitable for a client to depend on. Instead, each structured log line should have a contracted name/message/type that clients can use to process certain logs/events. Today, you'd either need to:
1. Do something pretty jank to inspect and respond to the `message` field of the log line OR
2. Depend solely on the existence of fields in the log line (eg. if there is `node_finished_at` in the `extra` property of the log, then a node has finished running.

Instead, it would be a lot better if we decoupled these "structured" log lines from typical debug/info-level logs that are intended for humans to read. Each structured log could have a semantically useful name (or message) like `node_status_update` that communicated the type of information in its payload.

**Node information completeness**

Today, structured logs contain partial updates about a given node. In the example above, the log line shows when the node finished, but the information about when that node started is in a different ~castle~ log message. Instead, I think it would be better if log lines contained _all_ of the information that we had about a node at the point in time that the log occurs. An example could look like:

```
{[other fields here]...., "node_info": {"node_path": "models/slow.sql", "node_name": "slow", "resource_type": "model", ""node_materialized": "table", "node_started_at": "2021-10-05T13:17:28.018613", "unique_id": "model.my_new_project.slow", "run_state": "running"}}
{[other fields here]...., "node_info": {"node_path": "models/slow.sql", "node_name": "slow", "resource_type": "model", ""node_materialized": "table", "node_started_at": "2021-10-05T13:17:28.018613", "unique_id": "model.my_new_project.slow", "node_finished_at": "2021-10-05T13:17:29.134126", "node_status": "passed", "run_state": "running"}}
```

This would make it possible for a consumer of the structured logs to know the state of a node at any point in time without needing to consume the entirety of a potentially very long log file.

Note: I am kind of on the fence about this one. I think it's probably a bad idea to assume that a client could "know" everything about a dbt run without consuming all of the structured logs for that run. Instead, I think that more complete structured logging would be good ergonomics for clients -- it would reduce the amount of "state building" that would need to happen on the client, and ultimately would give us more flexibility around how & when we log node information inside of dbt Core.

**Completeness**

There's a lot happening inside of dbt that _is not_ emitted in structured logs today. There are some potentially slow actions like _building the adapter cache_ that are not logged in such a way that clients can render progress information to a user. We should consider new types of structured logging around project parsing/run startup/running hooks (both on-run-start/end, and pre/post-hooks), etc, that communicate the exact status of dbt Core as it operates on projects.

**Materialization-based logging**

It would be _really good_ if logs could be emitted inside of materializations. This could help us communicate what's happening when a given model is running. Quick example of state transitions:
1. Running {model} with 3 steps
1. Running pre-hook 1 of 1 (1/4, 25% complete)
1. Creating a temp table {temp_table} (2/4, 50% complete)
1. Merging from {temp table} into {destination table} (3/4, 75% complete)
1. Running post-hook 1/1 (4/4, 100% complete)

This would totally be a stretch goal, but I think the idea of materializations being less imperative and more "planned out" is probably well-aligned with our goals for model building into the future :)

That's it! Those are all of the thoughts in my head around structured logging. Lmk if there's anything else I can shine a light on!

**Comment by nathaniel-may** [comment]
Thanks for the feedback @drewbanin! This helps a lot.

Regarding the "programmatic log processing" use case, it seems like the requirements are for core to support a dbt client in reporting the state of a run to a user in live time. I don't think writing these events to a log file then reading them again is actually the right way to achieve this goal, so I want to make sure that even if our initial solution is to stream logs, we have built the necessary plumbing to do it the right way when we need it. The type modeling for events on top of the logger in this proposal would allow us to send events to any number of destinations (potentially an event history in memory for clients to stream via a server layer) independent of the configured log level. If you think all of these events will always need to be logged, that's something I'll need some clarification around, since I'll want to guard against IO contention as best I can.

**Comment by drewbanin** [comment]
>  I don't think writing these events to a log file then reading them again is actually the right way to achieve this goal, so I want to make sure that even if our initial solution is to stream logs, we have built the necessary plumbing to do it the right way when we need it.

What do you think the right way to achieve this goal is?

**Comment by nathaniel-may** [comment]
Generally, when streaming status updates to a client I'd reach for a server end point. Either polling or http2 streams. It handles concurrency better, doesn't rely on synchronous reads and writes to a file on disk, and can be flexible about the information returned to minimize network load. Some off the shelf frameworks like graphql provide some of this for you because they're meant for this exact kind of pattern.

**Comment by drewbanin** [comment]
ok - i buy that as an overall strategy! I think my point of contention is that I don't think dbt Core shouldn't actually do anything like that -- it should instead provide an API for letting a wrapping process tap into the logs and then implement polling / http2 streams / websockets / etc.

This is actually a big challenge today that @kwigley and I have been discussing recently -- dbt Core's logger framework makes it _very hard_ for a process that imports dbt to tap into the log stream. You can do it, but jankness abounds! My preference would be to:
1. Support writing logs to file
2. Support tapping into the log stream in a first-class way so that file IO can be bypassed entirely if the wrapping process imports dbt and uses it as a library

Here's an example of the kind of jankness that's necessary today (more or less):
```python
import dbt.logger as dbt_logger
import logging

GLOBAL_LOGGER = logging.getLogger(__name__)
GLOBAL_LOGGER.setLevel(logging.DEBUG)
stdout = logging.StreamHandler()
stdout.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
stdout.setFormatter(formatter)
GLOBAL_LOGGER.addHandler(stdout)
logger = GLOBAL_LOGGER

json_formatter = dbt_logger.JsonFormatter(
    format_string=dbt_logger.STDOUT_LOG_FORMAT
)

# This could be any kind of log handler -- file, memory, or otherwise
logs_redirect_handler = logbook.FileHandler(
    filename=self.log_path,
    level=logbook.DEBUG,
    bubble=True,
    filter=lambda x: x.channel.split(".")[0] == "dbt"
)


# If you don't do this, then Core logs to a file itself
dbt_logger.log_manager.set_path(None)

# Reach into dbt lib and mutate the log managers handler list!! This is bad
dbt_logger.log_manager.objects = [
    handler
    for handler in dbt_logger.log_manager.objects
    if type(handler) is not logbook.NullHandler
]

# Create a new nested logging setup
handlers = [logbook.NullHandler(), logs_redirect_handler]
self.log_context = logbook.NestedSetup(handlers)
self.log_context.push_application()

### This is where you can actually invoke dbt and capture logs
dbt.do_the_thing()

### Pop the log handlers
self.log_context.pop_application()
```

A better approach IMO looks like:
```python
import dbt.logger as dbt_logger

# create whatever kind of log handler you want
logs_redirect_handler = logbook.FileHandler(
    filename=self.log_path,
    level=logbook.DEBUG,
    bubble=True,
    filter=lambda x: x.channel.split(".")[0] == "dbt"
)

# tell dbt to exclusively write logs to our handler, not its own internal handlers
dbt_logger.override_log_handler(logs_redirect_handler)
```

Again - the FileHandler is just an example - this could alternatively be a [StreamHandler](https://logbook.readthedocs.io/en/stable/api/handlers.html#logbook.StreamHandler) that buffers logs in memory and could be connected up to a polling service or http2 streams :)

**Comment by mobuchowski** [comment]
Hey all, this looks like wonderful feature that we'd love to use in [OpenLineage dbt integration](https://github.com/OpenLineage/OpenLineage) - especially getting live updates on node state transitions. 

One question: will we get (some) standarized adapter responses the same way? We'd like to report information like row count and byte size written, which we now get from `run_response.json` file.

**Comment by jtcohen6** [comment]
@mobuchowski Glad to hear this will be of help!

Adapter responses will continue to live on the `result` object for each node. Those results are included in `run_results.json`, and they're also used to construct several events / log messages while a node is running. I don't know if we already have a task event that includes the full `result` contents. I do think it would be possible, as a slight extension on top of the foundation we're working hard to build right now.
