### ISSUE TITLE
Parameterize key selecting for `list` task in RPC

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#3395]
Parametrize the set of ALLOWED_KEYS via `--keys` flag (CLI) or `keys` parameter (RPC). If not specified, we'd use the current hard-coded set as the default.

This will allow consumers of the RPC `list` method to customize responses by:
- Including additional available node properties without needing to wait for a new dbt version
- Trimming result payloads by limiting scope to only the keys that are needed

**Comment by jtcohen6** [comment]
Resolved by #3838
