### ISSUE TITLE
Allow tests to have owners

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#3436]
### Describe the feature
Some of our tests are checking the validity of data that we don't control, for example a Google Sheet mapping employees to employee IDs, or the [accuracy of revenue from HubSpot](https://getdbt.slack.com/archives/C0VLNUUTZ/p1622762514224600). If those tests fail, we currently have to relay that information to the responsible parties to get it fixed up. 

In a similar vein to exposures, it would be useful to know who is responsible for a test failing. In the short term this would be useful just to centralise the information instead of it hanging out in my head. In the longer term I could imagine users parsing run_results and programmatically notifying the guilty parties (maybe a native feature to dbt Cloud too). 

This programmatic notification would be particularly compelling given the persistence of tests' failing rows in 0.20.0, because it could be "these rows are bad" instead of "there's 2 bad rows out there somewhere".

### Describe alternatives you've considered
- Right now, we've made a Mode dashboard pointing at dbt models of the invalid rows (and then the dbt tests are data tests which select * from those models), which we expect stakeholders to review regularly.
- Including the information in the description of the model itself
- Do tests support `meta` properties? That would mostly cover the short-term use case.

### Who will this benefit?
People whose tests are failing, but they're not the people responsible for fixing the user-generated inputs

### Are you interested in contributing this feature?
Maybe in a couple of months!

**Comment by jtcohen6** [comment]
Thanks for opening @joellabes! I'd love to think about this some more.

We could think about adding `owner` as a first-class property of other resource types, in addition to exposures. For now, exposures are the first place we're experimenting with this kind of observability; I'd love to see us think about translating that into automated and targeted notifications.

In a world where `owner` can be set on models/sources/seeds/snapshots, too, I wonder if tests should inherit the `owner` of the resource they select from? (#3256)

> Do tests support `meta` properties? That would mostly cover the short-term use case.

Yes, tests do support `meta` properties—so, in the meantime, this is probably your best bet. Although it's a little kludgy, you could join between `run_results.json` and `manifest.json` to figure out who's responsible for each failing test, and perhaps even send them an email. A workflow like that would make a lot of sense in dbt Cloud, someday...

**Comment by codigo-ergo-sum** [comment]
Just adding my two cents here that this would be an awesome feature and also I think there's a lot of room for further innovation and improvement in this area. We constantly have these issues about wanting to push issues with failing tests automatically out to the designated owners of the data sources, where we don't control the data sources nor manage the owners per se.

**Comment by jtcohen6** [comment]
> Yes, tests do support `meta` properties

Update here: they used to, sort of / not exactly, as an undocumented feature (neither [here](https://docs.getdbt.com/reference/resource-properties/tests) nor [here](https://docs.getdbt.com/reference/resource-properties/meta)) that didn't work quite right. Let's add real support for `meta` to tests: https://github.com/dbt-labs/dbt/issues/3629
