### ISSUE TITLE
error on non-existing table referenced in snapshot (expected: warning)

### ISSUE THREAD

**Issue by diegodewilde** [dbt-labs/dbt-core#3478]
### Describe the bug
dbt fails when a table mentioned in the snapshot table is not (yet) existing.  
This can happen when: 
- you've just created a new model
- you want to have it snapshotted
- your snapshot runs before the actual dbt run

### Steps To Reproduce

1. Create a model `temp_model.sql` within the `models` folder
2. Copy-Paste the following content: 
```
select
    1 as id,
    'dummy value' as dummy_column,
    now() as updated_at
```
3. Create a snapshot `temp_snapshot.sql` within the `snapshots` folder
4. Copy-Paste the following content: 
```
{% snapshot temp_snapshot %}

{{
    config(
      target_database='analytics',
      target_schema='snapshots',
      unique_key='id',

      strategy='timestamp',
      updated_at='updated_at',
    )
}}

select * from {{ ref('temp_model') }}

{% endsnapshot %}
```
5. Execute `dbt snapshot --select temp_snapshot` (without executing dbt run).

### Expected behavior
dbt should report (= warning) that it couldn't find the table for the snapshot. This could be an optional parameter.

### Screenshots and log output
```
Completed with 1 error and 0 warnings:

Database Error in snapshot temp_snapshot (snapshots/temp_snapshot.sql)
  relation "<schema>.temp_model" does not exist
  LINE 10:     from <schema>.temp_model
                    ^

Done. PASS=6 WARN=0 ERROR=1 SKIP=0 TOTAL=7
```

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - postgres: 0.19.1
```

**The operating system you're using:** /

**The output of `python --version`:** Python 3.9.0

### Additional context
The execution of `dbt snapshot` can be done before executing `dbt run` in a scneario where we want to limit the amount of rows to be processed (e.g. only updated rows).

**Comment by jtcohen6** [comment]
Thanks for opening @diegodewilde, and for providing some context behind your use case.

The specific proposal here doesn't sit quite right with me. If at any point the snapshot query fails, the snapshot should raise an error. The fact that upstream resources are missing is a valid reason for the snapshot query to fail. I don't think we want to add try-handling logic to snapshots such that inspects the database error returned by the snapshot to determine whether it's warn-worthy or error-worthy.

There's a larger issue at play here:
- At the start of each invocation, dbt constructs a relational cache of which tables/views/etc exist in expected namespaces
- dbt knows which database objects are upstream of a given model (via `source` + `ref`)

If a model/snapshot/etc depends on a resource that's missing in the current/expected namespace, should dbt raise a warning at the start of the invocation and skip running the model/snapshot/etc? It knows that the associated query would encounter a database error. This has some conceptual relation to [deferred invocations](https://docs.getdbt.com/reference/node-selection/defer) (`--defer` + `--state`), where dbt repoints to the upstream resources located in the comparison/deferred manifest if they're missing in the current/expected namespace.

I'd be open to discussing that as a separate feature request. But it goes a few steps beyond the highly specific case you're describing in this issue. Speaking of which...

> your snapshot runs before the actual dbt run

Ah! I think we may have another answer here. We're planning a new `dbt build` task (#2743) for dbt v0.21 that will be able to run models _and_ snapshot snapshots, working from left to right across the DAG. That's one way of simplifying the orchestration of `dbt run` and `dbt snapshot` in cases where models and snapshots are deeply inter-dependent.

So for instance:
```
dbt build -s +temp_snapshot
```
This would run all models upstream of `temp_snapshot` _and_ snapshot `temp_snapshot`.

Having said that, could you say more about your final contextual note?

> The execution of `dbt snapshot` can be done before executing `dbt run` in a scneario where we want to limit the amount of rows to be processed (e.g. only updated rows).

I'm not sure I understand how snapshotting before running models helps you limit transformations to only updated rows.
