### ISSUE TITLE
Support console env var DO_NOT_TRACK

### ISSUE THREAD

**Issue by sethwoodworth** [dbt-labs/dbt-core#3540]
### Describe the feature
If the console environment variable `DO_NOT_TRACK` is set (to any value), do not send anonymous usage stats.  The current configuration equivalent is in `~/.dbt/profiles.yml`
```
config:
  send_anonymous_usage_stats: False
```
The website promoting and documenting the standard is: https://consoledonottrack.com/

### Describe alternatives you've considered
The current yaml config: send_anonymous_usage_stats serves the same purpose, but is specific to DBT, where `DO_NOT_TRACK` is intended to be universal.

### Who will this benefit?
Users who would like to avoid sending usage statistics by default would no longer need to:
* discover dbt sends usage statistics
* read documentation to find how to opt-out

### Are you interested in contributing this feature?
Yes, I would be more than willing to implement the feature if the issue is accepted.

**Comment by jtcohen6** [comment]
@sethwoodworth Thanks for opening the issue! This sounds like a great standard to follow. I'd be interested in supporting this via two env vars:
- `DO_NOT_TRACK=0|1` (standard)
- `SEND_ANONYMOUS_USAGE_STATS=True|False` (dbt-specific)

Ultimately, I'd like for every runtime config to have an associated flag, profile config, and env var, as outlined in #2990.

In any case, I'd welcome a contribution for this.
