### ISSUE TITLE
typo in UnparsedSourceDefinition.__post_serialize__

### ISSUE THREAD

**Issue by abuckenheimer** [dbt-labs/dbt-core#3545]
Haven't actually run into a bug from this yet but was just perusing the source code and noticed this:

https://github.com/dbt-labs/dbt/blob/85627aafcd7fcd1a2a1c61b13348ced1b52571d4/core/dbt/contracts/graph/unparsed.py#L271

Have to imagine `freshnewss` is a typo

**Comment by jtcohen6** [comment]
@abuckenheimer I have to imagine you're right :)

Care to make that one-line fix?

**Comment by jtcohen6** [comment]
Still there!

https://github.com/dbt-labs/dbt-core/blob/ba23395c8edfaf11fccfb136db920fd276b1d063/core/dbt/contracts/graph/unparsed.py#L288-L290

Going to mark this a `good first issue`
