### ISSUE TITLE
Add deprecation warnings for renamed commands

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3565]
### Describe the feature
In #3554, we renamed `source snapshot-freshness` -> `source freshness`. Both commands are supported and no deprecation warning is showed. It would be ideal to show deprecation warnings when using the old command.

### Describe alternatives you've considered
Support renamed commands forever via an alias and don't display any deprecation warnings. I'm perfectly happy with this answer as well, I'd happily close this issue if that is acceptable.

**Comment by jtcohen6** [comment]
I agree! Let's do both: continue support `source snapshot-freshness` as an alias forever*, and raise a deprecation warning when it's used.

*At least until dbt v2.0, if not longer :)
