### ISSUE TITLE
[CT-475] Fail-fast writes no run_results.json on error

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#3600]
`dbt run --fail-fast` does not write `run_results.json` if it encounters any error, for any model node, during its run.

I know `--fail-fast` is common in some development + CI setups. Metadata in those environments is lower-stakes than metadata from prod, but I believe it still has value.

We need to decide on and document the expected behavior. Perhaps it's right to consider `--fail-fast` like a keyboard interrupt mid-run, such that the invocation exits without completing.

This will also be less pressing in a future where we've instrumented dbt with a streaming event system, because a single JSON file at the end of a batch process will no longer be our only principal source of metadata.

**Comment by jtcohen6** [comment]
It would be desirable to write `run_results.json` for runs that are cancelled partway through.

Where we write those artifacts them currently, within the `run` step:
https://github.com/dbt-labs/dbt-core/blob/3a3bedcd8eb746ac81d006bbe35a0e5714dadbf2/core/dbt/task/runnable.py#L466-L468

That `result` is the returned value from `execute_with_hooks`, which calls (in turn) `execute_nodes`. That's the method that both collect results _and_ handles cancellation due to `--fail-fast`/`KeyboardInterrupt`:

https://github.com/dbt-labs/dbt-core/blob/3a3bedcd8eb746ac81d006bbe35a0e5714dadbf2/core/dbt/task/runnable.py#L383-L391

Is there a way we can replumb this to write partially complete results? I think the right next step might be to spike the difficulty of that replumbing.

**Comment by iknox-fa** [comment]
> I think the right next step might be to spike the difficulty of that replumbing.
In BLG we all agreed.  See: https://github.com/dbt-labs/dbt-core/issues/5204

**Comment by iknox-fa** [comment]
No estimate 5/2 /22 BLG, awaiting spike

**Comment by kieronellis** [comment]
Having errors included in the run_results.json when there's a fail fast would be super helpful for my team as we are using fail fast in our CI setup - Is there any chance of this being implemented? Thanks.

**Comment by jtcohen6** [comment]
Discussing with @ChenyuLInx, an answer that doesn't feel so terrible: **write `run_results.json` after every node completes.** That way, we don't need to gracefully handle graceless exits (whether due to `--fail-fast`, keyboard interrupt, process termination...)

**Comment by jtcohen6** [comment]
Closing in favor of #7302

**Comment by iknox-fa** [comment]
Closed per https://github.com/dbt-labs/dbt-core/issues/7302#issuecomment-1520688109
