### ISSUE TITLE
[Tracking] Automated testing improvements

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3614]

**Comment by leahwicz** [comment]
@nathaniel-may - We didn't scope the tasks in this epic but we want to only do 20 pts so let's prioritize this list (or add what we think is missing and higher priority) and then move the issues that we don't have time for to another epic.

**Comment by nathaniel-may** [comment]
The current plan is to tackle issues that need lots of team feedback. Namely, creating the smoke test suite, and fixing naming conventions. Then while we collect and apply feedback we can fix the flaky tests and turn that coverage back on.
