### ISSUE TITLE
Tooling: Automatically delete old integration test schemas

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-core#3685]
### Describe the feature
Integration tests are failing in Redshift with the error:
```
DETAIL:  Maximum tables limit exceeded. The maximum number of tables per cluster is 9900 for this instance type. The limit includes permanent and temporary tables. (pid:6211)
```

We employ a cleanup script to drop the integration test database on our sandbox Snowflake instance, and we should consider doing the same (or similar) on Redshift + BigQuery too. This will help catch any schemas that accumulate from integration test runs that are "stalled" or cancelled before tables can be cleaned at the end of the test sutie.

### Describe alternatives you've considered
- We probably should get to the bottom of stalled/hanging CI runs. This is a band-aid for that problem, not a silver bullet!

### Additional context
Here's an example query for Redshift - kind of fun:

```
with test_schemas as (

	select
		table_schema,
		right(left(table_schema, 14), 10)::int as prefix,
		timestamp 'epoch' + prefix * interval '1 second' AS schema_create_time,
		count(distinct table_name) as tables
	
	from information_schema.tables
	where table_schema like 'test1%'
	group by 1,2,3

)

select
	date_trunc('month', schema_create_time) as created_month,
	count(*) as num_schemas,
	sum(tables) as num_tables
from test_schemas
group by 1
order by 1 desc
```

The schema name prefix is actually an epoch time, so we can:
1. Manually delete older schemas (ie. to avoid erroring out any in-progress CI checks when old schemas are droppeD)
2. See that most of the tables/schemas are coming from July & August of 2021:

| created_month| num_schemas | num_tables |
| - | - | - |
| 2021-08-01 00:00:00 | 162 | 1003 |
| 2021-07-01 00:00:00 | 1178 | 8842 |
| 2020-09-01 00:00:00 | 8 | 44 |
| 2020-08-01 00:00:00 | 2 | 3 |

For the moment, I'll delete these tables manually

### Who will this benefit?
Contributors!

### Are you interested in contributing this feature?
Happy 2 help

**Comment by jtcohen6** [comment]
This also shows up as failing `docs_generate` tests for BigQuery. Specifically, once we hit 10k schemas in our BQ project, we can no longer identify the schema we need, and we skip cataloging those tables:
```
Skipping catalog for dbt-test-env.test16370006378919244391_docs_generate_029 - schema does not exist
```
The fix is to drop a whole bunch of schemas
