### ISSUE TITLE
DBT Run execution consumption more memory

### ISSUE THREAD

**Issue by chandrainnive** [dbt-labs/dbt-core#3709]
### Describe the bug
I'm running dbt (5 models) in GCP (k8s engine) with minimal record count as 500 Records with some business logic and load the records from one dataset of table to another dataset of table (GBQ) but it consume more memory approx. **2GB**.
Execute the same models in laptop, it occupy **5GB** of ram out of **8GB**. Even same memory occupy second time execution without recompile (No changes in the DBT Models). 

### Steps To Reproduce
dbt run --models +dq__act --selector aca_weeks

### Expected behavior

Need to run the command **dbt run** with minimal memory.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
-  bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
Running with dbt=0.18.1

**The operating system you're using:**

**The output of `python --version`:**
Python 3.7.6

**Comment by joellabes** [comment]
A bit of extra context in Slack: https://getdbt.slack.com/archives/CBSQTAPLG/p1628066783232500

**Comment by jtcohen6** [comment]
Thanks for the link to the Slack thread @joellabes!

@chandrainnive As Joel shared in Slack, dbt does not store any BigQuery data in memory, it simply sends and receives compiled SQL. (The notable exception is if you're using [seeds](https://docs.getdbt.com/docs/building-a-dbt-project/seeds), but it doesn't sound like that's the case here.)

It doesn't surprise me to hear that it requires the same memory to run dbt each time. It does surprise me to hear that you're measuring dbt's memory consumption at 2-5 GB; I wouldn't expect it to be nearly that much. I'd also expect dbt to require roughly the same memory, whether you run it locally (on your laptop) or in GCP (k8s engine).

It's hard to know exactly what's going on from the details you've shared thus far. I have a few questions, in the hopes that one of these may shed light on something else going on:
- How did you install dbt?
- Have you tried using a newer version of dbt?
- How are you measuring dbt's memory consumption?
- Have you tried placing a limit on the memory allocated to each k8s container?

**Comment by chandrainnive** [comment]
@jtcohen6 

Answers for you questions..!

How did you install dbt?
**In laptop :** pip install dbt. (At the time dbt have a version 0.18.1)
**In GCP :** In requirement.txt file (dbt<=0.18.0)
Have you tried using a newer version of dbt?
**In laptop :** Not Yet.
**In GCP :**Not Yet.
How are you measuring dbt's memory consumption?
**In laptop :**  Task Manager --> open resource monitor--> Memory (Verified the python.exe memory consumption)
**In GCP :**measured the pod memory while executing the dbt task in airflow.
Have you tried placing a limit on the memory allocated to each k8s container?
**In GCP :**No

**Comment by jtcohen6** [comment]
Thanks for the quick answers @chandrainnive! When I run dbt locally, I see its memory usage at ~130 MB, which is in line with the order of magnitude I'd expect.

High memory usage isn't one of the performance issues we've been tracking, so I'll do some asking around to see if anyone has an instinct as to a root cause or potential leak. In the meantime, I'd be interested to know if dbt runs successfully for you in a memory-constrained environment.

**Comment by chandrainnive** [comment]
130 MB, Surprise!
Yes, For the single DBT Model there is no issue but it consume more memory. 
As per business logic, have to execute 15 DAG's (15 DBT task) on parallel. At that time DAG is failed and ended with this error.
**_{process_utils.py:66} INFO - Process psutil.Process(pid=16, status='terminated', exitcode=1, started='15:13:10') (16) terminated with exit code 1_**

**Comment by jtcohen6** [comment]
@chandrainnive Ah, now we're getting somewhere! Can I ask why you're running 15 different dbt tasks in parallel? We _really_ discourage that and view it as an anti-pattern—if you accidentally run the same dbt models at the same time in separate invocations, bad things tend to happen.

dbt has a built-in mechanism for running independent models concurrently, configured via [threads](https://docs.getdbt.com/dbt-cli/configure-your-profile#understanding-threads). I think you'd find that a single dbt invocation running many models in parallel will be _much_ more memory-efficient than running each model in a separate invocation.

**Comment by chandrainnive** [comment]
@jtcohen6  The 15 different dbt tasks are not interlinked between that's. Each DBT task have independent other tasks. (No relation to other dbt models,source and target tables.) 

Currently we configured in the profiles.yml with threads=5.

Even i'm trying run the single dbt task in GCP VM machine (Linux)
root@dbt-testing:/home/csomu/dbttesting/DBT# dbt run --models sq_edfi__academicWeeks
csomu@dbt-testing:~$ sudo pmap 2521 | tail -n 1
 total          3071468K

For the above DBT model execution takes 3GB of memory consumption.

**Comment by jtcohen6** [comment]
Hmm ok, I'm really not sure why a single dbt invocation would be eating up 3 GB of memory :(

I'm not sure this will change anything, but you could you try installing a more recent version of dbt, and see if the memory consumption is still that high?

**Comment by chandrainnive** [comment]
Hi @jtcohen6 

Updated the DBT with latest version.

While executing the DBT model, getting the below error

root@dbt-testing:/home/csomu/dbtperformance# dbt run --model dq_edfi_academicWeeks
Running with dbt=0.20.1
Encountered an error:
the JSON object must be str, bytes or bytearray, not 'tuple'

While checking log, it have

  File "/usr/local/lib/python3.6/dist-packages/dbt/hooks.py", line 19, in get_hook_dict
    return json.loads(source)
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'tuple'

Could you guide for fix this issue.

**Comment by jtcohen6** [comment]
@chandrainnive It sounds like you may have a `pre-hook` or `post-hook` defined that's returning a tuple, rather than a string, array, or dictionary. That error message is not a known regression in v0.20.1, but it sounds like it might be, if it raised immediately after upgrading.

Is there anywhere where you set `pre_hook` or `post_hook` to the result of a macro or Jinja object?

**Comment by chandrainnive** [comment]
@jtcohen6 

After Upgraded the dbt with latest and trying to run the same models but it getting error as below.
Running with dbt=0.20.1
Encountered an error:
Compilation Error in model sq__actuals (models/data_lake/sq/sq__actuals.sql)
'NoneType' object is not iterable
Done the below steps
Upgrade the dbt by using pip upgrade dbt.
Added the config version as 2 in dbt_project.yml file.
Ran the dbt deps.
Executing the dbt model.
Need to alter the existing files dbt_project.yml , packages.yml , schema.yml and models/macro ?

**Comment by jtcohen6** [comment]
> ```
> Compilation Error in model sq__actuals (models/data_lake/sq/sq__actuals.sql)
> NoneType' object is not iterable
> ```

Ah, sorry, that's not a particularly helpful error message. It sounds like the model `sq__actuals` may be looping over a variable set to `None`? Perhaps the result of a query that is not executed at parse time?

**Comment by chandrainnive** [comment]
Ok, But the same code is working good in dbt version 0.18.0. I'm not sure....
 why the code is not fit to version 0.20.1

**Comment by jtcohen6** [comment]
@chandrainnive I'm not sure! We made a number of code changes to parsing in v0.19 + v0.20. It's possible that this represents a regression in dbt; it could also be faulty code that wasn't raising an error in older versions, when it should have.

**Comment by chandrainnive** [comment]
@jtcohen6 - There is no faulty code. everything is working fine and fulfill the business validations in the dbt v0.18. Features  decrepitated may be a reason.
ok..! ok..! 
there is any guidelines for reduce the memory consumption in the dbt model execution.

**Comment by vchakra23** [comment]
@jtcohen6:  Is there a way to Identify via release notes all of the changes between v0.18 and v0.20. This will aid in the effort the team has to make in refactoring the code.

**Comment by chandrainnive** [comment]
Hi @jtcohen6 

In my DBT model directory had a more than 100 models it includes data vault models too , with respective configuration in dbt_project.yml. (Laptop machine)

If i Just keep only one model and ran the model first time execution it takes 600MB memory consumption. Second & Third time model execution takes the memory consumption as 150MB only. If i kept all models under DBT directory, execute only one model at the time memory consumption is 3.0 GB and memory consumption is same for second and third time execution also.

Here i missing anything in the configuration. Any other thoughts or suggestions pl.
