### ISSUE TITLE
Partial Parsing error on saving macros in Cloud IDE

### ISSUE THREAD

**Issue by matt-winkler** [dbt-labs/dbt-core#3797]
### Describe the bug

When working from the dbt Cloud IDE with version `0.20.1` editing and saving macros files triggers a partial parsing error that appears to be related to the presence of test logic. 

Note that even though the logs show that the yearly_part_rollup exposure has been deleted, I am not taking any action on that file as a user. There is an exposure with that name in the project.

I did NOT make any substantive changes to the macro code (e.g. no missing jinja tags)

Note also that deleting the `partialparse.msgpack` file from the `target` directory temporarily resolves this issue.

### Steps To Reproduce

1. Log in to the a dbt Cloud account
2. Access a dev environment on a project connected to Snowflake
3. Edit any macro files by adding a space or some other non-substantive change
3. You may need to do this a few times before the compilation error appears

### Expected behavior

dbt Cloud should compile the project without issue.

### Screenshots and log output

**Debug Logs**
2021-08-24T14:33:30.318986Z: Partial parsing enabled: 0 files deleted, 0 files added, 1 files changed.
2021-08-24T14:33:30.319609Z: Partial parsing: deleted exposure exposure.tpch.yearly_part_rollup
'SourceFile' object has no attribute 'get_key_and_name_for_test'

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ X] snowflake
- [ ] other (specify: ____________)

**Comment by jtcohen6** [comment]
Thanks for the detailed report @matt-winkler! Weird that this bug cropped up while you were editing _macros_...

I think the short-term resolution here is going to come from the new handling for partial parse errors in v0.20.2, which will also fire up a stacktrace including the line of code where the error occurred. Then, when we see this error crop up again, we should be able to pinpoint the cause and resolve it, all without interrupting the flow of development.

**Comment by gshank** [comment]
The error encountered ('SourceFile' object has no attribute 'get_key_and_name_for_test') means that a file that was a schema file was de-serialized as a non-schema file ('SchemaSourceFile'). That would only happen if the serialized file did not have parse_file_type = 'schema'. I'm not sure how that would happen.
