### ISSUE TITLE
Using dev dependency `freezegun>1.0` causes Postgres integration tests to hang

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3817]
### Describe the bug
When bumping the development dependency `freezegun` (https://github.com/dbt-labs/dbt/pull/3206), it causes postgres intgration tests to hang. 

### Steps To Reproduce
- bump `freezegun` in `dev-dependencies.txt`
- run postgres integration tests

**Comment by peterallenwebb** [comment]
So much has changed since this is open, and nobody has seen this issue in a year+, so we will close until someone complains again, if it is still a thing.
