### ISSUE TITLE
Use exception chaining to provide more detailed feedback for adapter exceptions

### ISSUE THREAD

**Issue by JCZuurmond** [dbt-labs/dbt-core#3828]
### Describe the feature
Use [exception chaining](https://www.python.org/dev/peps/pep-3134/#id37) to provide more detailed feedback about exceptions happening in adapters.

### Describe alternatives you've considered
As described in the [connection methods docs](https://docs.getdbt.com/docs/contributing/building-a-new-adapter/#connection-methods) you can use an `try-except` clause with `log` statements, but as explained in the linked [pep page](https://www.python.org/dev/peps/pep-3134/#id37) explicit exception chaining is added to Python to avoid needing to do that.

### Additional context
It helps adapters to provide more detailed feedback on failures using Pythonic language.

### Who will this benefit?
People using adapters. For example, the `odbc` adapter in `dbt-spark` can create difficulties. Now, the feedback is simply 'pip install pyodbc` whilst that does not always solve the underlying problem. I encountered this multiple times when helping people set-up dbt.

### Are you interested in contributing this feature?
Sure

**Comment by jtcohen6** [comment]
@JCZuurmond To clarify my understanding, the idea is that, when raising our own errors in each adapter's `connection.py`, the dbt adapter should be wrapping / passing along the exception from the underlying library/client—similar to the change you made over in in https://github.com/dbt-labs/dbt-spark/pull/192. Does that sound right?

If so, I'm all for it; this feels like it could only be a step forward to help users when debugging adapter-specific issues. I'd welcome a PR to make those changes in `dbt-postgres`, `dbt-redshift`, `dbt-snowflake`, and `dbt-bigquery`, as well as a PR to the [docs page](https://docs.getdbt.com/docs/contributing/building-a-new-adapter/#connection-methods) to provide updated guidance for community-maintainers adapters.

**Comment by JCZuurmond** [comment]
Yes, I would like to see the full traceback when an exception is caught. I think it is nothing more than logging the `e.traceback` when catching an exception, for example in the [`debug`](https://github.com/dbt-labs/dbt/blob/332d3494b3ce54d9a180f88d67a4773729daa736/core/dbt/task/debug.py#L361) command.

I do not know have time to work on this in the near future. If someone else wants to do this, then go ahead.

**Comment by JCZuurmond** [comment]
Here an example:

``` python
import logging

logger = logging.getLogger(__name__)


def calculate_fraction(denominator):
    try:
        fraction = 1 / denominator
    except ZeroDivisionError as e:
        raise ValueError("Denominator should be non zero.") from e
    return fraction


def main():
    denominator = 0

    try:
        fraction = calculate_fraction(denominator)
    except Exception as e:
        logger.exception(e)
        fraction = None

    return fraction


if __name__ == "__main__":
    print(main())
```

This prints 

``` 
Denominator should be non zero.
Traceback (most recent call last):
  File "/private/tmp/soda-spark-test/test.py", line 8, in calculate_fraction
    fraction = 1 / denominator
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/tmp/soda-spark-test/test.py", line 18, in main
    fraction = calculate_fraction(denominator)
  File "/private/tmp/soda-spark-test/test.py", line 10, in calculate_fraction
    raise ValueError("Denominator should be non zero.") from e
ValueError: Denominator should be non zero.
```

With the full traceback you can see where the original error happened. Now this is hidden and thus making debugging harder.
