### ISSUE TITLE
Wait for postgres docker container to be ready before running commands

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#3876]
### Describe the bug
When running `make setup-db` during setup, it needs to wait for the database to be running before running commands to get the postgres database in the right state.

### Steps To Reproduce
Run through the steps in [CONTRIBUTING](https://github.com/dbt-labs/dbt/blob/enhance/log-file-configs/CONTRIBUTING.md).  The first time you run `make setup-db` there will be an error that the server connection closed unexpectedly.  If you attempt to run `make integration` the tests will fail as dbtMixedCase database will not exist.  Run `make setup-db` again and everything will work and integration tests will run.

### Expected behavior
Be able to run `make setup-db` a single time and have everything work.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.21.0-b1
```

**The operating system you're using:**

**The output of `python --version`:**

### Additional context
Wait for `pg_isready` in setup_db.sh should fix this.

**Comment by jtcohen6** [comment]
@emmyoop Thanks for opening! Sounds like there's a straightforward fix here, so, I'm all about it :)
