### ISSUE TITLE
new jinja function: log var

### ISSUE THREAD

**Issue by swanderz** [dbt-labs/dbt-core#3911]
### Describe the feature

As I mention in https://github.com/bastienboutonnet/vscode-dbt/pull/14

> in Python 3.8+ I'm now very dependent on the f-string and walrus-operator related move:
> ```
> > foo = 'my string'
> > print(f'{foo=}')
> foo='my string'
> ```
> 
> I find myself doing be below in Jinja all the time and missing my Pythonic way of doing it. A snippet would is the lowest-hanging fruit, although I'd love a `log_var()` macro in dbt, someday!
> ```
> {{ log('drop_script: ' ~ drop_script, info=True) }}
> ```

### Describe alternatives you've considered

Making it available as a snippet for VSCode, Atom and/or dbtCloud?

### Who will this benefit?

anyone who spends a lot of time writing dbt-jinja.

### Are you interested in contributing this feature?

Yes! PR imminent...

**Comment by jtcohen6** [comment]
@swanderz I like it! Thanks for the PR, too :)

Agree that it's not worth the trouble of back-porting exact support to python 3.6 or 3.7 (the former reaches its end of life in December). We'll just need to make sure that we're not breaking any existing functionality for folks using dbt with those older versions of python.

**Comment by swanderz** [comment]
closing in favor of #4184
