### ISSUE TITLE
Add GHA for CI for database adapters

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3924]

**Comment by jtcohen6** [comment]
Could this be as simple as:
- Each plugin's CI installs the latest version of dbt-core (from `develop` branch in this repo)
- We schedule each plugin's CI to run once per night

Downside of this approach is, we wouldn't have a centralized report of failures in this repo—but we would get the notification from the plugin repositories, and we'd still have the uploaded artifacts

**Comment by jtcohen6** [comment]
This is 95% complete. We still need:
- notification on failures
- complete dbt-spark cutover to GHA

I'm going to close this issue in favor of new issues to tackle both of the above.
