### ISSUE TITLE
Update release process to account for plugins in different repositories

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3925]

**Comment by jtcohen6** [comment]
We may want adapter plugin release processes to exist somewhat independently of the dbt-core release process (as dbt-spark + dbt-presto do today). If we adjust adapter plugins to pin minor versions of dbt _only_, I don't think we'll need to cut an adapter release for every core release, or vice versa.

That said, we'll want the various adapters to use a similar release process, just as we want to ensure consistent testing rigor across all of them. An ideal version of the `dbt-release` repo/workflow would be able to release one or more codebases at a time, largely by leveraging the same code.

**Comment by jtcohen6** [comment]
We've settled on:
- [x] Each plugin manages its own version bump via GHA
- [ ] Each plugin will manage its own release via GHA. That workflow includes GitHub release, PyPi, Docker image uploaded to registry (probably GCR)
- [x] Homebrew formulae will be centrally managed via GHA in `homebrew-dbt` repo
- [ ] Central GHA that kicks off the others when we want to coordinate many releases (e.g. minor version RC + final)

I'm going to close this issue, for now, in favor of opening new better-scoped tickets for the work yet to be completed.
