### ISSUE TITLE
Adapter-specific installations

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#3968]
- Stop updating PyPi package `dbt` (i.e. `pip install dbt`)
    - Remove `setup.py` for package `dbt`
    - Ideally, start raising some kind of deprecation warning?
- Remove Homebrew formula + Docker image for `dbt`
- Add Homebrew formulae and Docker images for:
    - `dbt-core`
    - `dbt-postgres`
    - `dbt-redshift`
    - `dbt-snowflake`
    - `dbt-bigquery`
    - `dbt-spark`

**Comment by jtcohen6** [comment]
Update: `pip install dbt` _shouldn't_ just stay stuck on v0.21.0 forever. We need to decide what this should do starting with v1.0.0. I think we should raise some kind of error/warning encouraging folks to switch to `pip install dbt-<adapter>`. In addition to that warning/error, should we:
- Install all the same packages as before
- Install just `dbt-core` (likely to raise an `Adapter <name> not found!` error)
- Install nothing (an error in the truest sense)

**Comment by iknox-fa** [comment]
@jtcohen6 Whatever we do with `pip install dbt` should probably be reflected in `brew install dbt` as well yes?

**Comment by jtcohen6** [comment]
@iknox-fa Thanks for those links!

### pip

After spending some more time with this, I'm leaning toward _deprecating_ rather than _disabling_. I don't think we gain a lot by bricking production pipelines that depend on (unpinned) `pip install dbt`, on the day that we release v1.0. However, we should include a warning message (during install) to the effect of:
```
"pip install dbt" is deprecated, and will stop supporting new versions on [date].
Please install your specific database adapter as `pip install dbt-<adapter> instead.
Link to docs: ...
```

Then, a few months/versions later, we should feel comfortable _disabling_ the `dbt` package by raising an error. What do you think?

### homebrew

Homebrew feels like a different beast. I don't _think_ anyone's production pipelines should depend on `brew install dbt` (weird if they did!), but certainly many users have already tapped `dbt-labs/dbt` and installed the `dbt` formula. I don't have an amazing understanding of the way Homebrew works, but I'm imagining existing users could do something like:
```bash
brew unlink dbt
brew link dbt-bigquery
```
And new users could do:
```bash
brew tap dbt-labs/dbt # rename to dbt-core?
brew install dbt-bigquery
# win: no need to install snowflake dependencies
```

That said, there is definitely a small-but-mighty set of users (our colleagues!) who will want to install and use multiple plugins in the same environment. It would be a shame if they had to run `brew unlink ... && brew link ...` every time they wanted to switch between `dbt-snowflake` and `dbt-bigquery`. Is it possible to install multiple formulae that share the same symlink? Or enable each plugin as an "extra" in the same main formula?

If we need to, we can punt on Homebrew for the time being, and just rename the `dbt` formula to `dbt-core`. That kind of renaming appears straightforward and commonly done.

**Comment by iknox-fa** [comment]
Sounds good to me @jtcohen6.  I'm not sure about homebrew either, but I'll do some experimenting and see what I can sort out.

**Comment by iknox-fa** [comment]
@jerco -- It appears that GH actions does not support macos build instances with an os version < 10.15.  This means dropping brew support for High-sierra and Mojave.  Are you good with that?

**Comment by jtcohen6** [comment]
@iknox-fa That's fine by me; Catalina (10.15) came out >2 years ago. I'm okay deferring to GHA on which MacOS versions we can reasonably support, for now. Homebrew isn't something that folks depend on in production, it's really a quality-of-life improvement to ease installation for Mac users brand new to local development.

**Comment by iknox-fa** [comment]
There's been further confusion in slack vis-a-vis the actual `pip install` commands.  @jtcohen6 can you confirm that this is the desired outcome matrix?

## Pip (pre-1.0 state)
| Install method    | codebases used                           | Databases supported     |
|-------------------|------------------------------------------|-------------------------|
| `pip install dbt` | dbt<sup>2</sup> repo + all adapter repos | Postgres + all adapters |
## Pip (1.0 + state)
| Install method                               | codebases used                   | Databases supported |
|----------------------------------------------|----------------------------------|---------------------|
| `pip install dbt-core`                       | dbt-core<sup>3</sup> repo        | Postgres            |
| `pip install dbt-<adapter-name>`<sup>1</sup> | dbt-core repo<sup>3</sup> + one adapter repo | Postgres + `<adapter>`|
| `pip install dbt-postgres`<sup>2</sup>                   | dbt-core repo<sup>3</sup>                    | Postgres            |
| `pip install dbt`<sup>2</sup>                            | dbt-core<sup>3</sup> repo        | Postgres            |

1: One of `spark`, `bigquery`, `redshift`, or `snowflake`.
2: Not officially blessed installation method, prefer `pip install dbt-core`.
3: `dbt-core` and `dbt` refer to the same repo, it was re-named and the new name used where appropriate.

**Comment by jtcohen6** [comment]
@iknox-fa Amazing Markdown, thanks for the work laying this out in detail :)

To make a long story short: _everything PyPi-related should work the exactly the same as it does today_. Yes, we're renaming the repo to `dbt-core`, and we moved Redshift/Snowflake/BigQuery into separate repos, but we're not changing their PyPi packaging _at all_.

The big question is, what to do with the PyPi package named `dbt`, defined [here](https://github.com/dbt-labs/dbt/blob/develop/setup.py). Note that this is _just_ a cosmetic consideration—it shouldn't change _anything_ about how we're packaging/distributing the underlying components—we just know that a lot of people are still using `pip install dbt`. Starting in v1, this could:
- Raise a deprecation warning, then nstall `dbt-core`, `dbt-postgres`, `dbt-redshift`, `dbt-bigquery` (backwards compatible). This might be tricky if we've released a newer patch/prerelease of `dbt-core` than 
- Warn, then install `dbt-core` + `dbt-postgres` (the equivalent of installing `-r editable-requirements.txt` in the `dbt-core` repo, i.e. for local development/testing; knowing that _most_ people will encounter errors and have to switch)
- Warn, then install `dbt-core` _only_ (knowing that people _will definitely_ encounter errors)
- If all of that is too tricky to figure out, we should keep it simple and just raise a good old fashioned error message when someone tries `pip install dbt --pre` or `pip install dbt==1.0.0b1`: "Going forward, you must install dbt-<specific-adapter-name>`.

## Pip (pre-1.0 state)
| Install method       | GitHub repo used                           | Databases supported     |
|-------------------|------------------------------------------|-------------------------|
| `pip install dbt-core` | `dbt` repo<sup>1</sup> (`core/`) | none! just the core library |
| `pip install dbt-<adapter-name>` | `dbt` repo<sup>1</sup>, external `<adapter>`<sup>2</sup>? | any `<adapter>` db |
| `pip install dbt-postgres`  | `dbt` repo <sup>1</sup> (`plugins/postgres`) | Postgres (like above)            |
| `pip install dbt` | `dbt` repo<sup>1</sup> (`core/` + `plugins/`) | Postgres, Redshift, Snowflake, BigQuery |

## Pip (1.0 + state)
| Install method                               | GitHub repo used                   | Databases supported |
|----------------------------------------------|----------------------------------|---------------------|
| `pip install dbt-core`                       | `dbt-core` repo (`core/`)  | none! just the core library            |
| `pip install dbt-<adapter-name>` | `dbt-core` repo + any one `<adapter>` repo | any `<adapter>` db |
| `pip install dbt-postgres`3  | `dbt-core` repo (`plugins/postgres`)     | Postgres (like above)            |
| `pip install dbt`<sup>4</sup>   | `dbt-core`+ ???        | ???            |

1: `dbt-core` and `dbt` refer to the same repo, it was re-named and the new name used where appropriate.
2: `spark`, `bigquery`, `redshift`, `snowflake`... but also `sqlserver`, `athena`, `trino`, etc.
3: This is good/preferred! It's exactly like `pip install dbt-<adapter-name>`. Postgres is _only_ a special case in that its plugin code will continue living in the `dbt-core` repo (`plugins/postgres`), rather than a separate repo.
4: Will display deprecation warning. Prefer `pip install dbt-<adapter-name>`.

**Comment by jtcohen6** [comment]
Update:
- We've resolved the Homebrew question: formulae will be centralized in `homebrew-dbt`. There's more work to do there, but we feel 80% good about the progress so far.
- Moved the `pip install dbt` conversation over to #4100
- Docker images will be built from wheels, and we're leaning toward GHCR as the registry to host them

I'm going to close this issue for now. Let's pick up on the unfinished threads after we've cut v1.0.0-rc1.
