### ISSUE TITLE
Further Simplify Flags

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#3973]
### Describe the feature
When adding a new flag, there are many places you must put the name of your flag in a very boiler platey fashion. Since adding and removing new flags is a very common user interface change that we want to get right, I would like to slightly rearrange the flow of flags so that you define the information once, and the rest of the code references that definition to set all the appropriate factors.

### Describe alternatives you've considered
We could also just not do this, because the boiler plate isn't really that bad.

### Additional context
You have to remember to put in all the argparse-specific parameters, defaults, and global values which are all defined in different places.

[PR#3839](https://github.com/dbt-labs/dbt/pull/3839) made huge improvements to the flag system already.

### Who will this benefit?
dbt contributors and developers.

**Comment by gshank** [comment]
I suspect that we're going to see some changes in flag handling with the new server work. Not sure where we'll end up on that, so we might wait until we see the requirements there to address this.
