### ISSUE TITLE
Visualize the model graph without the docs site

### ISSUE THREAD

**Issue by jsnb-devoted** [dbt-labs/dbt-core#4009]
### Describe the feature
I would love a way to visualize my dbt graph without launching the docs site.

### Describe alternatives you've considered
The docs site is excellent but sometimes I just want to see a quick graph of my model dependencies without spinning up the web app.

### Additional context
I worked on a home grown tool that had a command similar to `dbt ls` but you could pass a flag that would use `graphviz` to draw the graph.

### Who will this benefit?
Anyone developing models and wants a quick look at their graph dependencies

### Are you interested in contributing this feature?
I'm interested in contributing. My company uses dbt extensively and I think they could find this useful. Last I checked `dbt` was using `networkx` and it does have methods for drawing the graphs so it feels doable.

**Comment by pablomarambio** [comment]
is there any such tool yet @jsnb-devoted ?

**Comment by jsnb-devoted** [comment]
We made one for internal use but I just stumbled upon an open source tool that looks like it does this:
https://github.com/nicholasyager/hotdag
@pablomarambio

**Comment by htpaf** [comment]
@jsnb-devoted 
I tried hotdag v 0.7.2 but got 
`.pyenv/versions/3.9.18/envs/sfdbtsearch/lib/python3.9/site-packages/hotdag/__init__.py", line 36, in _load_graph
    compiler.link_graph(linker=linker, manifest=self.manifest)
AttributeError: 'Compiler' object has no attribute 'link_graph'
`


I tried using the https://docs.getdbt.com/reference/artifacts/other-artifacts#graphgpickle with networkx but the results are poor. If anyone knows how the dbt-core code (or if it is done somewhere else) creates the graph, I would like to know which APIs or code parts I should be looking at so I can try and extract the relevant parts.
