### ISSUE TITLE
Return to eager test selection by default, with an option to tone it down

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4082]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

- dbt 0.20.0 changed how tests were selected, to avoid errors in more complex dbt projects that don't build the entire project during development/CI.
    - Specifically: In a fresh schema, operators like `@` and `+` can cause models to be tested that don't exist ([1827](https://github.com/dbt-labs/dbt-core/issues/1827), [2132](https://github.com/dbt-labs/dbt-core/issues/2132)). Singular tests that touch a model are run even if they are only indirectly selected ([3832](https://github.com/dbt-labs/dbt-core/issues/3382))
    - The change was to only run tests if *all* first-order parents are included in selection ([2891](https://github.com/dbt-labs/dbt-core/issues/2891)). The writeup in the PR ([3235](https://github.com/dbt-labs/dbt-core/pull/3235)) is very good so I won't re-summarise it.
- As an unfortunate side effect, it broke people's mental model (it used to do what you *meant*; now it does what you asked)
- I was originally writing an article explaining why the changes are important and helping dbt users understand when they should use the new-in-0.21.0 `--greedy` flag. As I dug into the edge cases, my thinking changed and **I now think we should restore the 0.19.0 behaviour as the default**, with an option to disable greedy selection for the use cases that necessitated the changes in the first place. 

Matrix of functionality/options:
![image](https://user-images.githubusercontent.com/7335046/137647147-bb427102-2c94-4317-84f1-5ecc058a8ad7.png)

### Describe alternatives you've considered

- Make the new behaviour much more discoverable.
    - I think [if the DAG in dbt Docs also visualised tests](https://getdbt.slack.com/archives/C2JRTGLLS/p1633962686096200), then we could more reasonably expect users to preview their selections there (I used to use it as a visual debugger of complex selection syntax)
    - Document the crap out of it, particularly in the tutorial.
    
- Change nothing: there's a risk of creating *more* confusion by flipping back to the old way and annoying the people who liked it
    - If we're going to change, we should really do it before 1.0 or we're stuck.
    - There's already significant confusion in the community, for both new and longstanding members. [3496](https://github.com/dbt-labs/dbt/issues/3496), [3571](https://github.com/dbt-labs/dbt/issues/3571), [3706](https://github.com/dbt-labs/dbt/issues/3706), [3903](https://github.com/dbt-labs/dbt/issues/3903), [Slack 1](https://getdbt.slack.com/archives/C01UM2N7814/p1633623002202700) (9mths in community), [Slack 2](https://getdbt.slack.com/archives/C01UM2N7814/p1632336696127500) (2yrs in community), [Slack 3](https://getdbt.slack.com/archives/C01UM2N7814/p1633425377185100) (5mths in community), [Slack 4](https://getdbt.slack.com/archives/C2JRRQDTL/p1626271497173000) (18mths in community), [Slack 5](https://getdbt.slack.com/archives/C01UM2N7814/p1630508257048800) (new to community), [Slack 6](https://getdbt.slack.com/archives/CBSQTAPLG/p1630096188152800) (1mth in community)
- Try harder to internalise the new system.
    - I don't think it's better to expect this of new users: the old failure modes were real, but they tended to impact advanced dbt users (the green users). 
    ![image](https://user-images.githubusercontent.com/7335046/137646785-6bdfcc5d-64b9-4dc6-9345-f6f1a1180a4e.png)
    _NB: Venn diagram is entirely unscientific_
    - The new failure mode catches people immediately (the yellow users), especially since the [Tutorial](https://docs.getdbt.com/tutorial/test-and-document-your-project) currently says "Running tests on one model looks very similar to running a model: use the `--select` flag (or `-s` flag), followed by the name of the model"

### Who will this benefit?

- People whose mental model has been broken by the changes
    - Specifically, who expect to be able to switch between `dbt run -m some_model` and `dbt test -m some_model` and have all tests attached to `some_model` run.
    - The union of `dbt test --exclude tag:x` and `dbt test --select tag:x` is no longer the same as `dbt test` when one model in a test is tagged `x` and one isn't.
    - Side note: [docs#514](https://github.com/dbt-labs/docs.getdbt.com/issues/514) correctly calls for endless examples of node selection. We should do this, no matter what the outcome here!
- A lot of the takeaway from my original post was going to be "the good thing is that there's now a flag to allow you to choose the right approach for your use case". That remains true even if we flip the default back.
- I wanted to be able to provide a clear set of guidelines covering when you should use `--greedy` and not. All of the cases devolved towards "yes, but..." or "it depends". If the settings were flipped,  I think a lot of the guidance becomes easier because we can describe the handful of cases where it becomes desirable with less ambiguity: "Exclude the other parents when they won't exist"

### Are you interested in contributing this feature?

Sure am! @VersusFacit and I are going to tag-team it

**Comment by jtcohen6** [comment]
I'm on board!

Your second proposal tickles me. The naming and string type is a bit against convention, but the thing we're asking people to do here is more complex than a standard on/off global config. It feels more like "dbt language," wherein we speak about ephemeral materializations, high-maturity exposures, etc.
