### ISSUE TITLE
[CT-121] Turn Mypy on Everywhere

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#4089]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Right now, Mypy is not on everywhere and it is not a particularly high level of scrutiny. This has let some bugs slip through to users that could have been caught in devlopment. I would like to turn mypy on everywhere with `--strict` and maybe a few other settings. The places where it would be non-trivial to switch over we should manually disable mypy for, but this way all new files will be held to this new higher standard of Python.

### Describe alternatives you've considered

Not doing this. Strict Mypy is a subset of Python, which isn't as smooth of a development experience especially for experienced Python devs who are not used to Mypy.

### Who will this benefit?

Developers and users because some classes of bugs will not be able to make it into releases.

### Anything else?

related: #3203

**Comment by iknox-fa** [comment]
@nathaniel-may Just to clarify-- This ticket is just to make mypy runnable on the entire codebase with `--strict`.  It does not cover fixing all the the issues it surfaces.

**Comment by nathaniel-may** [comment]
It does cover at least addressing all the failures. If we don't, CI will fail when it runs mypy with the new configuration. In this ticket we can at a minimum add type ignores to them, and clean up those ignores in a separate ticket.

**Comment by leahwicz** [comment]
@iknox-fa @nathaniel-may where do we fall on this after the recent #5171 PR? We have:
* mypy running on the entire Core codebase except for Postgres (conscious decision - going to pull out Postgres into it's own repo)
* we don't have the strict flag on - correct?

**Comment by nathaniel-may** [comment]
closing in favor of #5225
