### ISSUE TITLE
Test Result Output to Single Table in Snowflake (via Variant Column)

### ISSUE THREAD

**Issue by brittianwarner** [dbt-labs/dbt-core#4099]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I would like to save all test output to a single table in Snowflake instead of a single table per test.  We can leverage the variant column type in order to do this and add other metadata as columns in the table. 

### Describe alternatives you've considered

Na

### Who will this benefit?

Anyone using Snowflake and wants to report on dbt tests for quality initiatives.  

### Anything else?

I believe this is a huge enhancement for anyone leveraging Snowflake and other warehouses that support variant/json type columns.  This provides the ability to save a full history of tests and be able to report on test/quality data.

**Comment by brittianwarner** [comment]
Update: This was a huge help!  I managed to work out a flow where I consolidate all of the data into a single table. Meant to reply sooner but better late than never! For anyone interested, I used the code @jtcohen6  shared and added my own flavor for our use case(cleanup and other metadata):

`{% macro centralize_test_failures(results) %}

  {%- set test_results = [] -%}
  {%- for result in results -%}
    {%- if result.node.resource_type == 'test' and result.status != 'skipped' and (
          result.node.config.get('store_failures') or flags.STORE_FAILURES
      )
    -%}
      {%- do test_results.append(result) -%}
    {%- endif -%}
  {%- endfor -%}
  
  {%- set central_tbl -%} {{ target.schema }}.test_failures {%- endset -%}
  
  {{ log("Centralizing test failures in " + central_tbl, info = true) if execute }}

  {%- if test_results | length > 0 -%}

    {% set query %}
  
   create or replace table {{ target.schema }}."{{ macro_to_create_a_unique_id() + '_' + central_tbl }}" as (
  

  {% for result in test_results %}
  
    select
        metadata1                                            as metadata1,
        metadata1                                             as metadata2,
        metadata(n)                                          as metadata(n),
        '{{ result.node.name }}'                        as test_name,
        '{{ result.node.unique_id }}'                 as model,
        object_construct_keep_null(*)            as row_data,
        current_timestamp                               as _timestamp
    from {{ result.node.relation_name }}
    
    {{ "union all" if not loop.last }}
  
  {% endfor %}
   );

    {% for result in test_results %}
        drop table if exists {{ target.schema }}."{{ macro_to_create_a_unique_id() + '_' + result.node.name |  trim }}";
    {% endfor %}
    
{% endset %}



{% set final_query %}

 insert into {{ central_tbl }}
 select * from {{ target.schema }}."{{ macro_to_create_a_unique_id() + '_' + central_tbl }}";
 drop table if exists {{ target.schema }}."{{ macro_to_create_a_unique_id() + '_' + central_tbl }}";
{% endset %}


{% do run_query(query) %}
{% do run_query(final_query) %}
{%- endif -%}
{% endmacro %}`

**Comment by codigo-ergo-sum** [comment]
I posted a version of this code for BigQuery along with some comments/thoughts in this ticket: https://github.com/dbt-labs/dbt-core/issues/4613

**Comment by Mira-Yassine** [comment]
Hello, Thank you very much for your solution. I'm writing some generic test in dbt and I want to store the failure in one table as you did. I'm using sqlserver and I got syntax error as : 


`  ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '('. (102) (SQLExecDirectW)") `

I removed the replace from your code since the sqlserver does not support it (I tried by the way truncate or alter)
If you can give me a version supported by sqlserver I'll be more than thankful. 
Thank you


`  create table {{ central_tbl }} as (
  
  {% for result in test_results %}
  
    select
      '{{ result.node.name }}' as test_name,
      object_construct_keep_null(*) as test_failures_json
      
    from {{ result.node.relation_name }}
    
    {{ "union all" if not loop.last }}
  
  {% endfor %}`

**Comment by codigo-ergo-sum** [comment]
@Mira-Yassine - we're all just dbt users mocking up code here so you might have to experiment to try to figure out what works on SQL Server :). `object_construct_keep_null` is a Snowflake function to aggregate a bunch of key-value pairs into one `OBJECT` datatype. https://docs.snowflake.com/en/sql-reference/functions/object_construct_keep_null.html

You'll need to find what the equivalent datatype would be in SQL Server and find the functions to work with it. `JSON` is the close-enough equivalent datatype in BigQuery, for example (see here: https://github.com/dbt-labs/dbt-core/issues/4613).

**Comment by Mira-Yassine** [comment]
@codigo-ergo-sum - Hello, Thank you very much for your hint. That's help me already to know that 'object_construct_keep_null' is a Snowflake function. I'll try to figure out how can I store the test data into one table in my SQL Server.

**Comment by ivanpetrusev** [comment]
Good afternoon. Thanks everyone for the helpful discussion.
Could you tell me what the error could be related to - **AttributeError: 'str' object has no attribute '_message'.**

In dbt_project.yml I write:
`on-run-end: "{{ centralize_test_failures(results) }}".`

Macro -
```
{% macro centralize_test_failures(results) %}

  {%- set test_results = [] -%}
  {%- for result in results -%}
    {%- if result.node.resource_type == 'test' and result.status != 'skipped' and (
          result.node.config.get('store_failures') or flags.STORE_FAILURES
      )
    -%}
      {%- do test_results.append(result) -%}
    {%- endif -%}
  {%- endfor -%}
  
  {%- set central_tbl -%} table_scheme.tests_result {%- endset -%}
  
--  {{ log("Centralizing test failures in " + central_tbl, info = true) if execute }}

  CREATE OR REPLACE TABLE {{ central_tbl }} ENGINE = MergeTree()
  ORDER BY model_name
  AS (
    {%- for result in test_results %}
    SELECT
      today() as test_date,
      multiIf(
        '{{ result.node.name }}' LIKE 'unique%', 'unique',
        '{{ result.node.name }}' LIKE 'accepted_values%', 'accepted_values',
        '{{ result.node.name }}' LIKE 'not_null%', 'not_null',
        '{{ result.node.name }}' LIKE 'relationships%', 'relationships',
        '{{ result.node.name }}' LIKE 'source_accepted_values%', 'source_accepted_values',
        '{{ result.node.name }}' LIKE 'source_not_null%', 'source_not_null',
        '{{ result.node.name }}' LIKE 'source_relationships%', 'source_relationships',
        '{{ result.node.name }}' LIKE 'source_unique%', 'source_unique',
        '{{ result.node.name }}' LIKE 'dbt_expectations%', 'dbt_expectations',
        'unknown_test'
    ) AS test_name,
      name AS model_name,
      replaceRegexpOne(substring('{{ result.node.name }}', (LENGTH (name) + LENGTH (test_name)+3)), '(__\\d+)+$', '') as column_name,
      toJSONString(tuple(base.*)) AS test_failures_meta
    FROM {{ result.node.relation_name }} AS base
    CROSS JOIN 
      (SELECT name
      FROM system.tables
      WHERE database = 'dev_env_datamart') AS models
    WHERE position('{{ result.node.name }}', name) != 0
    ORDER BY column_name, test_name
    {{ "UNION ALL" if not loop.last }}
    {%- endfor %}
  );

{% endmacro %}
```

**Thanks for any advice!**

**Comment by mariq41** [comment]
> macro_to_create_a_unique_id

Could you share the code for macro_to_create_a_unique_id?

**Comment by mariq41** [comment]
> Update: This was a huge help! I managed to work out a flow where I consolidated all of the data into a single table. Meant to reply sooner but better late than never! For anyone interested, I used the code @jtcohen6 shared and added my own flavor for our use case(cleanup and other metadata):
> 
> ```
> {% macro centralize_test_failures(results) %}
> 
>   {%- set test_results = [] -%}
>   {%- for result in results -%}
>     {%- if result.node.resource_type == 'test' and result.status != 'skipped' and (
>           result.node.config.get('store_failures') or flags.STORE_FAILURES
>       )
>     -%}
>       {%- do test_results.append(result) -%}
>     {%- endif -%}
>   {%- endfor -%}
>   
>   {%- set central_tbl -%} {{ target.schema }}.test_failures {%- endset -%}
>   
>   {{ log("Centralizing test failures in " + central_tbl, info = true) if execute }}
> 
>   {%- if test_results | length > 0 -%}
> 
>     {% set query %}
>   
>    create or replace table {{ target.schema }}."{{ macro_to_create_a_unique_id() + '_' + central_tbl }}" as (
>   
> 
>   {% for result in test_results %}
>   
>     select
>         metadata1                                            as metadata1,
>         metadata2                                             as metadata2,
>         metadata(n)                                          as metadata(n),
>         '{{ result.node.name }}'                        as test_name,
>         '{{ result.node.unique_id }}'                 as model,
>         object_construct_keep_null(*)            as row_data,
>         current_timestamp                               as _timestamp
>     from {{ result.node.relation_name }}
>     
>     {{ "union all" if not loop.last }}
>   
>   {% endfor %}
>    );
> 
>     {% for result in test_results %}
>         drop table if exists {{ target.schema }}."{{ macro_to_create_a_unique_id() + '_' + result.node.name |  trim }}";
>     {% endfor %}
>     
> {% endset %}
> 
> 
> 
> {% set final_query %}
> 
>  insert into {{ central_tbl }}
>  select * from {{ target.schema }}."{{ macro_to_create_a_unique_id() + '_' + central_tbl }}";
>  drop table if exists {{ target.schema }}."{{ macro_to_create_a_unique_id() + '_' + central_tbl }}";
> {% endset %}
> 
> 
> {% do run_query(query) %}
> {% do run_query(final_query) %}
> {%- endif -%}
> {% endmacro %}
> ```

Hi, @brittianwarner , could you share your macro_to_create_a_unique_id() as well?
