### ISSUE TITLE
[Feature] dbt snapshot --defer

### ISSUE THREAD

**Issue by iljau** [dbt-labs/dbt-core#4110]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Implement "dbt snapshot --defer", which would behave similar to "dbt run --defer".

### Who will this benefit?

When trying to set up "slim ci", one step in my case would be to run snapshots based on other dbt models.

`dbt snapshot --select 'dbt.*,state:modified' --state manifests/staging`

When running this command, generated references point to current schema, which doesn't have these tables, as they weren't generated during preceding run command:
`dbt run --models state:modified --defer --state manifests/airflow/staging`

### Anything else?

https://docs.getdbt.com/reference/node-selection/defer
https://docs.getdbt.com/docs/guides/best-practices#run-only-modified-models-to-test-changes-slim-ci

dbt version:  0.20.1

**Comment by jtcohen6** [comment]
@iljau Thanks for opening!

The steps here are quite straightforward. I'm going to mark this a `good first issue`, and I'd welcome a PR from a community member.

1. Include snapshot in the subcommands that get the `--defer` flag:
https://github.com/dbt-labs/dbt-core/blob/f79a968a0908add9de1b6acfdb75a6b205134ebd/core/dbt/main.py#L1091-L1092

2. Remove `defer_to_manifest` override in `SnapshotTask`, so as to inherit the implementation from `RunTask`:
https://github.com/dbt-labs/dbt-core/blob/f79a968a0908add9de1b6acfdb75a6b205134ebd/core/dbt/task/snapshot.py#L25-L27

3. Then, we'd want to add/adjust a test case combining snapshots + deferral:
https://github.com/dbt-labs/dbt-core/blob/f79a968a0908add9de1b6acfdb75a6b205134ebd/test/integration/062_defer_state_test/test_defer_state.py#L154-L161

Is this a change you'd be interested in contributing?

### one step further

At this point, there's no good reason not to support `--defer` for `compile`, too, and thereby `docs generate` as well (https://github.com/dbt-labs/dbt-core/issues/3741). (The only reason I can come up with: we might eventually want to rename/rework the UX of deferral (#2968)).

For that support:
- Add the `--defer` flag to the `compile` and `docs` subparsers, too
- Move `defer_to_manifest` up from `RunTask` into [`CompileTask`](https://github.com/dbt-labs/dbt-core/blob/f79a968a0908add9de1b6acfdb75a6b205134ebd/core/dbt/task/compile.py#L36) (its parent)

### alternative

The `build` task, new in v0.21, supports both snapshots and deferral:
```
$ dbt build --resource-type snapshot --defer --state manifests/airflow/staging`
```

So, that's something you can use in the meantime.

**Comment by kadero** [comment]
Hello @jtcohen6 @iljau  :wave:,

Thank you for opening this issue and to provide a solution :slightly_smiling_face:.
Happy to work on this feature and to raise a PR for it. Ok for you?

:pray:

**Comment by iljau** [comment]
I switched to using `dbt build` and don't have immediate plans to work on a fix.

**Comment by ciejer** [comment]
Hi @jtcohen6 - just checking in.
Is there another issue you're aware of that covers your "one step further" note from above? We're missing deferral in catalog generation (dbt docs generate); followed the link here from #3741 but the PR for this does not appear to close that issue.

**Comment by yajozwamajoz** [comment]
..|Hian’s Weblogs � Blog Archive � SiteBar|go.php?i|| ..|Как хранить интернет-закладки в сети?..|Bookmarks im Web - Home of Geewiz|go.php?||https://my.sitebar.org/favicon.ph-un-en

My  punishment where coming arrived to All Geewis. 

Scam, Houxes, Froud, Urban Legend, Acronyms, Emoticons, The Secret Weapon, of all Geewis,. Search Quran Al Kareem., the Last Real Biible, never change forever.,
