### ISSUE TITLE
[Bug] Calling a macro in a disabled model causes RuntimeError

### ISSUE THREAD

**Issue by RobMcZag** [dbt-labs/dbt-core#4126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I now have the test
```
{% test no_hash_collisions( model, column_name, base_fields ) -%}
```
and I call it in a model -in the test folder- like below
```
{{
  test_no_hash_collisions( 
                      model  = ref('GROUP_CUSTOMER')
                     , column_name  = 'CUSTOMER_HDIFF'
                     , base_fields = 'CUSTOMER_CODE, CUSTOMER_NAME'
  )
}}
```

Then I get
```
Server error: Runtime Error
got an update_rpc call with an unrecognized rpc: rpc.fds_dw.request
```

### Expected Behavior

As the model is disabled I suppose an erro should not be thrown (and possibly the macro should not even be called).

At the very least, the error should be more explicative.

### Steps To Reproduce

1. Create the following macro
```
{% test no_hash_collisions( model, column_name, base_fields ) -%}

WITH
all_tuples as (
    SELECT distinct {{column_name}} as HASH_FIELD, {{base_fields}}
    FROM {{ model }}
),

validation_errors as (
    SELECT HASH_FIELD, count(*)
    FROM all_tuples
    GROUP BY HASH_FIELD
    HAVING count(*) > 1
)

SELECT * FROM validation_errors

{%- endtest %}
```
2. create a test model (in the test folder) and call the macro as below (with some existing ref and column names)
```
{{ config(enabled=false) }}
{{
  test_no_hash_collisions( 
                      model  = ref('GROUP_CUSTOMER')
                     , column_name  = 'CUSTOMER_HDIFF'
                     , base_fields = 'CUSTOMER_CODE, CUSTOMER_NAME'
  )
}}
```
3. run the project (or just the disabled one) to see the error

### Environment

```markdown
- dbt: dbt cloud 0.20.0
```

### What database are you using dbt with?

snowflake

### Additional Context

Enabling the test, i.e. removing `{{ config(enabled=false) }}`, removes the error.

**Comment by jtcohen6** [comment]
Going to close in favor of https://github.com/dbt-labs/dbt-rpc/issues/79, which is the same issue in the right repo to make an improvement in the error message
