### ISSUE TITLE
[Bug] Deprecated unittest aliases were removed in Python 3.11

### ISSUE THREAD

**Issue by tirkarthi** [dbt-labs/dbt-core#4132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
dbt/test/integration/027_cycle_test/test_cycles.py:        with self.assertRaisesRegexp(Exception, message):
dbt/test/integration/027_cycle_test/test_cycles.py:        with self.assertRaisesRegexp(Exception, message):
```

assertRaisesRegexp was removed in Python 3.11 in PR python/cpython#28268

### Expected Behavior

assertRaisesRegex is the recommended equivalent.

### Steps To Reproduce

Python 3.11 will throw an error for the tests

### Environment

```markdown
- OS:Ubuntu
- Python:3.11
- dbt:
```

### What database are you using dbt with?

other (mention it in "Additional Context")

**Comment by jtcohen6** [comment]
Resolved by #4136
