### ISSUE TITLE
[Feature] dbt init with target directory

### ISSUE THREAD

**Issue by tekumara** [dbt-labs/dbt-core#4141]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

```
dbt init --dir .
```
would create the scaffolding in the current directory.

### Who will this benefit?

Users with projects that have a _.venv/_ directory for their virtual environment

### Are you interested in contributing this feature?

Yes

### Anything else?

My current workflow for installing dbt into a virtualenv:
```
mkdir jaffle-shop
cd jaffle-shop
virtualenv .venv
. .venv/bin/activate
pip install dbt
```

Now if I run `dbt init jaffle-shop` I end up with a extra directory level:

```
jaffle-shop
└── jaffle-shop
    ├── README.md
    ├── analysis
    ├── data
    ├── dbt_project.yml
    ├── macros
    ├── models
    │   └── example
    │       ├── my_first_dbt_model.sql
    │       ├── my_second_dbt_model.sql
    │       └── schema.yml
    ├── snapshots
    └── tests
```

The proposed solution would address this.

**Comment by jtcohen6** [comment]
@tekumara Thanks for opening! We've just finished making a bunch of improvements to `dbt init` in the lead-up to v1. It's now interactive and better than ever :)

The sequence of your workflow makes sense: you want to create your project directory, then activate a virtualenv, then install dbt, then initialize a project. If you're already willing to have a sequence of CLI setup steps, my sense is that it would only take two additional ones to achieve your desired behavior:
```bash
mkdir jaffle-shop
cd jaffle-shop
virtualenv .venv
. .venv/bin/activate
pip install dbt
dbt init jaffle-shop --skip-profile-setup  # new flag in v1
mv jaffle-shop/*   # move project scaffolding into current directory
rm -r jaffle-shop  # delete now-empty subdirectory
```

From my point of view, it feels like you've already got the tools at your disposal to make this work exactly the way you want! As such, I'm going to close this issue.

**Comment by tekumara** [comment]
Thanks @jtcohen6 yes that's how I resolved it, but i was hoping this could be integrated into `dbt init`
