### ISSUE TITLE
When on_schema_change is set, pass common columns as dest_columns in incremental merge macros

### ISSUE THREAD

**Issue by ccharlesgb** [dbt-labs/dbt-core#4144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have noticed that when removing a column from an incremental model that uses `insert_overwrite` and BigQuery that this causes dbt to fail.

### Expected Behavior

We had initially assumed this was intended behaviour on dbt's part because of how schema changes with incremental were not supported until 0.21 however after reading [the documentation](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#default-behavior). We thought maybe this was not intentional and that the missing column should just be ignored.

### Steps To Reproduce

1. Create an incremental model with 3 columns:

```
{{
  config(
    alias = 'incr_test',
    materialized = 'incremental',
    incremental_strategy = 'insert_overwrite',
    partition_by={'field': 'event_time', 'data_type': 'date'}
  )
}}

SELECT
  *
from (SELECT DATE('2021-01-01') as `event_time`,
      'a' as `col_a`,
      'b' as `col_b`)
```

2. Run the model against a BigQuery instance and then remove `col_b`:
```
SELECT
  *
from (SELECT DATE('2021-01-01') as `event_time`,
      'a' as `col_a`)
```
3. Run the model again and you will see this error:
```
Completed with 1 error and 0 warnings:

Database Error in model incr_test (incr_test.sql)
  Query error: Unrecognized name: col_b; Did you mean col_a? at [57:33]
  compiled SQL at target/run/auto_trader/models/incr_test.sql

```

### Relevant log output

```shell
Completed with 1 error and 0 warnings:

Database Error in model incr_test (incr_test.sql)
  Query error: Unrecognized name: col_b; Did you mean col_a? at [57:33]
  compiled SQL at target/run/auto_trader/models/incr_test.sql

```
```


### Environment

```markdown
- OS: Mac OS
- Python: 3.8
- dbt: 0.20.1
```

### What database are you using dbt with?

bigquery

**Comment by Kayrnt** [comment]
@jtcohen6 all tests added and PRs are green ✅

**Comment by Kayrnt** [comment]
Happy to have that issue solved!
Thank you @jtcohen6 for moving forward quickly 💪 
I'm looking forward for the next release 🙌
