### ISSUE TITLE
[Bug] Need more helpful error message when persist_docs encounters invalid column names

### ISSUE THREAD

**Issue by ljhopkins2** [dbt-labs/dbt-core#4151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For a given model, if the YML documentation contains a column name not found in the model and `persist_docs` is enabled, the build fails with the following error:

```
Database Error in model my_model (path/to/my_model.sql)
  column "<col_name>" of relation "my_model" does not exist
  compiled SQL at target/run/path/to/my_model.sql
```

This message misleads the user to look in the SQL file to resolve the issue, even though that's not where the error lies. (Assuming we take the _model_ to be canonical and the _documentation_ to be derivative: presumably, most people wait to document until after building, although, like me, they might \*cough\* fail to remember to update their docs after later changing the model.)

### Expected Behavior

It would be more helpful to direct the user to the YML file, where the problem actually exists, and to explicitly say that the error occurred during the persist docs step. Along the lines of

```
Error persisting docs for model my_model
  column "<col_name>" defined in path/to/my_model_docs.yml 
  does not exist in path/to/my_model.sql
```

### Steps To Reproduce

Put the following model and its docs file in a project, and run the model.
```sql
{{ config(
    materialized = 'table',
    persist_docs={"relation": true, "columns": true}
) -}}

with sample_data as (

{% for item in ['row1', 'row2', 'row3'] %}
    {% if not loop.first %}union all {% endif %}select
        '{{ item }}' as field1,
        '{{ item }}' as field2
{% endfor %}
)

select
    field1 as alias1,
    field2 as alias2
from sample_data
```
```yml
version: 2

models:
  - name: bad_file
    columns:
      - name: alias1
        description: This field will persist
      - name: field2
        description: This field will fail
```

You'll get
```
Completed with 1 error and 0 warnings:

Database Error in model bad_file (models/marts/core/bad_file.sql)
  column "field2" of relation "bad_file" does not exist
  compiled SQL at target/run/ae_dw/models/marts/core/bad_file.sql
```

### Environment

```markdown
- OS: Mac 11.6
- Python: 3.9.2
- dbt: 0.21.0
```

### What database are you using dbt with?

redshift

### Additional Context

See [this Stackoverflow question](https://stackoverflow.com/questions/69710700/why-am-i-getting-a-column-x-of-relation-y-does-not-exist-error-when-runnin), which led to a ticket to dbt support (18116), in which @jeremyyeo helped me resolve the issue.

**Comment by jtcohen6** [comment]
@ljhopkins2 Thanks for the issue! You're right, we should aim to give a much more helpful error message here.

There was a similar issue for this a ways back: https://github.com/dbt-labs/dbt-core/issues/3039. We ended up deciding there that, even better than raising a more helpful error, we should avoid raising an error at all, if we can help it. Philosophically, dbt doesn't "strictly enforce" column schemas as its default behavior.

We went with a Snowflake-specific solution at first (https://github.com/dbt-labs/dbt-core/pull/3149) that relied on using `comment if exists`, but we ended up swapping it for a slightly cleverer approach that leveraged `adapter.get_columns_in_relation` (https://github.com/dbt-labs/dbt-core/pull/3543).

I don't think there's anything stopping us from extending [that code](https://github.com/dbt-labs/dbt-snowflake/blob/9caa1850ecc42f95c5fe9cb3cde824885efd7b46/dbt/include/snowflake/macros/adapters.sql#L157-L163) to other adapters—in this case, Postgres/Redshift:

https://github.com/dbt-labs/dbt-core/blob/40ae6b6bc860a30fa383756b7cdb63709ce829a8/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L182-L188

Could instead be:
```sql
{% macro postgres__alter_column_comment(relation, column_dict) %}
  {% set existing_columns = adapter.get_columns_in_relation(relation) | map(attribute="name") | list %}
  {% for column_name in column_dict if (column_name in existing_columns) %}
    {% set comment = column_dict[column_name]['description'] %}
    {% set escaped_comment = postgres_escape_comment(comment) %}
    comment on column {{ relation }}.{{ adapter.quote(column_name) if column_dict[column_name]['quote'] else column_name }} is {{ escaped_comment }};
  {% endfor %}
{% endmacro %}
```

The only trick is, if a column is cased/quoted strangely, and the user doesn't match its casing/quoting _exactly_ in their yaml file, no error will be raised—the description just won't be persisted.

I'm going to mark this a `good first issue`, and I'd welcome a PR for it. Would you be interested in contributing? :)

### future

Today, persisting docs is just one step (among many) defined and orchestrated within the Jinja materialization. While that's true, we don't have the ability to, say, try persisting docs, catch any errors, and wrap those errors in a helpful message, a la `Error persisting docs for model my_model`.

Eventually, I could imagine reworking materializations—perhaps by rewriting in python!—so as to enable this kind of error raising/handling/wrapping. We have a lot of other questions we need to answer before we get there.

**Comment by kadero** [comment]
Hi @jtcohen6 @ljhopkins2 :wave:,

Thank you for raising this issue and providing a solution.
Happy to open a PR to fix this issue If it suits you ?

:pray:
