### ISSUE TITLE
Re-add support for `dbt init <project_name>`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4156]
Folks are used to being able to pass project name as a first positional argument to the `dbt init` subcommand. The new approach (new for v1!) is much more fun + interactive, but for muscle memory's sake, let's see if we can't find a way to keep supporting `dbt init my_new_project`, too.

If passed, I think this argument should be used as the implicit answer for "What is the desired project name?" We should set `project_name` accordingly [here](https://github.com/dbt-labs/dbt-core/blob/178f74b753aab0c40d03799b3287a13f35740248/core/dbt/task/init.py#L301), and skip the prompt.

Related ask that we should foresee:
- Ability to skip profile setup entirely, and just create scaffolding for a new project (`--skip-profile-setup`?). This could be used by tools which manage connection setup themselves, such as dbt Cloud
- Ability to create project scaffolding in the current working directory, rather than always creating a new subfolder (#4141)

**Comment by b-per** [comment]
Hi @kadero, have you worked on this one already? If not, I am happy to raise a PR for it.

**Comment by kadero** [comment]
> Hi @kadero, have you worked on this one already? If not, I am happy to raise a PR for it.

Hello @b-per, 
Thanks for your message :slightly_smiling_face: .

Yes I began to work on it. I didn't find the time to finish the job (integration tests) and open a PR. I'm going to open a PR ASAP.

Thanks :pray:
