### ISSUE TITLE
[Bug] "dbt test -m <csv_name>" => "Nothing to do"

### ISSUE THREAD

**Issue by TimoKruth** [dbt-labs/dbt-core#4175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I `run dbt test` it runs all my defined tests for my csv files under data.
When I `run dbt test --exclude` I can exclude specific csv files from the tests.
When I `run dbt test -m` _Nothing to do_ is found.

### Expected Behavior

I would expect to be able to select a single csv file to be selected via `-m` flag. And many others online mention it should work or post examples where they use it. I can't figure out why it finds nothing but can exlude and run all tests.

### Steps To Reproduce

Create a _csv_ under "data/" with accomodating _yml_ file including a test. I use some from dbt_utils. But was not successful when I tried standard tests either.
`dbt test -m <csv_name>`

### Relevant log output

```shell
dbt test -m F1_EXPECTED
Running with dbt=0.20.2
Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
Partial parsing enabled, no changes found, skipping parsing
Found 68 models, 22 tests, 0 snapshots, 0 analyses, 457 macros, 0 operations, 22 seed files, 77 sources, 0 exposures
WARNING: Nothing to do. Try checking your model configs and model specification args
Error sending message, disabling tracking
```

### Environment

```markdown
- OS: Linux
- Python: 3.8
- dbt: 0.20.2
- dbt_utils: 0.7.0
- DB: Exasol
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

Database is Exasol but is not relevant for this problem.

**Comment by jtcohen6** [comment]
@TimoKruth I'm not able to reproduce the issue you're seeing. When I set this up locally:

```csv
-- data/F1_EXPECTED.csv
id
1
```
```yml
version: 2

seeds:
  - name: F1_EXPECTED
    columns:
      - name: id
        tests:
          - not_null
```
And then run:
```
$ dbt seed
$ dbt test -m F1_EXPECTED
```
Everything works like a charm:
```
Running with dbt=0.21.0
Found 0 models, 1 test, 0 snapshots, 1 analysis, 162 macros, 0 operations, 1 seed file, 0 sources, 0 exposures

13:42:02 | Concurrency: 5 threads (target='dev')
13:42:02 |
13:42:02 | 1 of 1 START test not_null_F1_EXPECTED_id............................ [RUN]
13:42:03 | 1 of 1 PASS not_null_F1_EXPECTED_id.................................. [PASS in 0.05s]
13:42:03 |
13:42:03 | Finished running 1 test in 1.76s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

> Database is Exasol but is not relevant for this problem.

This is the one variable I can't replicate, so there might be a related issue of which I'm unaware.

**Comment by TimoKruth** [comment]
Hello, my question was based on 20.2 and not 21.0 if you can reproduce it on 20.2 I would know that I could possibly fix it when I update (which destroys our project at the moment) and I would be really happy. But if you can't reproduce it in 20.2 either I would know its something really special to us. I would really appreciate the help

**Comment by jtcohen6** [comment]
Sure thing! I don't believe this has to do with changes between v0.20.2 and v0.21.
```
$ dbt test -m F1_EXPECTED
Running with dbt=0.20.2
Found 0 models, 1 test, 0 snapshots, 0 analyses, 147 macros, 0 operations, 1 seed file, 0 sources, 0 exposures

16:16:24 | Concurrency: 5 threads (target='dev')
16:16:24 |
16:16:24 | 1 of 1 START test not_null_F1_EXPECTED_id............................ [RUN]
16:16:24 | 1 of 1 PASS not_null_F1_EXPECTED_id.................................. [PASS in 0.05s]
16:16:24 |
16:16:24 | Finished running 1 test in 1.87s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```
Is it possible that there's something wonky with your CLI/shell, such that the selection criteria isn't being passed in right? Perhaps to do with casing as well (`F1_EXPECTED`)? You can check the `args` dict in `target/run_results.json` to see, it should look something like:
```json
  "args": {
    "log_format": "default",
    "write_json": true,
    "use_experimental_parser": false,
    "profiles_dir": "...",
    "use_cache": true,
    "data": false,
    "schema": false,
    "store_failures": false,
    "version_check": true,
    "models": [
      "F1_EXPECTED"
    ],
    "which": "test",
    "rpc_method": "test"
  }
```

**Comment by TimoKruth** [comment]
Okay, I figured the problem has to do with dbt_utils tests like:
      - dbt_utils.equal_rowcount:
          compare_model:  ref('model_name')
      - dbt_utils.equality:
Normal tests are recognized correctly. My bad for not checking. But I thought they would probably be designed in an equal way...
Will confront the dbt_utils project about that

**Comment by jtcohen6** [comment]
@TimoKruth Ah! That's a test with multiple parents. In v0.20, we switched default test selection logic to _exclude_ that test if you only specify `dbt test -m F1_EXPECTED`, but to _include_ that test when you specify both its parents: `dbt test -m F1_EXPECTED other_model_name`. We realized this is confusing for users, so we're switching back the default in v1, to "eagerly" select tests.

**Comment by TimoKruth** [comment]
You just made my day :)

**Comment by TimoKruth** [comment]
I read about this but couldn't link it to this issue completly.
