### ISSUE TITLE
Loosely Couple CLI

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#4179]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I would like to see the dbt cli loosely coupled from the rest of the core code base. This way the cli could be parsed into an object, and the rest of the code can access that object's fields. Today we have the cli parsing arguments and mutating global state without saving the original values, which makes it difficult to respect the inputs users have given us later in the flow.

Additionally, users have noticed how slow the CLI is to start up (e.g. - #4627), and separating out the CLI would allow us to more easily return quickly without loading unnecessary resources when we invoke dbt with invalid arguments or just ask for the version.

### Describe alternatives you've considered

We could just keep adding global mutations of values ad-hoc every time we need them. It's just messy and keeps the cli unnecessary tightly coupled.

### Who will this benefit?

dbt core devs and community contributors.

### Are you interested in contributing this feature?

Yes

**Comment by nathaniel-may** [comment]
Realistically, this same approach should be applied to the cli, all environment variables, and reading files, probably in that order.

**Comment by jtcohen6** [comment]
I know we've discussed this previously: As part of splitting out / rewriting the CLI, we should also consider alternatives to `argparse`. It can do some surprising things today:
- "Skip" arguments in highly confusing ways (https://github.com/dbt-labs/dbt-core/issues/4645)
- "Complete" abbreviated flag names (has caused confusion between similarly-named-yet-different flags, e.g. `--select` + `--selector`)
