### ISSUE TITLE
[Feature] Warn when model has direct relation references

### ISSUE THREAD

**Issue by Nandakumar-M** [dbt-labs/dbt-core#4181]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Hi,

DBT [best practice](https://docs.getdbt.com/docs/guides/best-practices#use-the-ref-function) suggests users to source/ref functions and avoid direct references to database relations.

Is there a way for DBT to check and warn if the DBT model contains a direct reference? I have a bunch of (large) queries to be added as DBT models. I am changing the references to make use of ref/source functions but doing this manually is error prone and I have missed some of them.

Would be great if DBT generates a warning in this case.

Regards,
Nanda

### Who will this benefit?

1. People who are migrating queries from some other tool to DBT.
2. People writing SQL in DBT

### Are you interested in contributing this feature?

Yes

**Comment by markuspihlaja** [comment]
I found this issue when searching for a solution to exact same problem.
This would be very helpful in enforcing proper ref / source macro usage.
