### ISSUE TITLE
[Feature] "Slim CI" but with `LIMIT 0`

### ISSUE THREAD

**Issue by jsnb-devoted** [dbt-labs/dbt-core#4201]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### The "Concise" description
"Slim CI" but with the ability to limit the "deferred" ref's to **0 rows** for faster CI checks

### How I got here:
**Our Existing CI set up:**
Our existing CI set up does the following:
1. Use `git diff` to determine changed models
2. Construct a run command that uses the `@` to determine the graph we need to run in ci `dbt run -m @my_model`
3. A custom `source` macro that replaces all sources with `(select * from {{ builtins.source(source_name, table_name) }} LIMIT 0)` if the command is using the `ci` target

This worked great until the  project grew in complexity and the `@` operator started creating enormous graphs. Our CI checks started to run hundreds of models on small changes. Even though the queries were processing 0 rows the checks were taking ~10 minutes in total.

**Where Slim CI falls short**
Slim CI (the `--defer` flag) presented itself as the logical answer to our problem in that we could move away from the `@` operator to slim down the CI graphs. Our proposed CI was similar to the existing one except now the run command looked like:
```
dbt run -m my_changed_model+ --defer --state path/to/prod/target
```
This worked as advertised but the problem was that even if our CI check went from running 300 models to 20 -- the tables in prod now had millions of records in them so the run time of the actual models increased. Also we are using snowflake so this would represent an unreasonable use of our Snowflake credits.

### Describe alternatives you've considered

**Custom ref**
We tried to hack the ref in a similar manner to the comment posted [here](https://github.com/dbt-labs/dbt-core/issues/1096#issuecomment-793605052):

```
    {%- if target.name == 'ci' -%}
        {% set ref_rel = builtins.ref(model_name) %}
        {% set empty_rel %}
            (select * from {{ ref_rel }} LIMIT 0)
        {% endset %}
        {% do return(empty_rel) %}
    {% endif %}
```

This works in that the compiled SQL in the artifacts will render the refs with the `LIMIT 0` but when we use those artifacts as the state for our CI check the `defer` operation resolves the refs without the `LIMIT 0` (which makes sense -- I suspect that `defer` relies on the relation name from the state artifact and not the rendered part with the limit)

### Who will this benefit?

Projects with lots of models and lots of data that want faster CI runs

### Are you interested in contributing this feature?

I'm interested -- would need to know where the project wants this to go. I was looking at trying to override the `render` method in the `Relation` class but that seemed pretty hacky

### Anything else?

https://github.com/dbt-labs/dbt-core/issues/1059 - "dry run" mode is kind of what we want. We want to run our SQL with no data so we can verify that the SQL will run.
https://github.com/dbt-labs/dbt-core/issues/3226 - Most of what we hope to check with CI is "column level lineage" -- namely that you can't delete a field from a model that is being referenced 10 levels downstream

**Comment by jtcohen6** [comment]
@jsnb-devoted Thanks for the thoughtful issue! You've clearly done your homework :)

Everything in your approach sounds spot on to me, with the crucial detail being that (I believe) `--defer` and custom `ref` macros work just fine together. Here's my quick reproduction case:

```sql
-- models/model_a.sql
select 1 as id
```
```sql
-- models/model_b.sql
select * from {{ ref('model_a') }}
```
```sql
-- macros/ref.sql
{% macro ref(model_name) %}

  {% set ref_rel = builtins.ref(model_name) %}
  {%- if target.name == 'dev' -%}
      {% set empty_rel %}
          (select * from {{ ref_rel }} LIMIT 0) a
      {% endset %}
      {% do return(empty_rel) %}
  {% else %}
      {% do return(ref_rel) %}
  {% endif %}

{% endmacro %}
```
```
$ dbt run --target prod
$ mv target/manifest.json state/
$ dbt run --target dev --defer --state state/ --select model_b
```
```
  create view "jerco"."dbt_jcohen"."model_b__dbt_tmp" as (
    select * from 
          (select * from "jerco"."analytics"."model_a" LIMIT 0) a
      
  );
```

That looks right to me. Or is there another piece of this that I'm missing?

Also, I just have to ask:

> Use `git diff` to determine changed models

Any reason you're not using `state:modified` for this?

**Comment by jsnb-devoted** [comment]
Thanks @jtcohen6 -- I'll give this a shot right now. At first glance I feel like my initial crack at this was wrong in that I was conditionally adding the `LIMIT 0` to the ref when the target was `prod` but what I actually wanted was to keep the prod manifest as is and add the `LIMIT` when the target was `ci`

A couple clarifications:

#### This would be running in "CI" so I would want to `compile` and not `run` against prod right? eg:
```
$ dbt compile --target prod
$ mv target/manifest.json state/
$ dbt run --target dev --defer --state state/ --select model_b
```

#### The resulting compiled sql I would actually want is more like:
```
  create view "ci_db"."dbt_jcohen"."model_b__dbt_tmp" as (
    select * from 
          (select * from "prod_db"."analytics"."model_a" LIMIT 0) a
      
  );
```
I want to **create** the models in the `ci_db` but **read** unselected refs from the `prod_db`. Does that still work with your example? Also I might have missed the part where the model gets rendered as `model_b__dbt_tmp` instead of just `model_b`.


#### re: `git diff`
The short of it is that I understood `state:modified` to require that I effectively compile twice. We are on `0.20.1` and our compile step takes ~2.5 minutes to run. We run the checks on CircleCI. If we weren't moving to `--defer`/SlimCI I think we would stick with `git diff` since it is faster unless I'm missing something there.

**Comment by jsnb-devoted** [comment]
This is totally working. I just had the wrong mental model about which target I needed to hack the `ref` for. I have a "happy path" test case and I'm going to need to wire it all up in CircleCI but I don't anticipate running into any problems.
Thanks again for setting me straight there! Really glad I opened the issue!

**re: `state:modified`** 
First of all I had no idea that `dbt ls` would generate the artifact sufficient for calculating state. That will be a huge time saver. As for publishing the `main`/prod artifact -- that seems totally doable as part of our "deploy" step and then CI checks should be able to pull that from s3 or wherever it ends up. I'll tee that up after I get the `--defer` stuff sorted out.

Feel free to close this out unless you all are interested in making this a more integrated feature.

**Comment by jas-grover** [comment]
@jsnb-devoted I implemented something very similar in our dbt project for Slim CI runs recently. Something you might want to watch out for is when a `ref` is used in a function like `dbt_utils.star`. In this case you would still want to return a `ref` object instead of the `LIMIT 0` query even in CI runs. Similarly `dbt_utils.union_relations` would be one to consider as well.

**Comment by trungv0** [comment]
@jas-grover How do you differentiate `ref` call in a function like `dbt_utils.star` from `ref` call in the query, to properly return a `relation` object in the former case?

**Comment by jas-grover** [comment]
The approach I took was to add a new parameter called `relation` in the `ref` macro. Where a `relation` object is required in CI environments, it's set to `True`. 
```sql
-- usage
dbt_utils.star(from=ref('table_name', relation=True))

-- ref macro
{% macro ref(model_name, relation=False) -%}

  {%- set is_ci_env = ... -%}

  {%- if (is_ci_env and not relation) -%}
  (
    select *
    from {{ builtins.ref(model_name) }}
    where false
  )
  {%- else -%}
  {{ return(builtins.ref(model_name)) }}
  {%- endif -%}

{%- endmacro %}
```

**Comment by dongchris** [comment]
@jas-grover is there a way to override the star and other macros to automatically set "relation=true"?

**Comment by jas-grover** [comment]
> @jas-grover is there a way to override the star and other macros to automatically set "relation=true"?

One way would be to fork those macros from `dbt_utils` but I'm not sure if that's something you would want to manage yourself.
