### ISSUE TITLE
[Bug] <unexpected handling of special characters in profiles.yml password field when env vars are used>

### ISSUE THREAD

**Issue by samLozier** [dbt-labs/dbt-core#4211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a snowflake service account password that contains special characters, notably two $. Using the default profiles.yml setup and hardcoding the password works, I can connect and dbt works as expected. 

For deployment and ease of use with co-workers I've been trying to move to a profiles.yml profile that lives in my project directory and references env variables. This is demonstrated in the docs [here].(https://docs.getdbt.com/reference/dbt-jinja-functions/env_var)

dbt seems to be handling the password field differently when it's referencing an env variable than if it was hardcoded. Dbt debug (as expected) does not display the password, however if I move the password reference to another field it appears correctly in the output of dbt debug. 

### Expected Behavior

A properly formatted env password should work the same as a hardcoded one. If the password field is parsed in a way thats different from the other fields, that should be documented, ideally in the dbt generated files themselves. 

### Steps To Reproduce

Actual password is : pa$$word
Password with escaped special characters set as env var: 
```
> echo $password_var
> pa\$\$word
```
the relevant portion of profiles.yml. **Note:** the password is also displayed in the user field in an attempt to view the parsed password in the output. 
```
...
      user: "{{ env_var('password_var') }}"
      password: "{{ env_var('password_var')}}"
...
``` 
```
> dbt debug
```
returns:
```
Connection:
  account: example_account
  user: pa$$word
...
```

As you can see, the password variable seems to get parsed properly and turned into the actual password (at least when output via the user field) however after changing the user field back to the actual username and attempting the connection, the connection still fails. When the password in the yml file is replaced with the hardcoded string `pa$$word` the connection will succeed. 

There appears to be some additional parsing happening in the password field that is very difficult to debug from an end user perspective. 
  

### Environment

```markdown
- OS: osx 11.6
- Python: 3.9.7
- dbt: 0.21.0
```

### What database are you using dbt with?

snowflake

**Comment by pgoslatara** [comment]
@samLozier I have a dollar sign in my password for a Postgres database and it strikes me that you may not be creating your env var correctly. This is how I do it:
```
user$ export password_var="abc\$\$123"
user$ echo $password_var
abc$$123
```
Note how when I `echo` the variable it does not contain any "\\" characters. Can you see if you can update your `export` command to align with this and see if it solves your issue?

**Comment by samLozier** [comment]
@pgoslatara thanks for looking into this. I spent some time re-creating the .env file this am, and suddenly it's working. My best guess is that I had a trailing space or something that was hard to see. 

It's still be nice if it were easier to debug the config.... BUT it looks like this one is on me. I'm closing this issue now since it looks like it was operator error.
