### ISSUE TITLE
Improve error message in `pip install dbt`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4229]
Starting in v1.0.0, `pip install dbt` will raise an explicit error:

```
As of v1.0.0, `pip install dbt` is no longer supported.
  Instead, please use either:
    - `pip install dbt-core`, for core functionality
    - `pip install dbt-<adapter>`, to use dbt with your database, platform, or query engine
  See full list: https://docs.getdbt.com/docs/available-adapters
```

The goal here is clarity for what users should do as a next step. In https://github.com/dbt-labs/dbt-core/pull/4133#issuecomment-962730765, @joellabes rightly pointed out that the first line is confusing. We expect that >95% of users will want to use the second.

Let's reorder and alter the wording in this error to something like:
```
As of v1.0.0, `pip install dbt` is no longer supported.
Instead, please use one of the following:

**To use dbt with your specific database, platform, or query engine:**
    
    pip install dbt-<adapter>
    
    See full list: https://docs.getdbt.com/docs/available-adapters
    
**For developers of integrations with dbt Core:**

    pip install dbt-core
    
    Be advised, dbt Core's python API is not yet stable or documented
    https://docs.getdbt.com/docs/running-a-dbt-project/dbt-api

**For the previous behavior of `pip install dbt`:**

    pip install dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery
```

I think we should feel comfortable taking up more screen real estate, since this is the only real thing folks will see when they run `pip install dbt`.

**Comment by jtcohen6** [comment]
@joellabes What do you think of the proposed message above? Open to any/all wordsmithing suggestions!

**Comment by joellabes** [comment]
Yep I'm 100% happy with this! I was originally going to suggest swapping `pip install dbt-adapter` to pole position, but it wouldn't have made sense with the old layout.
