### ISSUE TITLE
[Feature] Allow users to define additional context or instructions for test failures/warnings

### ISSUE THREAD

**Issue by balmasi** [dbt-labs/dbt-core#4232]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I find that as a team, as we get failing tests, there is quite a bit of ramp-up time for the developer to wrap their head around the context of the failing test and figure out what to do when the test is failing/giving a warning. 

I think it would be pretty neat if the test author could provide some metadata that would pop up during test run failures/warnings that give a tip as to what to look for and how to resolve the issue.

For example, instead of only showing:

![image](https://user-images.githubusercontent.com/300100/140791804-3999cbb4-3415-42b4-b7f0-96f7827cf902.png)

You could show:

```
Warning in test unique_mrt_fetch_company_sfdc_v1_domain (models/marts/stg_fetch/company/mrt_fetch_company_sfdc_v1.yml)
  Got 6 results, configured to warn if != 0

  compiled SQL at target/compiled/gio_dbt_gdp/models/marts/stg_fetch/company/mrt_fetch_company_sfdc_v1.yml/schema_test/unique_mrt_fetch_company_sfdc_v1_domain.sql

Developer Notes: If there is a warning with this test, it means there are multiple Salesforce accounts 
with the same domain. This should be be fixed immediately at the source (Salesforce) because one of the 
accounts is auto-chosen to be shown in the fetch mart, and it may not necessarily be the right one.
```

### Describe alternatives you've considered

Currently, in my project, I'm specifying some metadata in the test yaml; This works, but still involves jumping to the file and finding the definition.

![image](https://user-images.githubusercontent.com/300100/140791079-015d0eb2-5506-4bea-82c1-5364c2c22c9a.png)

### Who will this benefit?

Teams with multiple developers writing many tests.

### Time saved

**Without** considered alternative:

1-10 minutes per failing test per dev

**With** considered alternative:

30s-1min per failing test per dev

**Comment by jtcohen6** [comment]
@balmasi Thanks for opening, I really like this idea!

When we started reworking tests for v0.20, the original proposal included the possibility of adding `description` and/or `fail_msg`, static for singular tests and dynamically templated for generic tests—perhaps with the possibility of overriding for a specific instance of a generic test, as in your example above. It sounds like you're thinking along similar lines. We didn't end up getting there then, but further improving the UX around tests will continue to be a passion of mine after v1.

At the same time, I don't hate the idea that this lives under the `meta` key; the only question is how best to surface this information. I can imagine a future version of dbt documentation / metadata-powered features that include information about each test, including its `meta` properties, and provides clear links to that test's documentation/metadata whenever the test fails. That link could take the place of the current pointer when reporting a test failure: `compiled SQL at target/compiled/.../*.sql`.

A related proposal that may be of interest: tests ought to have specific owners (#3436), who could be notified, manually or automatically (!), when a test they own fails. Perhaps they'd be all the

**Comment by smitsrr** [comment]
We often include comments in our custom test .sql files that include instructions on how to debug and where to investigate, or what stakeholders to contact.

**Comment by Gregory108** [comment]
Everything but `tests:` have parameter `description:`. It seems logical and straightforward to keep the same naming everywhere.

**Comment by phammer** [comment]
This would be a great improvement that will help us get time back from various people. Adding some context why something was set to severity warn and what it means, that would be perfect. I.e., having a `description` parameter and then show it when the tests fail.
