### ISSUE TITLE
[Feature] Output in common report format for `dbt test` and `dbt run`

### ISSUE THREAD

**Issue by moltar** [dbt-labs/dbt-core#4247]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Would be great to be able to output results of `dbt test` and `dbt run` in a common reporting format.

This would allow CIs and build tools to create programmatic reports and display them in a UI.

Specific use case: CodeBuild has the ability to display reports in the following formats:

```
CUCUMBERJSON
    Cucumber JSON
JUNITXML
    JUnit XML
NUNITXML
    NUnit XML
NUNIT3XML
    NUnit 3 XML
TESTNGXML
    TestNG XML
VISUALSTUDIOTRX
    Visual Studio TRX
```

### Describe alternatives you've considered

Just logging output as is.

### Who will this benefit?

Everyone who uses CI/CD.

### Are you interested in contributing this feature?

No

### Anything else?

https://github.com/awsdocs/aws-codebuild-user-guide/blob/main/doc_source/test-report-pytest.md

**Comment by jtcohen6** [comment]
@moltar I think the Run Results artifact (https://docs.getdbt.com/reference/artifacts/run-results-json) is just the thing you're looking for! This includes all task output (`run`, `test`, `build`, etc) in a reliable, contracted, versioned format (JSON). You should be able to parse and reformat that JSON into different reporting formats as needed.

Here's one I just produced after running `dbt build` locally:
```json
{
  "metadata": {
    "dbt_schema_version": "https://schemas.getdbt.com/dbt/run-results/v3.json",
    "dbt_version": "0.21.1rc1",
    "generated_at": "2021-11-16T19:39:10.434816Z",
    "invocation_id": "983f8b0b-6e96-4a8e-8d0b-7b6107afca98",
    "env": {}
  },
  "results": [
    {
      "status": "success",
      "timing": [
        {
          "name": "compile",
          "started_at": "2021-11-16T19:39:10.330379Z",
          "completed_at": "2021-11-16T19:39:10.331972Z"
        },
        {
          "name": "execute",
          "started_at": "2021-11-16T19:39:10.332109Z",
          "completed_at": "2021-11-16T19:39:10.386001Z"
        }
      ],
      "thread_id": "Thread-1",
      "execution_time": 0.05624127388000488,
      "adapter_response": {
        "_message": "CREATE VIEW",
        "code": "CREATE VIEW",
        "rows_affected": -1
      },
      "message": "CREATE VIEW",
      "failures": null,
      "unique_id": "model.testy.model_a"
    },
    {
      "status": "pass",
      "timing": [
        {
          "name": "compile",
          "started_at": "2021-11-16T19:39:10.388134Z",
          "completed_at": "2021-11-16T19:39:10.406940Z"
        },
        {
          "name": "execute",
          "started_at": "2021-11-16T19:39:10.413837Z",
          "completed_at": "2021-11-16T19:39:10.424584Z"
        }
      ],
      "thread_id": "Thread-3",
      "execution_time": 0.03851485252380371,
      "adapter_response": {},
      "message": null,
      "failures": 0,
      "unique_id": "test.testy.not_null_model_a_id.1e928b9f1f"
    },
    {
      "status": "pass",
      "timing": [
        {
          "name": "compile",
          "started_at": "2021-11-16T19:39:10.395942Z",
          "completed_at": "2021-11-16T19:39:10.400729Z"
        },
        {
          "name": "execute",
          "started_at": "2021-11-16T19:39:10.400865Z",
          "completed_at": "2021-11-16T19:39:10.425716Z"
        }
      ],
      "thread_id": "Thread-4",
      "execution_time": 0.032258033752441406,
      "adapter_response": {},
      "message": null,
      "failures": 0,
      "unique_id": "test.testy.unique_model_a_id.94b83a3ca6"
    }
  ],
  "elapsed_time": 0.23477697372436523,
  "args": {
    "log_format": "default",
    "write_json": true,
    "use_experimental_parser": false,
    "profiles_dir": "/Users/jerco/.dbt",
    "use_cache": true,
    "store_failures": false,
    "greedy": false,
    "resource_types": [],
    "version_check": true,
    "which": "build",
    "rpc_method": "build"
  }
}
```

You can combine the results there with the richer context available in the manifest (https://docs.getdbt.com/reference/artifacts/manifest-json), which offers a full account of the resources in your project, and the catalog (https://docs.getdbt.com/reference/artifacts/catalog-json), which includes metadata snapped up from the database by `dbt docs generate`.

The only limitation to the batch metadata artifacts is that they're only available at the end of a dbt invocation. To that end, we're working on implementing a system of structured events + logging ahead of dbt Core v1, to support real-time reporting and observability as well.

**Comment by moltar** [comment]
@jtcohen6 thank you for pointing out where raw data lives.

But that doesn't solve the issue though. Why was it closed?

**Comment by jtcohen6** [comment]
@moltar Sorry! I may not have understood your original request.

I heard you asking for a common, structured format in which to report the results of dbt tasks, such as `run` and `test`. We'e implemented that in the form of our contracted metadata artifacts, specifically `run_results.json`. That includes an overall `status`, as well as the `status` for each node executed, to enable you to know what has passed, failed, and errored.

Separately, we're working on dbt's structured logging for v1, in order to support similar reporting on a dbt task while it's running.

Could you say a bit more about what you're looking for?

**Comment by moltar** [comment]
What I was thinking is that dbt can support one of the standard report formats and/or pluggable reporters, like many other testing tools do.

This would allow users to integrate with many existing tools that track test results, gather stats.

Some examples in the wild:

- TAP: https://en.wikipedia.org/wiki/Test_Anything_Protocol
- pytest: https://docs.pytest.org/en/6.2.x/usage.html#creating-junitxml-format-files
- jest: https://jestjs.io/docs/cli#--reporters

---

But having `run-results.json` is useful too, which can open up the possibility of at least having a converted even if it's just a CLI too that you can pipe thru.

**Comment by jtcohen6** [comment]
Got it, ok! I think the right constructs exist in dbt Core today (batch `run_results.json` + improved structured logs). I'd welcome you or other folks to develop tools that can convert the information contained in those into the reporting formats you need, and share it with the community—whether as a CLI tool, orchestrator plugin, etc.

For the time being, I don't think this conversion/formatting capability is something I'd expect to live inside dbt Core. I won't rule it out forever, though.

**Comment by chasleslr** [comment]
I also was hoping for dbt to support this given that it acts as the test runner and that is a typical feature for test runners in any language.

I created this small CLI tool that converts run results into jUnit XML for anyone that lands here looking for this as well!

https://github.com/chasleslr/dbt-junitxml
