### ISSUE TITLE
Change parsing exceptions from CompilationException to ParsingException

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#4254]
We added a ParsingException class, but there is still a mix of ParsingException and CompilationException errors raised in parsing. We should standardize exceptions encountered in parsing on ParsingException.

**Comment by Imbruced** [comment]
@gshank  Hi, Can I help you with that issue ? I think it might be "good first issue".  If I am wrong do you see any issue on which I can help you ?
