### ISSUE TITLE
[Bug] Tests against disabled models are selected by dbt build

### ISSUE THREAD

**Issue by ciejer** [dbt-labs/dbt-core#4269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When making changes to a disabled model, running `dbt build -s state:modified+` across a repository will exclude the model correctly, but runs the tests of that model.

### Expected Behavior

If a disabled model is changed, both the model and any tests of that model should be excluded from `dbt build`.

### Steps To Reproduce

1. Disable a model in the dbt repository, by adding the property `+enabled: false` in dbt_project.yml
2. Add a generic test (tested with `unique`) to a column in the model's schema.ym.
3. Run `dbt compile -s state:modified` to generate a manifest.json that is aware of the disabled model
4. Make a change to the disabled model
5. Run `dbt build -s state:modified+` using the manifest from step 3
6. Build executes the test, despite the model not being built

### Environment

```markdown
- OS: Windows 10
- Python: 3.9.7
- dbt: 21.0
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment]
@ciejer Thanks for the detailed report. I followed the reproduction steps you've listed above, but I'm not seeing the behavior you're describing.

### setup

```
--models/model_a.sql
select 1 as id
```
``` yml
# models/whatever.yml
version: 2
models:
  - name: model_a
    columns:
      - name: id
        tests:
          - unique
```
```
# dbt_project.yml

models:
  +enabled: false
```

### initial run
```
$ dbt build
Running with dbt=0.21.0
Found 0 models, 0 tests, 0 snapshots, 0 analyses, 162 macros, 0 operations, 0 seed files, 0 sources, 0 exposures

WARNING: Nothing to do. Try checking your model configs and model specification args
```

### change
Establish previous state:
```
$ mv target/manifest.json state/
```
Make change:
```
--models/model_a.sql
select 1 as id
-- changed
```

### build modified
```
$ dbt build -s state:modified --state state/
Running with dbt=0.21.0
Found 0 models, 0 tests, 0 snapshots, 0 analyses, 162 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
The selection criterion 'state:modified' does not match any nodes

WARNING: Nothing to do. Try checking your model configs and model specification args
```

**Comment by ciejer** [comment]
Thank you @jtcohen6 and apologies - got to the bottom of the issue and had tangled it up with something else.

The 'unique' test that was triggering is actually not a generic, but is a singular test .sql with timeframe filtering; named as a generic unique would be - which was changed in the same PR (SQLFluff rules change and mass fix).
This change to test was correctly picked up in `dbt build state:modified`, as the code of the test had changed. 

Closing the issue - and will be renaming our singular tests! (and moving any like this to generic dbt-expectations now we have them available)
