### ISSUE TITLE
[Feature] New Database Adapter Scaffold

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-core#4281]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### The Why

The purpose of this document is to get feedback from the community on planned changes to how new third party adapters can be made by users. Currently the process is completed by following the [**build**](https://docs.getdbt.com/docs/contributing/building-a-new-adapter) a new adapter steps using **[create_adapter_plugins.py](https://github.com/dbt-labs/dbt-core/blob/main/core/scripts/create_adapter_plugins.py)** within the dbt-core codebase.

We wish to make the process interactive, user-friendly, more well documented and give some quality of life updates such as options to have linting, static type checking, etc.

### The Plan

As of right now I'd like to share with you the plan as it is set forth and would love feedback on what else you think the process could benefit from. 

- Make the creation of the base project interactive by using a scaffolding tool, where user changes variables and some settings before generating project.
    
    ![image](https://user-images.githubusercontent.com/91097623/141854889-4a8eb1e2-07be-457c-95c2-791a0dfc02af.png)
    
- Add helpful docstrings and point to reference materials in docs or the postgres adapter for code design tips.
    
    ![image](https://user-images.githubusercontent.com/91097623/141854983-e61fa284-e97a-4c1d-827d-b32df3778259.png)
    
- Provide stubs for required macros and base layout of class methods within connections.py.
  <img width="882" alt="Screen Shot 2021-11-16 at 11 56 13 AM" src="https://user-images.githubusercontent.com/91097623/142039713-b01ff8f3-af28-43ae-811f-602689c3c6cb.png">
- Add nice to have features by default like flake8, mypy, and tox
- Create a loom video showing a step by step process of how the new scaffold script works and create an adapter.
- Update documentation to go along with these various changes to keep entire picture clear and concise.

### Your Part

I would be excited to hear from those in the community who have made adapters to see what issues you came across, what could of been more clearly stated, what features were hurdles or you truly think would be great to have from the start.

### Describe alternatives you've considered

The current process is a .py file that leaves a lot on the user to guess at, we are trying to make it more user friendly and provide better pointers to guides.

### Who will this benefit?

users and data companies we do not currently have a first or third party adapter for.

### Are you interested in contributing this feature?

I am

### Anything else?

For reference to the in progress work please see the [dbt-database-adapter-scaffold](https://github.com/dbt-labs/dbt-database-adapter-scaffold) repo

**Comment by mikaelene** [comment]
I don't know dbt-labs plan for community adapters but think this is a great idea! 

When I started building dbt-sqlserver it was more of a guessing and trial and error process. The process was more or less to make dbt run with my adapter and issue dbt run in a sample project and look in the log of the project.

It is easy to miss things like dbt-version, names etc that are difficult to change later when someone uses the adapter. 

Also the docstrings would be a great addition, maybe to also add a little of where the functions are used later on. 

A guide for setting up a IDE for debugging would also be nice, sine it is a little difficult to understand when and how the adapter is loaded to dbt.

**Comment by McKnight-42** [comment]
@mikaelene  very good points, to be able to give a little more context, i've linked above to my in-progress repo so please feel free to look at the scaffold and ask any questions preferably through here or the slack post.

**Comment by swanderz** [comment]
really appreciate you spending the time on this @McKnight-42! I have two, (probably related) questions:

1. what is meant by `adapter_src`, that you can inheirit from the base adapter or the sql adapter?
2. is it possible to specify and existing adapter to inheirit from? Sometimes I know I need to make an adapter that inheirits from dbt-sqlserver. Also, I think it's sometimes helpful when making a new adapter to make one that's based off of dbt-postgres so I can learn more quickly what won't work and needs to be fixed, rather than implementing everything from scratch.

**Comment by McKnight-42** [comment]
@swanderz great questions.
-  The adapter_src is in reference to the  connection methods that we have in other adapters/ current created adatpers from the .py file they would be the `SQLAdapter`, `SQLConnectionManager` which seems to be most common connection methods found in connection.py vs `BaseAdapter` which shows up in adapters like `dbt-bigquery`. Currently have it set up so that the selection of `adapter_src` within the cookiecutter run will trigger conditionals in the `hooks/pre_gen_project.py` to try and make the build process as quick as possible for the user. (Name change suggestions for clarification are welcome).
- Currently during build there is no way to automatically pull in stuff from existing Adapters. 
- Currently I have included in the macros sections pulled copied some of them across from Postgres over as examples, didn’t wish to do this for every one as many call upon special methods needed to work with Postgres they similar version may not be needed for other adapters so gave brief descriptions of layout of each other macro.
