### ISSUE TITLE
[Feature] Metric filters should be allowed to be non-string types

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4294]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Via https://github.com/dbt-labs/docs.getdbt.com/pull/915

In a metric, the filter
```
  - field: ltv
    operator: ">="
    value: 100
```
is rejected during compilation `at path ['filters'][0]['value']: 100 is not of type 'string'`

Types like bools, floats, ints should be allowed as well

### Describe alternatives you've considered

Leaving them purely as strings. In that case, we'd need to change the documentation so that filters look like this: 

```
  - field: ltv
    operator: ">="
    value: "100"

  - field: some_string
     operator: "="
     value: "'double quoted'"
```

### Who will this benefit?

People who want to filter metrics in a friendly way

### Are you interested in contributing this feature?

No

### Anything else?

This would constitute an artifact schema change, and require us to update manifest v4 at schemas.getdbt.com

**Comment by jtcohen6** [comment]
Thanks @joellabes!

I _think_ this could be as simple as changing this line:
https://github.com/dbt-labs/dbt-core/blob/719b2026ab847ab887d3638c81a351b0f6f96158/core/dbt/contracts/graph/unparsed.py#L455-L456

To:
```python
    value: Union[str, int, float, bool]  # others??
```

**Comment by joellabes** [comment]
Gave that a whirl, but got 
`at path ['filters'][0]['value']: 100 is valid under each of {'type': 'number'}, {'type': 'integer'}", "pid": 38112, "ts": "2021-11-17T22:12:44.269034"}`
