### ISSUE TITLE
[Bug] Using column aliases with incremental models does not work

### ISSUE THREAD

**Issue by tevariou** [dbt-labs/dbt-core#4300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not sure exactly if that's a documentation issue or a bug.

The [documentation](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#defining-a-uniqueness-constraint-optional) shows the use of column aliases in an incremental model.

```sql
{{
    config(
        materialized='incremental',
        unique_key='id'
    )
}}

SELECT
    row_id as id
FROM
    {{ref('my_table')}}


{% if is_incremental() %}

  -- this filter will only be applied on an incremental run
  where id not in (select id from {{ this }})

{% endif %}
```
Running DBT results in an error saying the column `id` does not exist

### Expected Behavior

The column alias should be recognized or the documentation fixed.

### Steps To Reproduce

1. Create an incremental model using column aliases
2. Add an `is_incremental()` filter using a column alias
3. Run DBT

### Environment

```markdown
- OS: Macos
- Python: 3.9
- dbt: 0.21.0
```

### What database are you using dbt with?

postgres

### Additional Context

To fix this issue I used a CTE but it's a bit cumbersome
```sql
{{
    config(
        materialized='incremental',
        unique_key='id'
    )
}}

WITH model AS (
SELECT
    row_id as id
FROM
    {{ref('my_table')}}
)

SELECT *
FROM model
{% if is_incremental() %}

  -- this filter will only be applied on an incremental run
  where id not in (select id from {{ this }})

{% endif %}
```

**Comment by tevariou** [comment]
closing since that's a db engine issue

**Comment by jtcohen6** [comment]
I think you may just need to adjust the SQL in your incremental model:
```sql
{{
    config(
        materialized='incremental',
        unique_key='id'
    )
}}

SELECT
    row_id as id
FROM
    {{ref('my_table')}}


{% if is_incremental() %}

  -- this filter will only be applied on an incremental run
  -- the column is named "row_id" in "my_table", and "id" in this model
  where row_id not in (select id from {{ this }})

{% endif %}
```
