### ISSUE TITLE
Scalable in-memory event history

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#4320]
Does something graceful when it runs out of memory (small machines shouldn't explode because of logging), is queryable by a potential future server-wrapper.

**Comment by iknox-fa** [comment]
@jtcohen6 Do you have thoughts on what it should do when it reaches it's max capacity?  My current thought is that it's simply a FIFO queue that logs a warning stating that the event buffer is full when it hits it's limit and drops the earliest messages.

**Comment by jtcohen6** [comment]
@iknox-fa Yes, that sounds right to me for the first cut of this. When @nathaniel-may and I chatted about this (at a very high level) last week, he was thinking the initial implementation could just be a good old fashioned `deque`

**Comment by nathaniel-may** [comment]
I'm thinking that even though Python class values are pretty bloated, we'll still want to fill the structure with them instead of rendered log-lines because we want to preserve the ability to choose rendering options (text vs json for example) after the fact.
