### ISSUE TITLE
[Feature] Generated data files that describe terminal nodes and dependencies to empower programmatic project maintenance.

### ISSUE THREAD

**Issue by leoebfolsom** [dbt-labs/dbt-core#4323]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Structured data files (say, csv files) that are added to the `target` folder as part of `dbt docs generate` that describe:

- Terminal nodes (in other words, models that are not depended on by any downstream models).
- Model dependencies on upstream nodes.

All of this information can be found in `manifest.json`, but why not empower the community and reduce the number of hours analytics engineers spend parsing json.

A list of terminal nodes is useful if you want to systematically clean up a dbt project by identifying terminal nodes that may be candidates for deletion. (Once you've identified a terminal nodes, a next step might be to see if the model is used in Looker.)

There are many ways this could be done, but I propose:

An output of two additional CSV files when `dbt docs generate` is run:

1. `terminal_nodes.csv`
Columns:
`model`: Each terminal node is a row.

2. `model_upstream_nodes.csv`
Columns:
`model`: The model (each model has 1 or more rows)
`upstream_node`: Upstream node depended on by that model.

Note that `model_upstream_nodes.csv` is a tall table, so the model value is repeated if there is more than one upstream_node value for that model.

I've written a script that does all of the above in Ruby, which I've included below. I would be happy to mock up a Python version if that would be helpful!

`discover_terminal_nodes_and_dependencies.rb`

```
# The point of this script is to generate temporary files that describe current dependencies 
# in the dbt DAG, as well as identify models that are terminal nodes in the DAG.

# These files can be used will use to clean up the DAG by examining dependencies programatically.
# My current use case is to inspect the models that are terminal nodes and determine whether they serve 
# any purpose (e.g., are they used by Looker?).

# Perhaps in the future, a snippet like this could generate these files in the target folder 
# when dbt docs are generated.

require 'json'
require 'csv'

# Create a function for naming csv files that are generated.

def timestamp_filename(file) # h/t Ryan McGeary https://stackoverflow.com/questions/14508026/is-there-an-easier-way-to-insert-a-time-stamp-into-a-file-name-with-ruby
	dir  = File.dirname(file)
 	base = File.basename(file, ".*")
	time = Time.now.utc.strftime('%m-%d-%Y-%H%M%S')  # or format however you like
	ext  = File.extname(file)
	File.join(dir, "#{base}_#{time}#{ext}")
end

# Open a version of the dbt manifest.json file and save it in a reasonable location.

file = File.read('./2021-11-22-manifest.json')
data_hash = JSON.parse(file)

# Generate a csv file with two columns: model, upstream_node.
# This is a tall table, with multiple rows for tables that have multiple upstream nodes.

# At the same time, create an array, `upstream_models` of all models that are upstream of other models.

upstream_models = []

CSV.open(timestamp_filename("./model_upstream_nodes.csv"), "w", :write_headers=> true, :headers => ["model","upstream_node"]) do |csv|
	
	# Iterate through each child in the json's "nodes".
	data_hash['nodes'].each do |node|

		# For the purpose of this endeavor, I don't care about tests.
		if(!node[0].start_with?('test.')) 

			# Store the current node (model) as a variable.
			current_node = node[0] 

			# Iterate through each node that the current node (model) depends on.
			node[1]["depends_on"]["nodes"].each do |d| 

				# Add a row to the CSV with the model and the upstream node it depends on.
				csv << [node[0], d] 

				# Add the depended-on node to the upstream_models array (if it's not already there).
				upstream_models |= [d]
			end
		end
	end
end

# A csv now exists containing each model and its upstream nodes.

# Then, using the `upstream_models` array we just created, identify the terminal nodes, which will be any model
# that is NOT included in `upstream_models`. Save this as another csv.

CSV.open(timestamp_filename("./terminal_nodes.csv"), "w", :write_headers=> true, :headers => ["model"]) do |csv|
	data_hash['nodes'].each do |node|
		current_node = node[0]
		if((!upstream_models.include? current_node) && (!current_node.start_with?('test.')))
			csv << [current_node]
		end
	end
end
```

### Describe alternatives you've considered

I started by looking at the dbt docs DAG and inspecting visually for terminal nodes. This works, but was slow and human-error-prone.

Furthermore, with an automated system, I could build out an alert or test as part of a pipeline/job.

For example, I could flag newly terminal nodes, trigger a search for usage of those models by other systems such as Looker, and proactively escalate instances of models that seem to serve no purpose.

In the absence of this feature, I will continue to maintain and build out a jerry rigged version for my org to use internally.

### Who will this benefit?

Analytics engineers who want to keep their DAGs well maintained!

### Are you interested in contributing this feature?

Sure! I could probably translate my current script to Python. This would be my first time contributing to dbt-core.

**Comment by leoebfolsom** [comment]
Amy Chen (dbt) suggested that perhaps a version of this could be added to the [artifacts](https://hub.getdbt.com/tailsdotcom/dbt_artifacts/latest/) package. I'd be happy to contribute to either that or dbt-core; open to guidance.

**Comment by jtcohen6** [comment]
@leoebfolsom Thanks so much for the thoughtful issue, and so sorry for the delay on our end getting back to you!

As part of locking in the schemas for [metadata artifacts](https://docs.getdbt.com/reference/artifacts/dbt-artifacts), we're also saying: These are the artifacts that `dbt-core` will officially support going forward. We're highly unlikely to introduce a new one, especially if the information it contains is duplicative with information contained in an existing contracted artifact, such as `metadata.json`.

So a few thoughts following on that one:
- I'm really excited that you want to share your tool with other community members. I think the open source  [`dbt_artifacts`](https://github.com/brooklyn-data/dbt_artifacts) package is one potential home! Maybe it makes sense as a one-off Ruby/python script, maybe as a dbt model (rewritten into SQL) that can run in the warehouse and track this over many manifests over time. One note after a quick perusal of your code: I think you may get some mileage from the `parent_map` + `child_map` in `manifest.json`. Those include first-order parent and child relationships, without needing to parse `node.depends_on`, though it will still require some recursive logic to construct full/"tall" lineage.
- For folks who use dbt Cloud, and have access to the [Metadata API](https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-api/metadata/metadata-querying), I think it might be all the more ergonomic to write the same types of "queries" (childless nodes, full node lineage) in GraphQL.

For now, I'm going to close this issue, as I don't think it's something we'll be adding to `dbt-core`. Thanks again for opening it, and for sharing your code with the community :)

**Comment by leoebfolsom** [comment]
Hi @jtcohen6, thanks so much for your reply! In retrospect, it totally makes sense not to prioritize adding this to dbt-core, since really what I've done is taken information that's available in manifest.json and shaped it differently. 

I'll return to your comments next time I am searching for terminal nodes, at which point I hope to update and contribute my code. 

Thanks again!
