### ISSUE TITLE
Add node_status reporting to logging

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#4324]
### Big Picture
Provide a more complete picture of the node status in a point in time through logs.  Create a dict `node_info` that will contain the status at the time the log fired.

### Existing Events
- add a new dict with node_info
- ensure that all node-related events include unique_id.  Acts as both a unique identifier and a way to look up any node information in manifest.json
- Provide more structure by adding `node_info` to existing messages where we fire and event when starting/finishing node events.

### New Events
- add a few new granular events to fill in the gaps between Start + Finish — though we're currently limited in the level of granularity, since we can't (yet) fire custom event types within the materialization

### dict structure
```
  "node_info": 
        {"node_path": "models/slow.sql", 
        "node_name": "slow", 
        "resource_type": "model", 
        "node_materialized": "table", 
        "node_started_at": "2021-10-05T13:17:28.018613", 
        "unique_id": "model.my_new_project.slow", 
        "node_finished_at": "2021-10-05T13:17:29.134126", 
        "node_status": "passed", 
        "run_state": "running"}
```

[Original details](https://github.com/dbt-labs/dbt-core/issues/3359#issuecomment-934428619)

related to #4260 

Things left to do:

- [x] node_status - create new contract for "running" nodes and Union it with the result contract
    - "running" contract could be started (very first event for a node), compiling [here](https://github.com/dbt-labs/dbt-core/blob/4eb17b57fbcacb2c63a252b412a64e1c2e944adc/core/dbt/task/base.py#L282-L286), executing [here](https://github.com/dbt-labs/dbt-core/blob/4eb17b57fbcacb2c63a252b412a64e1c2e944adc/core/dbt/task/base.py#L291-L293) - and fire new events when the node reaches those points
- [x] start/end time need to be populated.  Needs to persist across events for a unique id.
- [ ] modify return of node_info after #4326 is merged in
- [ ] create Union of types for `report-node_data` instead of using `Any` - currently involves some circular imports
- [x] fire new events for node status changes
- [x] modify current events to include `node_info` as needed

**Comment by jtcohen6** [comment]
@emmyoop Is there a reason to prefer a totally separate `node_info` dict, versus passing this information as a property of the event type dataclass, for inclusion in the `data` dict? On one hand, node-specific reporting is of especial importance; if anything warranting its own top-level attribute, it's probably this. On the other hand, node information is just one more piece of rich context for our events, and we should seek to flesh out out all our events with as much structured contextual information as possible. I'm happy with either answer, just interested to hear your reasoning

**Comment by emmyoop** [comment]
@jerco I saw `node_info` as something very specific that warranted it's own dict.  Since it seems like something important to report on, it didn't make sense to me to have to wade through what mattered and what didn't.  Additionally:

1. Adding it to `data` as it is now may result in some duplications within the `data` dictionary.  This could be fixed but is a decent amount of overhead to make sure there are no collisions.

2. This way I can just pass in the node and parse it out as needed.  `data` doesn't have any processing on what properties are on the dataclass, it just passes them through to the json output.  It's simpler to have one dict we parse and one we don't, especially since the `data` dict is somewhat unpredictable in what it contains.

3.  As of right now `data` get overwritten to `None` when it has properties that cannot be serialized.  We definitely don't want that with `node_info`.

**Comment by jtcohen6** [comment]
@emmyoop Thanks for laying that out - I buy it!
