### ISSUE TITLE
[Bug] Equality test: failures => '0' is not of type integer

### ISSUE THREAD

**Issue by TimoKruth** [dbt-labs/dbt-core#4335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run an equality test from dbt_utils  on a seed and a model/table I get the error that '0' is not an integer.
It works in version 0.20.2 but not anymore in 0.21.0 or 1.0.0rc1.

### Expected Behavior

Running with dbt=0.20.2
Found 64 models, 15 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 25 seed files, 77 sources, 0 exposures

13:36:02 | Concurrency: 2 threads (target='unittest')
13:36:02 |
13:36:02 | 1 of 1 START test dbt_utils_equality_testcsv_A__ref_test_............ [RUN]
13:36:03 | 1 of 1 PASS dbt_utils_equality_testcsv_A__ref_test_.................. [PASS in 0.17s]
13:36:03 |
13:36:03 | Finished running 1 test in 0.57s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1

### Steps To Reproduce

Create following 3 files in corresponding folders for seeds and models.

testcsv.csv
```
"A" 
1
test.sql
select 1 as A from dual
```
test.yml
```
version: 2
seeds:
  - name: testcsv
    columns:
    - name: A
    tests:
      - dbt_utils.equality:
          compare_model: ref('test')
          compare_columns:
            - A
```
```
dbt seed
dbt run
dbt test
```

### Relevant log output

```shell
Running with dbt=0.21.0
Found 64 models, 15 tests, 0 snapshots, 0 analyses, 376 macros, 0 operations, 25 seed files, 77 sources, 0 exposures

13:31:58 | Concurrency: 2 threads (target='unittest')
13:31:58 |
13:31:58 | 1 of 1 START test dbt_utils_equality_testcsv_A__ref_test_............ [RUN]
Unhandled error while executing test.dib.dbt_utils_equality_testcsv_A__ref_test_.145311c1ec
'0' is not of type 'integer'

Failed validating 'type' in schema['properties']['failures']:
    {'type': 'integer'}

On instance['failures']:
    '0'
13:31:58 | 1 of 1 ERROR dbt_utils_equality_testcsv_A__ref_test_................. [ERROR in 0.15s]
13:31:58 |
13:31:58 | Finished running 1 test in 0.49s.

Completed with 1 error and 0 warnings:

'0' is not of type 'integer'

Failed validating 'type' in schema['properties']['failures']:
    {'type': 'integer'}

On instance['failures']:
    '0'

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: Linux
- Python: 3.8.8
- dbt: 0.21.0 | 1.0.0rc1
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

DB: Exasol with dbt-exasol: 1.0.2
I actually tested the scripts on the exasol and they do not output a string. So I can only see it to be converted somewhere inside the code of dbt

First opened in[ dbt-utils](https://github.com/dbt-labs/dbt-utils/issues/443) but was refered here by @joellabes .

I would need a hand. Can't figure out where it goes wrong or why.
I guess it failes at this place in dbt-core but since it depends on this dbt-utils.equality test I posted it here:
https://github.com/dbt-labs/dbt-core/blob/719b2026ab847ab887d3638c81a351b0f6f96158/core/dbt/task/test.py#L212

Some more informative compiled versions:
cat target/compiled/dib/unittests/test.yml/schema_test/dbt_utils_equality_testcsv_A__ref_test_.sql :

```
-- setup
with a as (
    select * from UT_DOCKER.testcsv
),
b as (
    select * from UT_DOCKER.test
),
a_minus_b as (
    select A from a
    except
    select A from b
),
b_minus_a as (
    select A from b
    except
    select A from a
),
unioned as (
    select 'a_minus_b' as which_diff, a_minus_b.* from a_minus_b
    union all
    select 'b_minus_a' as which_diff, b_minus_a.* from b_minus_a
)
select * from unioned
```
And from RUN folder
cat target/run/dib/unittests/test.yml/schema_test/dbt_utils_equality_testcsv_A__ref_test_.sql :
```

select

    count(*) + coalesce(abs(
        sum(case when which_diff = 'a_minus_b' then 1 else 0 end) -
        sum(case when which_diff = 'b_minus_a' then 1 else 0 end)
    ), 0)
 as failures,

    count(*) + coalesce(abs(
        sum(case when which_diff = 'a_minus_b' then 1 else 0 end) -
        sum(case when which_diff = 'b_minus_a' then 1 else 0 end)
    ), 0)
 != 0 as should_warn,

    count(*) + coalesce(abs(
        sum(case when which_diff = 'a_minus_b' then 1 else 0 end) -
        sum(case when which_diff = 'b_minus_a' then 1 else 0 end)
    ), 0)
 != 0 as should_error
    from (

-- setup

with a as (
    select * from UT_DOCKER.testcsv
),
b as (
    select * from UT_DOCKER.test
),
a_minus_b as (
    select A from a
    except
    select A from b
),
b_minus_a as (
    select A from b
    except
    select A from a
),
unioned as (
    select 'a_minus_b' as which_diff, a_minus_b.* from a_minus_b
    union all
    select 'b_minus_a' as which_diff, b_minus_a.* from b_minus_a
)
select * from unioned
    )
```
I removed some empty lines for length reasons.

**Comment by jtcohen6** [comment]
@TimoKruth It does sound like this is something happening on the dbt-exasol side of things, since we're not seeing this on other databases. The result of the failure calculation:
```
count(*) + coalesce(abs(
        sum(case when which_diff = 'a_minus_b' then 1 else 0 end) -
        sum(case when which_diff = 'b_minus_a' then 1 else 0 end)
    ), 0)
```
Is being returned as `'0'` instead of `0`.

Questions:
- Is this happening for any other tests (`unique`, `not_null`, etc), or just for `dbt_utils.equality`?
- Does _this specific error_ go away if you configure the `fail_calc` to use `count(*)` instead?
- Are you able to determine the data type of `failures`, when you run the full query in Exasol (_not_ using dbt)?

One possible solution could look like doing what we did for `should_warn` + `should_error` (boolean coercion) in v0.21.1 (https://github.com/dbt-labs/dbt-core/pull/4091), and try to coerce `failures` to be an integer here:

https://github.com/dbt-labs/dbt-core/blob/d046ae0606422db24865ce5eaeaa00933c72b72a/core/dbt/task/test.py#L39-L60

But I'd ideally like to get at the heart of the matter, by figuring out what's different in Exasol / the dbt-exasol adapter.

**Comment by TimoKruth** [comment]
Questions:

    

- Is this happening for any other tests (unique, not_null, etc), or just for dbt_utils.equality?
I could only recognize it for equality. We run equal_rowcount aswell pretty often and that works.

-  Does this specific error go away if you configure this test's fail_calc to use count(*) instead? (docs)
<- Will test and edit this ->

-  Are you able to determine the data type of failures, when you run the full query in Exasol (not using dbt)?
When I run it in exasol it outputs a number as failures. Specifically a decimal.

**Comment by TimoKruth** [comment]
Okay I found a hack... I will discuss this further with [dbt-exasol](https://github.com/tglunde/dbt-exasol/). 
# Hacks
For Equality:
```
{% set set_diff %}
    cast(count(*) + coalesce(abs(
        sum(case when which_diff = 'a_minus_b' then 1 else 0 end) -
        sum(case when which_diff = 'b_minus_a' then 1 else 0 end)
    ), 0) as INT)
{% endset %}
```

For Equal_rowcount:
`
{{ config(fail_calc = 'CAST(coalesce(diff_count, 0) as INT)') }}
`
