### ISSUE TITLE
[Feature] Run all tests in one query

### ISSUE THREAD

**Issue by matsavage** [dbt-labs/dbt-core#4346]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

It would be great to combine all tests to be run on a table, or a group of tables into one query when using BigQuery, the reason for this is that in BQ, you only pay for data scanned and not processing time, therefore if all tests can be run at the same time, they will only be charged once.

For example:

I may have one column I expect to have one of 2 values, and not be null, which can be specified like:
``` yaml
    - name: column_name
      tests:
        - accepted_values:
            values: ["VALUE1", "VALUE2"]
        - not_null
```
Which is perfectly fine, but running this would result in running two queries, which would scan the data twice, resulting in being charged twice, but they could be combined on DBT's side and then they would only be charged once.

### Who will this benefit?

Users of DBT and BigQuery

**Comment by jtcohen6** [comment]
@matsavage Thanks for opening the issue, and sorry for the delay getting back to you!

If I understand you right, I see a big idea here, as well as a specific problem you're trying to solve. I also think you might be interested to read the conversation in https://github.com/dbt-labs/dbt-core/issues/2884, which has some similarities with your idea!

### Bigger idea

dbt knows that, in columnar databases, it costs money (either in time or bytes) every time a query scans a column. To that end, dbt should try to bundle all tests that touch a single column into a single unioned query, thereby saving time and money.  (I don't see as much value in combining tests across multiple columns/tables into the same query.)

In the case of an `accepted_values` + `not_null` test, this would look something like:

```sql
-- this is the compiled SQL for the accepted_values test
with all_values as (

    select
        column_name as value_field,
        count(*) as n_records

    from `<project>`.`<dataset>`.`<model>`
    group by id

)

select *
from all_values
where not (value_field in (
    'VALUE1','VALUE2'
))

union all
    
-- This is the compiled SQL for the not_null test
select *
from `<project>`.`<dataset>`.`<model>`
where column_name is null
```

That query is going to return either zero rows (both tests passed—cool!), or nonzero rows (one or both of the tests failed). In cases where it returns nonzero rows, dbt could either:
- Re-run each test individually, to determine which 
- Label each test result row with an extra column, indicating the relevant test. Save the test failure (a la `--store-failures`), examine the output, and assign failing rows to the applicable test.

This does get complex pretty quickly: What if different tests have different severity thresholds (`warn_if`/`error_if`)? Different ways to calculate number of failures (`fail_calc`)? What about tests that require scanning columns/models other than the one on which they are defined (e.g. `relationships`)?

My sense is, this would be a pretty significant lift in dbt, and I think we get a lot of mileage out of the current abstraction, whereby one test = one query.

---

### Workaround

In the meantime, for the specific circumstance where you want to test that a column both contains only the values you want _and_ never contains a null value, and you want to test both conditions in a single query, you can — by writing a custom generic test that does it all.

Here's a pretty simple adaptation of the [built-in `accepted_values` logic](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/generic_test_sql/accepted_values.sql):

```sql
{% test accepted_values_and_not_null(model, column_name, values, quote=True) %}

with all_values as (

    select
        {{ column_name }} as value_field,
        count(*) as n_records

    from {{ model }}
    group by {{ column_name }}

)

select *
from all_values
where value_field not in (  -- this condition excludes null values
    {% for value in values -%}
        {% if quote -%}
        '{{ value }}'
        {%- else -%}
        {{ value }}
        {%- endif -%}
        {%- if not loop.last -%},{%- endif %}
    {%- endfor %}
) or value_field is null  -- so let's explicitly include them further down

{% endmacro %}
```
```yml
    - name: column_name
      tests:
        - accepted_values_and_not_null:
            values: ["VALUE1", "VALUE2"]
```

That's it! One query, one column scan, one test that will check both of the conditions you're after.
