### ISSUE TITLE
Support Semantic Versioning in Git

### ISSUE THREAD

**Issue by aodhan-domhnaill** [dbt-labs/dbt-core#4350]
For private packages, it would be nice to support semantic versioning. It would make sense to only support this for git tags.

I can contribute the change. Are you interested in supporting this?

<details>
<summary>
Changes needed
</summary>

https://github.com/dbt-labs/dbt-core/blob/5d1b104e1f33551dad502802eea34d74a977e22d/core/dbt/contracts/project.py#L66-L68

```
revision: Optional[Union[RawVersion, List[RawVersion]]] = None
```

https://github.com/dbt-labs/dbt-core/blob/5d1b104e1f33551dad502802eea34d74a977e22d/core/dbt/contracts/project.py#L65-L76

https://github.com/dbt-labs/dbt-core/blob/434f3d26789d4bed3f0057c7c7d898e9dbf6687f/core/dbt/clients/git.py#L93

https://github.com/dbt-labs/dbt-core/blob/434f3d26789d4bed3f0057c7c7d898e9dbf6687f/core/dbt/deps/git.py#L113

</summary>

**Comment by jtcohen6** [comment]
@aodhan-domhnaill Thanks for opening!

dbt does support pinning git packages to any branch or tag name. That includes tags named after specific semantic versions:
```
# packages.yml
packages:
  - git: https://github.com/dbt-labs/dbt-utils.git
    revision: 0.7.4
```

I understand your request to mean, dbt should also be able to do version/dependency resolution for git-pinned packages, such that you could specify something like:
```
# packages.yml
packages:
  - git: https://github.com/dbt-labs/dbt-utils.git
    revision: [">=0.7.4", "<0.8.0"]
```

Am I understanding you right? If so, that's a complex undertaking — and it's the functional purpose behind the dbt Hub package registry, which stores metadata about available versions and dependencies, and exposes that metadata via a simple API.

If you have a private package that you don't want posted publicly, I think your options are:
- Tightly pin the semantic version, i.e. by specifying a semver-compliant tag name with a `git` package
- Use a private, custom version of the Hub site (i.e. forked from [the public one](https://github.com/dbt-labs/hub.getdbt.com)), which you can then use via the `DBT_PACKAGE_HUB_URL` env var:

https://github.com/dbt-labs/dbt-core/blob/e93ad5f118261f428bd24f052a780d7f72277207/core/dbt/clients/registry.py#L12-L15

**Comment by abdel-87** [comment]
Is there a possibility to implement this in the current architecture?
