### ISSUE TITLE
[CT-529] [Bug] Validate docs block names + raise clear exception during parsing

### ISSUE THREAD

**Issue by ddobrinskiy** [dbt-labs/dbt-core#4352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using a colon `:` in naming a documentation block results in compilation error.

ℹ️ note that using a colon in model names, and in ref `{{ ref('my:model') }}` works as expected

```
Running with dbt=0.21.0
Encountered an error:
Compilation Error in model my:model (models/bug_example/my:model.sql)
  Documentation for 'model.dbt_timescale.my:model' depends on doc 'my:awesome:documentation'  which was not found

```

### Expected Behavior

dbt recognizes the reference and renders documentations successfully

### Steps To Reproduce

1. install dbt `0.21.0`
2. put files from [this gist](https://gist.github.com/ddobrinskiy/93fb6d11ef0b6a6932b42498e3eaed17) in `models/bug_example` folder
3. `dbt run --select models/bug_example`
4. observe the error

### Relevant log output

```shell
Running with dbt=0.21.0
Encountered an error:
Compilation Error in model my:model (models/bug_example/my:model.sql)
  Documentation for 'model.dbt_timescale.my:model' depends on doc 'my:awesome:documentation'  which was not found
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8.5
- dbt: 0.21.0
```

### What database are you using dbt with?

postgres

**Comment by gshank** [comment]
This is true of all block names. In core/dbt/clients/_jinja_blocks.py:  _NAME_PATTERN = r'[A-Za-z_][A-Za-z_0-9]*'

**Comment by jtcohen6** [comment]
Sounds like this is a limitation from Jinja, and it would apply equally to anything defined in a Jinja block:
- docs blocks
- snapshots
- macros
- generic tests
- materializations

@ddobrinskiy Is there a reason you need to include colons in the name of your docs blocks, rather than underscores? My inclination is to document this as a reasonable limitation, rather than calling it a bug that needs fixing.

**Comment by tekumara** [comment]
Ah I didn't realise there special chars like `:` or `$` are not valid jinja names. Perhaps an explicit syntax error message would be helpful, eg: 
```
unexpected char ':' at 9
```

**Comment by jtcohen6** [comment]
@tekumara A clearer error message like that, during parsing (rather than dependency resolution), makes sense to me!

**Comment by nathaniel-may** [comment]
estimation
- exit criteria: better exception for jinja names that include a `:` or `$`
- proposed implementation: catch the existing exception, look for these characters in the message and throw a different exception. (won't be able to access this value until after jinja parses it and throws).

**Comment by SandervandenOord** [comment]
So I ran into this starting the name of my doc block with a number.
This is also not allowed. 

Can the documenation also be corrected:

> docs blocks can be named however you like, as long as the name only contains alphanumeric and underscore characters

This  is stated on this page:
https://docs.getdbt.com/docs/building-a-dbt-project/documentation#using-docs-blocks

**Comment by ddobrinskiy** [comment]
Up
