### ISSUE TITLE
Text vs JSON and File vs CLI logs

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#4354]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

re [this comment](https://github.com/dbt-labs/dbt-core/pull/4353#discussion_r758603782), text log lines might want to be different per destination. We may want text log lines to filter from json log lines, but I'm not sure about that. Just something to consider.

**Comment by jtcohen6** [comment]
To summarize myself over in #4293:

> Broadly, I find that I want:
> 
> - color, concision, clean spacing on the CLI
> - colorless + compact verbosity in the File + JSON-formatted
