### ISSUE TITLE
[Bug] dbt run with custom printer width

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#4373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
We're quite inconsistent in which events support custom printer widths today. That's status quo with current (pre-v1) behavior. The primary places where `printer_width` is used:
- events that use `line_wrap_message` to construct their message strings
- `format_fancy_output_line` for the most recognizable "running" messages (but in a pretty unintuitive way!)

Let's revisit in the future, with the aim of applying printer width more consistently across all events
