### ISSUE TITLE
[Bug] Extraneous dbt.log.old in logs directory

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#4374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
- This is the file that `logbook` (old logging system) will write to
- If `DBT_ENABLE_LEGACY_LOGGING` is enabled, `dbt.log.old` will include all logs
- If the legacy logging is _not_ enabled, then `dbt.log.old` (i.e. logbook) seems to include only deprecation warnings from dependencies. I can't track down the logic for this behavior in `logger.py` (legacy)
