### ISSUE TITLE
[Bug] dbt init overwrite just appends to profile

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#4375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you have a profile setup and then you try to setup a new one, it will ask if you want to overwrite existing entry. It just adds another entry and does not overwrite it. 

1) dbt init a new project and verify the connection in profile.yml 
2) inside the existing project run `dbt init` again and when it asks you to overwrite the connection choose yes. 
There are now 2 entries in profile.yml for it

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
@leahwicz This isn't something I've managed to reproduce locally. I imagine the fix for it is super straightforward, though

**Comment by leahwicz** [comment]
@jtcohen6 yes I was able to do it again so that's why I filed it. I would rate this low on priorities but I would assume its an easy fix as well

**Comment by NiallRees** [comment]
@leahwicz I also wasn't able to reproduce the issue where two profile entries were created, but there definitely is a bug where the user isn't asked for permission to overwrite an existing profile entry. The above PR addresses that.

**Comment by iknox-fa** [comment]
@leahwicz I was not able to replicate the original described behavior either.
I reviewed @NiallRees's contribution which is perfectly fine code wise, I was unable to replicate that failure-to-ask bug as well.  

I tested this on 1.0.0 and 1.0.1 with the same results.  Can you both provide the versions you were working with so I can be sure I'm comparing apples to apples?

**Comment by iknox-fa** [comment]
@NiallRees Never mind my previous comment, that bug is confirmed as is it's fix (thanks again).  
I wasn't testing it correctly, mea culpa (the bug only occurs with custom `profile_template.yml`, which I missed in the first pass)

@leahwicz Let's close this ticket as addressing the issue Niall found and we can open a new one for the double-entry if you can show me how to reproduce it.
