### ISSUE TITLE
[Bug] Compilation errors appearing for me, whereas for other users it doesn't even if we check out to the same branch

### ISSUE THREAD

**Issue by AgnieszkaDul** [dbt-labs/dbt-core#4390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open dbt cloud, I DAG functionality for specific model doesn't work, as Compilation error is displayed. Other users can check out to the same branch and don't have the error.
The problem exists regardless of the branch, I can check out to the master, have everything up to date, and still see the compilation error.
Yesterday it was working,  there was no compilation error.
My dbt:
![dbt compilation error](https://user-images.githubusercontent.com/86959768/144433662-e7ed2985-9594-45cb-b96f-1e269dbac3fc.PNG)
Another user's: 
![Screenshot 2021-12-02 at 14 34 27](https://user-images.githubusercontent.com/86959768/144433687-fddd1d90-7af9-46da-9c0a-b3736c3b10e5.png)
 

### Expected Behavior

Lack of compilation error, DAG diagram is displayed.

### Environment

```markdown
- OS:
- Python:
- dbt: 0.21.0
```

### What database are you using dbt with?

postgres

**Comment by jtcohen6** [comment]
@AgnieszkaDul Sorry for the delayed response here!

For issues like this one, it's best to write into the Support channel in dbt Cloud. They'll be able to give you much more timely assistance, and dig into what might be causing the Compilation Error you mention. I hope you were able to get this resolved in the meantime!
