### ISSUE TITLE
[CORE-15] `SQLQueryStatus` event expects `get_response` to return `AdapterResponse` object only

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4433]
See https://github.com/dbt-labs/dbt-spark/pull/265 for context

My proposal would be:

- **v1.0.1:** Check the type of the value returned by `get_response`, then either use its `_message` attribute (if `AdapterResponse`) or itself (if `str`)
- **v1.1.0:** Enforce that the `get_response` abstract method must return an `AdapterResponse` — not a bad change, and it's _effectively_ true, but we should wait for a minor version release, with clearer communication ahead of time

**Comment by nathaniel-may** [comment]
re-opening since #4463 only solved the first bullet.

**Comment by jtcohen6** [comment]
Opened https://github.com/dbt-labs/dbt-core/issues/4499 to reflect future work. Closing this one as resolved!
