### ISSUE TITLE
[Feature] Identify source of error message "the JSON object must be str, bytes or bytearray, not Undefined"

### ISSUE THREAD

**Issue by tekumara** [dbt-labs/dbt-core#4436]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The source of the following error is unclear:
```
$ dbt compile
Running with dbt=0.21.1
Encountered an error:
the JSON object must be str, bytes or bytearray, not Undefined
```

Identifying the file and line number would be very helpful during development/debugging.

### Who will this benefit?

Anyone with this error

### Anything else?

Example that generates the error:

_customers.sql_
```
{{ config ( materialized='view', pre_hook=foobar()) }}
```

**Comment by emmyoop** [comment]
Thanks for taking the time to write this up and provide an easy way to reproduce this behavior!

I'll agree that this error is not very informative.  If you run with the `--debug` flag you do get a bit more information.  dbt will log the path of the node where the error was hit, `model.jaffle_shop.my_first_dbt_model` in my case.  Hopefully that will at least help with debugging.

```
2021-12-15 19:32:33.438517 (MainThread): Flushing usage events
2021-12-15 19:32:33.694959 (MainThread): Connection 'model.jaffle_shop.my_first_dbt_model' was properly closed.
2021-12-15 19:32:33.695987 (MainThread): Encountered an error:
2021-12-15 19:32:33.696471 (MainThread): the JSON object must be str, bytes or bytearray, not Undefined
```

I do see it being valuable to provide more context on this error in v1.0! 

Catching `TypeErrors` in addition to `ValidationError` here

https://github.com/dbt-labs/dbt-core/blob/0ed14fa2361c98e5119f52afebb3d5d8ee18c419/core/dbt/parser/base.py#L375-L381

would allow for an output of

```
(env) emily% dbt  compile
19:52:08  Running with dbt=1.0.0
19:52:08  Partial parse save file not found. Starting full parse.
19:52:09  Encountered an error:
Parsing Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
  the JSON object must be str, bytes or bytearray, not Undefined
```

While this is an improvement, it still doesn't seem informative enough to me.  It's a matter of tracking down when/what gets assigned `Undefined` and catching that sooner to pass as much useful information through as possible.
