### ISSUE TITLE
[Bug] on-start-run executes during compilation

### ISSUE THREAD

**Issue by tekumara** [dbt-labs/dbt-core#4445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

on-start-run executes macros during `dbt docs` and `dbt compile` even when inside an `if execute` conditional.

### Expected Behavior

dbt docs and dbt compile don't run macro code inside an `if execute` conditional

### Steps To Reproduce

_macros/run_start.sql_
```
{% macro run_start() %}
  {% if execute %}
  {{ dbt_utils.log_info("🏁 \033[1m Let's go! 🏁 \033[0m")}}
  {% set results = run_query('select 1 from foobar') %}
  {% endif %}
{% endmacro %}
```

_dbt_project.yml_
```
on-run-start: "{{ run_start() }}"
```

### Relevant log output

```shell
Running with dbt=0.21.1
Found 9 models, 7 tests, 0 snapshots, 0 analyses, 572 macros, 2 operations, 8 seed files, 4 sources, 0 exposures

12:24:46 | Concurrency: 4 threads (target='dev')
12:24:46 | 
12:24:46 + 🏁  Let's go! 🏁 
Encountered an error:
Runtime Error
  Database Error in operation jaffleshop-on-run-start-0 (./dbt_project.yml)
    002003 (42S02): SQL compilation error:
    Object 'FOOBAR' does not exist or not authorized.
```

### Environment

```markdown
- OS: darwin
- Python: 3.9
- dbt: 0.21.0
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment]
@tekumara Thanks for opening!

The `compile` task (and therefore `docs generate`) compiles SQL, including macros + hooks, in `execute` mode. The distinction between `run` and `compile` is subtle: `compile` is a subset of `run` functionality; model SQL is fully compiled for both (including execute-time introspective queries); the only step excluded in `compile` is the materialization logic itself.

We do need to update the docs for `on-run-*` hooks to reflect this reality: https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end

The good news is, in v1.0, there is now a context variable available from the `flags` module ([docs](https://docs.getdbt.com/reference/dbt-jinja-functions/flags)), `flags.WHICH`, which will return the name of the currently running task/command. So your macro code could look like:
```sql
{% macro run_start() %}
  {% if execute and flags.WHICH in ('run', 'build') %}
  {{ dbt_utils.log_info("🏁 \033[1m Let's go! 🏁 \033[0m")}}
  {% set results = run_query('select 1 from foobar') %}
  {% endif %}
{% endmacro %}
```
Be advised, you should _not_ use any values of `flags` in code needed at parse time (dependencies + configurations).

**Comment by jtcohen6** [comment]
Since there's a viable workaround in v1.0, I'm going to close this as a `wontfix`

**Comment by tekumara** [comment]
Thanks for the explanation and workaround @jtcohen6!

If the `on-run-*` hooks run for most everything, and not specifically `run`, maybe there's a better name for them?

**Comment by jtcohen6** [comment]
That's fair! `on-task-start`? `on-execute-start`? There are other places where we use the word `run` to refer to any task / execution, such as `run_results.json`

**Comment by tekumara** [comment]
Or how about `on-dbt-start` perhaps?
