### ISSUE TITLE
[Bug] Exposures docs not showing descriptions, tags, owner, and other properties v1.0.0

### ISSUE THREAD

**Issue by Husseinjd** [dbt-labs/dbt-core#4472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running "dbt docs serve" with exposures inside the project, the details are not shown on any of the exposures withing the documentation page, even thought the exposures are present, and the details can be found within the html, yet not shown on the page.

### Expected Behavior

Exposures details should be shown on the documentation page

### Steps To Reproduce

1. create exposure schema file
2.  run dbt docs generate && dbt docs serve

### Relevant log output

```shell
-
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.7.6
- dbt: 1.0.0
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment]
@Husseinjd Thanks for the report! We're tracking this one in the `dbt-docs` repo: https://github.com/dbt-labs/dbt-docs/issues/224

We're planning to include a fix for it in an upcoming patch release (v1.0.1).

In the meantime, I'm going to close this issue as a duplicate.
