### ISSUE TITLE
[Bug] Threading model prevents exceptions in threads from reaching logging in a meaningful way

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#4476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During the course of resolving #4424 it was discovered that exceptions caused within threads during runtime don't surface to the user in a meaningful way. My current understanding is that is due to the threading model we currently use, although this needs further verification.

### Expected Behavior

Exceptions are visible to the user

### Steps To Reproduce

Revert changes made in #4424
Run the test suite with json output enabled

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
@iknox-fa Is this the same as the issue described in https://github.com/dbt-labs/dbt-core/issues/4357? Let's close one and keep one open, whichever has the most useful + up-to-date info.

My sense is that this is only relevant for internal-to-dbt exceptions (e.g. failure to serialize logs to JSON). Any database errors that threaded execution encounters, even unhandled ones, are bubbled up appropriately.
