### ISSUE TITLE
Cancelling Runs Using CTRL-C In DBT 1.0.0 Triggers Verbose Error Message

### ISSUE THREAD

**Issue by kdw2126** [dbt-labs/dbt-core#4480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I start running a valid model using my valid _dbt_ configuration and then cancel it using Ctrl-C in bash, the error message that appears is:

```The <bound method BaseAdapter.type of <class 'dbt.adapters.bigquery.impl.BigQueryAdapter'>> adapter does not support query cancellation. Some queries may still be running!```

### Expected Behavior

This seems like a regression over the earlier error message in dbt 0.19.1:
```The big query adapter does not support query cancellation. Some queries may still be running!```

### Steps To Reproduce

1.  From a valid BigQuery configuration profile and project with at least one model, enter _dbt run_ in bash.
2. Before the command finishes running, use Ctrl-C to interrupt execution.

### Environment

```markdown
- OS: Mac OS X 11.4 (20F71)
- Python: Python 3.8.10
- dbt: 1.0.0 (along with dbt-bigquery 1.0.0)
```

### What database are you using dbt with?

bigquery

### Additional Context

I believe that [this line](https://github.com/dbt-labs/dbt-core/blob/b3039fdc7629b5027096e92ed9b7612419cf3fea/core/dbt/task/runnable.py#L362) is at the root of the issue. 

If you change the code from
 ```fire_event(QueryCancelationUnsupported(type=adapter.type))``` 
to 
```fire_event(QueryCancelationUnsupported(type=adapter.type()))```

 the error message returns to the 0.19.1 version.  It seems like the existing code assigns the actual method to QueryCancelationUnsupported.type, which is then passed into the error message, while adding parentheses is required to actually call the function and fetch the string name of the adapter so it can be passed to the error message.

**Comment by jtcohen6** [comment]
@kdw2126 Right you are! Thank you so much for opening the issue, and finding the specific spot in the code causing the unexpected output.

I think we should change that line exactly as you recommend, switching `type=adapter.type` for `type=adapter.type()`. After all, the event expects `type` to be a string, not an object method:

https://github.com/dbt-labs/dbt-core/blob/b3039fdc7629b5027096e92ed9b7612419cf3fea/core/dbt/events/types.py#L2148-L2149

Let's include this as a fix in v1.0.1. If you'd like to contribute the fix, and get there before we do, you're welcome to it :)
