### ISSUE TITLE
adapters w/o boolean support can't use 'check' strategy on snapshots with new columns

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-core#4488]
I'm surprised no dbt-sql server user ever reports this issue before, but this `TRUE` causes problems for SQL dialects that don't support boolean types. related: https://github.com/dbt-msft/dbt-sqlserver/issues/186 thanks to @oscar-konig for making a reproducible example that led to this fix!

Rather than asking adapter maintainers to override `snapshot_check_strategy`, a better answer would be a simple macro for generating a boolean expression with the default of course being `TRUE`, but in non-core adapters, it could be `1=1`

https://github.com/dbt-labs/dbt-core/blob/0ed14fa2361c98e5119f52afebb3d5d8ee18c419/core/dbt/include/global_project/macros/materializations/snapshots/strategies.sql#L157-L174

**Comment by McKnight-42** [comment]
Thank you @dataders for all the work you put in on this closing this issue as it was pushed up via #4871
