### ISSUE TITLE
[CT-61] [Bug] interactive dbt init allows illegal project names

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just set up a sandbox project for myself using the new interactive dbt-init. When it asked what I wanted to call it, I chose `joel-sandbox`. 

When I ran `dbt debug`, it failed because ` 'joel-sandbox' does not match '^[^\\d\\W]\\w*$'`. 

### Expected Behavior

`dbt init` should at minimum include the "lowercase and underscores only" rule, and really should also validate that the input conforms. 

### Relevant log output

```shell
Project loading failed for the following reason:
Runtime Error
  at path ['name']: 'joel-sandbox' does not match '^[^\\d\\W]\\w*$'

Error encountered in /Users/joel/Documents/GitHub/joel-sandbox/dbt_project.yml
```

### Environment

```markdown
- OS: MacOS
- Python: 3.8.10
- dbt: 1.0.0
```

### What database are you using dbt with?

snowflake

**Comment by iknox-fa** [comment]
Thanks for the bug report @joellabes!  We'll get this sorted ASAP.

**Comment by amirkdv** [comment]
@joellabes I took a stab at this! PR is ready for review

p.s: first time dbt contributor :nerd_face:

**Comment by joellabes** [comment]
That's awesome @amirkdv! Thanks for the contribution. 

I'll leave the Core team to handle the review 😁

**Comment by leahwicz** [comment]
@ChenyuLInx let's remember to backport this as well

**Comment by bendiktv2** [comment]
The tutorial needs to be updated to use a valid project name: https://docs.getdbt.com/tutorial/create-a-project-dbt-cli

**Comment by jtcohen6** [comment]
@bendiktv2 Good call! Could I ask you to open a quick issue or PR at https://github.com/dbt-labs/docs.getdbt.com? If you scroll to the bottom of that page, there's also an "Edit this page" link that will open the appropriate file in GitHub's web editor.

**Comment by bendiktv2** [comment]
@jtcohen6 , please see #1155 :)

**Comment by bendiktv2** [comment]
Sorry, PR is in other repo. Here is the correct link: https://github.com/dbt-labs/docs.getdbt.com/pull/1155

**Comment by jtcohen6** [comment]
Thank you!! :)
