### ISSUE TITLE
Sorting options when using dbt list

### ISSUE THREAD

**Issue by AdaptavistChak** [dbt-labs/dbt-core#4492]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Hi, when we list the parents of a dbt model like this:
dbt ls -m +<model_name>

It prints them out in alphabetical order. Is there a way to print these out according to the hierarchy? For example model C depends directly on models A and B. Model B also depends on Model A.

So I’d want it to print out:

Model A
Model B
Model C

So the list goes from the “furthest” parent to the “closest” one. 

### Describe alternatives you've considered

There's not many alternatives but I have juggled with the idea of checking which parents are in the model using a bash script. With this I can infer which parents are directly referenced in the model and which aren't.

### Who will this benefit?

I'm not entirely sure what I think have more options to sort the results of the list like you would in bash is just generally useful.

**Comment by iknox-fa** [comment]
Hi @AdaptavistChak , thanks for reaching out with your request.  We've started a discussion internally on the topic and we had a few questions before we can proceed:

* Are you a cloud or CLI user?
* How would you need to handle dependencies that aren't 1:1.. meaning one parent has two or more children?

Hit us up with the details and we'll see what we can do!
