### ISSUE TITLE
[Feature] Enable development of dbt models with refs which resolve to production dbt tables, without requiring state artifacts

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-core#4493]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I would love for there to be a way to configure dbt such that for an example model hierarchy of:

![image](https://user-images.githubusercontent.com/23722609/146179927-ce2d9e0d-3236-4378-982a-b13243c6bcaf.png)

When I run
```
dbt run --select dim_customers
```

The refs resolve to production tables. While zero-copy cloning in Snowflake provides a big improvement vs copying underlying production data to dev schemas, we can still do better by just referring directly to those production tables. 

I'm imagining flags something like:
```
- production_ref_database
- production_ref_schema
- production_ref_target_name
```

which would be used to determine the ref() for models which aren't selected in the CLI command.

**Comment by jtcohen6** [comment]
Thanks @NiallRees! I think there's real appetite for more ergonomic deferral, especially in local development.

I do want to link two related conversations that I remember:
- An `--upstream` flag, pointing to a different named `target` in the same profile, to use when resolving deferred references: https://github.com/dbt-labs/dbt-core/issues/2968#issuecomment-961339732
- [Slack thread](https://getdbt.slack.com/archives/C50NEBJGG/p1628695149035000): Why is a production artifact needed for `--defer`? Answer: It's possible that production namespaces are calculated using vars/env vars/macros/etc that are quite difficult to reproduce, with fidelity, at runtime

I like the ease of pointing to a different target for "upstream" only. I'm not convinced we should pursue that—but also not entirely opposed—knowing that it's going to be an easier, imperfect proxy, and less tenable in more complex setups. I also think dbt Cloud can do a lot to offer easier access to artifacts/metadata that power deferral, and lower the barrier that way.

**Comment by NiallRees** [comment]
> An --upstream flag, pointing to a different named target in the same profile, to use when resolving deferred references

is a great idea, and would work well I imagine for 95% of users
