### ISSUE TITLE
[Feature] Update Dockerfile and docker image release process

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#4495]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Our Dockerfile/image release process has been at least somewhat broken since we divided the codebase into `dbt-core` + `<dbt-adaptername>`.  This ticket encompasses the work required to create a new Dockerfile and implement a new image building process coupled to Github Actions.

### Describe alternatives you've considered

N/A

### Who will this benefit?

Anyone who uses Docker

**Comment by iknox-fa** [comment]
Duplicate of CORE-21 in Jira.

**Comment by jtcohen6** [comment]
@iknox-fa Thanks for opening!

Here's a proposed build matrix, for when we should actually build/tag/push new images:
| image / tag   | `latest`                                                           | minor latest (e.g. `1.0.latest`)                              | specific version (e.g. `1.0.1rc1`)                                       |
|---------------|--------------------------------------------------------------------|---------------------------------------------------------------|--------------------------------------------------------------------------|
| dbt-core      | **Triggered by:** every final release of dbt-core, if latest*                        | every final release in this minor version family (e.g. 1.0.1) | every individual release (including prereleases)                                    |
| dbt-[adapter] | every final release of dbt-core or this adapter plugin, if latest* | every final release of dbt-core or this adapter plugin in this minor version family        | every individual release (including prereleases) of dbt-core or this adapter plugin |

*The "latest" version of dbt should, at any point in time, mean the latest patch release of the latest minor version. E.g. after v1.1.0 is released, a subsequent v1.0.3 patch would no longer update the overall "latest" tag. It should still update the `1.0.latest` tag.

This won't handle the case where an adapter plugin depends on another adapter plugin (e.g. `dbt-redshift` &rarr; `dbt-postgres` &rarr; `dbt-core`), the intermediary plugin has an update, and neither `dbt-core` nor `dbt-redshift` does. I think that's going to be an exceedingly rare case, and we can always push a one-off manually if we need to.

Definitely open to your thoughts here!

**Comment by leahwicz** [comment]
@kwigley had release process thoughts as well- could you add them here please, Kyle?

**Comment by iknox-fa** [comment]
@jerco, I'd like to get a signoff on the rest of the plan to complete the automation:
* Automate the release process with GHA
* Follow the frequency and build matrix as defined above
* Push images to github's CR instead of dockerhub

Does that make sense to you?

Also I manually pushed 1.0.0 this AM to dockerhub so feel free to spread the word (I have already a bit)

**Comment by iknox-fa** [comment]
@jtcohen6!  Good thing @JerCo isn't actually a github account name.
*something something there are only two hard problems in computer science.. *

**Comment by jtcohen6** [comment]
@iknox-fa That sounds right to me!

One last item on the list: updating docs, https://docs.getdbt.com/dbt-cli/install/docker (i.e. [here](https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/dbt-cli/install/docker.md)), with the plan going forward for how folks should expect to install dbt via Dockerfile and/or image from GHCR.
