### ISSUE TITLE
[CT-297] `get_response` should always return `AdapterResponse`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4499]
Split off from #4433:

> In v1.1.0, let's enforce that the `get_response` abstract method must return an `AdapterResponse`

This will allow us to clear up some tech debt. At its very simplest, an `AdapterReponse` can just look like the one in `dbt-spark`:

```python
    @classmethod
    def get_response(cls, cursor) -> AdapterResponse:
        return AdapterResponse(
            _message='OK'
        )
```

Ideally, of course, an adapter has more interesting information to pass along (number of rows affected, bytes processed, relevant query/job ID, etc).

Let's do this for v1.1.0, with clear communication ahead of time for adapter maintainers, since this does constitute a breaking change.

**Comment by MartinNowak** [comment]
Sounds great, we've actually forked dbt to hack in logging of BigQuery job links.

**Comment by jtcohen6** [comment]
@MartinNowak Sounds like you might be interested in https://github.com/dbt-labs/dbt-bigquery/issues/92!
