### ISSUE TITLE
[Feature] Add project checksum to manifest.json and run_results.json metadata

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-core#4515]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Prompted by https://github.com/tailsdotcom/dbt_artifacts/issues/53

Currently, it's only possible to match a `run_results.json` with a `manifest.json` if they have the same `invocation_id`, a custom environment variable is set, or the `data:metadata:env:dbt_cloud_run_id` is present. It should be possible to link a `run_results.json` with a `manifest.json` based on the state of the project at the time of their generation.

An initial version of this could simply be a hash of all the concatenated node checksums.

**Comment by gshank** [comment]
I can see how useful this would be. The idea of concatenated node checksums is interesting, but there are some complications -- the contents may change based on environment variables, or vars, or things that change in the dbt_project.yml file. Perhaps an arbitrary uuid that's common to both the manifest and the run_results? Similar to the cloud run_id, I suppose.

**Comment by NiallRees** [comment]
> Perhaps an arbitrary uuid that's common to both the manifest and the run_results? Similar to the cloud run_id, I suppose.

Is this not just the existing `invocation_id`? The motivation really is being able to match `run_results.json` with a `manifest.json` produced by an identical version of the project. Identical version of the project needs clearly defining, but like you said could include the state of the models, env vars, vars etc.

**Comment by gshank** [comment]
Oh, I see. We have something like that for the partial parsing check, which is called ManifestStateCheck. We also check for file changes and env var changes. I suppose a combination of the ManifestStateCheck, the file checksums, and env_var changes might work.
