### ISSUE TITLE
[Bug] Exposures appear as "Not currently documented" with dbt 1.0

### ISSUE THREAD

**Issue by badge** [dbt-labs/dbt-core#4520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When generating documentation with dbt 1.0, Exposures all appear with the description "This is not currently documented". This is true whether documentation has been generated through the CLI or on dbt Cloud.

### Expected Behavior

The _Details_ and _Description_ sections of the documentation of an exposure would include details and the description.

### Steps To Reproduce

- Run `dbt init` to create a new project; set up the profile as necessary
- Copy the exposures example [from here](https://docs.getdbt.com/docs/building-a-dbt-project/exposures#declaring-an-exposure) and paste it into the `models/schema.yml` file
- Replace the `depends_on` entries with references to the two sample models
- Generate and serve docs with `dbt docs generate` and `dbt docs serve`
- Navigate to the exposure documentation

![Screenshot 2021-12-20 at 11 40 41](https://user-images.githubusercontent.com/1969339/146761961-aaf06c0b-797e-4748-abc7-cccff31dfd3d.png)

### Environment

```markdown
- OS: macOS 12.0
- Python: 3.8.9
- dbt: 1.0
```

### What database are you using dbt with?

snowflake

### Additional Context

- Looking at the generated `manifest.json` file, the description of the exposure appears there without issue
- Using the `doc` macro results in the same outcome
- The *Depends On* section **is** correctly populated with links to the models on which the exposure depends

**Comment by emmyoop** [comment]
@badge Thanks for the report! We're tracking this one in the dbt-docs repo: dbt-labs/dbt-docs#224

A fix for this has been included in the v1.0.1 patch release (currently in prerelease).

In the meantime, I'm going to close this issue as a duplicate.

**Comment by badge** [comment]
Thanks @emmyoop! I didn't realise there was a different docs repo, will check there next time. ☺️
