### ISSUE TITLE
Dockerfile should support multi-platform images

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#4527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our newly created Dockerfile for image building supports multiple platforms through the `build_for` build arg.. however there is a more clever solution-- to build images that support multiple architectures utilizing [multi-platform builds/manifests](https://www.docker.com/blog/multi-platform-docker-builds/).

This would require a small overhaul to the build system to use `buildx` and some re-arranging of the dockerfile

### Expected Behavior

`docker pull dbt-postgres` can pull the correct image based on your architecture.

### Steps To Reproduce

`docker pull dbt-postgres && docker run dbt-postgres --version` on a non AMD64 platform.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

This isn't a huge deal, but if we want to support M1 macs without making a separate image for them we'll have to go there eventually.

**Comment by iknox-fa** [comment]
Not really a bug I guess. :)

**Comment by jakeberesford-palmetto** [comment]
This would be a good improvement. Running the amd64 image on an M1 mac is noticeably slower because of emulation.

**Comment by jakeberesford-palmetto** [comment]
This is still an issue. We have changed our approach to building our own images, but I believe it should be fixed in the images provided by dbt.

**Comment by bendiktv2** [comment]
+1 for adding support for buildx multiplatform docker images

**Comment by jtcohen6** [comment]
Agree that this would be an improvement. Given other priorities, it's unlikely to be something we're able to prioritize in the near term.

For now, we've documented this as a fair motivation for using our Dockerfile for build a custom image, rather than using the prebuilt images: https://docs.getdbt.com/docs/get-started/docker-install#building-your-own-dbt-docker-image
