### ISSUE TITLE
python 3.10 compatibility (DeprecationWarning filling the logs)

### ISSUE THREAD

**Issue by fvigo** [dbt-labs/dbt-core#4537]
Hi,

when running some commands (i.e. `dbt compile` ) on python 3.10.0, I get tons of messages like these:
```
2021-12-29 09:45:49.495921 (MainThread): getName() is deprecated, get the name attribute instead
2021-12-29 09:45:49.496368 (MainThread): currentThread() is deprecated, use current_thread() instead
```
that clog the log file and the log buffer, resulting in errors also printed to `stderr`.

It looks like python 3.10 emits `DeprecationWarning` exceptions for these functions.

Tested on dbt 1.0.0:
```
 dbt --version
installed version: 1.0.0
   latest version: 1.0.0

Up to date!

Plugins:
  - bigquery: 1.0.0
 ```

**Comment by MartinNowak** [comment]
The deprecation warnings with Python 3.10 come from logbook which [seems unmaintained](https://github.com/getlogbook/logbook/issues/317).
https://github.com/getlogbook/logbook/blob/3e0badb395ed8d0038d02996d38aa0505441327e/logbook/concurrency.py#L47

**Comment by emmyoop** [comment]
Thanks for the report @fvigo.  We don't support Python 3.10 ([yet!](https://github.com/dbt-labs/dbt-core/issues/4562)).  Downgrading to Python 3.9 will resolve the deprecation errors you are experiencing for now.

I'm going to close this for now as we will resolve these with support for Python 3.10.
