### ISSUE TITLE
[CT-21] [Bug] Unable to get DBT_PSYCOPG2_NAME working

### ISSUE THREAD

**Issue by rjrudin** [dbt-labs/dbt-core#4552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My goal is to use DBT_PSYCOPG2_NAME to force usage of psycopg2 instead of psycopg2-binary as first documented at https://newreleases.io/project/github/dbt-labs/dbt-core/release/v0.15.0 , and also at https://github.com/dbt-labs/dbt-core/blob/main/plugins/postgres/setup.py#L32 . Not having any luck so far, as python3.9/site-packages always ends up with psycopg2-binary and the psycopg2 directory has the contents one would get if directly depending on psycopg2-binary (I've compared that with depending on psycopg2 and not dbt). 

### Expected Behavior

python3.9/site-packages should not contain psycopg2-binary and should only contain psycopg2

### Steps To Reproduce

1. I'm using Python 3.9.9
2. I can reproduce this locally on my Mac (OS 11.6.2), but I'll stick to the docker-compose file I'm using. That file has the slimmed-down contents of:

```
FROM python:3.9-slim-bullseye
RUN apt update && \
    apt install -y git && \
    apt install -y build-essential
RUN apt install -y libpq-dev python3-dev
RUN DBT_PSYCOPG2_NAME=psycopg2 pip install --user dbt
CMD ["ls", "-la",  "/root/.local/lib/python3.9/site-packages"]
```

3. That results in the following output for the "ls" command:

```
api_1  | drwxr-xr-x   3 root root   4096 Jan  5 15:41 psycopg2
api_1  | drwxr-xr-x   2 root root   4096 Jan  5 15:41 psycopg2_binary-2.9.3.dist-info
api_1  | drwxr-xr-x   2 root root   4096 Jan  5 15:41 psycopg2_binary.libs
```

I've tried "--force-reinstall" and "--no-cache-dir", but no luck. As mentioned above, I can't get this to work on my Mac either, but I figure the docker-compose file is more relevant for reproducing the issue. 

Hopefully I'm just missing something obvious, as I didn't see any other issues involving this except one using pip-compile, which we're not using. 

Thanks!

### Relevant log output

```shell
Log output shown above
```

### Environment

```markdown
- OS: Debian Bullseye (11)
- Python: 3.9.9
- dbt: Started with 0.20.2, have tried 0.21.1, 1.0, and 1.0.1 - all behave the same
```

### What database are you using dbt with?

postgres

**Comment by kwigley** [comment]
👋 @rjrudin, thanks for reporting this and providing helpful details! This isn't documented properly, I can update docs to explain instructions to do this properly. I'll show a fix with the docker example you provided and attempt and explanation.

```
FROM python:3.9-slim-bullseye
RUN apt update && \
  apt install -y git && \
  apt install -y build-essential
RUN apt install -y libpq-dev python3-dev
RUN DBT_PSYCOPG2_NAME=psycopg2 pip install --user dbt-postgres --no-binary dbt-postgres
CMD ["ls", "-la",  "/root/.local/lib/python3.9/site-packages"]
```

The difference here being `--no-binary dbt-postgres`. When dbt is installed using the provided python wheels (which is the default behavior) the code in `setup.py` won't be executed and so env vars won't affect the installation process. You can think of this as just placing a binary in the right place on your machine/image. By passing `--no-binary dbt-postgres`, this tells pip to install the package from source (almost equivalent to `python setup.py install` with the source code) which will execute code in `setup.py` and pick up env vars during the installation process.

I hope this resolves this issue, please confirm if it does! I'll close this issue and add instructions somewhere that makes sense as a follow up 👍

**Comment by rjrudin** [comment]
@kwigley That did the trick! Really appreciate the quick response. As you mentioned, I'll defer to you for closing the ticket so you can use it to keep track of adding the instructions as you see fit.

**Comment by kwigley** [comment]
Awesome, no problem
