### ISSUE TITLE
[CT-30] Add Support for Python 3.10

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#4562]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Officially support Python 3.10

**Comment by jtcohen6** [comment]
This will require us to resolve, at minimum, the mess of deprecation warnings emitted from the legacy logger, as described in https://github.com/dbt-labs/dbt-core/issues/4537

Going forward, we should seek to support each new python minor version, after its official release, in the subsequent minor version of dbt. (Do we need to support it in patch releases, too?)
