### ISSUE TITLE
[CT-37] [Bug] <Postgresql> Postgresql index creation improvement

### ISSUE THREAD

**Issue by Prajaktcs** [dbt-labs/dbt-core#4567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current behavior according to [this code](https://github.com/dbt-labs/dbt-core/blob/e943b9fc842535e958ef4fd0b8703adc91556bc6/core/dbt/include/global_project/macros/materializations/models/table/table.sql#L44-L47) is
- Create the `intermediate_relation` 
- Swap the tables with `target_relation` using a 3rd table
- Add index on the 3rd table

Switching steps 2 and 3 would help in avoiding locking the table.

We use postgresql as our transactional reporting layer against big tables. Locking them during index creation sometimes creates problems when our reporting tool tries to query the db at the same time.

### Expected Behavior

Moving [line](https://github.com/dbt-labs/dbt-core/blob/e943b9fc842535e958ef4fd0b8703adc91556bc6/core/dbt/include/global_project/macros/materializations/models/table/table.sql#L56) above this [line](https://github.com/dbt-labs/dbt-core/blob/e943b9fc842535e958ef4fd0b8703adc91556bc6/core/dbt/include/global_project/macros/materializations/models/table/table.sql#L49) will avoid locking on the table in turn avoiding slower queries which the dbt run is happening.

### Steps To Reproduce

Postgresql index creation without concurrently puts a shared lock on the table, even if its a transaction. A easy way to test this could be
```sql
begin;
Lock {table_name} in share mode;
select pg_sleep(30);
commit;

select * from {table_name};
```

### Environment

```markdown
- OS: debian slim bullseye
- Python: Python 3.9.2
- dbt:
installed version: 0.20.1
   latest version: 1.0.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 0.20.1
```

### What database are you using dbt with?

postgres

**Comment by nathaniel-may** [comment]
Hi @Prajaktcs! Thanks for filing this ticket. If I'm understanding correctly, it looks like your reporting tool can still read from the tables when dbt is running, but those queries are slower. What magnitude of a slowdown are you experiencing?

It sounds like the strategy you're proposing is to build the index on the empty table before populating it so the initial index build with the shared lock is quicker. From what I can tell, this sounds like a reasonable strategy. If you open a PR feel free to tag me as a reviewer and I'll make sure someone who works more closely with this part of the code takes a look at it too.
