### ISSUE TITLE
[CT-38] [Bug] --skip-profile-setup flag not respected

### ISSUE THREAD

**Issue by Andrew-Wichmann** [dbt-labs/dbt-core#4568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

dbt is running the interactive profile setup during init despite the flag being set on the command line.

### Expected Behavior

The init should not run the interactive profile setup

### Steps To Reproduce

1. With dbt 1.0.1
2. run `dbt init --skip-profile-setup project_name`

### Relevant log output

```shell
(.venv)  !  ◰³ .venv  ~/C/m/p/foo  ⎇ ~…  dbt init --skip-profile-setup tmp_dbt_proj                                                                                                4737ms < Thu 13 Jan 2022 12:17:52 PM CST
18:19:34  Running with dbt=1.0.1
18:19:34  Setting up your profile.
Which database would you like to use?
[1] snowflake

(Don't see the one you want? https://docs.getdbt.com/docs/available-adapters)

Enter a number: 
```

### Environment

```markdown
- OS: ubuntu 18.04
- Python: Python 3.8.5
- dbt: 1.0.1
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

Doesn't matter what database. This is during the init.

**Comment by Andrew-Wichmann** [comment]
:thinking: I can't replicate this issue now. Perhaps I was mistaken about using dbt v1.0.1

**Comment by varun-dc** [comment]
I feel like this flag, `-s`, is a bit inconsistent and this is a valid bug.
If someone is using dbt in a non-interactive manner, you'd think the `-s` flag would ensure the script isn't stuck in place waiting for some input from the user.

Reproduction on dbt 1.0.4
```
dbt init invalid-project-name -s
```
This will result in dbt showing a prompt to the user for a new project name. Whereas a more sensible thing to do is print an error message and exit.
