### ISSUE TITLE
[CT-41] [Feature] Allow additional Jinja filters (either built-in or user-definable)

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4571]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

When I go Googling for how to do something in Jinja, I often come across the Ansible documentation and get jealous. 

This has been a background hassle for a while, so I don't remember the specific ones I wanted - I think it was [intersections](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#selecting-from-sets-or-lists-set-theory) and [casting as bools](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#forcing-the-data-type). 

It would be ideal to either be able to create user-defined filters (maybe they could be provided in packages as well?) or if there's a tightly-defined set of ones that would be valuable to a broad cohort, I'd also be on board with just baking them into the main project. 

### Describe alternatives you've considered

Using macros 

### Who will this benefit?

People who would rather chain filters than use macros (yes I've seen #3113)

### Anything else?

Community Slack conversation that prompted me to write this up: https://getdbt.slack.com/archives/C2JRRQDTL/p1642105182233800

**Comment by gshank** [comment]
I think that there would be security issues with allowing random Python to be executed, but it seems really reasonable to expand the existing filters. Do you have other filters in mind, besides converting camelCase to snake_case?

**Comment by joellabes** [comment]
The ones that are interesting to me are set theory and casting bools (Ansible style, linked above) - I honestly think that case conversion is better handled by the existing exposure of the `re` module (potentially dbt utils could offer macros for snake case to camel case and vice versa). 

Assuming adding baked-in filters is a possibility, I'd probably open this issue up for discussion and link it in the community slack to see which things they'd find valuable

**Comment by joellabes** [comment]
Closing as a dupe of #1894
