### ISSUE TITLE
[CT-52] [Feature] Add prefix/suffix option for to seed table name

### ISSUE THREAD

**Issue by thomasaarholt** [dbt-labs/dbt-core#4580]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

dbt seeds are great for adding csv files to a database. They currently end with table name equal to the file name or the `alias` name specified in the configuration yaml file.

It would be nice to be able to prefix or suffix a string to seed table names in the yaml file. Imagine one has a directory `covid_statistics` with several csv files called e.g. `germany.csv`, `france.csv`, etc. It would be nice to have the seeds end up with table names `covid_germany` etc by providing a yaml option `prefix: covid_`, rather than renaming all files or specifying `alias: covid_<country_name>` for each country.

### Who will this benefit?

People with lots of csv seeds who may want to change their table names without renaming all files or specifying `alias` for each file.

### Are you interested in contributing this feature?

Sure, I could help out, perhaps by looking at alias.

**Comment by joellabes** [comment]
@thomasaarholt have you considered [overriding the generate_alias_name macro](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-aliases#generate_alias_name) instead? Something like this: 

```
{% macro generate_alias_name(custom_alias_name=none, node=none) %}
    {% if node.resource_type == 'seed' and node.original_file_path.startswith("seeds/covid/") %}

        covid_{{node.name}}

    {% else %}
    
        {{ node.name }}

    {% end %}
{% endmacro %}
```

This example is super-targeted to your use case; you might like to make it more generic (e.g. by extracting the directory path), or you could use the `meta` tag and access that.

**Comment by thomasaarholt** [comment]
Ah! I will admit to glancing over the `alias` documentation, since there was only a single reference to it at the top of the [seed configuration](https://docs.getdbt.com/reference/seed-configs) documentation - I just took it for what an alias normally means :)

Your suggestion will definitely suffice!
