### ISSUE TITLE
[CT-57] [Feature] Clarify what to do when getting a version incompatibility error

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4586]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

When trying to run dbt with a package that's incompatible due to require-dbt-version, the error message says "Check the requirements for the 'dbt_utils' package, or run dbt again with--no-version-check". 

I think "Check the requirements" is too ambiguous - we could direct them to check for an updated version of the package. 

### Describe alternatives you've considered

Extra for experts _could_ be to go and check the hub automatically (if it's a hosted package), but that would slow down the response due to the network overhead and potentially couple some things too close together 🤔 

### Who will this benefit?

People who are confused when upgrading dbt versions. Post 1.0 this should be less of an issue, but there's a lot of users who are still to update to 1.0 for the first time so there's still time for this to be relevant. 

### Are you interested in contributing this feature?

Definitely if it's just a phrasing change; maybe if we start futzing around with the hub.

**Comment by gshank** [comment]
A wording change for this message is very reasonable.

**Comment by leahwicz** [comment]
BAckport: https://github.com/dbt-labs/dbt-core/pull/4628
