### ISSUE TITLE
[CT-66] [Bug] dbt starter project's seed folder is still called data

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The starter project directory still has `data` as a folder, but the dbt_project.yml has changed it to `seeds`: 
https://github.com/dbt-labs/dbt-core/blob/11436fed45730cec392872cacfc511bbe7102ec3/core/dbt/include/starter_project/dbt_project.yml#L18

![image](https://user-images.githubusercontent.com/7335046/150054126-c187035a-cf4c-46ac-a6c7-d53b38652647.png)

### Expected Behavior

The folder to be called `seeds`.

### Steps To Reproduce

Run dbt init and follow the default interactive path
Add a seed, and a model that refs it 
Run dbt build

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by emmyoop** [comment]
Great catch @joellabes!

**Comment by leahwicz** [comment]
BAckport: https://github.com/dbt-labs/dbt-core/pull/4592
