### ISSUE TITLE
[CT-72] No docker for v1.0.1

### ISSUE THREAD

**Issue by vitalii-arcadia** [dbt-labs/dbt-core#4595]
This is more a question.
When new DBT dockers are published?
As of now, I see only https://hub.docker.com/r/fishtownanalytics/dbt/tags 1.0.0

**Comment by iknox-fa** [comment]
Hi @vitalii-arcadia!  Your question was well timed, we've just updated our docker images-- they're now available in [Github Packages](https://github.com/orgs/dbt-labs/packages?visibility=public), one per database adapter.

Our docs site should be updated fairly soon to reflect the change as well.

**Comment by vitalii-arcadia** [comment]
@iknox-fa thanks!!!
I see that dbt-core has next tags: latest,1.0.latest,1.0.1
But dbt-redshift tags : latest,1.0.latest,1.0.0
dbt-redshift does not have 1.0.1?

**Comment by iknox-fa** [comment]
@vitalii-arcadia That's correct.  

The version number of the images is based on the version of the data warehouse adapter, (with the exception of the `dbt-core` image which has no adapters installed).

What you probably want is the `dbt-redshift:1.0.0` image.  It will have the  v1.0.0 of the redshift adapter and the latest version of `dbt-core` that it plays nice with (in this case, it's 1.0.1)

**Comment by vitalii-arcadia** [comment]
@iknox-fa thanks will try that

**Comment by iknox-fa** [comment]
Closing the issue.  @vitalii-arcadia feel free to re-open it if you have any other issues finding the images.
