### ISSUE TITLE
[CT-85] [Bug] type "ltree" does not exist

### ISSUE THREAD

**Issue by fgamr** [dbt-labs/dbt-core#4612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running an ELT pipeline with Airbyte and for the transformation I am using DBT.
I have a query that uses ltree as type but it seems to be not working.
I tried to execute the query directly on Postgres but it works fine.

### Expected Behavior

I would expect to have the transformation running without any problem.

### Steps To Reproduce

I think any query using ltree should trigger the error.

### Relevant log output

```shell
type "ltree" does not exist
```

### Environment

```markdown
- image: fishtownanalytics/dbt:0.21.1
```

### What database are you using dbt with?

postgres

**Comment by gshank** [comment]
Could you share the model file that's getting this error? Do you know if the error message is coming from the database, jinja, python or dbt? If it's coming from the database, is it possible to get the SQL the database thinks it's running? I'm wondering if this query is filtered somehow in a way that changes the actual SQL.

**Comment by fgamr** [comment]
This is the log of dbt:
```sql
WITH RECURSIVE x AS ( 
    SELECT h1.ID,
        h1.ParentID, 
        h1.ID::varchar::ltree as HierarchyPath,
        1 as HierarchyLevel 
    FROM
        "postgres".dbo."hierarchy_src" h1 
    WHERE h1.ParentID is null

    UNION ALL

    SELECT h2.ID,
        h2.ParentID, 
        ltree_addtext(x.HierarchyPath, h2.ID::varchar) as HierarchyPath, 
        x.HierarchyLevel+1 as HierarchyLevel
    FROM
        x,
        "postgres".dbo."driver_hierarchy_src" h2
    WHERE x.ID = h2.ParentID
)
SELECT * FROM x
);

2022-01-22 15:26:06.019143 (Thread-23): Postgres error: type "ltree" does not exist
LINE 12: ...J_DESC, h1.CLS_DESC, h1.CAT_DESC, h1.ID::varchar::ltree as H...

```
As you can see in the error log there are more fields selected before "h1.ID::varchar::ltree". I removed those from the query for the sake of readability.
Copy-pasting the query directly on the database gives me no error. Obviously, I had to run on the database `CREATE EXTENSION IF NOT EXISTS ltree;` one time to enable ltree. After this, any connection using the dbo schema should have ltree already enabled.
**Anyway, I was able to fix this problem by adding before ltree and ltree_addtext the dbo schema.**
So, I refactored it like this:
```sql
WITH RECURSIVE x AS ( 
    SELECT h1.ID,
        h1.ParentID, 
        h1.ID::varchar::dbo.ltree as HierarchyPath,
        1 as HierarchyLevel 
    FROM
        "postgres".dbo."hierarchy_src" h1 
    WHERE h1.ParentID is null

    UNION ALL

    SELECT h2.ID,
        h2.ParentID, 
        dbo.ltree_addtext(x.HierarchyPath, h2.ID::varchar) as HierarchyPath, 
        x.HierarchyLevel+1 as HierarchyLevel
    FROM
        x,
        "postgres".dbo."driver_hierarchy_src" h2
    WHERE x.ID = h2.ParentID
)
SELECT * FROM x
);
```
I didn't thought I had to reference the schema because it was already running on dbo. Maybe it could be related to the connection handling on DBT or Airbyte.
I hope this could help.
Thanks!
