### ISSUE TITLE
[CT-92] [Feature] MergeBehavior extending for adapters by default

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-core#4622]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

in reference to [#105](https://github.com/dbt-labs/dbt-bigquery/issues/105) in `dbt-bigquery`

questions @jtcohen6 brought up in regards to this:
- Can adapter-specific configs be defined with non-default MergeBehavior?
- Could we find a way to let users declare/override the MergeBehavior for a specific config in a specific model?

Some syntax work that has been worked on [Custom merge behavior for configs](https://github.com/dbt-labs/dbt-core/issues/4108)

### Describe alternatives you've considered

Current strategy would be duplication of config labels before clobbering in case of bigquery and depending on size of project could be very heavy lift and unclean process

### Who will this benefit?

Users who need to be able to change default behavior of the adapter configs to stop things like clobbering of some configs ie. big-query multiple labels.

organization members who don't directly interface with dbt themselves but work from the warehouse side can rely on not losing values and know tables/datasets are organized correctly.

### Are you interested in contributing this feature?

Yes would love to work with language team on this

**Comment by nathaniel-may** [comment]
estimation:
- lots of questions around what our options are
- unknown unknowns around all ways merge behavior is used in core today
- unknowns around best ways to leverage the adapter interface
- recommendation: 3 day spike.
