### ISSUE TITLE
[CT-101] Add `Black` formatter to Core

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#4635]
We would like to add the `Black` formatter to dbt-core:
https://pypi.org/project/black/

This will standardize our code base across the board going forward

**Comment by kwigley** [comment]
more info here as well https://github.com/dbt-labs/dbt-core/issues/3195!

**Comment by leahwicz** [comment]
I'm going to close #3195 as a dupe but @iknox-fa there is good stuff in there so be sure to take a look
