### ISSUE TITLE
[CT-102] Use pre-commit to enforce `Black` and `flake8`

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#4636]
To make it easier for contributors to stick to the formatting guidelines for the repo, we will use `pre-commit` to help. This will let contributors know about formatting errors before committing their work locally. More info here on the integration and details: 
https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

**Comment by kwigley** [comment]
yes yes yes! I wrote about this here as well https://github.com/dbt-labs/dbt-core/issues/3196

**Comment by leahwicz** [comment]
I missed these issues so just closing this out in favor of the other
