### ISSUE TITLE
[CT-103] Add support for sha1 to package dependancies

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#4637]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Add an optional `sha1` field to package definitions.  If it exists, verify the downloaded package matches.

More details to come.

### Describe alternatives you've considered

Not doing it.  

### Who will this benefit?

Anyone using packages.  Will allow more informative error messages when things go sideways.

### Anything else?

This will help catch corrupt files as in #4579.  #4205 is also proposing adding this functionality with the new download type.

**Comment by jtcohen6** [comment]
For Hub-hosted packages, the Hub API includes/returns both:
- the URL of the tarball to be downloaded
- the `sha1` expected for that download

[Example](https://github.com/dbt-labs/hub.getdbt.com/blob/222ca090785388a57400bb6d62b5aa29d6abb3d5/data/packages/dbt-labs/dbt_utils/versions/0.8.0.json#L16):
```json
    "downloads": {
        "tarball": "https://codeload.github.com/dbt-labs/dbt-utils/tar.gz/0.8.0",
        "format": "tgz",
        "sha1": "9fb457bcec7b19a9e51241742cde64a01eb2d77e"
    }
```

Could we add that check somewhere [here](https://github.com/dbt-labs/dbt-core/blob/f3735187a620e3a40ee01b3fa04be191de2b5901/core/dbt/deps/registry.py#L61-L74), when we install registry packages? Then we'd benefit from the check, without users having to specify it in `packages.yml`
