### ISSUE TITLE
[CT-106] [Bug] Docker image build process is broken

### ISSUE THREAD

**Issue by korjavin** [dbt-labs/dbt-core#4638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On building I get:

```
ERROR: Could not find a version that satisfies the requirement dbt-postgres (unavailable) (from versions: 0.13.0a1, 0.13.0a2, 0.13.0rc1, 0.13.0, 0.13.1a1, 0.13.1a2, 0.13.1, 0.14.0a1, 0.14.0a2, 0.14.0rc1, 0.14.0, 0.14.1a1, 0.14.1rc1, 0.14.1rc2, 0.14.1, 0.14.2, 0.14.3rc1, 0.14.3, 0.14.4, 0.15.0b1, 0.15.0b2, 0.15.0b3, 0.15.0rc1, 0.15.0rc2, 0.15.0, 0.15.1rc1, 0.15.1rc2, 0.15.1, 0.15.2, 0.15.3rc1, 0.15.3, 0.16.0b1, 0.16.0b2, 0.16.0b3, 0.16.0rc1, 0.16.0rc2, 0.16.0rc3, 0.16.0rc4, 0.16.0, 0.16.1rc1, 0.16.1, 0.17.0b1, 0.17.0b2, 0.17.0rc1, 0.17.0rc2, 0.17.0rc3, 0.17.0rc4, 0.17.0, 0.17.1rc1, 0.17.1rc2, 0.17.1rc3, 0.17.1rc4, 0.17.1, 0.17.2b1, 0.17.2rc1, 0.17.2, 0.18.0b1, 0.18.0b2, 0.18.0rc1, 0.18.0rc2, 0.18.0, 0.18.1b1, 0.18.1b2, 0.18.1b3, 0.18.1rc1, 0.18.1, 0.18.2rc1, 0.18.2, 0.19.0b1, 0.19.0rc1, 0.19.0rc2, 0.19.0rc3, 0.19.0, 0.19.1b2, 0.19.1rc1, 0.19.1rc2, 0.19.1, 0.19.2rc1, 0.19.2rc2, 0.19.2, 0.20.0b1, 0.20.0rc1, 0.20.0rc2, 0.20.0, 0.20.1rc1, 0.20.1, 0.20.2rc1, 0.20.2rc2, 0.20.2, 0.21.0b1, 0.21.0b2, 0.21.0rc1, 0.21.0rc2, 0.21.0, 0.21.1rc1, 0.21.1rc2, 0.21.1, 1.0.0b1, 1.0.0b2, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 1.0.0, 1.0.1rc1, 1.0.1)
ERROR: No matching distribution found for dbt-postgres (unavailable)
```

### Expected Behavior

I'd expect to have docker image

### Steps To Reproduce

1. Clone fresh git repo
2. docker build -t tmp -f docker/Dockerfile

### Relevant log output

```shell
[3/9] STEP 2/2: RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_postgres_ref}#egg=dbt-postgres&subdirectory=plugins/postgres"
Collecting dbt-postgres
  Cloning https://github.com/dbt-labs/ to /tmp/pip-install-epfngjko/dbt-postgres_8d7eb22fbdbe4b06bf3a20348f72b0c7
  Running command git clone --filter=blob:none -q https://github.com/dbt-labs/ /tmp/pip-install-epfngjko/dbt-postgres_8d7eb22fbdbe4b06bf3a20348f72b0c7
  remote: Not Found
  fatal: repository 'https://github.com/dbt-labs/' not found
WARNING: Discarding git+https://github.com/dbt-labs/#egg=dbt-postgres&subdirectory=plugins/postgres. Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/dbt-labs/ /tmp/pip-install-epfngjko/dbt-postgres_8d7eb22fbdbe4b06bf3a20348f72b0c7 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement dbt-postgres (unavailable) (from versions: 0.13.0a1, 0.13.0a2, 0.13.0rc1, 0.13.0, 0.13.1a1, 0.13.1a2, 0.13.1, 0.14.0a1, 0.14.0a2, 0.14.0rc1, 0.14.0, 0.14.1a1, 0.14.1rc1, 0.14.1rc2, 0.14.1, 0.14.2, 0.14.3rc1, 0.14.3, 0.14.4, 0.15.0b1, 0.15.0b2, 0.15.0b3, 0.15.0rc1, 0.15.0rc2, 0.15.0, 0.15.1rc1, 0.15.1rc2, 0.15.1, 0.15.2, 0.15.3rc1, 0.15.3, 0.16.0b1, 0.16.0b2, 0.16.0b3, 0.16.0rc1, 0.16.0rc2, 0.16.0rc3, 0.16.0rc4, 0.16.0, 0.16.1rc1, 0.16.1, 0.17.0b1, 0.17.0b2, 0.17.0rc1, 0.17.0rc2, 0.17.0rc3, 0.17.0rc4, 0.17.0, 0.17.1rc1, 0.17.1rc2, 0.17.1rc3, 0.17.1rc4, 0.17.1, 0.17.2b1, 0.17.2rc1, 0.17.2, 0.18.0b1, 0.18.0b2, 0.18.0rc1, 0.18.0rc2, 0.18.0, 0.18.1b1, 0.18.1b2, 0.18.1b3, 0.18.1rc1, 0.18.1, 0.18.2rc1, 0.18.2, 0.19.0b1, 0.19.0rc1, 0.19.0rc2, 0.19.0rc3, 0.19.0, 0.19.1b2, 0.19.1rc1, 0.19.1rc2, 0.19.1, 0.19.2rc1, 0.19.2rc2, 0.19.2, 0.20.0b1, 0.20.0rc1, 0.20.0rc2, 0.20.0, 0.20.1rc1, 0.20.1, 0.20.2rc1, 0.20.2rc2, 0.20.2, 0.21.0b1, 0.21.0b2, 0.21.0rc1, 0.21.0rc2, 0.21.0, 0.21.1rc1, 0.21.1rc2, 0.21.1, 1.0.0b1, 1.0.0b2, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 1.0.0, 1.0.1rc1, 1.0.1)
ERROR: No matching distribution found for dbt-postgres (unavailable)
error building at STEP "RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_postgres_ref}#egg=dbt-postgres&subdirectory=plugins/postgres"": error while running runtime: exit status 1
```
```


### Environment

```markdown
- OS: linux
- Python: -
- dbt: main
```

**Comment by iknox-fa** [comment]
Hi @korjavin , sorry you're having some issues with the docker image.

Here's a few things that might help sort this out.

- The command provided `docker build -t tmp -f docker/Dockerfile` isn't a valid docker command because it lacks a path.  If you want to build the full image you're probably looking for something like this: `docker build -t <tag_name> path/to/folder/that/contains/the/Dockerfile`. The `-f` flag is meant to be used when you want to break the Dockerfiles-must-be-named-`Dockerfile` naming convention.

- While I wasn't able to reproduce your error, the log message makes it look as if the build arg `dbt_postgres_ref` has been somehow unset or never set in the first place.  That's pretty odd given that it's [hard coded directly into the dockerfile](https://github.com/dbt-labs/dbt-core/blob/13571435a319d6237bfc414ef15f27e23f0729db/docker/Dockerfile#L18).  Is there by chance some way that could have been broken in your environment?

**Comment by thenaturalist** [comment]
Hi @iknox-fa, I experienced the same issue as described above and it seems logical to me. 

As far as I am aware, `ARG`s are only persisted within the scope of the preceding `FROM` statement, unless an `ARG` is referenced in a `FROM` line (i.e. version number). See also [this](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact).

https://github.com/dbt-labs/dbt-core/blob/aafa1c7f473988bb1771b7cf5b120efab44a8144/docker/Dockerfile#L59 

From this line onwards, all `ARG`s declared above are out of scope again. 

This works for me:

```
##
# dbt-core
##
FROM base as dbt-core
ARG dbt_core_ref=dbt-core@v1.0.0

RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_core_ref}#egg=dbt-core&subdirectory=core"

##
# dbt-snowflake
##
FROM base as dbt-snowflake
ARG dbt_snowflake_ref=dbt-snowflake@v1.0.0

RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_snowflake_ref}#egg=dbt-snowflake"```

**Comment by Khouderchah-Alex** [comment]
+1. @iknox-fa, what tool are you using for docker builds (e.g. Engine, Desktop*, podman, etc)?
I'm reproducing this issue on Docker Engine 20.10.12.

From the ref [0]:
> An ARG instruction goes out of scope at the end of the build stage where it was defined. To use an arg in multiple stages, each stage must include the ARG instruction.

Same as with @thenaturalist, just moving the ARG lines into their respective stages worked for me, since the base stage wasn't using those.

[0] - https://docs.docker.com/engine/reference/builder/#scope

**Comment by iknox-fa** [comment]
@Khouderchah-Alex Thanks for chiming in and sorry for the delayed reply.  I've been doing all of my testing in Docker Desktop v 20.10.8 which should be functionally almost identical to Docker Engine 20.10.12.  

Can you provide the exact docker build command and whatever pertinent env vars you're using that causes the error?

**Comment by Khouderchah-Alex** [comment]
No special vars, just a plain `docker build -t $TAG .`.

Given the documentation about ARG scoping, I'm tempted to say the bug is with Docker Desktop rather than Engine, but I'm not familiar enough with the project to say for sure.

**Comment by iknox** [comment]
@korjavin Can you try the following? `docker build -t $TAG --target dbt-all .`  The docker file was only intended to be used in conjunction with a `target` specified.  This is documented, but sadly the PR for said docs has been held up and it's on the site yet.

Additionally, I've tested this in linux, windows, and macos and I still can't reproduce it.. even doing it without a tag creates a valid image (although it forces docker to do a TON of extra work).

**Comment by korjavin** [comment]
Trying:

```
$git clone ...
$cd <root>
$docker build -t tmp --target dbt-all ./docker/  

 <skip a lot>
 
 Step 19/39 : RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_core_ref}#egg=dbt-core&subdirectory=core"
 ---> Running in d384693f9402
Collecting dbt-core
  Cloning https://github.com/dbt-labs/ to /tmp/pip-install-h42yrkxl/dbt-core_fa3e85a74e6b4072ba794ea699793158
  Running command git clone --filter=blob:none --quiet https://github.com/dbt-labs/ /tmp/pip-install-h42yrkxl/dbt-core_fa3e85a74e6b4072ba794ea699793158
  remote: Not Found
  fatal: repository 'https://github.com/dbt-labs/' not found
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/dbt-labs/ /tmp/pip-install-h42yrkxl/dbt-core_fa3e85a74e6b4072ba794ea699793158 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/dbt-labs/ /tmp/pip-install-h42yrkxl/dbt-core_fa3e85a74e6b4072ba794ea699793158 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by iknox-fa** [comment]
*sigh*. Well, I'm out of ideas here.  I'll see if I can wrangle some better docker types to help out tomorrow.

**Comment by josejcardenas** [comment]
I think I found the error. Is Dockerfile config. Due Docker create a new build stage, isn't able to keep the ARG variables after a FROM statement. So I've done is declare every variable again before after every RUN statement. Dockerfile as below:

`##
#  Generic dockerfile for dbt image building.
#  See README for operational details
##

# Top level build args
ARG build_for=linux/amd64

##
# base image (abstract)
##
FROM --platform=$build_for python:3.10.3-slim-bullseye as base

# N.B. The refs updated automagically every release via bumpversion
# N.B. dbt-postgres is currently found in the core codebase so a value of dbt-core@<some_version> is correct

ARG dbt_core_ref=dbt-core@v1.2.0a1
ARG dbt_postgres_ref=dbt-core@v1.2.0a1
ARG dbt_redshift_ref=dbt-redshift@v1.0.0
ARG dbt_bigquery_ref=dbt-bigquery@v1.0.0
ARG dbt_snowflake_ref=dbt-snowflake@v1.0.0
ARG dbt_spark_ref=dbt-spark@v1.0.0
# special case args
ARG dbt_spark_version=all
ARG dbt_third_party

# System setup
RUN apt-get update \
  && apt-get dist-upgrade -y \
  && apt-get install -y --no-install-recommends \
    git \
    ssh-client \
    software-properties-common \
    make \
    build-essential \
    ca-certificates \
    libpq-dev \
  && apt-get clean \
  && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*

# Env vars
ENV PYTHONIOENCODING=utf-8
ENV LANG=C.UTF-8

# Update python
RUN python -m pip install --upgrade pip setuptools wheel --no-cache-dir

# Set docker basics
WORKDIR /usr/app/dbt/
VOLUME /usr/app
ENTRYPOINT ["dbt"]

##
# dbt-core
##
FROM base as dbt-core
ARG dbt_core_ref=dbt-core@v1.2.0a1
RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_core_ref}#egg=dbt-core&subdirectory=core"

##
# dbt-postgres
##a
FROM base as dbt-postgres
ARG dbt_postgres_ref=dbt-core@v1.2.0a1
RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_postgres_ref}#egg=dbt-postgres&subdirectory=plugins/postgres"


##
# dbt-redshift
##
FROM base as dbt-redshift
ARG dbt_redshift_ref=dbt-redshift@v1.0.0
RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_redshift_ref}#egg=dbt-redshift"


##
# dbt-bigquery
##
FROM base as dbt-bigquery
ARG dbt_bigquery_ref=dbt-bigquery@v1.0.0
RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_bigquery_ref}#egg=dbt-bigquery"


##
# dbt-snowflake
##
FROM base as dbt-snowflake
ARG dbt_snowflake_ref=dbt-snowflake@v1.0.0
RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_snowflake_ref}#egg=dbt-snowflake"

##
# dbt-spark
##
FROM base as dbt-spark
RUN apt-get update \
  && apt-get dist-upgrade -y \
  && apt-get install -y --no-install-recommends \
    python-dev \
    libsasl2-dev \
    gcc \
    unixodbc-dev \
  && apt-get clean \
  && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*

ARG dbt_spark_ref=dbt-spark@v1.0.0
ARG dbt_spark_version=all
RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_spark_ref}#egg=dbt-spark[${dbt_spark_version}]"


##
# dbt-third-party
##a
FROM dbt-core as dbt-third-party
ARG dbt_third_party
RUN python -m pip install --no-cache-dir "${dbt_third_party}"

##
# dbt-all
##
FROM base as dbt-all
RUN apt-get update \
  && apt-get dist-upgrade -y \
  && apt-get install -y --no-install-recommends \
    python-dev \
    libsasl2-dev \
    gcc \
    unixodbc-dev \
  && apt-get clean \
  && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*
  ARG dbt_redshift_ref=dbt-redshift@v1.0.0
  RUN python -m pip install --no-cache "git+https://github.com/dbt-labs/${dbt_redshift_ref}#egg=dbt-redshift"
  ARG dbt_bigquery_ref=dbt-bigquery@v1.0.0
  RUN python -m pip install --no-cache "git+https://github.com/dbt-labs/${dbt_bigquery_ref}#egg=dbt-bigquery"
  ARG dbt_snowflake_ref=dbt-snowflake@v1.0.0
  RUN python -m pip install --no-cache "git+https://github.com/dbt-labs/${dbt_snowflake_ref}#egg=dbt-snowflake"
  ARG dbt_spark_ref=dbt-spark@v1.0.0
  ARG dbt_spark_version=all
  RUN python -m pip install --no-cache "git+https://github.com/dbt-labs/${dbt_spark_ref}#egg=dbt-spark[${dbt_spark_version}]"
  ARG dbt_postgres_ref=dbt-core@v1.2.0a1
  RUN python -m pip install --no-cache "git+https://github.com/dbt-labs/${dbt_postgres_ref}#egg=dbt-postgres&subdirectory=plugins/postgres"
`

**Comment by inntran** [comment]
I had run into the same issue.
I guess @iknox-fa has "BuildKit" enabled, and that allows extra feature in Dockerfile, like reusing ARG across multiple stages, skipping not-required stages.

I have a fix to Dockerfile, but I don't want to sign CLA, so I post it here.
1. Move the "base" image FROM statement after [`ARG dbt_third_party`](https://github.com/dbt-labs/dbt-core/blob/main/docker/Dockerfile#L25).
2. Insert `ARG dbt_<component>_ref` before each RUN statement referencing that argument.
3. Insert all seven `ARG dbt_<component>_ref` in "dbt-all" target.
4. Move `dbt-third-party` target to the end of Dockerfile, so it won't be called unless specified in the command line.

Note: an "`ARG`" after second FROM without values will get the default value, see reference 1.

The test.sh also need a fix to work with the latest Dockerfile.
1. Either bump the version to latest 1.3.0b1
2. or remove those version specific tests.

With the fixes above, this Dockerfile will work with both docker and podman, BuildKit(env variable `DOCKER_BUILDKIT=1`) is no longer needed.

References:
1. [Understand how ARG and FROM interact](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact), see "An ARG declared before a FROM is outside of a build stage, so it can’t be used in any instruction after a FROM. To use the default value of an ARG declared before the first FROM use an ARG instruction without a value inside of a build stage"
3. [Containerfile(5) man page](https://github.com/containers/common/blob/main/docs/Containerfile.5.md), see "Note that a second FROM in a Containerfile sets the values associated with an Arg variable to nil and they must be reset if they are to be used later in the Containerfile"
4. [What is Podman?](https://docs.podman.io/en/latest/) [Podman](http://podman.io/) is a daemonless, open source, Linux native tool designed to make it easy to find, run, build, share and deploy applications using Open Containers Initiative ([OCI](https://www.opencontainers.org/)) [Containers](https://developers.redhat.com/blog/2018/02/22/container-terminology-practical-introduction/#h.j2uq93kgxe0e) and [Container Images](https://developers.redhat.com/blog/2018/02/22/container-terminology-practical-introduction/#h.dqlu6589ootw).

**Comment by thenaturalist** [comment]
@iknox-fa cc @iknox any update on this?

I think the issue has been scoped out, the root cause found. 

Could either a) the Dockerfile be updated or b) the Docs be ammended to make it clear that Buildkit needs to be enabled?

**Comment by PIMandatory** [comment]
> Hi @iknox-fa, I experienced the same issue as described above and it seems logical to me.
> 
> As far as I am aware, `ARG`s are only persisted within the scope of the preceding `FROM` statement, unless an `ARG` is referenced in a `FROM` line (i.e. version number). See also [this](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact).
> 
> https://github.com/dbt-labs/dbt-core/blob/aafa1c7f473988bb1771b7cf5b120efab44a8144/docker/Dockerfile#L59
> 
> From this line onwards, all `ARG`s declared above are out of scope again.
> 
> This works for me:
> 
> ```
> ##
> # dbt-core
> ##
> FROM base as dbt-core
> ARG dbt_core_ref=dbt-core@v1.0.0
> 
> RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_core_ref}#egg=dbt-core&subdirectory=core"
> 
> ##
> # dbt-snowflake
> ##
> FROM base as dbt-snowflake
> ARG dbt_snowflake_ref=dbt-snowflake@v1.0.0
> 
> RUN python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_snowflake_ref}#egg=dbt-snowflake"```
> ```

Hello,

I had the same issue yesterday using your Dockerfile structure. 
I have resolved the issue using the solution provided by @thenaturalist (moving arguments after the "FROM base" definition line)

Regards

**Comment by aliavni** [comment]
I have a PR to fix this issue https://github.com/dbt-labs/dbt-core/pull/9590
