### ISSUE TITLE
[CT-109] [Feature] Show a hint in the error message when trying to access the graph whenever execute = False

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4641]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Today in "Joel wants better error messages": `execute`!

This is a common tripwire - I trip over it myself about [once](https://getdbt.slack.com/archives/C0VLZPLAE/p1611289944020500) [a year](https://dbt-labs.slack.com/archives/C017GDLAF7D/p1639737456261600?thread_ts=1639699135.259500&cid=C017GDLAF7D). 

Is there anything we can do when someone tries to do something that works in execute mode, but not during the first runthrough? The first thread I linked above was particularly insidious because when I tried to debug it by outputting inside of {{ curly braces }} it worked correctly

### Who will this benefit?

People writing their own introspective queries, or code that depends on the graph object (likely to become more popular, especially to access metric definitions etc)

**Comment by joellabes** [comment]
I'm closing out comments on the metrics package's PR and didn't want this to get lost: 

> jtcohen6 yesterday 
> 
> Re: [this](https://github.com/dbt-labs/dbt_metrics/blob/main/macros/metric.sql#L20-L39), and [this](https://github.com/dbt-labs/dbt_metrics/blob/main/macros/get_metric_relation.sql#L3), and dbt-labs/dbt-core#4641: I think we might just want to add some new context-member methods like:
> 
> get_metric()
> get_exposure()
> get_node()
> 
> Crucially, they'd:
> 
> take the node name (or unique_id?) as an argument, and all they'd do is return the manifest entry for that node/metric/exposure, so you don't need any graph.things.values() looping or selectattr cleverness
> raise an error or return nothing at parse time (execute = False)
> 
> (cc @emmyoop — I see you assigned yourself to 4641, and we were just talking about context methods earlier)

**Comment by joellabes** [comment]
> If you're including a metric calculation in a model [...] you can actually get it working by explicitly specifying the underlying model reference. Does that even feel so wrong?

I think it's reasonable for now! Bonus: by it being a bit of a pain in the butt, it may help to discourage people from assuming it's the _default_ way to use the metrics package 😂 

In the medium term, yeah I think we'll need to be able to calculate metrics on top of one another, but I don't know that it has to be materialised as a model in the middle. (Although given how grumpy Redshift gets when you nest too many CTEs deep, it might be important to have a table as a stabilising point in the middle).

**Comment by jtcohen6** [comment]
> **Note:** Still need to confirm the behavior when running via new `dbt-server`. If that requires a manually commented `ref()`, it's no good, and we should find another way.

I haven't been able to confirm this by testing locally, but by reading through the codebase, I'm pretty sure this would be an issue. I've also convinced myself that it's a _good_ thing the manual `ref()` is required in models (DAG nodes). So the question is just, how to avoid raising this error when using the [`compile_sql` + `execute_sql` methods](https://github.com/dbt-labs/dbt-core/blob/c251dae75eaf7ee5d0e21b54d27701722905e96b/core/dbt/lib.py#L101-L115) on a bundle of arbitrary SQL, i.e. a metrics query.

To that end, I've opened https://github.com/dbt-labs/dbt-core/issues/4851. We'll need to make that change (or one like it) before we can implement the good version of `get_metric`.

**Comment by jtcohen6** [comment]
The motivating ask here (metrics) will be resolved by #5027. Even though that doesn't resolve the initial ask per se—raising an error if `graph` is accessed at parse time—I think it's less likely to come up now that we don't need as many hijinks in the metrics package. Closing for now.
