### ISSUE TITLE
[CT-110] [Feature] Ability to modify which variables are checked when partial parsing

### ISSUE THREAD

**Issue by AntonAiven** [dbt-labs/dbt-core#4642]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Partial parsing could be configured to not check if environment variables changes. We compile dbt in Github actions and we run it on a schedule in kubernetes. We change the authentication for dbt based on the environment, and do this through environment variables. This worked well in v0.21 because in that version dbt didin't check for changed environment variables, but since v1.0 it does, so now we need to compile each time we run. 

### Who will this benefit?

Anyone who runs dbt in multiple environments

**Comment by gshank** [comment]
Thanks for reporting this!  I assume that you have env_vars in your profile? If that's the case, then the intention was that env_vars starting with DBT_ENV_SECRET would not be used for setting off partial parsing, but we inadvertently included them. We'll be fixing this bug in the next point release.

Please let me know if using secret env_vars (when working correctly) would not meet your needs.

**Comment by gshank** [comment]
The place that needs to be fixed is in core/dbt/context/secret.py, in the env_var method. Where it saved the return_value in self.env_vars, we want to skip saving if the env_var if it starts with the SECRET_ENV_PREFIX.

**Comment by jtcohen6** [comment]
Going to open two issues as follow-ons to this one:
- Fix the SecretContext to avoid saving secrets (for v1.0.2)
- Update docs to mention that changes to secrets used in `profiles.yml` do _not_ trigger full re-parses, unlike other env vars used in the active profile

**Comment by AntonAiven** [comment]
> The place that needs to be fixed is in core/dbt/context/secret.py, in the env_var method. Where it saved the return_value in self.env_vars, we want to skip saving if the env_var if it starts with the SECRET_ENV_PREFIX.



> Thanks for reporting this! I assume that you have env_vars in your profile? If that's the case, then the intention was that env_vars starting with DBT_ENV_SECRET would not be used for setting off partial parsing, but we inadvertently included them. We'll be fixing this bug in the next point release.
> 
> Please let me know if using secret env_vars (when working correctly) would not meet your needs.

Something like this would definitely fix it for us!

**Comment by karunpoudel** [comment]
I second this feature.

We have separate snowflake account for each environment. It would be nice if we could parse and build the image once, and run it in different environment without having to reparse. This would mean some sort of `config` options to ignore change in variables used in profiles.yml.

We are using dynamic secrets so the username and password can change between each dbt run. If variables with DBT_ENV_SECRET is ignored for partial parse then it should fix for us.
