### ISSUE TITLE
[Bug] `--exclude` doesn't work when `--defer` flag is provided

### ISSUE THREAD

**Issue by AndrewCanva** [dbt-labs/dbt-core#4645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

it runs the model in `--exclude` while it has `--defer` in the dbt command whether the model is included in `--select` or not.

### Expected Behavior

dbt should exclude the model specified after `--exclude` whether it is included in `--select` when `--defer` is provided. In other words, `--exclude` overrides `--select`.

### Steps To Reproduce

run a project with `dbt run --select state:modified+1 --exclude m --state /tmp/tmp.daf --defer --target tgt`

### Relevant log output

```shell
same as the usual dbt logs but runs the excluded ones
```

### Environment

```markdown
- OS: ubuntu 20.04
- Python: 3.7.9
- dbt: 1.0.1
```

### What database are you using dbt with?

redshift

**Comment by AndrewCanva** [comment]
> Hey @AndrewCanva, thanks for opening this, and sorry for getting back to you late. I looked up the test case and seems like we don't have test coverage of mixing `--defer` and `--exclude` together. To get more information related to this, I have two questions.
> 
> * Does the `--exclude` work as expected in the case `--defer` is not provided?
> * are the model/s in `--exclude` exists in the `--state /tmp/tmp.daf`?
> 
> We probably should exclude those model/s regarding the answer to the questions, but more information is always helpful. Thanks!


- `--exclude` works when `--defer is not provided
- the model in `--exclude` is in the `--state /tmp/tmp.daf`

**Comment by AndrewCanva** [comment]
@jtcohen6 ah, I know why it doesn't exclude the model when I run it. it is not related to defer, what I did in a script is
```
local args="--exclude m"
dbt run --select state:modified+1 "${args}" --state /tmp/tmp.daf --defer --target tgt
```

when I remove the double quotes, it works fine
```
local args="--exclude m"
dbt run --select state:modified+1 ${args} --state /tmp/tmp.daf --defer --target tgt
```
what's confusing is that dbt ignore the `--exclude` and takes "${args}" as `m`.

that's probably because of argparse, I will close it if you don't regard it as a bug.

**Comment by jtcohen6** [comment]
Ahh, that's a weird one all right. We're talking about refactoring the dbt CLI (https://github.com/dbt-labs/dbt-core/issues/4179, https://github.com/dbt-labs/dbt-core/issues/4475). That work might include moving away from `argparse`, given some of its shortcomings. I think we should close the issue, and I'm happy to have it linked from there for visibility.
