### ISSUE TITLE
[CT-160] Create/use `pyproject.toml`

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#4674]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Given that:
* We should move to using [PEP-518](https://www.python.org/dev/peps/pep-0518/) compliant build tool specification
* People might [like to use Poetry](https://github.com/dbt-labs/dbt-core/issues/4446) while developing dbt
* SetupTools is .... not great.

We should consider utilizing a pyproject.toml file to enable all of those.

### Describe alternatives you've considered

There aren't any that I've discovered

### Who will this benefit?

Devs across the board

**Comment by jtcohen6** [comment]
@lostmygithubaccount Agree - we should still do this! In `dbt-core` and our adapter repos, too

**Comment by leahwicz** [comment]
Let's get an estimation for this work for just `dbt-core` to start

**Comment by iknox-fa** [comment]
Skipped pointing on 9/22/22 BLG-- Spike needed to determine:
* Will this break docker builds for cloud?
* Are we doing things in `setup.py` that can't be done with pyproject.toml?

**Comment by iknox-fa** [comment]
Spike still needed.  BLG 9/12/22

**Comment by iknox-fa** [comment]
Closing as duplicate of https://github.com/dbt-labs/dbt-core/issues/5696
