### ISSUE TITLE
[CT-168] Cache objects for selected resources only?

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4688]
### Background

Should we cache everything dbt cares about? Or try to cache objects relevant only to resources that are selected to run? This is an increasingly important consideration as folks move to:
- Execute smaller sub-DAGs within ever-larger projects
- Manage their slice of a multi-package dbt deployment 

The intent of the relation cache is to speed up performance, after all. If it's not serving that purpose, in its current unadaptive form, then we should change its behavior.

### Details

We know the set of selected resources at the time when we populate the adapter cache. We only _create_ schemas (if they do not yet exist) for objects that are selected. Should we also limit the reach of our metadata queries, to only introspect the schemas we care about?

https://github.com/dbt-labs/dbt-core/blob/a588607ec6546de441812e215fbbf4e9ff20101b/core/dbt/task/run.py#L457-L458

Should we go one step further, and use filters/wildcards to only cache the _objects_ we care about? This seems necessary on `dbt-spark` (issue linked below.)

### Risks

- The cache has made us "greedy" when it comes to really simple metadata lookups. What if, over the course of running a few models, we end up spending more time in one-off lookup queries (due to cache misses) than we saved at the start, by skipping one batch metadata query that seemed irrelevant?
- `--defer` depends on being able to access cache information about resources that are not selected (context in #2946):

https://github.com/dbt-labs/dbt-core/blob/a588607ec6546de441812e215fbbf4e9ff20101b/core/dbt/contracts/graph/manifest.py#L952-L955)

### Questions
- If dbt misses something in its cache, are we liable to return _slow_ or _incorrect_ results? The answer significantly changes the stakes of such a change
- Would we want cache behavior to vary based on  `--defer` behavior? 

### Related
- https://github.com/dbt-labs/dbt-snowflake/issues/83
- https://github.com/dbt-labs/dbt-bigquery/issues/104
- https://github.com/dbt-labs/dbt-core/issues/2673
- https://github.com/dbt-labs/dbt-spark/issues/228

**Comment by karunpoudel** [comment]
Hi, we are trying to run individual model at a time from Apache Airflow (by parsing the manifest.json). We have a common project where multiple teams are working. So there are about 30 schemas in total in various databases (Snowflake). When running single model, it takes 2 minutes just to run `show terse objects` in various schemas while the main query for the model completes in 9 second. This is very inefficient. It should have been sufficient to run `show terse` on the target schema of the particular model only.

I was hoping if there could be a command line or config parameter to change this default behavior.

**Comment by boxysean** [comment]
I spoke with a dbt user today who is trying to reference the data type of a column during a post-hook macro. They observed that, if the data type of a column changes between two successive runs (say from a TEXT to a NUMBER), then the post-hook macro that references the data type will be the data type before to the run (e.g., TEXT rather than NUMBER).

I _think_ this is an example of negative/unexpected behavior of caching.

**Comment by boxysean** [comment]
@jtcohen6 They are on Snowflake. I'll try to get them to chime in directly and share their code to illustrate.
