### ISSUE TITLE
[CT-176] [Bug] Github source freshness check error

### ISSUE THREAD

**Issue by tamdrashtri** [dbt-labs/dbt-core#4698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The health check tests source freshness and among those sources it checks is github.events.

After upgrading to dbt 1.0, this check has started to fail with the following error:

```
16:11:59 Database Error in source events (models/_sources/github.yml)

16:11:59 Expected a timestamp value when querying field 'created_at' of table "heap"."github"."events" but received value of type 'str' instead
```

The integration does appear to be functioning, however. The problem seems to be in the freshness check.

### Expected Behavior

Before dbt 1.0, it was having no issues in freshness check.

### Steps To Reproduce

1. In dbt, run `dbt source snapshot-freshness`

### Relevant log output

```shell
16:11:59 Database Error in source events (models/_sources/github.yml)

16:11:59 Expected a timestamp value when querying field 'created_at' of table "heap"."github"."events" but received value of type 'str' instead
```
```


### Environment

```markdown
- OS: Mac
- Python:
- dbt: 1.0.(??)
```

### What database are you using dbt with?

redshift

### Additional Context

This is the column showing the error:

![CleanShot 2022-02-08 at 10 13 46](https://user-images.githubusercontent.com/33707686/153053035-cf9629ac-d98c-43c5-977a-dc4c847c9450.png)

In here, T usually indicates that the next set is a timestamp and Z represents Zulu timezone, which is to say UTC.

**Comment by ChenyuLInx** [comment]
Hey @tamdrashtri, thanks for opening this issue. I saw you just closed, did you figure out what was the issue? We did a change in v0.21 that limited how we "coerce" types for the result sets returned by queries. Here's the PR #3499. 
If this is still an issue, we can maybe:
- verify the `created_at` column in `"heap"."github"."events"` is a timestamp. You can do this by running the same SQL that dbt is running during the freshness check(grabbing it from logs/dbt.log) and seeing what's the type returned.
