### ISSUE TITLE
[CT-207] [Bug] docker images 1.0+ use a different `WORKDIR` than pre-1.0 images -- Document this

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#4702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `WORKDIR` in dbt 1.0+ docker images was changed to `/usr/app/dbt`. When you mount a project to `/usr/app` dbt will still run properly, but arguments pass to dbt are relative to the `WORKDIR`

A situation where this issue crops up if you are providing the `--profiles-dir .` argument to dbt. This will tell dbt to look in the `/usr/app/dbt` directory, but I think it is expected that this argument be relative to where the project was mounted in the container (`/usr/app`)

### Expected Behavior

Arguments passed to dbt are relative to where the dbt project is mounted.

### Steps To Reproduce

DO NOT DO THIS IN PRACTICE

- If you have a working project with credentials in profiles.yml locally, you can temporarily copy your profiles.yml into the root of your dbt project.
- cd to this project
- run `docker run --rm --network=host -v $PWD:/usr/app fishtownanalytics/dbt:1.0.0 compile --profiles-dir .` this should fail
- run `docker run --rm --network=host -v $PWD:/usr/app fishtownanalytics/dbt:1.0.0 compile --profiles-dir ..` this should pass

### Environment

```markdown
n/a
```

**Comment by iknox-fa** [comment]
We're sticking with the existing behavior since, as @kwigley pointed out, people have come to count on it.  Repurposing this ticket to ensure it's well documented.
