### ISSUE TITLE
[CT-217] add `--no-print` flag

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#4710]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Add a flag to suppress `{{ print(msg) }}` messages coming out of macros.  Docs for `print` to be added [here](https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/dbt-jinja-functions.md).

`print` functionality in macros was added in as part of #3451 but there is currently no way to keep the messages from being printed to stdout.  This can result in these messages interspersed with logs going to stdout.

The change will involve adding a flag to [`flags.py`](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/flags.py) and [`main.py`](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/main.py) called `--no-print`.   Copying the way `quiet` was implemented will get you where you need to go.

Logic also needs to be added to stop printing to stdout.  This can be accomplished by wrapping the `print` command with an if statement for when the `--no-print` flag is false.

https://github.com/dbt-labs/dbt-core/blob/41c6177ae2c85343426c5af53f9e23451e762619/core/dbt/context/base.py#L576-L588

Once this is all done, `docs.dbt.com` will also need top be updated.  Specifically, [this page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/global-configs.md).  Open an issue over in that repo for that piece of this.

### Describe alternatives you've considered

Not doing this simply means that `{{ print(msg) }}` will always `print` to stdout.  

### Who will this benefit?

Right now, anything sent to stdout using `{{ print(msg) }}` will get printed to stdout all the time with no way to suppress it.  This will allow anyone using macros utilizing `print` to suppress those messages.

**Comment by ehmartens** [comment]
Hi @emmyoop 👋  Thanks for all of your help on https://github.com/dbt-labs/dbt-core/issues/3451 My coworker @poloaraujo and I are planning to take a crack at this! We'll get going next week.
