### ISSUE TITLE
[CT-222] [Bug] Postgres credentials persist after switching to BigQuery

### ISSUE THREAD

**Issue by BrJan** [dbt-labs/dbt-core#4715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After disconnecting Postgres and reconnecting with BigQuery, this message is thrown in the IDE -

Failed to start server.
'PostgresCredentials' object has no attribute 'schema'

### Expected Behavior

After disconnecting Postgres and reconnecting with BigQuery, the BigQuery connection should work as expected.

### Steps To Reproduce

1. Create a project with Postgres
2. Disconnect Postgres
3. Reconnect to BigQuery
4. Go to the IDE

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### What database are you using dbt with?

bigquery

### Additional Context

See this loom - https://www.loom.com/share/1ddfa55dcbed4a8388e19e409513cf42.

Workaround is to create a new project.

This is a low priority bug.

**Comment by ChenyuLInx** [comment]
Hey @BrJan, thanks for opening this. I believe this issue is related to dbt cloud and reached out to them about it.
