### ISSUE TITLE
[CT-224] Deprecation issues and runtime errors

### ISSUE THREAD

**Issue by johnh** [dbt-labs/dbt-core#4717]
Running 1.0.1 / Python 3.7.12
when I run a command on dbt (e.g. `dbt list`) I get
```
14:56:34  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
14:56:34  [WARNING]: Deprecated functionality
The `data-paths` config has been renamed to `seed-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
```

If I change the project file to use the new config names, I get run-time errors
```
Encountered an error while reading the project:
  ERROR: Runtime Error
  at path []: Additional properties are not allowed ('seed-paths', 'model-paths' were unexpected)
```

**Comment by mailtosumitrai** [comment]
@johnh I got this similar issue in pre-commit for SQLfluff, if its the same case for yours then update your pre-commit by running `pre-commit autoupdate`.

**Comment by emmyoop** [comment]
@johnh can you let me know if @mailtosumitrai's suggestion works?  

If not, would you mind sharing what you have in your `dbt_project.yml` and anything else you think might be useful to replicate this behavior?  Are you in the process of upgrading to 1.0?
