### ISSUE TITLE
[CT-229] Adapter compatible message rule update

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#4724]
For adapter compatible message, there are two rules we missed in the previous commit:
- plugins can put out patch releases before dbt-core puts out a patch release, so `dbt-core==1.0.1` and `dbt-synapse==1.0.2` can be both available
- `dbt-core` + plugins are compatible at the minor-version level.

Here's the [original thread](https://github.com/dbt-labs/dbt-core/pull/4565#pullrequestreview-872805134), #4565

**Comment by jtcohen6** [comment]
Two other quick thoughts:
- Users may have prerelease versions of plugins installed, in which case we should say `Ahead of the latest release!` rather than `Update available!`
- If one or more core/plugins is out of date, batch the upgrade instruction once at the end: `You can find instructions for upgrading here: https://docs.getdbt.com/dbt-cli/install/overview`

**Comment by jtcohen6** [comment]
I think we should also take another swing at the specific language, so it reads a bit more consistently. Something like:
```
$ dbt --version
Core:
  installed: 1.0.3
  latest:    1.0.4 - New [major/minor/patch] version available!

Plugins:
  - snowflake:  1.0.0 - Up to date
  - databricks: 1.0.0 - Update available! [note: newer patches only]
  - synapse:    0.21.0 - Not compatible!

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation
```

**Comment by jtcohen6** [comment]
>`   - databricks: 1.0.0 - Update available! [note: newer patches only]`

This might be trickier than I initially thought. As I understand it, the PyPi API only makes available "latest" and "all versions." There's no way to say "give me latest patch for minor version 1.0," except by churning through the JSON response of "all versions."
