### ISSUE TITLE
[CT-234] Automate Pytest conversion

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#4728]
With our move to pytest, instead of manually converting each test by hand, there are options out there and tools to automate the process. This issue is to look into and implement using one of those tools so we can take the manual work out of the process

**Comment by ChenyuLInx** [comment]
Closing with most work done at [link](https://github.com/ChenyuLInx/unittest2pytest/tree/dbt-pytest-all-dir). Expect smaller changes to happen over the time of converting tests.
