### ISSUE TITLE
[CT-237] Convert 002 integration test to use pytest

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#4731]
@emmyoop I just started at [001](https://github.com/dbt-labs/dbt-core/tree/main/test/integration/001_simple_copy_tests) to do as the next test after the initial one @ChenyuLInx is doing (#4729). If there is a better next test to go to, feel free to open an issue for that one. I imagine you and @ChenyuLInx tag teaming on these conversions.

**Comment by gshank** [comment]
I've already converted 001 and 003. So you should do a different one.

**Comment by leahwicz** [comment]
Oh good catch @gshank! @emmyoop I'll leave it up to you to pick then and just rename this
