### ISSUE TITLE
[CT-243] Encountered an error: Found a cycle: model.demo19_dbt.example_payments_details[Bug] <title>

### ISSUE THREAD

**Issue by sireeshachowdam11** [dbt-labs/dbt-core#4733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running with dbt=0.21.1
[WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.demo19_dbt.example.data

Encountered an error:
Found a cycle: model.demo19_dbt.example_payments_details

### Environment

```markdown
- OS:windows vm

- Python: PYTHON 3.9
- dbt: 0.21.
```

**Comment by jtcohen6** [comment]
Hey @sireeshachowdam11, it's hard to know what's going on here without more information. It sounds like you might have a project named `demo19_dbt`, and within that project you might have a model like:
```
-- models/example_payments_details.sql

select * from {{ ref('example_payments_details') }}
```
That type of self-reference is not allowed, in dbt and in DAGs more generally.

I'm going to close this issue for now. If you're looking for support / debugging help, I'd recommend posting in [the dbt Community Slack](https://community.getdbt.com/). If you think you've found a bug within `dbt-core`, though, feel free to update this issue with more details, and leave a comment below.
