### ISSUE TITLE
[CT-244] Support on_schema_change: full_refresh_on_failure

### ISSUE THREAD

**Issue by bashyroger** [dbt-labs/dbt-core#4734]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

This feature request overlaps with https://github.com/dbt-labs/dbt-core/issues/4473, but is a little different in nature.

Basically, what we would like to see is a **fallback** method for incremental models where an automatic full refresh is tried _(one time!)_ **when the build of an incremental model fails.**

Our use case is related to changing the data type of an existing column to a type that is not backwards compatible, IE from **integer** to **varchar**.

### Describe alternatives you've considered

Manually rebuiling an incremental model in our production schedule.

### Who will this benefit?

In our experience it can happen quite often that the data type of an existing column can change. Having this kind of fall-back option for incremental models can make deploying these changes to production more 'automated'

**Comment by ChenyuLInx** [comment]
@bashyroger Thanks for opening this!!
To understand the question a bit more, do you think #4473 would solve the challenges you have? Or there are cases that can't be covered by that feature request? I am assuming data type of an existing column change is a schema change.
