### ISSUE TITLE
[CT-246] [Feature] Have a space after model name before the alignment periods, for ease of double-click selection

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4737]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

In VS Code, double-clicking a model name selects it and all of the dots that line up the results:
![image](https://user-images.githubusercontent.com/7335046/154422957-a578c0ff-0b27-4d56-9562-f7728dc231f9.png)
```
07:00:06  1 of 1 START seed file dbt_jlabes.data_star_aggregate_expected.................. [RUN]
07:00:18  1 of 1 OK loaded seed file dbt_jlabes.data_star_aggregate_expected.............. [INSERT 3 in 11.49s]
```

If there was a space after expected and before the first period, it wouldn't select them all

### Describe alternatives you've considered

Using dbt Cloud in Chrome, which has different word boundary calculation logic

### Who will this benefit?

VS Code users, maybe other IDEs? 

### Are you interested in contributing this feature?

Sure

**Comment by jtcohen6** [comment]
You're so right! This has bugged me in the past.

I bet it's a one-liner in here:

https://github.com/dbt-labs/dbt-core/blob/3ad61d5d810aab8bf7bf7bc38f62d02348839c80/core/dbt/events/format.py#L20-L32

Anyone want to take a crack at it?
