### ISSUE TITLE
[CT-247] Support multiple `unique_key` for `delete+insert` incremental models (Postgres/Redshift/Snowflake/etc)

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4738]
I'd previously thought this would be harder than it is: https://github.com/dbt-labs/dbt-core/pull/4618#discussion_r791444227

When `unique_key` is a list, all we need to do is adjust the `delete` statement:

https://github.com/dbt-labs/dbt-core/blob/1df7a029b4be7c5b79e09bfbcd8ade657df6923e/core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql#L50-L56

To use `using`, which should enable multiple `unique_key` match conditions. Something like:

```sql
delete from analytics.my_model a
using my_model__dbt_tmp b
where a.unique_column_1 = b.unique_column_1
  and a.unique_column_2 = b.unique_column_2
  ...
```

And a test for it, of course :)

**Comment by leahwicz** [comment]
@jtcohen6 is this for every adapter? Basically is that what "etc." meant?

**Comment by jtcohen6** [comment]
@leahwicz This change is relevant to any adapter that uses `default__get_delete_insert_merge_sql`. Postgres, Redshift, and Snowflake (specifically the `delete+insert` incremental strategy) are the only ones we need to be conscious of ourselves.

**Comment by jtcohen6** [comment]
resolved by https://github.com/dbt-labs/dbt-core/pull/4858
