### ISSUE TITLE
[CT-249] Ability to hide all models in a directory from project config

### ISSUE THREAD

**Issue by brycebaker-centura** [dbt-labs/dbt-core#4739]
### Describe the feature
Currently, models can be hidden from docs using a schema.yml file with the show: false property specified for each model. It would be very useful to be able to hide an entire directory of models (i.e. stage models) from the dbt docs sidebar to maintain a less cluttered interface when browsing transformations.

Potential configuration in dbt_project.yml:

```
Path to directory: ./models/department_name/stage

models:
  my_namespace:
    department_name:
      +enabled: true
      +database: DEV_DEPARTMENT
      stage:
        +materialized: ephemeral
        +docs:
           show: false
```

### Describe alternatives you've considered
Modifying schema.yml to mention each stage that needs to be hidden.

### Additional context
N/A

### Who will this benefit?
All projects needing to provide transparency into their transformations, but in a cleaner interface for less technical users.

### Are you interested in contributing this feature?
Not able to contribute at this time due to level of familiarity with dbt's inner workings regarding resource properties.

**Comment by jtcohen6** [comment]
Resolved by #5397 :)
