### ISSUE TITLE
[CT-255] [Bug] ImportError: cannot import name soft_unicode from markupsafe

### ISSUE THREAD

**Issue by mailtosumitrai** [dbt-labs/dbt-core#4745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Markup recently released its new version 2.1.0 which is essential for Jinja2 package. Jinja has already released version 3.x.x and dbt still uses version 2.x.x and their [developers won't support 2.x.x for some time](https://github.com/pallets/jinja/issues/1585). Now the command `dbt deps` throws an error.

### Expected Behavior

While running `dbt deps` the packages should install instead of throwing errors.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/dbt", line 5, in <module>
    from dbt.main import main
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dbt/main.py", line 11, in <module>
    import dbt.version
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dbt/version.py", line 11, in <module>
    import dbt.semver
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dbt/semver.py", line 8, in <module>
    import dbt.utils
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dbt/utils.py", line 9, in <module>
    import jinja2
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markupsafe/__init__.py)
Error: Process completed with exit code 1.
```

### Environment

```markdown
- OS: MacOS Monterey 12.2
- Python: 3.9.6
- dbt: 1.0.1
```

### What database are you using dbt with?

snowflake

**Comment by mailtosumitrai** [comment]
If someone is facing this error and need an urgent fix for your CI/CD or job in production, you can downgrade your MarkupSafe into version 2.0.1 manually. If you installed dbt-core with pip then you can run `pip3 install --force-reinstall MarkupSafe==2.0.1`

**Comment by abhinav-kumar-17** [comment]
If building from source(`pip install .`), the Jinja2 version can be bumped to 3.0.3 as well in the [.core/setup.py](https://github.com/dbt-labs/dbt-core/blob/18fef38702460d8d1e5c52f5d663f3e12ed27c48/core/setup.py#L54). This does include some [breaking changes](https://jinja.palletsprojects.com/en/3.0.x/changes/#version-3-0-0) in Jinja2

**Comment by yu-iskw** [comment]
MEMO: https://github.com/pallets/jinja/issues/1587

**Comment by ftupas** [comment]
> If someone is facing this error and need an urgent fix for your CI/CD or job in production, you can downgrade your MarkupSafe into version 2.0.1 manually. If you installed dbt-core with pip then you can run `pip3 install --force-reinstall MarkupSafe==2.0.1`

Thanks, had this issue in our CI/CD and this worked liked a charm!

**Comment by jtcohen6** [comment]
Thanks for opening @mailtosumitrai, and for weighing in everyone! I think our approach here will need to look like:
- Pinning `MarkupSafe==2.0.1` in our production environments, and in the next patch release of dbt (v1.0.2, currently available as a release candidate)
- Looking into whether we can safely upgrade to Jinja3 in an upcoming minor version. We've hesitated on doing this so far, given the risk of breaking changes to user/project code—but we need to weigh that against the risk of running into this type of dependency/installation, issue given that Jinja2 is no longer officially supported.
