### ISSUE TITLE
[CT-256] [Bug] PostgreSQL - Casting timestamp with time zone to date yield wrong result

### ISSUE THREAD

**Issue by keurcien** [dbt-labs/dbt-core#4747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a timestamp with time zone column from which I'd like to extract the date.

```sql
with sample as (
    select '2018-11-30T23:41:06Z' as str_timestamp
)
select 
    str_timestamp::timestamp with time zone as sample_timestamp,
    (str_timestamp::timestamp with time zone)::date as sample_date
from sample
```

When I run this model, this is the table I get in the DB, as if the first cast did not happen:
|  sample_timestamp | sample_date  |
|---|---|
|  2018-12-01 00:41:06.000 +0100 | 2018-11-30 | 

### Expected Behavior

When I use a Postgres client (DBeaver/Metabase), the query yield the following result:

|  sample_timestamp | sample_date  |
|---|---|
|  2018-12-01 00:41:06.000 +0100 | 2018-12-01 | 

### Steps To Reproduce

1. Create a `sample.sql` file with the query
2. Run `dbt run --select sample`

### Environment

```markdown
- OS: MacOS Monterey Apple M1 Pro (installed with Homebrew) 
- Python: Python 3.10.0
- dbt:0.21.1
```

### What database are you using dbt with?

postgres

**Comment by keurcien** [comment]
I ran the same model on another machine to test it, and the same behaviour occurs on Ubuntu 20.04 with dbt==1.0.0.

**Comment by keurcien** [comment]
When I make a `SELECT current_setting('TIMEZONE')` locally, I get 'UTC', but on both my clients (DBeaver/Metabase), i get 'Europe/Brussels' which may explain the observed results. Is there a way to set the timezone in DBT?

**Comment by z3z1ma** [comment]
@keurcien 

Timezone is not a dbt construct. Nor is Casting values. All of this is happening in your database and the problem is independent from dbt. dbt only serves to *precompile* SQL templates with Jinja which are ultimately executed by your database. The above example has no Jinja. 

I do use Metabase though. Maybe try adjusting localization settings in the admin interface. Also use timestamptz for casting. I haven't seen it done the way above personally.

**Comment by McKnight-42** [comment]
@keurcien, @z3z1ma is correct this isn't something dbt is really able to configure and is more of a local db configuration, you could try using the above timestamptz mentioned above or something along the lines of [SET command](https://www.postgresql.org/docs/current/sql-set.html) in postgres to change their current settings.

**Comment by keurcien** [comment]
Thanks for your answers! 
I ended up using `at time zone 'Europe/Brussels'` to make sure I get the right timezone. 

The database server probably use the client timezone when reading "with time zone", and hence the inconsistencies.
