### ISSUE TITLE
[CT-265] [Bug] `clean` outside project path fails

### ISSUE THREAD

**Issue by pnadolny13** [dbt-labs/dbt-core#4762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a clean path is outside the project path it is not cleaned due to `not cleaning x because it is protected`. For us the target path is outside the project path. It looks like its considering anything outside the project path as protected, is this by design?

### Expected Behavior

If I can define my target path outside of my project path then I should also be able to clean it.

### Steps To Reproduce

1. Set `target-path` to something outside your project path
2. Set `clean-targets` to the `target-path` outside your project path you just added
3. dbt clean - you should get the message `not cleaning x because it is protected`

### Environment

```markdown
- OS: MacOS 11.6
- Python: 3.8.12
- dbt: 1.0.0
```

### What database are you using dbt with?

snowflake, other (mention it in "Additional Context")

### Additional Context

As an aside, this method name `__is_project_path` is a bit confusing as its returning if the the path is not matching the project path, https://github.com/dbt-labs/dbt-core/blob/43e3fc22c4eae4d3d901faba05e33c40f1f1dc5a/core/dbt/task/clean.py#L20.
Maybe the `not` should be moved to https://github.com/dbt-labs/dbt-core/blob/43e3fc22c4eae4d3d901faba05e33c40f1f1dc5a/core/dbt/task/clean.py#L31?

Using Athena and Snowflake databases.

**Comment by iknox-fa** [comment]
Hi @pnadolny13, thanks for the bugreport!  I can confirm that this is a problem as I just ran into it myself yesterday.  We'll get this prioritized ASAP.

**Comment by jaklan** [comment]
@iknox-fa any updates on that?

**Comment by pnadolny13** [comment]
@iknox-fa any update on this issue?

**Comment by iknox-fa** [comment]
Note:  For ticket estimation purposes the solution we're working towards is to automatically include any path designated as `target` as a path that we're allowed to clean.

**Comment by iknox-fa** [comment]
Forgot to tag you re comment above-- @jtcohen6 / @leahwicz

**Comment by jtcohen6** [comment]
Updates from me:
- This isn't something we're going to prioritize ourselves
- The default behavior feels sensible to me, and worth preserving: not removing any files located outside the relative path / directory of the dbt project

I do think it would be reasonable to support this via an optional config/flag. Perhaps `dbt clean --unsafe`?

@jaklan @pnadolny13 If one of you feels motivated to work on this, we'd be happy to review a PR for it.
