### ISSUE TITLE
[CT-398] [Bug] Specifying TRUE/FALSE instead of True/False for the invalidate_hard_deletes config of a snapshot results in "can not serialize 'Undefined' object" error

### ISSUE THREAD

**Issue by nathan-protempo** [dbt-labs/dbt-core#4765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the value of the invalidate_hard_deletes config of a snapshot is set to TRUE or FALSE instead of True or False (i.e. fully capitalized) this results in the following command line message:

01:22:06  Encountered an error:
can not serialize 'Undefined' object

Tested with `dbt snapshot` and `dbt build`, resulting in the same error. The dbt log does not contain any useful messages which makes this issue hard to troubleshoot. 

### Expected Behavior

Either:

- the invalidate_hard_deletes config should accept TRUE/FALSE as well as True/False as valid values
or
- a meaningful error message should be output to the command line and log

### Steps To Reproduce

1. Environment: Windows 11, Python 3.8.10, dbt 1.0.1
2. Define a snapshot with a config that contains:
    `invalidate_hard_deletes=FALSE`
3. Run `dbt snapshot` or `dbt build`
4. dbt errors out with the "can not serialize 'Undefined' object" message

### Relevant log output

```shell
This is the entirety of the log output: 

============================== 2022-02-23 01:24:23.418845 | fbe9ed5c-8445-46b9-921e-3da52a75fdf7 ==============================
01:24:23.418845 [info ] [MainThread]: Running with dbt=1.0.1
01:24:23.420839 [debug] [MainThread]: running dbt with arguments Namespace(cls=<class 'dbt.task.snapshot.SnapshotTask'>, debug=None, defer=None, event_buffer_size=None, exclude=None, fail_fast=None, log_cache_events=False, log_format=None, partial_parse=None, printer_width=None, profile=None, profiles_dir='C:\\Users\\Nathan\\.dbt', project_dir=None, record_timing_info=None, rpc_method='snapshot', select=['ordian.report_snapshot.dim_product_scd_snapshot_v2'], selector_name=None, send_anonymous_usage_stats=None, single_threaded=False, state=None, static_parser=None, target=None, threads=None, use_colors=None, use_experimental_parser=None, vars='{}', version_check=None, warn_error=None, which='snapshot', write_json=None)
01:24:23.420839 [debug] [MainThread]: Tracking: tracking
01:24:23.421847 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000187488A55B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000187488A5C70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000187488A5CA0>]}
01:24:23.650442 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 1 files changed.
01:24:23.651442 [debug] [MainThread]: Partial parsing: updated file: ordian://snapshots\report_snapshot\dim_product_scd_snapshot_v2.sql
01:24:23.739441 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018748B0F6A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018748B0F4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018748B0F640>]}
```

### Environment

```markdown
- OS: Windows 11
- Python: Python 3.8.10
- dbt: dbt 1.0.1
```

### What database are you using dbt with?

snowflake

**Comment by emmyoop** [comment]
@nathan-protempo thanks for the write up.  This was easy to reproduce with what you provided.

The reason that TRUE/FALSE doesn't work is actually a limitation of jinja.  From the [jinja docs](https://jinja2docs.readthedocs.io/en/stable/templates.html):

```
Note
The special constants true, false, and none are indeed lowercase. Because that caused
confusion in the past, (True used to expand to an undefined variable that was considered
false), all three can now also be written in title case (True, False, and None). However, for
consistency, (all Jinja identifiers are lowercase) you should use the lowercase versions.
```

With that said, we won't be accepting TRUE/FALSE but I definitely agree a more useful message would be valuable here.  

I'm not too sure without digging in a lot more exactly how we could generate a more useful error message in a valuable way.  This error is actually coming out of [mashumaro](https://github.com/Fatal1ty/mashumaro).  

I'll leave this open for future comments and possible prioritization.
