### ISSUE TITLE
[CT-272] [Feature] Packages - not recursive

### ISSUE THREAD

**Issue by chaimt** [dbt-labs/dbt-core#4770]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I would be great if we had a flag to not get a package recursive like:
  - git: https://github.com/YotpoLtd/dbt-datamocktool
    revision: 0.1.9a
    recursive: false

This way if we have repo A reference B that references A, would work.

Also this way we would be able to explicitly add the repos we need without conflicts

### Describe alternatives you've considered

Not many, just to stay with mega-repo, that does not scale

### Who will this benefit?

any big organisation that needs to split the repo according to teams, and each team shares models with each other

**Comment by emmyoop** [comment]
@chaimt I hear where you're coming from with this request.  My concern here is that this kind of architecture could cause some unexpected and hard to track down bugs or unexpected outcomes.

If I understand correctly, this is the (very) basic setup you're referring to causing issues:

```
package A, in repo 1, imports Package B
package B, in repo 2, imports package A
```

Would it be possible to have a base package that is the shared models?

```
package A (shared resources), in repo 1
package B, in repo 2, imports package A
package C, in repo 3, imports package A
```

If that won't work, I really encourage you to take this conversation to the [dbt community slack](https://www.getdbt.com/community/join-the-community/) and see how others are solving this problem with dbt.

I'm going to close this for now but feel free to let me know if you think I did not understand the problem correctly!
