### ISSUE TITLE
[CT-289] Automate Changelog Generation on Release

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#4789]
When releasing, it would be ideal to have the `CHANGELOG` auto generate for the release.  It makes the most sense to be part of the [version-bump.yml](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/version-bump.yml) GHA so that the version bump and changelog all go in as a single PR.  Since the version bump PR does not include a CHANGELOG entry, the PR would need to have the `Skip Changelog` tag added to it.

This would involve the input of that action needing to be split out to be version (ex 1.0.5) and prerelease tag (ex rc1, b1, etc) since changie takes them as separate inputs and inserts a dash in the middle while the version bump does not use the dash.

Not doing this as part of the original release of changie so we can see how the files get generated and manually adjust as needed.

**Comment by nathaniel-may** [comment]
Just a reminder to update the README with these changes once they're made.

**Comment by jtcohen6** [comment]
> Posting the contents of the release file as opposed to a link would be better since the prereleases end up getting squashed down into a final release.

On second thought: We still could link to the release notes, using the release tag as the branch. E.g. for v1.0.5rc1: https://github.com/dbt-labs/dbt-core/blob/v1.0.5rc1/.changes/1.0.5-rc1.md

It makes sense to me that:
- changelog is by long-lived minor version branch (`1.0.latest`, `1.1.latest`), and includes updates as new backports / patches are released
- release notes are immutable, and tied to a specific release/tag

So this comes down to a cosmetic question: to show all, or to link elsewhere?

I do like having the release notes visible right from [the releases page](https://github.com/dbt-labs/dbt-core/releases)—but I also recognize it can add clutter, and it takes longer to scroll back to see older releases. (Maybe we do neat things with HTML toggles...?)

**Comment by lostmygithubaccount** [comment]
@emmyoop @jtcohen6 is this already done? going to remove staleness

**Comment by emmyoop** [comment]
Partially.  @leahwicz added the changelog generation into `version-bump.yml` [here](https://github.com/dbt-labs/dbt-core/blob/bbf4fc30a56e43734dfc94e43a8cf1d2ef36ec29/.github/workflows/version-bump.yml#L77-L88).

But we are not automatically posting release notes yet.

**Comment by emmyoop** [comment]
This has been done for a while now!
