### ISSUE TITLE
[CT-290] [Bug] logger not outputing colors to stdout when stdout is piped to another process

### ISSUE THREAD

**Issue by varun-dc** [dbt-labs/dbt-core#4790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`dbt run` will output color as expected on Windows, MacOS and Linux.

`dbt run | cat` will **not** output color to stdout (on Windows, `dbt run | out-host -paging`, is closest equivalent to `| cat` afaik).

The log file in `<dbt project>/logs/dbt.log` does contain ANSI color codes.

### Expected Behavior

Piping stdout to another process should not stop color output to stdout

### Steps To Reproduce

Ensure you've got dbt profiles setup and make a new project if you don't already have one. This can be reproduced on a minimal, `dbt init` project as long as you've got a profile setup to use.

`dbt run` to see good and expected behavior. 

`dbt run | cat` to see incorrect behavior. `dbt run | out-host -paging` on Windows.

### Relevant log output

<img width="834" alt="image" src="https://user-images.githubusercontent.com/91232924/155771255-891e53ee-c39d-427f-99db-d50be0900d5c.png">

### Environment

```markdown
- OS: MacOS, Windows, Linux
- Python: Python 3.7, 3.9
- dbt: 1.0.3
```

### What database are you using dbt with?

snowflake

### Additional Context

I believe this is related to the changes done in https://github.com/dbt-labs/dbt-core/pull/4474

**Comment by ChenyuLInx** [comment]
@varun-dc  Thanks for submitting this! Let's keep following up on this in your PR!
