### ISSUE TITLE
[CT-292] [Feature] Add column attribute in project.yml file for friendly/display name

### ISSUE THREAD

**Issue by richiebful** [dbt-labs/dbt-core#4794]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I would like an attribute under the column (and ideally also under the model) that would hold a string representation of the friendly name for the reporting layer.

For example, we have a supplier model in our dbt project:
```yaml
- name: supplier
  friendly: "Supplier" 
  columns:
        - name: supplier_key
          friendly: "Supplier Key"

In the output documentation, this would be added alongside column name in the columns table.

### Describe alternatives you've considered

My alternative option would be to fork the project and add the column that I wanted in the output docs.

### Who will this benefit?

This will benefit business users who are using our models in PowerBI. We're exposing the friendly names in PowerBI already, but we want to keep the more tech friendly names with underscores in the background. If business analysts and the like can use our DBT documentation with the Friendly Names, it will make the documentation more accessible overall.

### Are you interested in contributing this feature?

I will write the feature if necessary. It would save me some time if you pointed me to the right files to edit.

### Anything else?

_No response_

**Comment by jtcohen6** [comment]
Hey @richiebful, thanks for opening the issue!

It sounds like, in addition to displaying the column name in the auto-generated documentation site for your dbt project, you're already renaming the column in PowerBI:

> We're exposing the friendly names in PowerBI already

Could you say more about how you're doing that? Does PowerBI have simple rules to convert snake-case column names into sentence case? Or are you defining "friendly" names as a custom `meta` property of each column, and pushing that metadata into PowerBI? For instance:

```yml
models:
  - name: my_model
    columns:
      - name: supplier_key
        description: Unique identifier for suppliers
        meta:
          friendly: Supplier Key
```

Defining that `meta` property doesn't have any effect in the `dbt-docs` site currently, but it could—the information does appear in the relevant artifact produced by `dbt-core` (`manifest.json`). If you do decide to fork the project, I think that's the place to make the intervention: https://github.com/dbt-labs/dbt-docs. You could continue using standard `dbt-core`, producing standard artifacts, with a custom `index.html`.

**Comment by richiebful** [comment]
We're manually renaming the columns inside of PowerBI right now, but we wanted dbt-docs to provide a BI-facing friendly name in the web docs.

Thanks for your recommendation. I will work on forking dbt-docs
