### ISSUE TITLE
[CT-304] Add structured logging for parse events

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4807]
Create [events](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/README.md) for each time dbt:

- Schedules a node for removal or re-parsing, including the unique_id of that node
- Finishes re-parsing a node, including its unique_id and all properties
- (Other parse-time events?)

**Goal:** Make it possible to track changes in dbt project state, using a solidified interface, without requiring access to `manifest.json` (or introspection of `partial_parse.msgpack`, for internal use only).

This will be a _lot_ of events during full re-parses in big projects. Should we seek to make these optional, or batch them up in any way?

**Comment by gshank** [comment]
I was wondering if we should have the option of writing these node updates to a separate log. Also, would we turn it off for full parses?

**Comment by nathaniel-may** [comment]
Estimation:
- needs more clarification on how we want this to work
- @jtcohen6 would this be a good use case for a flag like `--cache-events` to turn this off? 
- @jtcohen6 given the goal is about tracking dbt state changes, is just the filename enough information in each event?
- @jtcohen6  models are parsed multiple times. do we only want to fire an event when we're completely done with the file?
- estimation IF it were just adding events that contain the name of the file after it's completely parsed during partial parsing, and no flag: 3

**Comment by jtcohen6** [comment]
I think this would be a _great_ use case for a new logging level and/or flag akin to `--log-cache-events`. Most users running locally will not want the full information here. (I even wonder that about our `Parsing ...` / `static parser` / `parser fallback` events today, which add a lot of clutter to `logs/dbt.log`.)

I think the filename by itself may not be enough here. The goal for each event would be to provide all relevant, updated information about that (changed) node power downstream metadata use cases. And to fire it only when we're completely done with that file / node. What information is that exactly? The full manifest entry for that node? Or a much smaller subset (`unique_id`, `resource_type`, `checksum`, `config`/`materialization`)? I think our Metadata team colleagues will need to help us think through the answer.

I also know that, per the discussion in + around #4617, we'd like to turn "manifest node entry" from a joint internal/external contract, into something internal with a stabilized external serialization. That goes for `manifest.json` + these log events + [representation in the Jinja context](https://docs.getdbt.com/reference/dbt-jinja-functions/graph).

**Comment by jtcohen6** [comment]
More thinking needed here. Structured events / logging does not feel like the appropriate mechanism for fully reconstructing the full Manifest / project contents, even if we did have one event per parsed node representation. I'm going to close this issue for now.
