### ISSUE TITLE
[CT-306] [Bug] Indexes config does not create indexes

### ISSUE THREAD

**Issue by cleare-cl** [dbt-labs/dbt-core#4808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The config for index creation in postgres developed in [dbt-labs/dbt-core#3106](https://github.com/dbt-labs/dbt-core/pull/3106) does not create indexes.

We have tried different configuration methods, including specifying different uniqueness of the indexes on the columns as well as running it only with one column. 

The compiled dbt SQL did not include `create index` statement. 

### Expected Behavior

The indexes configuration in the model creates indexes of the specified columns when ran.

### Steps To Reproduce

1. In a dbt model, set the indexes configuration 

> {{
>     config(
>         materialized = 'table',
>         indexes=[ {'columns': ['column1', 'column2', 'column3'] } ]
>         )
> }}

2. Run the model

### Environment

```markdown
- OS: MacOS
- Python: 3.9.10
- dbt: 1.0.3
- Postgres: 14.2
```

### What database are you using dbt with?

postgres

**Comment by jtcohen6** [comment]
@cleare-cl Thanks for opening, and sorry for the delay getting back to you on this one!

> The compiled dbt SQL did not include `create index` statement.

To clarify, did you try running the model (`dbt run`), and see that the `create index` statement was missing from the logs (`logs/dbt.log`), and that the index was indeed missing within Postgres?

Or was it that, after `dbt compile` or `dbt run`, you checked the "compiled SQL" for that model (such as `target/compiled/.../model_with_indexes.sql`), and noticed that it didn't contain any `create index` statements?

Today, dbt's "compiled SQL" includes just the compiled SQL _written within that model_. It doesn't include the "helper" statements within the materialization that persist docs, create indexes, move temp/backup tables out of the way, and so on. By a similar token, dbt's "run SQL" includes only the "main" statement run during the materialization (`create table`, `insert into`, etc). The creation of indexes happens in a separate statement afterward:

https://github.com/dbt-labs/dbt-core/blob/ed5df342ca5d99c5e6971ee6d11c8cf3e6e263b3/core/dbt/include/global_project/macros/materializations/models/table/table.sql#L56

There's been a long-lived discussion about supporting a "dry run" mode for materializations, with the idea that dbt should be able to print out _everything_ it plans to do during the process of materializing a model: https://github.com/dbt-labs/dbt-core/discussions/4456

**Comment by jtcohen6** [comment]
@olia-cl Is there any chance you have custom materialization macros in your project, overriding the ones that ship within `dbt-core`'s global project? The calls to the `create_indexes` macro are here in the default `table` and `incremental` materializations:

https://github.com/dbt-labs/dbt-core/blob/e03d35a9fc606f5b1fc7e94c0bc04dbe88f558cf/core/dbt/include/global_project/macros/materializations/models/table/table.sql#L41

https://github.com/dbt-labs/dbt-core/blob/e03d35a9fc606f5b1fc7e94c0bc04dbe88f558cf/core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql#L69-L71

**Comment by wesleyguirra** [comment]
I'm having the same issue

**Comment by datasalaryman** [comment]
Having this issue now

**Comment by extramediumrare** [comment]
I am also experiencing this issue. I do not see any `create index` in the logs and also, no index is created in Postgres when referring to the `pg_indexes` table.
