### ISSUE TITLE
[CT-396] [Bug] Generic tests aren't valid in BigQuery when the struct and table name are the same 

### ISSUE THREAD

**Issue by dgreen161** [dbt-labs/dbt-core#4824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In BigQuery if the table name and the struct within both have the same name the unique test is failing due to table aliases not being applied. This is happening due to the way BigQuery parses the ```test_data.id``` portion. BigQuery believes that the ```test_data``` part is the table and then looks for a column called ```id```.

![Screenshot 2022-03-04 at 11 57 58](https://user-images.githubusercontent.com/43223669/156759517-9cad6927-7e95-4368-92d4-74fbd71705db.png)

This also affects the accepted_values, not_null, and relationship tests. I'm not sure if this also affects other packages such as dbt_utils etc as I haven't looked at the code for them.

### Expected Behavior

Instead, what it should be is similar to below where the table name is given an alias that is different to the name of any table, column, or struct. In the screenshot, since ```test_data``` is no longer the table name it is looking for a struct with that name. When it finds one, it then looks for a column called ```id```. This now allows for the query to be valid as shown in the top right.

![Screenshot 2022-03-04 at 11 58 55](https://user-images.githubusercontent.com/43223669/156759638-a2af0c89-10ad-4ad1-8358-dc6c6b5a8f9b.png)

I believe changing it in these fours places will fix it:
- [accepted_values](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/generic_test_sql/accepted_values.sql#L9)
- [not_null](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/generic_test_sql/not_null.sql#L4)
- [relationships](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/generic_test_sql/relationships.sql#L5)
- [unique](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/generic_test_sql/unique.sql#L7)

The alias will need to be random enough that no table or struct will have this name.

I'm not familiar with the intricacies of the code base but if you think it's limited to these four files I would be happy make the changes.

### Steps To Reproduce

This code is the output of a compiled unique test, replacing the source with the test data

```sql
WITH test_data AS (
    SELECT 
        STRUCT(
            1 AS id
        ) AS test_data
)
, dbt_test__target as (
  select test_data.id as unique_field
  from `test_data` AS some_alias_that_is_unlikely_to_be_a_table
  where test_data.id is not null
)
select
    unique_field,
    count(*) as n_records
from dbt_test__target
group by unique_field
having count(*) > 1;
```

### Environment

```markdown
- OS: dbt Cloud & Mac OS 11.6.3
- Python: 3.9.10
- dbt: 1.0.3
```

### What database are you using dbt with?

bigquery

### Additional Context

Not sure if this also applies to the other adapters. Looking at the documentation for postgres, redshift, and snowflake they all support the ```AS``` keyword so I don't think this will break them

**Comment by marianore-beepboop** [comment]
I had the same issue. Is it really a bug or is it an expected behaviour in order to force the use of best practices, in this case not using the same table name for a column name? 😅

**Comment by dbeatty10** [comment]
Thanks for the report @dgreen161 and @marianore-beepboop!

I'm not sure one way or another if this same scenario would affect databases other than BigQuery.

It doesn't feel great to try guessing an identifier that will be unique -- all that would do is just push the error case to be more rare.

### Alternative idea
A possibility might be to add an optional `alias` parameter to the built-in tests you referenced.

**Note:** The following is completely untested!
```
{% macro default__test_not_null(model, column_name, alias=none) %}

{% set column_list = '*' if should_store_failures() else column_name %}

select {{ column_list }}
from {{ model }}{% if alias is not none %} as {{ alias }}{% endif %}
where {{ column_name }} is null

{% endmacro %}
```

Then you'd do the following when you hit that error case:
```
version: 2

models:
  - name: orders
    columns:
      - name: status
        tests:
          - not_null:
              alias: you_write_something_unique_here
```

### Recommendation for workaround
I don't know the appetite for considering an update like this -- I'd recommend using one of the following workarounds:
- use unique names between the relation and the structs contained within
- implement [custom generic test(s)](https://docs.getdbt.com/guides/legacy/writing-custom-generic-tests) within your project(s) that handle this edge case

**Comment by dgreen161** [comment]
Thanks @dbeatty10 

I agree on the alias name attempting to be unique, it's likely to make it a more difficult thing to debug in the future.

With some slight tweaks to the alternative idea that you shared, I was able to adapt the not_null test to override the default with a `table_alias`. This SQL was placed into the `tests/generic/` folder.

```sql
{% test not_null(model, column_name, table_alias=None) %}

{% set column_list = '*' if should_store_failures() else column_name %}

select {{ column_list }}
from {{ model }}{% if table_alias %} as {{ table_alias }}{% endif %}
where {{ column_name }} is null

{% endtest %}
```

The yml file remained similar to what you shared also
```yml
  - name: test_data
    columns:
      - name: test_data.id
        tests:
          - not_null:
              table_alias: some_alias_that_is_unlikely_to_be_a_table
```

Note that I used a different name instead of `alias`, I wonder if it's a reserved word as it wasn't working for me until I changed it to `table_alias`.

If it's unlikely to be updated in core, this workaround with the override would work for us.

**Comment by dbeatty10** [comment]
@dgreen161 thanks so much for sharing your working solution!

It's very possible that `alias` is reserved in some capacity. We certainly have `where` as an internal keyword for generic tests, so maybe `alias` is similar.

Glad that this workaround handles your use case if this doesn't get updated in Core.
