### ISSUE TITLE
[CT-327] Use Structural Exceptions

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#4836]
### Describe the Feature

Following the same pattern in the event module for structured logging, exceptions in dbt could be converted into structural exceptions.

Structural exceptions are values that:
- contain only other values required to construct a message
- have an associated function that constructs this message. Messages are never constructed at the site the exception occurred. In our case, this function will handle common functionality like scrubbing secrets.
- can be easily passed if we don't want to throw

Looking at [exceptions.py](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/exceptions.py), a rough structure for the parent classes already exists. However, we currently use functions like `raise_compiler_error` to construct concrete error values from strings at each call site. This ticket is suggesting that in stead of having two exceptions both of class `CompilationException` like:

```
Compilation Error in model customers (models/customers.sql)
    Model 'model.jaffle_shop.customers' (models/customers.sql) depends on a node named 'stg_customer' which was not found
```

and

```
Compilation Error in macro (macros/cents_to_dollars.sql)
    Reached EOF without finding a close tag for macro (searched from line 1)
```

We instead create distinct classes for each kind of exception that can occur such as `ModelDependencyNotFoundErr` and `MacroMissingCloseTagErr`.

This pattern is common in other programming languages. For example, Java has exceptions like `ArrayIndexOutOfBoundsException`, `NoSuchMethodException`, and `NullPointerException` that are all very specific.

This would allow for easy incremental improvements to exception messaging by developers and community members because each message could be quickly located in the code base via the class name.

**Comment by jtcohen6** [comment]
As part of this effort, I'd like to create distinct classes for each `warn_or_error` call site as well. Currently, it just passes everything into the generic method `raise_compiler_error` or the generic event type `raise_compiler_error `. `WarnOrError` should become a base class for events/exceptions, defining the behavior around whether to warn or raise based on the `--warn-error` flag/config. See: https://github.com/dbt-labs/dbt-core/issues/4383#issuecomment-1048702639.

**Comment by nathaniel-may** [comment]
Estimation:
- this is a very large effort. below are some subtasks:
- create parent classes in a way mypy can be helpful e.g. `CompilationException` (use event module as inspiration)
- find all calls that create these exceptions today, and create classes for each
- modify call sites to raise directly e.g. `raise MySpecificException(arg0, arg1)` (don't call a function like `raise_error_for_me()`)
- total estimation: 13+
- might be worth a 5 day spike to see how much effort is required.

**Comment by jtcohen6** [comment]
Going to close this broad issue, in favor of a newer & narrower one: https://github.com/dbt-labs/dbt-core/issues/5958

We've been making solid progress on the way here!
