### ISSUE TITLE
[CT-363] [Feature] Automate changie entries for dependabot PRs

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#4864]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Add `Dependencies` as a new `Kind` to changie.  Add it to the bottom of the list here:

https://github.com/dbt-labs/dbt-core/blob/0fce63665cd8a45fbc069c02ae174e194ed5892b/.changie.yaml#L10-L16

### Describe alternatives you've considered

Not doing it and putting dependency changes somewhere else.

### Who will this benefit?

Anyone using dbt to clarify what's changed.

**Comment by jtcohen6** [comment]
I think this was resolved by https://github.com/dbt-labs/dbt-core/pull/4917?

**Comment by emmyoop** [comment]
@jtcohen6 the `Dependencies` type was added but not automation around dependabot creating that changie yaml file.  I was leaving this open to explore that path.  Since dependabot is meant to automate everything, it would be nice to not have to manually add the changie yaml.

I also know now that the blank fields will cause funky results like a link with an issue number of `<no value>` instead of an actual number.  I still think it's doable but will take more research.

**Comment by jtcohen6** [comment]
good call! I'll retitle the issue

**Comment by nathaniel-may** [comment]
estimation:
- dependency type already added
- still need to modify the dependabot github action to generate the changie entry. would need to use #4904 for the ticket.
- challenge: changie needs the PR number, but this action creates the PR.
- add dependabot to list of contributors to exclude (easy)
- estimation: 3

**Comment by jtcohen6** [comment]
@emmyoop Was this fully resolved by https://github.com/dbt-labs/dbt-core/pull/5065?

**Comment by emmyoop** [comment]
Yep, linked to the wrong issue.  Closing!
