### ISSUE TITLE
[CT-371] [Bug] CLI vars in packages.yml and selectors.yml don't work.

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#4876]
When we did the work to separate out rendering of secrets, a bug was introduced where instead of using cli_vars to construct the contexts for packages and selectors, we use the entire yaml context (which is also a dict). Because of this we get errors like: "Object of type method is not JSON serializable" and also vars are not found when rendering.

**Comment by jtcohen6** [comment]
@gshank Thanks for looking into this! Glad we caught it during our collective triage time the other day...

This feels like something we'd want to include in the next patch release. Do folks agree?
