### ISSUE TITLE
[CT-376] add ability to calculate metrics based off of other metrics

### ISSUE THREAD

**Issue by mary-hallewell** [dbt-labs/dbt-core#4884]
In order to calculate any rate-type metrics there has to be a mechanism supported to calculate metrics based off of other metrics.

This could be implemented by expanding the inputs allowed in model. Instead of just referencing a materialized model you could allow referencing a metric dynamically and passing the time aggregation info from your current metric as a variable argument. 

You could also enable this functionality by natively supporting more type aggregations such as division and then allowing dynamic metric arguments to be passed in that type field. I believe that can mostly be accomplished by overwriting the type functions but it still leaves a gap where you can't pass other metrics to be used in that type agg.

**Comment by JC-Lightfold** [comment]
Absolutely critical that metrics can input to other metrics. If that's achieved by intermediary models initial, okay, but ultimately metrics need to be able to work like models - they can and will chain into each other. Perfectly fine for them not to be recursive though.

**Comment by jtcohen6** [comment]
Agreed, this feels super important! There are two related questions on my mind:
- **Metrics that power other metrics.** Primary use case is a ratio. My main questions are all around validation: Does the composite child metric inherit all properties of the parent metrics? What if those properties disagree (e.g. different time scales)? Should it be allowed to override/reconcile them? What about metric types that should _not_ be allowed to power another metric type, e.g. a distinct count of a distinct count?
- **Metrics that power models.** I'm already hearing about folks who are creating "summary" models that union together a number of metrics. The problems: metrics cannot be DAG parents, and the metrics package does some creative things with lineage currently to work in all runtime environments. We need to figure out how to preserve lineage when a model depends on a metric (and thereby another model): https://github.com/dbt-labs/dbt-core/issues/4851#issuecomment-1068454343

We're continuing to collect feedback on the initial implementation of metrics, with plans to batch up larger-scale enhancements (like this one), along with more tactical improvements, for a minor version later this year. In the meantime, let's keep the thread going!
