### ISSUE TITLE
[CT-381] [HOTFIX] Homebrew Incident Resolution

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#4891]
### What Happened

dbt-core depends on the dbt-extractor package, and the dbt-extractor package depends on tree-sitter-jinja2. dbt-extractor specifies tree-sitter-jinja2 via a github link using the git protocol. Github security rules changed to require this link to use https which caused cargo to fail to build the dbt-extractor.

### Who Is Affected

Everyone attempting to build dbt-core from source after the github security rules took affect. This primarily affects homebrew users since homebrew builds dbt from source locally.

### Solution:
- release new dbt-extractor (0.4.1). The fix is already in main
    - dbt-labs/dbt-extractor#51
- release new dbt-core patch from branch [1.0.4-hotfix](https://github.com/dbt-labs/dbt-core/tree/1.0.4-hotfix) which depends on this new version and accepts all future patch releases so we can skip this step in the future. This branch is only the 3 necessary commits ahead of 1.0.3 to fix this incident.
    - main: #4890
    - backport is directly on branch [1.0.4-hotfix](https://github.com/dbt-labs/dbt-core/tree/1.0.4-hotfix) because of complications with running the bump-version workflow for a hotfix branch.
    
Getting the release out has been delayed due to complications with github actions due to an [ongoing GitHub incident](https://www.githubstatus.com/incidents/dcnvr6zym66r).

**Comment by nathaniel-may** [comment]
re opening until the release is published.

**Comment by elalonde** [comment]
Looks like I'm tripping on this issue. Any workarounds that I might employ in the meantime?

**Comment by leahwicz** [comment]
@elalonde I apologize for the trouble! We are currently trying to release a fix but GitHub Actions is having an incident so we are waiting for them to resolve that before we can get the release out. Sorry for the inconvenience but we will have a fix out as soon as we can

**Comment by MattiasVahlberg** [comment]
@leahwicz Any ETA when this fixed is deployed?

**Comment by leahwicz** [comment]
@MattiasVahlberg it should be within the next hour. We have the fix deployed out to PyPi and are now updating Homebrew

**Comment by leahwicz** [comment]
Ok the homebrew formulas are updated. Could anyone verify on their end that they are unblocked?

**Comment by msaminsky** [comment]
Works for me now!

**Comment by leahwicz** [comment]
Some additional instructions here to clear up any lingering issues you might be seeing:
https://github.com/dbt-labs/homebrew-dbt/issues/76#issuecomment-1072532628

**Comment by nathaniel-may** [comment]
Closing because we have community confirmation of the fix.

**Comment by elalonde** [comment]
works for me
