### ISSUE TITLE
[CT-388] NO ISSUE

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#4904]
This ticket is a placeholder for the rare changelog entries that do not have an associated ticket. If you're unsure if you should make a ticket or not, make one!

**Comment by emmyoop** [comment]
Background:  changie requires you have an issue number associated with your change.  If you delete the issue number from the yaml file it gets converted into an ugly

```
([#<no value>](https://github.com/dbt-labs/dbt-core/issues/<no value>)
```

in the formatted changelog entry.  That's no good so use this ticket number instead.

_This should be a rare exception, most PRs should have an issue associated with them!_
