### ISSUE TITLE
[CT-400] Event module should handle "warn on error" behavior.

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#4914]
There are some places in the code that conditionally fire otherwise identical warning events and error events. For example see [these lines](https://github.com/dbt-labs/dbt-core/blob/54027d996b54a2737c3c7a84695378a7c996a74a/core/dbt/task/printer.py#L84-L99) in the printer task. Because the logged message is identical in both of these events, they should not be two separate events.

The proposed solution:
1. respect the flag `--warn-error` within the event module
2. add a default named parameter to `fire_event` for adhoc error-on-warn behavior. (i.e. -  `error_on_warn=False`)
3. for all events that have a warning and error variant remove the error variant and use the added flag to fire_event at the call sites.

**Comment by jtcohen6** [comment]
This is eerily similar to (but subtly different from) our `warn_or_error` behavior. That's also something we should look to rework, when we bring exceptions into the same structured framework: https://github.com/dbt-labs/dbt-core/issues/4836#issuecomment-1061003390

**Comment by jtcohen6** [comment]
Realized that https://github.com/dbt-labs/dbt-core/issues/5424 was another instance of this tech debt (and an actual bug, since it's not working correctly today)

**Comment by stu-k** [comment]
Having looked through the event types in [events/types.py](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/types.py) and where they are emitted, I believe the only events with identical error/warning variants are as follows:
- [task/printer.py](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/task/printer.py#L84-L99): [RunResultWarning](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/types.py#L1632), [RunResultFailure](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/types.py#L1644) (conditionally fired)
- [task/freshness.py](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/task/freshness.py#L59-L102) [PrintHookEndErrorLine](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/types.py#L2045), [PrintHookEndErrorStaleLine](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/types.py#L2066), [PrintEndHookWarnLine](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/types.py#L2087) (conditionally fired)
- [events/adapter_endpoint.py](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/adapter_endpoint.py#L15-L68): [AdapterEventWarning](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/types.py#L87), [AdapterEventError](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/types.py#L92) (not conditionally fired, but has identical event structure)

Additionally, it would seem that our events are defined as whatever level they are (i.e. test, debug, info, warn, error) via inheritance, so emitting one event as both warn and error would require a refactor of how our events are defined.

Given this information, I'm not sure it makes sense to have the `fire_event` function optionally turn events from warnings into errors given it would only remove two events, and introduce unnecessary complexity into the events to be able to be transformed from one type into another.

I will close this for now in favor of #5424. Please feel free to reopen should my assessment be incorrect.
