### ISSUE TITLE
[CT-402] Randomly failing test: test_hard_delete_snapshot.py

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#4916]
The failing test seems to be a 1 second difference between 2 timestamps in tests/functional/simple_snapshot/test_hard_delete_snapshot.py just for one Python/ OS combo

            )
E           assert datetime.datetime(2022, 3, 21, 19, 39, 23, tzinfo=<UTC>) >= datetime.datetime(2022, 3, 21, 19, 39, 24, tzinfo=<UTC>)
E            +  where datetime.datetime(2022, 3, 21, 19, 39, 23, tzinfo=<UTC>) = <built-in method replace of datetime.datetime object at 0x7f0793efc780>(tzinfo=<UTC>)
E            +    where <built-in method replace of datetime.datetime object at 0x7f0793efc780> = datetime.datetime(2022, 3, 21, 19, 39, 23).replace
E            +    and   <UTC> = pytz.UTC
E            +  and   datetime.datetime(2022, 3, 21, 19, 39, 24, tzinfo=<UTC>) = <built-in method replace of datetime.datetime object at 0x7f0794198900>(microsecond=0)
E            +    where <built-in method replace of datetime.datetime object at 0x7f0794198900> = datetime.datetime(2022, 3, 21, 19, 39, 24, 2693, tzinfo=<UTC>).replace

/home/runner/work/dbt-core/dbt-core/tests/functional/simple_snapshot/test_hard_delete_snapshot.py:146: AssertionError

**Comment by nathaniel-may** [comment]
estimation:
- the failure implies an actual underlying bug
- should at least mark as flaky in the meantime, but that is not a fix.
- 1 day spike instead of estimation
