### ISSUE TITLE
[CT-411] [Feature] Seed json files

### ISSUE THREAD

**Issue by JCZuurmond** [dbt-labs/dbt-core#4936]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Let `dbt seed` also insert json files.

### Describe alternatives you've considered

Upload json file outside of dbt

### Who will this benefit?

- people who want to seed files with nested fields
- [Upload dbt artifacts](https://github.com/brooklyn-data/dbt_artifacts/issues/6)

### Are you interested in contributing this feature?

Always - if I find the time

### Anything else?

What is the idea behind supporting csv files? What is the motivation to (not) add new file types?

**Comment by jtcohen6** [comment]
Thanks @JCZuurmond! Quick hits:
- **For seeds:** I think this may be a dupe of https://github.com/dbt-labs/dbt-core/issues/2365, which has continued to garner interest. There are some pointers in https://github.com/dbt-labs/dbt-core/issues/2365#issuecomment-933429242 about what an implementation might look like. I'm going to tag in someone from the Execution team to take a look, for broader awareness of the request.
- **For uploading artifact files to the warehouse:** We've had issues opened on specific adapters to support an (internal and intentionally undocumented) `upload_file` macro, the implementation of which will necessarily vary by adapter. IMO important to call out that the intended use case here is loading rich dbt metadata into the warehouse; we see this as an interim "hack" to offer in-dbt parity with other orchestration tools, especially for dbt Cloud users who lack other means of syncing JSON artifacts into the warehouse.

**Comment by JCZuurmond** [comment]
Thanks @jtcohen6 . Closing this issue due to duplication with #2365
