### ISSUE TITLE
[CT-414] [Bug] dbt-core has incompatible with psycopg2 on Apple M1 architecture

### ISSUE THREAD

**Issue by hello1990called** [dbt-labs/dbt-core#4942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot run dbt-core on the M1 platform using any version of Python, with or without a virtual environment, inside or outside the Rosetta terminal, using any arch setting, either arm64 or x_86_64. In every permutation of python, virtual environment or Rosetta arch setting, the error is always exactly the same:

```dbt test
18:01:04  Encountered an error:
dlopen(/Users/<me>/<my project>/env/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002):
 tried: '/Users/<me>/<my project>/env/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' 
 (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

### Expected Behavior

dbt test should run properly after installing properly in either terminal or rosetta terminal, with arch set to a single value.

### Steps To Reproduce

1. install dbt-core on a Mac M1.
2. try to run dbt test
3. get error: python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

### Environment

- OS:Mac M1 arm64, arm64e, x86_64
- Python: 3.9.7, 3.7.9, 3.9.10
- dbt:1.0.0, 1.0.3, 1.0.4

### What database are you using dbt with?

Redshift

### Additional Context

We were able to get one developer's laptop running dbt-core on the M1 platform, but we are unable to repeat the steps to get it to work, using any permutation of PyCharm, venv, poetry, python 3.9.x, dbt 1.0.x, under any architecture.

**Comment by hello1990called** [comment]
We did find a workaround:

brew install libpq --build-from-source
export LDFLAGS="-L/opt/homebrew/opt/libpq/lib"
pip3 install psycopg2-binary --force-reinstall --no-cache-dir

**Comment by Olaktal** [comment]
Hello

I'm facing the same issue following issue on my Mac M1:

```
ImportError: dlopen(/Users/amelie.tea/.pyenv/versions/3.9.1/envs/data-engineering/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): tried: '/Users/amelie.tea/.pyenv/versions/3.9.1/envs/data-engineering/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
09:17:20  Encountered an error:
dlopen(/Users/amelie.tea/.pyenv/versions/3.9.1/envs/data-engineering/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): tried: '/Users/amelie.tea/.pyenv/versions/3.9.1/envs/data-engineering/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

I tried these commands as described by @josephbrownskilljar but it didn't worked :( 

```
brew install libpq --build-from-source
LDFLAGS="-L/opt/homebrew/opt/libpq/lib" poetry run pip3 install psycopg2-binary --force-reinstall --no-cache-dir
```

**Environment**
OS: Mac M1 Monterey 12.5
Python: 3.9.1
dbt-core: 1.2.0
poetry version: 1.1.14

**What database are you using dbt with?**
Redshift

Any idea where it comes from and how to solve it ?
We tried to drop the python virtual env and reinstall it also.
