### ISSUE TITLE
[CT-415] Reorder changie change kinds

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4943]
I sense that the order here:

https://github.com/dbt-labs/dbt-core/blob/1c71bf414d36a48b425f6183308a888a7cd30306/.changie.yaml#L10-L16

Maps to the order in the generated changelog [here](https://github.com/dbt-labs/dbt-core/blob/v1.1.0b1/CHANGELOG.md#dbt-core-110-tbd).

As a user of dbt and reader of the changelog, I'd prefer the order to be:
- Breaking changes (side note: in these entries, we need to call out _who_ these might be breaking for)
- Features
- Fixes
- Docs
- Under the hood
- Dependencies

**Comment by emmyoop** [comment]
You are correct.  The order in the `.changie.yaml` maps to both the order they appear in the generated markdown and the order they appear in the interactive prompt.
