### ISSUE TITLE
[CT-417] [Bug] User experiencing dbt deps loop when trying to import private package

### ISSUE THREAD

**Issue by crystalro0** [dbt-labs/dbt-core#4946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User is attempting to import package via a HTTPS and user/PAT. Once dbt deps is run, it looks like there's a loop even when the repo has been cloned. 
```
19:36:15  Set downloads directory='/tmp/xxxxx'
19:36:15  Executing "git clone --depth 1 https://xx/:*****@xx.com/xx/template.git xxxxxxxx"
19:36:16  STDOUT: "b''"
19:36:16  STDERR: "b"Cloning into 'xxxxxxxx'...\n""
19:36:16  Pulling new dependency xxxxxxxx.
19:36:16  Executing "git rev-parse HEAD"
19:36:16  STDOUT: "b'xxxxxxxx\n'"
19:36:16  STDERR: "b''"
19:36:16    Checking out revision master.
19:36:16  Executing "git remote set-branches origin master"
19:36:16  STDOUT: "b''"
19:36:16  STDERR: "b''"
19:36:16  Executing "git fetch origin --depth 1 --tags master"
19:36:16  STDOUT: "b''"
19:36:16  STDERR: "b'From https://xx.com/xx/template\n * branch            master     -> FETCH_HEAD\n * [new tag]         1.0        -> 1.0\n'"
19:36:16  Executing "git tag --list"
19:36:16  STDOUT: "b'1.0\n'"
19:36:16  STDERR: "b''"
19:36:16  Executing "git reset --hard origin/master"
19:36:16  STDOUT: "b'HEAD is now at xxxxxx Update packages.yml\n'"
19:36:16  STDERR: "b''"
19:36:16  Executing "git rev-parse HEAD"
19:36:16  STDOUT: "b'xxxxxx\n'"
19:36:16  STDERR: "b''"
19:36:16    Checked out at xxxxxx.
```
Then attempts to reclone:
```
19:36:16  Executing "git clone --depth 1 https://xx/:*****@xx.com/xx/template.git xxxxxx"
19:36:16  STDOUT: "b''"
19:36:16  STDERR: "b"fatal: destination path 'xxxxxx' already exists and is not an empty directory.\n""
19:36:16  command return code=128
19:36:16  Updating existing dependency xxxxxx.
19:36:16  Executing "git rev-parse HEAD"
19:36:16  STDOUT: "b'xxxxxx\n'"
19:36:16  STDERR: "b''"
19:36:16    Checking out revision master.
19:36:16  Executing "git remote set-branches origin master"
19:36:16  STDOUT: "b''"
19:36:16  STDERR: "b''"
19:36:16  Executing "git fetch origin --depth 1 --tags master"
19:36:17  STDOUT: "b''"
19:36:17  STDERR: "b'From https://xx.com/xx/template\n * branch            master     -> FETCH_HEAD\n'"
19:36:17  Executing "git tag --list"
19:36:17  STDOUT: "b'1.0\n'"
19:36:17  STDERR: "b''"
19:36:17  Executing "git reset --hard origin/master"
19:36:17  STDOUT: "b'HEAD is now at xxxxxx Update packages.yml\n'"
19:36:17  STDERR: "b''"
19:36:17  Executing "git rev-parse HEAD"
19:36:17  STDOUT: "b'xxxxxx\n'"
19:36:17  STDERR: "b''"
19:36:17  Already at xxxxxx, nothing to do.
```

### Expected Behavior

`dbt deps` should be able to clone the package into the dbt_packages folder successfully. 

### Steps To Reproduce

1. Create PAT for user.
2. Create packages.yml with private repo HTTPS and user:PAT (PAT can be saved in env_var, also happens with hardcoded)
3. Run `dbt deps`.

### Environment

```markdown
- dbt: 1.0.4
```

### What database are you using dbt with?

bigquery

**Comment by nathaniel-may** [comment]
Hi @crystalro0, sorry to hear you're having issues with `dbt deps`.

To help me investigate, could you post the output when you run the same command with json log output? i.e. `dbt --log-format=json deps`. This will help me identify exactly which code paths you're hitting in dbt-core.

**Comment by jtcohen6** [comment]
The method producing those log messages is definitely `clone_and_checkout`:

https://github.com/dbt-labs/dbt-core/blob/5071b00baac3ff2a9bcce565d09661605de52654/core/dbt/clients/git.py#L132-L174

The first time, it completes successfully and fires `GitProgressCheckedOutAt`. In subsequent tries, it finds that the package is already installed, and ultimately fires `GitNothingToDo`. The question is, why is it running `clone_and_checkout` over and over again?

**Comment by nathaniel-may** [comment]
@crystalro0, @jtcohen6 was just able to reproduce this behavior on a call with me just now by creating a package that _depends on itself_. Check this package and see if there might be any circular references causing this loop.

**Comment by nathaniel-may** [comment]
closing in favor of #4975
