### ISSUE TITLE
[CT-423] [Feature] Make release process testable

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#4952]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

We have been repeatedly caught off guard by bugs in the release process that don't manifest until an actual release.  To prevent this we need a method to test them regularly.

Ideas:
- A dry-run mode that does everything except the final push
- Running locally via Nektos/act
- Creating a test runner to integrate GHAs with pyTest so the release process can be tested as part of the current test suite (or in it's own test suite)
- Service checks at release start time to ensure the necessary systems are reachable and functional.

**Comment by emmyoop** [comment]
I'd call this done!  We run nightly tests and can manually test releases.
