### ISSUE TITLE
[CT-428] [Feature] When using `ref()` or `source()`, allow user to specify which components of fully-qualified name to be included

### ISSUE THREAD

**Issue by ybressler** [dbt-labs/dbt-core#4959]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

When using `ref()` or `source()`, DBT will replace the reference with a fully-qualified name (`<database_name>.<schema_name>.<object_name>`, [reference](https://docs.snowflake.com/en/sql-reference/name-resolution.html)). It would be beneficial to allow a user to specify which components of this fully-qualified name to be included.

### Current behavior:
```sql
SELECT * FROM ref('my_table')

-- DBT compiles to:
SELECT * FROM my_db.my_schema.my_table
```

### Desired behavior:
```sql
SELECT * FROM ref('my_table', name_components=['schema', 'object'])

-- DBT compiles to:
SELECT * FROM my_schema.my_table
```
Thus the database is inferred from the one in current use. This is especially relevant when working with cloned databases in Snowflake – see related ticket here: https://github.com/dbt-labs/dbt-snowflake/issues/118

### Describe alternatives you've considered

Can create multiple profiles with specific targets, but this becomes cumbersome, difficult to design and build, and is an elegant solution.

### Who will this benefit?

Anyone using DBT with Snowflake who has considered or is already using cloning. _(As an aside, Snowflake's zero copy cloning is one of its features which sets it apart from its competitors – it would be incredibly valuable to have a more DBT-native solution available)._

Additionally, this can lead to more sophisticated use cases – such as in the case of relative "paths" (as is used in software design). 

### Are you interested in contributing this feature?

Certainly I am, but would need to have someone else own the project management of this task. (I can do this "on the side" so to say.)

### Anything else?

[Snowflake reference on cloning views](https://docs.snowflake.com/en/sql-reference/sql/create-clone.html#:~:text=If%20you%20intend%20to%20point%20a%20view%20to%20tables%20with%20the%20same%20names%20in%20other%20databases%20or%20schemas%2C%20we%20suggest%20creating%20a%20new%20view%20rather%20than%20cloning%20an%20existing%20view.%20This%20guidance%20also%20pertains%20to%20other%20objects%20that%20reference%20objects%20in%20their%20definition.)

**Comment by jtcohen6** [comment]
Note to triageur: `ref()` returns a `Relation` object, which prints out the fully-qualified name as a string by default, but can also be accessed in other ways.

Relevant docs:
- https://docs.getdbt.com/reference/dbt-classes#relation
- https://docs.getdbt.com/reference/dbt-jinja-functions/builtins

**Comment by ybressler** [comment]
> Note to triageur: `ref()` returns a `Relation` object, which prints out the fully-qualified name as a string by default, but can also be accessed in other ways.
> 
> Relevant docs:
> 
> * https://docs.getdbt.com/reference/dbt-classes#relation
> * https://docs.getdbt.com/reference/dbt-jinja-functions/builtins

Wow, I can't believe I never came across these docs while working with DBT! Would you suggest a workaround here is to utilize the reference with a direct invocation of a relationship?
```
-- my_model.sql
SELECT
    *
FROM
    ref('staging', 'my_table')

-- Would instead be
  {% set rel = builtins.ref('staging', 'my_table') %}
  {% set newrel = rel.replace_path(database=None) %}  -- or some equivalent to remove the db reference 
SELECT
    *
FROM
    {{ newrel }}
```

**Comment by emmyoop** [comment]
@ybressler instead of what you propose above, I think you'll actually find the example at the bottom of the [builtins](https://docs.getdbt.com/reference/dbt-jinja-functions/builtins) docs might be just what you need.  You can override the `ref` method that way to not include the database.  Then all the `ref()`s that currently exist will continue to work but will compile down to just `staging.my_table`.

**Comment by jtcohen6** [comment]
@emmyoop is right on! `.replace_path()` is one way to go, but even better is to use the `.include()` classmethod of relations:
```
{% do return(builtins.ref(model_name).include(database=false)) %}
```
I'm going to close this issue, since I think it's perfectly possible in dbt today :)
