### ISSUE TITLE
[CT-434] [Feature] PostGres partial index

### ISSUE THREAD

**Issue by kmedara-wr** [dbt-labs/dbt-core#4970]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I understand since 0.20.0 you there is native support for indexes. but I could not find anything for partial indexes..something like

```
{{config(
    indexes=[
        {'columns': ['status'], 'type': 'partial', 'condition': 'status = 'Active'},
      ]
)
}}
```
or 
```
{{config(
    indexes=[
        {'columns': ['status'], 'type': 'partial', 'operator': '=', 'value': 'Active'},
      ]
)
}}
```

### Anything else?

https://docs.getdbt.com/reference/resource-configs/postgres-configs

**Comment by jtcohen6** [comment]
@kmedara-wr Sorry for the delay getting back to you!

I'm not a Postgres expert, so I was initially a bit skeptical—why not just a new table (filtered projection) that can have a simpler "full" index?—but [the docs](https://www.postgresql.org/docs/current/indexes-partial.html) set me straight:

> Partial indexes are a specialized feature, but there are several situations in which they are useful.
> 
> One major reason for using a partial index is to avoid indexing common values. Since a query searching for a common value (one that accounts for more than a few percent of all the table rows) will not use the index anyway, there is no point in keeping those rows in the index at all. This reduces the size of the index, which will speed up those queries that do use the index.

In terms of the syntax you're proposing: The `condition` example feels fine to me. For consistency with other dbt features, we might call this [`where`](https://docs.getdbt.com/reference/resource-configs/where) or [`filter`](https://docs.getdbt.com/reference/resource-properties/freshness#filter). (I lean `where` personally.) The only good reason I can imagine for the more-structured representation is that dbt could verify the existence and data types of the columns being filtered on. That's a worthwhile undertaking for [metrics](https://docs.getdbt.com/docs/building-a-dbt-project/metrics#filters), but it feels like overkill here.

### Implementation details

Add a new attribute (whichever it's called — `condition`, `where`, or `filter`) to the `PostgresIndexConfig` dataclass, with type `Optional[str] = None`

https://github.com/dbt-labs/dbt-core/blob/6267572ba764724c01386f5b768763aa5711f228/plugins/postgres/dbt/adapters/postgres/impl.py#L19-L23

In the docs, it looks like there's no partial "type," in the sense of passing through the keyword `using` ([index docs](https://www.postgresql.org/docs/current/indexes-types.html)). It would be possible to add validation ensuring that `type = 'partial'` if the new config is set, or the two attributes (`type` + `where`) could be unrelated to each other.

Then, update the `postgres__get_create_index_sql` macro such that, if the new attribute is set, dbt templates out a `where` statement accordingly:

https://github.com/dbt-labs/dbt-core/blob/6267572ba764724c01386f5b768763aa5711f228/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L17-L30

Finally, add a new test case to [`065_postgres_index_tests`](https://github.com/dbt-labs/dbt-core/tree/main/test/integration/065_postgres_index_tests).

I think all of those steps are fairly straightforward and self-contained, so I'm going to mark this a `good first issue`. Is it something you might be interested in contributing? :)

**Comment by kmedara-wr** [comment]
@jtcohen6 yea! sounds like a fun knowledge gainer. thank you for the details

**Comment by alswang18** [comment]
@kmedara-wr are you tackling this? I'd love to give it a shot

**Comment by kinghuang** [comment]
I'm quite interested in being able to declare PostgreSQL partial indexes in dbt. @kmedara-wr, did you get a chance to implement a change?

**Comment by williamkaper** [comment]
> I'm quite interested in being able to declare PostgreSQL partial indexes in dbt. @kmedara-wr, did you get a chance to implement a change?

I'm interested in this change as well @kmedara-wr  @alswang18

**Comment by razze76** [comment]
Any new on this? This would be very good to have

**Comment by christhekeele** [comment]
Also interested in this, it's essential for picking out common cases that represent a small fraction of records a large table (that you do not want to turn into its own intermediate table).

**Comment by kmiller96** [comment]
Still open :/ I'd love to have this as I have a very skewed distribution of values and want to create a partial index for these long-tail values.
