### ISSUE TITLE
[CT-436] [Bug] Passing test create empty tables in the dbt_test__audit schema when the `--store-failures` flag is used

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#4973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

dbt appears to be creating empty tables for passing tests when we ask dbt to store failures `dbt test --store-failures`.

### Expected Behavior

dbt shouldn't create empty tables for passing tests?

### Steps To Reproduce

1. Setup a simple project:

```sql
-- models/my_model.sql
select 1 as user_id
union all
select 1 as user_id
```

```yml
# models/schema.yml
version: 2
models:
  - name: my_model
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
```

2. Run and test:

> Be sure to drop the schema first for reproducibility `drop schema if exists development.dbt_jyeo_dbt_test__audit;`

```
dbt run && dbt test --store-failures
```

3. Check the `dbt_jyeo_dbt_test__audit` schema and notice that there is an empty table for the passing test:

![image](https://user-images.githubusercontent.com/8496748/160515153-3be22162-e9ac-4cea-a853-58e1e7bb927f.png)

### Relevant log output

```shell
01:34:35  Running with dbt=1.0.3
01:34:36  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 180 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
01:34:36  
01:34:42  Concurrency: 1 threads (target='dev')
01:34:42  
01:34:42  1 of 1 START table model dbt_jyeo.my_model...................................... [RUN]
01:34:45  1 of 1 OK created table model dbt_jyeo.my_model................................. [SUCCESS 1 in 3.87s]
01:34:45  
01:34:45  Finished running 1 table model in 9.88s.
01:34:45  
01:34:45  Completed successfully
01:34:45  
01:34:45  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
01:34:50  Running with dbt=1.0.3
01:34:51  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 180 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
01:34:51  
01:35:01  Concurrency: 1 threads (target='dev')
01:35:01  
01:35:01  1 of 2 START test not_null_my_model_user_id..................................... [RUN]
01:35:05  1 of 2 PASS not_null_my_model_user_id........................................... [PASS in 3.68s]
01:35:05  2 of 2 START test unique_my_model_user_id....................................... [RUN]
01:35:09  2 of 2 FAIL 1 unique_my_model_user_id........................................... [FAIL 1 in 4.33s]
01:35:09  
01:35:09  Finished running 2 tests in 18.88s.
01:35:09  
01:35:09  Completed with 1 error and 0 warnings:
01:35:09  
01:35:09  Failure in test unique_my_model_user_id (models/schema.yml)
01:35:09    Got 1 result, configured to fail if != 0
01:35:09  
01:35:09    compiled SQL at target/compiled/my_dbt_project/models/schema.yml/unique_my_model_user_id.sql
01:35:09  
01:35:09    See test failures:
  --------------------------------------------------------------------------
  select * from development.dbt_jyeo_dbt_test__audit.unique_my_model_user_id
  --------------------------------------------------------------------------
01:35:09  
01:35:09  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
```

### Environment

```markdown
- OS: macOS
- Python: `3.9.7`
- dbt: `1.0.3` and `0.21.0`
```

### What database are you using dbt with?

snowflake

### Additional Context

Looks like creating empty tables has been the default so likely not a bug but more of a discussion around "should we be creating empty tables for passing tests"?  I'm thinking maybe not? Since this option is called `store-failures` and not say `store-test-results`.

----

Looks like when that config is true, we create a table for that test then query it (that's what it says in the [docs](https://github.com/dbt-labs/dbt-core/blob/8442fb66a591c4f5353f8baaaaf62f846c5f5171/core/dbt/include/global_project/macros/materializations/tests/helpers.sql#L5-L14) 😄):

https://github.com/dbt-labs/dbt-core/blob/8442fb66a591c4f5353f8baaaaf62f846c5f5171/core/dbt/include/global_project/macros/materializations/tests/test.sql#L5-L33

So to clean up the empty table, we would need to change the following somewhat:

https://github.com/dbt-labs/dbt-core/blob/8442fb66a591c4f5353f8baaaaf62f846c5f5171/core/dbt/include/global_project/macros/materializations/tests/helpers.sql#L5-L14

Add in some `if results = 0 drop relation` logics

**Comment by jtcohen6** [comment]
Thanks @jeremyyeo, you raise some good points!

> Looks like creating empty tables has been the default so likely not a bug but more of a discussion around "should we be creating empty tables for passing tests"?

This was part of the original proposal, and part of the rationale for having test results live in a different schema by default (easier to drop with confidence). I'm definitely open to reconsidering this, though.

> I'm thinking maybe not? Since this option is called store-failures and not say store-test-results.

Fair. At the time, I think `--store-results` or `--store-test-results` was also in consideration. The appeal of `--store-failures` was a clearer connection to why someone would actually want to do this. The right answer here could also be, let's rename the config.

> Add in some if `results = 0 drop relation` logics

Users get to define custom `fail_calc`, `warn_if`, `error_if` logic, which may or may not correspond to "passing test == empty table." I think the rule here would need to look more like: if test result is `success` (a.k.a. `not should_warn and not should_error`), then `drop relation`.

**Comment by anuragbasani** [comment]
So, is there a solution at all that prohibits creating empty tables with 'store_failures'?

**Comment by jeremyyeo** [comment]
> if test result is success (a.k.a. not should_warn and not should_error), then drop relation.

@jtcohen6 doing a bit more research into this over the weekend (i.e. putting `breakpoint()` in random places to figure out more dbt inner workings), I can see that we may be able to achieve the above by tweaking this bit:

https://github.com/dbt-labs/dbt-core/blob/14c2bd9959a8393a7bb7e3f8d49dad69c576f6a4/core/dbt/task/test.py#L198-L199

To be:

```python
        else:
            status = TestStatus.Pass
            if test.config.store_failures or flags.STORE_FAILURES:
                rel = self.adapter.Relation.create(
                    database=test.database,
                    schema=test.schema,
                    identifier=test.alias,
                    type="table",
                )
                self.adapter.drop_relation(rel)
```

I recreated the relation via `self.adapter.Relation.create` because if I just tried `self.adapter.drop_relation(test)` there would be an `'CompiledGenericTestNode' object has no attribute 'type'` error.

On a passing test via `dbt --debug test --store-failures`, I can see these logged:

<details>
<summary>Click to expand...</summary>

```
11:36:34.664357 [debug] [Thread-1  ]: On test.postgres.not_null_my_model_user_name.80997e44b9: /* {"app": "dbt", "dbt_version": "1.2.0a1", "profile_name": "postgres", "target_name": "dev", "node_id": "test.postgres.not_null_my_model_user_name.80997e44b9"} */
drop table if exists "postgres"."public_dbt_test__audit"."not_null_my_model_user_name" cascade
11:36:34.664689 [debug] [Thread-1  ]: Opening a new connection, currently in state closed
11:36:34.680267 [debug] [Thread-1  ]: SQL status: DROP TABLE in 0.02 seconds
11:36:34.687372 [debug] [Thread-1  ]: Using postgres connection "test.postgres.not_null_my_model_user_name.80997e44b9"
11:36:34.687654 [debug] [Thread-1  ]: On test.postgres.not_null_my_model_user_name.80997e44b9: BEGIN
11:36:34.690343 [debug] [Thread-1  ]: SQL status: BEGIN in 0.0 seconds
11:36:34.690825 [debug] [Thread-1  ]: Using postgres connection "test.postgres.not_null_my_model_user_name.80997e44b9"
11:36:34.691250 [debug] [Thread-1  ]: On test.postgres.not_null_my_model_user_name.80997e44b9: /* {"app": "dbt", "dbt_version": "1.2.0a1", "profile_name": "postgres", "target_name": "dev", "node_id": "test.postgres.not_null_my_model_user_name.80997e44b9"} */

        

  create  table "postgres"."public_dbt_test__audit"."not_null_my_model_user_name"
  as (
    
    
    



select *
from "postgres"."public"."my_model"
where user_name is null



  );
    
11:36:34.694423 [debug] [Thread-1  ]: SQL status: SELECT 0 in 0.0 seconds
11:36:34.695673 [debug] [Thread-1  ]: On test.postgres.not_null_my_model_user_name.80997e44b9: COMMIT
11:36:34.695991 [debug] [Thread-1  ]: Using postgres connection "test.postgres.not_null_my_model_user_name.80997e44b9"
11:36:34.696302 [debug] [Thread-1  ]: On test.postgres.not_null_my_model_user_name.80997e44b9: COMMIT
11:36:34.699557 [debug] [Thread-1  ]: SQL status: COMMIT in 0.0 seconds
11:36:34.705501 [debug] [Thread-1  ]: Writing runtime SQL for node "test.postgres.not_null_my_model_user_name.80997e44b9"
11:36:34.706586 [debug] [Thread-1  ]: Using postgres connection "test.postgres.not_null_my_model_user_name.80997e44b9"
11:36:34.707024 [debug] [Thread-1  ]: On test.postgres.not_null_my_model_user_name.80997e44b9: BEGIN
11:36:34.709271 [debug] [Thread-1  ]: SQL status: BEGIN in 0.0 seconds
11:36:34.709583 [debug] [Thread-1  ]: Using postgres connection "test.postgres.not_null_my_model_user_name.80997e44b9"
11:36:34.709876 [debug] [Thread-1  ]: On test.postgres.not_null_my_model_user_name.80997e44b9: /* {"app": "dbt", "dbt_version": "1.2.0a1", "profile_name": "postgres", "target_name": "dev", "node_id": "test.postgres.not_null_my_model_user_name.80997e44b9"} */
select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
      
        select *
        from "postgres"."public_dbt_test__audit"."not_null_my_model_user_name"
    
      
    ) dbt_internal_test
11:36:34.712304 [debug] [Thread-1  ]: SQL status: SELECT 1 in 0.0 seconds
11:36:34.750494 [debug] [Thread-1  ]: Using postgres connection "test.postgres.not_null_my_model_user_name.80997e44b9"
11:36:34.750834 [debug] [Thread-1  ]: On test.postgres.not_null_my_model_user_name.80997e44b9: /* {"app": "dbt", "dbt_version": "1.2.0a1", "profile_name": "postgres", "target_name": "dev", "node_id": "test.postgres.not_null_my_model_user_name.80997e44b9"} */
drop table if exists "postgres"."public_dbt_test__audit"."not_null_my_model_user_name" cascade
11:36:34.753761 [debug] [Thread-1  ]: SQL status: DROP TABLE in 0.0 seconds
11:36:34.755051 [debug] [Thread-1  ]: finished collecting timing info
11:36:34.755489 [debug] [Thread-1  ]: On test.postgres.not_null_my_model_user_name.80997e44b9: ROLLBACK
11:36:34.758718 [debug] [Thread-1  ]: On test.postgres.not_null_my_model_user_name.80997e44b9: Close
11:36:34.759450 [info ] [Thread-1  ]: 1 of 1 PASS not_null_my_model_user_name ........................................ [PASS in 0.13s]
11:36:34.760036 [debug] [Thread-1  ]: Finished running node test.postgres.not_null_my_model_user_name.80997e44b9
11:36:34.761659 [debug] [MainThread]: Acquiring new postgres connection "master"
11:36:34.762114 [debug] [MainThread]: Using postgres connection "master"
11:36:34.762458 [debug] [MainThread]: On master: BEGIN
11:36:34.762794 [debug] [MainThread]: Opening a new connection, currently in state closed
11:36:34.776827 [debug] [MainThread]: SQL status: BEGIN in 0.01 seconds
11:36:34.777160 [debug] [MainThread]: On master: COMMIT
11:36:34.777434 [debug] [MainThread]: Using postgres connection "master"
11:36:34.777949 [debug] [MainThread]: On master: COMMIT
11:36:34.779832 [debug] [MainThread]: SQL status: COMMIT in 0.0 seconds
11:36:34.780166 [debug] [MainThread]: On master: Close
11:36:34.780786 [info ] [MainThread]: 
11:36:34.781139 [info ] [MainThread]: Finished running 1 test in 0.33s.
11:36:34.781473 [debug] [MainThread]: Connection 'master' was properly closed.
11:36:34.781901 [debug] [MainThread]: Connection 'test.postgres.not_null_my_model_user_name.80997e44b9' was properly closed.
11:36:34.787461 [info ] [MainThread]: 
11:36:34.787803 [info ] [MainThread]: Completed successfully
11:36:34.788127 [info ] [MainThread]: 
11:36:34.788473 [info ] [MainThread]: Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
11:36:34.788986 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fea1ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fea1af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fea36a0>]}
11:36:34.789319 [debug] [MainThread]: Flushing usage events
```

</details>

The `drop table` is logged but the test table with no rows still exists - presumably this has to do with not committing the drop table statement - do you know how one would go about committing those?

Let me know if I'm completely off base with the approach here (perhaps we should be evaluating test passing in pure SQL-land and then dropping the test audit table via `{% do adapter.drop_relation() %}` macros instead of breaching 🐍 -land). 

Merci 🙏

**Comment by jtcohen6** [comment]
@jeremyyeo Nice work here! I think your instinct is right, and I'm not in _love_ with the idea of recreating + dropping the relation in Python-land. What about doing something within the materialization here:

https://github.com/dbt-labs/dbt-core/blob/7d0fccd63f0a50e6f8b1130206118d1fcc19b2ae/core/dbt/include/global_project/macros/materializations/tests/test.sql#L40-L46

Like:
```
  {% call statement('main', fetch_result=True) -%}

    {{ get_test_sql(main_sql, fail_calc, warn_if, error_if, limit)}}

  {%- endcall %}
  
  {% set result = load_result('main')['table'].columns.values() %}
  {% set should_warn, should_error = result[1][0], result[2][0] %}
  {% do log(should_warn, info = true) %}
  {% do log(should_error, info = true) %}
  {% if should_store_failures() and not (should_warn or should_error) %}
    {% do log("dropping " ~ target_relation, info = true) %}
  
    {{ adapter.drop_relation(target_relation) }}
  
  {% else %}

    {{ return({'relations': relations}) }}
  
  {% endif %}
```

We shouldn't be returning the relation for cache addition if it's being dropped, right? (Turns out the test task doesn't update the cache at all... but that's a problem for another time.)

I'm also going to recategorize this as an `enhancement`, rather than a `bug`, since it's a known limitation + improvement of an existing feature. And mark it a `help_wanted`, if you're down to keep pushing on it :)

**Comment by yuna-tang** [comment]
Hey, All, will there be any future updates in this store_failures feature?
We are currently using it, and it creates a lot of empty tables for us. Would it be better for us to configure not to store those empty tables if the tests pass?

**Comment by marcilj** [comment]
Any plan on fixing this?

**Comment by 29antonioac** [comment]
Hi, this is interesting for us too, would core devs be open to plan this, or guide external PRs?
