### ISSUE TITLE
[CT-439] Infinite loop on run command

### ISSUE THREAD

**Issue by natebradshaw** [dbt-labs/dbt-core#4977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Executing run on Mac terminal (python 3.10.1, dbt 1.0.4, snowflake) results in an infinite error loop in python. Below is beginning of error message and the loop.
![image](https://user-images.githubusercontent.com/47017976/160726216-f18c55c8-afa0-40f6-948c-b658ad75e065.png)
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/47017976/160726337-623dfa02-ccf0-43bd-92ca-b94836a39bff.png">

### Expected Behavior

I expect the models to be built in snowflake after I execute 'debug' (being told everything is good) and 'run.'

### Steps To Reproduce

1. On Mac, Python 3.10.1, dbt 1.0.4, snowflake connection.
2. In Terminal execute 'dbt init' in own directory.
3. Find .dbt/profiles.yml and update to be as seen on [this page](https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile)
4. Fill in .dbt/profiles.yml as appropriately so when dbt debug is ran it gets the green light BUT leave the data warehouse blank.
6. In directory where new dbt was initalized, run 'dbt run'

### Environment

```markdown
- OS:macOS 12.0.1
- Python:3.10.1
- dbt:1.0.4
```

### What database are you using dbt with?

snowflake

**Comment by joellabes** [comment]
@natebradshaw Python 3.10 support is coming in dbt v1.1, which is currently in beta: https://github.com/dbt-labs/dbt-core/releases/tag/v1.1.0b1

Alternatively you can use Python 3.9 if you don't want to use the beta version. For now I'm going to close this since the fix is coming soon!

**Comment by koconnor-ampion** [comment]
this is rather bizarre, but I am installing dbt-bigquery@1.0.0 and the first thing it installs is python 3.10?!?! Isn't that rather a problem?

`% brew install dbt-bigquery@1.0.0                                
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.10/manifests/3.10.8-1
Already downloaded: /Users/koconnor/Library/Caches/Homebrew/downloads/d4e394cc5e1801239d2f498385a78f2f7b8cf39ba249179edb256c978697bc1b--python@3.10-3.10.8-1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.10/blobs/sha256:017d295e8091cf75e95c8002806865dca73d47b898984fff0a4d00df63a28962
Already downloaded: /Users/koconnor/Library/Caches/Homebrew/downloads/29058597e14d4a159d738fabb14e55c6cb8d19f32891cb63fc96ffd2dc17ec90--python@3.10--3.10.8.monterey.bottle.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ae/0e/34231b11f1b80463f64c5be7d7279de5a5609a47c59c0e34ba7016e4e333/agate-1.6.3.tar.gz`

I had thought it was just looking for the latest, so just prior to this install, I had uninstalled python 3.10 explicitly and installed 3.9
