### ISSUE TITLE
[CT-442] Productionize new adapter scaffolding 

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#4980]
We want to start offering the new adapter scaffolding as the way to create new adapters instead of the existing script.

Tasks:
- [x] Consume the new adapter testing framework
- [x] Manual test runs and verification from a new set of eyes
- [x] Polish work (i.e. are the docs in place, how do our tests and CI look, does the repo follow our best practices that are in place in `dbt-core`) - if this list is long, let's document it and split out the work
- [x] Remove the old script and point to the new repo 

CC: @McKnight-42 @ChenyuLInx let's pair on this

**Comment by McKnight-42** [comment]
List of various PR's open around this
- Docs changes for getdbt.com: https://github.com/dbt-labs/docs.getdbt.com/pull/1362#issuecomment-1104135721
- Removal of old .py file: https://github.com/dbt-labs/dbt-core/pull/5117
- various small prs for Scaffold finalization: https://github.com/dbt-labs/dbt-database-adapter-scaffold/pulls
