### ISSUE TITLE
[CT-458] Catalog queries should filter on specific relations in busy schemas

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#4997]
Related:
- https://github.com/dbt-labs/dbt-bigquery/issues/115
- https://github.com/dbt-labs/dbt-spark/issues/300

To enable this, `_get_catalog_schemas` would need to return a specific set of tables, rather than a set of database-schema combos (`SchemaSearchMap`):

https://github.com/dbt-labs/dbt-core/blob/7f953a6d48a4db254b17fd3929d267e4b6069228/core/dbt/adapters/base/impl.py#L313-L338

Given that we'll need to interpolate table names into actual queries, maybe we could have a rule like: If a database-schema has >100 objects in it, just catalog the entire schema; any less, pass the specific object names as filters.

We see this issue crop up on several adapters, including most recently Redshift. Catalog generation is different from cache generation in two ways:
- The cache needs an exhaustive list of the objects in a schema in order to reliably say whether the object exists or not. The stakes are lower for cataloging.
- We catalog source tables, which commonly live in shared schemas, and in ways that dbt developers cannot easily control/change

**Comment by jeremyyeo** [comment]
Reopening on behalf of enterprise customer.

**Comment by graciegoheen** [comment]
Closing this out, since we completed the dbt-core implementation! 

Adapter implementations are ongoing :)

**Comment by aerielsoriano** [comment]
Reopening on behalf of enterprise customer.
