### ISSUE TITLE
[CT-459] [Feature] Extend Jinja macros to contain required arguments (and maybe type hints)

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4999]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

In the metrics package, I have to jump through all sorts of hoops to check all necessary arguments have been provided to a macro ([example](https://github.com/dbt-labs/dbt_metrics/blob/39ebdaebc72ca80c7ecdbe5df5a0c08adbe5df6f/macros/secondary_calculations/secondary_calculation_period_over_period.sql#L36-L45)). 

I'd love to be able to define required arguments, and wouldn't say no to having type checking as well

### Describe alternatives you've considered

- Checking presence in every macro as currently happens
- Making some sort of helper macro which takes a dict of arguments/requiredness/provided value to dry up the checking

### Who will this benefit?

Developers of complex macros

### Are you interested in contributing this feature?

👶

### Anything else?

https://docs.python.org/3/library/typing.html

**Comment by jtcohen6** [comment]
> having type checking as well

I've wanted something like this for so so long. Even the ability to define type _hints_ inline with macro definitions would be a big improvement. (It is possible to [_document_ the expected arguments and types of a macro](https://docs.getdbt.com/reference/macro-properties), but this is extremely liable to drift: defined in a separate file, requires manual update, and never validated at compile/runtime.)

**Comment by gshank** [comment]
So what would something like this look like? A function in the context which would allow people to define their arguments and check them at the same time? 

You can inspect varargs and kwargs in Jinja macros. I wonder if it would be possible to create a macro_args function that wraps an arg definition dictionary (or something like that) and also checks them. Seems like it might be hard to do both in the same function though...

**Comment by joellabes** [comment]
Not sure! I think I might be trying to turn Python into my first love, C#, where it would be something like 

`{% macro my_macro(required_value_1 string, optional_value_2 int?) %}`

Given that half of Python's schtick is to _not_ care about all of this, I don't know how practical this is, but thought I'd put it out there just in case

**Comment by gshank** [comment]
Yeah, Python's mypy won't work on Jinja :) I think "required" might be doable more than actual type checking, because I think we'd have to implement the type checking which seems like a bridge too far...

**Comment by smitsrr** [comment]
I would LOVE this feature. 
We have a whole library of macros we use across our company, and we have to constantly reference the source code or documentation to remember what arguments are required or optional. 

If this isn't possible inside of core, a vsCode extension that could populate the arg template would be spectacular. Kind of like the new snowflake interface guesses your function then populates the template.

**Comment by joellabes** [comment]
> I think "required" might be doable more than actual type checking

I'll take that!
