### ISSUE TITLE
[CT-462] [Feature] `.yaml` and `.yml` extensions are interchangeable for `profiles.yml`, etc.

### ISSUE THREAD

**Issue by DharamLietz-BO** [dbt-labs/dbt-core#5002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you provide the `--profiles-dir` flag and a valid directory with a file named `profiles.yaml`, dbt will fail to initialize.

### Expected Behavior

dbt should look for both .yml and .yaml extensions

### Steps To Reproduce

1. Create a new project
2. Name your profiles file profiles.yaml
3. Run `dbt --profiles-dir /directory/with/profiles/yaml/file/in/it debug`

### Relevant log output

```shell
$ dbt --profiles-dir "/Users/dharam.lietz/bo/airflow-datawarehouse/.dbt" debug
18:34:45  Running with dbt=1.1.0-b1
dbt version: 1.1.0-b1
python version: 3.9.9
python path: /Users/dharam.lietz/.pyenv/versions/3.9.9/envs/airflow-dwh-3.9.9/bin/python3.9
os info: macOS-12.3-x86_64-i386-64bit
Using profiles.yml file at /Users/dharam.lietz/bo/airflow-datawarehouse/.dbt/profiles.yml
Using dbt_project.yml file at /Users/dharam.lietz/bo/airflow-datawarehouse/dbt/ecs_gl/dbt_project.yml

Configuration:
  profiles.yml file [ERROR not found]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]

1 check failed:
dbt looked for a profiles.yml file in /Users/dharam.lietz/bo/airflow-datawarehouse/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile
```

### Environment

```markdown
- OS: macOS-12.3-x86_64-i386-64bit
- Python: 3.9.9
- dbt: 1.1.0-b1
```

**Comment by gshank** [comment]
I think if we were going to do this, it would have to be for all config type yaml files, i.e. dbt_project.yml, profiles.yml, selectors.yml, packages.yml.  We've lifted the restriction against .yaml files in project schema files. It would, oddly, be a bit harder to do for these other files because that code is sprinkled around the codebase.

**Comment by DharamLietz-BO** [comment]
I think it's the "file doesn't exist" error that threw me for a loop. If it had just said "use .yml, the .yaml extension is not supported", it would've been an easy fix.

Are there command line flags that reference dbt_project, selectors and packages config files that also accept a directory but only look for files with the .yml extension? 

I imagined this being a very small change to update the code that looks for the profiles.yml in the directory provided to also look for the .yaml extension.

**Comment by DharamLietz-BO** [comment]
Something like this: https://github.com/dbt-labs/dbt-core/compare/main...DharamLietz-BO:patch-1

**Comment by DharamLietz-BO** [comment]
Sure, I'll put together sometime this week probably. Thanks for providing a suggested approach 💯 that all makes sense

**Comment by dbeatty10** [comment]
Issue #8738 prompted me to review this issue, and we're re-designating this as a handy feature request rather than a bug.

**Comment by morgan-dgk** [comment]
I'm interested in getting this done. I can see `[clients.system](https://github.com/dbt-labs/dbt-common/blob/main/dbt_common/clients/system.py)` has been extracted to the dbt_common library. Should the suggested changes to `clients.system` be made there? 

Had a poke around `dbt_core` and it seems like there is some variation in how reading project files happens. E.g. Some project file paths are defined as [constants](https://github.com/dbt-labs/dbt-core/blob/0bf38ce294e21c6e4056ed36ba8f35538c10604a/core/dbt/constants.py#L14-L16) whereas `profiles.yml` is passed directly as a string to `os.path.join` in `[profiles.yml](https://github.com/dbt-labs/dbt-core/blob/0bf38ce294e21c6e4056ed36ba8f35538c10604a/core/dbt/config/profile.py#L34)`
