### ISSUE TITLE
[CT-464] [Feature] improve GitHub Git Blame UI by ignoring commits auto-format

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-core#5004]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I was just informed via popup that [Ignoring commits in blame view](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) is now in public preview on GitHub.

This came up as I was trying to debug [this Slack issue for an adapter maintainer](https://getdbt.slack.com/archives/C030A0UF5LM/p1649275178019809). Where #4697 was in the way of me finding out what had recently changed here:
https://github.com/dbt-labs/dbt-core/blob/0ec829a096839bcba8aa9bcdd7ced8db87942f47/core/dbt/semver.py#L88-L90

### Describe alternatives you've considered

I click the previous commit button twice to see the "actual" last time it changed?

### Who will this benefit?

Anyone who looks at Git blame of dbt-core source code in GitHub 

### Are you interested in contributing this feature?

sure!

### Anything else?
Looks like we'd just have to fetch the collect the hashes of any "re-formatting" commit and put them into a `.git-blame-ignore-revs` file

**Comment by jtcohen6** [comment]
> Looks like we'd just have to fetch the collect the hashes of any "re-formatting" commit and put them into a `.git-blame-ignore-revs` file

Woah!! Heck yeah, let's do it

Tagging this one `tech_debt`, but it's almost more like `oss_debt`/`community_debt`

**Comment by iknox-fa** [comment]
What?  My re-formatting will no longer hide the world in a blanket of `Reformat core` commits?  *gasp*
Thanks for bringing this to our attention, I'll get a PR out for it shortly!

**Comment by iknox-fa** [comment]
https://github.com/dbt-labs/dbt-core/pull/5019

**Comment by jtcohen6** [comment]
resolved by #5019!
