### ISSUE TITLE
[CT-470] [Feature] Add option for --defer to favor using --state node even if node exists in current target

### ISSUE THREAD

**Issue by daniel-murray** [dbt-labs/dbt-core#5016]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

This is the current behaviour of the `--defer` flag:

> When the --defer flag is provided, dbt will resolve ref calls differently depending on two criteria:
> Is the referenced node included in the model selection criteria of the current run?
> Does the reference node exist as a database object in the current environment?

The first criterion is always valid. However, it would be useful if the second criterion was optional.

This is because we re-use the same development schemas for multiple features. Therefore you could accidentally use an old version of a node you created for a different feature while using the --defer flag.

### Describe alternatives you've considered

1. Drop all tables in our development schemas after each feature is complete.
It's not practical to delete all tables after each feature due to ongoing QA for old features.

2. Making `--favor-state` a completely different feature to `--defer`
The code change is minimal to implement this feature if used in conjunction with the code already created for `--defer`.

### Who will this benefit?

Anyone using the `--defer` flag so they can have more control over its behaviour. 

### Are you interested in contributing this feature?

Yes would love to! We have a PR ready and tested.

**Comment by iknox-fa** [comment]
Hi @daniel-murray, thanks so much for the contribution!  I'll give this PR a review shortly, but in the meantime can you please fill out [our CLA](https://docs.getdbt.com/docs/contributing/contributor-license-agreements) so we can get this merged in?

**Comment by daniel-murray** [comment]
Hi @iknox-fa no problem at all! Thank you very much. We're waiting on our legal team here to review the CLA and unfortunately, they've asked us to wait until next week. I'll update here as soon as they do.

**Comment by NiallRees** [comment]
Still want this!
