### ISSUE TITLE
[CT-489] Convert <xyz> tests to new adapter framework

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#5053]
Pick an adapter test from this list to convert:
https://www.notion.so/dbtlabs/Converting-older-Test-framework-to-pytest-b19ab90b19b941ecb141b4adc890c1a7#aa26483b738b4f0fba9d76e62a4d35bd

**Comment by McKnight-42** [comment]
Done! https://github.com/dbt-labs/dbt-bigquery/issues/164
