### ISSUE TITLE
[CT-490] [Feature] init: respect --skip-profile-setup when project name is invalid

### ISSUE THREAD

**Issue by varun-dc** [dbt-labs/dbt-core#5056]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

If someone is using dbt in a non-interactive manner, you'd think the `-s` flag would ensure the script isn't stuck in place waiting for some input from the user.

Reproduction on dbt 1.0.4
```
dbt init invalid-project-name -s
```
This will result in dbt showing a prompt to the user for a new project name. Whereas a more sensible thing to do is print an error message and exit.

Ideally, in all cases, when `init` is run with `-s`/`--skip-profile-setup`, we wouldn't prompt the user with any.

Or perhaps there should be a separate flag, for example `--no-interactive`, that skips all interactions and exits if unable proceed?

### Describe alternatives you've considered

There's really no other options besides making sure you enter the right options/args and run with the correct dbt config to ensure the init command doesn't trigger a prompt.

### Who will this benefit?

Anyone using dbt in a non-interactive manner.

### Are you interested in contributing this feature?

Yes

### Anything else?

Related to https://github.com/dbt-labs/dbt-core/issues/4568

**Comment by jtcohen6** [comment]
(Related to https://github.com/dbt-labs/dbt-core/issues/4490 / https://github.com/dbt-labs/dbt-core/pull/4536 as well)

**Comment by stu-k** [comment]
@varun-dc Thank you for the submission!

I agree with your assessment of the expected behavior around `dbt init invalid-project-name -s`. I would also expect not to enter an interactive mode, for the reasons you have described.

It looks like you already have a draft PR up, so we will continue to monitor the of your work there!
