### ISSUE TITLE
[CT-500] Investigate differences in manifest.json output for 'compile' and 'run' commands

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#5079]
When rewriting the docs generate tests I saw some surprising differences between the manifest.json output between the 'compile' (also docs generate) and 'run' commands.

In the manifest.json after a run command the models didn't have any of the compiled attributes (like "compiled", "compiled_sql", "extra_ctes", "extra_cetes_injected", and "compiled_path". I found that a bit surprising because a run command does compile the models.

I was also surprised that the lists of depends_on.macros are different. For example, the "model" model had no macros listed for "compile" or "docs generate" commands, but had ['macro.dbt.run_hooks', 'macro.dbt.drop_relation_if_exists', 'macro.dbt.statement', 'macro.dbt.persist_docs'] listed for "run". I assume that this is because "run" captures all macros used anywhere when it actually really jinja renders it. But I'm wondering if there are any implications for creating dags with macros or selecting using macros.

Determine the reasons for these differences in output, and make the output more consistent if it makes sense.

**Comment by rodik** [comment]
I can confirm this behavior is causing docs issues in our solution. The manifest.json file generated during deployment has "compiled_sql" attributes only for tests, not for models. Our deployment runs commands in this order:
```
dbt run
dbt test
dbt docs generate
```

**Comment by nguyenann13** [comment]
We are also running into this same issue.
