### ISSUE TITLE
[CT-523] [Bug] MacOS M1 dbt-postgres unable to pip install with python 3.7

### ISSUE THREAD

**Issue by varun-dc** [dbt-labs/dbt-core#5119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`pip install dbt-postgres` with python3.7 fails with an error. This appears to be a recent issue, I was able to previous install without error. Happens on a CI build, as well as my local Mac 11.6 machine.

### Expected Behavior

`dbt-postgres` should install without error.

### Steps To Reproduce

1. Setup Python3.7 on your Mac
2. Create a virtualenv and activate it
3. `pip install dbt-postgres`, expect error

### Relevant log output

```shell
$ /Users/varun/.pyenv/versions/3.7.13/bin/python3.7 -m venv venv

$ pip list
-bash: pip: command not found

$ venv   # custom alias, just doing a `source venv/bin/activate`
Activating virtual environment in ./venv

$ which pip
/Users/varun/code/dc/dbt-subsys/venv/bin/pip

$ which python
/Users/varun/code/dc/dbt-subsys/venv/bin/python

$ python --version
Python 3.7.13

$ pip install dbt-postgres
Collecting dbt-postgres
  Using cached dbt_postgres-1.0.5-py3-none-any.whl (13 kB)
Collecting psycopg2-binary~=2.8
  Using cached psycopg2-binary-2.9.3.tar.gz (380 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

$ pip list
Package    Version
---------- -------
pip        22.0.4
setuptools 47.1.0
```

Note that this is running in a virtualenv, setuptools is installed and python3.7 is being used here. 

Additionally, the native python's on this machine are,
```
$ python --version
Python 2.7.16

$ python3 --version
Python 3.8.9
```

But above I've used `pyenv` to force 3.7 for the purposes of installing `dbt-postgres`

### Environment

```markdown
- OS: MacOS 11.6.4
- Python: 3.7.13 (virtualenv)
- dbt: latest (`pip install dbt-core dbt-postgres` also fails)
```

### What database are you using dbt with?

postgres

**Comment by varun-dc** [comment]
This actually appears to be an upstream issue https://github.com/psycopg/psycopg2/issues/1286.
Please feel free to close if dbt-core isn't able to do anything about this, I'm going to leave it open for now in case there is any follow up comments from the dbt team.

**Comment by ChenyuLInx** [comment]
Hey, @varun-dc Sorry to get back to you late, and thanks for digging into this. Did[ this method](https://lifesaver.codes/answer/psycopg2-binary-fails-to-install-on-macos-big-sur-11-0-1-and-python-3-9-0-with-possible-workaround-1200) work for you?

**Comment by varun-dc** [comment]
Hi,

I'm quite unsure what exactly is going on. Right now, this isn't a blocker for me, so I'm not affected, but this. But perhaps there may be others who are still affected by this.

My situation was around using Python 3.7 with pyenv, which may be resulting in other complications due to libffi and _ctypes. So I can't be sure if the root cause is something related to dbt-postgres/dbt-core installation or something on my system.

For now, I can close this and if anyone else needs to follow up here with some additional details for the dbt team, they can re-open this issue and provide more concrete details than I'm able to at this time.

**Comment by Rakshitha-BR** [comment]
Hi,
I recently got mac m1.
dbt install postgres is failing with

Collecting psycopg2-binary~=2.8
  Using cached psycopg2-binary-2.9.3.tar.gz (380 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running egg_info
      creating /private/var/folders/l2/6ksjtxb15wjbvh5xlcqj1f4w0000gn/T/pip-pip-egg-info-54ej1_7t/psycopg2_binary.egg-info
      writing /private/var/folders/l2/6ksjtxb15wjbvh5xlcqj1f4w0000gn/T/pip-pip-egg-info-54ej1_7t/psycopg2_binary.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/l2/6ksjtxb15wjbvh5xlcqj1f4w0000gn/T/pip-pip-egg-info-54ej1_7t/psycopg2_binary.egg-info/dependency_links.txt
      writing top-level names to /private/var/folders/l2/6ksjtxb15wjbvh5xlcqj1f4w0000gn/T/pip-pip-egg-info-54ej1_7t/psycopg2_binary.egg-info/top_level.txt
      writing manifest file '/private/var/folders/l2/6ksjtxb15wjbvh5xlcqj1f4w0000gn/T/pip-pip-egg-info-54ej1_7t/psycopg2_binary.egg-info/SOURCES.txt'

      Error: pg_config executable not found.

      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:

          python setup.py build_ext --pg-config /path/to/pg_config build ...

      or with the pg_config option in 'setup.cfg'.

      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.

      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by tsinghammer** [comment]
I have the same issue on a Mac M machine. I've installed `psycopg2-binary` package as proposed, but it still tries to build it from source.
Anyone already succeeded with this?
It's a pity that the brew formula is not available anymore. That was so simple 😊
