### ISSUE TITLE
[CT-534] Add adapter plugin versions to telemetry + context

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5124]
Today, there are a few places where we return `dbt_version`, which is really the installed version of `dbt-core`. Now that dbt-core and adapter plugins can differ for patch versions (and patches only!), let's make available both:
- The version of `dbt-core` (current)
- The version of plugin(s)

For point 2, that could be either:
- The current "active" adapter plugin, and any upstream plugins used by the active plugin, e.g. `dbt-redshift -> dbt-postgres`. There are methods for this in [`adapters/factory.py`](https://github.com/dbt-labs/dbt-core/blob/979e1c74bf55bc6849c89accd75ce86531e7a1f9/core/dbt/adapters/factory.py#L124-L166)
- All installed plugins

I'm pretty happy with whichever is easier, and has fewer downstream implications.  Update from BLG:  Ensure this is structured data.

## Context

Made available to the dbt-Jinja context as `dbt_version`:

https://github.com/dbt-labs/dbt-core/blob/979e1c74bf55bc6849c89accd75ce86531e7a1f9/core/dbt/context/base.py#L208-L226

Which is also included in the default query comment for all queries:

https://github.com/dbt-labs/dbt-core/blob/979e1c74bf55bc6849c89accd75ce86531e7a1f9/core/dbt/contracts/connection.py#L200-L204

For backwards compatibility, we'd want `dbt_version` to continue returning the core version. Looking forward, we could update this to be a dictionary containing the core version and active plugin(s).

## Telemetry

Reported in our anonymous usage tracking:

https://github.com/dbt-labs/dbt-core/blob/979e1c74bf55bc6849c89accd75ce86531e7a1f9/core/dbt/tracking.py#L201

Let's update that to be `core_version` and `plugin_versions` (active or installed, whichever is simpler). We don't need to worry as much about backwards compatibility here, since we can update the modeling logic on our end :)

**Comment by dataders** [comment]
what's the impact for partner adapter developers here? does this make it easier to standardize on logging `dbt-<<ADAPTER>>==<<VERSION>>` in lieu of just "dbt"?
