### ISSUE TITLE
[CT-534] Create reusable `version` methods, task

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5125]
We've done a bunch of good work in [`get_version_information()`](https://github.com/dbt-labs/dbt-core/blob/979e1c74bf55bc6849c89accd75ce86531e7a1f9/core/dbt/version.py#L19) lately.

Let's take this one step further, by making it possible to return structured response from that method, in addition to the pretty-printed text currently returned by `dbt --version`.

Then, we can use that structured response to enable:
- https://github.com/dbt-labs/dbt-core/issues/5124
- https://github.com/dbt-labs/dbt-rpc/issues/74 (which may want a "real" version task defined inside `dbt-core`)

**Comment by iknox-fa** [comment]
This ticket isn't really defining any work.  Closing in favor of #5124 and dbt-rpc #74.
