### ISSUE TITLE
[CT-545] [Feature] Add CircleCI orb for modified models (like path-filtering)

### ISSUE THREAD

**Issue by jelstongreen** [dbt-labs/dbt-core#5135]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

In a dbt monorepo structure for multiple projects it is common to want CI to run for individual projects and not others. This could be done using the [path-filtering orb](https://circleci.com/developer/orbs/orb/circleci/path-filtering#orb-source) but the issue with that is it only checks for a git diff in files and would not find changes to schema files.

The fix for this (as is the case with doing slim ci) is to use manifests and work out what files have changed from there. It would be great if a public orb were available for filtering CI workflows based around what models have changed in a commit. 

### Describe alternatives you've considered

Currently we use state modified but this still leads to all workflows running for each project, just with empty model lists. The solution would prevent the workflow running if no model changes have been detected in a given manifest. 

### Who will this benefit?

Anyone using a slim CI build and Circle CI with a multi-project repo (and single project in fact - this would just avoid unneccessary workflows running in a cleaner fashion than doing `dbt run` with no matching selected models.

### Are you interested in contributing this feature?

Yes

### Anything else?

https://circleci.com/developer/orbs/orb/circleci/path-filtering#orb-source
https://circleci.com/docs/2.0/creating-orbs/
https://circleci.com/docs/2.0/configuration-cookbook/?section=examples-and-guides#execute-specific-workflows-or-steps-based-on-which-files-are-modified
https://medium.com/nerd-for-tech/mastering-monorepos-with-circlecis-new-dynamic-config-2e187fe7934c

**Comment by jelstongreen** [comment]
Think this may be possible with just path-filtering, closing in the meantime but will re-open if not the case.

**Comment by jelstongreen** [comment]
@jtcohen6 A lot of the multi-region stuff is solvable with path-filtering but I still think there's lots of scope for optimisation of CI with this orb available so I'd like to reopen - particularly interested in ability to isolate which steps of a split out `seed`,`snapshot`,`run`,`test` CI setup. If an orb were able to use a manifest to isolate which types of nodes had been edited we could optimise the CI even further.

**Comment by jtcohen6** [comment]
@jelstongreen Just want to make sure I understand the ask.

Right now, you have two tools at your disposal:
- CircleCI's path-filtering orbs (not dbt-specific): avoid spinning up a CircleCI process if zero files in the project/directory have changed
- `dbt [run|list|etc] --select state:modified`: will spin up a CircleCI process, but a very quick one if dbt finds that no nodes have changed

The thing you're saying is, when a path in the project _has_ changed, but it doesn't result in a node having changed—there should be a CircleCI orb that introspects `manifest.json` and performs the same sort of comparison that `dbt ls -s state:modified` is doing, without needing to actually invoke dbt.

Am I understanding you right? If so, I don't think this is something we'd prioritize building, but I'd be happy to see you work on it / share it with other members of the community.

**Comment by jelstongreen** [comment]
> The thing you're saying is, when a path in the project has changed, but it doesn't result in a node having changed—there should be a CircleCI orb that introspects manifest.json and performs the same sort of comparison that dbt ls -s state:modified is doing, without needing to actually invoke dbt.

@jtcohen6 I think the issue I am actually having is that a schema.yml can change for a model without actually appearing in `dbt ls` such as when a model's description is edited - apart from that I think most optimisations around CI within a single project can be solved in `dbt ls` - side question, is it intended that a desc for a model can be edited without causing it to appear in `dbt ls state:modified` ? If so I'll raise a seperate feature request for adding a kwarg to dbt ls for being more heavy handed for CI purposes. 

Will post in slack if I ever get the orb put together, thanks for the response!

**Comment by jtcohen6** [comment]
@jelstongreen Ah, dbt tries to be a bit clever here! If a model's description has changed, dbt will consider that model modified (for the purposes of running it in CI) if and only if it has `persist_docs` enabled.

There's a sub-selector for just that case, `state:modified.persisted_descriptions`: https://docs.getdbt.com/reference/node-selection/methods#the-state-method

Idea is, if the description's not actually being persisted to the model's SQL, it's not really a functional modification — it's just a change to metadata. Adding/removing `tags` and `meta` fields is similar, although those may also be picked up `state:modified.configs` (better safe than sorry).

You're definitely welcome to open an issue if you think `state:modified` should be less clever and include _all_ types of changes, by default. I think there's a fair case to make.

**Comment by jelstongreen** [comment]
Ah ok great, I'll switch my project to persist docs by default which will solve this, thanks again for the prompt responses!
