### ISSUE TITLE
[CT-547] [Bug] incremental materializations first run doesn't respect unique key

### ISSUE THREAD

**Issue by rdbenoit-orennia** [dbt-labs/dbt-core#5138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running an incremental model for the first time it doesn't use the unique_key plus incremental_strategy. This means that if your model doesn't have duplicate elimination inside of it that duplicates will appear on the first run of model. Subsequent models will use the incremental strategy and unique_key to eliminate duplicates.

### Expected Behavior

No matter if it is first run or subsequent run the same results should happen. That is the unique_key should cause a merge (or whatever incremental_strategy is set) to happen and therefore eliminate duplicates. 
The biggest issue with this is that if you need to refresh/rebuild an incremental model you can get different results then if that table had been build incrementally.

### Steps To Reproduce

1. start with base model that has 1 row, key of 'abc'
2. create incremental model that references that base model
3. run incremental model and resulting table will have 1 row with key 'abc'
4. add new row to base model with key of 'abc'
5. run incremental model and table will remain with a single row for key 'abc'
6. re-run incremental model with full-refresh, resulting incremental model table will now have 2 rows each with the key 'abc'

### Environment

```markdown
- OS:linux
- Python: 3.9.5
- dbt:1.0
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment]
@rdbenoit-orennia Thanks for the thorough write-up!

You're right, dbt does not enforce uniqueness (via `unique_key`) for the records returned by your model—neither when the table is first being created, nor in subsequent runs. Rather, dbt _uses_ the information provided by `unique_key` to reconcile new and old records, within its `merge` or `delete` + `insert` statement(s).

In this way, `unique_key` is a thing that you (the user) are responsible for ensuring, with whatever grouping or windowing or deduplicating logic is appropriate to your model. It's not something dbt takes care of on your behalf.

We have some docs on this, within the larger docs on incremental models: https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#defining-a-uniqueness-constraint-optional. I'd be curious to hear if those docs offer clarity on this point, or if this is a point we need to make more clearly.

### How would this work?

Let's imagine that dbt _should_ enforce uniqueness on a model that has `unique_key` defined, during its first run. How might that work?

Following your example, let's say you have a model like:
```sql
{{ config(materialized = 'incremental', unique_key = 'id') }}

-- your model sql
select * from {{ ref('base_model_with_dupes') }}
```
What dbt runs:
```sql
create table database.schema.table as (
  -- your model sql
  select * from database.schema.base_model_with_dupes
  
  -- automatically dedupe? raise an error? what should dbt be doing here?
  -- snowflake sql only
  qualify row_number over (partition by id order by random()) = 1
)
```
Deduplicating records requires judgment and familiarity with the underlying data. That's more than dbt has in this case. If (and only if) you're able to pass truly unique records into your incremental model, as identified by `unique_key` — then dbt can reliably handle the incremental processing and reconciliation of your model's new data with the preexisting table.

### future?

Given the semantic overlap between `unique_key` and `unique` tests, we might think about (eventually) offering a more ergonomic way to define both at once.

Today:
```yml
# models/config.yml
version: 2

models:
  - name: my_model
    config:
      materialized: incremental
      unique_key:  id
    columns:
      - name: id
        tests:
          - unique
```
Imagine:
```yml
# models/config.yml
version: 2

models:
  - name: my_model
    config:
      materialized: incremental
      primary_key:  id  # this has the effect of adding a 'unique' test on column 'id', and setting 'unique_key'
```

That's further out. In the meantime, I'm going to close this as `wontfix`.
