### ISSUE TITLE
[CT-548] [Bug] Error log is directed to stdout instead of stderr

### ISSUE THREAD

**Issue by setyven** [dbt-labs/dbt-core#5142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running dbt commands (`run`, `test`, haven't tested other methods), any runtime error during invocations will produce logs to stdout instead of stderr.

This is inconsistent with the `dbt.log` file that dbt command invocation produces, where log level there indicates that dbt recognises several log outputs as error logs. 

### Expected Behavior

Default log from debug to warning should still be directed to stdout, while error log should be directed to stderr.

### Steps To Reproduce

1. Tested in dbt-core and dbt-bigquery version 1.0.0
2. Intentionally create a problematic model, such as one that queries to non-existent table.
3. Run that model and redirect the error to a file: `dbt run a_model 2> err.log`
4. This will result in an empty `err.log` file.
5. Meanwhile `logs/dbt.log` will indicate that there was error log produced in the run.

### Relevant log output

This is the result from `logs/dbt.log`, where the model name is omitted and replaced with `a_model`.
```shell

05:45:05.975086 [debug] [Thread-1  ]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'e8557104-c2f3-4d2e-88af-01783c84fe8e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11dd05a00>]}
05:45:05.975679 [error] [Thread-1  ]: 1 of 1 ERROR creating table model setyven.a_model......... [ERROR in 0.68s]
05:45:05.976270 [debug] [Thread-1  ]: Finished running node model.a_model
05:45:05.977986 [debug] [MainThread]: Acquiring new bigquery connection "master"
05:45:05.978962 [info ] [MainThread]:
05:45:05.979488 [info ] [MainThread]: Finished running 1 table model, 1 hook in 12.02s.
05:45:05.979923 [debug] [MainThread]: Connection 'master' was properly closed.
05:45:05.980236 [debug] [MainThread]: Connection 'model.a_model' was properly closed.
05:45:06.522754 [info ] [MainThread]:
05:45:06.523152 [info ] [MainThread]: Completed with 1 error and 0 warnings:
05:45:06.523555 [info ] [MainThread]:
05:45:06.523894 [error] [MainThread]: Runtime Error in model a_model a_model.sql)
05:45:06.524234 [error] [MainThread]:   404 Not found: Table a_model was not found in location X
```

### Environment

```markdown
- OS: MacOS 10.14.6
- Python: 3.8.5
- dbt: 1.0.0
```

### What database are you using dbt with?

bigquery

### Additional Context

After scouring the issues list, I wonder if this came as a side effect from this [fix](https://github.com/dbt-labs/dbt-core/pull/4368).

**Comment by setyven** [comment]
If anyone can give a pointer, I'll be happy to try creating a fix for this.

**Comment by ChenyuLInx** [comment]
Het @setyven , Thanks for opening this!
I did some test locally following your steps to reproduce and found the following things

1. the there will be log in err.log no matter what version you use, here's a example result
> 22:40:53  Running with dbt=1.0.5
22:40:54  [WARNING]: Did not find matching node for patch with name 'customers' in the 'models' section of file 'models/schema.yml'
22:40:54  [WARNING]: Test 'test.jaffle_shop.unique_customers_customer_id.c5af1ff4b1' (models/schema.yml) depends on a node named 'customers' which was not found
22:40:54  [WARNING]: Test 'test.jaffle_shop.not_null_customers_customer_id.5c9bf9911d' (models/schema.yml) depends on a node named 'customers' which was not found
22:40:54  [WARNING]: Test 'test.jaffle_shop.relationships_orders_customer_id__customer_id__ref_customers_.c6ec7f58f2' (models/schema.yml) depends on a node named 'customers' which was not found
22:40:54  Found 1 model, 9 tests, 1 snapshot, 0 analyses, 392 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics
22:40:54  
22:40:55  Concurrency: 1 threads (target='dev')
22:40:55  
22:40:55  1 of 1 START view model dbt_chenyu.orders....................................... [RUN]
22:40:55  1 of 1 ERROR creating view model dbt_chenyu.orders.............................. [ERROR in 0.04s]
22:40:55  
22:40:55  Finished running 1 view model in 1.13s.
22:40:55  
22:40:55  Completed with 1 error and 0 warnings:
22:40:55  
22:40:55  Compilation Error in model orders (models/orders.sql)
22:40:55    Trying to create view `dbt-dev-168022`.`dbt_chenyu`.`orders`, but it currently exists as a table. Either drop `dbt-dev-168022`.`dbt_chenyu`.`orders` manually, or run dbt with `--full-refresh` and dbt will drop it for you.
22:40:55    
22:40:55    > in macro bigquery__handle_existing_table (macros/materializations/view.sql)
22:40:55    > called by macro handle_existing_table (macros/materializations/models/view/helpers.sql)
22:40:55    > called by macro create_or_replace_view (macros/materializations/models/view/create_or_replace_view.sql)
22:40:55    > called by macro materialization_view_bigquery (macros/materializations/view.sql)
22:40:55    > called by model orders (models/orders.sql)
22:40:55  
22:40:55  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1

2. if you use pre 1.1.0rc1(still in RC version), those logs don't have color. But after 1.1.0rc1, we have a community member make those also contain color.

What will you see if you do `cat err.log`?

**Comment by setyven** [comment]
Hi Chenyu, thanks for picking up this issue!
If I cat the log file, I'll get an empty file. It's probably worth noting that I'm using dbt 1.0.0 instead of 1.1.0-rc. And to be precise, this is the command that I ran
```bash
dbt run --target target-name --profiles-dir ./profiles --models model_name 2> err.log
```

**Comment by iknox-fa** [comment]
Hi @setyven, thanks for the bug report.  I'm going to check with the team, but IIRC this is intended behavior (although I don't recall exactly why).  I'll follow up with more info when I have it.

**Comment by iknox-fa** [comment]
@setyven After some digging it seems this isn't actually intended behavior and represents a piece of work that we didn't tackle when we re-factored our logging framework late last year.

See https://github.com/dbt-labs/dbt-core/issues/4836 for details.

**Comment by setyven** [comment]
Hi @iknox-fa , apology for the delay in responding. 

Yes you're right, from the [docs](https://docs.getdbt.com/reference/events-logging) this does seem to be the intended behaviour, so in retrospect I should have flagged this as feature change/request rather than a bug. However IMHO, this is still a request worth considering, as it will be easier to redirect any stack trace from any runtime error without having to build a separate parser for the output logs.

**Comment by setyven** [comment]
Sorry I somehow missed your previous message. I'll try to digest that thread some time this week. Thanks!

**Comment by kimfrie** [comment]
Hey all,

I'd be pretty much interested in the resolution of this.

**Comment by razsightfull** [comment]
Is there any update about this one?

**Comment by AnasBalk** [comment]
Any updates about this issue

**Comment by babaMar** [comment]
Running into this issue while executing `dbt compile` in an Azure Devops pipeline task. The error message is redirected to `stdout` so the task succeeds even when there's an error, really annoying. I understand this is not planned for resolution, however it would be great to know if there's a way to change this behavior?
