### ISSUE TITLE
[CT-559] [Bug] Partial parser does not recognize default values in envvars

### ISSUE THREAD

**Issue by ajbosco** [dbt-labs/dbt-core#5155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The partial parser does not support default values for envvars. As a result, it will consider all sources deleted since the current value is `None` even if the default value and previous value are the same and unchanged.

https://github.com/dbt-labs/dbt-core/blob/220d8b888c44d43fe54539684f397a05dacf0f02/core/dbt/parser/partial.py#L959

### Expected Behavior

Since nothing has been changed in the files, I would expect the partial parser to detect the default value matches the previous value and not reparse all the files.

### Steps To Reproduce

Include an envvar like this in a source YAML file:

```
schema: '{{ env_var("OUR_SCHEMA_ENV_VAR", "default_value") }}'
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.9.12
- dbt: 1.0.4
```

**Comment by jtcohen6** [comment]
@ajbosco Thanks for opening! Original thread with `dbt parse` output: https://github.com/dbt-labs/dbt-core/issues/3164#issuecomment-1109787404. It sounds like this might save your team up to 2 min on each re-parse.

I'll let someone from the Language team offer their sense of what a fix here might require.

**Comment by gshank** [comment]
The code that stores the env_var value will actually use the default value if one is provided. So I'm not exactly sure why this wouldn't be working. I'll have to do some investigation.

**Comment by gshank** [comment]
Is it possible that you're using the same env_var in a different place without a default?

**Comment by gshank** [comment]
Maybe instead of saving the default value in the env_var, we could save something like "DEFAULT" and then not compare those env_vars, since presumably if the default changed, the file itself would be marked as changed.
