### ISSUE TITLE
[CT-576] [Bug] `dbt debug` looks in wrong place for `dbt_project.yml`

### ISSUE THREAD

**Issue by aaronfowles** [dbt-labs/dbt-core#5185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am expecting to run `dbt init my_proj` and have the `dbt_project.yml` exist under `my_proj/dbt_project.yml`. It does - that's fine.

However, when I run `dbt debug`, it errors and says it cannot find `dbt_project.yml` in the root of the directory (where it is not). Why is it looking there?

### Expected Behavior

I would expect `dbt debug` to look for `dbt_project.yml` under the dbt project directory rather than the git project root.

### Steps To Reproduce

1. On Debian 10 Buster with Python 3.9.9 installed using a venv at root of git repo.
2. Only `dbt-postgres, dbt-bigquery` are installed.
3. run `dbt init my_proj`
4. run `dbt debug`

### Relevant log output

```shell
12:22:25  Running with dbt=1.0.6
dbt version: 1.0.6
python version: 3.9.9
python path: /home/aaronfowles/projects/analytics-engineering/.venv/bin/python
os info: Linux-5.10.101-14962-gede4ccb2bf53-x86_64-with-glibc2.28
Using profiles.yml file at /home/aaronfowles/.dbt/profiles.yml
Using dbt_project.yml file at /home/aaronfowles/projects/analytics-engineering/dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [ERROR not found]

Required dependencies:
 - git [OK found]

Connection:
  method: oauth
  database: prj-hq-d-dbt-afa8
  schema: transform
  location: EU
  priority: interactive
  timeout_seconds: 300
  maximum_bytes_billed: None
  execution_project: prj-hq-d-dbt-afa8
  Connection test: [OK connection ok]

1 check failed:
Could not load dbt_project.yml
```

### Environment

```markdown
- OS:Debian 10 Buster
- Python: 3.9.9
- dbt: 1.0.6
```

### What database are you using dbt with?

bigquery

**Comment by aaronfowles** [comment]
It's just dawned on me that I think you are supposed to run `dbt` CLI commands from the specific dbt project root, not the git root. If that's the case then this is not an issue at all!

**Comment by jtcohen6** [comment]
@aaronfowles That's correct! `dbt init` creates a new dbt project in a new (sub)directory. Every other dbt command expects to be run from within an already-existing dbt project. (Not counting `dbt --version`.)

Definitely open to hearing that we should have clearer documentation on this. I also recall an issue (https://github.com/dbt-labs/dbt-core/issues/4141) a few months ago about whether `dbt init` should create the dbt project within the _current_ working directory; I decided against it at the time.

**Comment by aaronfowles** [comment]
> @aaronfowles That's correct! `dbt init` creates a new dbt project in a new (sub)directory. Every other dbt command expects to be run from within an already-existing dbt project. (Not counting `dbt --version`.)
> 
> Definitely open to hearing that we should have clearer documentation on this. I also recall an issue (#4141) a few months ago about whether `dbt init` should create the dbt project within the _current_ working directory; I decided against it at the time.

Thanks for that! I'm new to dbt (literally just going through the tutorial!). I guess if the idiom is multiple dbt projects in a git project then the current approach definitely makes sense. I guess if there's only ever one project though then perhaps the sub dir makes less sense. I will learn to use the tool first though before I form any strong opinions!

**Comment by vrtoaso** [comment]
Hi all, 

I came across this thread searching the same error. 

In my case the default location of the dbt_project.yml file was not the path declared in the terminal output after running dbt debug

The actual location of the file was in the project folder I created after running dbt init

<img width="431" alt="dbt issue" src="https://user-images.githubusercontent.com/6005555/175185456-a4b7fbe6-8841-418a-b0d2-e5ad9110b576.png">

My question here is what is best practice? Relocating the dbt_project.yml file to the directory thats being declared or reassign the path to point to the actual location of the dbt_project.yml file?

Im new to dbt and pretty new to running tools like this in terminal so any guidance on how to change the path is appreciated.

**Comment by ChenyuLInx** [comment]
@vrtoaso  [this example repo](https://github.com/dbt-labs/jaffle_shop) is how I structure my project, hope it helps!

**Comment by lrazuri** [comment]
I had a similar error. I had a typo in my `~/.dbt/profiles.yml` the issue for me was that I didnt have a space between my users and user name `user:username` when it should have been `user: username`

**Comment by Bilbottom** [comment]
Just noting for future viewers that the dbt CLI has a `--project-dir` argument which you can use to specify the path to the `dbt_project.yml` file. There's also the equivalent `-profiles-dir` for the `profiles.yml` file

Although these commands aren't expected to be used if you've run `dbt init` (hence this issue), if you _do_ want your files to be in different locations, these arguments allow this; supposed that your `dbt_project.yml` file is in the directory `path/to/project` and your `profiles.yml` file is in the directory `path/to/profiles`, then you can run:

```
dbt debug --project-dir path/to/project --profiles-dir path/to/profiles
```

**Comment by ald0405** [comment]
Had a similar issue with somebody in my team; seemed to be resolved when we moved the repo from the root to another directory.
