### ISSUE TITLE
[CT-583] [Bug] adapter.load_relation does not exist

### ISSUE THREAD

**Issue by jarno-r** [dbt-labs/dbt-core#5192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Spark, the following fails:
````
{% if  adapter.load_relation(this) is not none %}
{% endif %}
````
with this error:
````
'dbt.context.providers.RuntimeDatabaseWrapper object' has no attribute 'load_relation'
````

### Expected Behavior

No error.

### Steps To Reproduce

In DBT cloud or CLI with Spark connector.
dbt-core 1.0.4
dbt-spark 1.1.0

Paste the code into a Scratchpad and press compile, or put in any .sql and run `dbt compile`.

### Environment

```markdown
dbt-core 1.0.4
dbt-spark 1.1.0
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

I'm not sure if this is Spark specific or applies to other adapters.
adapter.get_relation() can be used as a workaround.

**Comment by jtcohen6** [comment]
Hey @jarno-r, thanks for opening!

`load_relation` isn't an adapter method, it's a macro in the global project [here](https://github.com/dbt-labs/dbt-core/blob/a2b3602485a8e9e03eea51caa9ffdd974e5900c6/core/dbt/include/global_project/macros/adapters/relation.sql#L69-L76). So this should work if you just call it as `load_relation` (or `dbt.load_relation`) instead.

I also see you're using dbt-core v1.0.4 with dbt-spark v1.1.0, which are incompatible. Core + plugins are compatible [at the minor-version level](https://docs.getdbt.com/docs/core-versions#how-we-version-adapter-plugins)

**Comment by jtcohen6** [comment]
@jarno-r You're totally right! Sorry about that. I just opened a quick PR to get those docs fixed: https://github.com/dbt-labs/docs.getdbt.com/pull/1399

**Comment by jtcohen6** [comment]
Closing as resolved by update to user docs, rather than a code change
