### ISSUE TITLE
[CT-584] [Bug] `dbt build` doesn't respect n-plus operator

### ISSUE THREAD

**Issue by foundinblank** [dbt-labs/dbt-core#5193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I feel I might’ve run into a node selection bug when using `dbt run` vs `dbt build`. My understanding is that dbt build is supposed to respect [standard selection syntax](https://docs.getdbt.com/reference/commands/build) but it does not seem to be handling n-plus selection correctly. 

The behavior I’m seeing:
`dbt run -s 3+dim_users`  - only runs dim_users and 1st, 2nd, and 3rd degree upstream models
`dbt build -s 3+dim_users` - runs all upstream models, as if it’s just doing `+dim_users`

### Expected Behavior

`dbt build -s 3+dim_users` should run only `dim_users` and 1st, 2nd, and 3rd degree upstream models. 

### Steps To Reproduce

1. Be in a regular dbt environment with a basic DAG
2. Run `dbt run -s 1+model_name` - the output should be that dbt runs only `model_name` and all 1st degree upstream models
3. Run `dbt build -s 1+model_name` - the output is that dbt runs _all_ upstream models

### Environment

```markdown
- OS: macOS Big Sur 11.6
- Python: 3.7.9
- dbt: 1.0.1
```

### What database are you using dbt with?

snowflake

**Comment by iknox-fa** [comment]
Hi @foundinblank , thanks for the bugreport.  Unfortunately, I'm having a hard time replicating the issue locally.  Could you provide a sample project so I can try to sort out what's going wrong?

**Comment by patkearns10** [comment]
tested this on 1.4 and can confirm: https://www.loom.com/share/2dd237b0da834a6589211a8e23c8d77f

Confirmed this is happening in the IDE and locally cli.
`dbt run -s 2+some_model`  and `dbt build -s 2+some_model` return a different number of models
Confirmed this is also happening in the other direction, ie. 
`dbt run -s some_model+2`  and `dbt build -s some_model+2` return a different number of models

**Comment by ttusing** [comment]
I can also confirm this behavior.

**Comment by jtcohen6** [comment]
From a little poking around - I think the fix in https://github.com/dbt-labs/dbt-core/pull/7431 could address this one too! By filtering out the extra edges that we add during `build`, to block/skip downstream models on upstream models' tests.
