### ISSUE TITLE
[CT-585] [Bug] minor typo in dbt-cli docs for parse command

### ISSUE THREAD

**Issue by bavardage** [dbt-labs/dbt-core#5195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the output from the cli for the parse command reads

```
    parse               Parsed the project and provides information on performance
```

### Expected Behavior

it should read "Parses the project"

### Steps To Reproduce

run dbt command with no args

### Environment

```markdown
- OS: Mac OS X
- Python: 3.9.12
- dbt: 1.0.4
```

**Comment by iknox-fa** [comment]
Fixed by #5199
