### ISSUE TITLE
[CT-588] [Bug]drop_test_schema changes

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-core#5200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when working with redshift tables made from tests aren't being deleted at end of test. due to issue with tables being connected to current transactions which prevents drop table cascade calls from working in redshift

### Expected Behavior

tests be deleted during due course of testing.

### Steps To Reproduce

Running adapter/functional tests and checking your postico instance to see if tables generated by test which will be named in the sql log are in the database after test is finished.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### What database are you using dbt with?

redshift

**Comment by leahwicz** [comment]
@McKnight-42 was this fixed by this PR https://github.com/dbt-labs/dbt-core/pull/5198?

**Comment by McKnight-42** [comment]
@leahwicz Yes good catch.
