### ISSUE TITLE
[CT-591] Spike: Better handling `run_results` in threading

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5204]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

See https://github.com/dbt-labs/dbt-core/issues/3600 for more details.  This spike should give us a path forward to getting the run_result data if threads are killed due to --fail-fast or keyboard interrupts.

**Comment by igorlaryush** [comment]
This would be very useful especially in case when database close connection for loading data but you have a large number of models running by dbt that doesn't fully finished and takes a lot of time.
