### ISSUE TITLE
[CT-597] [Feature] Access denied when setting log-path: None

### ISSUE THREAD

**Issue by ignacioreyna** [dbt-labs/dbt-core#5208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the dbt_project.yml I set the `log-path: None`. When I run it in a FS in which it has permissions to write it'll run just fine: without creating the `logs/dbt.log` file. But when I go into a FS in which the user has _read-only_ access it fails due to not having permissions to write in said `None` dir.

### Expected Behavior

When the `log-path` value is `None` skip the permissions check

### Steps To Reproduce

Run dbt with RO permissions setting the `log-path` to `None`.

### Relevant log output

```shell
[Errno 30] Read-only file system: 'None'
```

### Environment

```markdown
- OS: Alpine 3.15
- Python: 3.8.12
- dbt: 1.0.6
```

### What database are you using dbt with?

redshift

### Additional Context

Setting the `log-path` value to `None` was the only way I found to avoid the creation of the `dbt.log` file. Perhaps this should be a feature request for that: `dbt run` without creating a `dbt.log`.

**Comment by gshank** [comment]
When I set "logs-path" to None in my dbt_project.yml file, it still writes the logs, it just writes them to a "None" directory. (Since None is just a string in yaml).  If I set it to null, it still writes the logs to the "logs" directory. So I think what you're asking for is a change to allow not logging, correct?

**Comment by ignacioreyna** [comment]
Yes, exactly. Or at least, be able to disable the file while keeping the stdout and stderr

**Comment by shousper** [comment]
Just ran into this issue today. We're using dbt via Apache Airflow in Kubernetes. Logs written to local files are discarded with when the pod is shutdown. We'd have to otherwise create a bespoke log collection pipeline _just for dbt_ if it cannot be configured to write to stdout, or our data engineers are going to be flying blind.

This is quite an urgent issue for us.

**Comment by jtcohen6** [comment]
@shousper Appreciate the clarification!

It is possible to access all dbt logging from stdout, by turning on the `debug` [global config](https://docs.getdbt.com/reference/global-configs) (`--debug` flag, `DBT_DEBUG` environment variable, or configured in `profiles.yml`):
```
dbt --debug run ...
```
That will send all logging to stdout, formatted as text by default, or optionally JSON (with `--log-format json`).

Fuller docs on logging capabilities: https://docs.getdbt.com/reference/events-logging

We're taking the ask in this issue to be: Make it possible to _disable_ file-based logging entirely, by setting `log-path: None`. That feels like a feature request, relative to existing capabilities. It's not something we're going to be able to prioritize in the near term, but we'd be supportive of a motivated community member taking it on. I think the change would be fairly self-contained, but the logger configuration can be a bit tricky to work through. For that reason, I'm going to label this issue `help_wanted`.

https://github.com/dbt-labs/dbt-core/blob/e7031f2d74c38f70dcea738622de5e87c7320f00/core/dbt/events/functions.py#L58-L65

https://github.com/dbt-labs/dbt-core/blob/e7031f2d74c38f70dcea738622de5e87c7320f00/core/dbt/events/functions.py#L85-L87

**Comment by DustinMoriarty** [comment]
We need this as well. Why not just let the user provide a logging configuration file?

**Comment by nathaniel-may** [comment]
closing in favor of #6639
