### ISSUE TITLE
[CT-624] [Feature] Allow for custom metadata to be attached to logs

### ISSUE THREAD

**Issue by alexrosenfeld10** [dbt-labs/dbt-core#5228]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

I run my dbt jobs using [Argo Workflows](https://argoproj.github.io/argo-workflows/), then I use [Vector](https://vector.dev/) to grab those logs from stdout and dump them into my logging provider. Argo and Vector don't make it super easy to set and attach something like the Argo Workflow step name and / or k8s pod name to the log line on a per-step basis.

It'd be great if `dbt` had functionality where you could set custom metadata properties (and their values) in each log line. Presumably, these could be both raw values as well as Jinja templateized values, from the project config. Something like this would be ideal:

```shell
dbt --log-format json --log-properties '{ "job_name": "my_job_name", "domain_name": "{{ project_name }}" } run'
```

It's possible this kind of thing already exists, but I couldn't easily find it. Thanks in advance for the consideration!

### Who will this benefit?

Anyone needing to run dbt jobs in a DAG-like scheduler that needs to log to some APM / Logging provider.

**Comment by jtcohen6** [comment]
@alexrosenfeld10 I super agree! I was _just_ thinking about this :)

Specifically, I want to supplement log output with metadata available from the _environment_, i.e. the tool orchestrating dbt. We already have a pattern for this in static artifacts ([docs](https://docs.getdbt.com/reference/artifacts/dbt-artifacts#common-metadata)):

> `env`: Any environment variables prefixed with `DBT_ENV_CUSTOM_ENV_` will be included in a dictionary, with the prefix-stripped variable name as its key.

I think we could do much the same thing for events / logs, either as a new attribute on the base event class, or a new JSON dictionary included in the serialized log output when `--log-format json` is enabled.

That wouldn't perfectly capture your ask for:

> Presumably, these could be both raw values as well as Jinja templateized values, from the project config.

But the Jinja templated configurations could pull in the same environment variables from `{{ env_var('DBT_ENV_CUSTOM_ENV_WHATEVER') }}`. It feels like a workable v1.

**Comment by alexrosenfeld10** [comment]
Yeah, outputting with details from the environment would be great too. I'm not sure why I didn't include that in my OP, it's pretty obvious 😆

**Comment by emmyoop** [comment]
There still seem to be a few unknowns here of exactly _how_ this would be implemented.

- created a new cli flag to pass values
- also allow to set by env var and/or config
- when processing events, if the flag is set then add these field(s) to an `extra` dictionary

**Comment by leahwicz** [comment]
AC: keep parity with JSON artifacts

**Comment by jtcohen6** [comment]
Relevant code for this:

https://github.com/dbt-labs/dbt-core/blob/356263798468d63198bf3b26d45461552d238e27/core/dbt/contracts/util.py#L154-L162

He says, given recent conversations about de-globalizing stateful behavior in `dbt-core`: We really want to load those _once_ per initialization, rather than needing to `os.environ` once for every single log event. (Could be slow in environments with tons of env vars.) I think it's okay to save env vars in global state, because they really _shouldn't_ change between invocations.
