### ISSUE TITLE
[CT-625] Raise a clear error if `materialized` override for seeds, snapshots, tests

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5229]
Seeds need `materialized: seed`
Snapshots need `materialized: snapshot`
Tests need `materialized: test`

They shouldn't ever really be otherwise. Let's raise a clear error the next time a user puts:
```
# dbt_project.yml
snapshots:
  materialized: table
```

In theory, it's _maybe_ desirable to support different kinds of custom snapshot materializations, but really a user could accomplish by having one snapshot materialization that "dispatches" to different strategies. These resource types are necessarily more constrained than models—they target narrower use cases.

**Comment by sungchun12** [comment]
hahahaha you are FAST at this Jerco ;)
