### ISSUE TITLE
[CT-629] [Bug] Setting `--indirect-selection=cautious` does not work as intended with `state:modified+`

### ISSUE THREAD

**Issue by MichaelGFagan** [dbt-labs/dbt-core#5233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setting `--indirect-selection=cautious` while running `dbt test -m state:modified+` runs relationship tests even if one of the models involved is not selected.

### Expected Behavior

I would expect these tests not to be run, as if I was selecting them manually.

### Steps To Reproduce

1. Run dbt and obtain a `manifest.json`.
2. Change a file that has a relationship test attached to it (as parent or child).
3. Run `dbt ls -m state:modified+ --state <path to manifest.json>` to ensure proper selection.
4. Run `dbt test -m state:modified+ --state <path to manifest.json> --indirect-selection=cautious`.

You can also follow the same steps while changing the other model file involved in the relationship test.

I also verified by running `dbt test` and explicitly selecting the models to verify that the relationship test did not run.

### Environment

```markdown
- OS: Mac OS 12.2.1
- Python: 3.9.12
- dbt: 1.1
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment]
@MichaelGFagan I think this is because `state:modified+` will include all children of the model, which includes tests!

I totally see what you're after, though. You may need a more specific selector to make this happen:
```
dbt test --select state:modified+ --exclude state:modified+1,test_name:relationships \
         --state <path to manifest.json> --indirect-selection=cautious
```

If you're using `dbt test` with `--defer`, the relationships test should "defer" to the production version of the unbuilt model. The test shouldn't fail due to the table being missing, but it may still fail if you sample/limit data in CI, which harms referential integrity.

**Comment by MichaelGFagan** [comment]
Did you guys update your issues SLA to 5 minutes or less? And you hit our use case right on the head with the defer/limiting CI data!

I just tried your suggestion and it does give us the behavior we want. So thanks for that!

When I was trying to determine if this was expected behavior from dbt by explicitly selecting models, I was doing so without adding `+` to the model selection. Retried with the `+` and see that those tests run in that scenario too. So it's good to know the behavior is consistent.

I suppose it's worth asking if that's the best way to implement? My expectation given the documentation is that the relationship test would only run if both models were selected, and the `+` acting as a sort of overrider really narrows how one can use the `--indirect-selection=cautious` flag without some additional workarounds. Thoughts?

**Comment by jtcohen6** [comment]
> My expectation given the documentation is that the relationship test would only run if both models were selected, and the `+` acting as a sort of overrider really narrows how one can use the `--indirect-selection=cautious` flag without some additional workarounds.

Totally fair. I think our best move here is to update the docs, to set this expectation more clearly, and give dbt users the information they need to derive the appropriate logic (which may look like the selection syntax above). I'm hesitant about trying to build more product capability around this, given how tricky the edge cases here already are, and the deep waters we've already waded into re: `indirect_selection`.

I'm going to close this issue for now, but could I trouble you to [open a new docs issue](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) linking to this one?
