### ISSUE TITLE
[CT-639] [Bug] DBT Cloud is using a very old version of the python connector to send queries to Snowflake periodically

### ISSUE THREAD

**Issue by mroy-seedbox** [dbt-labs/dbt-core#5239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This has nothing to do with dbt-core itself, but I'm not sure where else to report this.

It seems that for any connection configured in dbt Cloud, queries will be sent periodically. I don't know why, but I assume there must be some reason. Maybe to check if the credentials are still valid? Anyway, that's not the end of the world, as those queries only consume cloud services (no active warehouse required).

However, the version of the python connector used to send those queries is really old (`2.2.1`). We're doing our quarterly review of Snowflake client drivers, and this one came up as seriously out of date, and no longer supported.

I assume this is not unique to Snowflake, but we're not using any other data warehouse to check whether or not if affects them as well.

![image](https://user-images.githubusercontent.com/66686238/168187242-c1bf887b-e374-43ed-913a-6c2ef802968e.png)
![image](https://user-images.githubusercontent.com/66686238/168187299-5fad5092-498a-4dfe-930c-2584b113b251.png)

### Expected Behavior

Python connector is kept up-to-date with pip (or dbt-core, or _something_ more recent).

### Steps To Reproduce

- Create a connection to Snowflake in dbt Cloud
- Create a corresponding environment, with a configured user & credentials
- dbt Cloud will start sending queries periodically (using this old version of the python connector)

### Relevant log output

```shell
N/A
```

### Environment

```markdown
dbt Cloud

dbt-core version does not matter.
```

### What database are you using dbt with?

snowflake

**Comment by jeremyyeo** [comment]
Thanks for raising @mroy-seedbox. We have raised this internally with the dbt Cloud team. 

@jtcohen6 I tagged you in the internal thread.

**Comment by jtcohen6** [comment]
@mroy-seedbox Circling back to give you an update here.

dbt Cloud hooks into dbt directly for two of its own purposes today:
- Testing a new connection. It just runs `select 1 as id` (defined [here](https://github.com/dbt-labs/dbt-core/blob/0d8e061a3d8d726bb10ff767d8f276439cc472b2/core/dbt/adapters/base/impl.py#L193-L194))
- Dropping CI schemas built by PRs which have been closed/merged. This is a bit more complex: It first lists all schemas (`show terse schemas` as you're seeing), identifies the ones that start with its dedicated prefix (`dbt_cloud_pr`), and finally runs `drop schema`.

In both cases, dbt Cloud has been using an older version of `dbt-core` + `dbt-snowflake`, so it is also using the older version of `snowflake-connector-python` that you see above. We're right now in the process of upgrading it to use the latest versions of `dbt-core` + `dbt-snowflake` instead, so you should start seeing these queries run with `"snowflake-connector-python>=2.4.1,<2.8.0"` ([source](https://github.com/dbt-labs/dbt-snowflake/blob/c086d61650a3f3e6f1733b0d9243603bf566ee90/setup.py#L70)), just like all your other dbt + Snowflake queries.

@jeremyyeo or I will swing back to update and close the issue once we've confirmed that the upgrade is complete.

**Comment by mroy-seedbox** [comment]
Quick update here:
- We haven't seen `snowflake-connector-python=2.2.1` since May 15th (the blue line).
- On May 16th, `snowflake-connector-python=2.4.6` started appearing instead (the yellow line).
- Strangely, it then started replacing `snowflake-connector-python=2.7.7` (the red line). 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/66686238/169658991-aacf6b6c-2f29-4553-ac5d-57246769e471.png)

**Comment by mroy-seedbox** [comment]
Things have been running fine on `snowflake-connector-python=2.4.6` since May 16th.

Closing this.
