### ISSUE TITLE
[CT-640] File selectors and support for file selectors as a default method

### ISSUE THREAD

**Issue by jwills** [dbt-labs/dbt-core#5240]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

`dbt should just know that when i say: 
    dbt run -m my_model.sql 
i mean: 
    dbt run -m my_model
`

https://twitter.com/pedram_navid/status/1519160872588898304

### Describe alternatives you've considered

Seemed like a pretty straightforward paper-cut feature request.

### Who will this benefit?

Pedram, apparently

### Are you interested in contributing this feature?

yes!

**Comment by jtcohen6** [comment]
Thanks for opening @jwills! Makes total sense to me. Next up: "open this tweet as a GitHub issue" integration
