### ISSUE TITLE
[CT-641] [Feature] DBT Continuous running

### ISSUE THREAD

**Issue by aodhan-domhnaill** [dbt-labs/dbt-core#5242]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Run DBT migrations in a continuous loop with a sleep from commane line. For example, `dbt run --daemon --sleep 5m`, would run DBT, sleep for 5 min and loop.

### Describe alternatives you've considered

**Writing a loop myself**

This is fairly easy from command line, but inside DBT would offer better ability for error handling.

### Who will this benefit?

People running DBT as a prod data pipeline engine

### Are you interested in contributing this feature?

Yes

**Comment by jtcohen6** [comment]
Hey @aodhan-domhnaill, thanks for opening!

I have two primary reservations with an idea like that:
- dbt's execution model is a DAG. It only proceeds in one direction, not in a loop or cycle. Of course, you run that DAG multiple times per day (or every 5 minutes), but each standalone invocation is still directed and acyclic.
- Is your entire dbt invocation (batch process) really <5 minutes? If you do have models that need <5 minute latency, there are other solutions like:
    - [lambda views](https://docs.getdbt.com/blog/how-to-create-near-real-time-models-with-just-dbt-sql) (models that are "partitioned" between incremental processing + view)
    - [materialized views](https://github.com/dbt-labs/dbt-labs-experimental-features/tree/main/materialized-views)
    - [a dedicated streaming databases like Materialize](https://docs.getdbt.com/reference/warehouse-profiles/materialize-profile)

> This is fairly easy from command line, but inside dbt would offer better ability for error handling.

Given how easy this is to spin up with a simple cron runner—knowing that you're taking matters into your own hands—I'm not sure that there's an abstraction missing inside dbt today to make it possible.

Instead, I'm curious to know more about: What kind of error handling are you looking for? dbt may already offer support for it, via [structured logging](https://docs.getdbt.com/reference/events-logging) and [metadata-powered selection](https://docs.getdbt.com/docs/guides/understanding-state)

I'm going to close this issue, as I don't foresee us taking on this work, or merging a PR for it into `dbt-core`. That doesn't mean you couldn't work on it, though! If  `dbt run --daemon --sleep 5m` is indeed something you want to build, and you want to share with the community of open source users, I'd welcome you to do it.
