### ISSUE TITLE
[CT-643] Support package resources with `path:` selector method

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5243]
Prompts:
- [first internal Slack thread](https://getdbt.slack.com/archives/C2JRTGLLS/p1652249345961579)
- [second internal Slack thread](https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1711654816830159)

### Short description

The dbt Cloud IDE uses `dbt list` behind the scenes to power the DAG viz. When it provides `+dbt_packages/package_name/models/.../model_name.sql+`, `dbt-core` doesn't return any resources.

The reason: dbt-core's `path:` selector method doesn't support resources defined in packages.

https://github.com/dbt-labs/dbt-core/blob/72c17c446440afe7d4b6501ed364effe8e14c9f2/core/dbt/graph/selector_methods.py#L288-L289

### Proposed resolution

Update [`FileSelectorMethod`](https://github.com/dbt-labs/dbt-core/blob/e81f7fdbd5b248d7cc24847da1ac6eee453f9d1a/core/dbt/graph/selector_methods.py#L445) to accept the full relative path of resources defined in packages, including the install path and the package name, as a way to select that resource.

For example, `dbt_packages/dbt_project_evaluator/models/marts/dag/fct_direct_join_to_source.sql` to select [`fct_direct_join_to_source`](https://github.com/dbt-labs/dbt-project-evaluator/blob/f39053532ae7b55176da7f1aa70302ada053c0d1/models/marts/dag/fct_direct_join_to_source.sql).

### Acceptance criteria

- `dbt ls -s full/relative/path/to/package/model.sql` should return that model

### Suggested tests

https://github.com/dbt-labs/dbt-core/blob/e81f7fdbd5b248d7cc24847da1ac6eee453f9d1a/tests/unit/test_graph_selector_methods.py#L1150

https://github.com/dbt-labs/dbt-core/blob/main/tests/functional/list/test_list.py

### Alternatives

Both of these alternatives (the original resolutions I suggested in ~2022) would require additional logic on the "client" side. I believe a preferable resolution allows clients to pass the full (relative) path to all resources, both those defined in the root project and those defined in packages, without any additional logic.

1. Start returning package resources based on their `original_file_path` (always relative), and expect services passing file names into `dbt list` to trim off `dbt_packages/package_name/`. Because models with the same name can be defined in multiple installed packages, this could return multiple models that have the same relative path. For example, if I also `models/my_model.sql`, even if they're defined in different packages. I think that's fair, and in keeping with expected behavior.

2. Add a new `FileIDSelector`. `dbt-core` does have a notion of an internal "file ID" that looks like `package_name://relative/file/path`, which it uses to uniquely identify each file during partial parsing. That still requires knowing the _name_ of the package, though. I'm pretty sure `dbt deps` takes care of this. (It should be the same for Hub packages, based on how `dbt deps` renames the package after installation, but not necessarily the same for non-Hub packages.)

**Comment by ChenyuLInx** [comment]
We might need to insert dbt packages in the `original_file_path`

**Comment by ChenyuLInx** [comment]
Whoever picks this one up please pair with @gshank
