### ISSUE TITLE
[CT-648] [Feature] Distinguish what dbt command has been executed in Jinja context

### ISSUE THREAD

**Issue by SOVALINUX** [dbt-labs/dbt-core#5251]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Hi colleagues,
In multiple advanced cases like dbt hooks, operations and unit testing we would like to execute queries against the database and also run some state changing operations (e.g. agate table print to file)
Currently dbt doesn't gives the opportunity to avoid such misbehavior

Suggested idea is to add `executed_command` to the Jinja context storing `compile` | `run` | `test` | `docs` etc from dbt command palette

So all macroses for hooks and operations can use it and flexibly configure when to run and what
Same for unit testing use-cases:
1. I can skip unit tests on `dbt compile` and `dbt docs`
2. I can now mock `current_timestamp` function in `dbt_utils` to write advanced tests without changing the logic

### Describe alternatives you've considered

I was trying to do workarounds using tags and relying on presence of attributes like run_result, schemas, graph nodes in the Jinja context
Some of them are working, but all of them doesn't smell good

### Who will this benefit?

Looks like multiple developers are facing the same issue
So, users of hooks, operations and unit-testing will benefit

### Are you interested in contributing this feature?

Yes, PR will come soon

### Anything else?

Easily found several related cases
https://github.com/dbt-labs/dbt-core/issues/4785
https://github.com/dbt-labs/dbt-core/issues/4445

**Comment by jeremyyeo** [comment]
Hey @SOVALINUX, have you taken a look at `flags.WHICH` (https://docs.getdbt.com/reference/dbt-jinja-functions/flags) by any chance?

![2022-05-16 09 44 55](https://user-images.githubusercontent.com/8496748/168495344-9c3576c0-335d-4f7a-814b-f2de96d420ed.gif)

Kind of wondering if (`flags.WHICH` + `execute`) simply gives you what you need to do what you had wanted to with this proposed `executed_command` Jinja context?

**Comment by jtcohen6** [comment]
Agreed! I'm pretty sure that `flags.WHICH` is what you're after here @SOVALINUX. Newly available since v1.0:

https://github.com/dbt-labs/dbt-core/blob/0d8e061a3d8d726bb10ff767d8f276439cc472b2/core/dbt/flags.py#L129

I'm going to close the issue, since I believe it's already implemented :)

**Comment by SOVALINUX** [comment]
@jeremyyeo @jtcohen6 Thank you for response! It's indeed the same thing
But I wonder should we give a better name to this flag? Should we rename the feature or create a new one?
I've read the documentation on flags and jinja context several times, even dumped all flags to the logs, but haven't noticed this one
DBT itself calls it commands (https://docs.getdbt.com/reference/dbt-commands)
Another community members decided to struggle rather than contributing into it since they also haven't found it with such a name
