### ISSUE TITLE
[CT-652] dbt-docs Improvements for 1.2.0

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#5255]
This issue is a collection of all of the possible bug fixes and/or enhancements in dbt-docs for the `1.2.0` release.  There will be a single new index file including all of these changes.

If checked off, it is merged in to `main` in `dbt-docs`.

- [x] [Fix the sample SQL when the source has no database](https://github.com/dbt-labs/dbt-docs/pull/272)
- [x] [[Snyk] Upgrade prismjs from 1.27.0 to 1.28.0](https://github.com/dbt-labs/dbt-docs/pull/271)
- [x] [Adds support for File selector matcher](https://github.com/dbt-labs/dbt-docs/pull/273)
- [x] [Fix tests](https://github.com/dbt-labs/dbt-docs/pull/274)
- [ ] ~[Add label, type, and SQL to metric docs](https://github.com/dbt-labs/dbt-docs/pull/278) - review pending~
- [x] [Improve metrics docs & DAG viz](https://github.com/dbt-labs/dbt-docs/pull/285) - review pending
- [x] [fix dependency conflicts](https://github.com/dbt-labs/dbt-docs/pull/284)

Moving remaining to #5443 for next release

- [ ] [Use column.comment from catalog/database if column.description is missing](https://github.com/dbt-labs/dbt-docs/pull/263)
- [ ] many dependabot suggestions that need validation
- [ ] [Improved Searching](https://github.com/dbt-labs/dbt-docs/pull/145) (pending changes)

Note: The related PR should have a changie file for each PR below giving credit to the appropriate contributor but ref this issue.

**Comment by emmyoop** [comment]
@jtcohen6 Would love some direction on what should be slated for `1.1.1` and what should wait on `1.2`?

None are currently merged in.

**Comment by jtcohen6** [comment]
@emmyoop I think 1.2 is fair for all of these. They're valuable net improvements, and none makes the `dbt-docs` site unusable in its current state.
