### ISSUE TITLE
[CT-653] [Feature] Allow running unit/integration tests locally with any supported Python version

### ISSUE THREAD

**Issue by jwills** [dbt-labs/dbt-core#5257]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

This is more of a rough edge for a non-professional dbt-core developer: the `Makefile` hard-codes `py38` as the preferred python version in tox for running unit tests and integration tests; we use Python 3.9 at my day job, so when I need to do work on dbt-core I need to remember to swap out the version in the Makefile to `py39` before I run dbt tests and then switch it back before I send a PR upstream.

### Describe alternatives you've considered

I would love it if the Makefile was either a) configured to work with the Python version that I had installed locally as long as it was supported (i.e., if the default in the Makefile was `py` and `py-integration` instead of `py38` and `py38-integration`), or, if that presents a problem for e.g. CI or some such thing, if it was easy (like via an environment variable that was documented in the `CONTRIBUTING.md` guide) for me to override the setting in the `Makefile` on my local machine.

### Who will this benefit?

Developers who want to create PRs for dbt-core who do not work at dbt Labs.

### Are you interested in contributing this feature?

Happy to!

### Anything else?

Issue originally discussed in a Slack thread in dbt-core-development: https://getdbt.slack.com/archives/C50NEBJGG/p1652466095907019

**Comment by jtcohen6** [comment]
Using `py` and `py-integration` makes tons of sense—it will just uses your own local `PATH` version of Python, right?

We don't use the Makefile in CI (we hit `tox` directly), so I don't think there should be any implications there. Let's do a nice thing for non-professional dbt-core developers :)

The only edge I could see is someone very eagerly upgrading to a new minor version of Python, before `dbt-core` officially supports it, e.g. Python 3.10 prior to the v1.1 release. But I'd like to see us supporting new Python minor versions more proactively going forward, especially when they promise to have [some good stuff](https://docs.python.org/3.11/whatsnew/3.11.html#faster-cpython) inside...

@jwills proceed at your leisure!
