### ISSUE TITLE
[CT-654]  Can not install DBT with airflow because of MarkupSafe dependency

### ISSUE THREAD

**Issue by Kiollpt** [dbt-labs/dbt-core#5258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to use pip install -r requirements.txt  -c constraints.txt. It keeps failing to install.

My constrains.txt looks like below
MarkupSafe>=0.23,<=2.1
apache-airflow==2.1.1

Cannot install -r requirements.txt (line 32), apache-airflow==2.1.1 and dbt-core because these package versions have conflicting dependencies.
The conflict is caused by:
    dbt-core 1.0.4 depends on MarkupSafe==2.0.1
    jinja2 2.11.3 depends on MarkupSafe>=0.23
    apache-airflow 2.1.1 depends on markupsafe<2.0 and >=1.1.1
    The user requested (constraint) markupsafe<=2.1,>=0.23

**Comment by jtcohen6** [comment]
Hey @Kiollpt, try upgrading to `dbt-core==1.0.5`!

We made the `MarkupSafe` pin more flexible, including older versions, about a month ago: https://github.com/dbt-labs/dbt-core/pull/5039. We backported that change for inclusion in both v1.0.5 + v1.1.0.

I'm going to close this issue as I believe it's been resolved by a newer version of `dbt-core`.
