### ISSUE TITLE
[CT-668] [Bug] dbt-core capturing KeyboardInterrupt Event with significant delay after pressing ctrl-c

### ISSUE THREAD

**Issue by SatishChGit** [dbt-labs/dbt-core#5275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When pressing ctrl-c while dbt model executing, dbt-core waiting to capture KeyboardInterrupt Event until current model execution completion and also its waiting even after that with significant delay. 

My output:
14:48:40  1 of 8 START view model dbt_test.stg_customers.................................. [RUN]
14:48:55  1 of 8 OK created view model dbt_test.stg_customers............................. [OK in 14.96s]
14:48:55  2 of 8 START view model dbt_test.stg_orders..................................... [RUN]
14:49:15  2 of 8 OK created view model dbt_test.stg_orders................................ [OK in 19.97s]
14:49:15  dbt-core adapter: KeyboardInterrupt Event Captured!!!
14:49:15  3 of 8 START view model dbt_test.stg_payments................................... [RUN]
14:49:15  teradata adapter:  Canceling Open connections from teradata adapter
14:49:15  teradata adapter:  Connection Name :  list_schemas, connection state is: closed
14:49:15  teradata adapter:  Connection Name :  list_None_dbt_test, connection state is: closed
14:49:15  teradata adapter:  Connection Name :  model.jaffle_shop.stg_payments, connection state is: closed

Here the run was cancelled with ctrl+c after 1 second from starting but the model was running for the full almost 15 seconds despite this and also next model ran for 20 secs.

### Expected Behavior

When pressing ctrl-c while dbt model exeucting, dbt-core should capture KeyboardInterrupt Event immediately and it should not wait until model execution.

### Steps To Reproduce

1. Create dbt project with dbt-teradata adapter
2. Create model with a long runtime, materialised as a table (my example runs about 400 seconds)
3. Run the model with dbt run and model selector
4. Wait for model to start executing
5. Cancel the run with ctrl+c in the terminal
6. Check the console or log file

### Relevant log output

```shell
$ dbt  run
14:47:54  Running with dbt=1.0.1
14:47:54  Found 8 models, 20 tests, 0 snapshots, 0 analyses, 197 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics
14:47:54
14:48:40  Concurrency: 1 threads (target='dev')
14:48:40
14:48:40  1 of 8 START view model dbt_test.stg_customers.................................. [RUN]
14:48:55  1 of 8 OK created view model dbt_test.stg_customers............................. [OK in 14.96s]
14:48:55  2 of 8 START view model dbt_test.stg_orders..................................... [RUN]
14:49:15  2 of 8 OK created view model dbt_test.stg_orders................................ [OK in 19.97s]
14:49:15  dbt-core adapter: Satish: KeyboardInterrupt Event Captured!!!
14:49:15  3 of 8 START view model dbt_test.stg_payments................................... [RUN]
14:49:15  teradata adapter:  Canceling Open connections from teradata adapter
14:49:15  teradata adapter:  Connection Name :  list_schemas, connection state is: closed
14:49:15  teradata adapter:  Connection Name :  list_None_dbt_test, connection state is: closed
14:49:15  teradata adapter:  Connection Name :  model.jaffle_shop.stg_payments, connection state is: closed
14:49:26  teradata adapter:  calling teradata adapter cancel method to cancel connection : model.jaffle_shop.stg_payments as state of this connection is open
14:49:26  teradata adapter:  Closing connection name: model.jaffle_shop.stg_payments
14:49:26  teradata adapter: returning all connection names to dbt core ['list_schemas', 'list_None_dbt_test', 'model.jaffle_shop.stg_payments']
14:49:26  CANCEL query PrintCancelLine from dbt-core list_schemas......................... [CANCEL]
14:49:26  CANCEL query PrintCancelLine from dbt-core list_None_dbt_test................... [CANCEL]
14:49:26  CANCEL query PrintCancelLine from dbt-core model.jaffle_shop.stg_payments....... [CANCEL]
14:49:26  Unhandled error while executing model.jaffle_shop.stg_payments
6 is not a valid connection pool handle
14:49:26  3 of 8 ERROR creating view model dbt_test.stg_payments.......................... [ERROR in 11.10s]
14:49:26
14:49:26  Exited because of keyboard interrupt.
14:49:26
14:49:26  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
14:49:28  ctrl-c
```

### Environment

```markdown
- OS: Windows 10 
- Python:Python 3.9.11
- dbt:1.0.1
    Plugins:
     - teradata: 1.0.0a
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

database  : teradata
connector : dbt-teradata (https://github.com/Teradata/dbt-teradata
Parent Issue: https://github.com/Teradata/dbt-teradata/issues/35 

dbt-teradata adapter supports cancelling connections.  this extended dbt sql adatper functionality and it inherits the [is_cancelable](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/sql/impl.py#:~:text=def-,is_cancelable,-(cls) )

**Comment by iknox-fa** [comment]
Hi @SatishChGit
Thanks for opening this issue.  Unfortunately, replicating this for debugging is a bit of a big ask as we don't have access to Teradata and our development is done almost exclusively on Macs.  I will tag this as something to investigate in the future, but prioritizing that work may take quite some time.

**Comment by jtcohen6** [comment]
Linking [Slack thread](https://getdbt.slack.com/archives/C50NEBJGG/p1652165754957309) that prompted this issue, for additional context.

This exact issue is going to be quite tricky for us to reproduce exactly ourselves, given the reasons @iknox-fa mentioned above. Based on the information provided, it does seem like the `KeyboardInterrupt` is blocked by the current model's execution:

```
14:49:15 2 of 8 OK created view model dbt_test.stg_orders................................ [OK in 19.97s]
14:49:15 dbt-core adapter: KeyboardInterrupt Event Captured!!!
```

The logic to catch that and cancel is all inside `dbt-core`:

https://github.com/dbt-labs/dbt-core/blob/e50678c91424142aa1a4995ee1d358dac6a6fdf8/core/dbt/task/runnable.py#L386-L389

@SatishChGit Could you confirm that the `dbt-core adapter: KeyboardInterrupt Event Captured!!!` log line is something you put in place, within `dbt-core`'s codebase, in the spot linked just above?

**Comment by SatishChGit** [comment]
@jtcohen6 Yes, I added `dbt-core adapter: KeyboardInterrupt Event Captured!!!`   log line in dbt-core's code base at the spot linked above as below.

```
 except KeyboardInterrupt:
            logger.info("Satish: KeyboardInterrupt Event Captured!!!")
            self._cancel_connections(pool)
            print_run_end_messages(self.node_results, keyboard_interrupt=True)
            raise
```

**Comment by jtcohen6** [comment]
The weird thing is that, even though this code is in `dbt-core`, it isn't something we see on other adapters. For instance, I added the same sort of log line (as a print statement) to `dbt-core` locally, created a "long" model on Postgres:
```sql
-- models/model_a.sql
{{ config(
  pre_hook = "select pg_sleep(10)"
) }}

select 1 as id
```
When I try running, the interrupt is captured right away:
```
$ dbt build --threads 5
14:17:12  Running with dbt=1.2.0-a1
14:17:12  Found 3 models, 1 test, 0 snapshots, 0 analyses, 176 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics
14:17:12
14:17:12  Concurrency: 5 threads (target='dev')
14:17:12
14:17:12  1 of 5 START view model dbt_jcohen.model_a ..................................... [RUN]
14:17:12  2 of 5 START view model dbt_jcohen.model_b ..................................... [RUN]
14:17:12  3 of 5 START seed file dbt_jcohen.my_seed ...................................... [RUN]
14:17:13  3 of 5 OK loaded seed file dbt_jcohen.my_seed .................................. [INSERT 4 in 0.14s]
14:17:13  2 of 5 OK created view model dbt_jcohen.model_b ................................ [CREATE VIEW in 0.15s]
^CKeyboardInterrupt Event Captured!!!
14:17:13  CANCEL query model.testy.model_a ............................................... [CANCEL]
14:17:13  CANCEL query model.testy.model_b ............................................... [CANCEL]
14:17:13  CANCEL query seed.testy.my_seed ................................................ [CANCEL]
14:17:13  1 of 5 ERROR creating view model dbt_jcohen.model_a ............................ [ERROR in 0.48s]
14:17:13
14:17:13  Exited because of keyboard interrupt.
14:17:13
14:17:13  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
14:17:13  ctrl-c
```

**Comment by SatishChGit** [comment]
Weird!!!! Is there any dependency on platform where dbt project is running. I believe, dbt-teradata not handling any specific case of keyboard interrupt event.

**Comment by jtcohen6** [comment]
@SatishChGit That's a really good point. I see you're running on `OS: Windows 10`. Maybe...? I fear [there be dragons](https://stackoverflow.com/questions/4606942/why-cant-i-handle-a-keyboardinterrupt-in-python) in these parts

**Comment by zachoooo** [comment]
I'm noticing this same issue when running with Redshift using concurrency. It seems that the event isn't propagated to the running threads so it only actually stops once the current running models are completed.
