### ISSUE TITLE
[CT-678] [Bug] command line variable overrides are not visible in module level config overrides

### ISSUE THREAD

**Issue by mdesnoyer** [dbt-labs/dbt-core#5287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm seeing very weird behavior that's acting like command line variables aren't being injected in a config block even though they are visible in the body of the model definition. Here's the simplified case that I'm seeing.

I have a dbt_project.yml file with default vars defined as:

```
vars:
  'site': 'sin'  # The site to process by default.
  'sites_with_release_program': ['fat', 'pr', 'sin']
```

Then I have a model file model.sql defined as:

```
{{ config(enabled= var('site') in var('sites_with_release_program')) }}
SELECT "{{ var('site') }}"
```

If I run this with the default command line, the model is executed as expected and it compiles to:

SELECT "sin"

However, if I run this on the command line with a variable override like:

dbt run --vars '{"site": "other"}'

The model is still enabled and executes, but it compiles to:

SELECT "other"

To be complete, if I change the default variable value site in the dbt_project.yml to 'other', then the model is disabled with I do dbt run.

### Expected Behavior

I would expect that the command line variables override the defaults in the dbt_project.yml file inside the config block and in this case, the model would be disabled when using the command line override of dbt run --vars '{"site": "other"}'

### Environment

```markdown
- OS: dbt cloud v1.1.44.22
- dbt: 1.0
```

### What database are you using dbt with?

bigquery

**Comment by jtcohen6** [comment]
> OS: dbt cloud v1.1.44.22

If this is in the IDE, I suspect it's related to: https://github.com/dbt-labs/dbt-rpc/issues/48
