### ISSUE TITLE
[CT-679] [Bug] when shelling out to dbt, disabling colored output still prints out the reset color code

### ISSUE THREAD

**Issue by darin-reify** [dbt-labs/dbt-core#5288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when shelling out to dbt ([a la Prefect](https://docs.prefect.io/api/latest/tasks/dbt.html#dbtshelltask)), disabling colored output still prints the reset color code.

### Expected Behavior

no color codes should be printed when colored output is disabled

### Steps To Reproduce

1. install `dbt >= 1.0.0`
2. set up a dbt project
3. start python and shell out to dbt via your preferred method making sure to disable colored output
4. notice the reset color code from the stdout stream

### Relevant log output

```shell
# running 'dbt --no-use-colors run'
[0m23:06:09  Running with dbt=1.1.0
[0m23:06:09  Found 11 models, 10 tests, 0 snapshots, 0 analyses, 172 macros, 1 operation, 0 seed files, 2 sources, 0 exposures, 0 metrics
```
```


### Environment

```markdown
- OS: Debian 11
- Python: 3.9.12
- dbt: 1.1.0
```

### What database are you using dbt with?

redshift

### Additional Context

[this line here](https://github.com/dbt-labs/dbt-core/tree/main/core/dbt/events/functions.py#L179) looks to be the culprit

**Comment by gshank** [comment]
I tried this in a standard terminal and it works fine. Is this behavior dependant on using that DbtShellTask that you linked to? Because if it works find in a normal terminal and doesn't underneath that application, I'm wondering if there is an issue with DbtShellTask.

**Comment by darin-reify** [comment]
it's probably more of a problem with anything that wants programmatic access to the logs for whatever reason.

here's a super small snippet (modified from [DbtShellTask's parent functionality](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/shell.py#L134)) showing what's going on:

```python

import os
from subprocess import Popen, PIPE


with Popen(["dbt", "--no-use-colors", "compile"], stdout=PIPE, shell=False) as sub_process:
    lines = []
    for raw_line in iter(sub_process.stdout.readline, b""):
        line = raw_line.decode("utf-8").rstrip()
        lines.append(line)

    sub_process.wait()

print(lines)
```
results in:

```bash
$ python test.py
```

**Comment by gshank** [comment]
It looks like this might be due to a programming error in core/dbt/events/functions.py. The line `color_tag: str = "" if this.format_color else Style.RESET_ALL` should probably be `color_tag: str = "" if not this.format_color else Style.RESET_ALL` (in two places).

Would you be interested in trying this and doing a pull request?

**Comment by darin-reify** [comment]
sure, i'll give it a whirl! i found that line too but hadn't dug too deep to know if that was the _right_ spot to change.
