### ISSUE TITLE
[CT-680] [Feature] Support for .py files when using file selectors

### ISSUE THREAD

**Issue by leoebfolsom** [dbt-labs/dbt-core#5289]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

> dbt should just know that when i say: dbt run -m my_model.sql i mean: dbt run -m my_model
> 
> https://twitter.com/pedram_navid/status/1519160872588898304

but for `.py` files, since [dbt Python models are gonna happen](https://github.com/dbt-labs/dbt-core/discussions/5261).

I would edit [this code](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/graph/selector_spec.py#L83), as well as (I think?) [this test](https://github.com/jwills/dbt-core/blob/1510eeb06a4479f5e74cac645f3b19d10fecaf85/test/unit/test_graph_selector_methods.py#L708).

### Describe alternatives you've considered

Life would go on without this feature, but why should we settle for less when a first-time contributor (me) wants to build it.

### Who will this benefit?

- > Pedram, apparently
- Me, because I'll gain experience by making a small contribution to `dbt-core`.
- The community, because with my newly gained experience, I'll be able to help with more, and more complex, issues over time.
- There are times when it's easier to include the file extension in the `dbt run` command. For example, if you're generating the `dbt run` command from a script, and don't want to bother stripping the file extensions from the list of models you plan to run.

### Are you interested in contributing this feature?

I'd like to create the PR, but i'll take any help / suggestions / guidance

### Anything else?

- [Josh's issue](https://github.com/dbt-labs/dbt-core/issues/5240) adding file selectors and `.sql` support.
- [Josh's PR](https://github.com/dbt-labs/dbt-core/pull/5241) solving that issue
- Wherein @jwills [suggested](https://github.com/dbt-labs/dbt-core/discussions/5261#discussioncomment-2771140), albeit with a winky face, I add support for `.py` files.

**Comment by jtcohen6** [comment]
@leoebfolsom Props for being way ahead of the game :) and thanks for making sure this didn't get lost in the shuffle!
