### ISSUE TITLE
[CT-684] [Bug] Got 1 result, configured to fail if != 0

### ISSUE THREAD

**Issue by nishkarshkhokhar** [dbt-labs/dbt-core#5296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our job is failing at dbt test, returning this error: 

'Got 1 result, configured to fail if != 0'.

However, when I do a dbt test in development environment, it is successful. The job was working fine the whole day, only encountered the issue today evening. 

Can you suggest a solution for this?

### Expected Behavior

Would expect dbt test to either pass or fail in both the job and development environment.

### Environment

```markdown
- OS: Windows 11 Pro 10.0, build 22000
- dbt: 1.1.52.2
```

### What database are you using dbt with?

redshift

**Comment by jaypeedevlin** [comment]
Hey Nishkarsh, I don't work for dbt Labs but thought I would pop in and offer my thoughts on this one.

This is very unlikely to be a bug with dbt, instead it's likely that your dev environment is using different data, configurations, or model freshness than production. Without knowing the sequence of commands you're running in dev and what's running in production, it's very hard to suggest how you might resolve this issue.

I would recommend starting a conversation in the [dbt Community slack](https://www.getdbt.com/community/) with some more context where friendly dbt communities members might be able to help you.

If you are convinced this is a bug, providing reproduction steps will help the dbt Labs team understand what's driving this so they can fix it.

**Comment by nishkarshkhokhar** [comment]
Thanks for the reply Josh. I’ll work on the code, it could be a problem
with our data model. I was working on a fix for that just now. If the
problem persists tomorrow when we run a job then will proceed further.

Thanks again for your help!
Nishkarsh
