### ISSUE TITLE
[CT-687] [Informational Test Severity] Idea.. Additional Test Severity Levels 

### ISSUE THREAD

**Issue by MDamon** [dbt-labs/dbt-core#5299]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Applies to DBTCloud most notably.  

We've identified the need to mark some referential integrity testing as Informational rather than a Warn or Fail Severity.  

All test results in our Production environment have been moved to a Warn severity to alleviate Job Failure notifications during schedule run times.  A failed execution should only apply to actual failures and not failed test results so this leaves us with one severity level of Warn remaining.  

Warn is ideal for most tests and should be capable of triggering alerts from DBTCloud as well but we are running into scenarios where we know there's a test that will trigger a result set and count, but can't be fixed immediately or are more informational in nature.

### Describe alternatives you've considered

Omitting the test from execution seems to be our only option at the moment while we create a ticket and address it but that leaves us with an inconsistent testing strategy when compared to other tests.

### Who will this benefit?

DBTCloud users as well as scheduled production executions that are setup to trigger notifications from test results.

### Are you interested in contributing this feature?

No

**Comment by gshank** [comment]
Normally "warn" is the standard severity level to inform people that the test is failing but not derail the run. Have you looked at creating custom tests that will succeed instead of warn or fail?

**Comment by jtcohen6** [comment]
@MDamon Thanks for sharing your idea! I agree with Gerda, I'm inclined to think that "informational tests" which still find failing rows, but shouldn't result in actual run failure, is exactly what the `warn` test severity is for. It sounds like you see a need for finer distinction:

> Warn is ideal for most tests and should be capable of triggering alerts from DBTCloud as well but we are running into scenarios where we know there's a test that will trigger a result set and count, but can't be fixed immediately or are more informational in nature.

Could you share more about what you're thinking here? Is the concern around having too many tests with warnings, such that the signal is getting lost in the noise? Have you thought about using the conditional `warn_if` threshold ([docs](https://docs.getdbt.com/reference/resource-configs/severity))?

**Comment by saraleon1** [comment]
+1 dbt Cloud user - they would like to have additional test severity levels so as to help differentiate between 'important' warns that shouldn't get in the way of the run versus 'less important' warns that shouldn't get in the way of the run. Today, they are getting 100s of warns in their runs, and it is hard to get through the noise and triage these based on the type of test failure. Possible workaround for them is to add meta tags to their models that they can pull in alongside their test status data to help filter their warnings in their warehouse.
