### ISSUE TITLE
[CT-691] why isn't `postgres_get_relations` double-underscored?

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-core#5301]
for dbt-greenplum, @markporoshin [wants to inherit this macro](https://github.com/markporoshin/dbt-greenplum/pull/6#discussion_r882158493) without copying it. is there a reason it isn't double-underscored? Currently, the workaround is to modify this line in `impl.py`

https://github.com/dbt-labs/dbt-core/blob/10b27b963392cce33950d9cef31c7da5c3e65592/plugins/postgres/dbt/adapters/postgres/impl.py#L15-L16

to be this:

```
GET_RELATIONS_MACRO_NAME = "greenplum_get_relations"
```

but I don't know why!

https://github.com/dbt-labs/dbt-core/blob/10b27b963392cce33950d9cef31c7da5c3e65592/plugins/postgres/dbt/include/postgres/macros/relations.sql#L1

**Comment by dbeatty10** [comment]
@alzaar thanks for trying to find a `good_first_issue` to make your first contributions to this repo.

@dataders is this issue still relevant? If so, then @alzaar would like to try resolving it.

**Comment by alzaar** [comment]
Thanks @dbeatty10 In terms of any pre-reqs, is there anything I need to know before I get started (from the dbt docs) ? I would also like to know how can I replicate the usage locally.

**Comment by dbeatty10** [comment]
@alzaar you can set up your machine for local development using our [contributing](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) instructions (which include a local Postgres database using Docker).

Then you can create a local dbt project via [`dbt init`](https://docs.getdbt.com/reference/commands/init) or some other means. Run `dbt debug` to make sure the connection is working.

Create this file:
`analyses/test_macro.sql`
```
{% set result = postgres_get_relations() %}

{% if execute %}
{% do result.print_table() %}
{% endif %}
```

Run it and see the results:
```shell
dbt compile -s test_macro
```

After you've done your implementation, then you should be able to change `postgres_get_relations` within `analyses/test_macro.sql` to either be `get_relations` or `postgres__get_relations` and it should work.

**Comment by dbeatty10** [comment]
@alzaar if you've never run a dbt project before, then [this repo](https://github.com/dbt-labs/jaffle_shop_duckdb) is a quick way to get a first experience.
