### ISSUE TITLE
[CT-690] Ability to add package dependencies via the CLI

### ISSUE THREAD

**Issue by aaronsteers** [dbt-labs/dbt-core#5302]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

`dbt deps add ...`

Would accept args matching the specifications that land in yaml:

https://docs.getdbt.com/docs/building-a-dbt-project/package-management/#how-do-i-specify-a-package

For instance:

- `--package=PACKAGE` to set `package: 'PACKAGE'`
- `--version=VERS` to set `version: 'VERS`

Afterwards run the installation as would be performed by `dbt deps`.

### Describe alternatives you've considered

Today the alternative seems to be to manually edit the yaml or create some custom scripts which perform that yaml edit.

### Who will this benefit?

Users of packages on the hub will have a more streamlined installation method.

Community members can share a one-line snippet on how to add any community package to a project repo.

### Are you interested in contributing this feature?

Yes, definitely

**Comment by aaronsteers** [comment]
@gshank - Yes. If you are familiar with `poetry`, this is roughly equivalent to `poetry add ...` which adds the dependency to the `pyproject.toml` (analogous to `packages.yml` in dbt) and then installs/updates the environment (equivalent of running `dbt deps` with no args today).

Surgically editing the yaml file by hand just makes it harder to automate - especially in a cross-platform, cross-OS manner. A CLI version of 'deps add' would give a single cross-platform way of adding packages to a dbt project.

**Comment by jtcohen6** [comment]
@aaronsteers This is a neat idea! It sounds like something you'd be interested in working on / contributing?

@gshank Do you have qualms or hesitations about adding support for this? It would be tricky for us to support this outside the CLI / local file system context, but I think that's probably okay, given that it's really intended as a handy workflow for CLI users (= human beings).

I'm a bit more skeptical of the "`packages.yml` automation" workflow. I'd feel better about an approach that looks like constructing a Python dictionary of `packages`, and then either serializing it to yaml (as we do in [our testing framework](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/tests/fixtures/project.py#L203-L211)), or passing it into a (future) programmatic entrypoint of `dbt-core`.

**Comment by jtcohen6** [comment]
- Not something we're going to prioritize ourselves, but we might accept a PR from a motivated community member
- We would want to put this in a reasonable spot in the CLI tree (hard to do today, given current state of `argparse`)
- This feels more maintainable in a world where `deps` is split out into its own module / package
- We Like Rust, and Rust does support a `cargo add` CLI command

going to tag this `help_wanted` accordingly

**Comment by jtcohen6** [comment]
Update: It's NOT in `cargo`, it's a third-party extension: https://github.com/killercup/cargo-edit

Maybe that should change our point of view for native support...?

I do appreciate that editing `packages.yml` programmatically requires interacting with file systems (Windows!), which is a thing that dbt already knows how to abstract over [reasonably well](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/clients/system.py).
