### ISSUE TITLE
[CT-696] [Bug] DBT table alias not working and gives error `dataset.table does not match any nodes`

### ISSUE THREAD

**Issue by lucascr91** [dbt-labs/dbt-core#5308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

I have three datasets containing tables with the same name. Following [documentation][1], I use an alias to rename each table. For example, for a table I would like to call `mes_brasil` the DBT model is:

```sql
{{ config(alias='mes_brasil', schema='br_ibge_ipca') }}
SELECT *
FROM ...
```

even though the file name is `br_ibge_ipca__mes_brasil.sql`. I think this is supposed to work. However, when I run the flow DBT didn't recognize the alias and gives the message `'br_ibge_ipca.mes_brasil' does not match any nodes`. 

The whole project configuration can be found here: https://github.com/basedosdados/queries/blob/master/models/br_ibge_ipca/br_ibge_ipca__mes_brasil.sql

What am I doing wrong here? 

  [1]: https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-aliases

**Comment by jtcohen6** [comment]
@lucascr91 It sounds like this is an issue with _selecting_ the model (real name), rather than the name with which it's created in the database (alias)?

Both of these should work:
```
dbt run -s br_ibge_ipca__mes_brasil
dbt run -s config.alias:mes_brasil
```

But this won't, because the alias is a _configuration_ of the model, rather than a component of its fully-qualified name:
```
dbt run -s mes_brasil
```

**Comment by lucascr91** [comment]
sorry, I was indeed using:

```
dbt run -s mes_brasil
```

Change for `br_ibge_ipca__mes_brasil` solve it. Thanks
