### ISSUE TITLE
[CT-727] Hide Package Names from Documentation

### ISSUE THREAD

**Issue by taylorterwin** [dbt-labs/dbt-core#5333]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

We can disable individual models in main project but we can't do the same for an entire imported dbt package. (https://docs.getdbt.com/reference/resource-properties/docs)

**Comment by leahwicz** [comment]
AC: Turn `docs` into a real node config

**Comment by matt-winkler** [comment]
Hey @leahwicz curious: To make this backwards compatible, we'd basically maintain the existing code which maps `docs` properties into their own component of the `manifest.json`, correct? Are there other gotchas we'd need to think about in terms of overrides / collisions between that and a `docs` property that lives under `config`?

**Comment by grahamcarman** [comment]
Just saw that #5397 was just merged! Left me a uncertain though: is there still work to be done, to enable `show: false` at the `dbt_project.yml` level?

**Comment by b-per** [comment]
Even if it got merged to `main` it is not available to any stable release yet. I believe it will make its way to some `1.3 beta` and will be in the final release of dbt `1.3` (planned for Oct if I'm correct)

**Comment by jtcohen6** [comment]
Going to close this as resolved! Will be included in the next v1.3 beta prerelease

**Comment by mkleinbort-ic** [comment]
I'm trying to use this feature, but the nodes are still appearing in my DAG by default. Is there any way to turn off specific tags or sources by default? Ie. on opening the documentation's dag the filter is excluding them.

**Comment by b-per** [comment]
Hi! `docs: {show: false}` is hiding individual pages for the nodes but they will still appear on the docs site in the DAG ,in another grey color, without the ability to "drill into" them.

Today it is not possible to hide nodes from the docs site DAG

**Comment by G14rb** [comment]
Hi! Sorry for the stupid and articulate question, does it mean that the "docs show" will be grey, so still visible on DAG? Correct me if I'm wrong, in this case I could exclude them but in the DAG I won't see any lineage before and after. I mean it's not possible at this stage to go from A -> B -> C and visualize just A -> C using {show: false}. Thanks

**Comment by b-per** [comment]
Yes, `show: false` will still show in the DAG, greyed out, without the ability to drill into the docs of the hidden model. 

Today the dbt docs don't support removing models from the lineage entirely.
