### ISSUE TITLE
[CT-741] [Feature] evaluate selector and list selected objects

### ISSUE THREAD

**Issue by solomonshorser** [dbt-labs/dbt-core#5358]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

I have some complex selectors in some large projects.

It would be nice if there was a way that DBT could tell me the names of the models/tests/other objects that will be captured by a selector. Mostly for testing/debugging purposes, or when trying to modify a complex selector and ensuring that it selects the correct things, without needing to compile or run.

Maybe something like this, for models:
```bash
$ dbt eval --selector some_selector ...
Models/tests captured by selection criteria "some_selector":
Name         Type       Source
---------------------------------------------
ModelA      Model    path:staging/blah
ModelB      Model    path:staging/blah/blerg
ModelD      Model    fqn:my_base_package.common_models.foo.bar
id_not_null Test      fqn:my_base_package.common_models.foo.bar
```

### Describe alternatives you've considered

I can run `dbt clean && dbt compile --selector some_selector ...` and then look at what's in `target/compiled/` and I could probably even write a shell script that would do generate output similar to what I want above...

...But I've noticed that when I run `dbt compile` and I have  a custom macro with a known bug in a model that is _not_ covered by the selector, `compile` _still_ executes the macro and things still break. I need to manually tweak the macro to work around this to test selection criteria.

I'd like to be able to get a list of _all_ selected things without having to locally patch/gitignore the macro to work around a temporary bug.

### Who will this benefit?

Anyone who is writing complex selectors and wants to get a quick idea of what their selector will capture.

### Are you interested in contributing this feature?

Yes, but I'm not sure I have the necessary skills or time.

**Comment by jtcohen6** [comment]
Hey @solomonshorser! Give it a go:
```sh
dbt ls --selector some_selector --output json --output-keys name,resource_type,path,fqn
{"fqn": ["my_base_package", "common_models", "foo", "bar"], "path": "models/common_models/foo/bar.sql", "name": "bar", "resource_type": "model"}
...
```
Should we add support for "Markdown table" as an `--output` format for `dbt list`? :)

**Comment by solomonshorser** [comment]
Oh, neat! I didn't know about this. I'll give it a try and see if this gives me what I want.

**Comment by jtcohen6** [comment]
> a macro gets triggered (I can tell because it logs to the console as it queries and does stuff)

dbt does parse your project in order to understand all the resources defined in it (whether each one is enabled, their inter-dependencies, etc). To do that, it does some Jinja rendering. If you have calls to `{{ log() }}` in that code, it will be rendered (and logged) while dbt is parsing the code. I agree this can be confusing... let me open an issue.

To be clear: dbt will _not_ do any "execution"-time behavior at parse time. It doesn't actually run any queries against the database when you run `dbt ls`. You could confirm this by running `dbt ls` without an internet connection.

**Comment by solomonshorser** [comment]
So... trying to log the inner workings of my macro result in it running when I don't intend it to, which leads to outputs that are strange/contradictory _because_ it ran outside the expected context? 

Your explanation makes sense, it just doesn't match how I _thought_ DBT processed my files. I guess I should remove the log statements to avoid further confusion.

**Comment by jtcohen6** [comment]
I agree, this requires you to appreciate a bit more about dbt's internals than you should really need to. Opened up https://github.com/dbt-labs/dbt-core/issues/5360

**Comment by jtcohen6** [comment]
Yes! Worth noting that `generate_schema_name` is a "special case" — unlike almost all other macros, it's _actually_ resolved during parsing, since dbt needs to know all node configuration (including database representations) by the end of parse time.

Out of all the macros in existence, there's [only a few macros](https://github.com/dbt-labs/dbt-core/blob/72b6a80b07b3acc9aa64ae65c5d82191dbb1aa11/core/dbt/parser/partial.py#L57-L66) that work like that:
- `ref`
- `source`
- `config`
- `generate_alias_name`
- `generate_schema_name`
- `generate_database_name`

**Comment by solomonshorser** [comment]
One more thing: Is there any documentation on how tests in `tests/generic` are affected by selectors?

I had a problem where a test was getting executed prematurely because it references a model covered by the selector, but it _also_ references a model covered by a different selector, and that model had not yet been created (there is a very specific sequence to how these models get created). I suspect that because the test referenced a model that was covered by the selector, the test got evaluated/executed and then caused an error because the other model did not yet exist. I was able to exclude this test by using its fully-qualified name, but it was a bit of a surprise and I'm still not sure I understand why it happened. And yes, it _was_ listed by `dbt ls --selector my_selector...` but I really don't understand _why_ - the model that actually _uses_ the test had not been selected. 

If there's a particular way that generic tests are handled by selectors, it would be nice to know more.

**Comment by leahwicz** [comment]
@solomonshorser - here are our current docs so you can take a closer look https://docs.getdbt.com/reference/node-selection/test-selection-examples#indirect-selection

There are some edge cases but they are listed in the doc with examples.

**Comment by solomonshorser** [comment]
@leahwicz Ah, I don't think I saw that bit about the tests. Thanks!
