### ISSUE TITLE
[CT-749] [Bug] Console Log output should use utf8

### ISSUE THREAD

**Issue by 1c7** [dbt-labs/dbt-core#5375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## The dbt model contain one Chinese charactor "无" (which mean "None")
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/1804755/173751678-8d1de562-b884-49b8-99de-add7c6b298da.png">

## We are using `dbt-clickhouse`
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/1804755/173751874-349c557f-b0e0-4712-bc99-d777c80a7f95.png">

## This SQL is wrong, it should use single quote `'无'` not double quote `"无"`
```sql
{{ config(materialized = 'view') }} 

with batch2022Spring as (
  SELECT id
  from mp_production.apply_applications
  WHERE deleted_at IS NULL
    AND batch_id = 7
    AND status = 'submitted'
),

final as (
  select *
  from mp_production.apply_answers
  WHERE notEmpty(value_string)
    AND value_string NOT IN ["无",'/', '-', 'none']
    AND question_key NOT IN ['video_url', 'company_has_investment', 'company_url']
    AND application_id IN batch2022Spring
)

select * from final
```
https://clickhouse.com/docs/en/sql-reference/syntax/
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1804755/173751976-eb280578-ba49-447d-841d-53ce60e74284.png">

## The point is, when dbt output Error message, it should display utf8 charactor correctly。
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/1804755/173752254-213e790e-c0e6-4959-b8db-3a5ff054779c.png">

### Expected Behavior

When dbt-core output message, utf8 charactor should be display correctly.

### Steps To Reproduce

1. write a wrong ClickHouse SQL like `select * from post where title = "无"` ( `"无"`should use single quote like `'无'` not double quote)
2. `dbt run`
3. the error message didn't display utf8 charactor as is. but output something like `'\xe6\x97\xa0'`
`b"\xe6\x97\xa0".decode('utf8')` can output correct string `无`

### Relevant log output

```shell
05:49:53  Running with dbt=1.1.0
05:49:53  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 186 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
05:49:53
05:49:53  Concurrency: 1 threads (target='dev')
05:49:53
05:49:53  1 of 1 START view model mp_production_dbt_playground.batch_2022_Spring ......... [RUN]
HTTPDriver url http://ec2-71-131-225-146.cn-north-1.compute.amazonaws.com.cn:8123 returned response code 404)
b"Code: 47. DB::Exception: Missing columns: '\xe6\x97\xa0' while processing query: 'SELECT id, application_id, question_key, value_boolean, value_string, value_integer, value_array, deleted_at, created_at, updated_at FROM mp_production.apply_answers WHERE notEmpty(value_string) AND (value_string NOT IN [`\xe6\x97\xa0`, '/', '-', 'none']) AND (question_key NOT IN ['video_url', 'company_has_investment', 'company_url']) AND (application_id IN (batch2022Spring AS _subquery53))', required columns: 'id' 'question_key' 'value_integer' 'value_boolean' 'value_string' 'application_id' '\xe6\x97\xa0' 'value_array' 'created_at' 'deleted_at' 'updated_at', maybe you meant: ['id','question_key','value_integer','value_boolean','value_string','application_id','value_array','created_at','deleted_at','updated_at']. (UNKNOWN_IDENTIFIER) (version 22.4.3.3 (official build))\n"
05:49:54  1 of 1 ERROR creating view model mp_production_dbt_playground.batch_2022_Spring  [ERROR in 0.39s]
05:49:54
05:49:54  Finished running 1 view model in 1.26s.
05:49:54
05:49:54  Completed with 1 error and 0 warnings:
05:49:54
05:49:54  Database Error in model batch_2022_Spring (models/example/batch_2022_Spring.sql)
05:49:54    :HTTPDriver url http://ec2-71-131-225-146.cn-north-1.compute.amazonaws.com.cn:8123 returned response code 404)
05:49:54     b"Code: 47. DB::Exception: Missing columns: '\xe6\x97\xa0' while processing query: 'SELECT id, application_id, question_key, value_boolean, value_string, value_integer, value_array, deleted_at, created_at, updated_at FROM mp_production.appl
05:49:54    compiled SQL at target/run/zhengcheng_dbt/models/example/batch_2022_Spring.sql
05:49:54
05:49:54  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: macOS
- Python: 3.9.13
- dbt: 1.1.0
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

ClickHouse

**Comment by jaypeedevlin** [comment]
Hey Cheng, I don't work for dbt but I follow along with the issues.  I think like the issue you opened yesterday the problem lies somewhere in either the clickhouse adapter, the library it uses to connect to clickhouse, or clickhouse itself.

Here's a screenshot of an error I get back from Snowflake when I insert an emoji into my query randomly:

<img width="977" alt="image" src="https://user-images.githubusercontent.com/17235807/173768924-39338d20-b9c8-4cb0-9c20-0f90a505d311.png">

You can see that dbt-core renders the utf-8 character that the snowflake adapter gives it fine, so it's likely somewhere in the clickhouse paths that things are going awry.

As an aside, I might suggest that you join the [dbt Slack community](https://www.getdbt.com/community/) and post any questions you have there as a first-stop.  Folks like me are there pretty much 24 hours a day who can help community members like yourself with queries, which saves you from having to write up a GitHub issue for every question you have and wait for an official response.

**Comment by jtcohen6** [comment]
@jaypeedevlin I hope the move went smoothly! Welcome to Early Morning Issues :)

Was just about to pop in to say the same thing: When I was testing #5371 yesterday (again, using Postgres), I was able to see the original character in my log output:
```
07:38:57  Database Error in model model_a (models/model_a.sql)
07:38:57    syntax error at or near "["
07:38:57    LINE 18:     AND value_string NOT IN ["无",'/', '-', 'none']
07:38:57                                         ^
07:38:57    compiled SQL at target/run/test/models/model_a.sql
```
This does seem like a good lead on why `dbt-clickhouse` / `clickhouse-connect` isn't handling the characters in the way you'd expect! I think an issue [over there](https://github.com/ClickHouse/dbt-clickhouse/issues) is the right next step.
