### ISSUE TITLE
[CT-763] [Bug] 1.1.1 not available on Docker GCR

### ISSUE THREAD

**Issue by alrolorojas** [dbt-labs/dbt-core#5398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

dbt-core 1.1.1 is missing a Docker image on ghcr.io/dbt-labs/dbt-core even though the new version was announced a few days ago https://getdbt.slack.com/archives/C37J8BQEL/p1655377946934239

### Expected Behavior

Docker image for dbt-core tagged with 1.1.1 exists on ghcr.io/dbt-labs/dbt-core

### Steps To Reproduce

1. Go to ghcr.io/dbt-labs/dbt-core
2. Look for 1.1.1 (missing)

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### What database are you using dbt with?

snowflake

**Comment by leahwicz** [comment]
@alrolorojas sorry about that! It should be showing up now. If not, please let me know and re-open the issue
