### ISSUE TITLE
[CT-767] [Feature] Supporting on-the-fly configuration of `target-path`

### ISSUE THREAD

**Issue by isidentical** [dbt-labs/dbt-core#5399]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

A flag (like `--target-path=` or `--target-dir=`) to customize the [`target-path` variable](https://docs.getdbt.com/reference/project-configs/target-path) used by `dbt run` (and others) temporarily. If there is already a `target-path` set in the configuration file, this option will **override** it for the same `run`.

### Describe alternatives you've considered

An environment variable (like `DBT_TARGET_PATH`) would also be an alternative. The benefits include the ease of implementation (not needing to add the precise config option to each subcommand that needs to deal with `target-path`). But it would reduce the chances of discovery (since `--help` won't show it by default).

### Who will this benefit?

Anyone who has more than 1 DBT subprocess running at any given time. Our use case involves spawning multiple DBT subprocesses, and sometimes they clash and override each other's `run_results.json` files.

### Are you interested in contributing this feature?

Yes

### Anything else?

For more context, please see [this thread](https://getdbt.slack.com/archives/CBSQTAPLG/p1655767766784039) in DBT's slack channel.

**Comment by jtcohen6** [comment]
Also: We should find some way to square config that's set in `dbt_project.yml` versus `profiles.yml`, in cases where it makes sense to unify both under "global" configs. In the past, config that's relevant to _project directory files_ tended to go in the project file, but there's also a compelling proposal to support `profiles.yml` in the same directory by default: https://github.com/dbt-labs/dbt-core/issues/5411

That's out of the scope of this issue/PR, but it felt like a relevant place to leave the thought for now.

**Comment by isidentical** [comment]
Thanks a lot for your answer @jtcohen6! Two quick questions before I start the implementation:

> I think that sort of env var override should be the default/implicit behavior, too.

> explicitly enables setting these via CLI flag or DBT_-prefixed env var, following logic in [the flags module](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/flags.py)

Should #5402 initially aim for adding only the environment variables (which would solve the issue for us / and for the other people who have the use cases I've shared) or should it add both the env vars and the cli flags?

 For the environment variables, are the following namings make sense or should we consider `DBT_CONFIG_` prefix?
- `DBT_TARGET_PATH`
- `DBT_LOG_PATH`

**Comment by jtcohen6** [comment]
I'd much prefer to thread these through the same centralized `flags` logic linked above, rather than one-off calls to `os.getenv` nested deep in the `dbt_project.yml` parsing logic. At that point, it's probably not much additional work to support both CLI flags and env vars.
