### ISSUE TITLE
[CT-781] Bump manifest schema to v6 for v1.2

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5417]
v1.2 will include a schema change for `manifest.json`, with the addition of the `grants: {}` default config. We'll need to update, document `v6`, and add/declare backwards compatibility (per https://github.com/dbt-labs/dbt-core/pull/5346):

https://github.com/dbt-labs/dbt-core/blob/d5608dca322c63f1a894174b1f280ae55a217ab8/core/dbt/contracts/graph/manifest.py#L1138-L1140

As I've said many many times before (in https://github.com/dbt-labs/dbt-core/issues/4617 as elsewhere):

> I'm interested in any small, tactical lifts we can make so that we're not bumping the manifest schema version in every single new minor version. At the same time, we're eager to provide other interfaces into manifest information, over which we have more control

Given that `config` can accept any values, it probably makes more sense to treat this in our JSONSchema as a `dict[str, Any]`, rather than inferring its defaults from the node config classes.

The ability to declare backwards compatibility does remove this as an issue for most end users, but it remains true that we're creating unneeded manual work for metadata consumers.

This will also require updates to:
- https://github.com/dbt-labs/schemas.getdbt.com
- https://docs.getdbt.com/reference/artifacts/manifest-json

**Comment by jtcohen6** [comment]
Issue for updating docs: https://github.com/dbt-labs/docs.getdbt.com/issues/1667

**Comment by emmyoop** [comment]
`compatible_previous_versions` was updated as part of #5027.
