### ISSUE TITLE
[CT-793] [Feature] Testable _tmp tables in incremental models

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-core#5427]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Currently, it's only possible to apply dbt tests to the final table of an incremental model. There are circumstances where it would be useful to apply tests (both singular and generic) to the incremental _tmp table created by dbt in an incremental model. In large tables, it would drastically increase the speed and performance of tests by only tested new/updated data.

**Comment by jtcohen6** [comment]
Thanks @NiallRees! Two reasons I can see for wanting this:
- Prevent the merge/upsert/overwrite if the test fails (lengthy discussion about this just now: https://github.com/dbt-labs/dbt-core/discussions/5687)
- Save time & money by querying just the new data — it sounds like this is your main interest

I know folks have written (very tricky) custom materializations to accomplish both outcomes before. So long as the merge/upsert/overwrite logic is simple enough (and dbt _really_ wants to keep it simple), there should be minimal or zero risk of the test passing on the "new" data (no dupes, no nulls, etc), and yet failing on the "final" table.

Out of curiosity, have you experimented with using the [`where` config](https://docs.getdbt.com/reference/resource-configs/where) for generic tests? (It's not supported for singular tests, but I suppose it or something like it could be.) For instance, if you're always updating the last 1/3/7 days of data, could you limit the test query with a filter accordingly? That should be enough for Snowflake and BigQuery to prune partitions and run faster queries, though perhaps still slower than if the test ran against new data only.

**Comment by mrcool4** [comment]
Hi Team, Any update on this feature? 
Addition of this feature would mitigate the necessity for a rollback should a test failure occur.
