### ISSUE TITLE
[CT-803] Serialization errors in AdapterLogger

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5436]
Two places we've run into this:
- https://github.com/databricks/dbt-databricks/issues/115 (follow-up conversation in https://github.com/dbt-labs/dbt-spark/pull/371)
- https://github.com/dbt-labs/dbt-bigquery/issues/206

To quote @nathaniel-may from https://github.com/dbt-labs/dbt-spark/pull/371#issuecomment-1159184064, we should solve this in `dbt-core`, rather than pre-stringifying all values which might be passed into the `AdapterLogger`, because:

> This works because you're explicitly getting the value's string representation when you are making the log call. The reason the Python standard library doesn't do this, and instead uses the style of the original code is so that that string function is only called for the additional arguments if the log line is actually logged. For example, if you have a ton of debug lines with big values but you're only logging info level messages, those potentially expensive string conversions never actually happen.

> The place this should be handled is [here in core](https://github.com/dbt-labs/dbt-core/blob/d257d0b44c8118328a98caac5cb916eed4c3506c/core/dbt/events/types.py#L72) which was the original intent. If this is not working we should investigate modifying this line in core so that we can avoid calling string functions unnecessarily both to comply with a standard Python logging interface in adapters, and to avoid potential performance issues.

https://github.com/dbt-labs/dbt-core/blob/d257d0b44c8118328a98caac5cb916eed4c3506c/core/dbt/events/types.py#L72

**Comment by nathaniel-may** [comment]
As @jtcohen6 calls out in [this comment](https://github.com/databricks/dbt-databricks/issues/115#issuecomment-1159163212). The event should be serializable via `to_dict()` which is being called [here](https://github.com/dbt-labs/dbt-core/blob/1071a4681df91633301fdf23e34de819b66fbeb7/core/dbt/events/functions.py#L140) for json log lines.
