### ISSUE TITLE
[CT-812] [Feature] Refactor generic tests so they don't do select * !!!

### ISSUE THREAD

**Issue by adamcunnington-mlg** [dbt-labs/dbt-core#5441]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

The implementation of the generic tests that get shipped with DBT use bad practice; SELECT *, COUNT(*) etc. I think COUNT(*) probably isn't that bad with most modern databases but SELECT * is terrible.

There's no reason in these tests to do this as DBT only cares about # of rows returned. Please can you refactor these tests to avoid this unnecessary db query cost.

### Describe alternatives you've considered

None

### Who will this benefit?

Everyone in the world

### Are you interested in contributing this feature?

Sure

**Comment by jtcohen6** [comment]
@adamcunnington-mlg Thanks for opening.

In most cases, test queries with `select *` are actually being wrapped in `select count(*)` (the default `fail_calc`). My understanding has long been that modern data warehouses / query optimizers are smart enough to see the `count` aggregate and avoid scanning all underlying data; and that `count(*)` and `count(1)` are functionally identical. Is that a faulty assumption for your data warehouse? We're always interested in seeing benchmarks / performance measurements, or finding out if there's something we're missing!

What's the benefit to `select *`? Including other contextual columns from the underlying model may assist with debugging test failures, in cases where users have enabled storing failures ([docs](https://docs.getdbt.com/reference/resource-configs/store_failures)).

As it is, I believe there's only one generic test, available out of the box in `dbt-core`, that includes `select *`: The `not_null` test. We recently added some conditional logic (https://github.com/dbt-labs/dbt-core/pull/4777) to select only one column by default, and `select *` iff `--store-failures`.

https://github.com/dbt-labs/dbt-core/blob/cbd4570c67dbcd37e873f08aa9989210f65c177d/core/dbt/include/global_project/macros/generic_test_sql/not_null.sql#L3-L7

That change was [included in v1.1](https://github.com/dbt-labs/dbt-core/releases/tag/v1.1.0#:~:text=Change%20behaviour%20of%20non_null%20test%20so%20that%20it%20only%20selects%20all%20columns%20if%20%2D%2Dstore%2Dfailures%20is%20enabled.%20(%234769%2C%20%234777)).

**Comment by adamcunnington-mlg** [comment]
Wow, thanks for fast response.

Yep, I imagined that COUNT(*) is fine - I have no reason to think otherwise.
Got it about the improvement in 1.1, this is call! FYI, DBT Cloud defaults new environments specifically to 1.0 instead of latest (even though the drop down contains 1.1 (latest)!" Maybe that's some stale metadata that needs updating in DBT Cloud...

Thanks, closing issue.
