### ISSUE TITLE
[CT-824] [Bug] Docker image on dockerhub is outdated

### ISSUE THREAD

**Issue by janheyd-polyteia** [dbt-labs/dbt-core#5455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The latest version available at https://hub.docker.com/r/fishtownanalytics/dbt/tags is 1.0.0

### Expected Behavior

The latest version should be 1.1.1 or the image should be marked as unsupported with info where to get it instead if possible

**Comment by leahwicz** [comment]
@janheyd-polyteia thanks for raising this! We moved to using GitHub Packages to store our images: https://github.com/orgs/dbt-labs/packages?tab=packages

I didn't realize you could mark in unsupported in Docker so I can take a look at that so we can redirect people

**Comment by leahwicz** [comment]
I just updated our DockerHub descriptions and README to point to GitHub Packages instead and state that our use there is deprecated. Thanks @janheyd-polyteia for the suggestion and sorry about the confusion
