### ISSUE TITLE
[CT-862] uniqueness constraint as list does not work in incremental model

### ISSUE THREAD

**Issue by smithj51** [dbt-labs/dbt-core#5493]
I am trying to build a BigQuery incremental model using a list of unique keys as recommended [HERE](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#defining-a-uniqueness-constraint-optional), but it seems the **_merge on_** piece of the compiled SQL does not parse the unique keys as a list, while the **_when matched then update_** and the **_when not matched then insert_** pieces do correctly parse it as a list. The **_merge on_** piece results in the syntax error **Unexpected "["**.

This is what SHOULD happen:

```
unique_key=['col1', 'col2']

merge into <dest>
using <source>
on DBT_INTERNAL_SOURCE.col_1 = DBT_INTERNAL_DEST.col_1 AND
   DBT_INTERNAL_SOURCE.col_2 = DBT_INTERNAL_DEST.col_2
when matched then update set
   `col1` = DBT_INTERNAL_SOURCE.`col1`, `col2` = DBT_INTERNAL_SOURCE.`col2`
when not matched then insert
   (`col1`, `col2`)
values
   (`col1`, `col2`)
```

but what ACTUALLY happens is this:
```
unique_key=['col1', 'col2']

merge into <dest>
using <source>
on DBT_INTERNAL_SOURCE.['col1', 'col2'] = DBT_INTERNAL_DEST.['col1', 'col2']
when matched then update set
   `col1` = DBT_INTERNAL_SOURCE.`col1`, `col2` = DBT_INTERNAL_SOURCE.`col2`
when not matched then insert
   (`col1`, `col2`)
values
   (`col1`, `col2`)
```

**Comment by jtcohen6** [comment]
Hey @smithj51, which version of dbt are you using? Support for `unique_key = [list, of, columns]` was added in dbt Core v1.1

**Comment by smithj51** [comment]
ah yup, I was under the misconception that dbt Cloud would automatically use the latest version of dbt but just found the [documentation](https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/cloud-choosing-a-dbt-version) regarding changing the dbt versions within the different environments. problem solved, thank you!

**Comment by jtcohen6** [comment]
Glad you were able to get this working!
