### ISSUE TITLE
[CT-872] Move changie to reusable GHA

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#5501]
Convert [.github/workflows/changelog-check.yml](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/changelog-check.yml) to be reusable across repos.

### Open Questions:
- Should it live in dbt-labs/actions?
  - All actions should be split out or they should all live in here.  Otherwise it becomes really confusing where to look.
- Should it live in its own repo?
  - seems small for that
- Should a new repo be created that's for checks (action-checks)?
  - There are no other checks like this

**Comment by leahwicz** [comment]
Here's my 2 cents on this-
* Actions that are mission critical should be their own repo
* Actions that are heavily tied to a code base at a specific point in time should be their own repo (i.e. the Action is going to need updating a lot to match changes in the code base)
* Actions that are external tooling should be in a common repo
* Actions that are not likely to change or have critical refactoring should be in a common repo
