### ISSUE TITLE
[CT-875] [Bug] fail on_schema_changes error message not verbose enough

### ISSUE THREAD

**Issue by ilanbenb** [dbt-labs/dbt-core#5504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
I am using DBT on posgresql.
When I use on_schema_changes ` on_schema_change='fail',` I expect to get a verbose explanation of what the diff between the source and destination schemas are.

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/12747039/180051037-ee21b6d4-ca12-4079-97a3-47bdb5cb7be8.png">

### Expected Behavior

Getting extra information to fix my failed schema fast.

In this context:

`  {% set msg %}
    In {{ target_relation }}:
        Schema changed: {{ schema_changed }}
        Source columns not in target: {{ source_not_in_target }}
        Target columns not in source: {{ target_not_in_source }}
        New column types: {{ new_target_types }}
  {% endset %}`

### Environment

```markdown
- OS: mac and linux ( container based on  python:3.8-slim-buster  )
- Python: 3.8
- dbt: 1
```

### What database are you using dbt with?

postgres

**Comment by jtcohen6** [comment]
@ilanbenb Great point, thanks for opening!

I think we include this info in a debug log message today, but making it available in the info-level logs will be all the easier for folks to discover.

I see you've already opened a PR for this, so I'm going to mark this a `good_first_issue` :)

**Comment by ilanbenb** [comment]
Pull request merged
