### ISSUE TITLE
[CT-890] Infer Core Team membership in changie

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#5516]
The changie config currently has a [hardcoded list](https://github.com/dbt-labs/dbt-core/blob/1071a4681df91633301fdf23e34de819b66fbeb7/.changie.yaml#L34) of Core Group members that we want to exclude from the Contributors list in the `CHANGELOG.md`.  As we convert the adapters to use changie, it would be helpful to not rely on a hardcoded list as it's both hard to keep in sync and an unnecessary amount of work as the team evolves.

It would be great to leverage the [Core Team](https://github.com/orgs/dbt-labs/teams/core) membership at the org level.  it is maintained in a single place and is kept up to date.

`dependabot[bot]` and `snyk-bot` could remain hard coded as those do not change and we generally are not adding more bots.

The GitHub CLI allows you to [list team members](https://docs.github.com/en/rest/teams/members#list-team-members).  The hardcoded list in the changie config could be replaced with an environment variable (sprig [supports](http://masterminds.github.io/sprig/os.html) environment variables).  That environment variable would be populated in a GitHub action step before running `changie batch`.

**Comment by lostmygithubaccount** [comment]
actually have a little function for this: https://github.com/lostmygithubaccount/codyspace/blob/main/backfill-project.py#L34-L46

will attempt to integrate into this changie workflow

**Comment by emmyoop** [comment]
The hardcoded list of the Core Group members is in [`.changie.yml`](https://github.com/dbt-labs/dbt-core/blob/main/.changie.yaml).  There is also an instance of the same file in the snowflake repo [here](https://github.com/dbt-labs/dbt-snowflake/blob/main/.changie.yaml) that will need to be updated.  I was thinking it would be an environment variable for the Core Coup members there.  `"dependabot[bot]" "snyk-bot"` will need to stay hardcoded.

Updating `changie.yml` will be more than just replacing the current list with an environment variable.  The `yml` file will also need to be modified to read in the environment variable and combine it into a list with the bots so that the Contributors section can utilize them.  Sprig templating does allow [env vars](http://masterminds.github.io/sprig/os.html). 

If possible, the env var should have a default so that we can run changie batch locally without setting env vars.  However if that's not possible it will be fine as we would rarely be running it locally.

Then we need to update [version-bump.yml](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/version-bump.yml) to take in that variable and use it in addition to the bots to generate the Contributor section of the Changelog.

**Comment by emmyoop** [comment]
The changes have been made to changie ([PR](https://github.com/miniscruff/changie/pull/386)) to use env vars v1.10.0.  It should be possible now to implement this.
