### ISSUE TITLE
[CT-891] [Bug] Incremental model fails to load when inserting into empty table (Snowflake)

### ISSUE THREAD

**Issue by lee-chris** [dbt-labs/dbt-core#5517]
If I have an incremental model that was initially created from an empty source table, subsequent runs will not populate the table, even after the source table becomes populated.

Using an example from the docs:
```
{% if is_incremental() %}

  -- this filter will only be applied on an incremental run
  where event_time > (select max(event_time) from {{ this }})

{% endif %}
```

If the table is empty, then this where condition always returns false because any equality comparison to null is false.

The is_incremental() macro should probably check to see if the table is empty or not.

**Comment by lostmygithubaccount** [comment]
hi @lee-chris, thanks for opening! it isn't exactly a supported scenario and we're unlikely to address this, so I'm going to close as "won't fix". 

Do you think a warning at the top of [the doc page](https://docs.getdbt.com/reference/resource-configs/glue-configs#the-insert_overwrite-strategy) noting that incremental models on empty source tables aren't supported would be helpful? 

@jtcohen6 has hinted that you may be able to write some more clever code -- I suspect with further Jinja statements to check whether the table is empty first -- could be possible, but in general we'd probably recommend starting with a table and moving to an incremental model at a certain scale.
