### ISSUE TITLE
[CT-895] [Spike] Consolidate current_timestamp & associates

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5521]
Split out from https://github.com/dbt-labs/dbt-utils/pull/577 + https://github.com/dbt-labs/dbt-utils/pull/597, resolves https://github.com/dbt-labs/dbt-utils/issues/339

### Describe the feature
Rewrite `current_timestamp` + `current_timestamp_utc` to be built out of core/plugin functionality (e.g. `date_function`) and a `convert_timezone` macro.

Currently in `dbt-core`, there are _three_ methods/macros all purporting to do the same thing. I've linked the examples from Postgres.
- [`date_function`](https://github.com/dbt-labs/dbt-core/blob/75f3e8cb749c7b52d226844394ecb34c1e0070a4/plugins/postgres/dbt/adapters/postgres/impl.py#L66-L68) (Python classmethod)
- [`snapshot_get_time`](https://github.com/dbt-labs/dbt-core/blob/75f3e8cb749c7b52d226844394ecb34c1e0070a4/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L131-L133) (macro used for snapshots)
- [`current_timestamp`](https://github.com/dbt-labs/dbt-core/blob/75f3e8cb749c7b52d226844394ecb34c1e0070a4/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L121-L123) (macro used nowhere, except as [_the default implementation_ of `snapshot_get_time`](https://github.com/dbt-labs/dbt-core/blob/75f3e8cb749c7b52d226844394ecb34c1e0070a4/core/dbt/include/global_project/macros/materializations/snapshots/strategies.sql#L50-L59) — but often the two are different, mostly for data type reasons)

Then, there are the two versions currently living in `dbt-utils`:
- [`dbt_utils.current_timestamp`](https://github.com/dbt-labs/dbt-utils/blob/44eeb1978c1c720baca2e2cfe07671e94db02c7c/macros/cross_db_utils/current_timestamp.sql#L5)
- [`dbt_utils.current_timestamp_in_utc`](https://github.com/dbt-labs/dbt-utils/blob/44eeb1978c1c720baca2e2cfe07671e94db02c7c/macros/cross_db_utils/current_timestamp.sql#L31)

### Things we need to figure out

- Are the different implementations here functionally identical? (Doug's initial finding was "yes": https://github.com/dbt-labs/dbt-utils/pull/597#issuecomment-1142239494)
- If the data types are different, why?
- In what cases would their functional result differ? I'm imagining a case where Snowflake parameters [`TIMEZONE`](https://docs.snowflake.com/en/sql-reference/parameters.html#timezone) and [`TIMESTAMP_TYPE_MAPPING`](https://docs.snowflake.com/en/sql-reference/parameters.html#timestamp-type-mapping) are both set

### Ideal outcome

When I close my eyes and imagine how this could be really good:
1. We have _one_ method/macro, defined in `dbt-core` and implemented by each adapter plugin, that provides the SQL for getting the current timestamp. Whenever we need the current timestamp in a different data type, we use that `current_timestamp` macro plus a data type conversion function (see dbt-labs/dbt-utils#586).
2. We have a `convert_timezone` macro, defined in `dbt-core` and implemented by each adapter plugin. @clausherther [has already written one](https://github.com/calogica/dbt-date/blob/main/macros/calendar_date/convert_timezone.sql) for the `dbt-date` package—Claus, would you have any interest in kicking it upstream? :)
3. It's trivial to write a `current_timestamp_in_utc` macro that builds on top of 1+2. Whether that lives in `dbt-core`, `dbt-utils`, or somewhere else doesn't matter so much to me. Wherever it lives, it should look a lot like [`dbt_date.now(tz=None)`](https://github.com/calogica/dbt-date/blob/main/macros/calendar_date/now.sql). We'd leave the `dbt_utils` one in place for backwards compatibility.

### Describe alternatives you've considered
Leaving all of it where it is :)

### Additional context

Timezones are no fun

This stuff is pretty tricky to test. [We're not _really_ testing it currently](https://github.com/dbt-labs/dbt-utils/blob/44eeb1978c1c720baca2e2cfe07671e94db02c7c/tests/functional/cross_db_utils/fixture_current_timestamp.py#L4). I had an idea in https://github.com/dbt-labs/dbt-utils/pull/577#discussion_r869149492, but it's not a great one. We are indirectly testing our use of `snapshot_get_time` in `dbt-core` functional tests (specifically [`test_hard_delete_snapshot`](https://github.com/dbt-labs/dbt-core/blob/main/tests/functional/simple_snapshot/test_hard_delete_snapshot.py).

### Who will this benefit?

- Users who want to call well-named macros, and expect them to do the thing they're meant to
- Claus, as maintainer of the `dbt-date` package (I hope!)

**Comment by clausherther** [comment]
Just learned a couple of things on Snowflake:
- The 3 parameter version of convert_timezone that allows you to specify a source timezone does not accept a `timestamp_tz` column (any more?). So, one has to convert to timesamp_ntz before passing that in.
- If your SF instance/account/session/... is to set to timezone X and you're trying to convert what you think is a timestamp in timezone Z to timezone X, nothing will actually get converted, b/c SF assumes source and target are the same (and you just stripped off the tz 😞 )

**Comment by dbeatty10** [comment]
Added a comparison of dbt-core+adapters implementation vs. dbt-utils in [this](https://github.com/dbt-labs/dbt-utils/pull/597#issuecomment-1231074577) comment.

[TLDR](url): they don't appear to yield the same data types.

**Comment by dbeatty10** [comment]
@Fleid ☝️ this is the ticket that we were discussing earlier today about inconsistent timestamp data types across adapters.

**Comment by dbeatty10** [comment]
Awesome to see your thinking on this @jtcohen6 !

Agreed that inconsistency is unavoidable unless we break things. Also agreed that it is better to preserve that inconsistency rather than introducing breaking changes before dbt v2.

What's the advantage of adding `current_timestamp_backcompat` to dbt-core?

Is it so that users of dbt_utils >= 1.0.0 can update their references from `{{ dbt_utils.current_timestamp() }}` to `{{ current_timestamp_backcompat() }}` (assuming the end user has dbt Core >= 1.3.0 installed)?

If that is the case, how is that better for users rather than leaving `{{ dbt_utils.current_timestamp() }}` as-is?

**Comment by jtcohen6** [comment]
> Is it so that users of dbt_utils >= 1.0.0 can update their references from `{{ dbt_utils.current_timestamp() }}` to `{{ current_timestamp_backcompat() }}` (assuming the end user has dbt Core >= 1.3.0 installed)?

Exactly my thinking.

> If that is the case, how is that better for users rather than leaving `{{ dbt_utils.current_timestamp() }}` as-is?

If there's going to be inconsistency, I'd rather have it all in one place!

Right now, it's spread across `dbt-core`, adapter plugins, _and_ `dbt-utils`. By moving from `dbt-utils` into `dbt-core` / adapters, entropy may not actually be reduced, but it is more concentrated.

And we can make clear that the backcompat is _just_ there for that reason — backward compatibility — and shouldn't be used by anyone new. That doesn't feel clear if we keep `dbt_utils.current_timestamp` around. This feels directionally correct toward having a clear + concise recommendation for what to do _going forward_, even if we need to keep some other crufty stuff around.

**Comment by colin-rogers-dbt** [comment]
Here is where I ended up at for dbt-core changes: https://github.com/dbt-labs/dbt-core/pull/5838/files#diff-4ce397ee2492fb1078425ea420483cf3b55645b5bbcee3139ae696ad07c6c1bc

Still need to polish/test everything but it consolidates the dbt-core logic into a single file. Can reconcile our two versions (I don't have the backwards compat).
