### ISSUE TITLE
[CT-901] [Epic] API-ification + CLI - Phase 1

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5527]
This Epic encompasses the work to create a new cli using the click CLI framework—and, in so doing, to start the process of turning `dbt-core` into a mature Python library with stable APIs & programmatic entry points.

Generally, the goal of this epic is **functional parity.** From the perspective of most end users, everything should work just the same as before. We are _not_ aiming to introduce new functionality into `dbt-core`—except what we get "for free" from the click framework, and by (re)designing & (finally) documenting our internal APIs—but we _are_ laying foundations that will enable us to add new capabilities, in https://github.com/dbt-labs/dbt-core/issues/6356 and subsequent initiatives.

### Get `dbt run` working
* [x] #5526 
* [x] #5528
* [x] #5529
* [x] #6327
* [x] #5530
* [x] #5531 
* [x] #5533
* [x] #5534
* [x] #6096
* [x] #5551

### Parity for all commands (ordered list based off usage)

* [x] #5550 - tracked by https://github.com/dbt-labs/dbt-core/issues/6357
* [x] #5553
* [x] #5545
* [x] #5547
* [x] #5556
* [x] #5554
* [x] #5542
* [x] #5555
* [x] #5549
* [x] #5541 
* [x] #5543
* [x] #5552
* [x] #5544
* [x] #5546 
* [x] #5548
* [x] #6757

### Parity for all params

* [x] #6577
* [x] #6585
* [x] #6579

**Comment by jtcohen6** [comment]
Closing this initiative as completed :)

**Comment by dbeatty10** [comment]
The dbt-core CLI uses `click` for v1.5+ and used `argparse` before that.
