### ISSUE TITLE
[CT-902] CLI (Top level API) is automatically documented

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5528]
**User Story:**
As a user I would like to have accurate and easy to read documentation for how to use `dbt-core` as a library.

**Acceptance Criteria:**
An auto-documentation product (probably Sphinx) is set up and documents the top-level api.  This runs as a GHA.

**Comment by leahwicz** [comment]
Let's make sure we account for accurate help text for commands which is referenced in this issue:
https://github.com/dbt-labs/dbt-core/issues/5528

**Comment by iknox-fa** [comment]
FYI-- I think there's been some confusion vis-a-vis the documentation.  This ticket is to generate sphinx docs as a reference, it doesn't refer to help text at all.

That said, after looking at #5319  we don't have to worry about it.  The behavior described there is the default  behavior for Click CLIs so we get that for "free"
