### ISSUE TITLE
[CT-906] Logging works with Click

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5530]
User Story:
As a user of dbt, I want logging to work as it does currently.

Acceptance Criteria:
 * Both the legacy and the new loggers are enabled in the root click group and propagate down to all click commands.
 
 
 TODO: Consider only migrating the new logger?  Depends on timing of RPC replacement.

**Comment by jtcohen6** [comment]
Resolved by https://github.com/dbt-labs/dbt-core/pull/6088
