### ISSUE TITLE
[CT-909] Adapter Management works with Click

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5533]
User Story:
As a user of dbt, adapters continue to work as they do currently

Acceptance Criteria:
* The logic found in the `adapter_management` context manager is moved to the root click group and propagates down to all subcommands

**Comment by iknox-fa** [comment]
I love the idea, but it ended up being only one line of code to move this to the Click world so the global state persists for now.

**Comment by jtcohen6** [comment]
@iknox-fa great solution to the scope of this initial ticket!
