### ISSUE TITLE
[CT-910] Tracking works with Click

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5534]
User story:
As dbtlabs we want to know how/when our software is being used.

Acceptance criteria:
* Tracking is enabled and runs as part of the root click group.

**Comment by ChenyuLInx** [comment]
To get started on the issue, find the [commit](https://github.com/dbt-labs/dbt-core/commit/fd778dceb5953619f1c32865205d3ab690757458) that did something similar, and see how to do the same for tracking

**Comment by jtcohen6** [comment]
Resolved by https://github.com/dbt-labs/dbt-core/pull/5972
