### ISSUE TITLE
[CT-913] High Level API - Deps

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5537]
Dependencies  object is available as part of the High Level API

**Comment by iknox-fa** [comment]
Per BLG 1/23/23 -- We're going to wait to further refine this until we have a better sense of how deps need to be used for Runtime.  @ChenyuLInx and or @MichelleArk can you update this when that decision gets made please? :)

**Comment by jtcohen6** [comment]
I'm going to close this for now, and kick it out of Phase 2 scope. We're going to keep discussing `deps` as part of our ongoing conversations about dbt-core as a library, scaling its operations, reducing/removing the dependency on the file system, ...
