### ISSUE TITLE
[CT-916] High Level API - Documentation

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5540]
High-level API has documentation

**Comment by iknox-fa** [comment]
Not estimated in BLG 11/28/22. Currently work will be done in other ticket (#6099)-- once that's complete we can use this ticket to put it + the automated docs into the CI/CD process

**Comment by leahwicz** [comment]
Makes sure objects in high level API are listed so they are auto picked up for documentation
