### ISSUE TITLE
[CT-926] `dbt parse` works in click

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5550]

**Comment by jtcohen6** [comment]
I know there's been some discussion about the utility of "parse" as a standalone command/task, given that it's really more like an implicit initialization step for other commands/tasks.

There's still utility in having this as a separate command, especially for analyzing parsing performance.

I can also imagine using it as a first-class way to return & programmatically inspect the manifest. I opened that proposal as a new issue: https://github.com/dbt-labs/dbt-core/issues/6547

**Comment by iknox-fa** [comment]
Per @stu-k this work will be handled by the manifest loading work (#6357)
Closing ticket
