### ISSUE TITLE
[CT-927] `dbt run` works in click

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5551]

**Comment by jtcohen6** [comment]
As Ian mentioned in https://github.com/dbt-labs/dbt-core/pull/5859#discussion_r981473802, we'll want to do another pass at ensuring flag/param parity. (Specifically, the `--favor-state` flag added in https://github.com/dbt-labs/dbt-core/pull/5859 will need to be added to the new CLI as well)

**Comment by jtcohen6** [comment]
Resolved by https://github.com/dbt-labs/dbt-core/pull/6396!
