### ISSUE TITLE
[CT-934] Add deprecation warning to direct use of `compiled_sql`

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#5558]
User used to be able to access `compiled_sql` from model in jinja space.

We renamed it `compiled_code` in our code base. Given this is a user space attribute,  we **will still supporting that use case**, but we would want to add a deprecation warning to the use of it so we can remove it in future releases..
[Related discussion](https://github.com/dbt-labs/dbt-core/pull/5499#discussion_r927542733)

**Comment by emmyoop** [comment]
Concerns:

- If `compiled_sql` is used multiple times, we ideally wouldn't want to issue a Deprecation Warning for every time it's used, that's too repetitive
- It's also unclear how we would do this since it's a dictionary lookup and not a method.

**Comment by emmyoop** [comment]
Possible solution is to replace the dictionary with a class that implements the dictionary functions.

Are we okay with issuing the deprecation warning multiple times since maybe you want to know all the places using the deprecated functionality?

**Comment by jtcohen6** [comment]
> Possible solution is to replace the dictionary with a class that implements the dictionary functions.

I sorta like this idea in general!

I'm guessing it would require a change to how `flat_graph` works, which currently just converts the manifest into lists + dicts.

The only code I could see being at risk here is people writing Jinja code that expects a node object pulled from `model` or off `graph.nodes` to be a dictionary. As long as we implement enough dunder methods to make the `node` object dict-like...?

> Are we okay with issuing the deprecation warning multiple times since maybe you want to know all the places using the deprecated functionality?

The way our `deprecations` module works today, it intentionally suppresses any deprecations beyond the first. I can imagine the iterative experience of run dbt, see warning pointing to file, update that file, run again, see same warning with new file, ... is not so fun.

The dream would be _one_ deprecation warning containing _all_ the call sites. I think that would be tricky to wire up, though.

The real benefit of using our `deprecations` module is that it sends anonymous tracking events, so we get a sense of how many people are still using deprecated stuff.

So I'd propose: **fire one "overall" deprecation warning _plus_ one warning per call site**
