### ISSUE TITLE
[CT-946] Support DBT projects that are sub-packages of repos (rather than their own repo) more natively in DBT Cloud.

### ISSUE THREAD

**Issue by hsenger-tiger** [dbt-labs/dbt-core#5566]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Today in DBT Cloud, many things seem built on the assumption that your GitHub repo **_is_** your DBT project... in other words, that the repo's root folder is the DBT project folder.

At my organization, our DBT project lives in a sub-package of mono repo that contains all of our code. This makes a few things difficult in DBT Cloud today, and I'm expecting we'll discover more:
- In the Cloud IDE, it loads our entire GitHub repo, rather than just the DBT package. This makes it slower to load the IDE, harder for folks to locate the relevant package / files to edit in the IDE, and makes it difficult for us to give folks access to our DBT code but not other, more sensitive packages in our repo.
- The out-of-the box DBT CI setup with GitHub that can be configured to run tests on PRs will trigger the job to run on any PR in the repo, even if it doesn't touch any DBT code. To work around this we need a custom GitHub action.
- Potentially more things...

My feature request is a way within DBT Cloud to specify a sub-directory of your GitHub repo that is your DBT project. DBT Cloud would then automatically do things like scope the IDE to that sub-directory, only run test jobs on PRs that change things in that sub-directory, etc.

Today, DBT is in a halfway state where it supports having DBT projects that aren't their own repos (it previously did not, IIRC) but things are more difficult when you work this way (like with the examples above). Since DBT allows you to have your project as a sub-package of a broader repo, it seems like it should support that pattern in a more first class way.

### Describe alternatives you've considered

Today, we work around the DBT CI issue with a custom GitHub action. This works, but was much more work. For the Cloud IDE issue, we do not have a workaround... we can't prevent it from loading all code in there.

### Who will this benefit?

This will benefit any organization using DBT Cloud whose DBT project is not its own repo.

**Comment by jeremyyeo** [comment]
> Today in DBT Cloud, many things seem built on the assumption that your GitHub repo is your DBT project... in other words, that the repo's root folder is the DBT project folder.

Not sure if this is a true statement - there's a "DBT PROJECT SUBDIRECTORY" field in the project settings page:

![image](https://user-images.githubusercontent.com/8496748/181384056-708f6ed3-22f1-4577-8c3c-df27e5602090.png)

My repo is https://github.com/jeremyyeo/dbt-sandcastles and my dbt project is inside `dbt/snowflake/`. dbt Cloud does today look into that subdirectory (and finds the `dbt_project.yml` file) in order to run jobs / develop in the IDE.

----

I think this is separate from asking for these other features (which aren't available in dbt Cloud):
1. Only load files from my subdirectory but nothing else.
2. For dbt Cloud Slim CI functionality, watch for the specific subdirectory to trigger PR runs - i.e. do not trigger PR runs if change is for files outside my subdirectory.

**Comment by hsenger-tiger** [comment]
I think we are saying the same thing. I know about that setting and am using it as well. I would like for it to be used more places (like the IDE, CI, etc). So my feature request is the same...

**Comment by lostmygithubaccount** [comment]
## sparse checkout to only fetch/download subdirectories in git repository

It is possible to only checkout a subdirectory with `git` -- this SO post is helpful: https://stackoverflow.com/questions/4114887/is-it-possible-to-do-a-sparse-checkout-without-checking-out-the-whole-repository

This works for `dbt-core`, only checking out (and downloading) the files in the root directory and `core/` directory on the final command:

```bash
git clone https://github.com/dbt-labs/dbt-core --no-checkout dbt-core --depth 1
cd dbt-core
git sparse-checkout init --cone
git sparse-checkout set core # only download the core directory (recursively)
git checkout # checks out the root and core/ files
```

## this issue

Thank you for opening this, @hsenger-tiger! it is very good and valuable feedback for both dbt Core and dbt Cloud. I think it relates to https://github.com/dbt-labs/dbt-core/discussions/5244, and you might want to contribute to the discussion there -- might be a bit orthogonal, but I suspect these `git` repo usage patterns with dbt projects all ties together.

However, for this issue specifically I'm inclined to close as not planned given there's no concrete action here in the `dbt-core` repository to take at this point. At this stage, I think further discussion and ideation on solutions is needed. 

CC'ing @jtcohen6 to undo if this is incorrect

(apologies for possible double-notification and unsureness in closing here, I'm a relatively new PM here at dbt Labs -- going to use that excuse for a long time!)

**Comment by hsenger-tiger** [comment]
Agreed that there's no action here in the dbt-core repository... this is a DBT Cloud issue. Is there a place where I can file issues for DBT Cloud to discuss this further?

**Comment by jtcohen6** [comment]
@hsenger-tiger Thanks for the thorough write-up! As it is, the `dbt-core` GitHub repo isn't the right place to submit or track product feedback for dbt Cloud, so we're going to keep this one closed — but this is definitely something on our minds.

@lostmygithubaccount I fully agree with pointing to the discussion around multi-project deployments! There's a valuable comment in there from Winnie, about a pattern that will appeal to many folks: split into multiple projects, but _keep those projects unified in one repo._

For a given developer, it will be important to load just the right files into the IDE for their development. But when they open a PR and trigger CI, that CI should really check for downstream implications of their changes in _all_ projects. At worst, the change was in an unrelated (non-dbt) part of the monorepo, the Slim CI check selects zero models to run, and it completes within a minute or two. A very small price to pay IMO.

This is the one that I think we have no power over:

> makes it difficult for us to give folks access to our DBT code but not other, more sensitive packages in our repo.

dbt leans on git providers for two important things: version control over source code (obvious) and _access control_ over that source code (less obvious). If you have sensitive code that someone shouldn't see, that code should live in a separate git repository, to which they don't have access. Our work around cross-project lineage wants to enable that developer to still _benefit from_ the outputs of the hidden project, to build their models on top of those models, to use it as a service.

**Comment by VICIWUOHA** [comment]
@jtcohen6,  Just stopping by here to know if there's any plan for the following line in view

> makes it difficult for us to give folks access to our DBT code but not other, more sensitive packages in our repo.

Or dbt advises to split into separate repos in this case. If yes this should be added to the docs note under [Project Subdirectories](https://docs.getdbt.com/docs/build/projects#project-subdirectories) pending future releases.
