### ISSUE TITLE
[CT-949] [Rows Affected] <Rows Affected>

### ISSUE THREAD

**Issue by mauricioobgo** [dbt-labs/dbt-core#5568]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Currently working with dbt core version 1.1 for snowflake adapter.

And only using incremental models, so realized for incremental models in the run_results the  "rows_affected" is always 1 so it does not show the total rows affected. It would be nice that shows the updates and rows inserted apart as well as the total amount of rows.

### Describe alternatives you've considered

Querying directly snowflake with a table that records the history of the queries in snowflake and joins by query_id.

### Who will this benefit?

Someone that would be looking analysis on the monitoring of the jobs and tries to see where the credits in this case snowflake are being consumed the most within snowflake.

### Are you interested in contributing this feature?

Yeah

**Comment by jtcohen6** [comment]
@mauricioobgo This is fixed in dbt-snowflake v1.2 (just released this week)! Check out: https://github.com/dbt-labs/dbt-snowflake/issues/147, https://github.com/dbt-labs/dbt-snowflake/pull/153
