### ISSUE TITLE
[CT-962] artifact test modifies the test data

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#5584]
When running the tests/functional/artifacts/test_previous_version_state.py::TestPreviousVersionState::test_compare_state_current test, the test data is modified. You have to git checkout the file tests/functional/artifacts/data/state/v7/manifest.json after running.

The test should be fixed to not modify the test data.

**Comment by jtcohen6** [comment]
I think we could just comment out this line:
https://github.com/dbt-labs/dbt-core/blob/7bd861a3514f70b64d5a6c642b4204b50d0d3f7e/tests/functional/artifacts/test_previous_version_state.py#L81

Then, we'd uncomment and use that method _only_ in PRs that bump the manifest version, where we need to create the new versioned manifest for the very first time.
