### ISSUE TITLE
[CT-972] [Feature] Block usage of `submit_python_job` outside of materialization logic

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#5596]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Throw a clear error during parsing(or later time in dbt run) if `adapter.submit_python_job` is being used in places other than the materialization logic.

## Relative information:
`adapter.submit_python_job` is currently being called in macro [statement](https://github.com/dbt-labs/dbt-core/blob/a7ff003d4f74763f126e77a0fc9c55e7a3311b3d/core/dbt/include/global_project/macros/etc/statement.sql#L15).

## Ideas:
- when we parse macro we can look up the macro tree and check that for all macro nodes that isn't `materialization` -> `statement`, we run regex on it to make sure `adapter.submit_python_job` is not there. This could be very costy
- somehow update how we provide context to macros and only provide `adapter.submit_python_job` in desired situation. This means we will have to remove it from the context sometime during jinjia compilation, this could be complex

## related links
- [where we parse all of the jinja macros](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/parser/macros.py#L69)
- [check for banned macro](https://github.com/dbt-labs/dbt-core/blob/0a0f5778aff7c780ec1b2ad7b2edc26aad6bffe9/core/dbt/parser/models.py#L354)

**Comment by ChenyuLInx** [comment]
@jtcohen6  either way feels not very easy, any idea?

**Comment by lostmygithubaccount** [comment]
@ChenyuLInx to spike

**Comment by ChenyuLInx** [comment]
Talked about this live, the manipulating `context` idea might be the better approach

**Comment by ChenyuLInx** [comment]
@jtcohen6  I think I found a path to modify the context so that we only allow the code(not saying I like it)
https://github.com/dbt-labs/dbt-core/blob/a1ee348a6f9af3ffc88ea8100c782adc94091f44/core/dbt/clients/jinja.py#L301-L321
The `trace_call` function here is called for each macro call and all the sub macro calls. So we can do something like: when a macro being called, we figure out whether it is materialization macro(from name), if yes, preserve that `submit_python_job` function somewhere, update it with a non_op/raise error, then if we run into the `statement` , we put it back. This way we only allow using the `submit_python_job` being used in `materialization` -> `statement`. still not a total block, but better.
We can't really only allow it in for only `statement with name main` since we call it in create tmp table sometime. otherwise would that would be the way to only allow 1 python job submission per model. We can do something even more funky to add language to results of `statement` macro and do some check afterwards.

So the situation now is: we can limit this, with some less than ideal method, and the more restriction we want to have, the less ideal the implementation is going to be. How far do we want to go?

**Comment by jtcohen6** [comment]
@ChenyuLInx Thanks for the investigation!

> This way we only allow using the `submit_python_job` being used in `materialization` -> `statement`. Still not a total block, but better.

I'd be happy to proceed with this approach — not a complete block, but a helpful guardrail — so long as it doesn't add too much cruft to this tightly wound part of the codebase. If it seems like a ton of work, we'd need to weigh it against other priorities during the beta period.

Tracking calls between macros feels like a thread we might want to pull on more in the future, e.g. to understand which macros are "dirty" / volatile and depend upon introspective queries for their results.
