### ISSUE TITLE
[CT-974] [SPIKE] support UDF in python models

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#5598]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As we added python models, one capacity to tackle is using functions declared in python directly in SQL using UDF. Multiple warehouse support this ([snowflake](https://docs.snowflake.com/en/developer-guide/snowpark/python/creating-udfs.html), [spark/Databricks](https://docs.databricks.com/spark/latest/spark-sql/udf-python.html)). As we are looking into this, does it also make sense to support SQL UDFs is also a question to answer.

This spike aims to figure out what it will take for dbt to support UDF as a first class dbt object similar to `ref` `source`, `config`. This would include figure out:
- how should we materialize the UDF
- how to keep track of UDFs defined in dbt
- how to access UDFs defined in dbt in downstream tasks
- how do we support this in other places: examples: catalog, model selection

## related links:
- [internal notion](https://www.notion.so/dbtlabs/Python-models-can-be-materialized-as-prediction-functions-UDFs-c7acd394abef4a758dfd91306f09bcc5)
- [a package](https://github.com/kristeligt-dagblad/dbt_ml/blob/v0.5.1/macros/materializations/model.sql) that already does something similar

## Outcome
Document/ticket for the UDF materialization in dbt-core and adapters

**Comment by lostmygithubaccount** [comment]
spike writeup (internal): https://www.notion.so/dbtlabs/UDF-SPIKE-fd3e6ce8c9c945a6b29ac9231bdbd1b3

**Comment by lostmygithubaccount** [comment]
closing as completed, moving to public discussion here: https://github.com/dbt-labs/dbt-core/discussions/5741 and further as needed. no clear work yet
