### ISSUE TITLE
[CT-977] [Feature] Ignore changes in profiles.yml when using partial parsing

### ISSUE THREAD

**Issue by AntonAiven** [dbt-labs/dbt-core#5600]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Differences in profiles.yml currently force a full re-parse even if the changes in profiles.yml would not warrant a new parse. For example changing the authentication method forces a full re-parse, even though authentication method will (should at least) not have an effect on the compiled manifest.

In our case we compile and deploy our dbt image from our CI/CD, where dbt is authentication is done through credentials, but then run the image from kubernetes in GKE where authentication method is oauth. Due to this we always need to re-parse and its slowing down our dbt runs.

### Describe alternatives you've considered

- moving the compilation of the manifest to the same environment where dbt is ran where we can have the same authentication method during compilation & run

**Comment by gshank** [comment]
Some of the information in the profile really does require that everything be reparsed, in particular the database and schema, which is embedded in many different places in the manifest. So we would have to switch to recognizing changes on an individual profile field basis, and the fields that could be allowed to change would be different for every adapter and every adapter connection method.

**Comment by gshank** [comment]
We have special handling for "secret" env vars which might be helpful. We don't match environment variables starting with 'DBT_SECRET_ENV_' when doing partial parsing.

**Comment by jtcohen6** [comment]
That's right — that's the workaround we've recommended for other folks in the past. If you _know_ that a specific profile field is likely to change frequently, and shouldn't have any effect on the parsed content of your project, you can set it to a secret env var:
```yml
# profiles.yml

profile-name:
  targets:
    prod:
      ...
      method: "{{ env_var('DBT_ENV_SECRET_AUTH_METHOD') }}"
```

dbt will not record the value of that secret env var, and so it will not detect any changes made to that profile configuration. For its purposes, the config remains unchanged from one parse to the next.

Does that seem like a reasonable workaround for your use case? To be honest, I haven't heard many instances of folks using different authentication mechanisms within the same dbt deployment.

---

@gshank For other reasons, we may eventually want the ability to map specific adapter/profile fields to specific resource types. I can imagine a future where one dbt project supports models running via different adapters, for example.

**Comment by AntonAiven** [comment]
@jtcohen6 interesting suggestion, I had not thought of that. I suppose that means that I would need to pass the keyfile parameter even if my authentication method is 'oauth' just so that the two profiles would look identical from dbts perspective? Wonder if that would cause dbt to get confused though.

**Comment by mishinma** [comment]
We have a similar issue, except we specify the warehouse through an environment variable: 
```
        dev:
            type: snowflake
            ... 
            warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE', 'xsmall_1') }}"
```
Using a different warehouse than the default also triggers a full re-parse. I realize that we could add more profiles for each warehouse as a workaround, but we would prefer not to.

**Comment by gshank** [comment]
Currently for the partial parsing state checks we look at a filehash of the entire contents of the profile.yml file. This is not ideal from a granularity standpoint and does mean that changing an unused profile target will still cause reparsing. We also check for the non-secret environment variables changing in the profile or dbt_project files,  the cli vars that are passed in, and the target that's passed in. So one of the only ways to avoid a reparse if any of those things change is to use DBT_SECRET_ENV_ env vars.

**Comment by AntonAiven** [comment]
@gshank I see, thanks for clarifying. My understanding was that it compares the profile in use, not the entire contents profile.yml file. Appreciate the help!
