### ISSUE TITLE
[CT-978] [SPIKE] Utilities for making python models more consistent across database

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#5601]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In this spike, we are investigating our options to make python model feels more consistent across database.

- We should investigating data frame abstractions that others have created and seem promising.
- We should evaluate whether simple solutions like adding imports automatically helps our user, example
  ```
  # on databricks / bigquery
  import pyspark.sql.types as T
  import pyspark.sql.functions as F
  
  # on snowflake
  import snowflake.snowpark.types as T
  import snowflake.snowpark.functions as F
  ```
Also please purpose other simple solutions if anything came up during researching dataframe abstractions.

## Outcome of the Spike
- A report about the data frame abstraction frameworks, including which ones we evaluated, why we evaluated them and their pros/cons
- Github issues for proposals like adding import if we decided to do it. Or a write up of why we don't want to do it.
- decision/ticket/more spike about python package management and code reuse

**Comment by lostmygithubaccount** [comment]
me to do some initial investigation, opinionating, and writing

**Comment by lostmygithubaccount** [comment]
see: https://dbtlabs.atlassian.net/browse/CT-611

**Comment by lostmygithubaccount** [comment]
https://dbtlabs.atlassian.net/browse/CT-609

**Comment by lostmygithubaccount** [comment]
closing as completed. covered here and linked discussions: https://github.com/dbt-labs/dbt-core/discussions/5742
