### ISSUE TITLE
[CT-1184] [Feature] Exposures: stricter validation for `name`, support custom `label`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5606]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently, it's possible to define an exposure like:
```yml
exposures:
  - name: My Cool Exposure
     ...
```

A surprising number of things will keep working:
```
$ dbt list --resource-type exposure
exposure:my_project.My Cool Exposure
```

The problem is that it's not _guaranteed_ to work everywhere. In particular, the `dbt-docs` site DAG selection does not handle exposure names with spaces (https://github.com/dbt-labs/dbt-core/issues/2970).

Rather than fix it everywhere, I'd prefer to adopt the same approach we'll be taking for metrics (https://github.com/dbt-labs/dbt-core/issues/5456):
- Have stricter parse-time validation on the `name` property of exposures: snake-case, alphanumeric characters, _maybe_ periods (since this is supported for models)
- Support a `label` property that can be used in external metadata, and contain whatever characters the heart desires

```yml
exposures:
  - name: my_cool_exposures
    label: My Cool Exposure
     ...
```

### Describe alternatives you've considered

- Continue to support whatever exposure names users want, and they only find out much later
- Add tons of strict validation _without_ supporting a custom human-friendly `label`

I don't like either very much!

### Who will this benefit?

- Users of exposures
- Programmatic integrations with exposures (e.g. https://hightouch.com/blog/introducing-dbt-exposures-for-hightouch/)

### Are you interested in contributing this feature?

Perhaps :)

**Comment by emmyoop** [comment]
Can we combine the name validation portion of this tickets with #5456 so we could use a single name validation function and then just have a separate ticket for adding labels?

**Comment by jtcohen6** [comment]
Handling the associated questions in the linked PR — removing the `Refinement` label for now
