### ISSUE TITLE
[CT-1006] [Bug] Source clobbering behaviour is unexpected

### ISSUE THREAD

**Issue by adamcunnington-mlg** [dbt-labs/dbt-core#5629]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am trying to clobber my source properties/configurations.

The properties/configurations for a single source in my code base are spread out as follows:
* models/staging/foo/sources.yml - Here I define a source and some properties but not tables:
```yaml
sources:
- name: FOO
  schema: MERGED_FOO
  loaded_at_field: UpdatedAt
```
* models/staging/foo/bar/model.yaml - Here I define a source table ONLY
```yaml
sources:
- name: FOO
  tables:
  - name: bar
```
* models/staging/foo/baz/model.yaml - Here I define another source table ONLY
```yaml
sources:
- name: FOO
  tables:
  - name: baz
```

## What Happens:
* The tables are successfully clobbered! I was surprised by this - it is cool that DBT knows to append these nested array items. I read in an old github issue that arrays are typically extended but this is not well documented - and I was pleasantly surprised that this fact seems to work for nested arrays too! In this case, the source FOO is already an array item and tables is an array item of that array item!
* Strangely, the schema & loaded_at_field seem to be ignored. They are not "clobbered". I need to manually define them. I would have imagined that it was more likely these would be successfully clobbered than the nested array item. My guess is that there is some special behaviour concerning sources[].tables[] because you expect that it is common for tables to be defined separately?

### Expected Behavior

As above.

### Steps To Reproduce

As above.

### Relevant log output

```shell
n/a
```

### Environment

```markdown
dbt: 1.2
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

n/a

**Comment by jtcohen6** [comment]
@adamcunnington-mlg Thanks for opening. If I understand your use case, it's to split up a source's definition across multiple `.yml` files, to avoid having it all grouped together in a single file?

To be clear, I would not say that the current behavior you're seeing is documented or guaranteed. If anything, I might want dbt to raise an explicit error if it sees the same `source` defined in multiple places. That's what it does for other resource types that have properties defined multiple times, and it's better than silently overwriting one set of properties with another, in a way that isn't predictable.

There have been some other discussions about the best way to DRY-ly define multiple sources, especially if those sources have many many tables: https://github.com/dbt-labs/dbt-core/issues/3397

And the ability to configure more common properties, across sources, from `dbt_project.yml`: https://github.com/dbt-labs/dbt-core/issues/3662

I do see this as a feature request, rather than a bug in current documented functionality — and I'm going to close it in favor of centralizing the conversation in one of those other issues.

**Comment by adamcunnington-mlg** [comment]
@jtcohen6 thanks for your response. Happy - glad in fact - to see this being looked at as part of a bigger topic.

One question for clarification though - you are surprised (or at least concede that it is not guaranteed) - but it is a common pattern to at least define **sources** in multiple places. Indeed, `sources` is an array and the [DBT structure guide](https://docs.getdbt.com/guides/best-practices/how-we-structure/1-guide-overview) recommends defining each source separately - so I assume that it is deliberate and guaranteed behaviour that the `sources` object itself is clobbered. Is it specifically the behaviour of nested objects - such as `tables` that you do not consider expected/guaranteed?

Would appreciate your comment on what the current behaviour (by design rather than accidental) is supposed to be - specifically with regards to how source properties/configurations are clobbered together.

**Comment by jtcohen6** [comment]
Sorry, yes! I should have been more clear. We very much expect different sources (entries in the `sources` array) to be defined in different files. We encourage the definition for all `tables` in one source (entry in the `sources` array) to be defined in the same file, however.

In the case of your example, the idea would be to define your source `FOO`, its properties (`schema` + `loaded_at_field`), and all associated `tables` in one single yaml file.

**Comment by adamcunnington-mlg** [comment]
@jtcohen6 Yep - I was doing this before but we have a very strict process for defining new data feeds - which entails defining templates for the staging layer - which should include staging sql/yaml (easy as 1 file per model) and sources - which is a problem because we are editing a file which undermines our isolated templates approach.

My (selfish motivation) is a quick win here - I don't want to open an entire can of worms on the overarching approach to clobbering configurations. I have discovered that sources[].tables **can** be clobbered, yet weirdly, the scalar attributes of sources[] cannot - can you imagine any way in which this is relaxed in the short term?

**Comment by jtcohen6** [comment]
Thanks for the extra context on the process - that makes sense! Out of curiosity - does a "new data feed" usually mean a new table in an existing source (same schema, same loader)? Or a totally new source?

I can't think of a quick win here, unfortunately. You could store the specific values of those scalar attributes in a var / env var, but you'd still need to redefine them (with the call to `"{{ var() }}"`) in each source yaml file.

**Comment by adamcunnington-mlg** [comment]
@jtcohen6 could be new table in existing source or brand new source - which is why i'm keen to just have 1 file per "table" and leave it to DBT to correctly clobber (although I would still need some vanilla `source.yml` where i define the bare attributes (source name, schema, loaded_at_field etc.).

I like your suggestion of var - I use this elsewhere but it hadn't occurred to me here to set as variables. It probably makes less sense for my schema as this changes per source (i could maybe create a macro for this although not sure if that macro would have access to the source context in order to be able to get the name - if not, i could pass it through explicitly but then I haven't achieved DRY) but for the loaded_at_field, it's a good point!

I'll stick with the workaround for now / minor duplication. But will watch the evolution of the source configuration discussion. Feels like a good idea to centralise a bunch of thinking. Thanks again.

**Comment by adamcunnington-mlg** [comment]
FYI, for completeness, I am successfully using a `sources` block PER **table**. I have to repeat any source-level properties (schema, loaded_at_field etc.) because they don't get clobbered but this is working. The small amount of repetition is worth it for me (especially as I use stubs to generate my YML files so I can control standards / minimise inconsistency) as I can define the source for a given staging model, together.

My actual use case dynamically generates YML files from templates (templates within templates I know; *gulp*) and so this is a big enabler for me.
