### ISSUE TITLE
[CT-1019] [Feature] Remove `.coverage.<username>` files in `make clean`

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#5633]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

`make clean` doesn't currently catch `.coverage.<username>` files so they clutter up the repo after a while.

**Comment by Aditya-Gupta1** [comment]
Hi team! I would like to work on this issue.
As per my understanding of this issue from the issue title, we have to remove the `@rm -f .coverage` command in the `Makefile`.

Let me know if my understanding is correct. Thanks.

**Comment by Goodkat** [comment]
I understood this in a different way: we have to add _.coverage.username_ files into the  ```Makefile``` as well to be caught by ```make clean```.
So we can add in the ```Makefile``` something like this: ```@rm -f .coverage."$USER"```
