### ISSUE TITLE
[CT-1023] [SPIKE] Use real `ref` in metric compilation logic

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5637]
### Current State
As @jtcohen6 raised in the above issue, there are problems with how the metrics package is currently handling model references. For the curious, this is because metrics can have nested dependencies that resolve as models 1+n nodes upstream. For example, if you have an expression metric that is built on a chain of 4 other metrics, we need to resolve the model(s) reference at the end of that chain. 

Right now we construct that information from `graph`. We can find the edges of the metric dependency, get the model name from the metric, construct that as a relation and then use it in our sql generation. This produces issues, however, when it comes to state deferral.

### Desired End State

As most of this will happen behind the scenes, there are few constraints when it comes to resolving this issue. The end goal is that the relationship would be correctly picked up and understood . @jtcohen6 raised a few ideas on how to resolve this:

- **Add dependencies at parse time**. Whenever dbt-core detects a call to metric(), it also tries to look up that metric's model dependencies, to record them in depends_on.nodes, too. This is potentially very slow, and I'm not even sure it's possible — the metrics haven't been parsed yet.
- **More complex check in the RuntimeRefResolver.** We adjust the logic in RuntimeRefResolver (code linked above) so it checks to ensure that either:
  - the ref'd model is in self.model.depends_on.nodes, OR
  - the ref'd model is upstream of this model, because it's upstream of a metric that is in self.model.depends_on.nodes / self.model.metrics. This feels sorta gross, and like it requires information that's not in scope here.
- **Resolve the ref for the metric, rather than the downstream model**. If there were a way to "compile" a metric so that it's the one resolving the ref, everything's golden. We'd need to store the resolved form of the metric's model reference ... in the graph somewhere ... or make it accessible as another Python method.

One thing I do want to call out is that we'd need this functionality to be able to support n+1 node depth. IE not just understanding `metric --> model` but also understanding `metric --> ... --> model`. 

Would love to hear thoughts about solutions from the languages team!

_Originally posted by @callum-mcdata in https://github.com/dbt-labs/dbt-core/issues/5525#issuecomment-1208425135_

**Comment by jtcohen6** [comment]
@emmyoop Happy to provide as much context and reproduction cases as I can here!

The big idea:
- At parse time, we know that metric Y depends on model X
- It's also possible for model Z to call metric Y, via the `metric()` function. In that case, there's an indirect dependency: `model_x --> metric_y --> model_z`. (It's also possible for metrics to build off other metrics, so this nesting can be arbitrarily deep.)
- At runtime, while "compiling" metric Y, we need the ability to template out some SQL that includes a resolved `ref` to model X: `select <metric_y_query_logic> from <model_x>`. This means including a runtime `ref` to model X, even though model Z _doesn't_ have model X in its `depends_on` — it just has metric Y.

Here's the catch: dbt raises an error if it finds itself templating a `ref` at runtime that it didn't know about at parse time. It throws up its hands and says: I'm afraid I might be running the DAG out of order!

https://github.com/dbt-labs/dbt-core/blob/739fb98d0ecaa6cb8dc3b802444ab4e83550a71c/core/dbt/context/providers.py#L495-L500

---

The way we've worked around this to date is by using a "fake ref," which just looks up model X in the `graph` and constructs its `Relation` object by hand: https://github.com/dbt-labs/dbt_metrics/blob/main/macros/graph_parsing/get_model_relation.sql

The problem is that this substitute logic doesn't take account of:
- `--defer` (original problem identified in #5525)
- User-defined custom `ref` logic (https://docs.getdbt.com/reference/dbt-jinja-functions/ref)
- ... other edge cases that I'm sure exist ...

---

In this case, we _know_ that we're not running the DAG out of order — `model_x --> metric_y --> model_z`, so `dbt run` must proceed in the order `model_x --> model_z` — so the error message is misguided. The question is, how can we _know_ that _programmatically_, within dbt? I provided a few ideas above.

This logic feels related to ephemeral models: they have their own `depends_on`, but they're also compiled in the context of the models "calling" them. The bad news is, the way we handle compilation for ephemeral models is _gross_. It's some of the gnarliest code in `dbt-core` today, and it doesn't even work in all cases (e.g. `run-operation`).

**Comment by emmyoop** [comment]
Since metrics are actually executed it makes sense to have this in parsing.  Ephemeral nodes are not as they are actually a cte that gets inserted into another node whicc is what runs.

Suggestion:
Add a new `process metric chains` method to create a new map with just the metrics and every model ref'd by a metric we care about.  This could be similar to what we do with the macro map.  This would be a new networkx graph.  The current map includes _all_ nodes and `depends_on` but that's way more than we need to be able top figure out the tree for metrics.  Every metric node that is not a leaf node (has a ref) take every ref in the tree above it and put the metric in the tree below it.

A good place to start is with just one ref deep to get everything working.  Then add more complex n+1 paths to get it working more fully.

Open Questions:
Will this be too slow?
Are there networkx functions that exist already to make this easier?

**Comment by leahwicz** [comment]
@jtcohen6 @callum-mcdata I plan to close this spike out with these findings and open a new issue to track the work. With there still being open questions and more digging here, we are going to prioritize other high priority metrics work for 1.3 and circle back to this one at a later date.
