### ISSUE TITLE
[CT-1037] [Bug] dbt doc block name not allowed to start with a number - docum depends on doc not found

### ISSUE THREAD

**Issue by SandervandenOord** [dbt-labs/dbt-core#5650]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

**Following error occurs, because doc block names are (apparently) not allowed to start with a number:** 

> Documentation for 'model.0_PRM_Analytics_TopRankedProducts_Export' depends on doc '0_PRM_Analytics_TopRankedProducts_Export'  which was not found

If I remove the number or just don't start with a number, it works.
I guess it has to do with Python not allowing variables to start with a number.
But the table starts with a number (which is allowed) and I would like to keep the docs name as close as possible to the table name.

Have the following setup:

**transforms.yml**
```
version: 2

models: 
  - name: 0_PRM_Analytics_TopRankedProducts_Export
    description: "{{ doc('1_PRM_Analytics_TopRankedProducts_Export') }}"
```

**docs.md**
```
{% docs 1_PRM_Analytics_TopRankedProducts_Export %}

This table contains the export of the best selling products per country:
- DE
- NL
- FR
- ES
- GB

{% enddocs %}
```

### Expected Behavior

Allow any kind of name for a docs block, so also name like `0_PRM_Analytics_TopRankedProducts_Export`, so names starting with a number. 

### Steps To Reproduce

Set up files as described above.
Run `dbt parse`
Error will occur.

### Environment

```markdown
- OS: Windows
- Python: 3.8.10
- dbt: 1.2.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by jtcohen6** [comment]
@SandervandenOord Thanks for opening! You're right, block names must start with a letter (or an underscore):

https://github.com/dbt-labs/dbt-core/blob/a3b018fd3b0c789c976e0e189788471edef8acb1/core/dbt/clients/_jinja_blocks.py#L53

We should raise a clearer validation message earlier, while parsing the doc block: "Name disallowed." This was raised in another issue (https://github.com/dbt-labs/dbt-core/issues/4352); I'm going to close this one in favor of that one to keep the tracking centralized.
