### ISSUE TITLE
[CT-1054] [Feature] Add predicates to default__get_incremental_merge_sql

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-core#5680]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

See https://github.com/dbt-labs/dbt-snowflake/issues/231

**Comment by jtcohen6** [comment]
Prior discussion in https://github.com/dbt-labs/dbt-core/issues/3293 + https://github.com/dbt-labs/dbt-snowflake/issues/231.

The only question is whether this issue's scope should include all our supported incremental strategies, on all our adapters, or just the `merge` strategy on `dbt-snowflake`. If it's the latter, we could resolve this one, and then open a new issue to track the follow-up work.
