### ISSUE TITLE
[CT-1058] [Bug] Custom schema name not supported in Python models

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#5685]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

More detail at [the community slack](https://getdbt.slack.com/archives/C03QUA7DWCW/p1660624585363649).

Python models have a different parsing path compared with SQL models, thus the logic in [ConfiguredParser](https://github.com/dbt-labs/dbt-core/blob/3aab9befcf57b63b6f449adf0e83285bf26ec407/core/dbt/parser/base.py#L93) are not carried over to python models. This would result in macros like `generate_schema_name` only being applied to SQL models.

### Expected Behavior

Custom schema/database/alias works the same across python/SQL model

### Steps To Reproduce

1. create a custom `generate_schema_name` macro that's different from original implementation
2. run a SQL model, see it the schema name got generated as expected
3. run a Python model, see that still the default schema got used.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
Actually surprised this is happening — I think the `generate_x_name` macros should be happening here for Python models:
https://github.com/dbt-labs/dbt-core/blob/758afd40710933188cf1a081925327e3091d838c/core/dbt/parser/models.py#L227

Which has the effect of calling:
https://github.com/dbt-labs/dbt-core/blob/758afd40710933188cf1a081925327e3091d838c/core/dbt/parser/base.py#L258-L263

Which hooks into:
https://github.com/dbt-labs/dbt-core/blob/758afd40710933188cf1a081925327e3091d838c/core/dbt/parser/base.py#L72-L90

(This is a _really_ thorny code path)

**Comment by ChenyuLInx** [comment]
@jtcohen6 Just caught your comment and I looked through the same code path and think this shouldn't be an issue.

I did some tests locally and actually things works as expected.

In my testing project that has a model called `python_model_1`, I added a macro in `macro/generate_name.sql`
``` jinja
{% macro generate_schema_name(custom_schema_name, node) -%}

    {%- if target.name == 'dev' and node.identifier == 'python_model_1' -%}
        my_schema
    {%- else -%}
        {{ node.schema }}
    {%- endif -%}

{%- endmacro %}
```
This would mean that `python_model_1` will be under schema `my_schema`. 

I then run the `dbt run -s python_model_1` with the latest `dbt-core` and found that my model was materialized under the correct schema.

I am going to just close this issue since we tested that it works as expected.
Feel free to reopen if there's any other reproduction case found.

**Comment by adamdharris** [comment]
Thanks @ChenyuLInx.  It is the UDF not created incorrect schema.  In our testing we have a model called `python_model_1.py`, and macro `generate_schema_name.sql`  

When we run `dbt-core` the model is under schema `db.my_schema.tables` , however the UDF created by model is not under `my_schema.procedures`.  The UDF is under `default_schema.procedures`

**Comment by ChenyuLInx** [comment]
@adamdharris Thanks for the additional information!

Can you share some sample code of how that UDF is created? If you are creating that UDF inside the python model, you can use `dbt.this.schema` within your function `def model(dbt, session):` and it should be `my_schema`

something like
```python
def model(dbt, session):
    create_UDF(schema=dbt.this.schema)
```

**Comment by adamdharris** [comment]
@ChenyuLInx we do not use `create_UDF()` function you did above just a simple python data wrangling function.  Note we are using snowflake db
```
def model(dbt, session):
    dbt.config(materialized="table")
    df = dbt.ref("majesco_policy_to_broadspire")
    ... 
    data wrangling code
    ...
    return df
```

**Comment by ChenyuLInx** [comment]
Ohhhh, are you referring to the UDF **dbt created** to actually run python model?

**Comment by adamdharris** [comment]
Correct

**Comment by adamdharris** [comment]
@ChenyuLInx I think worth testing custom database name at same time.  e.g we use this one in our workflow.
```
{% macro generate_database_name(custom_database_name=none, node=none) -%}

    {%- set default_database = target.database -%}

    {%- if target.name == 'uat' -%}
        {{ 'development' | trim }}
    {%- else -%}
        {{ default_database }}
    {%- endif -%}

{%- endmacro %}
```

**Comment by ChenyuLInx** [comment]
@adamdharris  Thanks for the suggestion!! That one is also in the fix.
