### ISSUE TITLE
[CT-1063] [Bug] Small typos in core/dbt/adapters/

### ISSUE THREAD

**Issue by yoiki** [dbt-labs/dbt-core#5690]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

https://github.com/dbt-labs/dbt-core/blob/7f8d9a7af976f640e376900773a0d793acf3a3ce/core/dbt/adapters/cache.py#L387

I think `relaton` is a typo.

https://github.com/dbt-labs/dbt-core/blob/7f8d9a7af976f640e376900773a0d793acf3a3ce/core/dbt/adapters/protocol.py#L91

Also, I believe `restirctiveness` is a typo.

### Expected Behavior

Fix typos:

* `relaton` to `relation`
*  `restirctiveness` to `restrictiveness`

### Steps To Reproduce

1. Change from `relaton` to `relation` https://github.com/dbt-labs/dbt-core/blob/7f8d9a7af976f640e376900773a0d793acf3a3ce/core/dbt/adapters/cache.py#L387
2. Change from `restirctiveness` to `restrictiveness` https://github.com/dbt-labs/dbt-core/blob/7f8d9a7af976f640e376900773a0d793acf3a3ce/core/dbt/adapters/protocol.py#L91

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
Thanks @yoiki, you're right! Would you be up to contribute the fixes? :)

**Comment by yoiki** [comment]
@jtcohen6 Thanks for the quick reply :) I'll try it!

**Comment by SUGARXUST** [comment]
Hey @jtcohen6 @yoiki is this issue still relevant? I would like to work on this.
