### ISSUE TITLE
[CT-1075] [Feature] Ability to collapse multiple nodes into one in the Lineage Graph on dbt docs

### ISSUE THREAD

**Issue by noel** [dbt-labs/dbt-core#5708]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As projects grow in size, the lineage graph becomes harder to use. 

Project teams tend to organize their projects in logical groupings like staging_stripe, etc.

It would be useful to have collapsable areas where multiple models could be displayed as one node. 
e.g. 1 node = 1 folder 
Users can then expand the single node to see the models contained within

### Describe alternatives you've considered

Using selectors within the Lineage Graph view

### Who will this benefit?

Docs users like business analysts and analytics engineers.

### Anything else?

https://getdbt.slack.com/archives/CKHBDNHA6/p1661355317116189

**Comment by sungchun12** [comment]
Note: This will require changes across this repo for setting configs and https://github.com/dbt-labs/dbt-docs for rendering the colors.

**Comment by sungchun12** [comment]
This feels similar to airflow's task groups: https://www.astronomer.io/guides/task-groups/

**Comment by noel** [comment]
Exactly

**Comment by lostmygithubaccount** [comment]
we called these "subgraphs" in ML DAGs

**Comment by lostmygithubaccount** [comment]
agreed this would be cool! it's not something the Core team is likely to prioritize for the foreseeable future, so moving into the "help wanted" ice bucket and out of triage
