### ISSUE TITLE
[CT-1082] [Bug] backup table name generate conflict

### ISSUE THREAD

**Issue by olivierdet** [dbt-labs/dbt-core#5710]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In Redshift, we hame some schemas that have a very long name
- `stg_back_office__declaration_containers__declarations__alerts`
- `stg_back_office__declaration_containers__declarations`

While executing DBT with 4 thread, those two models are executed in the same time. 
We see in the log that DBT try to rename the backup table into `stg_back_office__declaration_containers__declaratio__dbt_backup` for the two models (63 length long) which cause an error 
```Cache inconsistency detected: in rename, new key _ReferenceKey(database='******', schema='lkh_staging', identifier='stg_back_office__declaration_containers__declaratio__dbt_backup') already in cache:```

### Expected Behavior

I see that redshift is able to manage a 127 char length table name, we should be able to create such a backup table
Or 
There should be a mechanism to avoid the duplication of backup table name. 

### Steps To Reproduce

1. Create two models that have a long name
2. Those two models have to be generated as a table
3. Execute twice those 2 models in // twice ( the first time, backup table is not generated)

### Environment

```markdown
- OS:Ubuntu
- Python:3.9.6
- dbt:1.2
```

### Which database adapter are you using with dbt?

redshift

**Comment by jtcohen6** [comment]
@olivierdet Thanks for opening! I think this might be a duplicate of https://github.com/dbt-labs/dbt-core/issues/5586, and it should be resolved by fixes included in v1.2.1. Could you try upgrading to that latest patch version?
```
pip install --upgrade dbt-core==1.2.1 dbt-redshift==1.2.1
```
