### ISSUE TITLE
[CT-1087] Docker Compose Fails 

### ISSUE THREAD

**Issue by ahsanshah** [dbt-labs/dbt-core#5716]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The docker and docker compose builds fail. Can this be corrected or is there a workaround that works?  

### Expected Behavior

docker-compose "works" 

### Steps To Reproduce

docker-compose up -d

### Relevant log output

```shell
The build fails and there are multiple docker files in the repo. I have tried all of them.  If clarity can be provided on how to easily get this running in Docker it would be great.
```

### Environment

```markdown
- OS: Docker Image in Git Repo
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

base core fails

**Comment by jtcohen6** [comment]
Hey @ahsanshah, are you trying to:
- Install dbt via Docker? If so, check out the docs (https://docs.getdbt.com/dbt-cli/install/docker) and README (https://github.com/dbt-labs/dbt-core/blob/main/docker/README.md)
- Run integration tests against Postgres while developing `dbt-core` locally? That's the purpose of the `docker-compose.yml` file at the root of the repo:

https://github.com/dbt-labs/dbt-core/blob/main/docker-compose.yml#L1-L4
