### ISSUE TITLE
[CT-1088] packing a dbt project into kedro starter

### ISSUE THREAD

**Issue by Kurdzik** [dbt-labs/dbt-core#5718]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like to integrate dbt project into [kedro](https://github.com/kedro-org/kedro) starter.

Right now whenever i do that kedro project can't be created because both kedro and dbt make use of Jinja functions, 

Kedro uses cookiecutter under the hood to clone repo and then replace all existing jinja functions with custom data. 
It fails to generate a project because it also tries to replace jinja functions located inside dbt project 

And all solutions i've found on the internet about putting directory path to cookiecutter.json so that it will not take some folders into consideration, have failed

### Describe alternatives you've considered

Right now we have kedro starters on one repo and dbt projects on another.

Then use shell script located inside kedro project in order to pull dbt project and initiate it (create profiles.yml etc.) 

### Who will this benefit?

We are working on set of different starters to automate some repetitive tasks, given data in the same format.

Since making transformations directly on a database is much quicker than downloading data, transforming it and then uploading it again, we thought about using dbt for that purpose.

And then running kedro on newly created tables

### Are you interested in contributing this feature?

yes

**Comment by lostmygithubaccount** [comment]
@Kurdzik thanks for opening! do you have an idea of how to implement this feature? we'd be happy to help you along to contribute this, but it's likely not something we'll prioritize ourselves 

kedro also looks very interesting, I would be curious to learn more about how you & others are planning to use it with dbt!

**Comment by lostmygithubaccount** [comment]
assigning to myself to not lose track of this one, not sure what's going on with the bot and labels there

**Comment by Kurdzik** [comment]
i did some more testing and passing path to dbt project inside "_copy_without_render " argument to cookiecutter.json (part of a kedro project), will prevent cookiecutter from replacing jinja functions which are inside a dbt project. And thus will enable for dbt project to exist inside a kedro project, so problem solved :)

**Comment by lostmygithubaccount** [comment]
@Kurdzik great to hear! I'm curious to learn more if there are any pointers
