### ISSUE TITLE
[CT-1102] [Feature] .dbtignore

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5733]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

A `.dbtignore` file that uses `.gitignore` syntax (including pattern matching) to define files that should NOT be parsed/loaded by dbt.

Code for this would go in [`read_files`](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/parser/read_files.py)

After thinking about this for 5 minutes, I don't think there would be unintended consequences for partial parsing. If a file is ignored, it's as if it were deleted; if it's un-ignored, it's as if it were created for the first time.

### Describe alternatives you've considered

Regex support for `model-paths`, `test-paths`, etc. Gross

### Who will this benefit?

https://getdbt.slack.com/archives/C03QUA7DWCW/p1661873024869149

Concretely, people who have `.py` files in their dbt projects that are not actually Python models!

### Anything else?

Another use case where this has come up: Removing unneeded files in dbt packages (https://github.com/dbt-labs/dbt-core/issues/4837). Unfortunately, because of how dbt installs Hub packages, this would still require downloading all files and then deleting the "ignored" ones. See conversation in https://github.com/dbt-labs/hubcap/issues/95.

**Comment by lostmygithubaccount** [comment]
there is this: https://github.com/mherrmann/gitignore_parser I'm not sure we should be comfortable using directly but likely implement what we'd need 

obviously we could go find the source C code in here: https://github.com/git/git

from a quick look it didn't seem like the more standard GitPython package natively supports exactly this, but also probably useful: https://github.com/gitpython-developers/GitPython
