### ISSUE TITLE
[CT-1106] [Bug] Include py.typed in MANIFEST.in

### ISSUE THREAD

**Issue by panasenco** [dbt-labs/dbt-core#5737]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently when developing a dbt adapter and installing dbt-core with pip, I get errors like the following when trying to run mypy:
```
error: Skipping analyzing "dbt.contracts.connection": module is installed, but missing library stubs or py.typed marker
error: Skipping analyzing "dbt.events": module is installed, but missing library stubs or py.typed marker
```
This is because the file [py.typed](core/py.typed) is not included in the package uploaded to pypi.

### Expected Behavior

No mypy errors when checking types of packages that depend on dbt-core

### Steps To Reproduce

Create a file with the line `import dbt.events`
Run `mypy` on that file

### Environment

```markdown
- OS: Ubuntu
- Python: 3.10.4
- dbt: 1.1.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Writing a custom adapter for dbt

**Comment by dbeatty10** [comment]
Exciting that you are working on a custom database adapter @panasenco!

(Side note: you might find a bunch of helpful experts in the [#adapter-ecosystem](https://getdbt.slack.com/archives/C030A0UF5LM) Slack channel if you aren't already subscribed there.)

Thanks for submitting this issue and the relevant pull request 👍
