### ISSUE TITLE
[CT-1110] [Feature] Cross-database macro for `type_boolean()`

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt-core#5739]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

There are some great type helpers that have migrated from utils to core, but `type_boolean()` is a notable exception.  Speaking to @joellabes he indicated that y'all would likely be supportive of adding this one in.  I've got a basic implementation in https://github.com/brooklyn-data/dbt_artifacts/pull/188 that I'd be happy to contribute.

### Describe alternatives you've considered

Not doing it :)

### Who will this benefit?

Mostly folks maintaining packages.

### Are you interested in contributing this feature?

Certainly!

### Anything else?

Not officially included in the scope of this request, but something I'd love input on is a `type_json` and `type_array`, both of which I implemented in the above PR.  If y'all were open to this I _might_ expand the scope since I have versions ready to go.

**Comment by joellabes** [comment]
Additional context: another community member opened a PR for `type_boolean` in utils (https://github.com/dbt-labs/dbt-utils/pull/508) which I closed because I didn't want to add it just to remove it a couple of weeks later. I had intended for it to come along in the initial migration, but it turns out it missed the boat.

**Comment by dbeatty10** [comment]
@jaypeedevlin thanks for opening!

### Reaction
Any (or all) of the following are reasonable to include:
- `type_boolean`
- `type_array`
- `type_json`

@Fleid please feel free to weigh in or contradict me case you have both interest and insight on this!

> Side note: it would be awesome to consult the [most recent SQL standard](https://en.wikipedia.org/wiki/SQL#Standardization_history) to see which types we already have covered in some fashion and which we don't. Maybe [this](https://en.wikipedia.org/wiki/SQL#Predefined_data_types) list is an accurate reflection of SQL standard data types? Not that dbt-core _has_ to also define and support these, but would serve as a helpful guide.
>
> And maybe we'd create a pretty picture like this too:
> [<img alt="image" width="200" src="https://user-images.githubusercontent.com/44704949/187711738-449cf2ad-f17c-44d0-9e8c-49bd4bac6348.png" />](https://www.educative.io/answers/sql-data-types)


### Implementation hints
We'd expect any adapter to override these methods as-needed (including raising a not supported exception when appropriate). Not all databases will support all of these types, but they might be able to be "faked" in some fashion (see [SQL Server and booleans](https://github.com/dbt-labs/dbt-core/issues/4488)).

Each high-level default implementation will look like this:
https://github.com/dbt-labs/dbt-core/blob/3bfce2bac91a89a2886785e2fb31315e41830239/core/dbt/include/global_project/macros/utils/data_types.sql#L3-L9

Then the low-level default implementation will use [`translate_type `](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/base/column.py#L22-L24) and be like this:
https://github.com/dbt-labs/dbt-core/blob/1df713fee986741289568f553befdd4e38a51122/core/dbt/adapters/base/column.py#L11

For database adapters that need to override the default, it will look like this:
https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/column.py#L14
```python
        "STRING": "STRING",
```

### Testing hints
1. Implement testing in dbt-core:
    - https://github.com/dbt-labs/dbt-core/blob/1df713fee986741289568f553befdd4e38a51122/tests/adapter/dbt/tests/adapter/utils/data_types/test_type_string.py
1. Also implement the testing in every adapter (dbt-biquery, dbt-snowflake, dbt-redshift, and dbt-spark):
    - https://github.com/dbt-labs/dbt-bigquery/blob/defb70e5311ae79620b9caf7567e45b26ffd5f56/tests/functional/adapter/utils/test_data_types.py#L27-L28

**Comment by jpmmcneill** [comment]
@jaypeedevlin related to discussion over in https://github.com/dbt-labs/dbt-core/discussions/5778, I'm happy to take the `type_array` note that @dbeatty10 suggested.

This is one that's grinding on my gears for a lack of support.

**Comment by jaypeedevlin** [comment]
You're welcome to any/all of it, I have some (temporary) code [here](https://github.com/brooklyn-data/dbt_artifacts/blob/f57ed7a1022bb2ea92220b4d0e187f1e9dd25bf4/macros/type_helpers.sql) you're welcome to borrow, although as Doug points out there will need to be changes in each adapter.

**Comment by dbeatty10** [comment]
@jpmmcneill very timely of you: https://github.com/dbt-labs/dbt-core/issues/5520 is related to cross db macros for arrays.

Background:
https://github.com/dbt-labs/dbt-utils/pull/595 added some macros related to arrays to dbt-utils:
- `array_append`
- `array_concat`
- `array_construct`

I'm in progress of moving those into dbt-core (plus each adapter, like dbt-redshift, etc)

Would be glad for any feedback you're able to provide on those implementations!
- https://github.com/dbt-labs/dbt-core/pull/5823
- https://github.com/dbt-labs/dbt-redshift/pull/182
- https://github.com/dbt-labs/dbt-snowflake/pull/257
- https://github.com/dbt-labs/dbt-bigquery/pull/308
- https://github.com/dbt-labs/dbt-spark/pull/454

**Comment by jpmmcneill** [comment]
@dbeatty10 👋 I've spun up two PRs for type_boolean. I think the bigquery one is required because of how the inheritence is set up, but am not 100%.

I need to figure out how to get my dbt-core local dev setup for running the data type tests (they're complaining about a module error when I try to pytest them).

Depending on how fast local dev will get setup, type array / json might be possible before 1.3. type_boolean is definitely the most simple version of the three!

**Comment by dbeatty10** [comment]
Awesome @jpmmcneill !

Continuing the conversation with next steps over at https://github.com/dbt-labs/dbt-core/pull/5875
and https://github.com/dbt-labs/dbt-bigquery/pull/313.

**Comment by dbeatty10** [comment]
Resolved by https://github.com/dbt-labs/dbt-core/pull/5875, et al.

Thank you to @jpmmcneill, @jaypeedevlin, @Maayan-s and everyone else who participated in making this feature happen 🙌
