### ISSUE TITLE
[CT-1136] [Feature] dbt should load in `.jinja-sql` files

### ISSUE THREAD

**Issue by pepelovesvim** [dbt-labs/dbt-core#5785]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

`dbt` should load in `.jinja-sql` files so that for those of use who want to use independent language servers while still on the same vscode instance can do so.

### Describe alternatives you've considered

use two instances of vscode with different workspaces (lol no)

### Who will this benefit?

People who develop with editors and language servers

### Are you interested in contributing this feature?

yes, see below for pull request

### Anything else?

See pull request https://github.com/dbt-labs/dbt-core/pull/5784

Edit: just saw another issue regarding this

**Comment by jtcohen6** [comment]
I just reopened https://github.com/dbt-labs/dbt-core/issues/3484, can keep discussing there the appropriate file extension
