### ISSUE TITLE
[CT-1141] [Bug] docs - minor clarification/correction

### ISSUE THREAD

**Issue by andy-clapson** [dbt-labs/dbt-core#5791]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

very slightly misleading docs when new demo project set up, coming from here: https://github.com/dbt-labs/dbt-core/blob/7239ffe41dfe743d1117adab5cebe75740335e89/core/dbt/include/starter_project/dbt_project.yml

### Expected Behavior

That the examples are accurately described - it's just that the models are built as views, but docs say they are tables.

### Steps To Reproduce

init a new demo project, or just look at the /starter_project/dbt_project.yml

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
@andy-clapson thanks for opening.

Is there a link to a URL with the misleading docs that you could provide?

Depending on where those docs are located, we might move this issue over to the https://github.com/dbt-labs/docs.getdbt.com repo.

**Comment by andy-clapson** [comment]
for sure - it's this: https://github.com/dbt-labs/dbt-core/blob/7239ffe41dfe743d1117adab5cebe75740335e89/core/dbt/include/starter_project/dbt_project.yml

The guide on the demo project, just correcting a typo here. So I guess not *really* docs maybe? Sort of an in-between.

**Comment by dbeatty10** [comment]
👍 I see your pull request for this now too (#5684). Thanks for submitting proposed code changes!

Could you update your pull request description from `resolves #` to `resolves #5684` here?
<img width="422" alt="image" src="https://user-images.githubusercontent.com/44704949/189378570-4bb40009-92d6-4d5c-971d-f75ecb0d54a1.png">

When you do that update, GitHub will automatically link your pull request (#5684) to this issue (#5791). Then it will auto-close this issue when the PR is merged 💪 .
