### ISSUE TITLE
[CT-1142] [Bug] Getting ModuleNotFoundError: No module named 'pyspark'

### ISSUE THREAD

**Issue by lawrence-vo** [dbt-labs/dbt-core#5792]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

My `model.py` looks something like this:

```
import pyspark
import pyspark.sql.functions as F


def model(dbt, session):
    dbt.config(
        materialized='table',
        database='some_db',
        schema='some_schema')
    df = dbt.source('some_source', 'some_table')
    df = df.withColumn('AS_OF_DATE_', F.to_date(F.col('AS_OF_DATE_'))) # AS_OF_DATE_ was originally a string
    return df
```

Upon running `dbt run`, I get `ModuleNotFoundError: No module named 'pyspark'`

Is there something I am missing? I've been referencing the [docs](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/python-models).

When I import pyspark via the python console, it works without fail.

Thanks!

### Expected Behavior

Should run without fail.

### Steps To Reproduce

1. Create a simple model like the one described.
2. Run the python console and import pyspark to determine pyspark is installed
3. Run dbt run.

### Environment

```markdown
- OS: Windows 10
- Python: 3.9x
- dbt: 1.3beta
```

### Which database adapter are you using with dbt?

Snowflake

**Comment by lawrence-vo** [comment]
All,

I believe this has to do with what default version of Python is being used. I am using WSL2 and I have both 3.10 and 3.9. Is there a way to specify which python version dbt should use?

THanks!

**Comment by lawrence-vo** [comment]
using a virtual environment solved my issue.

**Comment by lawrence-vo** [comment]
Nevermind, I am using pyenv and am still getting the same error.

**Comment by lostmygithubaccount** [comment]
@lawrence-vo Snowflake uses Snowpark dataframes, not PySpark. they compile down into SQL running in Snowflake, with no Spark engine involved. you can find more here: https://docs.snowflake.com/en/developer-guide/snowpark/python/working-with-dataframes.html and API reference here: https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/index.html

**Comment by lostmygithubaccount** [comment]
also the list of packages here: https://repo.anaconda.com/pkgs/snowflake/

I'm going to close this issue, please directly "@" me in it for further questions or feel free to open a new issue/discussion (closed issues are a bit harder to keep track of). and thanks for trying out the beta! definitely curious what you're intending to use this for

**Comment by lawrence-vo** [comment]
@lostmygithubaccount ,

Thanks for the resources! Is there a way to specify that I rather use PySpark than Snowspark? PySpark has 3.9 Python support and a more active community. I also would like to stay warehouse agnostic. 

Thanks!
