### ISSUE TITLE
[CT-1147] Timeline for release of v1.3

### ISSUE THREAD

**Issue by kosteev** [dbt-labs/dbt-core#5806]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Google Cloud Composer is affected by https://github.com/dbt-labs/dbt-core/issues/4748 - Airflow 2.3+ is not compatible with dbt-core.

There is a bump in constraints for Jinja2 in dbt-core==1.3.0b2 which resolves the issue. Can you, please, share the timeline for the release of dbt-core==1.3.0?

### Expected Behavior

---

### Steps To Reproduce

---

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
Hey @kosteev, we're planning to release v1.3.0 (final) in October.

The calendar of planned dbt Core releases is documented here: https://docs.getdbt.com/docs/core-versions

And in our recent update to the dbt Core roadmap: https://github.com/dbt-labs/dbt-core/blob/main/docs/roadmap/2022-08-back-for-more.md

To that end, we're planning to cut the first release candidate of v1.3.0 in two weeks, ~September 28. That's the date we have on the [v1.3 milestone](https://github.com/dbt-labs/dbt-core/milestone/77).
