### ISSUE TITLE
[CT-1150] Include `flat_graph` in `manifest.deepcopy()`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5809]
Why isn't `flat_graph` included in `manifest.deepcopy()`? Probably not for any reason in particular.

The original implementation of `manifest.deepcopy()` was the early days of the dbt-RPC server (https://github.com/dbt-labs/dbt-core/commit/1a0df174c9f252d0f93e03dbf4ef5005b2429072), and that's still the only place we really call it. The idea is to support dynamically adding new temporary nodes (arbitrary SQL compilation/execution) that might need to [`add_refs`](https://github.com/dbt-labs/dbt-rpc/blob/b45d09e487fedb1b12fd3214081e593d52332bb4/dbt_rpc/task/sql_commands.py#L30-L50) in the manifest — or rather, a full copy of the manifest.

This does mean, however, that any time you want to deepcopy of a manifest, and you want that copied manifest to support introspection of the `graph` variable in the Jinja context, you actually need an extra step:
```python
from dbt.contracts.graph.manifest import Manifest

manifest = Manifest(...)

# should just be this, right?
copy_of_manifest = manifest.deepcopy()

# still missing something
copy_of_manifest.build_flat_graph()
# now you're good to go
```

The fix here might be as simple as taking this:
https://github.com/dbt-labs/dbt-core/blob/b26280d1cf1af1c715753f73eb3b46f6eaa717f5/core/dbt/contracts/graph/manifest.py#L781-L794
And adding in:
```python
import copy
...

    def deepcopy(self):
        return Manifest(
            ...
            flat_graph={k: copy.deepcopy(v) for k, v in self.flat_graph.items()},
            ...
        )
```

**Comment by leahwicz** [comment]
@emmyoop maybe this is something small you could pick up with extra bandwidth
