### ISSUE TITLE
[CT-1151] [Feature] add missing test for escape single quotes

### ISSUE THREAD

**Issue by sdebruyn** [dbt-labs/dbt-core#5811]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

A tests was missing in the adapter tests https://github.com/dbt-labs/dbt-core/pull/5810

**Comment by dbeatty10** [comment]
Thanks for opening a pull request for this @sdebruyn 👍

**Comment by dbeatty10** [comment]
Closing this due to the rationale [here](https://github.com/dbt-labs/dbt-core/pull/5810#issuecomment-1243916886). If I missed something crucial, we can revisit this.
