### ISSUE TITLE
[CT-1152] [Bug] dead anchor link in PR template

### ISSUE THREAD

**Issue by sdebruyn** [dbt-labs/dbt-core#5813]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

link to adding a changelog entry does not go to anchor directly

### Expected Behavior

link works

### Steps To Reproduce

click link

### Additional Context

PR incoming in a minute

**Comment by jtcohen6** [comment]
Thanks @sdebruyn :)
