### ISSUE TITLE
[CT-1154] [Bug] Adapter test bool_or contains reserved keyword

### ISSUE THREAD

**Issue by sdebruyn** [dbt-labs/dbt-core#5817]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The test fixture for the adapter test bool_or contains the reserved keyword `key` which might fail in some adapters (as it does in the one for SQL Server)

### Expected Behavior

Tests should not use commonly reserved keywords for their column names

### Steps To Reproduce

Implement the bool_or test in your adapter in a database engine where `key` is reserved (e.g. SQL Server)

### Relevant log output

```shell
('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'key'. (156) (SQLMoreResults)")
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

dbt-sqlserver

**Comment by dbeatty10** [comment]
Thanks for reporting this @sdebruyn!

Which test(s) are failing on `key` being a reserved keyword?

Is it [fixture_bool_or](https://github.com/dbt-labs/dbt-core/blob/1db48b3cca25912977a753b54d1b69729ccb245b/tests/adapter/dbt/tests/adapter/utils/fixture_bool_or.py)? Or something else?

**Comment by sdebruyn** [comment]
Hi @dbeatty10 that's indeed the one. I fixed that in the linked PR.
