### ISSUE TITLE
[CT-1169] [Feature] dbt-core compatibility with Airflow 2.3+

### ISSUE THREAD

**Issue by erdos2n** [dbt-labs/dbt-core#5832]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When adding dbt-core to my `requirements.txt` file, I am unable to run Airflow. 

I am currently attempting to use `dbt-core==1.0.3` as suggested in a previous issue, as well as, `dbt-core==1.0.5`. I use Astronomer to build Airflow but the conflict is with `Jinja` and `click` at the moment.

### Describe alternatives you've considered

```python
dbt-core==1.0.3
dbt-core==1.0.5
```

### Who will this benefit?

Airflow and dbt-core users alike

### Are you interested in contributing this feature?

No

**Comment by dbeatty10** [comment]
Thanks for reaching out @erdos2n

Could you share the commands (or method) you are using to install Astronomer/Airflow?

Could you also share the log output where you are seeing the version conflicts with Jinja and click?
