### ISSUE TITLE
[CT-1171] Blueprint json artifacts to persist contracts' state and unify manifests and catalogs across projects

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/dbt-core#5835]
**Success Criteria:**
- Links to existing files in dbt-core that need to be updated
- Net new files in dbt-core and why it needs new files
- Potential "gotcha" implementations based on the above(think: if we update this file here, we have to update 100 files downstream)
- pseudo-code snippets on initial approach for the above to make this functionality work

**Comment by matt-winkler** [comment]
```
"nodes": {
        "model.upstream_project.my_first_dbt_model": {
            "resource_type": "model",
            "has_downstream_dependencies": true,
            ...
        },
        "model.downstream_project.my_second_dbt_model": {
            "resource_type": "model",
            "depends_on": {
                "macros": [],
                "nodes": ["model.upstream_project.my_first_dbt_model"]
            },
```

**Comment by matt-winkler** [comment]
- https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/contracts/graph/manifest.py
- https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/parser/manifest.py

**Comment by matt-winkler** [comment]
Envisioned process:  
* contract configs set in the `dbt_project.yml`, `schema.yml` or `model.sql` files.
* As part of project parsing in an upstream project, dbt identifies when there are node contracts in place and if so, generates a `contracts.json` which is written to `/target`.

**Comment by sungchun12** [comment]
Great update!

I'm going to use your example json outputs as sketches for the json my contract yml configs will output!

**Comment by sungchun12** [comment]
@matt-winkler I used your json schemas as a starting point and built this template: https://github.com/dbt-labs/dbt-core/blob/120e4d3edceaa5bed9180546140e4a49a9aa44c5/tests/functional/dbt_contracts/contracts.json

`contracts.json` will consolidate a subset of the `manifest.json, catalog.json, run_results.json, sources.json` files and then merge that with the consumer's `manifest.json, catalog.json`(`run_results.json, sources.json` files are for validating contract requirements only)

**Pros**:
- A single file that consolidates the relevant details
- Removes the need to point to a project directory and/or git repo url as the `contracts.json` contains all the relevant metadata, code, results

**Cons**:
- This file can easily become overloaded and gigantic
- Still need to figure out how to merge elegantly with a downstream(consumer) project's `manifest.json, catalog.json`, but that will happen regardless of the approach
