### ISSUE TITLE
[CT-1177] [Spike] Auto-generate docs for dbt-Jinja rendering contexts

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5837]
Today, the docs on dbt's Jinja "extensions" (context methods) are hand-crafted by in-house artisans: https://docs.getdbt.com/reference/dbt-jinja-functions

This risks all sorts of human-error mistakes (see https://github.com/dbt-labs/docs.getdbt.com/pull/1454, among many others), not to mention the constant risk of staleness.

Most of these methods are defined today in our contexts ([`BaseContext`](https://github.com/dbt-labs/dbt-core/blob/7da7c2d69288791cdabe3b6f3fe588b3c1e029ce/core/dbt/context/base.py#L179), [`ProviderContext`](https://github.com/dbt-labs/dbt-core/blob/7da7c2d69288791cdabe3b6f3fe588b3c1e029ce/core/dbt/context/providers.py#L678)). Many already have solid docstrings. When I've been the one creating docs, I've often copy-pasted those docstrings into markdown files.

Could we auto-generate docs? Perhaps using a mechanism similar to the one we propose for https://github.com/dbt-labs/dbt-core/issues/5528?

To be clear, I have _no_ idea if this is possible in the current state of our code — that's the goal of the spike. In the meantime, it's worth writing the idea somewhere :)

Goals:
- Avoid copy-paste toil, prevent staleness
- Handle files with specialized rendering contexts (current examples: https://docs.getdbt.com/reference/dbt-jinja-functions/dbt-project-yml-context, https://docs.getdbt.com/reference/dbt-jinja-functions/profiles-yml-context, https://docs.getdbt.com/reference/dbt-jinja-functions/on-run-end-context)

**Comment by leahwicz** [comment]
We might be able to take advantage of the Sphinx implementation we are doing for the API-fication and get to use that here as well
