### ISSUE TITLE
[CT-1192] [Feature] Deprecate 1.3 backwards compatibility for old metric definition

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-core#5849]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Version 1.3 of dbt-core introduced backwards compatibility for the old metric spec. In our error message, we state that this compatibility will be removed in 1.4. This issue is being created to track that for the future 1.4 release. 

Relevant PR for code to remove: https://github.com/dbt-labs/dbt-core/pull/5825

### Are you interested in contributing this feature?

Yes!

**Comment by leahwicz** [comment]
@callum-mcdata I assigned this to you since you said you were interested in doing this. If not, let me know and I can assign and prioritize having this happen in 1.4

**Comment by callum-mcdata** [comment]
@leahwicz happy to take this on for 1.4! Just to level set, I'd probably work on this after Coalesce - does that align with Core's timeline for the early 1.4 PR's?

**Comment by jtcohen6** [comment]
After discussion with @callum-mcdata, let's pause on removing the deprecation warning & backwards compatibility for now, given greater changes that we're envisioning for the metrics spec in the next few versions (e.g. #6379).

In the meantime, let's just update the deprecation warning to replace "in v1.4" with "in a future version":

https://github.com/dbt-labs/dbt-core/blob/fafd5edbda2e94e6452bf2487fffee6e267736b1/core/dbt/events/types.py#L395
