### ISSUE TITLE
[CT-1205] [Feature] default `dbt-sql` and `dbt-py` models to different colors in the DAG viz

### ISSUE THREAD

**Issue by lostmygithubaccount** [dbt-labs/dbt-core#5880]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

it'd be nice to default colors for `.py` and `.sql` models to different colors in the dbt DAG

### Describe alternatives you've considered

you can provide those colors yourself https://github.com/dbt-labs/dbt-docs/pull/281

### Who will this benefit?

people with SQL and Python models who want to easily differentiate without manually coloring nodes

### Are you interested in contributing this feature?

~probably not~ maaayyyyyybbbbbeeeeeeee

**Comment by jtcohen6** [comment]
> probably not

you sure? :)

This would be (I think) pretty simple to do over in the `dbt-docs` codebase. A new selector like [one of these](https://github.com/dbt-labs/dbt-docs/blob/807e2ac9063346c9721c694ecad6a8de9db474de/src/app/services/graph.service.js#L177-L225). Just need to come up with a hex code we like...

> They have pale tan, yellow-brown, or gray bodies with large, reddish blotches outlined in white or yellow, according to the Smithsonian National Zoological Park.

**Comment by paulbenschmidt** [comment]
I've dug into this, and I think the change should be pretty simple, if I'm understanding what's going on. (Though this is my first time contributing to an open-source project, so take that with a grain of salt.)

Will be pushing a branch shortly...
