### ISSUE TITLE
[CT-1233] [Bug] Race condition in lib.py causes concurrent API calls to fail

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-core#5919]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The `lib.py` file in Core contains logic to "reset adapters" in the process of generating a RuntimeConfig object. While this logic is appropriate for single-threaded usage of dbt Core, we've seen that concurrent api calls to this method can result in race conditions:

https://github.com/dbt-labs/dbt-core/blob/56783446dbc765d93c43afad2b763302f034ef6b/core/dbt/lib.py#L27-L32

The `reset_adapters` call will clear out the set of adapters registered in the dbt Core adapter factory. If a concurrent api call accesses adapters (eg. to compile sql, or run dbt, or similar) before the `register_adapters` call is complete, there's a chance it will fail with a `KeyError` eg. [here](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/factory.py#L101) because the adapter dictionary was cleared in another thread.

### Expected Behavior

The `get_dbt_config` should not mutate global state to generate a RuntimeConfig.

### Steps To Reproduce

Here's a minimal repro case:

```python
import dbt.lib
import threading
import time
import random
import dbt.adapters.factory

PROJECT_PATH = "/Users/drew/dev/internal-analytics"


def repro_func(thread_no):
    time.sleep(random.random())

    try:
        # Simulate concurrent use of adapters
        config = dbt.lib.get_dbt_config(PROJECT_PATH)
        adapter = dbt.adapters.factory.get_adapter_by_type(config.credentials.type)
        adapter.acquire_connection()
        adapter.execute('select 1 as id')

        print(f"Thread {thread_no} OK")
    except KeyError:
        print("ERROR: KeyError")


threads = []
for i in range(25):
    thread = threading.Thread(target=repro_func, args=(i,))
    thread.start()
    threads.append(thread)

for thread in threads:
    thread.join()
```

<img width="1552" alt="Screen Shot 2022-09-23 at 9 51 27 AM" src="https://user-images.githubusercontent.com/1541139/191976057-18a94daf-4330-4a0a-b9c0-5b5298c57570.png">

### Environment

```markdown
- OS: macOS
- Python: 3.9.14
- dbt: 1.2.1
```

### Which database adapter are you using with dbt?

postgres, redshift, snowflake, bigquery, spark

### Additional Context

I am interested in submitting a patch for this issue

**Comment by jtcohen6** [comment]
Thanks for opening @drewbanin!

@iknox-fa and I have been chatting about this a bit, most recently over in #5533. De-globalizing adapters, while not in the immediate scope of API-ification, is something I'd like to tackle in the next few months. I think we can disambiguate between:
- "plugin": a driver, appropriate to register globally at application startup, and then treat as library code for use in specific invocations
- "adapter": an object initialized using plugin (library) code, using config/credentials that might be specific to one invocation — and should not be treated as a singleton registered/cleared globally
