### ISSUE TITLE
[CT-1235] [Bug] env_var() does not work when setting schema name in dbt cloud beta UI

### ISSUE THREAD

**Issue by Nazaniiin** [dbt-labs/dbt-core#5924]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

**DBT-Cloud Beta:**
----------------------
Environment variables work fine in setting connection configurations, username, and password. However, it errors on the syntax when used for defining `Schema`

<img width="803" alt="image" src="https://user-images.githubusercontent.com/8875071/192039336-0d8553c0-5975-40fd-860f-a0522d8a9a67.png">

### Expected Behavior

**DBT-Cloud Classic:**
-------------------------

Schema can take in an `env_var()` as value, like how it does in the classic view:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/8875071/192042529-9ad74f6e-8dde-4ce5-b0fe-f3566127cd4d.png">

### Steps To Reproduce

- Change to DBT-Cloud Beta UI (toggle on top of the page)
- Go to Profile Settings > Credentials
- Select a project for which you want to enter credentials
- Put some environment variable like `{{env_var('DBT_SCHEMA')}}` for schema (You can also put in env variables for other configs like database connection, username and password. They work as expected)
- Try to save and you should see the same error attached in the screenshot

### Environment

```markdown
- OS: Mac OS
- dbt: DBT-Cloud v1.2
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jeremyhutt11** [comment]
Hi @Nazaniiin! Thanks for reporting this issue. This seems to be a legitimate bug in the new dbt Cloud UI that we will address. If you see more issues in dbt Cloud, please don't hesitate to reach out to our customer support team! You can do by selecting the question mark icon in the top right and then click on the "Chat with us" option.

<img width="406" alt="Screen Shot 2022-09-26 at 1 13 07 PM" src="https://user-images.githubusercontent.com/15676167/192370962-63cb6db5-295a-4cd1-96d6-71f2987acfe7.png">

**Comment by lostmygithubaccount** [comment]
thanks @jeremyhutt11! @Nazaniiin going to close this out as there's no action in this repository

**Comment by patkearns10** [comment]
In case anyone stumbles upon this in the future, this was closed because it is a dbt Cloud bug, not dbt-core. 
This was fixed long ago.
![image](https://github.com/dbt-labs/dbt-core/assets/30663534/3ae11afd-ce67-4108-badf-2a95dfef4d89)
