### ISSUE TITLE
[CT-1239] [Feature] Allow partitions in external tables to be supplied as a list

### ISSUE THREAD

**Issue by pgoslatara** [dbt-labs/dbt-core#5929]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Partitions in external tables can be supplied as a list (currently a name and data type are the minimum requirements).

### Describe alternatives you've considered

Supplying a list of partitions with `name` and `data_type` values is superfluous, especially the `data_type` as this is not used. While specifying the partitions in this way works, it is not a great user experiences.

### Who will this benefit?

Users of the `dbt-external-tables` package that have a Spark/Databricks connection.

### Are you interested in contributing this feature?

Yes.

### Anything else?

Background can be found in this [comment](https://github.com/dbt-labs/dbt-external-tables/pull/161#issuecomment-1255940060) on a PR for `dbt-external-tables`.

**Comment by lostmygithubaccount** [comment]
hi @pgoslatara, thanks for opening this issue and the corresponding PR to fix! we'll get that reviewed and get back to you with any requested changes through the PR
