### ISSUE TITLE
[CT-1249] [Bug] dbt build runs tests for table materialized models with config.materialized:view selection

### ISSUE THREAD

**Issue by deugene** [dbt-labs/dbt-core#5939]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

This dbt command:
```
dbt build --select 100+tag:hourly,config.materialized:view 
```
runs tests for a model with config:
```
{{ config(materialized='table', tags=['hourly']) }}
```

### Expected Behavior

dbt build --select 100+tag:hourly,config.materialized:view runs tests only for view materialized models

### Steps To Reproduce

run 
```
dbt build --select 100+tag:hourly,config.materialized:view
```
for a project with tests for both materialized view and table models

### Relevant log output

```shell
[0m11:10:44 Running with dbt=1.2.1
[0m11:10:45 Found 175 models, 236 tests, 3 snapshots, 0 analyses, 769 macros, 0 operations, 0 seed files, 337 sources, 0 exposures, 0 metrics
[0m11:10:45
[0m11:10:46 Concurrency: 2 threads (target='prod')
[0m11:10:46
...
[0m11:17:25 52 of 175 START test relationships_company_marketing_app_hospital_acquisition_kanban_flow_columnId__id__ref_parsed_company_app_portfolio_boards_columns_ [RUN]
[0m11:17:25 52 of 175 ERROR relationships_company_marketing_app_hospital_acquisition_kanban_flow_columnId__id__ref_parsed_company_app_portfolio_boards_columns_ [[31mERROR[0m in 0.23s]
[0m11:17:25 53 of 175 START test relationships_company_marketing_app_hospital_acquisition_kanban_flow_projectId__id__ref_parsed_company_app_projects_ [RUN]
[0m11:17:25 53 of 175 ERROR relationships_company_marketing_app_hospital_acquisition_kanban_flow_projectId__id__ref_parsed_company_app_projects_ [[31mERROR[0m in 0.22s]
...
[0m11:17:42

[0m11:17:42 Finished running 54 view models, 121 tests in 0 hours 6 minutes and 57.57 seconds (417.57s).

[0m11:17:43

[0m11:17:43 [31mCompleted with 2 errors and 0 warnings:[0m

[0m11:17:43

[0m11:17:43 [33mRuntime Error in test relationships_company_marketing_app_hospital_acquisition_kanban_flow_columnId__id__ref_parsed_company_app_portfolio_boards_columns_ (models/mart/marketing/company_marketing_app_hospital_acquisition_kanban_flow.yml)[0m

[0m11:17:43 Table or view not found: mart.company_marketing_app_hospital_acquisition_kanban_flow; line 13 pos 9

[0m11:17:43

[0m11:17:43 [33mRuntime Error in test relationships_company_marketing_app_hospital_acquisition_kanban_flow_projectId__id__ref_parsed_company_app_projects_ (models/mart/marketing/company_marketing_app_hospital_acquisition_kanban_flow.yml)[0m

[0m11:17:43 Table or view not found: mart.company_marketing_app_hospital_acquisition_kanban_flow; line 13 pos 9m
```

### Environment

```markdown
- OS: Debian Bullseye
- Python: 3.8
- dbt: 1.2.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

databricks

**Comment by jtcohen6** [comment]
Hey @deugene - thanks for opening, and sorry for the delay getting back to you!

In this case, `test relationships_` says it all. For tests with multiple "parents" (i.e. the test depends on and selects from multiple models), the default behavior is that dbt will _eagerly_ select those tests to run, even if only one parent is selected. In this case, I'm guessing that the tests are for the relationship between a view-materialized model and a table-materialized model. Because you're selecting all views, they get picked up.

This is configurable behavior. Instructions on how to switch it up, and a more detailed explanation: https://docs.getdbt.com/reference/node-selection/test-selection-examples#indirect-selection

I'm going to close this issue in the meantime
