### ISSUE TITLE
[CT-1255] Are we thinking too hard about this and we should simply evolve the functionality of `dbt exposures`?

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/dbt-core#5944]
**Success Criteria:**

- [ ] Links to existing files in dbt-core that need to be updated
- [ ] Net new files in dbt-core and why it needs new files
- [ ] Potential "gotcha" implementations based on the above(think: if we update this file here, we have to update 100 files downstream)
- [ ] pseudo-code snippets on initial approach for the above to make this functionality work
- [ ] Loom demo video

**Comment by matt-winkler** [comment]
@sungchun12 I added a new [branch](https://github.com/dbt-labs/dbt-core/tree/ct-1255/producer-contracts-via-exposures) for this.

In terms of generating useful outputs at compile time in the `manifest.json`, this kind of works. 

Here is my exposure definition:

**Comment by sungchun12** [comment]
Thanks Matt! I'll figure out a way to unite this with the work Doug and I are doing here: #5945
