### ISSUE TITLE
[CT-1259] [Bug] Python formatter configs are not in config files

### ISSUE THREAD

**Issue by max-sixty** [dbt-labs/dbt-core#5946]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Not quite a bug, but what category should this be in? According to the PR template I need to open an issue.

Python formatter configs are not in config files, so IDEs can't read them, so saving a file in VSCode changes the formatting, which pre-commit then changes back.

The PR will put the configs in a single place where everything can read them!

### Expected Behavior

n/a

### Steps To Reproduce

n/a

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by lostmygithubaccount** [comment]
@max-sixty thanks for opening this with the PR! looks like something we should do to me

**Comment by max-sixty** [comment]
@lostmygithubaccount great — let me know if you need anything else to hit the green button!
