### ISSUE TITLE
[CT-1261] Have a "FROM SOURCES" SQL query

### ISSUE THREAD

**Issue by mkleinbort-ic** [dbt-labs/dbt-core#5949]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I often query views created in DBT, but when I encounter an issue it is hard to share the SQL with external colleagues to troubleshoot the problem. This is mainly because some teams that don't have access to the DBT managed views themselves (or the data vendors for the raw data), so **there is no single SQL statement they can run to reproduce the issue**. 

I'm looking for a version of the "Compiled SQL" that goes all the way back to the sources. I envision this as a recursive replacement of the dbt tables/views until you get to only referencing sources.  

For example; if you have model:

```
-- dbtTable1.sql
SELECT * FROM {{ source('dbo', 'sourceX') }}
```

and 
```
-- dbtTable2.sql
SELECT * FROM {{ref('dbtTable1')}}
```

I'd like to be able to see dbtTable2's compiled sql as 

```
SELECT * FROM dbo.sourceX
```

Note: Obviously this is more valuable with more complex queries. 

### Who will this benefit?

Teams working with data vendors and/or collaboration between DBT users and non-dbt users.

### Are you interested in contributing this feature?

No

**Comment by lostmygithubaccount** [comment]
hi @mkleinbort-ic, are you aware of the compiled code in the target directory? when you run `dbt compile` or several other commands (`run`, `build` at least) your code is "compiled", which is then shipped off to the warehouse for execution. 

that code ends up (by default) somewhere like `target/compiled/<project-name>/models/<path-to-model>/<model-name>.<sql|py>

let us know if you're looking for something else or this isn't sufficient!

**Comment by mkleinbort-ic** [comment]
Yes, and it is very helpful, but not enough to address the ask.

When I have DBT models on DBT models the compiled SQL references tables/views that are not available to the data vendors / external partners (ie. not the raw data). I'd have to send 10+ (compiled) SQL files to external colleagues and they'd have to run each of these (in a given order) to create the tables/views - and then they can see what I'm seeing.


To illustrate the point, consider the following:

`layer1.sql`
```
SELECT * FROM {{ source('dbo', 'raw_transactions') }} WHERE transactionStatus != 'cancelled'
```

`layer2.sql`
```
SELECT storeId, SUM(sales) AS storeSales FROM {{ ref('layer1') }} GROUP BY storeId
```

This roughly gets compiled to:

`layer1.sql`
```
SELECT * FROM SOURCE_DATABASE.SOURCE_SCHEMA.raw_transactions WHERE transactionStatus != 'cancelled'
```
And 

`layer2.sql`
```
SELECT storeId, SUM(sales) AS storeSales FROM TARGET_DATABASE.TARGET_SCHEMA.layer1 GROUP BY storeId
```

However, if I see an error in the results of `layer2` (the view) I need people to have access to the `layer1` view to help me troubleshoot it. 

A naive solution would be to recursively replace dbt's views with CTEs. Something like:

`layer2_from_source.sql`
```
WITH layer1 AS (
    SELECT * FROM SOURCE_DATABASE.SOURCE_SCHEMA.raw_transactions WHERE transactionStatus != 'cancelled'
)

SELECT storeId, SUM(sales) as storeSales FROM layer1 GROUP BY storeId
```

But it is unlikely a CTE solution would always result in valid SQL. 

(as before, this has much more value the "deeper" the DBT dag becomes)

**Comment by jtcohen6** [comment]
> A naive solution would be to recursively replace dbt's views with CTEs.

You could actually get this, by changing all the model materializations to `ephemeral`!

Here's what I get in the example above, with `dbt compile -s layer2`:
```sql
with __dbt__cte__layer1 as (
SELECT * FROM "jerco"."dbo"."raw_transactions" WHERE transactionStatus != 'cancelled'
)SELECT storeId, SUM(sales) AS storeSales FROM __dbt__cte__layer1 GROUP BY storeId
```

The spacing could be prettier, but that's effectively what you're after.

One cool trick to override the configuration of all models in your project: Install it as a package in another project. Any config you set in your root-level project's `dbt_project.yml` takes precedence over all config set in packages.
```yml
# packages.yml
local: path/to/actual/project
```
```yml
# dbt_project.yml
name: 'wrapper_project'
...
models:
  actual_project_name:  # installed here as a package
    +materialized: ephemeral
```

---

Now, in order to _rewrite_ that SQL — to simplify it down — dbt would need an actual validating SQL parser / transpiler. That's something we've discussed wanting for other reasons (#4454, #4458), and we might want it for this reason, too — probably by integrating with other SQL parsers / transpilers! That would be a way to "simplify" the SQL above to something like:
```sql
SELECT storeId, SUM(sales) AS storeSales
FROM "jerco"."dbo"."raw_transactions"
WHERE transactionStatus != 'cancelled'
GROUP BY storeId
```

---

I'm going to close this issue in the meantime, as something that's already made possible by the `ephemeral` materialization. Rewriting/simplifying SQL would be a much bigger lift, but I'm not saying never.

**Comment by mkleinbort-ic** [comment]
No need for the SQL simplification - your answer solves my problem!
