### ISSUE TITLE
[CT-1270] [Spike] Integration Tests not cleaning up artifacts

### ISSUE THREAD

**Issue by Fleid** [dbt-labs/dbt-core#5960]
Spike for https://github.com/dbt-labs/dbt-bigquery/issues/300

Behavior observed in dbt-bigquery, but solving it should happen in core:

> [Integration test](https://github.com/dbt-labs/dbt-bigquery/blob/1.1.latest/tests/integration/docs_generate_tests/test_docs_generate.py) in branches 1.1 and 1.0 began failing after we exceeded the max number of allowed tables in our sandbox account for the alternate_db (project: dbt-test-alt). Once we dropped the old tables in that project the tests began to succeed again.

> Root cause is there are a few (~5) tests where database objects aren't getting cleaned up after a run resulting in a steady accumulation. Since [we set a limit of 10k](https://github.com/dbt-labs/dbt-bigquery/blob/597aaa4667320a2f0e21abdf6ac10d523757183e/dbt/adapters/bigquery/impl.py#L260) on the number of objects to return when generating docs the tests fail since the created object is not in the catalog.json file docs generates.

**Comment by McKnight-42** [comment]
through some checking through a bunch of the `bigquery` projects I saw these as the tests that are being left over artifacts

```
dbt-test-env
- _docs_generate_test_029_test
- _docs_generate_test  **
- _defer_state_other  **
- _test_store_test_failuers
- _test_store_test_failures_dbt_test__audit
- _adapter_methods_rename_relation
- _simple_copy
- _bigquery_test
- _no_access_models
- _model_hooks
- _test_incremental_schema
- _incremental_unique_key
- _adapter_methods_caching

dbt-test-env-alt
- _simple_archive_004
- _docs_generate_029
- _simple_snapeshot_004
- _aliases_026
- _docs_generate
- _simple_snapshot
- _docs_generate_test
- _test_override_database

tests with ** next to their name are left over the most often
```

**Comment by McKnight-42** [comment]
This is just an initial theory but for `test_override_database` which gets left  in the `dbt-test-env-alt` my current guess is that when we create new `schemas` that point from to a different `database` 
ex:
```
    def assertExpectedRelations(self, project):
        check_relations_equal_with_relations(project.adapter, [
            project.adapter.Relation.create(schema=project.test_schema, identifier="seed"),
            project.adapter.Relation.create(database=os.getenv("BIGQUERY_TEST_ALT_DATABASE"), schema=project.test_schema, identifier="view_2"),
            project.adapter.Relation.create(database=os.getenv("BIGQUERY_TEST_ALT_DATABASE"), schema=project.test_schema, identifier="view_1"),
            project.adapter.Relation.create(schema=project.test_schema, identifier="view_3"),
            project.adapter.Relation.create(database=os.getenv("BIGQUERY_TEST_ALT_DATABASE"), schema=project.test_schema, identifier="view_4")
        ])
```

`drop_test_schema` might not work properly found in `util.py`
```
# Drop the unique test schema, usually called in test cleanup
    def drop_test_schema(self):
        with get_connection(self.adapter):
            for schema_name in self.created_schemas:
                relation = self.adapter.Relation.create(database=self.database, schema=schema_name)
                self.adapter.drop_schema(relation)
            self.created_schemas = []
``` might point back to the original schemas not the modified once so they remain?

**Comment by McKnight-42** [comment]
NOTE: may need to also tag people to check what they are currrently converting during or at end of process to see if any tests get left as part of testing during conversion.

**Comment by McKnight-42** [comment]
Notion doc for writeup would love any feedback https://www.notion.so/dbtlabs/Bigquery-Leftover-tests-artifacts-350aa89a047f44b3b3b1967aaff8367e

**Comment by McKnight-42** [comment]
also sadly as though we would like to solve this in the `dbt-core` as noted above `dbt-bigquery` is only adapter that is a `BaseAdapter` and doesn't natively use a `drop_schema` method via sql as done in `SQLAdapter` and uses a bigquery specific version of `drop_schema` found [here](https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/impl.py#L313).
