### ISSUE TITLE
[CT-1283] Generate proto definitions from Python classes for complex internal objects

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#5987]
A related part of this is identifying ways to generate proto definitions from Python classes, because creating a set of parallel classes where every time we add a new attribute it must be added in two places is suboptimal. This might look like adding proto integer identifiers to attributes, like pure_protobuf.

_Originally posted by @gshank in https://github.com/dbt-labs/dbt-core/issues/5663#issuecomment-1261128872_

Particularly interested in objects that are _sort of_ contracted today, via our JSON artifacts:
- nodes
- run results

This is also an opportunity for us to decide which fields in these objects should be internal only vs. publicly contracted

**Comment by emmyoop** [comment]
It does not make sense to do this at this point.  Closing for now.
