### ISSUE TITLE
[CT-1285] [Feature] extend `-f` flag shorthand to other commands 

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-core#5990]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

PR #5908 added the `-f` shorthand for `--full-refresh`, but I accidentally only allowed it for the `dbt build` command. This shoul dbe extended to `dbt seed` and `dbt run` and ot any other command that takes `--full-refresh`

### Describe alternatives you've considered

NA

### Who will this benefit?

typers

### Are you interested in contributing this feature?

yes

**Comment by lostmygithubaccount** [comment]
thanks @dave-connors-3! looks like the PR is already approved
