### ISSUE TITLE
[CT-1286] [FLAGS.WHICH] No output for variable flags.which

### ISSUE THREAD

**Issue by JosePPortela** [dbt-labs/dbt-core#5992]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hi!

My issue resides on the fact that when I invoke via Jinja the variable {{ flags.WHICH}} it returns no output.

I am trying to use this variable to get what type of command the DBT is running at the moment, either a run, a test, generate, etc.

I am using the version dbt 0.18.1 with the adapter SPARK

### Expected Behavior

My expectation was that this variable would return a value, as I have seen in other issues on the Internet, like for example https://github.com/dbt-labs/dbt-core/issues/4445

### Steps To Reproduce

1. Create a macro that is invoked in the on-run-start
2. On this macro, through a Jinja log command, display in log the variable value {{log(flags.WHICH,info=True)}}

### Environment

```markdown
- OS:
- Python: 3.7.9
- dbt: 0.18.1
```

### Which database adapter are you using with dbt?

spark

**Comment by lostmygithubaccount** [comment]
hi @JosePPortela, we will not be able to fix this as [we are no longer releasing new patches for minor versions prior to v1.0](https://docs.getdbt.com/docs/core-versions#version-support-prior-to-v10)

I've just tested this on the 1.3 RC and it works as expected.

_models/test.sql_

```sql
select '{{ flags.WHICH}}' as test
```

`dbt run -s test` results in `target/compiled/<project_name>/models/test.sql`:

```sql
select 'run' as test
```

`dbt compile -s test` will result in the same filename with:

```sql
select 'compile' as test
```

this will evaluate the `flags.WHICH` variable at compile time

**Comment by lostmygithubaccount** [comment]
(sorry, meant to close as won't fix, need to reopen and close again)
