### ISSUE TITLE
[CT-1288] [Feature] allow returning `str` instead of dataframe object from `ref` and `source` in dbt-py models

### ISSUE THREAD

**Issue by lostmygithubaccount** [dbt-labs/dbt-core#5995]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

allow returning the relation string from `dbt.ref` and `dbt.source` calls in dbt-py models instead of the platform's corresponding dataframe object (Snowpark or PySpark). this is to allow customization on read. customization on write should still be handled by the materialization concept

**Option A: new param in the functions**

```python
...

relation_str = dbt.ref("orders", direct=True)

# or 

relation_str = dbt.ref("orders", return_str=True)
```

fairly striaghtforward. I'm biased toward `direct` given a previous product life

**Option B: `str` via dunder methods**

```python
...
relation_str = str(dbt.ref("orders"))
```

**Option C: new method**

```python
relation_str = dbt.ref_str("orders")
```

---

I prefer Option B. note while only `ref` is shown, the same is needed for `source`

**Acceptance criteria:**

- settle on exact UX for getting strings from dbt refs and sources
- implementation and testing

### Describe alternatives you've considered

not allowing this. or a more complex `dbt` object that can return all relevant metadata

### Who will this benefit?

- people with custom requirements for loading in dataframes to their dbt-py model
- other needs for the relation string 

### Are you interested in contributing this feature?

no

**Comment by leo-schick** [comment]
@lostmygithubaccount does the use of `dbt.ref_str` add the model as upstream to cover discussion https://github.com/dbt-labs/dbt-core/discussions/6841 ?
