### ISSUE TITLE
[CT-1289] Research Building Block Efforts: Short Term Wins + Long Term Reusability | Public/Private models in a monorepo

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/dbt-core#5998]
Inspired by this internal slack thread: [here](https://dbt-labs.slack.com/archives/C0418AGGQ74/p1664817873731629?thread_ts=1664802844.975229&cid=C0418AGGQ74)

**Success Criteria**
- [x] Links to existing files in dbt-core that need to be updated
- [x] Net new files in dbt-core and why it needs new files
- [x] Potential "gotcha" implementations based on the above(think: if we update this file here, we have to update 100 files downstream)
- [x] pseudo-code snippets on initial approach for the above to make this functionality work
- [x] Working Code to verify general flow is in the right direction
- [x] Loom demo video

- This will be included in the draft pull request

**Comment by sungchun12** [comment]
Also inspired by an internal notion page: [here](https://www.notion.so/dbtlabs/Are-projects-really-the-thing-1ee712e2a68944d28997f62c380c6b4f)

**Comment by sungchun12** [comment]
Fun diagram to illustrate how the public/private dbt DAG should look and feel: [here](https://whimsical.com/public-private-dbt-models-2NxeKuU8oUiPxpKrkWpsvo)

**Comment by sungchun12** [comment]
How python handles public/private interfaces: [here](https://www.geeksforgeeks.org/access-modifiers-in-python-public-private-and-protected/)

**Comment by lostmygithubaccount** [comment]
@sungchun12 that first Slack thread link goes to a docs page (https://docs.getdbt.com/docs/dbt-cloud/deployments/deployment-architecture)

**Comment by sungchun12** [comment]
@lostmygithubaccount fixed!

**Comment by sungchun12** [comment]
@ian-fahey-dbt thanks for the great example below!

As an example, I’ve been working on resolving and clarifying the customer entity in our internal project. A primary goal of my work currently is better clarifying our use of customer_id with prefixes (quickbooks_, stripe_, and ultimately dbt_)

As you can imagine, those are extremely densely threaded identifiers, appearing in dozens of models. It took me some time to identify a handful of final models to “run/build upstream” that captured all of the relevant without having to explicitly call every changed file (which would also be risky)

At an early point, I realized fct_dbt_invocations was included in my run because one of the slimmer models was using an aggregate off of it. The invocations-based field was not germane to my work and it was the difference between hours and minutes to run with it. Anecdotally, I knew it was safe to exclude it, but it feels like there is likely a contextual boundary somewhere, perhaps shortly after an aggregation that represents a significant ratio down in rows, where there could be a contract at that point such that if you’re not working on either immediate model in the contract, you can stop graph notation at that point.

**Comment by sungchun12** [comment]
Internal feedback from a customer: [here](https://www.notion.so/dbtlabs/Vercel-Managing-scale-and-complexity-c0e43023e79b479ba3813ebe99771fa9)

A fun blog by David Jayatillake: [here](https://davidsj.substack.com/p/yet-another-post-on-data-contracts-9f0?sd=pf)
