### ISSUE TITLE
[CT-1291] Review Partner Adapters

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#6001]
This ticket tracks the work to review two partner adapters, and to collect feedback on their code. Let's report back on both the parts they could improve, and the parts we liked or appreciated about their implementation.

- [ ] [Databricks](https://github.com/databricks/dbt-databricks)
- [ ] [Trino](https://github.com/starburstdata/dbt-trino)

**Comment by colin-rogers-dbt** [comment]
Reviewed and completed
