### ISSUE TITLE
[CT-1294] [Feature] Make Postgres' `indexes` config cumulative

### ISSUE THREAD

**Issue by owenprough-sift** [dbt-labs/dbt-core#6003]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

dbt on Postgres [supports creating indexes](https://docs.getdbt.com/reference/resource-configs/postgres-configs#indexes) but indexes are not cumulative when specified at multiple levels.

My situation is that there is a specific column I want to index in ~70 models so my first thought was to put that config in `dbt_project.yml`. But it looks like `{{ config( indexes = [ ... ] ) }}` in model scripts override rather than extend project-level index config.

[Hooks are cumulative](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook#hooks-are-cumulative). [Tags are additive](https://docs.getdbt.com/reference/resource-configs/tags#tags-are-additive). Grants [have inheritance rules](https://docs.getdbt.com/reference/resource-configs/grants#grant-config-inheritance). So why not make indexes cumulative/additive/inheritable as well?

### Describe alternatives you've considered

For now I have added `indexes` configuration in every model script, which is tedious and easy to forget for new scripts.

### Who will this benefit?

Folks using Postgres

### Are you interested in contributing this feature?

Not at this time, sorry

### Anything else?

https://getdbt.slack.com/archives/C0172G2E273/p1664821151316579

**Comment by lostmygithubaccount** [comment]
thanks for opening @owenprough-sift! this sounds reasonable. I'm going to edit the labels and we'll see if we or someone from the community can pick this up in the future

**Comment by JoeKellyRVA** [comment]
I just came across this issue as I ran into the same situation (I have a field that I want indexed across all of my models, but I also have separate indexes I want to add to most models). It seems more intuitive to me to have the `dbt_project.yml` `+indexes` value be additive with the config within the model
