### ISSUE TITLE
[CT-1304] [Bug] run_sql_for_tests fails when commit() method is available

### ISSUE THREAD

**Issue by lexus-dev** [dbt-labs/dbt-core#6015]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Running `python -m pytest tests/functional` against Vertica adapter results in several runtime errors.

I believe the problem is caused by `commit()` [invocation](https://github.com/lexus-dev/dbt-core/blob/23c8ac230ccf3e56413d3fa7d22fc62c5e51d7a3/core/dbt/adapters/sql/impl.py#L229) right before `fetch` is called

### Expected Behavior

Resulting datasets being fetched prior to `commit` statement

### Steps To Reproduce

Run basic tests using new testing framework against [Vertica adapter](https://github.com/vertica/dbt-vertica). Though any adapter having `commit()` available might be affected

No special environment or configs required

### Relevant log output

```shell
def test_incremental(self, project):
        # seed command
        results = run_dbt(["seed"])
        assert len(results) == 2

        # base table rowcount
        relation = relation_from_name(project.adapter, "base")
        result = project.run_sql(f"select count(*) as num_rows from {relation}", fetch="one")
>       assert result[0] == 10
E       TypeError: 'NoneType' object is not subscriptable
```
Followed by:
```
FAILED tests/functional/adapter/test_basic.py::TestSimpleMaterializationsMyAdapter::test_base - TypeError: 'NoneType' object is not subscriptable
FAILED tests/functional/adapter/test_basic.py::TestEphemeralMyAdapter::test_ephemeral - TypeError: 'NoneType' object is not subscriptable
FAILED tests/functional/adapter/test_basic.py::TestIncrementalMyAdapter::test_incremental - TypeError: 'NoneType' object is not subscriptable
FAILED tests/functional/adapter/test_basic.py::TestSnapshotCheckColsMyAdapter::test_snapshot_check_cols - TypeError: 'NoneType' object is not subscriptable
FAILED tests/functional/adapter/test_basic.py::TestSnapshotTimestampMyAdapter::test_snapshot_timestamp - TypeError: 'NoneType' object is not subscriptable
FAILED tests/functional/adapter/test_incremental.py::Testincremental::test_incremental - TypeError: 'NoneType' object is not subscriptable
=============================================================================================== 6 failed, 5 passed in 73.55s
```

### Environment

```markdown
- OS: Windows 11
- Python: 3.9.6
- dbt: 1.2.2
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

As mentioned above the issue relates to `dbt-vertica`

**Comment by lostmygithubaccount** [comment]
thanks for opening this and the PR @lexus-dev! it looks like the PR has already been marked for review by the engineering team

**Comment by hantmac** [comment]
I met the same error.
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/7600925/201909852-1f42ba3a-f3fd-405e-9db8-4d29379c5f6b.png">

**Comment by andyreagan** [comment]
I hit the same issue, and it turns out that you can, in fact, override this behavior on the adapter.

I've done so with `dbt-vertica` (see override here: https://github.com/vertica/dbt-vertica/commit/eebc963162e316d57c1b925ca2beb59144dcadfc#diff-67874b3d691086b8c7e9728acf19d6203e5f077eeca0c97f83d264158a625b8b), and this issue can safely be closed.

**Comment by colin-rogers-dbt** [comment]
thanks for the update @andyreagan! @lexus-dev closing this out but feel free to re-open if needed
