### ISSUE TITLE
[CT-1307] [Feature] Support private key auth using key in environment variable

### ISSUE THREAD

**Issue by jayhale** [dbt-labs/dbt-core#6018]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

dbt profiles support key-pair authentication using a `private_key_path` configuration option.  E.g., [Snowflake](https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile#key-pair-authentication).

While using key files is a common practice, it is also common to store keys in environment variables (typically as the base-64 encoded DER-encoded key bytes).

Allow for connection configurations using key-pair authentication when the the key is stored in an environment variable.

### Describe alternatives you've considered

*Key files*: E.g., `private_key.pem`. For most teams, storing a key file in source is disallowed by security policy.  Further, many teams may lack the ability to inject key files during deployment of a dbt application.

### Who will this benefit?

Anyone using key-pair auth for connecting to a database.

### Are you interested in contributing this feature?

I can provide the PR

**Comment by lostmygithubaccount** [comment]
issue for snowflake https://github.com/dbt-labs/dbt-snowflake/issues/291

thanks @jayhale for opening these issues and the PR! do you intend to contribute PRs for all the adapters, or just snowflake?

**Comment by jayhale** [comment]
@lostmygithubaccount I've prepared a PR for dbt-snowflake since that is impacting us today.  Happy to help with PRs for other adapters over time.

**Comment by jtcohen6** [comment]
I figure that support for this will vary by adapter auth implementation. It is already supported for `dbt-bigquery`: https://docs.getdbt.com/reference/warehouse-setups/bigquery-setup#service-account-json

It would be ideal to standardize this logic / configuration to the extent possible, but I'm not sure which pieces of the logic would actually make sense to have in `dbt-core`. My inclination is to close this broader issue in favor of the concrete next step for `dbt-snowflake` (https://github.com/dbt-labs/dbt-snowflake/issues/291)
