### ISSUE TITLE
[CT-1308] [Bug] [databricks] dbt seed strips single quotes from values in csv

### ISSUE THREAD

**Issue by jakub-auger** [dbt-labs/dbt-core#6020]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

csv contents

col_1,col_2
"Joes Diner",123
"Joe's Diner",456

run dbt seed

contents of created seed table are
Joes Diner,123
Joes Diner,456

### Expected Behavior

contents of created seed table are
Joes Diner,123
Joe's Diner,456

### Steps To Reproduce

create /seed/test.csv file with the following contents
col_1,col_2
"Joes Diner",123
"Joe's Diner",456

run dbt seed -s test

on your databricks instance, run select * from default.test

### Environment

```markdown
- OS:
windows 11
- Python:
python --version
Python 3.9.12
- dbt:
dbt --version
Core:
  - installed: 1.2.2
  - latest:    1.2.2 - Up to date!

Plugins:
  - databricks:        1.2.3  - Up to date!
  - postgres:          1.1.0  - Not compatible!
  - spark:             1.2.0  - Up to date!
  - sqlserver:         0.20.1 - Not compatible!
  - synapse:           0.20.0 - Not compatible!
  - synapseserverless: 0.20.0 - Not compatible!
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

dbt-databricks

**Comment by otosky** [comment]
this is actually a dependency issue on the [databricks-sql-connector](https://pypi.org/project/databricks-sql-connector/) package

I noticed that this issue recently went away when someone on my team accidentally bumped that package from 2.1.0 -> 2.2.0

**Comment by dbeatty10** [comment]
Thanks for this crucial info @otosky !

I haven't yet tested databricks-sql-connector 2.1.0 vs. databricks-sql-connector 2.20 myself. Assuming that 2.2.0 indeed fixes this, then this issue could be solved by updating the dbt-databricks adapter [here](https://github.com/databricks/dbt-databricks/blob/4b56862db1947239585315e9361cc479a547f041/setup.py#L59) to reflect that version.

I'll plan on opening this issue over at [dbt-databricks](https://github.com/databricks/dbt-databricks) and then closing this one.

**Comment by dbeatty10** [comment]
Closing in favor of https://github.com/databricks/dbt-databricks/issues/254
