### ISSUE TITLE
[CT-1311] [Feature] pre/post hooks of type webhook

### ISSUE THREAD

**Issue by Dikootje** [dbt-labs/dbt-core#6021]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Extend the pre/posthook functionality to not only support SQL queries to be executed but webhooks as well. 

Even a simple GET request could be enough i.e.: 
```
{{ config(
    post_hook=[
      "alter table {{ this }} ..."
    ],
    post_webhook=[
      "https://<hostname>/api/<endpoint>/?modelname={{ this }}"
    ]
) }}
```

I get the naming of `post_webhook` for a GET request is weird, so I'm very open for naming suggestions. 

### Describe alternatives you've considered

On Snowflake there is the possibility to create python stored procedures which we could maybe call to do the request (not sure if python is able to make connections to external networks yet). But the reason we choose DBT as our engine was the idea it would be easy to port to another platform like Azure Synapse, GCP.

**Comment by lostmygithubaccount** [comment]
hi @Dikootje, thanks for opening! have you seen the feature request for external nodes in https://github.com/dbt-labs/dbt-core/discussions/5073? this is likely something we'll be prioritizing soon and sounds like it'd meet your needs

on Python making external network connections, the latest I've seen is here: https://community.snowflake.com/s/question/0D53r0000BeAAgHCQW/error-in-calling-rest-api-endpoint-using-requests-get-post-method-in-snowpark-python-stored-procedure essentially saying they'll support it at GA

**Comment by Dikootje** [comment]
This is more or less the same as I mentioned in the considered alternatives section. Which would require a very platform specific solution.

But unfortunately this does not work on synapse or big query.

**Comment by jtcohen6** [comment]
I definitely agree with supporting this via "external"/"activated" nodes! This is a Big Idea we're interested in starting on next year. We'd want to remain strongly opinionated about what, when, & why to use these. Think:
- sources that trigger their own ingestion
- models that trigger data transformation/processing/enrichment via third-party DWH integrations
- exposures that trigger sinks/syncs once the dataset(s) is/are ready

I'm much _less_ excited about supporting these hooks via pre/post hooks. I'm pretty bearish on pre/post hooks in general! It's important that they exist, as "advanced" functionality, a place to stick highly custom glue code that's not well represented by the opinionated (and intentionally narrow) set of functionality that is first-class in dbt. Or, even code that's borderline anti-pattern for the dbt way of doing things. Hard things that should be possible, not easy :)

When we think a use case is important and legit enough — performance optimizations in years past, `grants` this year, integrations with other data tools in the future — we should treat them as real first-class attributes of a DAG node, or as DAG nodes in their own right.

In the meantime, pre/post hooks are "just SQL" — which, depending on your data platform, can still do some pretty powerful things in this vein. See: [Snowflake external functions](https://docs.snowflake.com/en/sql-reference/external-functions-introduction.html), [BigQuery remote functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/remote-functions), ... nothing I could find for Synapse, though.

I'm going to close this issue, as I think we'll want a more opinionated framework for how dbt integrates with / orchestrates external requests.
