### ISSUE TITLE
[CT-1318] [Bug] error while generating docs for database designed without schema

### ISSUE THREAD

**Issue by forestlzj** [dbt-labs/dbt-core#6031]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am creating a adapter for maxcompute , it is designed without schema, it raises error while generating docs:

```
05:25:22.591766 [warn ] [MainThread]: Encountered an error while generating catalog: 'NoneType' object has no attribute 'lower'
```

### Expected Behavior

docs is generated successfully when running command:
dbt docs generate

### Steps To Reproduce

1. create a python env with dbt=1.1.1
2. create a new adapter for maxcompute with setting database = None and schema = maxcompte project
3. set up profile.xml
4.  go dbt sample jaffle_shop-main
5. run  `dbt run`
6. run `dbt docs generate`

### Relevant log output

```shell
05:25:22.591306 [debug] [ThreadPool]: On None.information_schema: Close
05:25:22.591766 [warn ] [MainThread]: Encountered an error while generating catalog: 'NoneType' object has no attribute 'lower'
05:25:22.597671 [error] [MainThread]: dbt encountered 1 failure while writing the catalog
05:25:22.597964 [info ] [MainThread]: Catalog written to /mnt/program/pyenv/code/jaffle_shop-main/target/catalog.json
05:25:22.598231 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe31e659070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe31c6edf40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe31c6edfd0>]}
```

### Environment

```markdown
- OS: ubuntu 20.4
- Python: 3.8
- dbt: 1.1.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

alicloud maxcompute (i am creating this adapter)

**Comment by dataders** [comment]
hey @forestlzj! Have you seen our [Adapter Development guides](https://docs.getdbt.com/category/adapter-development) on our docs site already? That's a great place to start. I also highly recommend [joining the community Slack](https://community.getdbt.com/), especially the #adapterecosystem channel.

With regards to your question, there are many adapters that do not support the `database` field. The classic example of this is dbt-spark. We have Relation include policy which should be enough to drop all instances of `database` in your adapter.
https://github.com/dbt-labs/dbt-spark/blob/b65e4f366bce7dc98c2e698667fb197faa7cbe48/dbt/adapters/spark/relation.py#L16-L20
