### ISSUE TITLE
[CT-1319] [Bug] run_sql_for_tests fail for mysql.connector when executing select stmt

### ISSUE THREAD

**Issue by zhangyangyu** [dbt-labs/dbt-core#6033]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`run_sql_for_tests` would fail if trying to use it to execute a select statement when the driver is mysql.connector, because though [it has a `commit` method](https://github.com/lexus-dev/dbt-core/blob/23c8ac230ccf3e56413d3fa7d22fc62c5e51d7a3/core/dbt/adapters/sql/impl.py#L229), it's not expected to be called after select, check [the thread on MySQL forum](https://forums.mysql.com/read.php?50,705497,705497#msg-705497). A workaround would be pass `buffered=True` to `connect` to make it use another cursor type underneath.

### Expected Behavior

Be compatible with mysql.connector. I think `run_sql_for_tests` might take a wrong assumption.

### Steps To Reproduce

```
>>> import mysql.connector
>>> cnx = mysql.connector.connect(user="root")
>>> cur = cnx.cursor()
>>> cur.execute('select count(*) from test.test')
>>> cnx.commit()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/opt/homebrew/lib/python3.9/site-packages/mysql/connector/connection.py", line 1229, in commit
self._execute_query("COMMIT")
File "/opt/homebrew/lib/python3.9/site-packages/mysql/connector/connection.py", line 1247, in _execute_query
self.handle_unread_result()
File "/opt/homebrew/lib/python3.9/site-packages/mysql/connector/connection.py", line 1455, in handle_unread_result
raise errors.InternalError("Unread result found")
mysql.connector.errors.InternalError: Unread result found
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @zhangyangyu!

Did you try adding a custom implementation of `run_sql_for_tests` that works for mysql-connector-python to [here](https://github.com/pingcap/dbt-tidb/blob/main/dbt/adapters/tidb/impl.py)? That might be your best bet.

We haven't heard a similar report from any other adapters, and it sounds like this code does work for other MySQL clients like [PyMySQL](https://pypi.org/project/PyMySQL/) and [mysqlclient](https://pypi.org/project/mysqlclient/). So I'm inclined to believe that this is a request to be made of the maintainers of [mysql-connector-python](https://pypi.org/project/mysql-connector-python/).

**Comment by zhangyangyu** [comment]
I am the maintainer of dbt-tidb and this is the problem we found while developing it :-). This is specific to mysql-connector-python and only their basic cursor type, not big problem.

Not sure mysql-connector-python will change it as you could see the replies in MySQL forum thread. But never mind, I create this issue in case anyone in future encounter the same problem as us.

**Comment by dbeatty10** [comment]
Yeah, thank you for reporting this @zhangyangyu in case anyone else encounters this (like [dbt-mysql](https://github.com/dbeatty10/dbt-mysql)).

Our recommended solution for any adapter maintainers that run into a similar issue:
- Override `run_sql_for_tests` with a custom implementation that handles this behavior of mysql-connector-python

Closing as "wontfix" since the underlying issue seems to be in the mysql-connector-python driver and we have a work around.

**Comment by dbeatty10** [comment]
For any dbt adapter maintainers relying on the mysql connector, here are two identical examples of solving this error:
- https://github.com/pingcap/dbt-tidb/blob/44b90a73e8d0140a9a3fbdd98efcbfdd8a675313/dbt/adapters/tidb/connections.py#L86
- https://github.com/dbeatty10/dbt-mysql/blob/fa650a78a08d430f712de381f5c1c090f058322e/dbt/adapters/mysql/connections.py#L88
