### ISSUE TITLE
[CT-1321] [Feature] Bigquery: set the execution project in dbt_project.yml

### ISSUE THREAD

**Issue by matt-winkler** [dbt-labs/dbt-core#6036]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Today, we allow setting the `execution_project` in `profiles.yml`. This is a request to enable setting this value for specific folders, models etc. within the `dbt_project.yml`. From an end user perspective, it's similar in concept to enabling selection of virtual warehouses on snowflake. However, "project" in bigquery is for sure a different entity than warehouse in snowflake.

**Comment by jtcohen6** [comment]
Closed in favor of https://github.com/dbt-labs/dbt-bigquery/issues/343
