### ISSUE TITLE
[CT-1335] [Feature] Add support for columnar tables for the PostgreSQL table materialization

### ISSUE THREAD

**Issue by Dennis8** [dbt-labs/dbt-core#6052]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Make it configurable to add a configuration parameter with columnar that is a boolean, that

### Describe alternatives you've considered

Posthook is possible, however data then already is written in a row-orientation in the table.

### Who will this benefit?

Anyone using Citus Columnar extension for analytic or DW workloads:
- Compression
- Doesn't read unnecessary columns
- Efficient VACUUM

### Are you interested in contributing this feature?

Yes, I will add it myself to the codebase. Where should I adjust the documentation to inform users about the added option?

### Anything else?

[README of Citus Columnar](https://github.com/citusdata/citus/blob/main/src/backend/columnar/README.md)
[Docs of Citus Columnar](https://docs.citusdata.com/en/stable/admin_guide/table_management.html#columnar-storage)

**Comment by lostmygithubaccount** [comment]
thanks @Dennis8! it looks like engineering is already engaged on the PR

I believe the relevant doc page is this one: https://docs.getdbt.com/reference/resource-configs/postgres-configs which you can edit here: https://github.com/dbt-labs/docs.getdbt.com/edit/current/website/docs/reference/resource-configs/postgres-configs.md

**Comment by jtcohen6** [comment]
Closing this issue for now, given the rationale above
