### ISSUE TITLE
[CT-1337] [Bug] dbt is writing `target/partial_parse.msgpack` in current working directory and not using config's project-dir

### ISSUE THREAD

**Issue by ssassi** [dbt-labs/dbt-core#6055]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

This [line](https://github.com/dbt-labs/dbt-core/blob/558468e85480c2f25fa7742d7d3d54ee813524d1/core/dbt/parser/manifest.py#L546) is creating a new relative path to the `target` folder instead of an absolute path as [this line](https://github.com/dbt-labs/dbt-core/blob/558468e85480c2f25fa7742d7d3d54ee813524d1/core/dbt/parser/manifest.py#L643) is correctly doing.

### Expected Behavior

To store `partial_parse.msgpack` in the right folder. Right now, it could create it in current working directory instead of `project-dir`.

### Steps To Reproduce

Couldn't find a way to reproduce it using dbt commands. It is happening on [sqlfluff dbt templater](https://github.com/sqlfluff/sqlfluff) when using `dbt.parser.manifest` to read manifest.

### Environment

```markdown
- OS: any
- Python: 3.8
- dbt: 1.3
```

### Which database adapter are you using with dbt?

postgres, redshift, snowflake, bigquery, spark

**Comment by jtcohen6** [comment]
Closing as a duplicate of https://github.com/dbt-labs/dbt-snowflake/issues/288. From conversation on that issue, it sounds like the root cause here was a behavior change in a recent Snowflake release, which they're working to roll back.
