### ISSUE TITLE
[CT-1343] [Regression] 1.3.0 breaks projects that colocate non-dbt-related Python code with sql model ("dbt only allow one model defined per python file")

### ISSUE THREAD

**Issue by tin-homa** [dbt-labs/dbt-core#6061]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

We have been structuring our projects to have the models_path pointing to folders that contains both dbt code (in .sql files) and other python code used for extract-load the data, or run some light modelling. This simplifies our repo structure a lot and has been very convenience to work with (compared to the default approach of having a separate dbt folder).

However, since v1.3.0 we're failing to run any dbt model (sql) due to this error
```
Parsing Error in model the_unrelated_python_file
dbt only allow one model defined per python file
```

We realize this is due to the new version starting looking into .py files to find models, and assuming all .py files are dbt-related.

### Expected/Previous Behavior

While I look forward to using dbt Python model, I don't think this feature should inhibit the ability of having other type of Python files in the same folder.
I'd suggest to either
- ignore .py files that don't have a specific dbt marker
- allow a project config to turn off the use of dbt Python altogether (we use Redshift so it's not even supported yet I believe)

### Steps To Reproduce

1. Have a dbt project. Inside the model-path folder, put:
   - a sql dbt model
   - a non-dbt Python file which contains more than 1 class definition.
2. Run `dbt run -s the_sql_model`
3. See the error

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8
- dbt (working version): <=1.2.2
- dbt (regression version): 1.3.0
```

### Which database adapter are you using with dbt?

redshift

**Comment by ChenyuLInx** [comment]
@tin-homa  Sorry to hear that you run into this issue! We added [`.dbtignore`](https://github.com/dbt-labs/dbt-core/issues/5733) feature to help with this situation. 

Can you try to add the `.dbtignore` file at the project root dir that excludes those files? Let us know if there's still a issue afterwareds!

**Comment by lostmygithubaccount** [comment]
hi @tin-homa, I just tested this and placing `**.py` works for me to ignore all `.py` files in the models directory. can you confirm the version of dbt you're on? 

the `.dbtignore` should be in the project root, on the same level as `dbt_project.yml`. one example here: https://github.com/dbt-labs/dbt-demo-data/blob/snowflake-sql-v-py/.dbtignore

I tested another with `**.py` in it and a few Python files

**Comment by tin-homa** [comment]
Here's some screenshots
- 1.3.0 error
![image](https://user-images.githubusercontent.com/90271975/195649930-ccc28756-e130-476d-9907-35de45808cfe.png)

- 1.2.2 success (same repo, same code, I just reinstall dbt through pip)
![image](https://user-images.githubusercontent.com/90271975/195650008-53951db7-1b8d-4475-b337-6e583624c9f6.png)

- Here's where my `.dbtignore` is placed, same level with `dbt_project.yml`
![image](https://user-images.githubusercontent.com/90271975/195650113-66c71104-6121-430e-bbf6-7092f495a966.png)

- Here's the content of the file
![image](https://user-images.githubusercontent.com/90271975/195650130-3105184c-f7b1-40f5-a076-c0a822a403a2.png)

- FYI my model-paths have multiple folders inside. Maybe it's an edge case that's not been considered during dbtignore implementation?
![image](https://user-images.githubusercontent.com/90271975/195650843-025996e0-7faa-48db-b9ba-6bc4f8dd8fbf.png)

**Comment by ChenyuLInx** [comment]
@tin-homa  I still couldn't reproduce the issue, with multi layer of folder and everything. I wonder could it be library mismatch? Can you try `pip freeze | grep pathspec` and see which version of `pathspec` you have? I had 0.9.0 and also just tested 0.10.1 works fine.

Also happy to hop on a huddle on dbt slack to take a look together, you can find me at `@Chenyu Li(dbt Labs)`

**Comment by tin-homa** [comment]
I have `pathspec==0.9.0` as well.
Let me try creating a minimal example that can produce the error.

**Comment by tin-homa** [comment]
I tested again and the dbtignore works for me now. Maybe I was doing stupid things yesterday or I just needed to restart my environment somehow. Sorry for all the fuzz and thanks a lot for the quick response.

**Comment by jtcohen6** [comment]
Very glad you were able to get this working!

@lostmygithubaccount We still need to actually document `.dbtignore`: https://github.com/dbt-labs/docs.getdbt.com/issues/2043
