### ISSUE TITLE
[CT-1347] [Bug] Tags defined outside of dbt_project.yml not showing in docs

### ISSUE THREAD

**Issue by prgx-aeveri01** [dbt-labs/dbt-core#6065]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If I add a tag in a non dbt_project.yml file for a model it is not shown in dbt docs when served.

### Expected Behavior

I would expect all tags for a model defined at any level to be shown in the documentation

### Steps To Reproduce

1. Add a tag to a project folder .yml file: 
```
config:
   tags: ['my_tag']
```
2. run `dbt docs generate`
3. run `dbt docs serve`
4. Navigate to the model's page
5. See "tags" section

### Environment

```markdown
- OS:Ubuntu 20.04
- Python: 3.7.6
- dbt: 1.2.3
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Trino

**Comment by jtcohen6** [comment]
I wasn't able to reproduce this:
```yml
version: 2
models:
  - name: model_a
    config:
      tags: ['my_tag']
```
I see this in `manifest.json`:
```json
    "model.test.model_a": {
        ...
        "tags": [
          "my_tag"
        ],
```
And the tag appears in generated `dbt-docs` as well
