### ISSUE TITLE
[CT-1350] Clean up string formatting

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#6068]
### Describe the feature

Clean up the strings in `dbt-core`.

When we originally mass formatted our code with black, it caused some weird formatting that does not matter to Python but is not how it should be.

Examples:
https://github.com/dbt-labs/dbt-core/blob/9b84b6e2e87f4e6ada4ccc343906749ba013b138/core/dbt/adapters/base/impl.py#L583-L585
https://github.com/dbt-labs/dbt-core/blob/9b84b6e2e87f4e6ada4ccc343906749ba013b138/core/dbt/config/project.py#L670-L672

Searching the code for `" f"` finds many.  The first example is harder to find as there are legitimate parts of the code with empty strings.  It is still doable however.

### Describe alternatives you've considered

Doing it as we touch these areas of code.

### Who will this benefit?

Anyone looking at the code who is irked by this formatting.

**Comment by mhoss2008** [comment]
Hi

**Comment by luke-bassett** [comment]
Can I help with this one?

**Comment by luke-bassett** [comment]
I think this command finds all the files that contain cases that match the examples in the first comment on this issue (with a few false positives):
```bash
fd '.py$' | xargs grep -Ei '(.*"\s+".*)|(.*"\s+f".*)' | awk '{print $1}' | sort | uniq | sed -E 's/(.*):/\1/'
```

```
./core/dbt/adapters/base/impl.py
./core/dbt/clients/_jinja_blocks.py
./core/dbt/config/project.py
./core/dbt/context/base.py
./core/dbt/context/providers.py
./core/dbt/contracts/connection.py
./core/dbt/contracts/graph/manifest.py
./core/dbt/contracts/graph/unparsed.py
./core/dbt/contracts/results.py
./core/dbt/events/functions.py
./core/dbt/events/types.py
./core/dbt/exceptions.py
./core/dbt/graph/cli.py
./core/dbt/graph/graph.py
./core/dbt/graph/selector.py
./core/dbt/logger.py
./core/dbt/parser/base.py
./core/dbt/parser/generic_test_builders.py
./core/dbt/parser/schemas.py
./core/dbt/parser/sources.py
./core/dbt/task/base.py
./core/dbt/task/compile.py
./core/dbt/task/freshness.py
./core/dbt/task/init.py
./core/dbt/task/runnable.py
./core/dbt/tests/util.py
./core/dbt/utils.py
./plugins/postgres/dbt/adapters/postgres/connections.py
./tests/functional/artifacts/expected_manifest.py
./tests/functional/configs/test_disabled_model.py
./tests/functional/deprecations/test_deprecations.py
./tests/functional/duplicates/test_duplicate_analysis.py
./tests/functional/duplicates/test_duplicate_macro.py
./tests/functional/duplicates/test_duplicate_model.py
```

**Comment by luke-bassett** [comment]
Working on this one for the hackathon

**Comment by eve-johns** [comment]
> Working on this one for the hackathon

+1

**Comment by emmyoop** [comment]
@luke-bassett script is a great way to go!  The `" "` case has a lot more false positives.  Feel free to do this in two iterations - once for f-strings and once for plain string.

**Comment by luke-bassett** [comment]
Looks like @eve-johns has covered f-strings. This command still has a couple false positives, but fewer. 

```bash
fd '.py$' | xargs grep -Ei '.*".*"\s+".*".*' | awk '{print $1}' | sort | uniq | sed -E 's/(.*):/\1/' 
```


I'm making the changes now.

**Comment by eve-johns** [comment]
Ah I didn't noticed there are also plain strings problem. Trying regx
