### ISSUE TITLE
[CT-1351] [Feature] Add optional `incremental_key` config to incremental models

### ISSUE THREAD

**Issue by randypitcherii** [dbt-labs/dbt-core#6069]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like the ability to pass in a column (or SQL expression string) to incremental models that specifies an incremental column to use for incremental processing.

This follows the pattern of the optional `unique_key` config.

This change would remove the need to repeatedly add the same `is_incremental()` check by hand. 

So instead of:
```sql
{{
  config(
    materialized='incremental',
    unique_key='id'
 )
}}

select 
  id, 
  ingestion_time 
from {{ref('my_parent')}}

{% if is_incremental() %}
  -- this filter will only be applied on an incremental run
  WHERE {{ incremental_key }} >= (SELECT MAX(THIS.{{ incremental_key }}) FROM {{ this }} THIS)
{% endif %}

```

A user can write:
```sql
{{
  config(
    materialized='incremental',
    unique_key='id',
    incremental_key='ingestion_time'
 )
}}

select 
  id, 
  ingestion_time 
from {{ref('my_parent')}}
```

### Describe alternatives you've considered

The obvious alternative is creating this as a custom materialization, maybe throw it in a library for folks to use.

I think this is such a common pattern though that it deserves to be built in to incrementals.

### Who will this benefit?

Users that process incremental data in relatively simple ways.

### Are you interested in contributing this feature?

Yes! Will PR next : )

### Anything else?

I know I brought this up once, but I can't find if that ever made its way to a github issue / PR.

I have ensured that users can still use is_incremental checks simply by NOT providing an incremental_key config.

**Comment by jtcohen6** [comment]
Hey @randypitcherii, thanks for opening the issue!

**Problem statement:** The `is_incremental()` code is repetitive boilerplate, more than most users probably care to write over and over again. I agree!

The issue I see with the proposed solution is that we need to be sure the filter is successfully pruning data scan on the upstream table. Wrapping the entire model SQL with a `where` statement is the approach we took back in the day, and it could actually result in _worse_ performance for models with complex queries, versus just full-refreshing the model query as a table every time. Some history on this: https://github.com/dbt-labs/dbt-core/issues/744

Now, it's possible that query optimizers have gotten smarter — but you'll never know exactly when the filter predicate _stops_ being pushed down, until your model runtimes jump up.

What I could see: We could develop a better shorthand for "put the incremental predicate here." Something like:
```sql
{{
  config(
    materialized='incremental',
    unique_key='id',
    incremental_key='ingestion_time'
 )
}}

select 
  id, 
  ingestion_time 
from {{ref('my_parent')}}
{{ incremental_where() }}
```
Where `incremental_where` is a macro like:
```sql
{% macro incremental_where() %}
where {{ incremental_key }} >= (select max(this.{{ incremental_key }}) from {{ this }} this)
{% endmacro %
```
Having typed that out, I realized it would be possible to define that macro and use it in your projects _now_, without needing a custom materialization or a `dbt-core` change. If it's a good thing to have across-the-board, it could still be a great addition for `dbt-core` + update for our docs.

**Comment by randypitcherii** [comment]
Hey!

I agree with all of this. 

My suspicion is that the vast majority of incremental models have the incremental check at the bottom. 

But that’s just a hunch!

So if folks need the control you describe, just don’t define an incremental key. 

Do you buy that?

**Comment by randypitcherii** [comment]
Ok I’ll modify the problem statement a little  more. 
 
Our default materializations in core can all be swapped without needing to change model sql. 

I’d love the option to make that true of incrementals as well. Even if just for the easier learning curve in the first exposure to dbt concepts.

**Comment by jtcohen6** [comment]
Hey! Sorry I missed your comments here last month. I hear you, keep the easy stuff easy. Re-assigning myself to give it another pass.
