### ISSUE TITLE
[CT-1360] [Bug] `dbt --version` is very slow

### ISSUE THREAD

**Issue by aranke** [dbt-labs/dbt-core#6085]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt --version` is slow and does not yields all output at once instead of incrementally.

### Expected Behavior

`dbt --version` runs faster and/or yields output incrementally

### Steps To Reproduce

Run `dbt --version`

### Relevant log output

```shell
N/A
```

### Environment

```markdown
- OS: macOS
- Python: 3.9.13
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

I used DuckDB to test but issue should be consistent across all databases.

**Comment by gshank** [comment]
This is almost certainly slow because it access PyPi to get the latest version. In order to speed this up we would have to do something different.
