### ISSUE TITLE
[CT-1367] New tracking event: Adapter info

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#6097]
We currently try to get the adapter information for tracking purposes long before we actually load the adapters-- this causes a bunch of issues where we have to parse projects and such just to track the invocation.  Since there's no benefit to this in terms of our analytics, this approach has [been changed in this PR](https://github.com/dbt-labs/dbt-core/pull/5972). 

This ticket encompasses the work necessary to properly report adapter info at such a point that we actually load the adapters.  This includes the work to update the internal analytics project to reflect the change in raw event data.

Specifically we need `adapter_type` and `adapter_unique_id` as indicated [here](https://github.com/dbt-labs/dbt-core/blob/79f043a733becd41459711fc5261ab1088deaa58/core/dbt/tracking.py#L470).

**Comment by jtcohen6** [comment]
> This includes the work to update the internal analytics project to reflect the change in raw event data.

For simplicity, let's kick this out of scope for here, and open a new issue in our `internal-analytics` repo instead to track this as follow-up work: https://github.com/dbt-labs/internal-analytics/issues/1402
