### ISSUE TITLE
[CT-1368] New tracking event: Project ID

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#6098]
We currently try to get the project ID for tracking purposes long before we actually load the project-- this causes a bunch of issues where we have to parse projects and such just to track the invocation.  Since there's no benefit to this in terms of our analytics, this approach has [been changed in this PR](https://github.com/dbt-labs/dbt-core/pull/5972). 

This ticket encompasses the work necessary to properly report the project ID at such a point that we actually load the project. This includes the work to update the internal analytics project to reflect the change in raw event data.

Specifically we need `project_id` as indicated [here](https://github.com/dbt-labs/dbt-core/blob/79f043a733becd41459711fc5261ab1088deaa58/core/dbt/tracking.py#L468).

**Comment by jtcohen6** [comment]
> This includes the work to update the internal analytics project to reflect the change in raw event data.

For simplicity, let's kick this out of scope for here, and open a new issue in our `internal-analytics` repo instead to track this as follow-up work: https://github.com/dbt-labs/internal-analytics/issues/1402

**Comment by iknox-fa** [comment]
@jtcohen6 I was working on this, and I realized we already have the project id as [part of the timing context](https://github.com/dbt-labs/internal-analytics/blob/f5407139dfc970beb960a4dd224874130d132054/models/staging/snowplow/raw/current/dbt/current_snowplow_load_all_timing.sql#L10).  Would it make sense to source it from there as opposed to invoicing another snowplow event?

**Comment by iknox-fa** [comment]
Ah Ok that makes sense.  A new event it is!

**Comment by jtcohen6** [comment]
Resolved by #7231!
