### ISSUE TITLE
[CT-1382] Seed csv cannot have SQL key words as headers

### ISSUE THREAD

**Issue by villar1** [dbt-labs/dbt-core#6116]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

csv contents

id,group
1,Group A
2,Group B

After running
```markdown
run dbt seed
```
It creates an error

```markdown
001003 (42000): SQL compilation error:
syntax error line 1 at position 64 unexpected 'group'.
```

### Expected Behavior

Expected for the code to compile and run

### Steps To Reproduce

Using Snowflake

Create /seed/test.csv file with the following contents
id,group
1,Group A
2,Group B

then run the command
```markdown
run dbt seed
```
 And then you get the error message about unexpected 'group'

### Environment

```markdown
- OS: macOS Monterey 12.7
- Python: 3.9.6
- dbt: 1.2.1
- snowflake plugin: 1.2.0
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Seems like the issue is with SQL key words as column names in seed files

**Comment by china-cse** [comment]
Hi @villar1 

you can utilize quote column feature in seeds.. which avoid this error. by default quote_columns is false and set to true and retry..

https://docs.getdbt.com/reference/resource-configs/quote_columns

**Comment by villar1** [comment]
Was looking for something like this but clearly used wrong keywords when searching. Thanks for the help and sorry for the incorrect bug report.
