### ISSUE TITLE
[CT-1384] temp_relation is not dropped from incremental materialization

### ISSUE THREAD

**Issue by aurany** [dbt-labs/dbt-core#6123]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

temp_relation is not removed in incremental model after dbt has finished OK.

below code should be added to the materialization somewhere?

`{% do to_drop.append(temp_relation) %}`

### Expected Behavior

temp_relation should be removed if no errors occur.

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: Mac
- Python: 3.9.14
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Adapter: dbt-ibmdb2

**Comment by jtcohen6** [comment]
@aurany I see you're using `dbt-ibmdb2`, and that you're also the maintainer! (https://github.com/aurany/dbt-ibmdb2)

Relevant spots in the adapter code:
- [`incremental.sql#L40-43`](https://github.com/aurany/dbt-ibmdb2/blob/1c171c78288a8e389fca4b05402d90e99b3498ad/dbt/include/ibmdb2/macros/materializations/incremental/incremental.sql#L40-L43)
- [`adapters.sql#L85`](https://github.com/aurany/dbt-ibmdb2/blob/1c171c78288a8e389fca4b05402d90e99b3498ad/dbt/include/ibmdb2/macros/adapters.sql#L85)

On most databases, temp tables are automatically (implicitly) dropped at the end of the session/transaction. So `get_create_table_as_sql(True, temp_relation, sql)` &rarr;  `create temp table {{ temp_relation }} as {{ sql }}` &rarr; the temp relation will be dropped implicitly, and doesn't need to be dropped explicitly.

It looks like DB2 supports temporary tables (https://www.ibm.com/docs/en/db2-for-zos/12?topic=tables-creation-temporary), but not `create temporary table ... as` (https://www.ibm.com/docs/en/i/7.1?topic=language-creating-table-using-as). In which case, the most expedient approach is to add some `drop` calls within the materialization code — and I see that's exactly what you've done!

In the meantime, I think it's reasonable for the default implementation in `dbt-core` to presume the existence of temporary tables, which live for the duration of the materialization, and are implicitly dropped as soon as it finishes. I'm going to close this issue.
