### ISSUE TITLE
[CT-1392] [Bug] dbt-core 1.3.0 compatibility issue with apache-airflow 2.2.2

### ISSUE THREAD

**Issue by driazanova** [dbt-labs/dbt-core#6128]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm having the compatibility issue for **dbt-core==1.3.0** with package **apache-airflow**. 
I have Airflow version 2.2.2.  
Tried to install with docker container and locally, same behaviour. 

### Expected Behavior

There is no issue with previous version of dbt, dbt-core==1.2.0. So I'm expecting to fix this dependencies with new one. 

### Steps To Reproduce

here it is list with my requirements:

- apache-airflow==2.2.2
- dbt-core==1.3.0

### Relevant log output

```shell
The conflict is caused by:
    apache-airflow 2.2.2 depends on markupsafe<2.0 and >=1.1.1
    jinja2 3.1.2 depends on MarkupSafe>=2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

### Environment

```markdown
- OS: macOS Monterey, Linux version 5.15.64-0-virt (buildozer@build-3-16-aarch64) (gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, GNU ld (GNU Binutils) 2.38) #1-Alpine SMP Mon, 05 Sep 2022 08:02:49 +0000
- Python: 3.9.6
- dbt: 1.3.0
- Airflow: 2.2.2
```

### Which database adapter are you using with dbt?

bigquery

**Comment by lostmygithubaccount** [comment]
hi @driazanova, thanks for reporting. I'm not sure we can do too much here given the conflict is a dependency with Jinja, which dbt relies on heavily

there are some newer versions of `apache-airflow` available, are you able to try with one of those?

**Comment by jtcohen6** [comment]
Older versions of `apache-airflow` are compatible with older versions of `dbt-core`. The latest version of `apache-airflow` is compatible with the latest version of `dbt-core`. That's the best we feel we can do right now. We want to keep the Jinja dependency tightly pinned, given how critical it is to end user code, to avoid unexpected breakages (as has happened in the past).

**Comment by driazanova** [comment]
Hi @jtcohen6 thank you for reply!

**Comment by AyadiGithub** [comment]
@BenoitLF @driazanova Similar concerns here and would appreciate any information, specifically which "newer" dbt versions are compatible with some of the newer MWAA Airflow versions (v2.4.3, ...)
