### ISSUE TITLE
[CT-1406] [Feature] Refine "Formatting" Events

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#6140]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The current set of event types contains a number of types which are heavily tied to log presentation and formatting, rather than conveying important information that could be used to automatically track state transitions during dbt's execution. We should try to improve the balance between providing an abstract event stream and the need to use the same stream to update the console during normal dbt CLI operation.

### Examples

The FirstRunResultError event is raised for the first line of a run result error. Subsequent lines of text associated with the same error are fired, one event per line, as separate AfterFirstRunResultError events. Consider combining all of these into a single event with a single message.

Several events include the words "Print" and/or "Line" implying that they are intended to write a log line (e.g. PrintStartLine, PrintSnapshotResultLine, StatsLine, EmptyLine, etc.) Consider renaming these classes so they sound more like events and less like output commands.

### Who will this benefit?

This change will benefit anyone who consumes the event log programmatically, and will improve code clarity.

**Comment by emmyoop** [comment]
This was done as part of other work.  Will schedule time to do a final pass over names of logs.
