### ISSUE TITLE
[CT-1407] [Feature] Scrub Secrets from Protobuf Messages

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#6141]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

During the spike on protobuf logging we prepared a prototype (https://github.com/dbt-labs/dbt-core/pull/6138), but the existing mechanism for wiping secrets out of the log text was not workable, since the protobuf messages are not converted to a text format. Implement a method for scrubbing secrets from events *before* they are logged, regardless of the way they are logged.

**Comment by emmyoop** [comment]
Let's find the logs this may apply to as a first step.  Then come together again to discuss the best way to solve this.  Keep scrubbing everything or scrub specified things?
