### ISSUE TITLE
[CT-1411] [Feature] Support Python 3.11

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#6147]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Support Python 3.11.x in dbt Core and adapters:
- https://github.com/dbt-labs/dbt-snowflake/issues/331
- https://github.com/dbt-labs/dbt-bigquery/issues/398
- https://github.com/dbt-labs/dbt-redshift/issues/225
- https://github.com/dbt-labs/dbt-spark/issues/524

### Who will this benefit?

Folks using the most recent release of Python

### Are you interested in contributing this feature?

Will mark as a "good first issue" and let someone else take a shot at this

### Last time
It looks like this work was split across multiple PRs last time, but it would be nice to have a single PR this time:
1. https://github.com/dbt-labs/dbt-core/pull/4866/files
1. https://github.com/dbt-labs/dbt-core/pull/5025/files

### How to implement

Add 3.11 (and 3.10 when it is missing) to these locations:
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/core/setup.py#L82-L84
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/tests/adapter/setup.py#L53-L54
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/plugins/postgres/setup.py#L84-L86
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/tox.ini#L5
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/tox.ini#L17
1. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/.github/workflows/main.yml#L74
2. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/.github/workflows/main.yml#L119
3. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/Dockerfile.test#L46-L51
4. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/CONTRIBUTING.md?plain=1#L59
5. https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/CONTRIBUTING.md?plain=1#L163
1. Any other relevant file I may have missed in the two pull requests from last time (when we added Python 3.10)

**Comment by jtcohen6** [comment]
https://docs.python.org/3.11/whatsnew/3.11.html#faster-cpython

> CPython 3.11 is on average [25% faster](https://github.com/faster-cpython/ideas#published-results) than CPython 3.10 when measured with the [pyperformance](https://github.com/python/pyperformance) benchmark suite, and compiled with GCC on Ubuntu Linux. Depending on your workload, the speedup could be up to 10-60% faster.

It took a teensy bit of finagling (https://github.com/dbt-labs/dbt-core/commit/48e6f96b3344f35dc2a3e4646898c89d63f8ae20), but I was able to experiment running `dbt-core` + `dbt-postgres` with Python 3.11.0. Running on my M1 locally, **a full parse is ~3x faster** (just over 9 seconds, instead of just under 27 seconds) for our internal analytics project (almost 2k files, 700+ models).

**Comment by leahwicz** [comment]
We should open up issues for each adapter repo as well

**Comment by dbeatty10** [comment]
> We should open up issues for each adapter repo as well

✅ done!

**Comment by Fleid** [comment]
@leahwicz @nathaniel-may @jtcohen6  I'm going to assign to the adapter team unless there's a huge outcry. We have to do the 4 adapters + Postgres anyway so...

**Comment by leahwicz** [comment]
@Fleid if Adapters wants to do this, that is fine with me. #6326 has already been put up as a draft PR and but still needs works obviously. I created a Slack thread in #dev-core to consolidate knowledge on who has looked at what so far with Python 3.11 and then we can have an Adapters person pick it up from there

**Comment by jelstongreen** [comment]
Folks the Dockerfile is currently pinned to 3.10 due to bug - any plans to upgrade to 3.11?

**Comment by dbeatty10** [comment]
Hey @jelstongreen !

Just replied to you here: https://github.com/dbt-labs/dbt-core/issues/9491#issuecomment-1917712388
