### ISSUE TITLE
[CT-1416] [Bug] GitHub Actions: Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by kevinneville** [dbt-labs/dbt-core#6153]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

GitHub Actions: Deprecating save-state and set-output commands, these should be replaced with the proposed solution.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

### Expected Behavior

We should not see the warnings.

### Steps To Reproduce

Run all GH checks.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by leahwicz** [comment]
Thanks @kevinneville for the issue!

@emmyoop we can use this for tracking for this repo since I don't see an issue here yet

**Comment by leahwicz** [comment]
Oh nvm @kevinneville I see your PR already!!!
https://github.com/dbt-labs/dbt-core/pull/6152

**Comment by kevinneville** [comment]
> Oh nvm @kevinneville I see your PR already!!!
> 
> https://github.com/dbt-labs/dbt-core/pull/6152
> 
> 

Sorry, not sure if I missed something in the contribution guide. My first PR, I tried to follow it the best I could.

**Comment by leahwicz** [comment]
@kevinneville oh no problem! 

In the top of the PR description, you will see the "resolve #" line. If you add the issue number there, it links the issue and the PR so its easy to see the 2 are connected. I edited your PR description to have that so the link is there now
