### ISSUE TITLE
[CT-1418] [Bug] CLI argument `--profile` ignored in `dbt init`

### ISSUE THREAD

**Issue by scheah92** [dbt-labs/dbt-core#6154]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

According to `dbt init --help`, the `--profile` option lets the user load an existing profile to use with a new project. However, that option currently does nothing when you call it with `dbt init`. 

Example:
```
dbt init --profile default proj1
```

Result:
proj1 created with `proj1/dbt_project.yml` showing `profile: 'proj1'`. `~/.dbt/profiles.yml` shows a new profile `proj1` created with placeholders. **Note**: if a profile named `proj1` already exists, dbt *still* creates another profile named `proj1` again.

In contrast, calling `dbt run --profile default` actually does make the project use the profile `default`, so the `--profile` argument does work elsewhere at least. 

### Expected Behavior

proj1 created with `proj1/dbt_project.yml` showing `profile: 'default'`. `~/.dbt/profiles.yml` should not show any new profile created.

### Steps To Reproduce

1. Create new project directory to store project in
2. Open `~/.dbt/profiles.yml` and create a new profile `default`.
3. Run `dbt init --profile default proj1`
4. `cd` into `/proj1` and open `dbt_project.yml`. The `profile` will be set to `proj1` instead of `default`.
5. Check `~/.dbt/profiles.yml` again and see that dbt has created a new blank `proj1` profile to go with the new project, instead of using the existing `default` profile.

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- Python: 3.10.6
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

postgres

**Comment by lostmygithubaccount** [comment]
hi @scheah92, thanks for reporting, I am able to reproduce this. my first thought was the order of arguments, so perhaps `dbt init proj1 --profile default` would work, but that behaves the same

we are reworking our CLI commands as part of v1.4 and v1.5 and we can likely pick this up for those releases

**Comment by scheah92** [comment]
Hi @lostmygithubaccount, if you guys are reworking CLI commands, you might be interested to know that `--profile` is not the only CLI argument that has issues. In my testing, I've found that `--target` and `--vars` also do not appear to have any effect. I suspect these don't work because they rely on `--profile` in the first place.

**Comment by iknox-fa** [comment]
Good place to start looking at this:
https://github.com/dbt-labs/dbt-core/blob/edb5634b9ad20e84c1234bcc41f4039639692e18/core/dbt/task/init.py#L247

**Comment by ezraerb** [comment]
The code shows that the profile argument is simply ignored:
`
        with open("dbt_project.yml", "r+") as f:
            content = f"{f.read()}".format(project_name=project_name, profile_name=project_name)
            f.seek(0)
            f.write(content)
            f.truncate()
`

**Comment by alzaar** [comment]
Would it be possible, if I pick this up ?

**Comment by ezraerb** [comment]
I submitted a PR for it: https://github.com/dbt-labs/dbt-core/pull/7450
It has not been reviewed yet. Given the reorg that dbt labs just had, I suspect that will take a while.

**Comment by lostmygithubaccount** [comment]
glhf

**Comment by alzaar** [comment]
Cool, thanks!
