### ISSUE TITLE
[CT-1420] [Bug] Ref creates a new relation every time, meaning that model data (such as `type` cannot be inherited)

### ISSUE THREAD

**Issue by jpmmcneill** [dbt-labs/dbt-core#6155]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

At the moment, `ref` creates a new relation object each time rather than checking if something already exists.

Context for the problem this is causing is in slack:

https://getdbt.slack.com/archives/C50NEBJGG/p1666805781564349

This is something that I've run into when developing the duckdb adapter.

https://github.com/jwills/dbt-duckdb/issues/19#issuecomment-1292375802

The relevant code is: https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/core/dbt/context/providers.py#L463

which uses:

https://github.com/dbt-labs/dbt-core/blob/19167842873ea882c2dbb70aeb525953812d8ef3/core/dbt/adapters/base/relation.py#L243

### Expected Behavior

If model `x` has a materialization of `foo` (and the returned relation from the materialization sets this up correctly) i'd expect `ref('x')` to be a relation of type `foo`, up to the enum being supported under the hood etc.

### Steps To Reproduce

Make a relation (via a model) that has a type that is not `None`, and then ref that model. A relation of type none is returned, with the same name etc

**Comment by jtcohen6** [comment]
@jpmmcneill Thanks for opening!

The change you propose in #6175 makes sense to me. In the past, I think I've written extra code to achieve the same effect:
```
{% set ref_model = ref('some_model') %}
{% set with_type = load_relation() or ref_model %}
```
Probably better if this is something dbt does natively, and best yet if it can be a cache lookup!

**Comment by jtcohen6** [comment]
Left a lengthier comment in https://github.com/dbt-labs/dbt-core/pull/6175#discussion_r1013259582. I'm come around to thinking that this isn't actually a `bug`! If we close the issue, we should definitely update the documentation:
- https://docs.getdbt.com/reference/dbt-jinja-functions/ref
- https://docs.getdbt.com/reference/dbt-classes#relation

**Comment by jpmmcneill** [comment]
Not complete but closing because this isn't really a bug as @jtcohen6 said + the use case I was looking at this for was solved a different way :duck:
