### ISSUE TITLE
[CT-1440] [Bug] Connection reused event is not shown

### ISSUE THREAD

**Issue by JCZuurmond** [dbt-labs/dbt-core#6168]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The connection reused event does not show in the logs: `Re-using an available connection from the pool (formerly {self.conn_name})`

I think this is because [the connection reused event](https://github.com/dbt-labs/dbt-core/blob/9b84b6e2e87f4e6ada4ccc343906749ba013b138/core/dbt/adapters/base/connections.py#L175) is never fired.

I am not completely sure if I am reading the code below correctly, but I think the `ConnectionReused` is misplaced and maybe never reached:

``` python
        conn = self.get_if_exists()
        if conn is None:
            conn = Connection(
                type=Identifier(self.TYPE),
                name=None,
                state=ConnectionState.INIT,
                transaction_open=False,
                handle=None,
                credentials=self.profile.credentials,
            )
            self.set_thread_connection(conn)

        if conn.name == conn_name and conn.state == "open":
            return conn

        fire_event(NewConnection(conn_name=conn_name, conn_type=self.TYPE))

        if conn.state == "open":
            fire_event(ConnectionReused(conn_name=conn_name))
        else:
            conn.handle = LazyHandle(self.open)

        conn.name = conn_name
        return conn
```

I read the following
1. The code fetches an existing connection
2. If no connection exists, it creates a new one and adds the connection to be used later
3. If the connection has the same name and is open, the connection is returned immediately
4. If not, a new connection event is sent
5. Then if the connection is open, a connection reused event is sent
6. Else lazy handler is set
7. Connection is returned

I do not understand why the connection reused event might be sent right after the new connection event is sent. 

Also, I do not understand when this `conn.name == conn_name` evaluates to `False`. When is a different connection name used within the same thread?

### Expected Behavior

``` python
        conn = self.get_if_exists()
        if conn is None:
            conn = Connection(
                type=Identifier(self.TYPE),
                name=None,
                state=ConnectionState.INIT,
                transaction_open=False,
                handle=None,
                credentials=self.profile.credentials,
            )
            self.set_thread_connection(conn)

        if conn.state == ConnectionState.OPEN.
            fire_event(ConnectionReused(conn_name=conn_name))
        else:
            fire_event(NewConnection(conn_name=conn_name, conn_type=self.TYPE))
            conn.handle = LazyHandle(self.open)
            conn.name = conn_name
        return conn
```

### Steps To Reproduce

NA

### Relevant log output

```shell
NA
```

### Environment

```markdown
- OS: NA
- Python: NA
- dbt: v.1.3.0
```

**Comment by lostmygithubaccount** [comment]
thanks @JCZuurmond! your read on this makes sense to me

**Comment by gshank** [comment]
There is a connection per thread. If a connection already exists, it is reused and named with the new connection name (usually the unique_id of the node).  I think it will be more clear in the modified ConnectionReused message.
