### ISSUE TITLE
[CT-1451] The dbt graph should always display source of model to macro lineage

### ISSUE THREAD

**Issue by bashyroger** [dbt-labs/dbt-core#6182]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We have several macros that use various dbt **models** or **sources** as input. As usual they are stored in the _macros_ folder.
We _know_ that you can _force_ dependencies being displayed using **depends_on**. 
However, this **ONLY works** when the macros folder is added to the models directory array in sources.yml. We do not want to do this, as dbt run commands using upstream dependencies then start executing macros as if they are models, which we obviously not want.

Instead, the lineage DAG should simply display dependencies between resources and macros as to enable refactoring

### Describe alternatives you've considered

tested adding the **macros** folder to the models directory in sources.yml. But this had the adverse effects described above

### Who will this benefit?

Everyone using macros as lot that use a lot of other dbt objects and want to keep overview on what is using what

**Comment by dbeatty10** [comment]
Thanks for opening @bashyroger !

Is your primary goal to determine which models use a particular macro? e.g., be able to determine the affected models if you refactor a particular macro?

Could you share a concrete example of using a dbt model (or source) as input to a macro? [`dbt_utils.star()`](https://github.com/dbt-labs/dbt-utils/blob/6a5dd1eb97700301eaeba14c23c3682ceac9fb2b/README.md#star-source) is one macro that comes to mind, but it would be helpful to see one of your example use-cases.
