### ISSUE TITLE
[CT-1457] Move dbt-postgres into its own repository

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6189]
### Why

- Simplify our release process, which currently has to treat `dbt-postgres` as a special case
- Many of our [Postgres issues](https://github.com/dbt-labs/dbt-core/issues?q=is%3Aissue+is%3Aopen+label%3Apostgres) are quite specific to Postgres, in the same way that `dbt-snowflake` issues are quite specific to Snowflake
- Simplify our documentation, the way we talk about adapter plugins, ... It's sorta weird to have Postgres be the cohabitating adapter, when using dbt + Postgres (row-store db) is already a mild anti-pattern for analytics
- We have nothing against monorepo people, it's just not the pattern we've chosen for the `dbt-core` plugin ecosystem (a thing we want to expand!)

### Considerations

We can still install `dbt-postgres` for use in CI against `dbt-core`, and keep most of the test definitions located in the `dbt-core` repository.

Changes that must be coordinated across `dbt-core` and `dbt-postgres` will require two PRs. (This is already the case for our other adapter plugin repositories.) Note that this is _not_ true of changes that only require `default__` macros within the `dbt-core` global project — it's specifically true in cases where `dbt-postgres` requires some divergence from the implementation we want to use as default.

We do not actually make _that_ many changes to the `dbt-postgres` code (https://github.com/dbt-labs/dbt-core/commits/main/plugins/postgres). In the past year, there have been a handful of "core" changes where the separation of `dbt-postgres` would have added marginally more friction (but all of these already required multiple PRs across multiple adapter repos):
- **Cross-db utilities:** https://github.com/dbt-labs/dbt-core/pull/5298 / https://github.com/dbt-labs/dbt-core/pull/5838
- **Grants:** https://github.com/dbt-labs/dbt-core/pull/5369
- **Retries:** https://github.com/dbt-labs/dbt-core/pull/5432 / https://github.com/dbt-labs/dbt-core/pull/5503
- **Refactoring incremental strategies:** https://github.com/dbt-labs/dbt-core/pull/5359

### How hard would this be?

I don't think it would be very hard — we've done it three times before — but I'd be open to spiking it first if folks feel that's appropriate.

**Comment by jtcohen6** [comment]
We'd also want to move Postgres-specific tests to the new `dbt-postgres` repository: https://github.com/dbt-labs/dbt-core/tree/main/tests/functional/postgres

**Comment by mdemierre** [comment]
It seems like since the move started, the `dbt-postgres` Docker images are not being released anymore. Related to https://github.com/dbt-labs/dbt-core/issues/7149 maybe?
