### ISSUE TITLE
[CT-1463] What files need to be touched in adapters: Snowflake, Databricks?

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/dbt-core#6194]
**Success Criteria**
- [ ] Links to existing files that need to be updated
- [ ] Net new files and why it needs new files
- [ ] Potential "gotcha" implementations based on the above(think: if we update this file here, we have to update 100 files downstream)
- [ ] pseudo-code snippets on initial approach for the above to make this functionality work

**Comment by sungchun12** [comment]
@jonathanneo

**Comment by sungchun12** [comment]
Due Date: 11/14

**Comment by sungchun12** [comment]
Example of Snowflake Macro Code: https://www.loom.com/share/14020499f5f646b6bc80c909716850fd

**Comment by sungchun12** [comment]
FYI for snowflake to make your journey faster: https://github.com/dbt-labs/dbt-core/pull/6271#issuecomment-1320598319

**Comment by b-per** [comment]
Based on what I understand so far of the feature:

### For table materialization support
- each adapter needs to define a `<adapter>__columns_spec_ddl` macro if the default one is not using the correct syntax.
  - TODO: we need to `dispatch` `columns_spec_ddl` in `dbt-core` to allow other adapters to overwrite
  - TODO: we need to update the docs somewhere to mention that support for constraints will require this macro working
- each adapter needs to update its `<adapter>__create_table_as(temporary, relation, sql)`
  - [BigQuery](https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/include/bigquery/macros/adapters.sql) `bigquery__create_table_as`
  - [Databricks](https://github.dev/databricks/dbt-databricks/blob/main/dbt/include/databricks/macros/materializations/table.sql) `databricks__create_table_as`
  - [RedShift](https://github.com/dbt-labs/dbt-redshift/blob/main/dbt/include/redshift/macros/adapters.sql) `redshift__create_table_as`
  - [Snowflake](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/adapters.sql) `snowflake__create_table_as`
  - Spark (do we focus on it?)

I will dive more into the specific syntax for the constraints and `check` for each of those adapters.

My question about the approach we are taking is that whether we want to support "partial constraints" on columns, e.g. providing the inputs for some columns, but not all, and if so, we will need a mechanism to mention if the `constraints_enabled` is full or partial (I believe that in today's code, we need to define all columns)

### For incremental models
This might be more complex and I will need to dig more into it. Will it be in scope of v1?

### For snapshots
This might be more complex and I will need to dig more into it. Will it be in scope of v1?

**Comment by sungchun12** [comment]
@b-per Great research so far!

Your TODOs are solid and agreed on `dispatch` and figuring out what an elegant override macro experience looks like, especially for future adapters.

Each `<adapter>__create_table_as(temporary, relation, sql)` should be as simple as injecting a single line like: `{{ get_columns_spec_ddl() }}` based on `<adapter>__columns_spec_ddl`. Example below.

For "partial constraints", I recommend all or nothing constraints. Especially since this will be a building block to multi-project experiences, people need whole promises on the data they're `ref`ing, not half-hearted ones. 

Incremental and Snapshot materializations are NOT in scope for v1. And that's okay because going forward, those simply need to manipulate the `constraints`, `data_type`, and `check` configs in an adapter-specific macro. 

```sql


{% macro snowflake__create_table_as(temporary, relation, compiled_code, language='sql') -%}
  {%- if language == 'sql' -%}
    {%- set transient = config.get('transient', default=true) -%}
    {%- set cluster_by_keys = config.get('cluster_by', default=none) -%}
    {%- set enable_automatic_clustering = config.get('automatic_clustering', default=false) -%}
    {%- set copy_grants = config.get('copy_grants', default=false) -%}

    {%- if cluster_by_keys is not none and cluster_by_keys is string -%}
      {%- set cluster_by_keys = [cluster_by_keys] -%}
    {%- endif -%}
    {%- if cluster_by_keys is not none -%}
      {%- set cluster_by_string = cluster_by_keys|join(", ")-%}
    {% else %}
      {%- set cluster_by_string = none -%}
    {%- endif -%}
    {%- set sql_header = config.get('sql_header', none) -%}

    {# # get the list of columns in my schema file#}
    {# {%- set user_provided_columns = model['columns'] -%} #}

    {{ sql_header if sql_header is not none }}

        create or replace {% if temporary -%}
          temporary
        {%- elif transient -%}
          transient
        {%- endif %} table {{ relation }} {% if copy_grants and not temporary -%} copy grants {%- endif %} 
        {# loop through user_provided_columns to create DDL with data types and constraints #}
        {{ get_columns_spec_ddl() }}
        {# {% if config.get('constraints_enabled', False) %}
          (
          {% for i in user_provided_columns %}
            {% set col = user_provided_columns[i] %}
            {% set constraints = col['constraints'] %}
            {{ col['name'] }} {{ col['data_type'] }} {% for x in constraints %} {{ x or "" }} {% endfor %} {{ "," if not loop.last }}
          {% endfor %}
        )
        {% endif %} #}
        as
        (
          {%- if cluster_by_string is not none -%}
            select * from(
              {{ compiled_code }}
              ) order by ({{ cluster_by_string }})
          {%- else -%}
            {{ compiled_code }}
          {%- endif %}
        );
      {% if cluster_by_string is not none and not temporary -%}
        alter table {{relation}} cluster by ({{cluster_by_string}});
      {%- endif -%}
      {% if enable_automatic_clustering and cluster_by_string is not none and not temporary  -%}
        alter table {{relation}} resume recluster;
      {%- endif -%}

  {%- elif language == 'python' -%}
    {{ py_write_table(compiled_code=compiled_code, target_relation=relation, temporary=temporary) }}
  {%- else -%}
      {% do exceptions.raise_compiler_error("snowflake__create_table_as macro didn't get supported language, it got %s" % language) %}
  {%- endif -%}

{% endmacro %}
```
