### ISSUE TITLE
[CT-1474] [Feature] Let users add fields to strucutred logs

### ISSUE THREAD

**Issue by tmastny** [dbt-labs/dbt-core#6216]
### Is this your first time submitting a feature request?

No, I have made other feature requests.
- [x] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

At the moment, structured logs have a predefined set of JSON properties ([docs](https://docs.getdbt.com/reference/events-logging#structured-logging)). 

I would like to to be able to add fields to the structured logs to consume in downstream systems.

This ask was inspired by the [query-comment marco](https://docs.getdbt.com/reference/project-configs/query-comment#advanced-use-a-macro-to-generate-a-comment). By customizing the macro, I can "log" exactly the details I need, removing info I don't need and adding info I do need.

### Describe alternatives you've considered

Here's my work-around to augment logs with additional data. 

Instead of consuming logs as they are generated to stdout, I write the logs to file. Then I execute a Python script that adds data from `manifest.json` into the logs file (by `data.node_info.unique_id` in logs) and then re-emits the logs.

### Who will this benefit?

Use-case: add node tags to the `data.node_info` property in logs. By tagging a node with team ownership, the log consumer can alert different teams based on the failures.

Example:
```
{"level": "error", "data": { "node_info": {"tags": ["finance_team"], ...}, ...}, ...}
```
The consumer would see the `"level": "error"` and prepare to alert. Then the consumer would see that the node is tagged with `"finance_team"`, so instead of sending a general alert, a more narrow, finance alert is sent.

### Are you interested in contributing this feature?

Yes, I could help if we are interested in the feature.

**Comment by jtcohen6** [comment]
@tmastny Thanks for opening! & long time no see :)

First off, you have good timing. We're doing work on structured logging right now, and one piece of it is ensuring that the `node_info` dict is available on as many relevant events as possible (at parity with the old logging system: https://github.com/dbt-labs/dbt-core/issues/6222).

Two thoughts:
1. I don't think we should put the full `node` object (manifest entry) on every single node-related. The motivation for `node_info` is, this should be enough information to answer 80-90% of real-ish-time questions you could ask about _dbt models running right now_. For everything else, including retrospective / longitudinal analysis, a join to the full manifest entry feels appropriate.
2. I don't think we'll be able to support this in the same sort of _totally flexible_ mechanism as the `query_comment` macro. We're doing a lot of work to make our events/log messages strongly typed, and that requires us to be able to say in advance the exact structure of their contents.

### Proposal

So: **What do you think about using the `meta` field for this?** That is: always `meta`, and only `meta`.

The big idea with `meta` is:
- it's a dictionary that can contain whatever key-value pairs you want
- it has no functional purpose within dbt — you put things in there, and they show up
- it's for metadata! and logs are metadata :)

Not too dissimilar from the ability to annotate all log events with env/run-level metadata (https://github.com/dbt-labs/dbt-core/issues/5228). It's explicit, and it's explicitly _not used_ for any actual dbt core functionality.

How is `meta` different from `tags`? Well... `tags` are a teensy bit more special, and originally designed for node selection. (You can use `config.meta.key:value` now for node selection, too, but that's not its original intent.) I'd vote for one or the other, and my vote goes to `meta`.

### Implementation

As far as implementing this, I think it could be a fairly simple change in two places. First, the proto type:
https://github.com/dbt-labs/dbt-core/blob/6c76137da4e72bbcad6e7789a78c31f1bf5cffac/core/dbt/events/types.proto#L27-L37
Adding something like: `map<string, string> adapter_response = 9;`

And then the Python code to use it:
https://github.com/dbt-labs/dbt-core/blob/6c76137da4e72bbcad6e7789a78c31f1bf5cffac/core/dbt/contracts/graph/parsed.py#L186-L203

Adding something like: `"meta": getattr(self, "path", {}),`
