### ISSUE TITLE
[CT-1483] [Bug] Macros whose names contain "materialization" treated as materialization macros by compiler, fail with "no supported_languages..."

### ISSUE THREAD

**Issue by CraftyIvan** [dbt-labs/dbt-core#6231]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After upgrading to dbt 1.3.0 which adds `supported_languages` for materialization macros (#5695), all standard macros whose name has `"materlialization"` as a substring prevent compilation.

A project I'm contributing to contains a macro named `get_materialization` (it defaults model materializations to view under certain conditions). The parser seems to treat it as a materialization macro for that, even though it's not (location of this in dbt-core code referenced below in "Additional Context").

So when running `dbt run` or `dbt compile` I get the following error:
```
No supported_languages found in materialization macro <project_prefix>__get_materialization
```

### Expected Behavior

Only materialization macros are able to trigger this compilation error when not declaring supported languages.

A regular macro (`{% macro_name([params]) %}`) with the substring `"materialization"` in its name is not considered a materialization macro (`{% materialization [materialization_name] ... %}`) and does not trigger the compilation error.

### Steps To Reproduce

1. Create a new regular macro and have its name contain the substring `"materialization"`, e.g. `get_materialization` or `print_materialization`.
2. Run `dbt compile`.

### Environment

```markdown
- OS: macOS 12.5.1
- Python: 3.8.15
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

The `parse_unparsed_macros` method performs this "generalization":
https://github.com/dbt-labs/dbt-core/blob/f02243506df2a9b6851abe6bcfe10af8808d41cc/core/dbt/parser/macros.py#L88

**Comment by dbeatty10** [comment]
Thanks for surfacing this @CraftyIvan !

Agreed that this is a surprising result when there is a non-materialization macro that happens to have "materialization" within the name.

Our next step will be to determine what our options are for changing the implementation.

**Comment by jtcohen6** [comment]
@dbeatty10 Your proposal makes sense to me! Much better than what I was going to say.

I'm going to tag this one for `Team:Language`, since that's whose surface area this falls under. Stu was original implementer here, so still very happy to hear from him too.

**Comment by mjedrzejczak-wh** [comment]
please reopen this ticket, now we have version 1.5.2 and it is still not fixed :(

**Comment by jtcohen6** [comment]
Given how straightforward Doug's proposed fix is, I think this could be a community contribution.

@mjedrzejczak-wh Any interest in giving it a spin?

**Comment by mjedrzejczak-wh** [comment]
@jtcohen6 unfortunately we have in our projects such macros, which block us effectively from upgrade

and I would prefer not to fix this myself - I do not know dbt internals so well

**Comment by ArunT317** [comment]
@jtcohen6 - I am also facing the same issue trying to upgrade.

**Comment by ArunT317** [comment]
@jtcohen6 @mjedrzejczak-wh @dbeatty10 @CraftyIvan @joevandyk 

Just FYI, I too faced the same error while trying to upgrade dbt.

I did try the code change suggested by @dbeatty10 locally in my python virtual environment and it is working as expected. I am facing some other project specific errors but thought to share this here so that we are all aware that the idea proposed above is fixing the issue.

**Comment by mjedrzejczak-wh** [comment]
@fconrady it is already fixed and closed, update your dbt :)
