### ISSUE TITLE
[CT-1489] --defer does not seem to select correct nodes if the profile name is 'ci'

### ISSUE THREAD

**Issue by rudeb0y** [dbt-labs/dbt-core#6235]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I was running this command:
`dbt build -s state:modified+ --target ci --defer --state <my_state_location>`

`dbt build -s state:modified+ --target dev --defer --state <my_state_location>`

Each time it would select different number of nodes. State was same, only thing that was changing was the target.

I duplicated the dev target as ci.. and still the same thing.

Renamed ci to something else (cicd, mi, CI) - and I started to get the same number of nodes as dev!

This is really weird. In my case 'ci' would get 124 nodes based on my project whereas it should only be returning 7 (as it does for any other profile name)

### Expected Behavior

Expect node selection to be consistent regardless of the profile name

### Steps To Reproduce

Create a profile ci

target this profile when building/running dbt with the `--defer` flag and a previous state file (e.g. `dbt build -s state:modified+ --defer --state <the_state> --target ci`)

See if the nodes selected is the same as another profile name (e.g. rename profile to dev and target that)

### Environment

```markdown
- OS: mac
- Python: 3.10.7
- dbt: 1.3.0
```

**Comment by rudeb0y** [comment]
I believe the problem was that there was logic in the project that changed things if the target is ci :@

**Comment by jtcohen6** [comment]
Thanks for the follow-up comment @rudeb0y! Sounds like some conditional config that led dbt to reasonably believe a number of models really had changed. More on "false positives" here: https://docs.getdbt.com/reference/node-selection/state-comparison-caveats#false-positives
