### ISSUE TITLE
[CT-1494] [Bug] DBT run on incremental wipes out default privilege 

### ISSUE THREAD

**Issue by JordanZimmitti** [dbt-labs/dbt-core#6238]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In Postgres, we use '[alter default privileges](https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html)' to give a set of pre-defined grants to newly created tables. This works fine for _tables_ and _views_ in DBT because a drop and create occurs which reapplies the default privilege grants on each new DBT run.

Because an incremental is not re-created on a DBT run when the [apply_grants](https://github.com/dbt-labs/dbt-core/blob/c25260e5dd2afa237a30db115605ece9629443d1/core/dbt/include/global_project/macros/adapters/apply_grants.sql#L139) macro runs it wipes out the default privilege grants.

### Expected Behavior

After reading through the source code I figured out that the problem statement is with the [should_revoke](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql#L70) macro. Since **should_revoke** is set to true for incremental inserts and the table is not recreated, the default privilege grants never get reapplied.

It would be great if there was an option to only perform a revoke on grants when a _full-refresh_  is performed that way when they are revoked any default privilege grants applied won't be deleted

So maybe an `"is_revoke_only_on_refresh": True` option added to the incremental config that allows for the following functionality:

- Grants will stay the same and can be added to on normal incremental runs
- Grants can be removed only on full-refresh runs

### Steps To Reproduce

1. Have a Postgres user account with 'alter default privileges' setup
2. Perform a dbt run on an incremental ('alter default privileges' are given correctly)
3. Perform a dbt run on the same existing incremental ('alter default privileges' are lost)

### Environment

```markdown
- OS: Debian bullseye
- Python: 3.9.12
- dbt: 1.2.1
```

### Which database adapter are you using with dbt?

postgres

**Comment by ekitzing** [comment]
@jtcohen6 sorry to post on this closed thread. I have tried to get an answer in the [dbt Slack workspace](https://getdbt.slack.com/archives/C0172G2E273/p1731489993319939), but without success, so trying it here.

I have tried the suggested approach Nr. 2 to disable the `grants` config for my incremental models, but it doesn't work in my dbt project. I tested the following 2 ways, but none of them seem to work:

- adding grants config to the yaml property file:
```
models:
  - name: my_model
    config:
      grants: {}
```
- or adding `grants={}` to the config block of the model
```
{{
    config(
        materialized="incremental",
        unique_key="surrogate_key",
        incremental_strategy="delete+insert",
        grants={}
    )
}}
```

Could you please specify how the `grants: {}`, described in your message, should be applied?
Thanks a lot
