### ISSUE TITLE
[CT-1495] [Feature] Snowflake query tags and warehouse size during test exection

### ISSUE THREAD

**Issue by calleo** [dbt-labs/dbt-core#6239]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We are using Snowflake specific features in DBT to set the query tags and warehouse used during model building. Heavy models can run on larger warehouse and query tags allows us to track performance and cost on model level.

Today I noticed that these settings (tags and warehouse size) is not applied when `dbt test` is executed. The trigger was me noticing certain tests taking a lot of time to execute. Tags would make this visible in our monitoring and a configurable warehouse would allow us to cut test time by running them on a larger warehouse.

I was surprised that the model configuration did not apply to the tests of that model.

### Who will this benefit?

DBT customers using Snowflake

### Are you interested in contributing this feature?

Yes

**Comment by jtcohen6** [comment]
@calleo Thanks for opening! Sorry for the time & confusion spent figuring out what was going on.

What you're asking for is totally reasonable, and already covered in this older issue: https://github.com/dbt-labs/dbt-snowflake/issues/23

Good news: `query_tag` is supported for tests in `dbt-snowflake` as of v1.3! https://github.com/dbt-labs/dbt-snowflake/pull/210

As far as supporting `snowflake_warehouse`, I think the next step is laid out in this issue: https://github.com/dbt-labs/dbt-core/issues/5766

I'm going to close this in the meantime, as a duplicate / partially resolved.

**Comment by calleo** [comment]
Thank you!
