### ISSUE TITLE
[CT-1500] [Feature] Append mode for persist_docs

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#6244]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The current persist docs functionality adds whatever we have in our schema yml files TO the target relation & columns. 

Let's say we had an existing table `foo` in our datawarehouse already with the description `This is a table.` (pre our dbt journey) - it would be cool if we could do something:

```yml
# dbt_project.yml
+persist_docs:
  relation: true
  append: true

# models/schema.yml
models:
  - name: foo
    description: It sure is.
```

Which results in the `foo` table description be:

```
This is a table. It sure is.
                 ^^^^^^^^^^^ Appended dbt description.
```

### Describe alternatives you've considered

I think one could reasonable achieve this by generating a run-operation or on-run-end hook that:
1. Retrieve the dbt graph (https://docs.getdbt.com/reference/dbt-jinja-functions/graph) which contains all the node's descriptions + it's column descriptions.
2. Retrieve the relation + column descriptions via a SQL query that does a lookup of the node.
3. Append string (2) and (3) for each relation + column.
4. Run `alter table` / `alter column` queries (using the right DDL for the specified adapter) using (3).

But just specifying `append: true` would be much less work to do.

Of course this is also problematic for tables since they are dropped and re-created - now we have to actually store the descriptions (if they exists) before we do our `ctas`.

### Who will this benefit?

Users with pre-existing non-dbt mechanisms of writing table/column descriptions that want to also use dbt to append to the existing descriptions. Probably most useful for sources and incremental models - which are things that will generally be brought into the dbt-world without a "drop & recreate".

### Are you interested in contributing this feature?

Yes

**Comment by jtcohen6** [comment]
@jeremyyeo Thanks for the clear-write up! The example gave me a chuckle, it sure did :)

I'm still inclined to stick to the answer I gave in an older related issue, https://github.com/dbt-labs/dbt-core/issues/4226#issuecomment-971447928:

> I don't feel great about officially decoupling running a model and persisting its descriptions as database comments.

dbt wants to fully manage an object, or not at all. The clarity of that abstraction gets us a lot! Where does this table come from? Whence its properties, its comments, every column it contains? The answer should be either 100% dbt, or zero.

As in that issue, I do think the right building blocks are in place to code up a custom macro that would handle this. Until/unless there's a lot of demonstrated need for this functionality, I'm inclined to leave it as an exercise for the end user. For now, the use cases seem to be fairly ad hoc and live along the edges.

You (or anyone else) should feel free to say that you big-time disagree. If so, I'll reopen, and we can keep discussing!
