### ISSUE TITLE
[CT-1502] [Feature] Add md5 function to the jinja context

### ISSUE THREAD

**Issue by haritamar** [dbt-labs/dbt-core#6246]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like to add a simple md5 function to the base context, so it can be used in macros / models / tests.

### Who will this benefit?

The main use case we have in mind is performance-related - we have a relatively slow computation that we want to avoid repeating on every run.
In order to do this we want to be able to compute an MD5 locally and compare it to an MD5 stored in the database, and only perform the computation if the values are different.

### Are you interested in contributing this feature?

Yes, I will submit a PR following the submission of this issue

**Comment by jtcohen6** [comment]
@haritamar Thanks for opening!

I'm not opposed to an `md5` function in the Jinja context. There's at least one time I remember working around _not_ having this context method, to ensure globally unique auto-generated names for Postgres indexes:

https://github.com/dbt-labs/dbt-core/blob/39c5c42215b4d6751e9644324040a1c716742224/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L20

https://github.com/dbt-labs/dbt-core/blob/39c5c42215b4d6751e9644324040a1c716742224/plugins/postgres/dbt/adapters/postgres/impl.py#L25-L33

That said, I found your stated use case pretty interesting:

> In order to do this we want to be able to compute an MD5 locally and compare it to an MD5 stored in the database, and only perform the computation if the values are different.

Could you say more? Are you storing a hash of model contents, a bookmark of the newest record of data, ...?

I'd think you _could_ accomplish this with just SQL, and thereby push as much of the compute as possible to the underlying data platform:
```sql
{% if execute %}
    {% set comparison_sql %}
    
    select precomputed_hash != md5('{{ whatever_jinja_you_need_to_md5 }}') as has_changed
    from table_with_precomputed_hash
    
    {% endset %}
    {% set has_changed = run_query(comparison_sql).columns[0].values()[0] %}
    {% if has_changed %}
        ... do your thing ...
    {% endif %}
{% endif %}
```

**Comment by haritamar** [comment]
Hi @jtcohen6 - thank you for the quick reply here!

Sure thing, I'll be happy to add more context about our use case.
In our package [dbt-data-reliability](https://github.com/elementary-data/dbt-data-reliability), we have an on-run-end hook that uploads various DBT artifacts to the DB (information about models, tests, etc that we extract from the graph).

So for this purpose we'd actually like to have a **local** md5 implementation that we can run on the metadata we collected and compare it against the stored metadata.
That can save us the need from re-uploading the metadata on every dbt run. Using a hash function in the DB will not be possible without fully uploading the new metadata - which defeats the purpose :)
I believe it could be relevant for other similar computations that are done locally in Jinja - whether on the graph or on other Jinja variables available in the context.

Got your point about the function name - do you think renaming it to `local_md5` or something similar will be good enough?

Please let me know if I can add any additional context.
Thanks!

**Comment by jtcohen6** [comment]
@haritamar Cool! Thanks for the thorough answer, it's an interesting pattern. Again, the actual thing you're requesting here is super reasonable, and most of the complexity will be outside `dbt-core` in your custom implementation.

I very much like the idea of disambiguating between SQL `md5` (as most databases implement it), and this one as `local_md5` or `jinja_md5`, to avoid confusing folks who would otherwise wonder about the subtle differences between:
```sql
select
    md5('some_string'),
    md5('{{ "some_string" }}'),
    '{{ md5("some_string") }}'
```
Though, in theory, all of them should yield the same result :)
