### ISSUE TITLE
[CT-1523] Improve to_dict processing in betterproto based events

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#6285]
The betterproto package has a flag "include_default_values" that is passed on the to_dict() call. We need to have default values on the standard fields and the oneof message that is particular for a specific event, but we don't want all of the defaults for all of the other events in the Event "oneof".

Some possibilities are requesting a feature from betterproto or overriding the betterproto to_dict to produce our desired output.

**Comment by jtcohen6** [comment]
- Switched to using `Optional` and that helped a lot
- We can close this
