### ISSUE TITLE
[CT-1533] [Bug] When moving YAML files between directories or renaming a directory, a python error occurs

### ISSUE THREAD

**Issue by uptocaroline** [dbt-labs/dbt-core#6287]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When moving YAML files between directories or renaming a directory, a python error occurs.

I have the following structure:
-models (1)
--metrics (2)
---monthly_new (3)
----metrics.yml (4)
----sources.yml (5)
----session_amount_per_platform_monthly.sql (6) - uses metric definition from metrics.yml (4)
---metrics.yml (7)

When the error happens:
1 - When I rename the folder "monthly_new (3)" to "monthly" or/and
2 - When I remove the file metrics.yml (7) - not used anymore or/and
3 - When I move the file metrics.yml (4) to one directory level before (to replace metrics.yml (7)).

```
root@W1389:~/git_repo/smg-data-group-dbt/dwh-group# dbt compile
13:53:09  Running with dbt=1.3.0
13:53:11  Encountered an error:
'dwh_group://models/05_pl_group/real_estate/metrics/by_platform/monthly_new/metrics.yml'
13:53:11  Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/main.py", line 135, in main
    results, succeeded = handle_and_check(args)
  File "/usr/local/lib/python3.10/site-packages/dbt/main.py", line 198, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/lib/python3.10/site-packages/dbt/main.py", line 245, in run_from_args
    results = task.run()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/runnable.py", line 453, in run
    self._runtime_initialize()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/runnable.py", line 161, in _runtime_initialize
    super()._runtime_initialize()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/runnable.py", line 94, in _runtime_initialize
    self.load_manifest()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/runnable.py", line 81, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 221, in get_full_manifest
    manifest = loader.load()
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 368, in load
    self.parse_project(
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 467, in parse_project
    block = FileBlock(self.manifest.files[file_id])
KeyError: 'dwh_group://models/05_pl_group/real_estate/metrics/by_platform/monthly_new/metrics.yml'

```

### Expected Behavior

When I remove a yaml file that is no longer used, or rename a file (unique name) dbt should be able to compile.

### Steps To Reproduce

0 - On dbt models, create the following structure (or similar):

-models (1)
--metrics (2)
---monthly_new (3)
----metrics.yml (4)
----sources.yml (5)
----session_amount_per_platform_monthly.sql (6) - uses metric definition from metrics.yml (4)
---metrics.yml (7)

1 - run dbt compile
2 - it should succeed
3 - When I rename the folder "monthly_new (3)" to "monthly" or/and
4 - When I remove the file metrics.yml (7) - not used anymore or/and
5 - When I move the file metrics.yml (4) to one directory level before (to replace metrics.yml (7)).
6 - run dbt compile
7 - the error should happen

### Environment

```markdown
- OS: Windows 10
- Python: 3.10
- dbt: 1.3
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

It started to happen after upgrade to dbt 1.3.

**Comment by jtcohen6** [comment]
@uptocaroline Thanks for opening, and providing the clear walkthrough. I suspect this would be a bug related to partial parsing, [given the line in the stacktrace](https://github.com/dbt-labs/dbt-core/blob/d71385bdb60a0961d6a6ea1248849fa31b4690a5/core/dbt/parser/manifest.py#L467), and specifically the link between the downstream model with the dependency on the metric.

Unfortunately, I haven't been able to reproduce this error! Here's the repro case I'm trying, following yours:
```
models/
└── metrics
    ├── metrics.yml
    └── subfolder
        ├── metrics.yml
        ├── model_a.sql
        └── model_b.sql
```
```yml
# models/metrics/subfolder/model_b.yml
version: 2
metrics:
  - name: some_metric
    label: Some Metric
    model: ref('model_a')
    calculation_method: count
    expression: id
    timestamp: updated_at
    time_grains: [day]
```
```sql
-- models/metrics/subfolder/model_b.sql
select * 
from {{ metrics.calculate(
    metric('some_metric'),
    grain='day'
) }}
```
```yml
# models/metrics/metrics.yml
version: 2
metrics:
  - name: some_other_metric
    label: Some Other Metric
    model: ref('model_a')
    calculation_method: count
    expression: id
    timestamp: updated_at
    time_grains: [day]
```

I tried making the changes you described. First, I run `dbt compile` — or just `dbt parse`, which should manage to catch any bugs during (partial) parsing — then I make the change, and run `dbt compile` / `dbt parse` again.

```
$ dbt --version
Core:
  - installed: 1.3.1
  - latest:    1.3.1 - Up to date!
```

> When the error happens:
> 1 - When I rename the folder "monthly_new (3)" to "monthly" or/and

```bash
$ dbt compile && mv models/metrics/subfolder models/metrics/subfolder_renamed && dbt compile
15:22:02  Running with dbt=1.3.1
...
15:22:12  Done.
```

> 2 - When I remove the file metrics.yml (7) - not used anymore or/and

```
$ dbt compile && rm models/metrics/metrics.yml && dbt compile
15:27:02  Running with dbt=1.3.1
...
15:27:05  Done.
```

> 3 - When I move the file metrics.yml (4) to one directory level before (to replace metrics.yml (7)).

```
$ dbt compile && mv models/metrics/subfolder/metrics.yml models/metrics/metrics.yml && dbt compile
15:28:00  Running with dbt=1.3.1
...
15:28:02  Done.
```

Does that reproduction case look right to you? Is there an obvious piece I may be missing?

**Comment by nicholasyager** [comment]
@jtcohen6 I believe that this defect has been reintroduced in a dbt-core 1.4.x. I personally have seen this defect pop-up in 1.4.6, and it seems to be a regular occurrence for my employee. We are able to work around the issue by clearing out the cache artifacts in `target` using `dbt-clean`, but this does indicate to me that there may be an edge case in partial parsing.

Want me to create a new issue to track this?

**Comment by TrololoLi** [comment]
The same thing. We simply delete target folder, but it's still a bit annoying

**Comment by jtcohen6** [comment]
@nicholasyager @TrololoLi Heard! Could I ask one of you to open a new issue? If you're able to reliably reproduce, any details you provide will help us reproduce on our side and find/fix the root cause.

**Comment by louis-king99** [comment]
is there a new issue?

**Comment by dimitrik1223** [comment]
Echoing the comment above, would be great to have another issue for this
