### ISSUE TITLE
[CT-1539] [Feature] Ignore `manifest.json` files for `git grep`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#6294]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Problem

There are multiple lengthly JSON files that make it harder to scroll through `git grep ...` results.

[Here](https://github.com/dbt-labs/dbt-core/blob/f5a94fc77428426002ef2a908ebf57a32597a627/tests/functional/artifacts/data/state/v7/manifest.json) is an example file that gums up the results when doing a search like this:
```shell
git grep "unrendered_config" tests
```

Although this JSON file is all text, it's all on a single line which makes it behave more like a binary file for text comparison tools.

### Solution
1. Create a [`.gitattributes`](https://git-scm.com/docs/gitattributes#_marking_files_as_binary) file in the root directory
1. Add a line like the following (tweak as needed/desired -- e.g., replace `binary` with [`-diff`](https://git-scm.com/docs/gitattributes#_marking_files_as_binary) or [`-text -diff`](https://git-scm.com/docs/gitattributes#_using_macro_attributes))
    ```
    tests/functional/artifacts/data/state/*/manifest.json binary
    ````
1. Add this line to capture another file that commonly causes overwhelm:
    ```
    core/dbt/include/index.html binary
    ````
Then a command like the following will have more consumable results:
```
$ git grep "unrendered_config" tests

Binary file tests/functional/artifacts/data/state/v4/manifest.json matches
Binary file tests/functional/artifacts/data/state/v5/manifest.json matches
Binary file tests/functional/artifacts/data/state/v6/manifest.json matches
Binary file tests/functional/artifacts/data/state/v7/manifest.json matches
tests/functional/artifacts/expected_manifest.py:                "unrendered_config": unrendered_model_config,
...
```

**Comment by gshank** [comment]
Can we also skip the core/dbt/include/index.html file?

**Comment by dbeatty10** [comment]
> Can we also skip the core/dbt/include/index.html file?

Yeah! Good call @gshank -- added that file name to the description above
