### ISSUE TITLE
[CT-1542] [Feature] Combine MetricReference and ResolvedMetricReference?

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-core#6301]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Right now, we have two classes in `metrics.py` called `MetricReference` and `ResolvedMetricReference`. The latter is a proxy over the former and contains helper functions  for working with metrics.

The issue with this is that we need the information from these helper functions at parse time, not runtime. They are required to construct the SQL for the metric queries. As such, this functionality can't be used because it is called at the same time and any attempt to use them in dbt_metrics causes errors.

Some might ask if this is a bug - it **could be** but we don't use these helper functions to date so I figured feature made more sense!

### Describe alternatives you've considered

Adding the same logic to MetricReference but that seems tricky given that it appears that the class doesn't contain an input of the metric node.

### Who will this benefit?

Anyone using metrics - this will speed up performance!

### Are you interested in contributing this feature?

Yes!

### Anything else?

I would love to contribute this feature but might need some advice on how dbt is using inheritance with regards to Parse classes and Runtime classes. To my novice eyes it looks like Parse exists **before** the node information is written to the manifest while the Runtime exists **after**. Obviously this isn't entirely true because we are able to parse some node level information at runtime.

**Comment by gshank** [comment]
My guess is that the two classes might have been copied from the implementation of ecposures. I can take a look tomorrow.

**Comment by ChenyuLInx** [comment]
@gshank  I feel like we could just use one `ResolvedMetricReference`? Although it looks like in `ResolvedMetricReference` there are functions that tries to access parent_metrics_id which seems not accessible during parsing time?

**Comment by callum-mcdata** [comment]
@gshank I agree, it closely mimics exposures so it would make sense if it was copied using that format. @ChenyuLInx the helper functions would need to know the parent_metric_ids , which to your point might not be available at parse time. Is there way we can trigger some form of additional parse on metrics after the first completion in order to have all the information we need after running `dbt parse`?

**Comment by jtcohen6** [comment]
https://github.com/dbt-labs/dbt-core/blob/cfece2cf51036b69d74f9212cfeb58958d193121/core/dbt/contracts/graph/metrics.py#L32-L93

> The issue with this is that we need the information from these helper functions at parse time, not runtime. They are required to construct the SQL for the metric queries. As such, this functionality can't be used because it is called at the same time and any attempt to use them in dbt_metrics causes errors.

@callum-mcdata I'm a bit surprised to hear this. My understanding is that the entire `{{ metrics.calculate() }}` function should be happening at compile/runtime! Any chance you could share some sample code / errors where you've tried swapping out the [Jinja-based approach](https://github.com/dbt-labs/dbt_metrics/blob/main/macros/variables/get_metric_tree.sql) for the `ResolvedMetricReference` helper methods?

There should be parity in terms of the information available between the Jinja context and Python objects like `ResolvedMetricReference` (exposed to the [`RuntimeProvider`](https://github.com/dbt-labs/dbt-core/blob/2289e45571da690d8b997a5346379443ed48a631/core/dbt/context/providers.py#L661)). The `graph` variable is not yet populated at parse time, though it _is_ available/empty, and I'm wondering if that's what makes the difference.
