### ISSUE TITLE
[CT-1543] [Bug] dbt seed raise error  mismatched input 's' when there is 's in csv file

### ISSUE THREAD

**Issue by grhaonan** [dbt-labs/dbt-core#6306]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt seed will raise the following error when there is a 's expression in csv

botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 2:2611: mismatched input 's'. Expecting: ')', ','
Failed to execute query.

### Expected Behavior

it should work

### Steps To Reproduce

csv with format

2500, dustin's test

The issue will gone if it is

2500, dustins test, the issue is ' character before the letter s

### Environment

```markdown
- OS: Macos 12.6
- Python: 3.9
- dbt: 1.0.8
- athena plugin athena: 1.0.1
```

### Additional Context

I am not sure if this issue is related to athena adapter or dbt core

if ' character is not supported in the csv form seed would expect, may I suggest to update the documentation to mention this limitation as I spent 1 hour to figure out this.

if ' character is supposed to be supported( my understanding), then this is an issue either related to core or athena adapterfiguring

**Comment by dbeatty10** [comment]
Thanks for reaching out @grhaonan !

Did you include column headers in the first line of CSV (like `my_number,my_string` as shown below)?

If so, then I suspect this is an issue in Athena adapter you are using, as all of the following work for me when testing with dbt-snowflake:

```
my_number,my_string
2500,dustin's test
```
Or:
```
my_number,my_string
2500,"dustin's test"
```
Or:
```
my_number,my_string
"2500","dustin's test"
```

**Comment by grhaonan** [comment]
Hi Doug,

Thanks for your quick check and test. 

Yes, it did have the headers and I am able to reproduce the issue with your sample as well


![Screen Shot 2022-11-24 at 9 32 03 am](https://user-images.githubusercontent.com/9297622/203657370-0caa8953-6736-4483-95a0-289a14b8de89.png)

![Screen Shot 2022-11-24 at 9 32 11 am](https://user-images.githubusercontent.com/9297622/203657420-b1031945-96bc-453c-9b66-82d0dd9e95e9.png)

The issue is gone after removing the ' before s

Okay, I will route this issue to athena-adapter community then, thanks for your help.

**Comment by dbeatty10** [comment]
Closing in favor of https://github.com/dbt-athena/dbt-athena/issues/60

**Comment by owenprough-sift** [comment]
> Closing in favor of [dbt-athena/dbt-athena#60](https://github.com/dbt-athena/dbt-athena/issues/60)

@dbeatty10 you may have forgotten to close this issue. :)

**Comment by dbeatty10** [comment]
😅 Thank you @owenprough-sift
