### ISSUE TITLE
[CT-1545] [Bug] dbt.config.get returns Undefined instead of the default value in Python model

### ISSUE THREAD

**Issue by devmessias** [dbt-labs/dbt-core#6309]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt.config.get("missing_key", "default_value")` default value dosen't work.  This behavior creates an Undefined variable inside the context after the compilation like this.

```python
config_dict = {'KEY_AVAILABLE': 'everthing_is_ok',  'MISSING_KEY': Undefined}
```

### Expected Behavior

```python
config_dict = {'KEY_AVAILABLE': 'everthing_is_ok',  'MISSING_KEY': "default_value"}
```

### Steps To Reproduce

Define a model like:

```python
def model(dbt, session):

    CONFIG_KEY = dbt.config.get("KEY_EXIST", "DEFAULT_VALUE")
    MISSING_KEY = dbt.config.get("MISSING_KEY", "DEFAULT_VALUE")

    df = dbt.ref("orders")

    return df
```
With configs like:

```yaml
version: 2
models:
  - name: something
    config:
      CONFIG_KEY:  everthing_is_ok
```
Run dbt compile. 

The compiled output will create a `config_dict` like this

```python
config_dict = {'CONFIG_KEY': 'everthing_is_ok',  'MISSING_KEY: Undefined}
```

In that case, Undefined is a undeclared variable in the context. Because that, this will create an exception. 

### Environment

```markdown
- OS: Linux/Ubuntu
- Python:3.9.12
- dbt-core==1.3.0 
- dbt-databricks==1.3.0
```

### Which database adapter are you using with dbt?

spark

**Comment by devmessias** [comment]
Related to https://github.com/dbt-labs/dbt-core/issues/5846. I can work in a PR to fix that.

**Comment by jtcohen6** [comment]
@devmessias Good catch, thanks for opening!

This feels like a relatively simple & self-contained fix, so we'd welcome a contribution for it. Let us know if it turns out to be trickier than expected.

**Comment by devmessias** [comment]
> @devmessias Good catch, thanks for opening!
> 
> This feels like a relatively simple & self-contained fix, so we'd welcome a contribution for it. Let us know if it turns out to be trickier than expected.

You're right! It was a quite simple fix
