### ISSUE TITLE
[CT-1555] Allow for Only `INSERT` Operation (without `UPDATE`) with `unique_key` in `MERGE` DML for Incremental Models

### ISSUE THREAD

**Issue by anaghshineh** [dbt-labs/dbt-core#6320]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like for `dbt` to support an incremental model build type that uses the `merge` strategy with `unique_key` config to produce `MERGE` DML that only consists of an `INSERT` operation, without `UPDATE`. Currently, the `merge` strategy with `unique_key` enabled produces a `MERGE` statement consisting of an `UPDATE` AND `INSERT` operation. There is no built-in config for excluding the `UPDATE` portion.

I could see an additional config param being added that would, if `true`, allow for users to exclude any `UPDATE` portion of the `MERGE` statement.

### Describe alternatives you've considered

I've considered overriding the default behavior of the relevant macro (`get_merge_sql` [here](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql)) to allow for the "skipping" of the `UPDATE` portion [here](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql#L37-L43) when `unique_key` is enabled.

### Who will this benefit?

This will benefit users who are interested in building tables incrementally, but do not need to worry about records being updated after they are inserted from the upstream source table into the target table. In this instance, the `UPDATE` portion is unnecessary/wasteful.

We build the majority of our tables incrementally given their size. We have upstream tables from which we source data. These tables are constantly having new records inserted into them throughout the day, and they have a reliable `unique_key` field that we can take advantage of. Once a record is inserted, it is not touched again (no updates) - it is considered "final." We have downstream, incremental models that pull from these source tables. We use the `unique_key` field to identify new records within a given lookback window we define (one reason for the lookback is to account for potential lag in our data processing pipelines). We want to insert new records into the downstream tables, but we have no need to update any preexisting records as part of the `MERGE`, as we are confident that there have been no changes to the fields of records that have already been inserted.

### Are you interested in contributing this feature?

Yes! This will be my first attempt at contributing, but I think I have a good idea re: how to go about it :)

### Anything else?

Interested to hear thoughts on this - does it seem useful?

**Comment by jtcohen6** [comment]
Hey @anaghshineh - I think what you're asking for is:
- An "append-only" incremental strategy
- Where any new records with the same `unique_key` as an existing row in the table value are completely ignored

I see two valid ways to achieve this:
1. `merge` that matches on unique keys, `when matched` ignores, `when not matched` inserts
2. In your model SQL, filter out any records where the `unique_key` is already in `{{ this }}` (preexisting table) — leaving you with only never-before-seen rows. Then, use a simple `insert` statement to add them in.

The second approach is less fancy, and that's a good thing! All the business logic lives in the model; the materialization logic is dead simple. It's super easy to reason through, and to see the exact rows that will be appended into the resulting table, _without actually modifying that table_, simply by previewing the model SQL (`select ...`).

As of v1.3, dbt-core supports an explicit "append" strategy as _the default strategy_ on all databases. In previous releases, and for backwards compatibility, this is also the behavior for the `merge` and `delete+insert` strategies, if no `unique_key` is specified.

---

So, here's what that could look like today, in a dbt model:
```sql
-- models/my_append_only_incremental_model.sql

{{ config(materialized = 'incremental') }}

with first_cte as (

    select * from {{ ref('upstream_model') }}

    {% if is_incremental() %}
        where id not in (select id from {{ this }})
    {% endif %}

),

...
```

Or, in v1.3+, if you still want to record the `unique_key` as configuration (e.g. for metadata tracking):
```
-- models/my_append_only_incremental_model.sql

{{ config(
    materialized = 'incremental',
    incremental_strategy = 'append',
    unique_key = 'id'
) }}

{% set unique_key_col = config.get('unique_key') %}

with first_cte as (

    select * from {{ ref('upstream_model') }}

    {% if is_incremental() %}
        where {{ unique_key_col }} not in (select {{ unique_key_col }} from {{ this }})
    {% endif %}

),

...
```

---

I'm going to close this issue in the meantime, as I believe the desired pattern is possible with existing capabilities.

> As of v1.3, dbt-core supports an explicit "append" strategy as _the default strategy_ on all databases.

Updates to [the relevant docs](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#configuring-incremental-strategy) haven't landed quite yet (issue for this: https://github.com/dbt-labs/docs.getdbt.com/issues/1761).
