### ISSUE TITLE
[CT-1562] Remove PR# from changelogs

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#6332]
The standard for changelogs in the industry is to link changes to _either_ an issue or a PR, but generally not both.  Currently we link to both for every changelog.

```
This pulls the profile name from args when constructing a RuntimeConfig in lib.py, enabling the dbt-server to override the value that's in the dbt_project.yml (https://github.com/dbt-labs/dbt-core/issues/6201, https://github.com/dbt-labs/dbt-core/pull/6202)
```

I propose we remove the PR from changelogs and only link to the issues related to the change.  The only exception to this change would be dependabot and snyk changes because they never have issues.  But for those we could remove the #4904 issue link completely and only link to the PR.

What's involved in this change:
- [ ] update .changie.yaml to not use PR except for dependency and snyk changes.
    - [x] dbt-core
    - [x] dbt-snowflake
    - [x] dbt-redshift
    - [x] dbt-spark
    - [x] dbt-bigquery
    - [ ] dbt-docs
- [x] update [changelog-existence.yml](https://github.com/dbt-labs/actions/blob/main/.github/workflows/changelog-existence.yml) to pass on changelog modification or addition, not only addition.  This allow the check to pass when we add an associated issue to an existing chnagelog.
- [x] Go through existing changie yaml files and remove the PR lines
    - [x] dbt-core
    - [x] dbt-snowflake
    - [x] dbt-redshift
    - [x] dbt-spark
    - [x] dbt-bigquery
    - [x] dbt-docs
- [x]  backport all the way to 1.1.latest in all repos - this allow future backports to work and not break changelog generation
    - [x] dbt-core
    - [x] dbt-snowflake
    - [x] dbt-redshift
    - [x] dbt-spark
    - [x] dbt-bigquery
    - [ ] ~~dbt-docs~~

**Comment by jtcohen6** [comment]
@emmyoop Thanks for the thorough writeup, reflecting the conversation from Slack! I'm in favor of doing this.

> The only exception to this change would be dependabot and snyk changes because they never have issues. But for those we could remove the https://github.com/dbt-labs/dbt-core/issues/4904 issue link completely and only link to the PR.

👍 

The other thing we discussed: A big change that's split into lots of little PRs (often against feature branches), all of which roll up into a single big coherent change. We should have a single big issue / epic, with links out to the PRs in its description, and a single changelog entry linking to that issue. Subsequent PRs can modify the changelog entry if they're expanding / modifying the scope of the overall change.

Examples:
- https://github.com/dbt-labs/dbt-core/issues/4260
- https://github.com/dbt-labs/dbt-core/issues/4788
- https://github.com/dbt-labs/dbt-core/issues/5527

**Comment by emmyoop** [comment]
We will want to backport this because it could otherwise cause changie to break the changelogs we backport.

**Comment by emmyoop** [comment]
This is also relevant for `dbt-server`!
