### ISSUE TITLE
[CT-1566] Add a timeout to structured-logging-schema-check.yml

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#6338]
### Describe the feature

Add a timeout to [structured-logging-schema-check.yml](https://github.com/dbt-labs/dbt-core/blob/ad9aabca1d7b08c5b82d524833b3a96c4f332c76/.github/workflows/structured-logging-schema-check.yml) of 45 min to match [main.yml](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/main.yml)

**Comment by leahwicz** [comment]
@leahwicz look if project level setting is possible

**Comment by emmyoop** [comment]
I looked into this and it's not something that can be defaulted at the org or repo level.  Timeout can only be set at the job or step level.

**Comment by MichelleArk** [comment]
Done as part of https://github.com/dbt-labs/dbt-core/pull/6346/files#diff-99491260a59ff497a4cafcef10f47531bd34e4ab7fb4580f5e8ca36d7c650468R49
