### ISSUE TITLE
[CT-1574] [Feature] Better error messages when a column doesn’t exist

### ISSUE THREAD

**Issue by devmessias** [dbt-labs/dbt-core#6348]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

At my company, I’m handling models with hundreds of columns .  Sometimes, I make some typos and I get errors like this

```
  AnalysisException: Column ‘somithing’ does not exist. Did you mean one of the following? [....scary]
```

Look at how python   >=3.10 deals with that, python suggests the most similar and correct name in case of an Attrribute Exception:

```
class Math:
    sqrt = 0
    squirrel = “squirrel”

m = Math()
m.sqrr

File "<stdin>", line 1, in <module>
    m.sqrr
AttributeError: module 'Math' has no attribute 'sqrr'. Did you mean: 'sqrt'?
```

I strongly believe that using the [Damerau–Levenshtein distance](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance) to suggest the most similar column name and sort the list of cols using this distance will improve the readability and cognitive load of dbt.

### Describe alternatives you've considered

None

### Who will this benefit?

Everyone who deals with models (and python models) with a huge number of columns. Specially non-native English speakers.

### Are you interested in contributing this feature?

Yes, I've been working with Levenshtein distance variations in the past months.

**Comment by dbeatty10** [comment]
I see what you are saying @devmessias !

And using the minimum [edit distance](https://en.wikipedia.org/wiki/Edit_distance) like [Damerau–Levenshtein distance](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance) to suggest the most likely intended column name seems like a great idea.

I'm guessing you're getting this error message while using PySpark with either Databricks or BigQuery?

Unfortunately, this particular error message looks like it might be coming from [Apache Spark](https://github.com/apache/spark), so not much we can do about the content on the dbt side of things. The best I can do is suggest is contributing a JIRA issue and/or GitHub pull request within the Apache Spark project -- their contributing guide is [here](https://spark.apache.org/contributing.html).

(See [here](https://github.com/apache/spark/search?q=Did+you+mean+one+of+the+following) and [here](https://github.com/apache/spark/search?q=AnalysisException) for some ideas where it might be in their source code.)

**Comment by jtcohen6** [comment]
Agree with Doug here! dbt is just passing along the error message from the database. We intentionally don't try to do anything very clever, such as comparing the error message to the query that was submitted, since we think this is a job for the database's own query optimizer / error handler.

**Comment by jtcohen6** [comment]
I'm going to close this issue, since I don't think it's in scope for `dbt-core` — at least, not in the short or medium term. Maybe someday, if/when dbt gains the capability or proclivity for parsing user-provided model code (SQL, Python, ...) more than it does today.
