### ISSUE TITLE
[CT-1580] [Bug] Warning message produces parameter value from another macro argument, not the one configured

### ISSUE THREAD

**Issue by kd7vrc** [dbt-labs/dbt-core#6355]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

A macro that accepts two arguments, and warns based on a condition, and contains one of the parameters in the message outputs the other parameter value in the compile log. (Correct at execution.)

### Expected Behavior

A parameterized warning message should produce the correct values for the corresponding parameter.

### Steps To Reproduce

1. Create a macro fitting the description like this:
```sql
{% macro exception_warn_bug(source_rel, target_rel) %}
{# Defaults for easy test #}
{% set source_rel = source_rel or ref('wk_umb_policy_trig_pc') %}{# Exists #}
{% set target_rel = target_rel or source('etl_policy_dbt_tgt','cv_umb_insured_subject_pc') %}{# Does not exist #}
{% set allow_target_not_exists = allow_target_not_exists or True %}
{{ log("Begin processing from " ~ source_rel ~ " to " ~ target_rel, True) }}
{%- if load_relation(target_rel) is none -%}
    {% do exceptions.warn("Target '" ~ target_rel ~ "' does not exist on the database.", True) %}
{% elif execute %}
    {% do log('Execute stuff', True) %}
{% endif %}
{% endmacro %}```
2. Add it somewhere so dbt IDE compiles it `{{ exception_warn_bug }}`
3. Review the **compilation** logs

### Relevant log output

```shell
# From compile log
18:56:42  Begin processing from RRADDEV.PLZ4614.wk_umb_policy_trig_pc to RRADDEV.PLZ4614.wk_umb_policy_trig_pc
18:56:42  Target 'RRADDEV.PLZ4614.wk_umb_policy_trig_pc' does not exist on the database.
```

### Environment

```markdown
- dbt Cloud: 1.3
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Documentation indicates that the warning is intended to be used for compilation warning. See https://docs.getdbt.com/reference/dbt-jinja-functions/exceptions#warn

**Comment by jtcohen6** [comment]
(Sorry @dbeatty10 , this one happened to catch my eye!)

Related: https://github.com/dbt-labs/dbt-core/issues/5360

`load_relation` is _always_ going to return `None` at parse time, because the cache has not yet been populated. Yet, macros like `log()` and `exceptions.warn()` are still evaluated at parse time, during our "first-pass" Jinja render to extract ref/source/config. This is misleading.

Of course, it's possible to avoid this with a modification to the code above:
```sql
{%- if execute and load_relation(target_rel) is none -%}
```

**Comment by dbeatty10** [comment]
@kd7vrc Thanks again for reaching out about this!

We're going to address this with some updates to the docs and close this as `wontfix`. But we'd welcome your thoughts on what a better behavior might look like, though.

Here's the issue we opened as a result:
https://github.com/dbt-labs/docs.getdbt.com/issues/2492

We'd value your feedback on those docs updates as well.

**Comment by elyobo** [comment]
Does `wontfix` imply that you're not fixing https://github.com/dbt-labs/dbt-core/issues/2793 as well? That's not just a "causes confusion" issue, that's a "prevents very useful $$$ saving and performance improving functionality in BigQuery" issue...
