### ISSUE TITLE
[CT-1588] [Bug] Define python version for tests in 1.0.latest

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#6361]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I don't know why we're just hitting this bug, but since the workflow does not specify the python version, it's trying to run on python 3.11 and fails.

Offending Workflow: .github/workflows/main.yml 

### Expected Behavior

No errors

### Steps To Reproduce

Run the workflow

**Comment by dbeatty10** [comment]
Resolved by #6362
