### ISSUE TITLE
[CT-1593] [Bug] Update core/dbt/README.md to match current situation

### ISSUE THREAD

**Issue by yoiki** [dbt-labs/dbt-core#6368]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

There are several omissions in [core/dbt/README.md](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/README.md) . `constants.py`, `selected_resources.py`, etc. are not listed.

### Expected Behavior

List some file name under `## The following are individual files in this directory.`
* constants.py
* selected_resources.py

Add some dir name under `## The subdirectories will be documented in a README in the subdirectory`
* contracts
* parser
* tests

It may be a good idea to sort this list in abc order to improve readability.

### Steps To Reproduce

Please check [core/dbt/README.md](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/README.md) 

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by dbeatty10** [comment]
Thanks for noticing and reaching out @yoiki !

I created https://github.com/dbt-labs/dbt-core/pull/6371 to incorporate your suggestions.
