### ISSUE TITLE
[CT-1598] [Regression] Granting select does not work with dbt-postgres==1.3.1  

### ISSUE THREAD

**Issue by keurcien** [dbt-labs/dbt-core#6378]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Granting `select` to a certain user by adding this config to a model used to work with dbt 1.1.x, but after an upgrade to dbt 1.3.0, this raises an error when running `dbt run --models xxx`

```
# xxx.sql
{{ 
    config(
        grants = {'select': ['user_a']}
    )
}}
```

### Expected/Previous Behavior

The dbt command should not fail.

### Steps To Reproduce

1. Use a postgres profile
2. Create a dbt model `one.sql`
```
select 1
```
3. Add the config
```
{{ 
    config(
        grants = {'select': ['user_a']}
    )
}}
```
4.Run the command `dbt run --models one`

### Environment

```markdown
- OS: macOS 13.0.1
- Python: python 3.10
- dbt (working version): 1.1.0
- dbt (regression version): 1.3.1
```

### Which database adapter are you using with dbt?

postgres

**Comment by jtcohen6** [comment]
@keurcien What's the actual error you're seeing?

> Granting `select` to a certain user by adding this config to a model used to work with dbt 1.1.x, but after an upgrade to dbt 1.3.0, this raises an error when running `dbt run --models xxx`

This is surprising — we only added built-in support for `grants` in dbt-core v1.2.x, and we didn't make any significant changes from v1.2 &rarr; v1.3.

Is it possible that you hand-rolled your own implementation of a `grants` config? In that case, upgrading from v1.1 &rarr; v1.3 would mean that dbt's built-in `grants` implementation would _start_ taking effect, and it could conflict with your own custom one.

**Comment by keurcien** [comment]
Ok actually my user was not 'user_a' but 'metabase-proxy' and it might be due to the dash `-`. We did not have a custom implementation and I'm pretty sure we were under 1.1 and had it running, so this is strange.

```
{{ 
    config(
        grants = {'select': ['metabase-proxy']}
    )
}}
```

```
> dbt run --models one.sql

14:48:30  Running with dbt=1.3.1
14:48:30  Found 106 models, 1 test, 0 snapshots, 0 analyses, 733 macros, 0 operations, 3 seed files, 43 sources, 3 exposures, 0 metrics
14:48:30  
14:48:34  Concurrency: 4 threads (target='dev')
14:48:34  
14:48:34  1 of 1 START sql table model core.one .......................................... [RUN]
14:48:34  1 of 1 ERROR creating sql table model core.one ................................. [ERROR in 0.28s]
14:48:35  
14:48:35  Finished running 1 table model in 0 hours 0 minutes and 4.22 seconds (4.22s).
14:48:35  
14:48:35  Completed with 1 error and 0 warnings:
14:48:35  
14:48:35  Database Error in model one (models/marts/core/one.sql)
14:48:35    syntax error at or near "-"
14:48:35    LINE 4: ...    grant select on "dwh"."core"."one" to metabase-proxy
```

**Comment by keurcien** [comment]
Oh ok! Yeah my bad because I thought it was broken, gonna close the issue. Thanks for your help!
