### ISSUE TITLE
[CT-1602] [Feature] a thin layer for calling dbt top level commands programatically

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#6381]
### Describe the feature

In the current iteration of integrating dbt-core into dbt-server, we are doing something similar to [the example](https://github.com/dbt-labs/dbt-core/pull/6307/files) @MichelleArk added.

But this require use to setup the click context manual, for example([link](https://github.com/dbt-labs/dbt-server/blob/ac1f183ea5304b6fb40790441cee90c8038f0e69/dbt_server/views.py#L471-L472))

```
    project_dir_override = os.path.expanduser(ctx.params.get('project_dir'))
    ctx.obj["project"] = load_project(project_dir_override, True, None, None)  # type: ignore
    dbt.commands[command].invoke(ctx)
```

In this example, we are constructing a project object and put it in the context, so that the following command can use it.

It is not ideal that we are doing this kind of operation on the raw click context, dbt-core side should provide an abstraction layer on top to hide the click implementation underneath. Option 3 out of the discussion with @peterallenwebb  and @MichelleArk  is what we are currently thinking about.([link](https://github.com/dbt-labs/dbt-server/blob/ac1f183ea5304b6fb40790441cee90c8038f0e69/dbt_server/views.py#L490-L494))

```
    # option3
    # we need to customize making context
    # ctx.set_logger_for_dbt(new_logger)
    # ctx.set_profie()
    #     # maybe have a customize invoke function from click
```

Here we imagine the `ctx` being some dbt-core object that has certain functions that other program can use to customize setup.

This issue is for implementing such thin layer on top of the click framework core uses to model it's cli interface.

This would be the replacement(maybe part of the replacement) for current [lib.py](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/lib.py), we should also think about what are the things that we don't like about `lib.py` and avoid doing similar thing in the new thin layer. We would want this layer tested, and also avoid any hard code happening in it.

### Describe alternatives you've considered

Updating the click context directly

### Who will this benefit?

Users who wants to use dbt as a python package

**Comment by jtcohen6** [comment]
First cut of this was included in https://github.com/dbt-labs/dbt-core/pull/6387
