### ISSUE TITLE
[CT-1612] Add deprecation decorator for functions

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#6393]
Create a decorator that can be added to functions to mark them as deprecated.

Related to #6347 as we need to make the functions that currently trigger exceptions as deprecated for all the adapters that may be using them.

Open questions:
- What standard info to include with deprecation?
- When should the exception functions actually be deprecated - 1 or 2 versions?

**Comment by justbldwn** [comment]
hi @emmyoop! i see this is self-assigned - are you looking for PR's for this issue? or have you already started work on this? just checking before possibly contributing 👍

**Comment by emmyoop** [comment]
@justbldwn I'll be working on this over our next sprint.  Thanks for checking in though!
