### ISSUE TITLE
[CT-1621] [Feature] de-globalize things through contextvar

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#6399]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We have a few things inside dbt-core that are python global objects. Some examples are [`active_user`](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/tracking.py#L178), [`EVENT_MANAGER`](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/functions.py#L23). With the future of `dbt-server` running multiple `dbt-core` invocations at the same time, we should make sure those multiple invocation don't overwrite those objects.

In the example [here](https://stackoverflow.com/questions/63105799/understanding-python-contextvars), `contextvars` is a great way of dealing with global variables during concurrency.

We should make sure we move the usage of all global object in `dbt-core` into `contextvars`

**Comment by jtcohen6** [comment]
Another funny one to add to the list of unnecessarily global objects: [`selected_resources`](https://github.com/dbt-labs/dbt-core/blob/b9a35da1182571e667bce5cda4e717c3fc032637/core/dbt/selected_resources.py#L3)

We already have an open issue for that here: https://github.com/dbt-labs/dbt-core/issues/6009. Thoughts on keeping it as a separate issue/ticket, versus pulling it into this one?

**Comment by MichelleArk** [comment]
Another global flag to be aware of is `USE_COLORS`, which is initialized as part of [`GLOBAL_FLAGS` Namespace in flags.py](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/flags.py#L29), and [used in `ui.color`](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/ui.py#L23)
