### ISSUE TITLE
[CT-1627] [Spike] Identify requirements for structured logging in dbt-server

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#6401]
### Describe the feature

The result of this spike should be a list of issues that we have to go do to support `dbt-server` using structured logging

**Comment by jtcohen6** [comment]
@peterallenwebb Would you consider this one resolved, given the conversations we had with @racheldaniel and the flexible callback implementation added in #6291?

**Comment by peterallenwebb** [comment]
Yes, we've provided runtime with what they should need for 1.4, so I'll close this.
