### ISSUE TITLE
[CT-1642] [Bug] DBT with python

### ISSUE THREAD

**Issue by sunnylilili** [dbt-labs/dbt-core#6418]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

"import requests" and "import retry"  in python not working for dbt build. (I used the clound IDE)

How to use these two packages.

00:11:05
00:11:05 Completed with 1 error and 0 warnings:
00:11:05
00:11:05 Database Error in model my_python_v2 (dbt/models/my_python_v2.py)
00:11:05 100357 (P0000): Python Interpreter Error:
00:11:05 Traceback (most recent call last):
00:11:05 File "_udf_code.py", line 9, in <module>
00:11:05 ModuleNotFoundError: No module named 'requests'
00:11:05 in function MY_PYTHON_V2__DBT_SP with handler main
00:11:05 compiled Code at dbt/target/run/models/my_python_v2.py

### Expected Behavior

Should dbt build work for these two packages.

### Steps To Reproduce

1) Write a python file 
just import the two packages.

In cloud IDE for dbt lab,

### Environment

```markdown
- OS:
- Python:
- dbt: dbt cloud IDE
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @sunnylilili !

Two guesses for what's going on here:
1. You are using Snowflake
2. Missing `packages` within the `dbt.config`

Which data platform are you trying to use: Databricks, Snowflake, or BigQuery? Note that Snowflake does not currently support importing the `requests` library.

Importing packages hosted on PyPI is described in our documentation [here](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/python-models#using-pypi-packages). The general pattern for importing a package (in this case `holidays`) is:
```python
import holidays

def model(dbt, session):
    dbt.config(
        materialized = "table",
        packages = ["holidays"]
    )
    
    ...
```

The `packages = ["holidays"]` part near the end is required, but easy to overlook.
