### ISSUE TITLE
[CT-1643] [Bug] Deal with another change in tox behavior

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#6421]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The builds for 1.0.latest and 1.1.latest are failing because a recent change to tox yesterday (https://github.com/tox-dev/tox/issues/2658) causes it to error out when it encounters passenv parameters separated by spaces. This is a bit different than the previous tox change that affected newer versions of dbt but the fix should be the same. In that case the spaces simply caused tox to ignore the parameters.

### Expected Behavior

The 1.0.latest and 1.1.latest tests should pass.

### Steps To Reproduce

The failures can be observed in the 1.0.latest and 1.1.latest CI pipelines.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
Resolved by #6445 + #6446
