### ISSUE TITLE
[CT-1645] [Regression] Datetime format in run_results.json results.timing[].completed_at has no timezone

### ISSUE THREAD

**Issue by lustefaniak** [dbt-labs/dbt-core#6428]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

run_results.json and sources.json has completed_at datetime in timing report without timezone.

```
      "timing": [
        {
          "name": "compile",
          "started_at": "2022-12-09T11:45:25.274155Z",
          "completed_at": "2022-12-09T11:45:25.294915"
        },
        {
          "name": "execute",
          "started_at": "2022-12-09T11:45:25.312143Z",
          "completed_at": "2022-12-09T11:45:25.984434"
        }
      ],
```

### Expected/Previous Behavior

```
      "timing": [
        {
          "name": "compile",
          "started_at": "2022-12-09T11:45:25.274155Z",
          "completed_at": "2022-12-09T11:45:25.294915Z"
        },
        {
          "name": "execute",
          "started_at": "2022-12-09T11:45:25.312143Z",
          "completed_at": "2022-12-09T11:45:25.984434Z"
        }
      ],
```

### Steps To Reproduce

Happens on dbt Cloud with version 1.4.0a1

### Environment

```markdown
dbt Cloud using HEAD version
- dbt (working version): 1.4.0a1 HEAD at 2022-12-07T15:45:32.039789Z
- dbt (regression version): 1.4.0a1 HEAD at 2022-12-07T16:01:21.330798Z
```

### Which database adapter are you using with dbt?

bigquery

**Comment by lustefaniak** [comment]
Problem with timestamps, sometimes having timezone and sometimes not is also present in many dbt Cloud API endpoints.

**Comment by dbeatty10** [comment]
@lustefaniak Thanks for reporting this!

I was able to reproduce this for `run_results.json` using dbt-core 1.4.0a1 (bigquery). I didn't try reproducing this for `sources.json`, but trust it is being rendered in a timezone-naive fashion as reported.

Agreed that `started_at` and `completed_at` should both be timezone-aware when rendered with an ISO 8601 format in `run_results.json`. Timestamps within `sources.json` should be timezone-aware as well.

**Comment by peterallenwebb** [comment]
Note that this issue resolves if mashumaro is rolled back to 3.1.1. I'm currently looking into workarounds and the option of going back to that version.

**Comment by jtcohen6** [comment]
Related issue: https://github.com/Fatal1ty/mashumaro/issues/93

**Comment by peterallenwebb** [comment]
I got to the bottom of this issue in mashumaro and added my notes to the issue for them. Hopefully it will be enough information for them to fix it soon.
