### ISSUE TITLE
[CT-1653] [Bug] DBT uses wrong PROFILES_DIR, even if DBT_PROFILES_DIR env variable is set.

### ISSUE THREAD

**Issue by codycrossley** [dbt-labs/dbt-core#6436]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Using dbt-core 1.3.1, `dbt` commands are using the wrong `profiles.yml` file, despite being told which file to use by the `DBT_PROFILES_DIR` env variable. It will try to use a `profiles.yml` file that exists in the current working directory instead.

### Expected Behavior

`dbt` commands should use the `profiles.yml` located at the `DBT_PROFILES_DIR` directory when the environment variable is set; instead, it attempts to use the **local** `profiles.yml` file.

### Steps To Reproduce

I have defined the environment variable `DBT_PROFILES_DIR=/Users/my_username/.dbt/`

When I run `dbt debug --config-dir`, I get the following

```
16:04:00 Running with dbt=1.3.1
16:04:00 To view your profiles.yml file, run:

open /Users/my_username/.dbt
```

However, when I execute any `dbt run` command from a directory where another `profiles.yml` file exists, it attempts to use the local profile instead.

### Environment

```markdown
- OS:MacOS 12.6
- Python: 3.9
- dbt: 1.3.1
```

### Which database adapter are you using with dbt?

redshift

**Comment by jtcohen6** [comment]
@codycrossley Thanks for opening — I haven't been able to reproduce this locally:

```bash
$ DBT_PROFILES_DIR=/something/else dbt debug --config-dir
16:46:49  Running with dbt=1.3.1
16:46:49  To view your profiles.yml file, run:

open /something/else
```

Are you sure you're setting the env var correctly? What do you see if you run this in the same environment?
```bash
$ echo $DBT_PROFILES_DIR
```

**Comment by codycrossley** [comment]
Oh my god. I am so sorry. After all this time, I realized my env variable was `DBT_PROFILES_PATH` rather than `DBT_PROFILES_DIR`.

And when I ran the `debug` command, it was _outside_ of any directory that contained a `profiles.yml` file, so it defaulted to the `HOME/.dbt` directory.

Please forgive me for wasting precious time. 🙏

**Comment by jtcohen6** [comment]
@codycrossley No worries!! Glad you were able to get to the bottom of it :)
