### ISSUE TITLE
[CT-1665] [Feature] Surface ordinal_position in get_columns_in_relation

### ISSUE THREAD

**Issue by Fleid** [dbt-labs/dbt-core#6449]
The package [dbt-audit-helper](https://github.com/dbt-labs/dbt-audit-helper) offers `compare_relation_columns`, a macro that compares the metadata between two relations. Columns are compared by ordinal position.

The recommended way to get column metadata is to use `adapter.get_columns_in_relation()`, but this macro doesn't project `ordinal_position`.

So in `audit_helper`, for BigQuery, Postgres, Redshift, and Snowflake, that information has to be loaded directly from the information schema. The queries found in each adapter are [re-implemented](https://github.com/dbt-labs/dbt-audit-helper/blob/d76a87fde6a9786e04ffa2b9c4afd18cc9ea22fe/macros/compare_relation_columns.sql), just to get around the fact that ordinal_position is not projected originally.

For adapters other than BigQuery, Postgres, Redshift, and Snowflake, the ordinal position is inferred based on the response from core's `adapter.get_columns_in_relation()`, but it's brittle.

There are 2 ways forward:

1. Expose `ordinal_position` in `get_columns_in_relation`
2. Create a new `get_columns_in_relation_sql` that returns the SQL executed by `get_columns_in_relation` which can be used to get the column metadata
  - `get_columns_in_relation` : returns opinionated metadata
  - `get_columns_in_relation_sql` : returns the SQL string we use, with all the fields available

Current preference is number 2 - this could be a [new pattern](https://github.com/dbt-labs/dbt-core/issues/5318) we follow more generally?

In the meantime, [this](https://github.com/dbt-labs/dbt-audit-helper/pull/57) is happening.

Tagging @joellabes @dave-connors-3 @barberscott
Please let me know if I got this wrong ;)

**Comment by dave-connors-3** [comment]
@Fleid -- would the lower lift here be option 1? after yesterday's discussion, definitely keen to remove the need for adapter support from our packages if at all feasible!
