### ISSUE TITLE
[CT-1670] [Feature] `dbt deps` should consider `require-dbt-version` when deciding which package version to install.

### ISSUE THREAD

**Issue by elongl** [dbt-labs/dbt-core#6454]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I'll use `dbt-utils` as an example as it's a widespread and commonly-used package.
The package has various versions that comply with different version of dbt.
Here's roughly the matrix of them.
```
{
  "1.0.0": [">=0.8.0", "<0.9.0"],
  "1.1.0": [">=0.8.0", "<0.9.0"],
  "1.2.0": [">=0.9.0", "<1.0.0"],
  "default": [">=1.0.0"]
}
```

However, upon installing `dbt-utils`, I'd get the latest version regardless of my dbt version.
If I specified `[">=0.8.0", "<2.0.0"]` and my dbt version is 1.1.0, I'd still get `dbt-utils=1.0.0` regardless and then upon running `dbt` I'll get an error.

Instead, I would expect `dbt deps` to install `0.9.0` and let me know that newer versions are available (as it already does).

### Describe alternatives you've considered

I'm installing the appropriate version dynamically according to my `dbt_version`.

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: |
      {%- set minor_to_utils_range_map = {
        "0": [">=0.8.0", "<0.9.0"],
        "1": [">=0.8.0", "<0.9.0"],
        "2": [">=0.8.0", "<1.0.0"],
      } -%}
      {{- minor_to_utils_range_map.get(dbt_version.split('.')[1], [">=0.8.0", "<2.0.0"]) -}}
```

### Who will this benefit?

dbt package users and maintainers.

### Are you interested in contributing this feature?

Yes.

### Anything else?

I assume that the complexity is that the `require-dbt-version` is currently only stored as part of the codebase and therefore it's not possible to predict it before downloading it. I suppose this needs to be part of the registry's capabilities like it is on PyPI for instance with `py2` or `py3`.

**Comment by dbeatty10** [comment]
Hey @elongl ! 👋 

So I've got some good news and some bad news.

Good news:
- This feature was implemented and released in dbt-core 1.3.0 ([#5651](https://github.com/dbt-labs/dbt-core/pull/5651)) 👍

Bad news:
- This feature wasn't implemented and released _until_ dbt-core 1.3.0, so it won't work on versions earlier than that 😭 

### Feature in action
Here's how you can see it in action (assuming >= dbt-core 1.3)

`packages.yml`
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.7.0", "<0.8.0"]
```

Then:
```shell
dbt deps
```

You'll get output like:
```shell
$ dbt deps
Running with dbt=1.3.1
Encountered an error:
Could not find a matching compatible version for package dbt-labs/dbt_utils
  Requested range: >=0.7.0, <0.8.0
  Compatible versions: ['0.0.1', '0.1.0', '0.1.1', '0.1.2', '0.1.3', '0.1.4', '0.1.5', '0.1.6', '0.1.7', '0.1.8', '0.1.9', '0.1.10', '0.1.11', '0.1.12', '0.1.13', '0.1.14', '0.1.15', '0.1.16', '0.1.17', '0.1.18', '0.1.19', '0.1.20', '0.1.21', '0.1.22', '0.1.23', '0.1.24', '0.1.25', '0.2.0', '0.2.1', '0.2.2', '0.2.3', '0.2.4', '0.2.5', '0.3.0', '0.4.0', '0.4.1', '0.5.0', '0.8.0', '0.8.1', '0.8.2', '0.8.3', '0.8.4', '0.8.5', '0.8.6', '0.9.0', '0.9.1', '0.9.2', '0.9.5', '0.9.6', '1.0.0']

  Not shown: package versions incompatible with installed version of dbt-core
  To include them, run 'dbt --no-version-check deps'
```

Since I believe your request is the same as https://github.com/dbt-labs/dbt-core/issues/5648 which was resolved in https://github.com/dbt-labs/dbt-core/pull/5651, I'm going to close this as a duplicate. But please feel to continue the conversation here about your needs and use-case, and we can re-open this issue if it turns out that I closed it prematurely.

**Comment by dbeatty10** [comment]
### Your options going forward

I saw that you are trying to make it as easy as possible install and use the [elementary](https://hub.getdbt.com/elementary-data/elementary/latest/) package. ➕ for that goal!

As you are already well-versed, this is a bit tricky 😰 

Here are a handful of ideas (probably many or all of which you've already considered):
1. Divorce the `elementary` package entirely from `dbt_utils` by making copies of the macros you need into your package.
1. [Have the end users specify their version of dbt-utils](https://github.com/elementary-data/dbt-data-reliability/blob/bbec6517353869d7098bdc8ac7528caf2713df9f/README.md#quick-start) (:point_left: which I believe is your current strategy)
1. Support multiple long-lived versions of the package (targeting different ranges of dbt-core) that end users would need to choose between
1. Drop support going forward for dbt-core versions prior to 1.3

There's definitely trade-offs of each of these.

**Comment by elongl** [comment]
Hi @dbeatty10, thanks a lot for replying and sharing your thoughts on the topic.
Given that it's now implemented in 1.3.0, I believe we'd stick to the (2) strategy and with time potentially drop support for prior versions. It's good to know that we wouldn't have to keep maintaining the version matrix going forward (>1.3.0).

**Comment by dbeatty10** [comment]
Sure thing @elongl

I forgot to mention earlier -- I thought the jinja-based version matrix you described in your alternative was super clever!

**Comment by elongl** [comment]
@dbeatty10 Funny thing, it worked when I installed Elementary in development using the `local` method.
Later, we released it and upon installing it with `package` (registry) it does a semver validation and no longer works 😆
