### ISSUE TITLE
[CT-1671] [Bug] Nested macro in `if is_incremental()` block results in false negative `state:modified` selection when macro is modified

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#6455]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If you have a macro that's nested in an `if is_incremental()` block - it is not added to the model's `depends_on` node manifest 

### Expected Behavior

Model that depends on a modified macro should be executed even if the macro is nested in the `is_incremental()` condition.

### Steps To Reproduce

1. Setup models and macros:

```sql
-- macros/cond.sql
{% macro cond() %}
    where 1 = 1
{% endmacro %}

-- models/foo.sql
{{ config(materialized = 'incremental') }}

select 1 as id
{% if is_incremental() %}
{{ cond() }}
{% endif %}

-- models/bar.sql
{{ config(materialized = 'incremental') }}

select 1 as id
{{ cond() }}
```

> `dbt_project.yml` has nothing significant.

2. Run dbt and move state file for a subsequent run.

```
$ dbt run --full-refresh
20:28:57  Running with dbt=1.3.0
20:28:58  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 304 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
20:28:58  
20:29:02  Concurrency: 8 threads (target='dev')
20:29:02  
20:29:02  1 of 2 START sql incremental model dbt_jyeo.bar ................................ [RUN]
20:29:02  2 of 2 START sql incremental model dbt_jyeo.foo ................................ [RUN]
20:29:05  2 of 2 OK created sql incremental model dbt_jyeo.foo ........................... [SUCCESS 1 in 3.44s]
20:29:15  1 of 2 OK created sql incremental model dbt_jyeo.bar ........................... [SUCCESS 1 in 13.19s]
20:29:15  
20:29:15  Finished running 2 incremental models in 0 hours 0 minutes and 17.04 seconds (17.04s).
20:29:15  
20:29:15  Completed successfully
20:29:15  
20:29:15  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2

$ mv target target_old
```

3. Modify macro:

```sql
-- macros/cond.sql
{% macro cond() %}
    where 2 = 2
{% endmacro %}
```

5. Run dbt comparing state to the above run.

```
$ dbt run -s state:modified --defer --state target_old
20:31:50  Running with dbt=1.3.0
20:31:51  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 304 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
20:31:51  
20:31:55  Concurrency: 8 threads (target='dev')
20:31:55  
20:31:55  1 of 1 START sql incremental model dbt_jyeo.bar ................................ [RUN]
20:31:59  1 of 1 OK created sql incremental model dbt_jyeo.bar ........................... [SUCCESS 1 in 4.30s]
20:31:59  
20:31:59  Finished running 1 incremental model in 0 hours 0 minutes and 8.10 seconds (8.10s).
20:31:59  
20:31:59  Completed successfully
20:31:59  
20:31:59  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

Notice model `foo` which has `cond()` nested in the `is_incremental()` block is not selected even though the macro it uses _has_ been modified.

### Environment

```markdown
- OS: macOS
- Python: 3.8.7
- dbt: 1.3, 1.2
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Interestingly if we peek at both `manifest.json` files - we see that the `depends_on` for model `foo` has a missing `macro.my_project.cond` string in the `macros` key in the _current_ state - I think this should actually flag it for `state:modified` yes? The `macro.my_project.cond` appearing _after_ `macro.dbt.is_incremental` in the previous / deferred to state is reminiscent of https://github.com/dbt-labs/dbt-core/issues/5202

![image](https://user-images.githubusercontent.com/8496748/208318408-2f6e850d-f745-45a4-8d1e-6241818b3845.png)

**Comment by ernestoongaro** [comment]
Related to https://github.com/dbt-labs/dbt-core/issues/5922

**Comment by jtcohen6** [comment]
Another related (older) issue: https://github.com/dbt-labs/dbt-core/issues/5079

The right move for now might just be to document this as a known limitation here: https://docs.getdbt.com/reference/node-selection/state-comparison-caveats

### Workaround

```
-- models/foo.sql
{{ config(materialized = 'incremental') }}

-- force this model to take a dependency on the 'cond()' macro
-- {{ cond() }}

select 1 as id
{% if is_incremental() %}
{{ cond() }}
{% endif %}
```

### Explanation

This has to do with some deep-down fundamentals of how we parse models today, which is actually by rendering Jinja. Any instances of `{% if execute %}` act as a "logic gate" that gets completely skipped over at parse time. is_incremental() contains an implicit if execute check here: https://github.com/dbt-labs/dbt-core/blob/748a9328117d601560f056f3186e6a52572ff7a2/core/dbt/include/global_project/macros/materializations/models/incremental/is_incremental.sql#L4

dbt does Jinja rendering at parse time to capture macro calls, principally for ref/source/config, but for also to populate `depends_on.macros`. If there are logic gates at parse time that the Jinja skips over, parsing completes without dbt knowing they're there. To get around this, we'd need to fundamentally change how we parse complex Jinja models, and switch to statically analyzing the code, whether with Jinja's AST or another mechanism we build.
