### ISSUE TITLE
[CT-1675] [Bug] dbt shows no tests when a custom test is missing rather than throwing a compilation error

### ISSUE THREAD

**Issue by prgx-aeveri01** [dbt-labs/dbt-core#6457]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

when executing a `dbt run / build / test` on a model with a custom test that does not exist in the project all other tests for that model are ignored.

### Expected Behavior

Either throw a compilation error for the missing test and error out or continue to run the tests that do exist.

### Steps To Reproduce

1. Assign a test to a model (at table level in my example) that does not exist.
2. Assign other tests to the fields of the same model
3. Run `dbt test --select [your model]`
4. Dbt should show that there are no tests for that model

### Relevant log output

```shell
`[WARNING]: Nothing to do. Try checking your model configs and model specification args`
```

### Environment

```markdown
- OS:Ubuntu 20.4
- Python:3.7.6
- dbt:1.3.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Trino connector

**Comment by dbeatty10** [comment]
Thanks for reporting this @prgx-aeveri01 !

I wasn't able to reproduce this behavior in a local environment (I tried it with dbt-bigquery).

Could you try out the following and see if it gives you the same error or not?

`models/my_simple_model.sql`
```
select 1 as id
```

`models/_models.yml`
```
version: 2

models:
  - name: my_simple_model
    tests:
      - asdf
    columns:
      - name: id
        tests:
          - unique
```

This failed with an appropriate error message for me:
```
dbt test --select my_simple_model
```

Error message:
```
Completed with 1 error and 0 warnings:
Compilation Error in test asdf_my_simple_model_ (models/_models.yml)
  'test_asdf' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
```

**Comment by prgx-aeveri01** [comment]
Hey @dbeatty10 , i'll try this today and get straight back to you.

**Comment by prgx-aeveri01** [comment]
Ok, that works no problem. It must be something in my setup.

**Comment by dbeatty10** [comment]
> Ok, that works no problem. It must be something in my setup.

The hunt for the root cause continues!

To take action on the issue, we'll ultimately need to discover a minimal reproducible example. But I'm happy to go back and forth as long as you want to try narrowing it down. It's also okay if we throw our hands up at some point. I'll follow your lead.

**Comment by prgx-aeveri01** [comment]
@dbeatty10 , close it off for now... i'll keep hunting!

**Comment by dbeatty10** [comment]
> @dbeatty10 , close it off for now... i'll keep hunting!

👍 Sounds good @prgx-aeveri01, just reach out here if you're able to find it and we'll re-open the issue.
