### ISSUE TITLE
[CT-1679] Python Materialization 

### ISSUE THREAD

**Issue by reletreby** [dbt-labs/dbt-core#6459]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Running a simple Python module (Amazon Redshift) gives

`Materialization "materialization_table_default" only supports languages ['sql']; got "python"`

The model I am running is
`def model(dbt,session):
    dbt.config(materialized="table")
    return session.sql("select 'hello world' as message")`

and I run it as
`pipenv run dbt run --models intermediate.python_models.python_template --target qa`

and I have the following versions
`Core:
  - installed: 1.3.1
  - latest:    1.3.1 - Up to date!

Plugins:
  - redshift: 1.3.0 - Up to date!
  - postgres: 1.3.1 - Up to date!`

### Expected Behavior

I expect not to see this error as `python` should be supported!

### Steps To Reproduce

I have added information in the body of the issue above

### Environment

```markdown
- OS: Mac OSX M1
- Python: 3.8.16
- dbt:1.3.1
- Amazon Redshift
```

**Comment by owenprough-sift** [comment]
https://docs.getdbt.com/docs/build/python-models#supported-data-platforms
> In their initial launch, Python models are supported on three of the most popular data platforms: Snowflake, Databricks, and BigQuery/GCP (via Dataproc). 

Is this issue therefore "please bring Python models to Redshift"?

**Comment by dbeatty10** [comment]
> Is this issue therefore "please bring Python models to Redshift"?

That's what I'm hearing @owenprough-sift 😎 

Thanks for opening this issue @reletreby ! As noted by @owenprough-sift above, we don't currently support Python models in Redshift, and that is why you are getting that error message.

We do have an issue open for adding Python models, so I'm going to close this one as a duplicate. You can subscribe to it if you want to get notifications (see screenshot below for how to subscribe):
- https://github.com/dbt-labs/dbt-redshift/issues/204

Go to https://github.com/dbt-labs/dbt-redshift/issues/204 and click this button on the right hand side of your screen to subscribe:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/44704949/208536503-44589e92-70d4-47ef-b272-cb8ec6245518.png">

**Comment by arybach** [comment]
From docs:
"In a dbt Python model, all Python code is executed remotely on the platform. None of it is run by dbt locally. We believe in clearly separating model definition from model execution".
Is there a way to specify where python code is run (at least for testing purposes) or pass an archive similar to aws lambda function setup? 
This would be my next issue after postgres support is live)
