### ISSUE TITLE
[CT-1688] [Feature] Remove packaging <22 version cap

### ISSUE THREAD

**Issue by smackesey** [dbt-labs/dbt-core#6461]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This isn't really a "feature", but no other category fit. Please consider lifting `dbt-core`'s current upper version bound of `packaging<22`, it prevents installation in the same environment as tox 4, and I doubt the cap actually needs to be there-- just delete any references to `packaging.LegacyVersion` (which used to be a possible return from `packaging.version.parse`) and you can probably remove it.

### Who will this benefit?

Anyone working with `dbt-core` in an environment with a lot of other packages, and in particular in a dev environment with tox 4.

### Are you interested in contributing this feature?

I'd be happy to put up a PR, I grepped dbt-core codebase and packaging only used in a few places

**Comment by dbeatty10** [comment]
Thanks for noticing this @smackesey !

We'd welcome your contribution on this. [Here's](https://github.com/dbt-labs/dbt-core/pull/5218/files) a similar PR you can use as an example. Obviously, your PR might be a little more involved depending on what you find.

Feel free to let me know if you run into any issues with the [contributing instructions](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#contributing-to-dbt-core).

**Comment by smackesey** [comment]
Thanks @dbeatty10, as you can see I've opened a PR. I'd also like to make a more general point, which is that dbt (both core and other packages) are very aggressive with version capping-- it looks like caps are put on almost all dependencies as a matter of course, rather than only when specifically required.

Every version cap raises the probability of a versioning conflict with other libraries. Dbt's caps have caused us build pains over at [Dagster](https://github.com/dagster-io/dagster) a few times-- see [here](https://github.com/dbt-labs/dbt-core/issues/4833) for an older similar issue. In fact there is another issue even now, which is that the [dbt-snowflake](snowflake-connector-python) cap on `snowflake-connector-python` is conflicting with some of our packages (not sure how exactly, but it's causing build failures).

Dbt is a library likely to be used with all manner of other python packages, and dbt's aggressive version caps  are probably causing your users more pain than you realize. As a fellow library developer in the data engineering space, I'd like to humbly request you reconsider your version capping philosophy, to a "cap only when needed" approach. If a new version of a library comes out that breaks dbt, your CI should catch it immediately and you can introduce a cap at that time.

A gentleman by the name of Henry Schreiner wrote something approximating a [small novel](https://iscinumpy.dev/post/bound-version-constraints/) on the subject of version caps in python libs-- it's a good read (even just the intro) for anyone trying to really understand this issue. Thanks.

**Comment by dbeatty10** [comment]
Resolved by https://github.com/dbt-labs/dbt-core/pull/6838
