### ISSUE TITLE
[CT-1711] [Bug]  Materialization "materialization_table_trino" only supports languages ['sql']; got "python" in dbt-core 1.3.0 and 1.3.1

### ISSUE THREAD

**Issue by curiosityCursed** [dbt-labs/dbt-core#6476]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

def model(dbt,session):
    df = dbt.ref('<view>')
    return df
    
07:58:55  Completed with 1 error and 0 warnings:
07:58:55  
07:58:55  Runtime Error in model <model> (models/./././<model>.py)
07:58:55    Materialization "materialization_table_trino" only supports languages ['sql']; got "python"

### Expected Behavior

def model(dbt,session):
    df = dbt.ref('<view_model>')
    return df
    
    
Should be able to create python model referencing the view model.

### Steps To Reproduce

1. Create a new view model under models/. folder.
2. Create a python model which references the above view.
3. dbt run --select <view_model> <python_model>

### Relevant log output

```shell
07:58:55  Finished running 2 view models, 1 table model in 0 hours 0 minutes and 2.80 seconds (2.80s).
07:58:55  
07:58:55  Completed with 1 error and 0 warnings:
07:58:55  
07:58:55  Runtime Error in model <model> (models/./././<model>.py)
07:58:55    Materialization "materialization_table_trino" only supports languages ['sql']; got "python"
07:58:55  
07:58:55  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
```

### Environment

```markdown
- OS:macOS Monterey 12.6
- Python: 3.96
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Trino

**Comment by dbeatty10** [comment]
Thank you for reaching out about this @curiosityCursed !

> In their initial launch, Python models are supported on three of the most popular data platforms: Snowflake, Databricks, and BigQuery/GCP (via Dataproc) [[1]](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/python-models#specific-data-platforms)

I think the reason you are getting this error is that dbt-trino doesn't currently support dbt Python models.

Although we can't help you directly, here's a couple options for you:
1. [Open a feature request at dbt-trino](https://github.com/starburstdata/dbt-trino/issues/new?assignees=&labels=enhancement&template=feature_request.yml)
1. Take a look at https://fal.ai/

I'm closing this in favor of the options above, but please reach out again with any bug reports or feature requests!

**Comment by curiosityCursed** [comment]
@dbeatty10 Thanks for quick response.
