### ISSUE TITLE
[CT-1712] [Bug] information schema columns not included in dbt docs for non-default database

### ISSUE THREAD

**Issue by rtooker** [dbt-labs/dbt-core#6477]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

With a default database `profiles.yml` of e.g. `ods`:

```yaml
my_project:
  target: local
  outputs:
    local:
      database: 'ods'
```

and over-ridden database of e.g. `dwh` for some model paths in `dbt_project,yml`:

```yaml
models:
  my_project:
    marts:
       +database: `dwh`
```

Dbt docs generate only includes information schema information (columns not in models, data types for all columns) for models in the default database of `ods` and not the over-ride of `dwh`.

### Expected Behavior

dbt docs should include information schema information for models in databases other than the default.

### Steps To Reproduce

Override the database in config as above, then:

`dbt compile [other args]`
`dbt docs generate --no-compile`

Note that `catalog.json` only includes tables in the default database.

Note that columns do not contain full information in the documentation for non-default databases.

### Environment

```markdown
- OS: Windows 10
- Python: 3.10.1
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

sqlserver

**Comment by dbeatty10** [comment]
Thanks for reaching out @rtooker !

Using dbt-snowflake, I created a `dbt_project.yml` like you described:
```yaml
models:
  my_dbt_project:
    +materialized: table
    marts:
       +database: analytics
       +schema: DBT_DBEATTY_DBT_UTILS
```

My `profiles.yml` has the following default database:
```yaml
      database: JAFFLE_SHOP
```

Then created a (very simple) model in the marts folder:
`models/marts/my_little_table.sql`
```sql
select 1 as my_number
```

After running `dbt docs generate`, I could see this model in my `target/catalog.json`:
`jq . target/catalog.json > target/catalog.pp.json`
```json
    "model.my_dbt_project.my_little_table": {
      "metadata": {
        "type": "BASE TABLE",
        "schema": "DBT_DBEATTY_DBT_DBEATTY_DBT_UTILS",
        "name": "MY_LITTLE_TABLE",
        "database": "ANALYTICS",
        "comment": null,
        "owner": "TRANSFORMER"
      },
    ...
```

And running `dbt docs serve` gave me this:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/44704949/209410446-a86196aa-08bb-4fe1-9ff8-fbbed75bce4d.png">

It sounds like you might be using the [dbt-sqlserver](https://github.com/dbt-msft/dbt-sqlserver) adapter?

Based on the above, this doesn't look like a bug in dbt-core to me, and I suspect that it is an edge case not covered within the dbt-sqlserver adapter. Could you try [opening an issue](https://github.com/dbt-msft/dbt-sqlserver/issues/new) there instead?

I'm going to close this in the meantime, but we can open it back up again if it doesn't indeed turn out to be a bug in dbt-core.
