### ISSUE TITLE
[CT-1714] [Feature] merge main into feature/click-cli branch

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#6478]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Do the merge so we can get logging refactor onto one branch

**Comment by leahwicz** [comment]
@ChenyuLInx can we close this out?

**Comment by ChenyuLInx** [comment]
Yes, Somehow the pr didn't close this automatically
