### ISSUE TITLE
[CT-1716] Combine ProfileListTitle, ListSingleProfile, NoDefinedProfiles and ProfileHelpMessage into a single event.

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#6479]
### Describe the feature

The ProfileListTitle, ListSingleProfile, NoDefinedProfiles and ProfileHelpMessage events should be combined into a more succinct and helpful event. The unified event should have fields for the list of the profiles defined, if any, and a help message.

### Who will this benefit?

Consumers of structured logs will benefit from a simpler event schema with the same information, but better organized.

**Comment by jtcohen6** [comment]
resolved by https://github.com/dbt-labs/dbt-core/pull/6561
