### ISSUE TITLE
[CT-1717] Combine Events With Their "Exception" Equivalents

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#6480]
### Describe the feature

Combine DbtProfileError and DbtProfileErrorException into a single event. Also combine DbtProjectError and DbtProjectErrorException into a single event. The unified events could include an "Exception" field which includes the exception message and stack trace, but which is only used when the error is the result of an exception.

### Who will this benefit?

This change will benefit structured log consumers by making it easier to monitor for project and profile errors, without having to understand and listen for multiple events which overlap, conceptually.

**Comment by jtcohen6** [comment]
resolved by https://github.com/dbt-labs/dbt-core/pull/6561
