### ISSUE TITLE
[CT-1718] Add an "FYI" Message Type

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#6481]
### Describe the feature

Sometimes we have messages we would would like to write to the console without creating a custom event type. For example, we often want to add formatting by inserting blank lines or break lines like "=====...". We also have a variety of messages we print for informational purposes, but which are unlikely to be consumed programmatically by structured logging users.

To solve this problem, let's introduce a new event type which contains the standard event fields, but only one additional field (called "Text" or "Message"?) which can include miscellaneous text and formatting.

After this change, we should also be able to remove the EmptyLine event.

### Who will this benefit?

Consumers of structured logging will benefit from this change, since they will no longer see events like EmptyLine which are useless to them. Since this change will also make it possible to remove other events, like StarterProjectPath and project initialization related events, it will reduce the complexity and size of our event schema.

**Comment by jtcohen6** [comment]
resolved by https://github.com/dbt-labs/dbt-core/pull/6561

**Comment by jtcohen6** [comment]
Sorry! This was _not_ included in #6561
