### ISSUE TITLE
[CT-1719] Combine All Cache Events into a Single Event

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#6482]
### Describe the feature

Today, there are a large number of events inheriting from the Cache class, which all capture information about similar operations. We would like to combine these into a single event, which indicates the sub-type in an enumeration field.

### Who will this benefit?

Structured log consumers will benefit from a simpler and easier to understand event schema.

**Comment by gshank** [comment]
This was included in a different ticket (#6561)
