### ISSUE TITLE
[CT-1729] rpc requests fail on dbt version 1.3.1

### ISSUE THREAD

**Issue by dima898** [dbt-labs/dbt-core#6487]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am running dbt-rpc server with following packages:
dbt-snowflake==1.3.0
dbt-rpc==0.2.1
On executing any rpc request (like status check), rpc server returns following response:
`TypeError: _get_responses() takes 3 positional arguments but 4 were given`

Downgrading packages to earlier version returns same results.

### Expected Behavior

rpc server must return correct respose

### Steps To Reproduce

1. Environment with following packages:
dbt-snowflake==1.3.0
dbt-rpc==0.2.1
2. run server status check like following:
{
    "jsonrpc": "2.0",
    "method": "status",
    "id": "2db9a2fe-9a39-41ef-828c-25e04dd6b07d"
}
3. get the following error:
TypeError: _get_responses() takes 3 positional arguments but 4 were given

### Relevant log output

```shell
Installing dbt packages 
16:20:16  Running with dbt=1.3.1
16:20:17  Installing dbt-labs/dbt_utils
16:20:19    Installed from version 0.9.1
16:20:19    Updated version available: 1.0.0
16:20:19  
16:20:19  Updates available for packages: ['dbt-labs/dbt_utils']                 
Update your versions in packages.yml, then run dbt deps
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/wrappers/request.py", line 187, in application
    resp = f(*args[:-2] + (request,))
  File "/usr/local/lib/python3.8/site-packages/dbt_rpc/task/server.py", line 152, in handle_jsonrpc_request
    jsonrpc_response = ResponseManager.handle(
  File "/usr/local/lib/python3.8/site-packages/dbt_rpc/rpc/response_manager.py", line 143, in handle
    result = cls.handle_valid_request(
  File "/usr/local/lib/python3.8/site-packages/dbt_rpc/rpc/response_manager.py", line 88, in handle_valid_request
    return cls.handle_request(request, dispatcher)
  File "/usr/local/lib/python3.8/site-packages/jsonrpc/manager.py", line 75, in handle_request
    responses = [r for r in cls._get_responses(rs, dispatcher, context)
TypeError: _get_responses() takes 3 positional arguments but 4 were given
```

### Which database adapter are you using with dbt?

snowflake

**Comment by timopetmanson** [comment]
Could be related to `json-rpc` dependency update that happened on Christmas [[json-rpc PyPi](https://pypi.org/project/json-rpc/#history)] + this change in `setup.py`?
https://github.com/dbt-labs/dbt-rpc/commit/43a13999441268d220236bc230791554daa78320

**Comment by jtcohen6** [comment]
@timopetmanson is spot on. We've fixed this for now by capping the version of `json-rpc` required by `dbt-rpc`: https://github.com/dbt-labs/dbt-rpc/pull/114

If you're using an older version of `dbt-rpc` with an older version of `dbt-core`, you should specify the explicit dependency version yourself:
```
json-rpc<1.14.0
```

There's another open issue that proposes updating the `dbt-rpc` code for compatibility with the changes in `json-rpc==1.14.0`: https://github.com/dbt-labs/dbt-rpc/issues/116

This problem is limited to `dbt-rpc`, and that's the place where we'll want to make the fix. I'm going to close this `dbt-core` issue in the meantime.
