### ISSUE TITLE
[CT-1731] [Bug] tests run in CI when `DBT_DEBUG=true` environment is set

### ISSUE THREAD

**Issue by moltar** [dbt-labs/dbt-core#6489]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have some unexplained behaviour that I hope someone can shine some light on.

It appears that when dbt runs in the AWS CodeBuild environment, it executes the tests by default, without instructions to do that.

The command that runs in the AWS CodeBuild environment looks like this:

```sh
dbt --warn-error run || dbt --warn-error run --state target/ --select result:error+
```

As you can see, I am using run, which shall not target tests. And if the run fails, then we re-run only failed models, so again, not targeting tests.

Meanwhile, I am seeing the following in the logs _(edited)_:

```json
{
  "code": "Q023",
  "data": {
    "node_info": {
      "materialized": "test",
      "node_finished_at": null,
      "node_name": "dbt_utils_expression_is_true_fct_foo___0",
      "node_path": "dbt_utils_expression_is_true_f_49215d44b179a2b5b54b93c412284f7b.sql",
      "node_started_at": "2022-12-26T14:02:16.723982",
      "node_status": "started",
      "resource_type": "test",
      "unique_id": "test.foo.dbt_utils_expression_is_true_fct_foo_v1_cost___0.96393ad610"
    },
    "unique_id": "test.foo.dbt_utils_expression_is_true_fct_foo_cost___0.96393ad610"
  },
  "invocation_id": "19995c96-4a77-4713-bfa4-cdc717528df9",
  "level": "debug",
  "log_version": 2,
  "msg": "Began running node test.foo.dbt_utils_expression_is_true_foo___0.96393ad610",
  "pid": 712,
  "thread_name": "Thread-1",
  "ts": "2022-12-26T14:02:16.724244Z",
  "type": "log_line"
}
```

The only difference between my dev environment and AWS CodeBuild would be some environment variables that we set, and also the default ones set by CodeBuild itself:

```
DBT_PROFILES_DIR: .
DBT_PACKAGES_INSTALL_PATH: /root/.cache/dbt_packages
DBT_LOG_FORMATL: json
DBT_DEBUG: true
DBT_ANONYMOUS_USAGE_STATS: false
```

I am wondering if any environment variables (whether ours or CodeBuild ones) could have an effect on which models are executed.

I have narrowed this down to flipping the `DBT_DEBUG` flag, but with the same flag set to `true` in the local environment, I am not observing the same problem. So it must be some combination of flags.

### Expected Behavior

Tests should not run, if not requested.

### Steps To Reproduce

See the main issue body.

### Relevant log output

```shell
See the main issue body.
```

### Environment

```markdown
- OS: Local: macOS / Remote: CodeBuild Amazon Linux
- Python: 3.8
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

N/A

**Comment by dbeatty10** [comment]
Thanks for reaching out @moltar

Off the top of my head, I can't think of a combination of environment variables (whether yours or CodeBuild ones) that would have an effect on which models are executed.

I wasn't able to reproduce this in a local environment, and I don't have a AWS CodeBuild environment handy either, but I'll try my best to help uncover what might be going on.

Assuming that you have a small sample project you are using for troubleshooting within CodeBuild, could you provide the entire log output starting with `{"code": "A001", "data": {"v": "=1.3.0"} ...` and ending with `{"code": "Z042", "data": {}, "invocation_id" ...`?

Separately, could you try the following two environment variables settings and see what the output is within CodeBuild?
- `DBT_LOG_FORMAT=text`
- `DBT_DEBUG=false`
