### ISSUE TITLE
[CT-1746] Flags.MP_CONTEXT is not JSON serializable

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6509]
One of the many exceptions raised during integration test runs on the feature/click-cli branch is: 

`TypeError: Object of type SpawnContext is not JSON serializable`

There are a [couple options](https://github.com/dbt-labs/dbt-core/pull/6504#issuecomment-1371002518) to mitigate the issue:
1. Remove MP_CONTEXT from flags (where would be the best place to put it instead?)
2. Avoid serializing MP_CONTEXT

**Comment by iknox-fa** [comment]
@ChenyuLInx Can you make sure that this has been fixed?  Per BLG we really think this doesn't belong in flags and should re-locate it-- will open a ticket for that work.
