### ISSUE TITLE
[CT-1751] Config to optionally skip population of relation cache

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6526]
Users should have the ability to turn off relation cache population, if they really need to. It should still be "on" by default.

```bash
$ dbt --no-populate-cache [run|test|...]
$ DBT_POPULATE_CACHE=0|1 dbt [run|test|...]
```
```yml
# profiles.yml (UserConfig)
config:
  populate_cache: true|false
```

This is different from entirely disabling or skipping over the cache — we're just skipping the population of the cache on startup. When dbt needs to run caching queries, I think it should still report "cache miss," and then cache the result of the metadata query, if it needs to be used again in the same invocation.

### Where

https://github.com/dbt-labs/dbt-core/blob/54538409509e0d677876f1102aa3bc0c67007278/core/dbt/task/runnable.py#L407-L421

### Who is it for?
- Users in large projects, or of data warehouses that are quite slow at running metadata queries.
- Users running into inexplicable issues with specific relations not showing up in the relation cache (https://github.com/dbt-labs/dbt-core/issues/6050)
- Interactive compile & preview (#6358, #6359), which need to be blazing-fast

### YMMV
End users will need to experiment with the approach that's most efficient for them, between:
- full cache enabled
- "cache selected only" ([docs](https://docs.getdbt.com/reference/global-configs#cache-database-objects-for-selected-resource))
- `--no-populate-cache`

I expect mileage may vary between dev, CI, and prod environments.

### Questions

Would this break behavior around `--defer`, which expects to use the relation cache to determine if model X already exists in the dev schema, or should have its reference rewritten to use the schema defined in the other manifest?

https://github.com/dbt-labs/dbt-core/blob/54538409509e0d677876f1102aa3bc0c67007278/core/dbt/contracts/graph/manifest.py#L1018

Imagining a future where interactive compile/preview want to be _both_ very fast, and able to correctly leverage `--defer`: We should also think more about making the adapter cache pluggable, as something that can live & persist outside of a single `dbt-core` invocation. It would be the responsibility of that other application wrapping `dbt-core` to handle cache invalidation (fun!).

**Comment by AnotherGuitar** [comment]
We're using the dbt-databricks adaptor and would be very interested in seeing this feature get developed because compile times are taking a while for us. Thanks for writing up this issue!
