### ISSUE TITLE
[CT-1758] [Bug] dbt  process is never reaped，occur a large number of zombie processes.

### ISSUE THREAD

**Issue by abeizn** [dbt-labs/dbt-core#6533]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Every time I execute the dbt project, a python zombie process will be added.

![image](https://user-images.githubusercontent.com/101256042/210975162-b9d85790-95bd-4f1d-9f4d-1f59b53f2be3.png)

I also found that other people used the dbt project to have this problem（ https://github.com/python/cpython/issues/88887 ）. It may be a python problem, but I still want to confirm that dbt is also caused by this? Is there any good solution?

and i try to add threads=1, but It still appears zombie process.

### Expected Behavior

occur a large number of zombie processes.

### Steps To Reproduce

run dbt project by golang cmd.Command().
![image](https://user-images.githubusercontent.com/101256042/210976015-3f8aa4e0-d70b-471d-ae54-478e37cb78cc.png)

### Environment

```markdown
- OS: CentOS Linux release 7.9.2009
- Python: 3.9.13
- dbt:1.3.0
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Thanks for reporting this @abeizn !

I don't immediately know what is happening here since I don't know a lot about defunct / zombie / orphaned processes (or how best to clean them up via adoption / reaping).

Reading [here](https://www.back2code.me/2020/02/zombie-processes/#killing-zombies) and [here](https://docs.docker.com/engine/reference/run/#specify-an-init-process), it notes that standard Docker containers do not include `init` process by default and can accumulate orphans unless removed from the system via a wait.

The solution they propose is using the [Docker `--init` flag](https://docs.docker.com/engine/reference/run/#specify-an-init-process).

Are you observing this problem when using Docker, by any chance? If so, does adding `--init` solve the problem?

Also, does the following part successfully prevent zombie processes for you? Or is it not working as intended?
```go
    // prevent zombie process
    defer func() {
        err := errors.Convert((cmd. Wait ()))

        if err != nil {
            log.Error(err, "The DBT project run failed!")
        } else {
            log. Info("The DBT project run ended.")
    }()
```

**Comment by abeizn** [comment]
@dbeatty10 Thank you very much, I also found out that it is a docker problem.

**Comment by babaMar** [comment]
> Thanks for reporting this @abeizn !
> 
> I don't immediately know what is happening here since I don't know a lot about defunct / zombie / orphaned processes (or how best to clean them up via adoption / reaping).
> 
> Reading [here](https://www.back2code.me/2020/02/zombie-processes/#killing-zombies) and [here](https://docs.docker.com/engine/reference/run/#specify-an-init-process), it notes that standard Docker containers do not include `init` process by default and can accumulate orphans unless removed from the system via a wait.
> 
> The solution they propose is using the [Docker `--init` flag](https://docs.docker.com/engine/reference/run/#specify-an-init-process).
> 
> Are you observing this problem when using Docker, by any chance? If so, does adding `--init` solve the problem?
> 
> Also, does the following part successfully prevent zombie processes for you? Or is it not working as intended?
> 
> ```go
>     // prevent zombie process
>     defer func() {
>         err := errors.Convert((cmd. Wait ()))
> 
>         if err != nil {
>             log.Error(err, "The DBT project run failed!")
>         } else {
>             log. Info("The DBT project run ended.")
>     }()
> ```

hi @dbeatty10 do you know a similar solution when running on a K8s pod? I've been observing exactly the same problem, and the docker solution works locally indeed. Need to translate that in the actual deployment setting on K8s

**Comment by dbeatty10** [comment]
@babaMar I don't know about a similar solution on a K8s pod. Do let us know if you're able to translate that to a deployment setting on K8s.

**Comment by babaMar** [comment]
> @babaMar I don't know about a similar solution on a K8s pod. Do let us know if you're able to translate that to a deployment setting on K8s.

Found the issue, https://github.com/kubernetes/kubernetes/issues/84210 but it seems not progressing. I ended up using `dumb-init` and changing my entrypoint from the Dockerfile
