### ISSUE TITLE
[CT-1759] `dbt parse` should (over)write `manifest.json` by default

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6534]
That's it, that's the issue.

https://github.com/dbt-labs/dbt-core/blob/d43c070007b823588e7a170c6c37495ce319b011/core/dbt/task/parse.py#L97-L99

I find it mildly annoying that I can't use just `dbt parse`, when all I want to do is update `manifest.json` with the latest project contents, often for manual inspection / debugging.

We can make this opt-out (with a `--no-write-manifest` argument), instead of opt-in (with a `--write-manifest` flag as it is today).

**Comment by gshank** [comment]
@jtcohen6 In my protobuf nodes branch I added a bit to write out the manifest.json when we write out the partial parse manifest.  I hadn't thought about the implications for the "parse" command, but that change would have made the '--write-manifest' flag a no-op.  (as a side note, when I wrote the parse command I wanted to write out the manifest.json but was overruled, so the --write-manifest thing was a compromise).  I could pull that change out of the protobuf nodes branch if we want to move that bit up...

**Comment by jtcohen6** [comment]
> as a side note, when I wrote the parse command I wanted to write out the manifest.json but was overruled, so the --write-manifest thing was a compromise

overruled! by me?? quite possibly

> I could pull that change out of the protobuf nodes branch if we want to move that bit up...

I'm just happy to have this change happen, I don't feel strongly that it must happen immediately

**Comment by jtcohen6** [comment]
Resolved by #6565
