### ISSUE TITLE
[CT-1763] [Feature] Configurable behavior for `print`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6543]
In addition to the simple default behavior (Python's `print` function &rarr; stdout), which is fine for CLI use, we should support programmatic invocations, where printing to `stdout` doesn't make sense. We could do this with a "print" event/log instead, probably with a special level.

If we do go the logging route, we'd need to respect these flags:
- `--quiet`: suppress all log messages from stdout, _except_ those with the special "print" level
- `--no-print`: suppress all "print"-level log messages from stdout

Implementation options:
1. In all current call sites for `print`, we add conditional logic that either `print`s, or fires an event specific to that call site. (E.g. `CustomMacroPrint`, `ListResult`)
2. We add a single new event type, `PrintMessage`. We swap out 1:1 all direct calls to `print` with a new custom "print" method, defined either in [`clients.system`](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/clients/system.py) or the [`events` module](https://github.com/dbt-labs/dbt-core/tree/main/core/dbt/events), and define the conditional logic (to print or not to print) one time in that method.

## Current call sites

There are three primary places in the codebase where we call `print` today, plus a few miscellaneous others. 

### 1. `print` dbt-Jinja context member

a.k.a. the ["codegen"](https://github.com/dbt-labs/dbt-codegen) use case

https://github.com/dbt-labs/dbt-core/blob/94d6d19fb43f1ed466c9049dea40e203b23f89da/core/dbt/context/base.py#L640-L656

This should optionally fire an event, instead of just calling `print`.

### 2. `dbt list`

We definitely need a way to make the results of `list` available programmatically. But that might already be the case—we already _both_ `print` the results, _and_ return them as the task result:
https://github.com/dbt-labs/dbt-core/blob/94d6d19fb43f1ed466c9049dea40e203b23f89da/core/dbt/task/list.py#L150-L154

So when the new CLI/API supports `list` (https://github.com/dbt-labs/dbt-core/issues/5549), we should expect the `list` results being returned like:
```python
from dbt.cli.main import dbtRunner
dbt = dbtRunner()
results, success = dbt.invoke(['list', '--select', 'some_model+'])
# 'results' now contains the list of selected nodes
```

In the spirit of completeness, I think it makes sense to opt for sending a structured logging event for each `list` result, instead of printing it to stdout (default). It should be possible to suppress those in-lieu-of-printing events via the `--no-print` flag described above.

### 3. `dbt debug`

This is pretty clearly a case where we want actual events/logs, and not just text `print`ed to stdout.

Already open in https://github.com/dbt-labs/dbt-core/issues/5353
Proposed resolution in https://github.com/dbt-labs/dbt-core/pull/6541

### 4. Misc other spots

In `dbt init` — this is probably just an oversight, I believe there should be an event manager available:
https://github.com/dbt-labs/dbt-core/blob/94d6d19fb43f1ed466c9049dea40e203b23f89da/core/dbt/task/init.py#L284

In our functional testing framework — nbd

**Comment by peterallenwebb** [comment]
Does this overlap with #6481, our message-only "FYI" event type?

**Comment by ChenyuLInx** [comment]
Talked about this live, the path forward would be
- make those messages `print` type event 
- add additional logic in std logger to make sure we don't add the timestamp when receive `print` type event.

Will create new implementation ticket for it.

**Comment by jtcohen6** [comment]
Let's open as a new issue.

We believe `dbt debug` has been resolved.

Targeting the two important remaining pieces:
1. User `print` method. We want this to always be a logging event, but without timestamp/formatting in stdout. Convert to `UserPrint` event.
2. `dbt list` with non-JSON logging. We want this to always be a logging event, but without timestamp/formatting in stdout. Convert to always use `ListCmdOut`.

So we need new behavior for the text-formatted stdout logger, to include timestamp/formatting by default, but not for:
- `UserPrint` or `ListOutput` events

Acceptance criteria:
- Tests for stdout text-formatted, stdout JSON-formatted, `logs/dbt.log` file
- Catalog any remaining instances of Python `print` method within `dbt-core` codebase

**Comment by jtcohen6** [comment]
Closing in favor of implementation ticket:
- https://github.com/dbt-labs/dbt-core/issues/8756
