### ISSUE TITLE
[CT-1768] [Docs] Top-level API docs glow-up

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6548]
We have some MVP docs for dbt-core's nascent Python API. It's possible to generate & view these locally:
```bash
# working dir: cloned version of dbt-core repo
# within python virtualenv
$ pip install -r editable-requirements.txt -r dev-requirements.txt
$ cd core/dbt/docs
$ make clean
$ make build
$ open build/html/index.html
```

That's a solid start! Before we go live with a `dbt-core` Python API, we should make these docs fuller & user-friendlier.

```[tasklist]
- [ ] #7097
- [ ] #7096
- [ ] #7098
- [ ] #7106
```

We can close this ticket when we have correct, high-quality, user-friendly documentation for programmatic invocations of `dbt-core` via its top-level API.

**Comment by jtcohen6** [comment]
Queueing this up for Execution team to discuss during BLG. I would understand if we're not ready to point a points estimate on this just yet (given other work that needs to happen first), but I would really like us to make progress here during the 30% of API-ification Phase 2 that's dedicated to UX / documentation improvements. Let's discuss more if the exit criteria listed above don't make sense, or if this should be split into multiple narrower tickets.

**Comment by stu-k** [comment]
@jtcohen6 Let discuss the differences between our higher-level API versus `dbt` as a library this Friday during our design discussion and what we actually want to document.

**Comment by jtcohen6** [comment]
Let's make sure to discuss this as part of today's follow-up conversation:
- What's the API we want to have by v1.5 / April?
- What's the _API documentation_ we want to have by v1.5 / April?
