### ISSUE TITLE
[CT-1773] [Bug] dbt docs does not show my schema name, instead shows todo_changeme

### ISSUE THREAD

**Issue by oscarecruitics** [dbt-labs/dbt-core#6554]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt docs does not show my schema name, instead shows todo_changeme in the schema name. For instance, the relation name should be mydatabase.myschema.mymodel but it it showing mydatabase.todo_changeme.mymodel

### Expected Behavior

Get the name of my schema after running dbt docs

### Steps To Reproduce

dbt run model
dbt docs generate
dbt docs serve

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

redshift

**Comment by dbeatty10** [comment]
Thanks for reaching out @oscarecruitics !

Is it literally showing `todo_changeme`, or is that just an example you providing?

Are you using [custom schemas](https://docs.getdbt.com/docs/build/custom-schemas) or overriding the `generate_schema_name` macro?

**Comment by oscarecruitics** [comment]
Thanks for reply @dbeatty10!

It shows literally `todo_changeme`, so for instance shows in relations `databasename.todo_changeme.modelname`

I am using `generate_schema_name` macro which dynamically set the schema for each model, may be this the problem?

**Comment by dbeatty10** [comment]
Sure thing @oscarecruitics !

Could you send the full definition of your `generate_schema_name` macro?

Another thing you could do to try to track down where the `todo_changeme` is coming from:
Search for `changeme` within a terminal within your project root directory:
```shell
git grep -i "changeme" .
```

This will use git to do a case-insensitive search within your project to hunt for anything already committed that might modify your schema name. If that comes up empty, you can do a regular `grep` to search for uncommitted code, logs, etc.:
```shell
grep -r "changeme" .
``` 

I checked each of the following repositories so I don't think it's coming from any of them:
- https://github.com/dbt-labs/dbt-docs
- https://github.com/dbt-labs/dbt-core
- https://github.com/dbt-labs/dbt-redshift
