### ISSUE TITLE
[CT-1780] [Regression] Documentation formatting

### ISSUE THREAD

**Issue by OnFormLimited** [dbt-labs/dbt-core#6559]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

I noticed that in updating DBT from 0.x to 1.x documentation markup seems to no longer support certain elements for colour (i.e. span style="color:darkslateblue"> Overview </span>)

### Expected/Previous Behavior

Code such as span style="color:darkslateblue"> Overview </span> expected to render the text element in the specified colour

### Steps To Reproduce

1. In Develop - click View Docs
2. Opening page will show elements like <span style="color:darkslateblue"> Data Warehouse Documentation </span> - instead of the actual text in the specified colour

### Environment

```markdown
DBT Cloud

- OS: Windows 10
- dbt (working version): 1.2
- dbt (regression version): 0.nnn
```

**Comment by OnFormLimited** [comment]
Thanks lots, will do

**Comment by jtcohen6** [comment]
This is related to some security changes we made a while ago, in v1.0.x, which sanitize Markdown (and thereby disallow a lot of arbitrary HTML/JS): https://github.com/dbt-labs/dbt-docs/pull/227

Thanks for reaching out to dbt Cloud so they can take a deeper look!

**Comment by fernandobrito** [comment]
Fun story: we have an internal automation that appends extra "data quality" metrics at the bottom of each model description, formatted as Markdown + HTML tags to color some of the numbers. Every time we upgrade dbt we do a "search and replace" from `sanitize:!0` to `sanitize:0` in our `index.html` so we can render our pretty formatting correctly.

Ok, technically we have a pre-generated `index_customized.html` in another folder and we overwrite the `index.html` with it during our publishing pipeline (we self-host our docs). On every upgrade, we take a newly generated `index.html`, copy to `index_customized.html`, and make our changes again.

I understand and agree that it makes sense to sanitize it, so I'm not re-opening the ticket or expecting any action on it. I'm just sharing it here in case other people also want to take the risk and disable the sanitization themselves. 😄
