### ISSUE TITLE
[CT-1782] [Bug] Check length of escaped strings in the adapter test

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#6566]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Adapter maintainers can choose to extend one of the following pytests (which are expected to be mutually exclusive):
- BaseEscapeSingleQuotesQuote
- BaseEscapeSingleQuotesBackslash

But we've observed at least one case where the adapter made the wrong choice, but the test passed anyways.

Example
The Spark and Databricks adapters were inheriting the `BaseEscapeSingleQuotesQuote` pytest instead of `BaseEscapeSingleQuotesBackslash`. 

This resulted in the following bug report:
https://github.com/dbt-labs/dbt-spark/issues/572

### Expected Behavior

If the adapter maintainer accidentally makes the wrong choice, the test should not pass.

One way to do this would be to also check the length of the resulting string [here](https://github.com/dbt-labs/dbt-core/blob/b13b0e949232ed7fefb626ab0fe6499979621482/tests/adapter/dbt/tests/adapter/utils/fixture_escape_single_quotes.py).

Run the following in postgres:
```sql
select 'let''s' as contraction, length('let''s') as contraction_length
```

We'd expect it to yield:
| contraction | contraction_length |
|-------------|--------------------|
| let's       | 5                  |

Any length other than `5` would indicate a problem. Such a check would have caught the spark/databricks bug.

### Steps To Reproduce

See https://github.com/dbt-labs/dbt-spark/issues/572

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by VersusFacit** [comment]
[Outstanding concern on the bottom of the linked PR](https://github.com/dbt-labs/dbt-core/pull/6567#pullrequestreview-1243151338)

**Comment by VersusFacit** [comment]
Commented on PR. This test covers the cases we need it to
