### ISSUE TITLE
[CT-1791] Add `buildable` as to `indirect_selection` param in Click CLI

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#6577]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

See #6366 for reference, but the TL;DR is that we need to add an additional option of `buildable` in the param for `indirect_selection`

**Comment by MichelleArk** [comment]
resolved as part of https://github.com/dbt-labs/dbt-core/pull/6761
