### ISSUE TITLE
[CT-1798] Add mutually exclusive handling for `warn_error_options` and `warn_error` params in Click CLI

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6579]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The `--warn-error-options` flag was shipped as part of dbt-core 1.4 via https://github.com/dbt-labs/dbt-core/pull/6520. `--warn-error-options` was [added as an option in the new click CLI params](https://github.com/dbt-labs/dbt-core/pull/6520/files#diff-f328aa466db7d10c562b1d34db497f911c05b6d1210988f127e07fa198a14763R369), but the mutually exclusive behaviour has not yet been implemented in the click CLI - `--warn-error` and `--warn-error-options` should be mutually exclusive - whether they are specified through the CLI, user_config, or env vars. 

Note: Look for opportunities to improve the logging the mutually exclusive options are specified from various sources (env var vs cli vs user config): https://github.com/dbt-labs/dbt-core/pull/6520#discussion_r1066303862

**Comment by iknox-fa** [comment]
Potential entry point to param validation:
https://click.palletsprojects.com/en/8.1.x/api/#parameters
(see the section on param callbacks)
