### ISSUE TITLE
[CT-1799] [Feature] Add --log-level global config

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6580]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Similar to the existing `LOG_PATH` and `LOG_FORMAT` global configs, consider adding a `LOG_LEVEL` config. This would be passed through [`setup_event_logger`](https://github.com/dbt-labs/dbt-core/blob/7a6160273875853525c6709cc196b4835617530a/core/dbt/events/functions.py) to provide a configuration option for the `LoggerConfig` that specifies logging configuration for both the stdout and file loggers. There may be use cases to configure stdout and file logger levels separately but a single config that controls both feels like a good starting point.

Note: This is a request from dbt-server and would be only be necessary to implement in the new click CLI.

**Comment by nathaniel-may** [comment]
closing in favor of #6639
