### ISSUE TITLE
[CT-1800] Make logging of meta in node_info more flexible.

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#6581]
In #6216 we added the "meta" dictionary to the node_info that is included on logging events. Since the meta field in the protobuf message NodeInfo was defined as a string/string map, we had to force all of the keys to strings. We should try to make this more flexible, either by using a protobuf struct or a map of string to Any.

**Comment by jtcohen6** [comment]
Closing as a duplicate of #6832
