### ISSUE TITLE
[CT-1806] [Spike] Measure usage of certain functions(os.environ, os.path)

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#6587]
After API-ification is merged to main, search in the codebase and figure out where are the following functions still being called in dbt-core after we create the [Flags object](https://github.com/dbt-labs/dbt-core/blob/feature/click-cli/core/dbt/cli/flags.py#L22). Ideally, we would like to get all of those information before Flags are being constructed and store it either inside Flags or some other object.
- `os.path`
- `os.envvar`
- functions to read or write files(optional)

**Comment by jtcohen6** [comment]
Closely related, with some more context: #6544 + #6545

We may want different mechanisms for "reading" files (accepting data as inputs), versus "writing" files (publishing data to a log/stream/...)
