### ISSUE TITLE
ref'ing an ephemeral model inside of a statement does not work

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-core#659]
The CTE is not injected into the query, so the user sees an error message that looks like: 
```
relation "__dbt__cte__model_name" does not exist
```

**Comment by carlyfk** [comment]
I get this error when referencing a CTE within a call to `dbt_utils.get_column_values`

**Comment by clrcrl** [comment]
A common issue people run in to is trying to get column names from an ephemeral model. Currently the [star macro](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql) only works on tables/views as it uses the `get_columns_in_table` function which queries the information schema.

If we can get ctes to work in statements, a star_model macro that works for any (including ephemeral) models would be possible, à la:
```sql
{% macro star_model(from) -%}


  {%- call statement('empty_results', fetch_result=True) -%}
   select
   *
   from {{ref(from)}}
   where false

  {%- endcall -%}
  {% set results = load_result('empty_results') %}
  {% if results %}
    {%- set column_names = load_result('empty_results').table.column_names -%}
    {{log(column_names, info=True)}}
  {% endif %}

  {{return(column_names)}}


{%- endmacro %}
```

**Comment by drewbanin** [comment]
Thanks for the writeup @clrcrl!
