### ISSUE TITLE
[CT-1810] Update matrix for integration tests

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#6597]
Update the matrix for release-branch-tests.yml to include 1.4.latest

- [x] dbt-core - #6604 
- [x] dbt-snowflake - https://github.com/dbt-labs/dbt-snowflake/pull/390#pullrequestreview-1246388224
- [ ] ~~dbt-redshift~~ - no scheduled tests on release branches
- [ ] dbt-bigquery - https://github.com/dbt-labs/dbt-bigquery/pull/467

**Comment by jtcohen6** [comment]
Relevant: https://github.com/dbt-labs/dbt-core/issues/5773
