### ISSUE TITLE
[CT-1822] [Feature] More granular logging configurations (e.g. USE_COLORS) for stdout vs. file

### ISSUE THREAD

**Issue by xxchan** [dbt-labs/dbt-core#6615]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/37948597/212436925-e4ae1b1e-21b3-49ef-aa9f-7d3cfa06e174.png">

### Expected Behavior

Should not write color codes to log files

### Steps To Reproduce

/ (Just installed dbt, and run `dbt init` and `dbt run`)

### Environment

```markdown
- OS: MacOS 12.6
- Python: 3.10.6
- dbt: 1.3.2
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @xxchan !

There's a couple different ways that you can [turn off colorized output](https://docs.getdbt.com/reference/global-configs#use-colors):
- Use the `use_colors: False` configuration within your `profiles.yml`
- Use the `--no-use-colors` flag on the command line

Could you give those a try and see if it behaves the way you expect?

**Comment by xxchan** [comment]
The configuration works. But I think ideally it should work without configuration. i.e., even when colorful output is enabled, it should only affect console logging, instead of file logging.

FWIW I've seem some recommendations about coloring [here](https://rust-cli-recommendations.sunshowers.io/colors.html#general-recommendations)

> 3. Otherwise, if the output stream (stdout or stderr) is a pipe, applications must disable colors. (Each output stream must be evaluated separately. For example, if stdout is a pipe but stderr isn't, applications must disable colors on stdout but may enable them on stderr.)

**Comment by jtcohen6** [comment]
Do we need each of these configurations to be doubly/separately defined, once for "stdout" and once for "file" logs? `dbt --use-colors-stdout --no-use-colors-file run`? It gets a bit cluttered...

In this case, it does seem reasonable to me that "file" logs should exclude the color code. (Although the color code will take effect if you `cat`/`tail` the file to your terminal!)

The behavior for this is defined here:
https://github.com/dbt-labs/dbt-core/blob/20c95a49933cd48dfbba9bd2ad5bc372ad440c6b/core/dbt/events/eventmgr.py#L154-L156

**Comment by nathaniel-may** [comment]
closing in favor of #6639
