### ISSUE TITLE
[CT-1830] [Epic] Adding entities into dbt-core

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-core#6626]
## Purpose
This issue will serve as the central `epic` issue for all the individual components associated with adding `entities` into dbt-core. 

### Shared Branch
This epic will merge all code changes into the `adding-semantic-structure` branch. Any new branches created for individual feature work should be spun off of the above branch.

### Emoji Legend:
- ✅ : Completed
- ❓ : Ready for review
- 🔨  : In progress
- ❌ : Not yet picked up

## Issues
**Nodes & Inheritance**
- ❓   #6627 : An initial pass of this was taken by @callum-mcdata before 1.4's release. CM will own converting that to the 1.4 world and opening a PR for review by team.
- ❌  #6629 : This is foundational work that handles how dimension inheritance will work. @MichelleArk would probably be the best person to take this on as her work on #6520 is very relevant to the data class structure.
- ❌ #6630 : Smaller task but we want to ensure parity between other node types and `exposures`.
- ❌ #6649 : This task spun out of a discussion with the Language team and how 6630 would require this functionality.
- ❌ #6632 : Big updates to `metrics` in order to build them on top of `entities` as opposed to models. Also some `dimensions` logic updates similar to behavior we want to introduce in #6629 . 
- ❌ #6662: This is a research spike on whether we should pursue adding this property in and whether we want to offer this as an extensible part of the semantic layer.
- ❌ #6683: This is a research spike on how to best lay the groundwork for a future where entities can be related to one another **and** how metrics can fit in the context of those relationships.

**Parse/Resolution**
- ❌ #6633 
- ❌ #6636

**dbt_metrics**
- ❌ https://github.com/dbt-labs/dbt_metrics/issues/212

**Docs**
- ❌ https://github.com/dbt-labs/dbt-docs/issues/360

### Are you interested in contributing this feature?

You betcha.

### What is the priority list of issues? What order should we tackle them in?
1. 🔨  #6627
2. ❌ #6629
3. ❌ #6632
4. ❌ #6649
5. ❌ #6630
6. ❌ #6662
7. ❌ #6683
8. ❌ #6633
9. ❌ #6636
10. ❌ https://github.com/dbt-labs/dbt_metrics/issues/212
11. ❌ https://github.com/dbt-labs/dbt-docs/issues/360

**Comment by jtcohen6** [comment]
I'm excited to spend the next few weeks talking about how our thinking around `entities` should (or shouldn't) change, in light of some forthcoming work to integrate [MetricFlow](https://github.com/transform-data/metricflow) :)

I'm going to remove this from the v1.5 milestone in the meantime. There may be some smaller bits of work that we decide to add back, or queue up for v1.6.
