### ISSUE TITLE
[CT-1850] [Bug] Using combo schema names in `generate_schema_name()` prevents adapter.get_columns_in_relation from working

### ISSUE THREAD

**Issue by jaredx435k2d0** [dbt-labs/dbt-core#6655]
### Describe the bug
If I try to combine two values to define my schema using the generate_schema_name() macro, using union_relations produces SQL with a trailing comma in the select due to omitting columns

### Steps to reproduce
Use this for generate_schema_name.sql:
```
{% macro generate_schema_name(custom_schema_name, node) -%}

    {%- set default_schema = target.schema -%}
    {%- if custom_schema_name is none -%}

        {{ default_schema }}

    {%- else -%}

        {{ custom_schema_name ~ '__' ~ default_schema }}

    {%- endif -%}

{%- endmacro %}
```

I've tried a few different things in the `else`. If I just use custom_schema_name OR default_schema, then it works fine. But if I try to combine them, I get the error. I've also tried combining them [as the dbt docs recommend](https://docs.getdbt.com/docs/build/custom-schemas#how-does-dbt-generate-a-models-schema-name):
`{{ default_schema }}_{{ custom_schema_name | trim }}`

### Expected results
I'd expect dbt_utils.union_relations to produce valid SQL with functioning unions.

### Actual results
Compiled SQL in target/run:
```
create or replace transient table DATABASE_NAME.SCHEMA_NAME.TABLE_NAME copy grants as
(


(
    select
        cast('DATABASE_NAME.SCHEMA_NAME.TABLE_NAME' as TEXT) as _dbt_source_relation,

        

    from DATABASE_NAME.SCHEMA_NAME.TABLE_NAME

    
)

union all


(
    select
        cast('DATABASE_NAME.SCHEMA_NAME.TABLE_NAME' as TEXT) as _dbt_source_relation,

        

    from DATABASE_NAME.SCHEMA_NAME.TABLE_NAME

    
)

);
```

You can see the comma at the end of the first column of each select. This causes the model to fail. If I only use one value in the `else` block of the macro, then the columns that should be there appear in the compiled SQL and the model builds fine.

### Screenshots and log output
Terminal output when I try to run the model:
```
001003 (42000): SQL compilation error:
syntax error line 14 at position 12 unexpected 'from'.
```

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: calogica/dbt_date
    version: 0.7.0

  - package: dbt-labs/dbt_utils
    version: 1.0.0

  # - package: dbt-labs/dbt_project_evaluator
  #   version: 0.2.0

  # - package: calogica/dbt_expectations
  #   version: 0.7.0

  - package: dbt-labs/codegen
    version: 0.9.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.0
  - latest:    1.3.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0 - Up to date!
```

**Comment by jaypeedevlin** [comment]
I'm not a dbt Labs employee so take this as an unofficial response, but this there a chance the models you're unioning haven't been rebuilt after you change the `generate_schema_name()` macro but before you run the model that unions things?

I'd expect this behavior if that were the case, since they'd exist in the original schema only and so retrieving the columns would come back empty.

**Comment by dbeatty10** [comment]
Thanks for reaching out @jaredx435k2d0 !

Could you try out the suggestion from @jaypeedevlin? The most simple way to make sure everything everything is built is to do:
```
dbt build
```

(If necessary you could choose more targeted ways to make sure each of your objects exist within the expected database & schema.)

## Example that worked for me
See below for example code and commands that worked for me.

### Project files

`packages.yml`
```yaml
packages:
  - package: calogica/dbt_date
    version: 0.7.0

  - package: dbt-labs/dbt_utils
    version: 1.0.0

  - package: dbt-labs/codegen
    version: 0.9.0
```

`seeds/colors_primary.csv`
```csv
category,color
primary,red
primary,yellow
primary,blue
```

`seeds/colors_secondary.csv`
```csv
category,color
secondary,orange
secondary,green
secondary,violet
```

`models/colors.sql`
```sql
{{
  config(
    materialized='table',
    copy_grants=true,
  )
}}

{{ dbt_utils.union_relations(
    relations=[ref('colors_primary'), ref('colors_secondary')],
) }}
```

`macros/generate_schema_name.sql`
```sql
{% macro generate_schema_name(custom_schema_name, node) -%}

    {%- set default_schema = target.schema -%}
    {%- if custom_schema_name is none -%}

        {{ default_schema }}

    {%- else -%}

        {{ custom_schema_name ~ '__' ~ default_schema }}

    {%- endif -%}

{%- endmacro %}
```

### Run
This worked for me:
```shell
dbt deps
dbt seed
dbt run -s colors
```

But if I change the `generate_schema_name` macro and then run _only_ the following, then I get an error similar to you:
```shell
dbt run -s colors
```

### Looking at the logs
If you look in your logs where it says:
```
create or replace transient table DATABASE_NAME.SCHEMA_NAME.TABLE_NAME copy grants
```
Just a few lines above, you'll see something like:
```
describe table DATABASE_NAME.SCHEMA_NAME.TABLE_NAME
```

If you also see a line like the following, it will give a hint about the cause:
```
Table 'DATABASE_NAME.SCHEMA_NAME.TABLE_NAME' does not exist or not authorized
```

**Comment by jaredx435k2d0** [comment]
This makes sense. I really appreciate such a detailed response!

I just started trying to test this quickly before signing off for the day with our actual models but, due to the fact that we're midway through our dbt migration, it gets messy quickly.

I'll spend time testing thoroughly next week. Looking forward to the results!

**Comment by jaredx435k2d0** [comment]
I think this takes care of it!

I really appreciate your thorough reply and help here :)

**Comment by dbeatty10** [comment]
Awesome to hear @jaredx435k2d0 !
