### ISSUE TITLE
[CT-1881] [Feature] When possible, bypass an expensive method during graph construction

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#6697]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

https://github.com/dbt-labs/dbt-core/issues/6073 describes how projects with 1000's of nodes can take ~15 minutes to `dbt build` even a single node.

The `_already_known` method call is a relatively expensive method call during DAG parsing. There are some cases where it is unnecessarily called, namely when `in_degree != 0` [here](https://github.com/dbt-labs/dbt-core/blob/93619a9a3761d3606d257c1274828ac4eef4f627/core/dbt/graph/queue.py#L159-L166).

Swapping the conditions of the if statement would short-circuit calling `_already_known`  while keeping the logic the same.  This is shown in https://github.com/dbt-labs/dbt-core/commit/9f9608731263b7b3b3e8dfd22a9d579cb650cd54. (We know we can safely swap the order by [commutativity of conjunction](https://en.wikipedia.org/wiki/Commutativity_of_conjunction)).

### Describe alternatives you've considered

There's at least two alternatives:
1. Default approach of changing nothing
1. More complicated refactor

This proposal seems obviously superior to the first alternative while not preventing us from taking up the second alternative at a later date. So it's an easy win.

### Who will this benefit?

This will (slightly) benefit teams with very large DAGs (thousands of nodes).

### Are you interested in contributing this feature?

There's already a PR ready for this!

**Comment by jtcohen6** [comment]
Renamed the issue just to make clear that this is _graph generation_, not _project parsing_!
