### ISSUE TITLE
[CT-1885] [Feature] Remove flags.py

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#6701]
### Describe the feature

Moving to the new Flags module instead of old flags.py

## Things to watch out for:
* dbt cloud would import this module [link](https://github.com/dbt-labs/dbt-cloud/blob/master/sinter/services/connection.py#L547)
* a few places where we would read env vars in while starting the dbt process
  https://github.com/dbt-labs/dbt-core/blob/7a6160273875853525c6709cc196b4835617530a/core/dbt/flags.py#L116-L121
  https://github.com/dbt-labs/dbt-core/blob/cbb9117ab997289062cd5bacaf4cfd4466ab9b1e/core/dbt/logger.py#L597-L601
* For there are functions that is buried pretty deep
  https://github.com/dbt-labs/dbt-core/blob/4480d05cfbe211bb78cdac721ff2664d0a8fc6a7/core/dbt/ui.py#L21-L35

**Comment by jtcohen6** [comment]
@ChenyuLInx I saw you added to the GH project for merging the feature branch, so I added to https://github.com/dbt-labs/dbt-core/issues/6631 as well — let me know if that was a mistake / feel free to remove it
