### ISSUE TITLE
[CT-1887] Global variables defined in root dbt_project.yml are not working in salesforce_source package

### ISSUE THREAD

**Issue by jaswanthColibri** [dbt-labs/dbt-core#6704]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I want to overwrite few variables in  package(salesforce_source) from my project's root dbt_project.yml.

I am able to do this in another project. same way i am trying in another project but default values are used in installed package though i explicitly mentioned them in dbt_project.yml

### Expected Behavior

dbt global variables should work in installed packages

### Steps To Reproduce

  dbt compile +my_model

### Relevant log output

```shell
None
```

### Environment

```markdown
- OS:Windows
- Python: 3.9
- dbt:1.3.2
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

   None

**Comment by jtcohen6** [comment]
@jaswanthColibri Could you provide some more details that would help someone else reproduce the bug you're seeing? Specifically, the relevant config from `packages.yml` + `dbt_project.yml`, so we can know:
- the exact version of the package you have installed
- the exact `vars` you're setting
- the behavior you're seeing, versus the behavior you're expecting to see

**Comment by jaswanthColibri** [comment]
@jtcohen6 I am setting few variables(database , schema names) in root dbt_project.yml with global scope. those variables are being used in salesforce_source package. but when i compile the model from salesforce_source package global variables are not working default values were taken by dbt.
