### ISSUE TITLE
[CT-1889] [Epic] API-ification + CLI - Phase 2

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#6706]
This epic tracks follow-on work from Phase 1 of API-ification. Our goal at the end of this epic is to have a rock-solid, well-documented top-level API that is powering a compelling CLI and an initial Python API for programmatic invocations.

## (40%) UX & documentation

```[tasklist]
### CLI Improvements
* [x] #6676
* [ ] #6800
* [ ] #6497
```

```[tasklist]
### Documentation
* [x] #6099
* [x] #6310
* [ ] #5540
* [ ] #6546
* [ ] #6548
* [ ] #6969
* [ ] #6970
* [ ] #6971
```

## (30%) Enable smooth upgrades

Restore previous behavior (bugs & telemetry), and provide clear warnings for deprecated/renamed functionality.

```[tasklist]
### Bugs
* [x] #6933
* [x] #6957
* [ ] #7010
* [ ] #7118
* [ ] #6913
* [ ] #6985
```

```[tasklist]
### Telemetry
* [ ] #6097
* [ ] #6098
* [ ] #3631
```

```[tasklist]
### Deprecations
* [ ] #6960
* [ ] #6903
* [ ] #6882
```

## (30%) Tech debt

```[tasklist]
### Flags
* [ ] #6397
* [ ] #6259
* [ ] #6857
* [ ] #6207
* [ ] #7036
```

```[tasklist]
### Misc
* [x] #6509
* [x] #6722
* [ ] #5886
* [ ] #6257
* [ ] #6360
* [ ] #6350
* [ ] #6646
```

**Comment by leahwicz** [comment]
Phase 1 work can be found here: https://github.com/dbt-labs/dbt-core/issues/5527

**Comment by jtcohen6** [comment]
Closing in favor of the more narrowly scoped epic for v1.5: https://github.com/dbt-labs/dbt-core/issues/6706
