### ISSUE TITLE
[CT-1890] Reintroduce logging to manifest generation

### ISSUE THREAD

**Issue by stu-k** [dbt-labs/dbt-core#6707]
As part of the work in #6565, event logging in the `parse` task was removed. This ticket captures the work to reintroduce it to `ManifestLoader.get_full_manifest`, likely behind an optional flag. I believe the best method to achieve this is to pass in the `fire_event` function to the method, defaulting to a noop function.

**Comment by gshank** [comment]
We also have a "fire_event_if" function in core/dbt/events/functions.py
