### ISSUE TITLE
[CT-1897] Release v1.5.0b1 - Feb 17th

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-core#6717]
### Core Team
- [x] Verify that `main` branch is in good state (all tests passing)
- [x] Follow release process (TBD link to instructions)
- [x] Determine if artifact jsonschemas have changed, and need version bump

### Adapters Team
- [x] Verify that `main` branch for all adapters is in good state (all tests passing)
- [x] Follow release process (TBD link to instructions)

### Runtime Team
- [ ] https://dbtlabs.atlassian.net/browse/RUNTIME-746

### Product Documentation
- [x] [Product] https://github.com/dbt-labs/docs.getdbt.com/issues/2781
- [x] [Product] Open docs issues for all merged changes that require new/updated documentation

### Announce
- [ ] [Product] Announce in dbt Slack (#dbt-prereleases)

**Comment by creeeeeg** [comment]
MWAA team at AWS is having some dependency issues with their product and one of them is a jsonschema conflict.  I hope this can help them resolve it.

**Comment by jtcohen6** [comment]
@creeeeeg I just opened a dedicated issue to track that dependency conflict: https://github.com/dbt-labs/dbt-core/issues/6775

**Comment by jtcohen6** [comment]
Going forward, we'll make sure to close these as soon as the release is live! Even if there's still more follow-on work (documentation, announcement, etc)
