### ISSUE TITLE
[CT-1906] Enable user-space code to fire typed events

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6733]
_copying from https://github.com/dbt-labs/dbt-core/issues/5325_

> Create a new function in the Jinja context `log_event` like `log` ([source](https://github.com/dbt-labs/dbt-core/blob/75f3e8cb749c7b52d226844394ecb34c1e0070a4/core/dbt/context/base.py#L576-L593)) so that instead of taking a string msg, it takes a string `event_name` and a list of values of type `List[Any]`. This will fire an event with the same name as the string passed with the parameters in the list. (Using `Event.__subclasses__()`, and the splat operator for lists (i.e. `*[foo, bar]`) may help here). Mypy will not be able to catch any type mismatches here since the event constructors aren't passed concrete values till runtime. Since these log lines will run with every materialization, tests should catch any issues with these log lines.

Idea here is, in addition to just passing strings into `{{ log() }}`, users should be able to pass structured data as the payload to a real named/type event. The Python context method `log_event` would accept those inputs, then turn around and call actual `fire_event`.

**Motivation:** All materialization code is written in user-space (Jinja), and the fact that we lack mechanisms to structure / distinguish between all those events is quite limiting.

**Comment by gshank** [comment]
The new protobuf code has a ListValue type which allows lists with elements of different types.
