### ISSUE TITLE
[CT-1908] [Regression] `exposure_content` referenced incorrectly

### ISSUE THREAD

**Issue by Mathyoub** [dbt-labs/dbt-core#6738]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

```local variable 'exposure_content' referenced before assignment ``` error due to `exposure_content` being referenced instead of `source_content`

### Expected/Previous Behavior

This is new in 1.4.0
dbt deps will not fail with error above

### Steps To Reproduce

- you're doing state comparison (--state <old_manifest>)
or
- your old project has sources defined in it (our automated test for cross-version state comparison compatibility [does not](https://github.com/dbt-labs/dbt-core/blob/main/tests/functional/artifacts/test_previous_version_state.py) include sources)

### Relevant log output

```shell
see current behavior
```

### Environment

```markdown
- OS:
- Python:
- dbt (working version): 1.3.2
- dbt (regression version): 1.4.0
```

**Comment by jtcohen6** [comment]
Specifically, this would affect any project with `sources` defined, that is doing a manifest comparison across v1.3 &rarr; v1.4. If their last dbt run was on v1.3 (or earlier), and they use a manifest from that run in a `state:modified` run with v1.4, they will run into this error.

This method exists to make that cross-version comparison possible. There was a bug in the method.
