### ISSUE TITLE
[CT-1916] Rename 'constraints_enabled' to 'contract'

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6748]
In the foundational [dbt Constraints work](https://github.com/dbt-labs/dbt-core/pull/6271), we added a boolean config named `constraints_enabled` that “turns on” contracting for this model. Given that the scope of model contracts is broader than “constraints,” and that dbt’s enforcement may go beyond the built-in behavior of analytical data platforms, we should rename this config to `contracted` instead.

**Comment by jtcohen6** [comment]
@sungchun12 in https://github.com/dbt-labs/dbt-core/pull/6271#discussion_r1092126607:
> I recommend the syntax be: `contract: true | false` because `contracted` invokes imagery of pregnancy(a beautiful human experience but dissonant related to data contracts) at first glance and is in past tense, which may confuse the reader. Whenever the term `data contracts` come up, it's a noun in plural or singular, not a verb.

@gshank in live conversation:
> When "the economy has contracted," that's not a good thing! I like `contracts` better.

**Comment by jtcohen6** [comment]
I'd vote for `contract` (singular) over `contracts` (false), given some of the recent discussion in #6726 about how this is a "producer-side" contract, and there's going to be exactly one (or zero) per model.
