### ISSUE TITLE
[CT-1917] [Regression] Non-error log is not silenced by `-q` flag.

### ISSUE THREAD

**Issue by elongl** [dbt-labs/dbt-core#6749]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

According to `-q`:
> Suppress all non-error logging to stdout. Does not affect {{ print() }} macro calls.

A new log is printed even though it's not an error.

```bash
(elementary) ☁  dbt_project [main] dbt run-operation hello
14:22:47  target not specified in profile 'elementary', using 'default'
14:22:47  Running with dbt=1.4.0
hello
(elementary) ☁  dbt_project [main] dbt -q run-operation hello
14:22:56  target not specified in profile 'elementary', using 'default'
hello
```

### Expected/Previous Behavior

Previously, the log was omitted when passing the `-q` flag.

```bash
(elementary) ☁  dbt_project [main] dbt run-operation hello
14:22:15  target not specified in profile 'elementary', using 'default'
14:22:16  Running with dbt=1.3.0
hello
(elementary) ☁  dbt_project [main] dbt -q run-operation hello
hello
```

### Steps To Reproduce

1. Name a `default` target without having a `target` defined.
2. Run a dbt command with the `-q` flag.

### Environment

```markdown
- OS: macOS
- Python: 3.9.6
- dbt (working version): 1.3.0
- dbt (regression version): 1.4.0
```

### Additional Context

I'd love to contribute.

**Comment by jtcohen6** [comment]
My suspicion here is:
- We set up a basic event logger before we have the full set of information we need to initialize it for real (all flags & configs resolved). This ensures that any real initialization errors don't get swallowed. Relevant: #6434, #6447.
- The event you're seeing, `MissingProfileTarget`, is raised during `render_profile`, which is happening during initialization and before we call `setup_event_logger` here:
https://github.com/dbt-labs/dbt-core/blob/c65ba11ae6dca5203228320a7f6388ce1796f104/core/dbt/main.py#L225-L232

Should we simply

**Comment by elongl** [comment]
Hi @jtcohen6 , thanks a lot for replying.
I personally tend to favor (2) because I think that if a user is using `--quiet` they'd generally like to keep a program quiet at its entirety except for logs made by them (`print()`) and it doesn't really matter at what phase the execution is.
What do you think?

If that resonates, care to share any guidelines on how can I make this contribution?

**Comment by jtcohen6** [comment]
I think it would be as simple as turning line 117 to:
```python
 EVENT_MANAGER.add_logger( 
     _get_logbook_log_config() if flags.ENABLE_LEGACY_LOGGER else _get_stdout_config(EventLevel.ERROR) 
 ) 
```

@peterallenwebb How does this approach sound to you? The downside is, I think we'd _never_ actually log `MissingProfileTarget`, whether or not the user is actually passing the `--quiet` flag. (Since we haven't resolved flags before this default logger is set up.)

**Comment by peterallenwebb** [comment]
The approach would work, and it would indeed have the consequences you described.

We could, however, add some log configuration code right after [command line arguments are parsed](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/main.py#L176) so that we can turn on quiet mode as soon as possible, if it is specified. I think I actually like that approach better?

**Comment by jtcohen6** [comment]
@peterallenwebb I'm all for it!
