### ISSUE TITLE
[CT-1928] Support passing event callbacks to EventManager via dbtRunner

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6763]
Accept event [callbacks](https://github.com/dbt-labs/dbt-core/blob/ed50877c4fe5a74aa8cdd203bc9aceac979d9243/core/dbt/events/eventmgr.py#L186) as part of [`dbtRunner`'s constructor](https://github.com/dbt-labs/dbt-core/blob/ed50877c4fe5a74aa8cdd203bc9aceac979d9243/core/dbt/cli/main.py#L34-L41) and use them to setup the `EventManager` for programmatic invocations of dbt.

**Comment by stu-k** [comment]
My have to add a method to add a callback to `EventManager`, and use the `ctx` to carry the callbacks from `dbtRunner`'s constructor to `preflight` where we setup the logger.

**Comment by chamini2** [comment]
Hey, the current implementation fro #7214 seems to wait for the callbacks to be processed before continuing with the invocation. Let me share an example:

```py
from dbt.cli.main import dbtRunner, list
from dbt.events.base_types import EventMsg

import time

def print_callback(event: EventMsg):
    print("Sleeping")
    time.sleep(2)
    print("Got an event:", event.info.name, event)

dbt = dbtRunner(callbacks=[print_callback])
dbt.invoke(['list'])
```

This takes 30 seconds to run because it waits for the `time.sleep(2)` to finish befor continuing.

Is this an implementation detail that may change in the future or as intended?

**Comment by DanielDuranSW** [comment]
Hello!! Do you know about the future support for registering callbacks on dbt's EventManager? "The current behavior blocks subsequent steps, but this may not be guaranteed in future versions". "Given that the Python interface for events is less mature than the structured logging interface", would it be better to rely on parsing JSON-formatted logs for handling real-time events, or are callbacks still the recommended approach for this use case?
