### ISSUE TITLE
[CT-1940] [Feature] Stand-alone Python module for PostgresColumn

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#6772]
See also: https://github.com/dbt-labs/dbt-redshift/issues/290

### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

There is a stand-alone `{adapter}/column.py` module _almost_ everywhere:
- https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/base/column.py
- https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/column.py
- https://github.com/dbt-labs/dbt-spark/blob/main/dbt/adapters/spark/column.py
- https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/column.py

The two exceptions are:
- [dbt-core/plugins/postgres/dbt/adapters/postgres/relation.py](https://github.com/dbt-labs/dbt-core/blob/c653330911ccbfdee331e56f5c2f8ced1aea5681/plugins/postgres/dbt/adapters/postgres/relation.py#L26-L34)
- [dbt-redshift/dbt/adapters/redshift/relation.py](https://github.com/dbt-labs/dbt-redshift/blob/16b122b4f3f0ef433987ab44e6b09789eeddc20a/dbt/adapters/redshift/relation.py#L17-L18)

It's easy enough to standardize on the convention by splitting `PostgresColumn` into its own file.

### Describe alternatives you've considered

It won't affect the functionality of the dbt-postgres adapter if it stays as-is. But it also won't affect the functionality if it is moved.

### Who will this benefit?

It is easier to find the definition or compare definitions across adapters if things are in the standard locations. This is helpful for anyone inspecting the code, including adapter maintainers outside of dbt-postgres that want to compare/contrast implementation details.

It will also allow for slightly more standardization of this file:
https://github.com/dbt-labs/dbt-core/blob/c653330911ccbfdee331e56f5c2f8ced1aea5681/plugins/postgres/dbt/adapters/postgres/__init__.py#L4

### Are you interested in contributing this feature?

Yep :thumbsup:

**Comment by nssalian** [comment]
@dbeatty10, I can pick this up along with a similar change in Redshift.

**Comment by dbeatty10** [comment]
@nssalian That sounds perfect! Here's the files to create or update:
- create: dbt-core/plugins/postgres/dbt/adapters/postgres/column.py
- update: [dbt-core/plugins/postgres/dbt/adapters/postgres/relation.py](https://github.com/dbt-labs/dbt-core/blob/c653330911ccbfdee331e56f5c2f8ced1aea5681/plugins/postgres/dbt/adapters/postgres/relation.py#L26-L34)
- update: [dbt-core/plugins/postgres/dbt/adapters/postgres/__init__.py](https://github.com/dbt-labs/dbt-core/blob/c653330911ccbfdee331e56f5c2f8ced1aea5681/plugins/postgres/dbt/adapters/postgres/__init__.py#L4)
