### ISSUE TITLE
[CT-1943] Loosen pin on `jsonschema` (via `hologram`)

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6775]
For more context on our latest thinking around dependencies (how & why we pin today, and how we want it to change):
- https://github.com/dbt-labs/dbt-core/discussions/6495

### Summary

`dbt-core` depends on `hologram`, and as such it also includes `hologram`'s transitive dependencies on `jsonschema` and `python-dateutil`. `hologram`'s upper bound on `jsonschema` in particular is causing issues for some folks trying to install `dbt-core` alongside other popular tools, such as Airflow:
- https://github.com/dbt-labs/hologram/issues/52
- https://github.com/dbt-labs/hologram/pull/51

### Short term

- Try removing upper bound on `jsonschema`
- Release a new version of `hologram` with no / looser upper bound
- Support the new version of `hologram` [in `dbt-core`](https://github.com/dbt-labs/dbt-core/blob/a8abc496323f741d3218d298d5d2bb118fa01017/core/setup.py#L54)

### Medium term

Remove `dbt-core`'s dependency on `hologram` entirely. It doesn't do nearly as much for us today as it used to, and the validation errors it raises aren't even all that nice.
- https://github.com/dbt-labs/dbt-core/issues/6776

**Comment by emmyoop** [comment]
Part of this will be determining how to release hologram since we have not done that recently.

**Comment by r-richmond** [comment]
Is this targeted for being included with the 1.5 release?

**Comment by jtcohen6** [comment]
@r-richmond This hasn't been a top priority for us, compared to other planned work for v1.5, but I understand it's a pain for a number of folks who need to install `dbt-core` alongside other Python programs that require newer versions of `jsonschema`.

I just opened a quick PR to run CI with the latest version of `jsonschema`. If this "just works," we can try to sneak it in for v1.5.

**Comment by gshank** [comment]
I've released hologram 0.0.16
