### ISSUE TITLE
[CT-1944] [SPIKE] Remove dependency on `hologram`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6776]
We started `hologram` a fork of [`dataclasses-jsonschema`](https://github.com/s-knibbs/dataclasses-jsonschema). It allowed us to adopt Python dataclasses in Python 3.7+, while still making use of JSONSchema-based validation. We haven't done a particularly good job of maintaining it in the years since, and it now brings us more grief than good.

We use `hologram` in two places today:
1. **Validation** ([`dataclass_schema.py`](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/dataclass_schema.py)), although the validation errors it raises are really unpleasant & not very helpful
2. **Generating JSONSchemas** from artifacts, which are still not always technically correct (#4657)

I recently ran into the unpleasantness of the validation error message, while trying to find the root cause of https://github.com/fivetran/dbt_amazon_ads_source/issues/6. Nowhere did this error tell me that this was in the `config.enabled` of a source, nor even the file where the source was defined!

```
08:24:59  Encountered an error:
'False and True' is not of type 'boolean'

Failed validating 'type' in schema['properties']['enabled']:
    {'default': True, 'type': 'boolean'}

On instance['enabled']:
    'False and True'
08:24:59  jsonschema.exceptions.ValidationError: 'False and True' is not of type 'boolean'

Failed validating 'type' in schema['properties']['enabled']:
    {'default': True, 'type': 'boolean'}

On instance['enabled']:
    'False and True'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jerco/dev/product/dbt-core/core/dbt/main.py", line 135, in main
    results, succeeded = handle_and_check(args)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/main.py", line 198, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/main.py", line 245, in run_from_args
    results = task.run()
  File "/Users/jerco/dev/product/dbt-core/core/dbt/task/parse.py", line 93, in run
    self.get_full_manifest()
  File "/Users/jerco/dev/product/dbt-core/core/dbt/task/parse.py", line 74, in get_full_manifest
    manifest = loader.load()
  File "/Users/jerco/dev/product/dbt-core/core/dbt/parser/manifest.py", line 373, in load
    patcher.construct_sources()
  File "/Users/jerco/dev/product/dbt-core/core/dbt/parser/sources.py", line 84, in construct_sources
    parsed = self.parse_source(patched)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/parser/sources.py", line 145, in parse_source
    config = config.finalize_and_validate()
  File "/Users/jerco/dev/product/dbt-core/core/dbt/contracts/graph/model_config.py", line 353, in finalize_and_validate
    self.validate(dct)
  File "/Users/jerco/dev/product/dbt-core/env/lib/python3.9/site-packages/hologram/__init__.py", line 989, in validate
    raise ValidationError.create_from(error) from error
hologram.ValidationError: 'False and True' is not of type 'boolean'

Failed validating 'type' in schema['properties']['enabled']:
    {'default': True, 'type': 'boolean'}

On instance['enabled']:
    'False and True'
```

### Requirements

Copying from [older Jira ticket](https://dbtlabs.atlassian.net/browse/CT-270):

> **Functional requirements:**
> - Must not require us to write an entire schema validation/generation system from the ground up.
> - Must be fast enough to suit core performance goals
> - Must utilize some sort of cross platform standard (json schema, protobuf defs, etc)
> - Must auto-generate validation schemas/defs.  Preferably from python data classes or python typedefs or some combination of the two.

Since writing that Jira ticket, we have introduced proto definitions for our event system, and are working (slowly but surely) to extend that framework to our core classes (#6391).

The other serialization/validation library we use, `mashumaro`, considers native support for schema generation out of scope:
- https://github.com/Fatal1ty/mashumaro/issues/55

**Comment by jtcohen6** [comment]
Relevant conversation, proposing a few more alternatives:
- https://github.com/dbt-labs/dbt-core/discussions/6915#discussioncomment-4918721

**Comment by codecae** [comment]
FWIW: the dependent version of hologram is now making dbt-core incompatible with Airflow >=2.5.2...  Airflow now requires jsonschema>=4.0.0, which is incompatible with hologram>0.0.14,<0.0.15

Effectively, we are unable to upgrade airflow due to this dependency.  I know our problems really aren't your problems, but if this is can be upgraded that would be excellent :)

**Comment by Fatal1ty** [comment]
Hi, folks! As I promised, JSON Schema generation is now [out of the box](https://github.com/Fatal1ty/mashumaro/releases/tag/v3.6) in mashumaro. Would you like to give it a try? If some functionality you need is missing, then I'm ready to work on it.

**Comment by mariahjrogers** [comment]
Seconding @codecae's sentiment above, this dependency is also making dbt-core incompatible with `poetry > 1.1.15` (three minor versions behind). Would love for this to go ~away~ 🫠

**Comment by peterallenwebb** [comment]
@gshank Should we close this spike and open a separate issue for follow up?

**Comment by gshank** [comment]
Closing this for now, will continue work in #8426.
