### ISSUE TITLE
[CT-1950] Use an Enum instead of a string to represent IncludeExclude.include

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6786]
Use an Enum instead of a string in the `IncludeExclude` dataclass to represent the "all"/"*" options of the `include` attribute. Shouldn't be a breaking change in terms of the user interface, just internals

_Originally posted by @MichelleArk in https://github.com/dbt-labs/dbt-core/pull/6771#discussion_r1091251799_

**Comment by iknox-fa** [comment]
Per discussions w @MichelleArk:
We're not really gaining anything by making this an enum so I'm closing the ticket.
