### ISSUE TITLE
[CT-1981] Issue when passing `--select` and `--model` to a command together

### ISSUE THREAD

**Issue by aranke** [dbt-labs/dbt-core#6800]
Did some manual testing by locally overwriting a command that accepts the new `select` (--select, --model) alias command with `print(ctx.obj["flags"].SELECT)` and found some issues when passing `--select` and `--model` to a command together. 

The options are not treated as mutually exclusive via MultiOption and the resulting `flags.SELECT` value is clobbered by the value from the last alias option:
```
❯ python3 core/dbt/cli/main.py docs generate --select model_a model_b  --model model_c
('model_c',)

❯ python3 core/dbt/cli/main.py docs generate --model model_c --select model_a model_b
('model_a', 'model_b')
```

This was unexpected behaviour to me, but for better or for worse this is also how main's parsing currently works (printing args.select and exiting on main to test): 
```
❯ dbt docs generate --select model_a model_b --model model_c
['model_c']
❯ dbt docs generate --select model_a model_b --model model_c
['model_c']
❯ dbt docs generate --model model_c --select model_a model_b 
['model_a', 'model_b']
```

We should probably open an issue to document this behaviour and investigate a fix that gets us --select/--model option mutual exclusivity if possible. But given that it's the current behaviour on main I don't see it as pressing to fix as part of this PR.

_Originally posted by @MichelleArk in https://github.com/dbt-labs/dbt-core/issues/6787#issuecomment-1410299008_

**Comment by iknox-fa** [comment]
@jerco can we close this as a won't fix due to the fact that we want to deprecate `--model`?

**Comment by iknox-fa** [comment]
*sigh* I have done this more times than I'd like to admit.
Thanks @aranke
