### ISSUE TITLE
[CT-1982] [Regression] Docs overview changed

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6801]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

See https://github.com/dbt-labs/dbt-docs/issues/366 for details

### Expected/Previous Behavior

See https://github.com/dbt-labs/dbt-docs/issues/366 for details

### Steps To Reproduce

See https://github.com/dbt-labs/dbt-docs/issues/366 for details

### Environment

```markdown
See https://github.com/dbt-labs/dbt-docs/issues/366 for details
```

### Additional Context

Related to #6427, which changed the `unique_id` for docs blocks

**Comment by emmyoop** [comment]
Let's test that the community PR work for custom overviews.
