### ISSUE TITLE
[CT-1987] [Feature] utility to show manifest differences

### ISSUE THREAD

**Issue by noel** [dbt-labs/dbt-core#6819]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When slim ci does not work as expected it is difficult to troubleshoot what exactly is different between two manifests.
It would be great if there was a way to output the exact key in the manifest which is different.  This would make debugging simpler.

### Describe alternatives you've considered

dbt ls -s state:modified.<sub selector>
This process at least narrows down the location of the difference, but you still need to check at key differences between the two manifests

### Who will this benefit?

Anyone using slim ci.

**Comment by dbeatty10** [comment]
Thanks for this suggestion @noel !

It makes sense to figure out ways to simplify debugging when two manifests differ in some unknown way.

I wonder if something like [jq](https://stedolan.github.io/jq/) could help out here?

### Example

Let's say that you have two manifests `manifest-1.json` and `manifest-2.json` and `jq` is installed. Then run the following:
```shell
diff -I "created_at" <(jq . manifest-1.json) <(jq . manifest-2.json) > my_diff
```

Here's `my_diff` for a project similar to [this](https://github.com/dbt-labs/dbt-core/issues/6806#issuecomment-1411283162) one. Can you tell what I changed between each invocation?

<details>
<summary>Click here to reveal diff</summary>

```diff
5,6c5,6
<     "generated_at": "2023-02-01T00:55:39.494863Z",
<     "invocation_id": "0e612d69-17aa-4331-aa77-559def7bf77b",
---
>     "generated_at": "2023-02-01T00:56:09.170195Z",
>     "invocation_id": "3649e233-054e-49f9-8f39-111212939828",
848c848,854
<         "post-hook": [],
---
>         "post-hook": [
>           {
>             "sql": "select 1",
>             "transaction": true,
>             "index": null
>           }
>         ],
862,863c868,873
<       "unrendered_config": {},
<       "created_at": 1675212940.54368,
---
>       "unrendered_config": {
>         "post-hook": [
>           "select 1"
>         ]
>       },
>       "created_at": 1675212970.255466,
908c918,924
<         "post-hook": [],
---
>         "post-hook": [
>           {
>             "sql": "select 1",
>             "transaction": true,
>             "index": null
>           }
>         ],
922,923c938,943
<       "unrendered_config": {},
<       "created_at": 1675212940.545138,
---
>       "unrendered_config": {
>         "post-hook": [
>           "select 1"
>         ]
>       },
>       "created_at": 1675212970.258373,
968c988,994
<         "post-hook": [],
---
>         "post-hook": [
>           {
>             "sql": "select 1",
>             "transaction": true,
>             "index": null
>           }
>         ],
982,983c1008,1013
<       "unrendered_config": {},
<       "created_at": 1675212940.546604,
---
>       "unrendered_config": {
>         "post-hook": [
>           "select 1"
>         ]
>       },
>       "created_at": 1675212970.261195,
1028c1058,1064
<         "post-hook": [],
---
>         "post-hook": [
>           {
>             "sql": "select 1",
>             "transaction": true,
>             "index": null
>           }
>         ],
1042,1043c1078,1083
<       "unrendered_config": {},
<       "created_at": 1675212940.547963,
---
>       "unrendered_config": {
>         "post-hook": [
>           "select 1"
>         ]
>       },
>       "created_at": 1675212970.263995,
```

</details>

### Explanation of the command
- This [gist](https://gist.github.com/zfz/0932119200d2c94760019d85af2fb6fe) gist demonstrates the diff
- This [post](https://stackoverflow.com/questions/2747091/how-to-ignore-lines-starting-with-a-string-with-diff) to ignore all the different `created_at` timestamps

### More ergonomic, using a shell alias

The command above is a bit of a bear. There's no way my fingers could possibly remember it.

Different shells have different ways of creating parametrized aliases, but I'll demonstrate using `zsh` (as described [here](https://www.thorsten-hans.com/5-types-of-zsh-aliases#functions-for-aliases-with-parameters)):
1. Open `~/.zshrc`
1. Add something like this (replacing `diffman` with your preferred alias):
    ```
    diffman() {
        diff -I "created_at" <(jq . $1) <(jq . $2)
    } 
    ```
1. Save and close
1. Run `source ~/.zshrc` to re-load the shell
1. `diffman manifest-1.json manifest-2.json`

Admittedly, I haven't done a ton of manifest diff'ing myself, so I'll be interested to hear your feedback on how useful (or not!) an approach like this might be.

**Comment by noel** [comment]
Still seems valuable and maybe even more so with the new features in 1.5+

**Comment by noel** [comment]
I meant that things like model versions and cross project dependencies may make this even harder. I still have to play around with 1.5, but I suspect there can be scenarios that should/shouldnt trigger during a state:modified run and when they do it could be difficult to pin point the reason why a model did/didnt run.

Regarding the manifest diffing, I guess I forgot to report back when I initially looked at this, but the output was too verbose and difficult to interpret.  I can show you if you are interested as I just reran it on a branch that has a single change yet I got a lot of output from diff

**Comment by dbeatty10** [comment]
@noel Providing that [example](https://github.com/dbt-labs/dbt-core/issues/6819#issuecomment-1411327293) of how to generate a diff between manifests is probably the best we can offer here.

You're right that those diffs can be pretty verbose! Performing some kind of diff between manifests is a decent place to start troubleshooting, but it will be more art than science to sort the signal from the noise and interpret the differences.

Troubleshooting / debugging problems with `state:modified` will always have some inherent complexity to it that we can't make go away -- it's necessarily hard.

For those reasons, this seems like something we'd choose not to take on. What do you think @jtcohen6 ?
