### ISSUE TITLE
[CT-1993] Raise an exception from ref if referencing a private model across groups

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6826]
During resolution, raise an exception if a node attempts to ref a private model from a different group than the referenced private model’s group. 

Nodes not in a group (group is `None`) should not be able to reference _any_ private models because they are not part of any group.

Note: exposures can have `ref` calls, but are not 'groupable'. Following on the logic above, they should _not_ be able to reference _any_ private models because they are not part of any group.

**Comment by jtcohen6** [comment]
Discussed live: We may want a new class of exception, `DependencyError`, when:
- `ref`/`source`/`metric` a model/source/metric/etc that doesn't exist
- a model wants to belong to a `group` that doesn't exist
- `ref` a model in a different `group` with `access: private`

(as distinct from existing `CompilationError`)

**Comment by MichelleArk** [comment]
From 2/6 Estimation - `ReferenceError` would be a preferable name to `DependencyError`

**Comment by jtcohen6** [comment]
As @emmyoop rightly knew (or guessed), we already have an exception named `DependencyError`, and it's only used within `dbt deps`.

`ReferenceError` all the way!
