### ISSUE TITLE
[CT-1998] Improve handling of dictionaries in protobuf messages

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#6832]
In pull request #6820 we implemented protobuf message versions of nodes and node configs. However the match between Python dictionaries that allow values of any type and protobuf maps isn't straightforward. As a result we have temporarily forced a number of dictionaries into string/string dictionaries.

We should look at other options for this and improve the representation of dictionaries in protobuf messages. In particularly this applies to the "meta" dictionary, which is already included in 1.4 in the node_info structures in the logs.

In addition to "meta", the following dictionaries are affected:
* in NodeConfig - persist_docs, quoting, column_types, grants
* in ColumnInfo - _extra
* in various nodes - unrendered_config
* in TestMetadata - kwargs
* in SourceDefinitino - source_meta

**Comment by jtcohen6** [comment]
_Copying from https://github.com/dbt-labs/dbt-core/issues/6803#issuecomment-1435099103_

Next steps here:
- Check out what `Struct` can do
- See what `map<str, Any>` can do
- Both have their limitations
- Pick one, and go implement

Closing #6581 and #6803 in favor of this one — more context in the discussions there
