### ISSUE TITLE
[CT-2003] [Spike] Research and Investigate Automated Test Monitoring with Datadog

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#6836]
Research and investigate how we can implement automated test monitoring with Datadog, particularly with their [CI Visibility offering](url).

Goals:

- Identify internal contacts who can help us allocate and configure a test environment
- Set up basic monitoring for dbt-core's integration and unit tests
- Identify gaps between Datadog's capabilities in this area and our requirements
- Identify any added costs to dbt Labs of implementing this solution

**Comment by jtcohen6** [comment]
@emmyoop Can we close this one out, spike successful?

**Comment by emmyoop** [comment]
We have implemented datadog pipline visibility and test visibility for `dbt-core`, `dbt-snowflake`, `dbt-redshift`, `dbt-bigquery`.  

`dbt-spark` and `dbt-core-bundles` only have pipeline visibility enabled for now.  `dbt-spark` is in circle CI and involves some extra/different setup.  Open question as to if we're moving off CircleCI anyways so nto worth the effort.  `dbt-core-bundles` will just need to add the appropriate env vars if it is determined to need test visibility.
