### ISSUE TITLE
[CT-2026] Add proto serialization to automated event testing

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6852]
Let's extend this test, so it validates serialization to proto (and thereby our proto schema definitions) in addition to JSON:

https://github.com/dbt-labs/dbt-core/blob/b2ea2b8b256e5db1da0b712dfedd7973e1e50a37/tests/unit/test_events.py#L391-L417

**Comment by emmyoop** [comment]
- Need to set more values in the test events (dictionaries)
- New test may surface errors that will need to be fixed

Time box this for now, and if there's more work to do create another ticket.
