### ISSUE TITLE
[CT-2036] Parsing: model ‘latest’ attribute

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6867]
Parse `latest: Optional[boolean]`, as configured in a model yaml property file. Should be available as a model node attribute in the manifest. Should be `None` for un-versioned models, `True` if explicitly set via model property, or if model has highest numeric version, and `False` otherwise.
 
**Validation**
 - only one version of a given model can have latest: true set
 - only versioned models can have latest set to true or false

**Comment by jtcohen6** [comment]
I'm going to close this as a standalone issue, I think we'll need to capture it as part of the updated version spec proposed in #6866. We can reopen if that's the wrong call
