### ISSUE TITLE
[CT-2037] Parsing: model ‘deprecation_date’ attribute

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6868]
Parse `deprecation_date: Optional[str]`, as configured in a model yaml property file. Should be available as a model node attribute in the manifest. 

**Validation** 
- deprecation_date should be a valid datetime format(potentially configurable at the project-level?) or a special ’never’/‘unplanned’ string value
- All versioned models with `latest:false` _must_ declare a `deprecation_date`. 
- Only versioned models can have a non-null deprecation_date

**Comment by jtcohen6** [comment]
> potentially configurable at the project-level?

Yeah, this would be a vote in favor of implementing `deprecation_date` as a standard config (unlike `version` or `latest`).

> Only versioned models can have a non-null deprecation_date

I don't think we need to enforce this. While all non-latest versioned models must be deprecated, I think a model could declare its own forthcoming deprecation, even if it's not versioned.

Taken together, I think there's a fair argument for `deprecation_date` as a config. It's definitely _related to_ `version`/`latest`, conceptually and for certain validation steps, but users could also make use of it independently of model versioning.

**Comment by emmyoop** [comment]
Will we throw an error if we are past the deprecation date? #6870 mentions warnings if the date exists but it's unclear what happens after the date is in the past.

**Comment by MichelleArk** [comment]
Closing in favor of implementation issue: https://github.com/dbt-labs/dbt-core/issues/7433
