### ISSUE TITLE
[CT-2043] [Bug] Missing type (double) in `is_float` for databricks 

### ISSUE THREAD

**Issue by rlh1994** [dbt-labs/dbt-core#6876]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm not sure if this belongs in here or the spark or the databricks adapator, but a `double` type column in databricks returns false for all of `is_float`, `is_numeric`, and `is_number`.

### Expected Behavior

It would return true for all those class method.

### Steps To Reproduce

1. Create a databricks table with a double column
2. Use `adapter.get_columns_in_relation(your_table)` and loop over the columns, logging or adding comments for the `.data_type` and the `.is_number()`
3. Observe the column with type `double` has `false` for `is_number()`

### Environment

```markdown
- OS:
- Python:
- dbt: 1.4.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Using databricks as unable to test on spark, it is a delta table if that is relevant.

I believe it just needs to be added to the list here:
https://github.com/dbt-labs/dbt-core/blob/b2ea2b8b256e5db1da0b712dfedd7973e1e50a37/core/dbt/adapters/base/column.py#L55-L63

**Comment by jtcohen6** [comment]
Thanks for opening @rlh1994!

While both `dbt-spark` and `dbt-databricks` implement their own `Column` class ([`SparkColumn`](https://github.com/dbt-labs/dbt-spark/blob/main/dbt/adapters/spark/column.py) and [`DatabricksColumn`](https://github.com/databricks/dbt-databricks/blob/main/dbt/adapters/databricks/column.py)), it doesn't look like either reimplements the `is_float` method. So, they're just using the `BaseAdapter.Column` method, defined in `dbt-core`, which you linked above.

Given that we already have `double precision` in the list above, and other data platforms (e.g. [Snowflake](https://docs.snowflake.com/en/sql-reference/data-types-numeric.html#double-double-precision-real)) also treat `DOUBLE` and `DOUBLE PRECISION` as true aliases, it seems reasonable to me that we'd add `double` to the default `is_float` method.

Is that a change you'd be up for making?
