### ISSUE TITLE
[CT-2049] Fire an event at the end of every command

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6878]
On the `feature/click-cli` branch, each command explicitly returns a tuple of `success: bool, results: Any`. (The structure of `results` differs based on the command.)

We should additionally fire an event that can be used programmatically to determine:
- when the command completed
- if the command succeeded

Ideally, this event would be fired _always_, even in cases where the command was interrupted (`^C`) or cancelled itself (e.g. `--fail-fast`).

**Comment by gshank** [comment]
Super agree with this. I suggest that we might want to have a CommandCompleted event that contains the data common to all commands, such as timing and success, and refer to an additional event that would contain more of the specific Result dump. We could do a "oneof" of all of the various Result objects, but the way they work in python protobufs is kind of kludgey and slow. We could even include the name of the Result event in the CommandCompleted event, if that would help.

**Comment by jtcohen6** [comment]
Discussed during BLG: This event shouldn't include the full result that would be returned from the command if invoked programmatically, à la:
```python
results, success = dbt.invoke(['<command>'])
```
**Rationale:**
- those `results` can be different types (depending on the command), as Gerda mentioned above
- node-level results are already fired as events as soon as the node is finished
- we should already have events that "summarize" a graph-running command (how many nodes, how many succeeded, etc)

This event should just be:
- `which` command
- when it finished
- how long it took
- standard metadata of course (`invocation_id` etc)
