### ISSUE TITLE
[CT-2066] Handle old param/flag names in new CLI

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6903]
We're renaming some flags to match the common naming convention:
- `no_print` &rarr; `print`
- `flags.DEFER_MODE` / (env var) `DBT_DEFER_TO_STATE` &rarr; `defer`
- `flags.FAVOR_STATE_MODE` &rarr; `favor_state`
- `flags.ARTIFACT_STATE_PATH` / (env var) `DBT_ARTIFACT_STATE_PATH` &rarr; `state`
- (`--single-threaded` was renamed, but it's not something we publicly document, and it might only be relevant for `dbt-rpc`?)

**Acceptance criteria:** We continue to respect the old name:
- respect the old name in env var
- respect the old name in CLI flag
- raise a deprecation warning encouraging them to switch over to the new name
- have tests for each flag changed

I'm less concerned about the CLI flag, which raises a clear error already:
```
$ python3 -m dbt.cli.main --no-send-anonymous-usage-stats run
Usage: python -m dbt.cli.main [OPTIONS] COMMAND [ARGS]...
Try 'python -m dbt.cli.main -h' for help.

Error: No such option: --no-send-anonymous-usage-stats (Possible options: --anonymous-usage-stats, --no-anonymous-usage-stats)
```

**Comment by stu-k** [comment]
After speaking with @iknox-fa, we can keep the `send_anonymous_usage_stats` as is, as it conforms with existing naming of params. I will edit the issue description to remove this change, and any mentions of the `UserConfig`, as this was the only env var held in `UserConfig`.

**Comment by jtcohen6** [comment]
@stu-k The `no_print` &rarr; `print` rename _should_ also be relevant for `UserConfig`, since this is in the same category of "global config" that's settable in three places (CLI flag, env var, user config): https://docs.getdbt.com/reference/global-configs#suppress-print-messages-in-stdout

I see it's actually missing from [the class here](https://github.com/dbt-labs/dbt-core/blob/6b5e38ee2855e8739414c7f5172b80a2090c3a0c/core/dbt/contracts/project.py#L244-L260)! That's an oversight, and speaks to the way that the definition and initialization of these configs have been poorly coordinated in the past.

Not very high priority, so I'd be open to discussing kicking it out of scope — just want to make sure we're aligned on the functionality that's documented / expected.

**Comment by jtcohen6** [comment]
@stu-k Opened as a new ticket: https://github.com/dbt-labs/dbt-core/issues/7036
