### ISSUE TITLE
[CT-2067] [Bug] Nightly release tests fail

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#6906]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

[Nightly release test](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/nightly-release.yml) fails on the PyPI step because PEP440 doesn't allow releasing with the [local version identifier](https://peps.python.org/pep-0440/#local-version-identifiers) in the version.  This tests use `+nightly` on the end and that should be removed from the version.

### Expected Behavior

Nightly release tests pass and publish to PyPI test.

### Steps To Reproduce

Run the [nightly release workflow](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/nightly-release.yml)

### Relevant log output

```shell
25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
         '1.5.0a1.dev2082023+nightly' is an invalid value for Version. Error:   
         Can't use PEP 440 local versions. See                                  
         https://packaging.python.org/specifications/core-metadata for more     
         information.  
```
```


### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
> because PEP440

classic
