### ISSUE TITLE
[CT-2069] Unexpected behavior with global/subcommand flags

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6913]
For backwards compatibility with older behavior, some flags are implemented at both the "global" ("parent") level, and also at the "subcommand" ("child") level. We have some tricky logic to handle this potential duplication:
https://github.com/dbt-labs/dbt-core/blob/77748571b46593999dfc45b717a1bc1189ec2533/core/dbt/cli/flags.py#L70-L95

On `feature/click-cli` branch, I'm observing behavior where:
- parent flag alone isn't respected
- child flag alone is respected
- flag provided to both parent + child, parent flag takes precedence and is respected

**Expected behavior:**
- parent flag alone **is** (!) respected
- child flag alone is respected
- if both parent + child flags are passed, raise an error (ideal) — but if needed, we can document that the parent flag always wins

### Example

Create a new dbt project, and add `require-dbt-version: "1.4.1"` to `dbt_project.yml`.

```bash
$ python3 -m dbt.cli.main --no-version-check parse
...
dbt.exceptions.DbtProjectError: Runtime Error
  This version of dbt is not supported with the 'test' package.
    Installed version of dbt: =1.5.0-a1
    Required version of dbt for 'test': ['=1.4.1']
  Check for a different version of the 'test' package, or run dbt again with --no-version-check
```
```
$ python3 -m dbt.cli.main parse --no-version-check
23:52:24  Performance info: target/perf_info.json
```
```
$ python3 -m dbt.cli.main --no-version-check parse --version-check
23:52:27  Performance info: target/perf_info.json
```

**Comment by stu-k** [comment]
@jtcohen6 Can we choose only the option where there are not parent flags? LIke `dbt run --flag` and never `dbt --flag run`?

**Comment by jtcohen6** [comment]
@stu-k That would be a significant breaking change for a large number of existing CLI users, so I don't see it as a viable option.

**Comment by stu-k** [comment]
@jtcohen6 Would it be fair to ask that a flag be defined in either the parent or child level, not both?

✅ `dbt --full-refresh run` OR (not both) `dbt run --full-refresh`
🚫 `dbt --full-refresh run --full-refresh`

**Comment by jtcohen6** [comment]
It's clear that this is the intent of the [`assign_params`](https://github.com/dbt-labs/dbt-core/blob/77748571b46593999dfc45b717a1bc1189ec2533/core/dbt/cli/flags.py#L70) method, but it's not currently working.

Acceptance criteria for this ticket:
- P0: Respect "parent"-level flag when passed alone
- P1: Raise an exception if the same flag is passed in both places, as [this logic](https://github.com/dbt-labs/dbt-core/blob/77748571b46593999dfc45b717a1bc1189ec2533/core/dbt/cli/flags.py#L35-L45) is intended to accomplish. Only do this if it's a minor lift. Otherwise we document the current behavior.

**Comment by jtcohen6** [comment]
@ChenyuLInx says:

https://github.com/dbt-labs/dbt-core/blob/77748571b46593999dfc45b717a1bc1189ec2533/core/dbt/cli/flags.py#L87

This is the wrong `ctx`. It is currently the context of the child, and it should be the context of the parent.

**Comment by iknox-fa** [comment]
> @jtcohen6 Would it be fair to ask that a flag be defined in either the parent or child level, not both?
> 
> ✅ `dbt --full-refresh run` OR (not both) `dbt run --full-refresh` 🚫 `dbt --full-refresh run --full-refresh`

@jtcohen6 Just to be clear-- your 👍 on this comment means there is no legitimate use case where the same flag will be populated on multiple levels?  I ask because right now we have logic [here](https://github.com/dbt-labs/dbt-core/blob/567e2ca2be0ecb6272b4c873c8a3489a3696b7f6/core/dbt/cli/flags.py#L119) specifically to support that happening.

**Comment by jtcohen6** [comment]
> @jtcohen6 Just to be clear-- your 👍 on this comment means t[here](https://github.com/dbt-labs/dbt-core/blob/567e2ca2be0ecb6272b4c873c8a3489a3696b7f6/core/dbt/cli/flags.py#L119) is no legitimate use case where the same flag will be populated on multiple levels? I ask because right now we have logic here specifically to support that happening.

IMO, if the same flag is passed at both the "parent" and the "child" levels:
- Ideal: Raise an error
- Acceptable: We have a consistent behavior whereby either the "parent" or the "child" always wins, and we document that behavior.
