### ISSUE TITLE
[CT-2126] [Spike] Enforce model contracts for python models

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6984]
If possible, enforce model contracts for python models. 

Otherwise, keep the parsing error we're currently if contracts are used on python models around. 

Relevant discussion: https://github.com/dbt-labs/dbt-core/pull/6271/files#r1084049809

**Comment by jtcohen6** [comment]
For SQL models, we run an "empty" version of the model query (`where false limit 0`) to extract the output schema in advance. I don't think any equivalent exists for Python models.

We could have the option of:
- Always create the model in a temporary location
- Compare the output result to the contracted set of columns, and raise an error if they differ
- Apply constraints after-the-fact, and raise an error if their enforcement fails
- IFF the contract enforcement passes, atomically replace the existing table with the current version of the model (whether `alter` swap, or `clone`, or `create or replace {tbl} as select * from {tmp_tbl}`)

The biggest downsides are:
- (For end users) Contract enforcement will take much more time & compute, versus for SQL models
- (For us & adapter maintainers) This would require slightly different & trickier codepaths for contract enforcement, within [`create_table_as`](https://github.com/dbt-labs/dbt-snowflake/blob/c61372308aaae15320ed474d541bd1174010f147/dbt/include/snowflake/macros/adapters.sql#L48-L50) and [`py_write_table`](https://github.com/dbt-labs/dbt-snowflake/blob/c61372308aaae15320ed474d541bd1174010f147/dbt/include/snowflake/macros/materializations/table.sql#L41-L62)
