### ISSUE TITLE
[CT-2139] Don't exclude `Formatting` events from JSON-formatted logs

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6998]
We have some events that are only for formatting / aesthetic display in the terminal. (Previously, this was called `EmptyLine`; in v1.5 we're renaming it to `Formatting`.) Historically, we've intentionally _excluded_ these events from JSON-formatted structured logs. This makes sense in one way, but it's actively unhelpful for someone who wants _both_ the full structure of JSON logs _and_ the ability to produce their own text-formatted logs at parity with `dbt-core`'s.

_copying from slack_
> @jtcohen6
> While it's great to be opinionated about what & how we display `text`, it does feel weird to me that we're depriving the json log consumer of some detail/flexibility.
> @peterallenwebb:
> On balance, I think we should include the EmptyLine/Formatting events. I infer that the original logic behind excluding them was that they would be confusing/unwanted by consumers, but the existence of this use case suggests otherwise.

### Proposed change

Remove the line from `_stdout_filter` that filters out `Formatting` if we're emitting JSON-formatted logs:
https://github.com/dbt-labs/dbt-core/blob/c952d44ec5c2506995fbad75320acbae49125d3d/core/dbt/events/functions.py#L89

[`TextOnly`](https://github.com/dbt-labs/dbt-core/search?q=TextOnly) achieves the same purpose, for legacy logging _only_. We could remove it now, or remove it when we deprecate legacy logging in ~v1.6~ v1.7.

**Comment by emmyoop** [comment]
Add a test looking for formatting to ensure it's getting through.

**Comment by jtcohen6** [comment]
Let's check with Orchestration & Experience (IDE) before backporting this change

**Comment by emmyoop** [comment]
We have been including the `Formatting` event in json logs since the 1.5 release due to a bug in our code.  I'm adding a test and removing dead code but this won't result in an actual change.

**Comment by jtcohen6** [comment]
@emmyoop hah! I'll take it :)
