### ISSUE TITLE
[CT-2150] [Bug] "RecursionError: maximum recursion depth exceeded" in Python3.10

### ISSUE THREAD

**Issue by haf** [dbt-labs/dbt-core#7022]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I don't believe this to be a new bug! But it's not in dbt Cloud and it's not about troubleshooting my own project.

See https://github.com/dbt-labs/dbt-core/issues/4560 — it's currently not solved, because even using dbt-core v1.4.1 doesn't solve the problem. I asked a comment in October 2022 about whether the ticket should be re-opened but received no reply

### Expected Behavior

See https://github.com/dbt-labs/dbt-core/issues/4560 — it's currently not solved, because even using dbt-core v1.4.1 doesn't solve the problem. I asked a comment in October 2022 about whether the ticket should be re-opened but received no reply

### Steps To Reproduce

See https://github.com/dbt-labs/dbt-core/issues/4560 — it's currently not solved, because even using dbt-core v1.4.1 doesn't solve the problem. I asked a comment in October 2022 about whether the ticket should be re-opened but received no reply

### Environment

- OS: macOS
- Python: 3.10

```
poetry run datapipe dbt --version
Core:
  - installed: 1.4.1
  - latest:    1.4.1 - Up to date!

Plugins:
  - bigquery: 1.4.1 - Up to date!
  - postgres: 1.4.1 - Up to date!
```

**Comment by dbeatty10** [comment]
@haf I'm sorry about the lack of response in the [original](https://github.com/dbt-labs/dbt-core/issues/4560) thread!

I've re-opened that issue, and I'm going to close this one as a duplicate.

We've got some eyes on this, and we'll respond in that issue.
