### ISSUE TITLE
[CT-2160] [Regression] "Legacy" Logging Broken in 1.4.2rc1

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#7028]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

When running a dbt command from the cli with the DBT_USE_LEGACY_LOGGER env var set, the console logs are written via a standard Python logger, rather than the logbook logger, as they should be to support legacy logging scenarios correctly.

### Expected/Previous Behavior

Logging should be directed to the logbook log with this flags set, just as it was in 1.4.1.

### Steps To Reproduce

Issue was seen when running `dbt build` with DBT_USE_LEGACY_LOGGER=True on the jaffle_shop project with 1.4.2rc1 on macOS with Python 3.10, but likely affects all platforms, Python versions, and projects.

### Relevant log output

At the console, logs look the same, but integrations relying on logbook are failing.

### Environment

```markdown
- OS: macOS
- Python: 3.10
- dbt (working version): 1.4.1
- dbt (regression version): 1.4.2rc1
```

### Which database adapter are you using with dbt?

postgres

**Comment by jtcohen6** [comment]
Resolved by https://github.com/dbt-labs/dbt-core/pull/7029
