### ISSUE TITLE
[CT-2162] [Feature] Fix Drop schema for functional tests to take into account changes in schema

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-core#7030]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently some tests in adapters such as `dbt-bigquery` and `dbt-snowflake` can have tests artifacts remain in database slowly filling up till limits are reached. this is due in part to changes in schema for tests not being cleaned up proplerly. `drop_schema` only drops for default defined schema for the test.

### Describe alternatives you've considered

We have added cleanup fixtures to some tests that required it. more popped up as we finished off test conversions

### Who will this benefit?

adapter maintainers

**Comment by damian3031** [comment]
We are also facing this issue in `dbt-trino`

**Comment by McKnight-42** [comment]
@damian3031 currently the best way to fix this is to add a `teardown_method` 

```
@pytest.fixture(scope="function", autouse=True)
    def teardown_method(self, project):
        yield
        relation = project.adapter.Relation.create(
            database=, schema=f"{project.test_schema}_{ALT_SCHEMA_NAME}"
        )
        project.adapter.drop_schema(relation)
```

to the `Test` class of the test.
There are a few root causes of this to happen 
      1. The database is changed and different from originally defined test schema name and may not drop properly so you would need to specify that change in the Relation part of teardown.
      2. Mid test we denote a custom schema name different from the original test schema and the default drop relation teardown method of the functional test will not have been able to get this new information so you need to specify it in the `ALT_SCHEMA_NAME`
      - In the case a test creates multiple schema name changes you can use a for loop to cycle through all known version using just the one `project.adapter.Relation.create` by simply defining the schemas names as a list global variable.
      
The reason we have to keep this at adapter level is due to naming variations between adapters (capitalization, etc).
