### ISSUE TITLE
[CT-2167] Enforce model contracts for default view materializations

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#7034]
Currently, we [assert column equivalence during table creation](https://github.com/dbt-labs/dbt-core/pull/6271/files#diff-7246f19f4d12042d172ac61b3d0c4564ea27dd8825870b35425ede1ea41625dbR28-R31). 

We'll need to similarly assert column equivalence in [default view materializations](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/models/view/create_view_as.sql). 

Note - we won't be able to generate `column_spec_ddl` as column spec ddl is generally unsupported for view creation.

**Comment by emmyoop** [comment]
Also add tests but they can follow the pattern for the table version but for a view.
