### ISSUE TITLE
[CT-2171] [Feature] Add adapter(s) version(s) to the log

### ISSUE THREAD

**Issue by Fleid** [dbt-labs/dbt-core#7038]
It would make things much easier when debugging a dbt invocation, if the adapter version were present.

Right now we get (below for a `dbt debug`)

```
============================== 2023-02-22 23:21:37.421632 | d8954cb4-b0c3-461a-a0f1-68c918c2fe23 ==============================
[0m23:21:37.421632 [info ] [MainThread]: Running with dbt=1.4.1
[0m23:21:37.422456 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '/Users/fleide/.dbt', 'send_anonymous_usage_stats': True, 'quiet': False, 'no_print': False, 'cache_selected_only': False, 'config_dir': False, 'which': 'debug', 'indirect_selection': 'eager'}
...
[0m23:21:38.799040 [debug] [MainThread]: Flushing usage events
[0m23:21:39.154756 [debug] [MainThread]: Connection 'debug' was properly closed.
```

But I could be running that with `dbt-bigquery` 1.4.0, 1.4.1 or 1.4.2!

If we could get that info logeed (anywhere practical, it doesn't need to be at the top):

```
============================== 2023-02-22 23:21:37.421632 | d8954cb4-b0c3-461a-a0f1-68c918c2fe23 ==============================
[0m23:21:37.421632 [info ] [MainThread]: Running with dbt=1.4.1
[0m23:21:37.422456 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '/Users/fleide/.dbt', 'send_anonymous_usage_stats': True, 'quiet': False, 'no_print': False, 'cache_selected_only': False, 'config_dir': False, 'which': 'debug', 'indirect_selection': 'eager'}
...
[0m23:21:38.122456 [info ] [MainThread]: Running with dbt-bigquery=1.4.0
...
[0m23:21:38.799040 [debug] [MainThread]: Flushing usage events
[0m23:21:39.154756 [debug] [MainThread]: Connection 'debug' was properly closed.
```

**Comment by Fleid** [comment]
@VersusFacit that's one you may be interested in contributing, even though that's pretty core ;)

**Comment by dbeatty10** [comment]
➕

**Comment by jtcohen6** [comment]
yes! related older issue: https://github.com/dbt-labs/dbt-core/issues/5124

**Comment by VersusFacit** [comment]
Love me some tooling. And I certainly enjoy working on the `tasks/` dir in `core`! 🍵

**Comment by Fleid** [comment]
@jtcohen6 and I did search for an earlier issue, but couldn't find one.
You're good (or you've been around these parts for too long, up to you to decide which one :D)

**Comment by jtcohen6** [comment]
Also related!
- https://github.com/dbt-labs/dbt-core/issues/6097

To @Fleid's point in the issue description ("anywhere practical, it doesn't need to be at the top") — we actually load the adapter a little ways in, so the point where we can know the "active" adapter version is certainly later than when we can know the installed version of `dbt-core`.

We need to add back telemetry for the "active" adapter's `adapter_type` and `adapter_unique_id`. We could also include the `adapter_version` in that telemetry, and at the same point, fire an event / log message containing any/all of those bits of info.

**Comment by VersusFacit** [comment]
I think #7741 fixes this!

**Comment by dbeatty10** [comment]
Nice @VersusFacit 🤩

If possible, we'd be looking for the adapter version to be added to all tasks.
