### ISSUE TITLE
[CT-2175] Add ability to ignore columns in generated model queries

### ISSUE THREAD

**Issue by eavonius** [dbt-labs/dbt-core#7042]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In [this post on the DBT discourse](https://discourse.getdbt.com/t/how-to-handle-generated-columns-in-target-model-in-incremental-materialization/4334) the user 'ypc-faros' came up with a solution for a problem I was also having that seems like a no-brainer for including in dbt core.

Essentially, the problem we both had is when you're creating an incremental model that materializes into a table you've created ahead of time that has generated columns. They [came up with a workaround](https://github.com/faros-ai/faros-community-edition/blob/main/dbt-transforms/macros/incremental.sql#L63-L69) that allows you to add an "ignored_columns" section to the config of your model. Columns present in this config are skipped in the generated query.

It works, but as written it required you to add this setting to all of your models. I tweaked their code slightly to not require this config setting, but use it if present. I've created [a fork with the code that does this](https://github.com/eavonius/dbt-core/commit/6b148c8ec4f8e2b18e5803790c5d6f21cc3320f9). 

**I can submit as a PR if you'd like to consider it for inclusion**.

Thanks for your consideration.

### Describe alternatives you've considered

I could find no alternatives.

### Who will this benefit?

Anyone who uses generated columns in their DBT models that are materialized incrementally.

### Are you interested in contributing this feature?

Yes, I have some code to submit if you want to check it out.

### Anything else?

Here's [the proposed change from my fork](https://github.com/eavonius/dbt-core/commit/6b148c8ec4f8e2b18e5803790c5d6f21cc3320f9).

**Comment by dbeatty10** [comment]
Thanks for opening @eavonius ! All the links you sent were really helpful.

Did you try the [`dbt_utils.star()`](https://github.com/dbt-labs/dbt-utils#star-source) macro for your use-case, by any chance?

`dbt_utils.star()` uses `dbt_utils.get_filtered_columns_in_relation()` under the covers, which looks [really similar](https://github.com/dbt-labs/dbt-utils/blob/d2795428e163fee6e4dbc3ab9b8296e9e813c0b4/macros/sql/get_filtered_columns_in_relation.sql) to the logic in your PR.

```
select
{{ dbt_utils.star(from=ref('my_model'), except=["exclude_field_1", "exclude_field_2"]) }}
from {{ ref('my_model') }}
```

If you haven't used it before, the `dbt_utils` package has some handy stuff. The main caveat is that you have to install it before using it, which is described [here](https://hub.getdbt.com/dbt-labs/dbt_utils/latest/).

**Comment by eavonius** [comment]
Hey thanks @dbeatty10 . I've used dbt utils but never noticed this function.

Let me see if I can get that working for me and get back to you.

**Comment by eavonius** [comment]
After looking at this more, I'm not sure that it will fit my use case.

This query selects from one ref table, does a bunch of joins, and is then unioned with another query from a different table with different joins. Those are wrapped in a WITH statement, and at the end selected from with an is_incremental check (it's a materialized table). 

With the star macro, would I need to generate these results in a non-materialized view, then select out of that in another downstream model that does the ignoring of the columns before they're inserted? It seems like this would be expensive since the is_incremental check would run on the downstream model. I'd also have to introduce another asset purely for the purpose of excluding columns. Which isn't the end of the world, but I usually try not to add models unless they are an ultimate output or an output to at least two downstream sources.

Open to your thoughts and ideas, thanks again.

**Comment by dbeatty10** [comment]
@eavonius totally understand that you're trying to keep things as streamlined and efficient as possible.

It sounds like the crux of the issue for you and @ypc-faros both ran into was incremental models + [generated columns](https://www.postgresql.org/docs/current/ddl-generated-columns.html) in Postgres. Although I've seen generated columns before in other databases like SQLite (and others), I haven't actually used them myself. So hopefully you'll be patient with me while I catch up 😄 

Where do you define the expression that is used for the generated column? My guess is that you're creating the initial DDL for the incremental model outside of dbt?

My understanding is that Postgres only supports "stored" generated columns. Are there reasons why you couldn't (or wouldn't want to) remove the definition of the generated column from the DDL and add that expression into the incremental model instead?

**Comment by eavonius** [comment]
Hey @dbeatty10 thanks again for the follow up. Been busy here, apologies for the delay in responding.

I've built a pretty sophisticated product for a client that uses a combination of dagster (a python based data DAG orchestrator) and DBT. This product always uses DBT to generate views, or tables that are sourced only ever from things like CSV files. However some of these tables are sourced from imported data in staged tables, but then also become transactional tables that a web application can modify. 

I know this is a bit of a non-standard use of dbt since the vanilla use case is pure data warehousing. I use alembic (a python based database migration utility) to create and alter schemas for tables that DBT interacts with when the web app also has access to modifying records in those tables. This is so I can do non-destructive altering of the schema with complete control.

I know DBT has some schema synching capabilities, but I like to have more control when I'm iterating on a product and pushing regular changes out into the staging and production environments without disrupting the client's business too much. 

I also use alembic to create (and update) indexes, and in a few occasions some triggers as I work on the product. I have seen that DBT does have some pre/post model hooking capabilities, but to be honest I haven't used those much yet. Maybe that would be the more appropriate thing to do here? Not sure.

**Comment by graciegoheen** [comment]
Hello! New to this discussion, so trying to catch up on the context. What's the different between the `ignore_columns` config that ypc-faros is proposing in [his discourse article](https://discourse.getdbt.com/t/how-to-handle-generated-columns-in-target-model-in-incremental-materialization/4334/2), vs. the `merge_exclude_columns` [config in dbt-core](https://docs.getdbt.com/docs/build/incremental-models#:~:text=Alternatively%2C%20you%20can%20specify%20a%20list%20of%20columns%20to%20exclude%20from%20being%20updated%20by%20passing%20a%20list%20of%20column%20names%20to%20a%20merge_exclude_columns%20config.)?

Would `merge_exclude_columns` work for your use case?
```
{{
  config(
    materialized = 'incremental',
    unique_key = 'id',
    merge_exclude_columns = ['created_at'],
    ...
  )
}}

select ...
```
