### ISSUE TITLE
[CT-2187] [Feature] dbt docs stop

### ISSUE THREAD

**Issue by rainermensing** [dbt-labs/dbt-core#7052]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I am running dbt on a remote server and would like a user to have the ability to stop the docs server using a GUI. However, as of now there is only a command to start, not stop the server.
I would like to stop the webserver from the CLI using a command like ``dbt docs stop``

This [SO Thread](https://stackoverflow.com/questions/10085996/shutdown-socketserver-serve-forever-in-one-thread-python-application) could be a starting point.

### Who will this benefit?

I think it would be great to be able to stop the server when it is only needed rarely.

### Are you interested in contributing this feature?

I can ultimately try to submit something, but would appreciate some support.

**Comment by jtcohen6** [comment]
@rainermensing Thanks for opening!

`dbt docs serve` does little more than start a simple HTTP server to view the static documentation site. This is just about all the code defining the operation:

https://github.com/dbt-labs/dbt-core/blob/0ef9931d197c996ccd4e3caf641729176eceda99/core/dbt/task/serve.py#L23-L28

Nowadays, if I'm honest, this doesn't make much sense as functionality that lives right in `dbt-core`. It's not really specific to dbt at all. So, this isn't something we'd be likely to prioritize; I hesitate to even expand its capabilities.

So, two questions:
- Is there a reason why you'd want a separate command, versus stopping the remote server via a simple interrupt (`ctrl^C`)?
- At the point where you're running your own docs server remotely, wouldn't it make more sense for you to fully "own" the code for spinning up & down that server? That feels both reasonable, given how simple the existing implementation is, and desirable, gvien the amount of customization I expect you may want/need.

I'm going to close this issue as a `wontfix` in the meantime, but I'm happy to hear more about your use case, and to hear if other folks have the same need.
