### ISSUE TITLE
[CT-2231] [Feature] Print macro stack trace upon error.

### ISSUE THREAD

**Issue by elongl** [dbt-labs/dbt-core#7085]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I'd like dbt to print a stack trace upon stumbling an error (whether a Compilation Error or a Database Error, etc.).

At the moment, it's incredibly hard to understand where does an error originates from and all you get is the final error message. For instance, finding the root cause of the _"each UNION query must have the same number of columns"_ in the [following test](https://github.com/elementary-data/dbt-data-reliability/blob/012dc165399b990f974127c9a863c8b5d51775b2/macros/edr/tests/test_table_anomalies.sql#L0-L1) is very difficult. It would be incredibly useful if we'd print the macro stack (which is already stored and can be accessed easily) like programming languages do.

### Are you interested in contributing this feature?

Yes.

**Comment by dbeatty10** [comment]
@elongl We feel your pain how difficult debugging can be sometimes 😢

Does `logs/dbt.log` have the level of detail you are looking for?

Did you already try [debug-level logging](https://docs.getdbt.com/reference/global-configs#debug-level-logging) `dbt --debug`, by any chance?
