### ISSUE TITLE
[CT-2254] `dbt debug` for connection testing

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7104]
_Much older issue in the same vein: https://github.com/dbt-labs/dbt-core/issues/3735_

It should be possible to use `dbt debug` for connection testing. Currently, `debug` also includes checks for:
1. Valid `profiles.yml` file
2. Valid `dbt_project.yml` file
3. `git` as an installed dependency (for `deps`)
4. dbt can connect and submit a "debug" query to the selected profile

Of those checks, we really only need the last one for connection testing. Ideally, we'd be able to skip the other checks (perhaps by passing a flag?) and return success/error (programmatically & as CLI exit code) on the basis of the "debug" query only.

If we had to hack this today, it would be _sorta_ possible by examining the structured events (`DebugCmdOut`) returned from the `debug` command, but this hardly feels like a stable interface.

### Why `dbt debug`?

Why not just an interactive query (new `preview` command) with the query hard-coded to `select 1 as id`? Reasons to prefer:
- leveraging an adapter method, [`debug_query`](https://github.com/dbt-labs/dbt-core/blob/cbb9117ab997289062cd5bacaf4cfd4466ab9b1e/core/dbt/adapters/base/impl.py#L229-L230)
- it's part of dbt-core's top-level API, and clearly the intent of `debug`

### Questions
- How should the profile be provided? In `profiles.yml`, or could it be provided as a Python data structure?
- Could we avoid the need to have a `dbt_project.yml`? Just use a "dummy"/empty `dbt_project.yml`?

### Acceptance criteria

- Given the contents of a profile _only_, validate that profile via `dbt debug`, and return success/error

**Comment by nssalian** [comment]
An alternative suggestion would be to add a command 
`dbt test_connection` that would use the selected profile. I can open a separate issue to surface this alternative way.

**Comment by VersusFacit** [comment]
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/67295367/233598569-c62d402a-d21b-45a0-b2bb-1ffb3849fe2c.png">
Just going by what we see here, I would say we communicate that dbt debug exists to support and validation of a dbt environment. Having a flag that skipped those validation steps would mirror the `git commit --no-verify` workflow. Basically, just validate that the connection makes sense. I worry that if we create a new command which under the hood is leveraging the same code invites unclear interfaces at the executable level

**Comment by VersusFacit** [comment]
With the merge of #7741 , the workflow for this in 1.6 and on will be `dbt debug --connection`.

Other flag skips/features may be added. See [this issue](https://github.com/dbt-labs/dbt-core/issues/7818).
