### ISSUE TITLE
[CT-2257] Reimplement automated documentation generation for CLI

### ISSUE THREAD

**Issue by stu-k** [dbt-labs/dbt-core#7106]
### Details

In #7089, the workflow for auto generating documentation for the new CLI was removed. It actively hindered development and created frustrating merge conflicts. This should instead be coupled with the release workflow to make a commit on main with the updated docs.

**Comment by jtcohen6** [comment]
@stu-k I'm going to add to this tracking issue:
- https://github.com/dbt-labs/dbt-core/issues/6548

Does it feel like the same or separate work from the issue we opened yesterday?
- https://github.com/dbt-labs/dbt-core/issues/7098

**Comment by MichelleArk** [comment]
> created frustrating merge conflicts

Specifically around the `environment.pickle` file. If it's not necessary for sphinx, we should avoid checking it in and/or add .gitignore it.
