### ISSUE TITLE
[CT-2261] [Bug] --fail-fast still executes the remaining models

### ISSUE THREAD

**Issue by ecerulm** [dbt-labs/dbt-core#7110]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running with `dbt run -x `  or `dbt run --fail-fast` , if one of the models fails to build, it won't cancel the second one

With dbt==1.4.1 dbt-snowflake==1.4.1

It starts `model2` and then `CANCEL model1` (the one that already failed / ERRORed), then waits for completion of `model2`. I think it was supposed to cancel `model2` not wait for it to complete. 

### Expected Behavior

From the documentation at https://docs.getdbt.com/reference/global-configs#failing-fast I would expected to 

START model1
ERROR model1
START model2
CANCEL model2
ERROR model2

but  in my case it does

START model1
ERROR model1
START model2
CANCEL **model1**
OK model2

I think it was supposed to CANCEL model2 since model1 failed. But no, it waits for completion of model2. 

### Steps To Reproduce

1. create a new project
2. add 2 models that take 5 minutes to complete each 
3. introduce a SQL syntax error in the one that executes first
4. run with `dbt run -x` 
5. dbt should exit quickly since the syntax error, it detected quickly. but it instead waits for the second one to complete (which defeats the purpose of --fail-fast)

### Relevant log output

```shell
dbt run -x
13:26:08  Running with dbt=1.4.1
13:26:08  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 304 macros, 0 operations, 0 seed files, 2 sources, 0 exposures, 0 metrics
13:26:08
13:26:10  Concurrency: 1 threads (target='dev')
13:26:10
13:26:10  1 of 2 START sql table model xxx.model1  [RUN]
13:26:11  1 of 2 ERROR creating sql table model xxx.model1  [ERROR in 0.80s]
13:26:11  2 of 2 START sql table model xxx.model2 ... [RUN]
13:26:11  CANCEL query model.myproject.model1 ......... [CANCEL]

```
```


### Environment

```markdown
- OS: macOS Monterey
- Python: 3.10.10
- dbt: 1.4.1
```

### Which database adapter are you using with dbt?

snowflake

**Comment by ecerulm** [comment]
well apparently the right syntax is `dbt --fail-fast run`  not `dbt run --fail-fast`.

**Comment by ecerulm** [comment]
Anyway `dbt run --fail-fast` should fail with `dbt: error: unrecognized arguments: --fail-fast`, it's very misleading to accept the parameter and do nothing. 

At least fail and mention that it should be invoked as a global option instead.

**Comment by dbeatty10** [comment]
Thanks for sharing your experience @ecerulm !

Agreed that this isn't the behavior we want ❌ 

💡 In fact, wouldn't it be nice if it just accepted it with either syntax? We have a spike to investigate that possibility: https://github.com/dbt-labs/dbt-core/issues/6497

Looking foward, 1.4.x is the last series we'll be using `argparse` for our CLI. Starting in 1.5.0, we'll be using `click` instead. There's multiple things we'll want to resolved related to `--fail-fast`. There's a known bug with parent/child flags: https://github.com/dbt-labs/dbt-core/issues/6913. Also, while investigating how your situation will be handled in 1.5, I ran into another issue: https://github.com/dbt-labs/dbt-core/issues/7118

I'm going to close this issue in favor of https://github.com/dbt-labs/dbt-core/issues/6497. Thanks again for raising this issue 🏆
