### ISSUE TITLE
[CT-2265] [Feature] Allow adapters to overwrite python model name resolution

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-core#7114]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We've realized, as part of [this change](https://github.com/dbt-labs/dbt-core/pull/6620), that there is an opportunity to clean up our code and allow adapters (in this case dbt-bigquery) to have a different method in handling quoting in python models

**Comment by jtcohen6** [comment]
Attempted to summarize our huddle in this comment: https://github.com/dbt-labs/dbt-core/pull/6620#discussion_r1124907253
