### ISSUE TITLE
[CT-2275] [Bug] Execute DBT command on multi tags

### ISSUE THREAD

**Issue by mytreyireddy** [dbt-labs/dbt-core#7129]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Execute DBT command on multi tags : `dbt run --select tag:products, tag:orders`

### Expected Behavior

Executing the multi--tag sql models in DBT should execute the models simultaneously .

### Steps To Reproduce

`dbt run --select tag:products, tag:orders or dbt run -m tag:products, tag:orders.`

The above command is executing only the second tag related tables and not executing the first tag related tables.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @mytreyireddy !

Within our selection syntax commas (`,`) have a special meaning to indicate a set intersection. You can see a few different examples [here](https://docs.getdbt.com/reference/node-selection/syntax#examples).

If you want nodes that have either `tag:products` **OR** `tag:orders`, then you'll want this instead:
```
dbt run --select tag:products tag:orders
```

If you want to select only nodes that have both the tags `tag:products` **AND** `tag:orders`, then you'll want this:
```
dbt run --select tag:products,tag:orders
```

Put another way, a space (` `) is like `OR` and a comma (`,`) is like `AND`.

It sounds like you want the first option shown above (without any commas).

Wanna give this a try and see if it works for you?
