### ISSUE TITLE
[CT-2288] [Bug] Latest containers are not released and the wrong versions are marked `latest`

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#7149]
### Current Behavior

We ran the workflow to generate the new containers for v1.4.4: [workflow output](https://github.com/dbt-labs/dbt-core/actions/runs/4308505619)

There were unexpected inputs found when trying to determine if this version is the latest (it is) in [this step](https://github.com/dbt-labs/dbt-core/actions/runs/4308505619/jobs/7514856225)

Which caused the build and publish steps to get skipped [here](https://github.com/dbt-labs/dbt-core/actions/runs/4308505619/jobs/7514867098)

We have not fully released `dbt-postgres` specifically.

Additionally the wrong package is marked as latest

![Screen Shot 2023-03-09 at 2 59 03 PM](https://user-images.githubusercontent.com/7070049/224156487-3fdaf7bf-b289-49c8-88a6-a3f6bffcbc78.png)

View all packages [here](https://github.com/orgs/dbt-labs/packages)

### Expected Behavior

1. everything gets released, and if it doesn't we get some kind of error
2. the correct version gets marked as `latest`

### Steps To Reproduce

Run [release-docker.yml](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/release-docker.yml)

### Additional Context

Current Package Versions

| Package | Version Marked Latest | Most up to Date Package Version | Latest GitHub Release Version |
| ----- | ----- | ----- | ----- |
| dbt-core | 1.3.2 | 1.4.4 | n/a|
| dbt-postgres | 1.2.3 | 1.4.1 | 1.4.4|
| dbt-snowflake | 1.3.latest / 1.3.0 | 1.4.1 | 1.4.1 |
| dbt-redshift | 1.3.latest / 1.3.0 | 1.4.0 | 1.4.0 |
| dbt-bigquery | 1.3.latest / 1.3.0 | 1.4.1 | 1.4.1 |
| dbt-spark | 1.3.latest / 1.3.0 | 1.4.1 | 1.4.1 |

**Comment by raginjason** [comment]
I am looking to add some CI to my dbt project and this is a blocker for me. I am on v1.4.6 and now need to look at reverting to v1.4.3 to get my project added to CI

**Comment by joaocc** [comment]
Hi. Same here... Thanks

**Comment by mdemierre** [comment]
`dbt-postgres` is back, so not affected anymore, sorry for the noise.

**Comment by dbeatty10** [comment]
Resolved by #9495
