### ISSUE TITLE
[CT-2304] [Bug] run-operation cannot be run with --no-version-check flag

### ISSUE THREAD

**Issue by lucianmoldovanu** [dbt-labs/dbt-core#7165]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

As a temporary exception, I need to run my currently installed DBT (i.e. 1.3.2) despite the project-driven requirement for DBT 1.3.3. When running a macro via `dbt run-operation` I get the following response:
```
15:39:30  Encountered an error while reading the project:
15:39:30    ERROR: Runtime Error
  This version of dbt is not supported with the '...' package.
    Installed version of dbt: =1.3.2
    Required version of dbt for '...': ['=1.3.3']
  Check for a different version of the '...' package, or run dbt again with --no-version-check
```

When I then run `dbt run-operation --no-version-check`, this is not accepted and I get the following error:
```
dbt: error: unrecognized arguments: --no-version-check
```

### Expected Behavior

`dbt run-operation --no-version-check` is successful, just like running `dbt run ... --no-version-check` works fine

### Steps To Reproduce

1. Using DBT 1.3.2 installed (no specific config, just a random demo project)
2. `dbt run ... --no-version-check` -> ok
3. `dbt run-operation ... --no-version-check` -> error

### Environment

```markdown
- OS: Ubuntu 22.04
- Python: 3.10.6
- dbt: 1.3.2
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reporting this @lucianmoldovanu !

Could you try this and see if it works for you?
```shell
dbt --no-version-check run-operation {...}
```

Instead of:
```shell
dbt run-operation {...} --no-version-check
```

### Example
I was able to reproduce what you are seeing, but was also able to get it to work by changing the order of `--no-version-check`.

First, I added `require-dbt-version: 0.0.0` to `dbt_project.yml`.

Then I created this dummy macro within `macros/my_macros.sql`:
```sql
{% macro do_nothing() %}
{% endmacro %}
```

As it should, this complained about the version :
```shell
dbt run-operation do_nothing
```

Same as for you, this didn't work for me though:
```shell
dbt run-operation do_nothing --no-version-check
```

But this did work:
```shell
dbt --no-version-check run-operation do_nothing
```

**Comment by dbeatty10** [comment]
In this specific case, the solution might be as simple as adding [`@p.version_check`](https://github.com/dbt-labs/dbt-core/blob/30503697f2023c379338da1e58029582499ca877/core/dbt/cli/main.py#L125) to [here](https://github.com/dbt-labs/dbt-core/blob/30503697f2023c379338da1e58029582499ca877/core/dbt/cli/main.py#L441-L456).

In the general case, we'd like to have a way that it doesn't matter if an optional flag is supplied before or after a sub-command.

See https://github.com/dbt-labs/dbt-core/issues/6913 for more context (including a problem to solve).
