### ISSUE TITLE
[CT-2309] [Feature] Be more verbose when changing schema

### ISSUE THREAD

**Issue by alejandrofm** [dbt-labs/dbt-core#7178]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

On a schema change, for example, changing the size of a column, be more verbose about the reason of this change,

### Describe alternatives you've considered

 for example a message:
- recreating column table.column because source is varchar(20) and destination varchar(2)

### Who will this benefit?

This will help in several cases why is trying to change the data type and allow me to manually correct the source/dest if a change is not expected, also helps to debug errors like this (reported on dbt-redshift)

[0m13:15:56    cannot drop distkey column "user_id"

Thanks

**Comment by dbeatty10** [comment]
Thanks for reaching out @alejandrofm !

In dbt-redshift 1.4.0, I'm seeing something like the following in my `logs/dbt.log` file:
```
Changing col type from character varying(5) to character varying(10) in table ReferenceKeyMsg(database='qa', schema='dbt_dbeatty', identifier='model_1')
```

I believe the default message comes from [here](https://github.com/dbt-labs/dbt-core/blob/30503697f2023c379338da1e58029582499ca877/core/dbt/events/types.py#L583-L589) and will render something like this:
> Changing col type from {self.orig_type} to {self.new_type} in table {self.table}

Are you seeing a similar message in your logs before it says `cannot drop distkey column "user_id"`?

**Comment by alejandrofm** [comment]
I see this, maybe is something dbt-redshift is overloading? (DBT-Core 1.3.1, I checked and that code existed in the version I'm using)

Executing command: dbt run --profiles-dir .  --target prod --models my_process --vars '{}'
Standard output: [0m13:43:51  Running with dbt=1.3.1
[0m13:43:51  Partial parse save file not found. Starting full parse.
[0m13:43:54  Found 228 models, 4 tests, 0 snapshots, 0 analyses, 327 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
[0m13:43:54
[0m13:43:54  Concurrency: 1 threads (target='prod')
Traceback (most recent call last):
  File "/dbt/main.py", line 147, in <module>
[0m13:43:54
[0m13:43:54  1 of 1 START sql incremental model user_info.my_process ..................... [RUN]
[0m13:44:12  1 of 1 ERROR creating sql incremental model user_info.my_process ............ [[31mERROR[0m in 17.66s]
[0m13:44:12
[0m13:44:12  Finished running 1 incremental model in 0 hours 0 minutes and 18.01 seconds (18.01s).
[0m13:44:12
[0m13:44:12  [31mCompleted with 1 error and 0 warnings:[0m
[0m13:44:12
[0m13:44:12  [33mDatabase Error in model user_edid_lkp (models/user_info/my_process.sql)[0m
[0m13:44:12    cannot drop distkey column "user_id"
[0m13:44:12
[0m13:44:12  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1

**Comment by dbeatty10** [comment]
Do you see it in your `logs/dbt.log` file?

**Comment by alejandrofm** [comment]
Hi, didn't have time to look yet, the previous post was the output I get via Airflow, and we start our debugging with that information, I think being a transformation task on the **destination table** it could be shown there for very easy access. Ending good (no reason to go to the log) or bad is something that I shouldn't need to look at in the log, is, in my experience and on some databases more important than others, a very important piece of information.
Thanks!

**Comment by dbeatty10** [comment]
We'd consider verbose output like the following to be best in the logs rather than standard out:
```
Changing col type from character varying(5) to character varying(10)
```

Agreed that it's preferable to not need to examine the logs when possible. But we'd expect it to be necessary in some cases, and this looks like one of them to me.

I'm going to close this as "not planned" but we can re-visit and re-open if I'm missing something crucial.
