### ISSUE TITLE
[CT-2313] [Feature] Do not run scheduled github actions on forks 

### ISSUE THREAD

**Issue by flexponsive** [dbt-labs/dbt-core#7183]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Change the github workflows to run scheduled actions only in the `dbt-labs/dbt-core` repository.

Some workflows that are only really relevant for the main dbt-core repository (such as nightly release branch testing) are also run on forks. This causes users of forks to receive unnecessary error emails, and - given the large number of active forks - wastes a lot of computing resources:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/7556675/225760653-9538e707-7212-48bd-a478-eef64860a52b.png">

Run these workflows only in the `dbt-labs/dbt-core` repo:

- stale.yml
- nightly-release.yml
- release-branch-tests.yml

### Describe alternatives you've considered

Leaving as is: advantage of not making the github actions more complex, downsides see above

### Who will this benefit?

People with dbt-core forks

### Are you interested in contributing this feature?

Yes, very straightforward change

**Comment by dbeatty10** [comment]
We appreciate you getting in touch about this @flexponsive!

If you open a PR for this for dbt-core, we'd be happy to give it a look.

As a follow-up action, we'd probably want to open issues to make the same updates to dbt-bigquery, redshift, snowflake, and spark as well.

**Comment by emmyoop** [comment]
@flexponsive thanks for the suggestion.  In addition to adding some complexity to our workflows, adding this logic will prevent us from testing actions in forks, which we sometimes do.

By default when you fork a repository you have to manually turn on actions to run.  None of these workflows will run on a fork until a user chooses to enable them.

![Screen Shot 2023-03-20 at 11 26 57 AM](https://user-images.githubusercontent.com/7070049/226405388-ca44b9d2-f771-46f9-97be-dfa6b526868f.png)

If you have already done this (or you created the fork before this was an option) and it's not the behavior you desire, you can choose to turn them all off again in the repository settings of your fork:

Settings > Actions > General > Actions Permissions

![Screen Shot 2023-03-20 at 11 29 37 AM](https://user-images.githubusercontent.com/7070049/226406097-309d467d-517a-4755-8c42-efac8753d3a8.png)

If you would like to run some workflows but not others, you can leave them all enabled and just turn off workflows you would like to prevent from running.  To do this, select the workflow you want to remove from the `Actions` tab,  click the setting for the workflow and select `Disable workflow`.  This will prevent it from running.

![Screen Shot 2023-03-20 at 11 24 05 AM](https://user-images.githubusercontent.com/7070049/226404667-ef4d8804-3531-4554-8763-c5c77d1d6990.png)

With the above options available, I'm going to close this issue and the accompanying PR.
