### ISSUE TITLE
[CT-2317] `invocation_id` is cached between invocations in same Python process

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7197]
Originally reported by @jeremyyeo:

> With dbt >= 1.4, we seem to be maintaining invocation_id across steps in a single run.

Starting in v1.4, `invocation_id` is now stored on `EventManager`:
https://github.com/dbt-labs/dbt-core/blob/65fcbe7b79c66b15a833fd9033117cc3f8ad3b3b/core/dbt/events/eventmgr.py#L185

I think we should clear or reset `invocation_id` as part of the steps in `cleanup_event_logger`:

https://github.com/dbt-labs/dbt-core/blob/0ef9931d197c996ccd4e3caf641729176eceda99/core/dbt/events/functions.py#L269-L272

https://github.com/dbt-labs/dbt-core/blob/0ef9931d197c996ccd4e3caf641729176eceda99/core/dbt/events/functions.py#L160-L165

### Reproduction case

- Create an `on-run-start` hook with `{{ log(invocation_id, info = true) }}`
- Create a dbt Cloud job with multiple run steps
- See if the invocation IDs are the same or different

**Comment by jtcohen6** [comment]
We've confirmed that this is happening when multiple `dbt-core` commands are called from within the same Python process.

@peterallenwebb's recommendation:

> I do think calling `set_invocation_id()` between in-process dbt calls will solve the issue.

**Comment by peterallenwebb** [comment]
The approach I took was to call set_invocation_id() within `preflight`. The unit tests show this approach will work for programmatic invocations of dbt through the official API.
