### ISSUE TITLE
[CT-2320] [Regression] [v1.5] `dbt list` no longer suppresses info-level logging

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7206]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Using latest beta / `main` branch:
```
$ dbt ls
13:47:10  Running with dbt=1.5.0-b4
13:47:10  Unable to do partial parsing because of a version mismatch
13:47:11  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 310 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics, 1 group
test.subdir.another_model
test.my_model
test.my_seed
(env) 14:47:11 ~/d
```

### Expected/Previous Behavior

v1.4.x:
```
$ dbt ls
test.subdir.another_model
test.my_model
test.my_seed
```

This is nice because it allows users to easily pipe the results (and only the results) to `jq` / a file!

### Steps To Reproduce

1. Use latest `main`
2. Run `dbt ls`
3. See that `info`-level logging is included in `stdout`

### Environment

```markdown
- dbt (working version): v1.4
- dbt (regression version): v1.5 (beta)
```

### Additional Context

Previous logic in `1.4.latest` branch:
https://github.com/dbt-labs/dbt-core/blob/65fcbe7b79c66b15a833fd9033117cc3f8ad3b3b/core/dbt/task/list.py#L53-L65

This logic was removed in #6541.

FWIW it's possible to achieve the previous behavior, using v1.5, thanks to the new `--log-level` flag:
```
$ dbt --log-level warn ls
test.subdir.another_model
test.my_model
test.my_seed
```

### Acceptance criteria:
- Make `--log-level warn` the default behavior with `list`, without needing to pass the `--log-level` flag
- If a user _does_ explicitly pass/set the `--log-level` flag (or env var), it should take precedence over the default used for `list`

**Comment by iknox-fa** [comment]
Per BLG Mar 27 2023:  We're pointing this ticket as is, however the inconsistent use of a default log level feels a little dodgy.  @jtcohen6 should we have a larger conversation about default log levels and expected outputs at some point?

**Comment by jtcohen6** [comment]
@iknox-fa I agree it's a little dodgy :)

My primary motivation here is in restoring the previous default behavior, since this wasn't a change we'd intended. If that's too tricky, though, we can document the workarounds of `--log-level warn` or `--quiet` to achieve the same behavior as the previous default.

**Comment by jtcohen6** [comment]
After chatting about this with more folks internally, I've come around to:
- This was weird & inconsistent behavior before
- It's a defensible change, as part of our move toward a more consistent & solid application
- There are such easy & sensible mechanisms to achieve exactly the same behavior as before, it just requires passing an explicit flag instead of relying on the implicit/magical inconsistency

I'm going to close this issue and kick this out of scope for v1.5, and open a docs issue to make sure this is called out within the "Breaking Changes" section of the v1.5 migration guide.
