### ISSUE TITLE
[CT-2322] [Feature] Side-by-side diff when an enforced model contract fails

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#7209]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

See this Loom starting at 12:50 for context of this feature proposal:
https://www.loom.com/share/f436e5e336e4433695dc63d53ee72fcf?t=770

Two things:
- Update "Contracts are enabled for this model." to "This model has an enforced contract."
- Do a side-by-side diff rather than a stacked listing of column names

Where a preflight check fails for a model contract, could the output look more like this?

<img width="650" alt="image" src="https://user-images.githubusercontent.com/44704949/226979830-b6ce1f81-01e6-42cb-99f9-3a91017fa3c8.png">

Right now, the output looks like this:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/44704949/226978591-41c952a0-d682-434a-a3c3-ff329c97b2cd.png"> snip...
<img width="650" alt="image" src="https://user-images.githubusercontent.com/44704949/226978227-b5e5acef-9eb2-40dd-b871-41a413d97191.png">

### Describe alternatives you've considered

Sometimes the status quo is the way to go ...
... and sometimes it isn't 😉 

### Who will this benefit?

This will benefit folks that:
- are using enforced model contracts
- there is a mismatch in the contract leading to a preflight failure
- have a model with tons of columns (or even just a few!)

**Comment by kentkr** [comment]
Created a [PR](https://github.com/dbt-labs/dbt-core/pull/7223) for this with some questions!
