### ISSUE TITLE
[CT-2327] [Spike] Produce publication artifact and resolve cross-project refs

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#7227]
Write a new 'publication artifact' as a result of dbt invocations. This artifact should contain the set of _logical_ project state necessary for downstream projects to take dependencies (resolve refs) to public models in the producer project. 

Minimally, the publication artifact would contain: 
* common artifact metadata (version, custom env vars, etc) 
* project name
* quoting policy
* the relation components (database, schema, alias) for _each public_ model in the project
* project-level dependencies (to prevent project-level cycles) or model-level dependencies (to prevent model-level cycles across projects)

Let's prove out that this publication artifact can be used to resolve two-variant refs, where the first variant is a project (not package) name. If the two-variant ref _can_ be resolved with a package - prefer the package resolution to using the publication artifact.

**Comment by jtcohen6** [comment]
Paraphrasing from a conversation with @bossnunta:

> Will there be a way to tell from `dbt-core` when an error emerges from a bad "cross-project" reference, versus a bad intra-project reference?

When we're trying to resolve the `ref`, definitely!

If we can successfully resolve the `ref`, but then the user lacks permissions on the underlying database object... that would be trickier.

> From the UX perspective, it could be compelling (P1) to tell users that their error comes from the fact that your current project does not have access to the referenced model in the upstream project. Then we can link you to a documentation page that tells you to:
> - if it's the same adapter type -- go set up permissions (Snowflake share, BigQuery project IAM, Redshift cross-db query, etc)
> - if it's a different adapter type -- we don't support this (yet)
