### ISSUE TITLE
[CT-2335] [Follow-up] Inspect why the length of Agate table in results is wrong in tests

### ISSUE THREAD

**Issue by aranke** [dbt-labs/dbt-core#7234]
Follow-up from https://github.com/dbt-labs/dbt-core/pull/7208

See comment here: https://github.com/dbt-labs/dbt-core/pull/7208#issuecomment-1487660244

See examples of some removed flaky tests: https://github.com/dbt-labs/dbt-core/pull/7208/commits/e20af8475cf988fc4916ef271f8ba0234ba9a990

**Comment by iknox-fa** [comment]
Per BLG -- assigned to @aranke to check if that was fixed by other work.
