### ISSUE TITLE
[CT-2342] [Feature] Support secret `--vars`, by scrubbing their values from logs (like env vars)

### ISSUE THREAD

**Issue by nielspardon** [dbt-labs/dbt-core#7247]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When the `RequiredVarNotFoundError` exception is raised anywhere within the dbt execution it leaks secrets to stdout / logs since it does not mask `DBT_ENV_SECRET_*` vars in the exception message.

### Expected Behavior

`DBT_ENV_SECRET_*` vars should be masked in the exception message for `RequiredVarNotFoundError`

### Steps To Reproduce

1. Trigger a `RequiredVarNotFoundError` with `DBT_ENV_SECRET_*` vars
2. See plain text secrets in stdout

### Environment

```markdown
- OS: any
- Python: any
- dbt: 1.4.3+
```

**Comment by nielspardon** [comment]
I think our expectation of the behavior was different than documented. What we are actually looking for is secret scrubbing for vars (not only env_vars). The expectation was that if you provide a var with the `DBT_ENV_SECRET_` prefix that it would be scrubbed just like env vars would be scrubbed.

**Comment by nielspardon** [comment]
I've been playing around with this code snippet for `RequiredVarNotFoundError.get_message()`:
```
        return scrub_secrets(msg, self.var_secrets(dct))

    def var_secrets(self, dct: Dict) -> List[str]:
        return [v for k, v in dct.items() if k.startswith(SECRET_ENV_PREFIX) and v.strip()]
```

**Comment by jtcohen6** [comment]
@nielspardon Ah, ok! That's different from the current behavior, and from what we have documented here: https://docs.getdbt.com/reference/dbt-jinja-functions/env_var#secrets

I just tried this out locally, and found that if I set the same value as _both_ a "secret" env var, and pass it into `--vars`, it is appropriately scrubbed from the logs:
```
-- models/my_model.sql
select {{ var('another_var') }}
```
```
$ DBT_ENV_SECRET_ENV_MYSECRET=abc123 dbt run --vars 'nowasvar: abc123'
...
09:50:00  Compilation Error in model my_model (models/my_model.sql)
09:50:00    Required var 'another_var' not found in config:
09:50:00    Vars supplied to my_model = {
09:50:00        "nowasvar": "*****"
09:50:00    }
09:50:00
09:50:00  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
```

**Comment by nielspardon** [comment]
> @nielspardon Ah, ok! That's different from the current behavior, and from what we have documented here: https://docs.getdbt.com/reference/dbt-jinja-functions/env_var#secrets

Yes, I also just realized that. It would probably also explain why scrub_secrets was not implemented in the first place for this specific exception.

I think it would be beneficial to also be able to scrub secret vars and this is more of a feature request then.

**Comment by jtcohen6** [comment]
@nielspardon Could you say more about the intended use case? Since `vars` need to be specified either in `dbt_project.yml` (version control!), or in the `--vars` CLI parameter, it doesn't make as much sense to me as a place to store sensitive values.

**Comment by nielspardon** [comment]
This is still a open issue and should be fixed.
