### ISSUE TITLE
[CT-2349] [Feature] `dbt docs generate --exclude tag:xyz` should work while generating catalog

### ISSUE THREAD

**Issue by sfc-gh-kumaurya** [dbt-labs/dbt-core#7259]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This request is about the `dbt docs generate` to support the `--exclude` while generating the catalog file.
We can have databases in different environments and we do not want to run the docs generate for those models that are not accessible.
Right now we are getting errors something like this:
```
  Building catalog
  Encountered an error while generating catalog: Database Error
  002003 (02000): SQL compilation error:
  Database 'some_database_in_diff_env' does not exist or not authorized.
```
I have seen a few raised issues regarding this. ([issue#6014](https://github.com/dbt-labs/dbt-core/issues/6014)) 

### Describe alternatives you've considered

`dbt docs generate --target <env> --exclude tag:<tag_name>` command should not consider those models with tag "tag_name" while generating catalog file.

### Who will this benefit?

Everyone who is having databases in multiple environments and just want to generate the dbt docs for some specific models.

**Comment by jtcohen6** [comment]
@sfc-gh-kumaurya Thanks for opening! I believe this request is already captured in:
- https://github.com/dbt-labs/dbt-core/issues/6014

I'm going to close this issue as a duplicate. I welcome you to leave your upvotes/comments over there :)
