### ISSUE TITLE
[CT-2371] [Bug] incremental macro - need_swap rename needs to be from existing not target relation

### ISSUE THREAD

**Issue by tglunde** [dbt-labs/dbt-core#7267]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Using the default implementation of the incremental macro, when executing the functional test https://github.com/tglunde/dbt-core/blob/main/tests/adapter/dbt/tests/adapter/basic/test_base.py - the incremental execution from the view model to be changed back to an incremental model (line 94) fails because it tries to rename the target_relation instead of the existing_relation - where the latter is the view previously created.

### Expected Behavior

in case of need_swap = true - the existing_model needs to be renamed - not the target model, because according to the test_base the target_model is a table - where the existing model could be a view. Using the existing_model the adapter macro could change from alter table to alter view - as we do in case of exasol.

### Steps To Reproduce

1. Execute test suite with default postgres implementation
2. alter table swappable rename ... - gets generated instead of - alter view swappable rename ...

### Environment

```markdown
- OS: MacOS
- Python: 3.10.6
- dbt: 1.3.3
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Thanks for reporting this @tglunde !

I'm not quite following though -- could you help me understand?

What is the scenario that wouldn't work correctly for a user? Is it something like the following?

1. Create a model named `my_model` with a materialization of `view`
2. Do `dbt run --select my_model`
3. Change the materialization to `incremental`
4. Re-run `dbt run --select my_model`

**Comment by tglunde** [comment]
Hi @dbeatty10 ,
yes. This is the flow that is implemented in above mentioned [Test](https://github.com/tglunde/dbt-core/blob/main/tests/adapter/dbt/tests/adapter/basic/test_base.py) - see line 77. As this test fails with the dbt-core default implementation I did not describe too much.
Regards, Torsten

**Comment by dbeatty10** [comment]
@tglunde Could you help me reproduce getting this test to fail?

It's showing as passed in a recent CI check [here](https://github.com/dbt-labs/dbt-core/actions/runs/4796137786/jobs/8546004918#step:8:1609):

<img width="730" alt="image" src="https://user-images.githubusercontent.com/44704949/235490063-dbb6fe0b-645e-4835-ba29-1bd19c1941ef.png">

We can't really assess the code changes in https://github.com/dbt-labs/dbt-core/pull/7268 until we've reproduced the error, so we're seeking your help in doing that. Could you provide a set of steps I can follow that would reproduce the error you are seeing in dbt-postgres?

Something similar to the following would be ideal 🙏 

### Reprex

The following commands should work in `zsh` or `bash`, but you may need to do these steps differently depending on your environment.

[These](https://github.com/dbt-labs/dbt-core/issues/7267#issuecomment-1496625910) steps worked without error for both dbt-postgres and dbt-duckdb using dbt 1.5.0.

1. Create a model named my_model with a materialization of view
    ```shell
    cat <<EOF > models/my_model.sql 
    {{ config(materialized='view') }}

    select 1 as id
    EOF
    ```

2. Run it

    ```shell
    dbt run --select my_model
    ```

    <img width="800" alt="image" src="https://user-images.githubusercontent.com/44704949/235489754-b28a1e6a-bd3c-42e1-920a-871cc0b0317f.png">


3. Change the materialization to incremental
    ```shell
    cat <<EOF > models/my_model.sql 
    {{ config(materialized='incremental') }}

    select 1 as id
    EOF
    ```

4. Run it again

    ```shell
    dbt run --select my_model
    ```

    <img width="800" alt="image" src="https://user-images.githubusercontent.com/44704949/235489656-a87286a4-63ca-47b6-9f3e-36369b5402cf.png">


Note that the above commands worked for me.

**Comment by tglunde** [comment]
@dbeatty10 , sorry for late reply, but I am trying to reproduce this now, please give me some more time.

**Comment by tglunde** [comment]
closing because it was my fault - got confused with naming of variables.

**Comment by dbeatty10** [comment]
No prob @tglunde -- glad it is working for you now.
