### ISSUE TITLE
[CT-2372] [Feature] Any interest in a `dbt manifest` command?

### ISSUE THREAD

**Issue by jsnb-devoted** [dbt-labs/dbt-core#7269]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We use the manifest for CI and auxiliary tooling and we have been doing `dbt compile` to generate it. I'm now just realizing that we are wasting time doing a `compile` for just the manifest. It is handy that [the doc](https://docs.getdbt.com/reference/artifacts/manifest-json) has the list of commands that will generate the manifest but it feels a tad odd to be doing a `dbt ls` just so I can generate the manifest byproduct.

### Describe alternatives you've considered

`dbt ls` is totally fine -- I could just see us writing things in our code like:

```
# don't actually need to `ls` -- we just want the manifest
dbt ls
```

### Who will this benefit?

Just folks that use the manifest directly for metadata/tooling/CI etc

### Are you interested in contributing this feature?

Sure -- I think I could pattern match my way around it if there is a single function that generates the manifest.

**Comment by jsnb-devoted** [comment]
Just thinking about this now after I submitted this but I could also see the `dbt parse --generate-manifest` flag as a suitable ux.

**Comment by jtcohen6** [comment]
@jsnb-devoted Definitely interest - `dbt parse` will start doing this by default in v1.5!

(`dbt parse --write-manifest` in older versions)

See also:
- #6547

**Comment by jsnb-devoted** [comment]
get out of town! thanks @jtcohen6 -- and there it is in the help dialogue for `dbt parse`!
