### ISSUE TITLE
[CT-2376] [Bug] Create or replace view is hard-coded to revoke grants

### ISSUE THREAD

**Issue by mbdataminr** [dbt-labs/dbt-core#7280]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We are creating views in snowflake with `copy_grants=true` and appending additional roles to select views with `grants={'+select': ['role_name']}`. It will copy the current grants when it creates the view, and then immediately revoke all current grants, and applies the grants from the config, which is not desired.

Potential source of issue: [Create or replace view](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/models/view/create_or_replace_view.sql#L38) is hard coded to revoke grants. The tables/views are not hard-coded.

### Expected Behavior

With `copy_grants=true`, it is expected that it does **not** revoke grants, but only appends grants listed in the `grants` config.

### Steps To Reproduce

1. Create future grants on 

```
grant select on future views in schema DB_NAME.SCHEMA_NAME to role ROLE_1;
```

2. Create view

```
{{ config(copy_grants=true, grants={'+select': ['ROLE_2']}) }}

select * from {{ ref('some_table') }}
```

4. Run dbt. **Problem 1**: All grants (granted by future grants) will be revoked, except those defined in `grants`.

5. Grant view to another role outside of dbt

```
grant select on view DB_NAME.SCHEMA_NAME.VIEW_MODEL to role ROLE_3;
```

6. Run dbt. **Problem 2**: All grants are again revoked, except those defined in `grants` despite the `copy_grants` flag enabled.

### Environment

```markdown
- OS: Mac
- Python: 3.9.13
- dbt: 1.4.3
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
@mbdataminr Good point! From a quick glance, I think the lines you've identified:
https://github.com/dbt-labs/dbt-core/blob/ce5d02569f8a8d192f4086760ed1bf8ea39a1982/core/dbt/include/global_project/macros/materializations/models/view/create_or_replace_view.sql#L37-L38

Should really be:
```
  {% set should_revoke = should_revoke(exists_as_view, full_refresh_mode=True) %}
  {% do apply_grants(target_relation, grant_config, should_revoke=should_revoke) %}
```

If you override/reimplement the `create_or_replace_view()` macro in your own project, with that change, does it work the way you'd expect?

**Comment by mbdataminr** [comment]
Yep! That resolves the issue.

**Comment by dbeatty10** [comment]
I just opened this PR with the suggested fix: https://github.com/dbt-labs/dbt-core/pull/7285

**Comment by kevinjmccarthy** [comment]
I'm a bit confused by the solution and the behavior of `copy_grants`. I've tried adding it into my own project which uses the following versions:
```
dbt --version 
Core:
  - installed: 1.3.0
  - latest:    1.4.5 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0  - Update available!
  ```
  
  in [dbt-core](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/adapters/apply_grants.sql), `copy_grants` is True by default
```jinja
{% macro copy_grants() %}
    {{ return(adapter.dispatch('copy_grants', 'dbt')()) }}
{% endmacro %}

{% macro default__copy_grants() %}
    {{ return(True) }}
{% endmacro %}
```
in [dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/apply_grants.sql), `copy_grants` is False by default
```jinja
{% macro snowflake__copy_grants() %}
    {% set copy_grants = config.get('copy_grants', False) %}
    {{ return(copy_grants) }}
{% endmacro %}
```
So with this PR change, setting `copy_grants` to True ends up setting `should_revoke` to True and a revoke is issued. Is this the expected behavior? Why does setting copy_grants to True cause dbt to revoke existing grants after the model is created? It seems to happen after the `copy grants` DDL is ran.

**Comment by dbeatty10** [comment]
Thanks for sharing this situation @kevinjmccarthy ! 🙏 

I've opened up a separate issue on your behalf, and we'll get back to you early next week within that thread:
https://github.com/dbt-labs/dbt-snowflake/issues/567
