### ISSUE TITLE
[CT-2381] [Bug] `state:modified+` selection doesn't behave as expected for `dbt build` when tests are modified

### ISSUE THREAD

**Issue by b-luu** [dbt-labs/dbt-core#7289]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt build --select state:modified+` should behave like the other commands.

Specifically the following scenario doesn't yield the expected selection:
- modify a single/bunch of tests (but only tests)
- `PREVIOUS_TARGET=~/previous_target`
- `cp -r $DBT_PROJECT_DIR/target/* $PREVIOUS_TARGET`
- run `dbt list --select state:modified+ --state $PREVIOUS_TARGET`  => correctly lists only the changed tests (nothing downstream)
- run `dbt build --select state:modified+ --state $PREVIOUS_TARGET`  => runs the changed tests but also ALL downstream nodes!!
- while `dbt run --select state:modified+ --state $PREVIOUS_TARGET` does as expected: "Nothing to run"
- and `dbt test --select state:modified+ --state $PREVIOUS_TARGET` as well: only runs the changed tests.

### Expected Behavior

`dbt build --select state:modified+` should NOT run models downstream from modified tests (if only the tests have been modified, not the tests' model(s) )

### Steps To Reproduce

- modify a single/bunch of tests (but only tests)
- `PREVIOUS_TARGET=~/previous_target`
- `cp -r $DBT_PROJECT_DIR/target/* $PREVIOUS_TARGET`
- run `dbt list --select state:modified+ --state $PREVIOUS_TARGET`  => correctly lists only the changed tests (nothing downstream)
- run `dbt build --select state:modified+ --state $PREVIOUS_TARGET`  => runs the changed tests but also ALL downstream nodes!!
- while `dbt run --select state:modified+ --state $PREVIOUS_TARGET` does as expected: "Nothing to run"
- and `dbt test --select state:modified+ --state $PREVIOUS_TARGET` as well: only runs the changed tests.

### Environment

```markdown
- OS: PopOS 22.04
- Python: 3.7
- dbt: 1.2.5
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reporting this @b-luu !

Excellent write-up -- I was able to reproduce what you described:
- If we change test X anything downstream of it's parent node gets executed during `dbt build --select state:modified+ ...`


<details>
<summary>Full details of the reprex I used.
</summary>

`models/my_model_1.sql`

```
select 1 as id
```

`models/my_model_2.sql`

```
select * from {{ ref("my_model_1") }}
```

`models/my_model_3.sql`

```
select * from {{ ref("my_model_2") }}
```

`tests/my_test.sql`

```sql
select * from {{ ref("my_model_2") }}
where 0=1

```

Prime the pump:
```shell
dbt build
```

Alter the test and save the state:
```shell
echo "-- $(date +%T)" >> tests/singular/my_test.sql
PREVIOUS_TARGET=~/previous_target
mkdir -p $PREVIOUS_TARGET
cp -r target/* $PREVIOUS_TARGET
```

Try a few different commands:
```shell
dbt list --select state:modified+ --state $PREVIOUS_TARGET
dbt run --select state:modified+ --state $PREVIOUS_TARGET
dbt test --select state:modified+ --state $PREVIOUS_TARGET
dbt build --select state:modified+ --state $PREVIOUS_TARGET
```

</details>

**Comment by b-luu** [comment]
Intuitively, I'd look into the order of execution between [BuildTask.get_node_selector](https://github.com/dbt-labs/dbt-core/blob/fe62ab8ec5df334985505bf03c5dd10b465ef995/core/dbt/task/build.py#L45) and [BuildTask.compile_manifest](https://github.com/dbt-labs/dbt-core/blob/fe62ab8ec5df334985505bf03c5dd10b465ef995/core/dbt/task/build.py#L67).

I've gotta admit I've stopped looking/lost myself in the [CompilerProtocol](https://github.com/dbt-labs/dbt-core/blob/fe62ab8ec5df334985505bf03c5dd10b465ef995/core/dbt/adapters/protocol.py#L53) because it lacks the `add_test_edges: bool` kwarg that's passed in [`BuildTask`'s `.compile_manifest()` method](https://github.com/dbt-labs/dbt-core/blob/fe62ab8ec5df334985505bf03c5dd10b465ef995/core/dbt/task/build.py#L72)... :thinking: :shrug:

**Comment by jtcohen6** [comment]
In its current implementation, the `build` task does actually add an edge between a test on upstream model A, and model B depending on model A. Meaning that, even though model B doesn't directly depend on that test, there is an edge between them in the DAG, and so it's selected _for the `build` task only_.

I think it will be tricky to resolve this issue, given that's our current approach to achieving the `build` behavior. In practice, we don't see this issue come up so frequently. I agree it's confusing when it does happen, though, and "leaks" the underlying implementation.

**Comment by b-luu** [comment]
Thanks @jtcohen6 for the confirmation that it is indeed the expected behavior.

True the solution would be tricky, but here it's preventing me from using `dbt build` and forcing me to fallback to executing `run`, `test`, `snapshot`, and `seed` which isn't optimal because each type of task only runs after all the previous type have succeeded.

Anyway, as a quicker solution, do you think we could add a note on this caveat in [the documentation](https://docs.getdbt.com/reference/commands/build)? Or would it add more confusion than it would solve?

Actually, looking more deeply into it, I think the definitive solution isn't too complicated:
- because the edges added between parent models' tests and children models are only really useful for the resolution of execution order during the actual execution (i.e not at compile time)
- we could just add an attribute to these edges in the [add_test_edges method the Compiler](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/compilation.py#L477)
- and then filter out on this attribute in [dbt.graph.Graph.descendants()](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/graph/graph.py#L40)

I could give it a go if you want?

**Comment by jtcohen6** [comment]
@b-luu You're more than welcome to give a go! Conceptually, that approach makes sense to me. It would be worth a quick check to see if the added attribute and filtering step results in a meaningful slowdown at scale
