### ISSUE TITLE
[CT-2411] [Bug] Ephemeral materialization not working properly with recursive CTE

### ISSUE THREAD

**Issue by pcasteran** [dbt-labs/dbt-core#7350]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When performing the expansion of the referenced ephemeral models in the final query, the generated CTE are misplaced if the query starts with a `WITH RECURSIVE` statement.

### Expected Behavior

The CTE for the ephemeral models should be inserted after the `WITH RECURSIVE` statement.

### Steps To Reproduce

Let's say we have `model_1` using ephemeral materialization:
```sql
{{ config(materialized="ephemeral") }}

SELECT
  "Hello" AS greetings
```

And `model_2` using a `WITH RECURSIVE` statement and referencing `model_1`:
```sql
{{ config(materialized="table") }}

WITH RECURSIVE

  # Not actually recursive CTE.
  target AS (
    SELECT
      "world" AS target
  )

SELECT
  CONCAT(m1.greetings, ", ", t.target, " !!") AS col
FROM
  {{ ref("model_1") }} AS m1
CROSS JOIN
  target AS t

```
The generated SQL is not valid as the `model_1` CTE is inserted between the `WITH` and the `RECURSIVE` keywords:
```sql
   create or replace table `XXXX`.`XXXX`.`model_2`  as (

WITH  __dbt__cte__model_1 as (
SELECT
  "Hello" AS greetings
),RECURSIVE

  # Not actually recursive CTE.
  target AS (
    SELECT
      "world" AS target
  )

SELECT
  CONCAT(m1.greetings, ", ", t.target, " !!") AS col
FROM
  __dbt__cte__model_1 AS m1
CROSS JOIN
  target AS t
    );
```

After looking at the source code, it seems the issue comes from [this](https://github.com/dbt-labs/dbt-core/blob/70c26f5c74c340283a12f3a9270ec4c0f7135da5/core/dbt/compilation.py#L233) code that only looks for a `WITH` keyword for determining at which position to insert the CTE generated for the ephemeral models.

### Environment

```markdown
- OS: Linux Mint 20.3
- Python: 3.11.2
- dbt: 1.4.5
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thank you for reporting this @pcasteran !

Thanks also for your simple reprex; I was able to reproduce the behavior you reported (after updating any BigQuery-specific syntax).

Would you be interested in contributing a PR to fix this by any chance?

If so, [this](https://www.postgresql.org/docs/current/queries-with.html#:~:text=follow%20this%20way.-,7.8.2.%C2%A0Recursive%20Queries,-The%20optional%20RECURSIVE) could be a nice example to include in the testing.

**Comment by dbeatty10** [comment]
For anyone wondering the value of recursive CTE, here are a couple resources:
- https://duckdb.org/docs/sql/query_syntax/with.html
- https://motherduck.com/blog/solving-advent-code-duckdb-dbt/

**Comment by willbryant** [comment]
The following patch:

```patch
diff --git a/core/dbt/compilation.py b/core/dbt/compilation.py
index e5503af4..47c6f3fe 100644
--- a/core/dbt/compilation.py
+++ b/core/dbt/compilation.py
@@ -231,7 +231,17 @@ class Compiler:
         with_stmt = None
         for token in parsed.tokens:
             if token.is_keyword and token.normalized == "WITH":
-                with_stmt = token
+                _, next_token = parsed.token_next(
+                    parsed.token_index(token), skip_ws=True, skip_cm=True
+                )
+                if (
+                    next_token is not None
+                    and next_token.is_keyword
+                    and next_token.normalized == "RECURSIVE"
+                ):
+                    with_stmt = next_token
+                else:
+                    with_stmt = token
                 break
 
         if with_stmt is None:
```

Works perfectly, but I can't push it right now because mypy complains:

```
core/dbt/compilation.py:234: error: "Statement" has no attribute "token_next"  [attr-defined]
core/dbt/compilation.py:235: error: "Statement" has no attribute "token_index"  [attr-defined]
```

So I guess I need to figure out how to add those definitions now.

**Comment by willbryant** [comment]
NM, simplified it to just carry on the loop. Just need to add a test case now.

**Comment by willbryant** [comment]
OK, MR is ready to go now, I think.

**Comment by dixitatcoast** [comment]
so is this fixed , I see issue even in Redshift
