### ISSUE TITLE
[CT-2415] [Feature] Excel seed files

### ISSUE THREAD

**Issue by kentkr** [dbt-labs/dbt-core#7359]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

For better or for worse, business users love excel. Although it's not the safest option for consistent data quality, there are times where using an excel file is easier to use than a csv.

For instance I'm automating a workflow of internal users who currently use an excel file with three sheets. The file is created by hand and cannot be done programatically. Its a bit cumbersome to export the files as a csv. 

If dbt can read csvs then it most likely is using a package that can read .xslx files and convert them to csvs.

### Describe alternatives you've considered

1) Export sheets to csvs
2) Create a separate python script, outside of dbt, to convert xlsx to csv. 

### Who will this benefit?

Developers that cater to a user base familiar with excel.

### Are you interested in contributing this feature?

yes please

**Comment by dbeatty10** [comment]
Thanks for suggesting this idea @kentkr 💡 

> there are times where using an excel file is easier to use than a csv

This is so true! Spreadsheet apps can be very handy for handcrafting the data itself. I do data curation in spreadsheets weekly myself.

For seeding spreadsheet-curated data, I think either of your suggested alternatives will be the way to go on this one:

> 1. Export sheets to csvs
> 2. Create a separate python script, outside of dbt, to convert xlsx to csv.

### Trade-offs between alternatives
The former would be best for folks doing a one-time curation of data prior to seeding. The latter would be better when the seed data is being edited frequently.

### Rationale for not enabling XLSX seed files directly

One reason is that we believe the existing CSV capabilities provides a sufficient interface for doing this indirectly. e.g. users can convert a wide variety of file types to CSV with whatever tools they prefer.

Another reason it would be better outside of dbt-core is that there is a large surface area for converting Excel files, and we are not positioned to take that on. A final reason is that we'd prefer to keep dbt-core as tight and focused on essential activities as possible.

I'm going to close this as "not planned", but I'll be super interested to hear about any workflow or tooling you use to do these types of conversions (and I'm sure others will also) -- please let us know!
