### ISSUE TITLE
[CT-2419] Ensure process_refs is called for nodes referring to versioned models

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#7369]
If a node refs a versioned model but does not specify a version, the ref will use the latest version. But if a new latest version is added to the ref'd model and nothing changes in the model with the ref, the depends_on unique_id will not be updated.

Create a test case for this situation and update the code in core/dbt/parser/manifest.py "process_refs". We could check for refs to versioned models or just process all refs (not just models with an updated "created_at" timestamp. Processing refs is pretty fast, though it might be useful to compare the time it takes to do it both ways.

**Comment by gshank** [comment]
I think this may not actually be a real problem, since referencing nodes are scheduled for re-parsing.

**Comment by MichelleArk** [comment]
reproduction case: 

```yaml
---models/schema.yml
models:
  - name: my_model
    latest_version: 0
    versions:
      - v: 1
      - v: 0
```

```sql
---models/depends_on_version.sql
SELECT * FROM {{ ref('my_model') }}
```
1. initial run, without partial parsing - depends on v0 (latest) as expected
```sh
dbt --no-partial-parse --quiet ls --select depends_on_version --output json --output-keys unique_id depends_on
{"unique_id": "model.jaffle_shop.depends_on_version", "depends_on": {"macros": [], "nodes": ["model.jaffle_shop.my_model.v0"]}}
```

2. updating `latest_version` to `1` in schema.yml + subsequent runs _with_ partial parsing - does _not_ depend on v1 (latest) as expected
```sh
dbt --quiet ls --select depends_on_version --output json --output-keys unique_id depends_on
{"unique_id": "model.jaffle_shop.depends_on_version", "depends_on": {"macros": [], "nodes": ["model.jaffle_shop.my_model.v0"]}}
```
