### ISSUE TITLE
[CT-2422] [Bug] Using absolute seed path overwrites seed with compiled sql

### ISSUE THREAD

**Issue by kyle-kent** [dbt-labs/dbt-core#7373]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If `seed-path` in `dbt_project.yml` is an absolute path then the seeds get overwitten with the compiled sql code. Furthermore the typical compiled code is not written to `<project root>/target/run/<project root>/seed.csv`. My conclusion is that the paths of the actual seed file and the sql code are getting crossed.

### Expected Behavior

1) The seed file does not get overwritten
2) The compiled sql populates in `target/`
3) The compiled sql should populate with a `.sql` file ending (`seed.sql` instead of `seed.csv`)

### Steps To Reproduce

1) in `dbt_project.yml` set `seed-paths: [<path>]` to an absolute path like `/Users/<you>/<project root>/seeds`.
2) `dbt seed` a file
3) `dbt seed` that same file again

This will produce a compilation error. You can then see that the seed file was replaced by the compiled sql. 

### Relevant log output

```shell
17:52:50  Compilation Error in seed MSR_652_codes (/Users/kylekent/desktop/dash_1_transformations/seeds/MSR_652_codes.cs
v)
17:52:50    Row 5 has 4 values, but Table only has 1 columns.
17:52:50
17:52:50    > in macro materialization_seed_default (macros/materializations/seeds/seed.sql)
17:52:50    > called by macro materialization_seed_snowflake (macros/materializations/seed.sql)
17:52:50    > called by seed MSR_652_codes (/Users/kylekent/desktop/dash_1_transformations/seeds/MSR_652_codes.csv)

```
```


### Environment

```markdown
- OS: Mac Monterey M1, and 
- Python: 3.9.6
- dbt: dbt-core 1.4.5, dbt-snowflake 1.4.5
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Our seeds are being used as configuration files for runs; they are one-off runs executed manually. Therefore we are not tracking them in git and their folder must be referenced with an absolute path. Maybe this isn't the expected use case.

**Comment by jtcohen6** [comment]
Ah, this old bug:
- https://github.com/dbt-labs/dbt-core/issues/2669
- https://github.com/dbt-labs/dbt-core/issues/3683

@kyle-kent Thanks for opening! I agree this isn't the expected/intended behavior. We just don't see most people using absolute paths all that often, so it hasn't been a high-priority fix.

In the meantime, we should certainly document this as a known limitation

**Comment by BoltMaud** [comment]
Hi, just a message to say that I would be happy to use absolute paths for seed :)

**Comment by MingjiaNi** [comment]
+1 to using absolute path in dbt_project.yml. This would allow us to run the same dbt project with different global configs, and this is very helpful when upgrading DBT versions and doing testing/validation in a staging environment which running both dbt versions in parallel (namely migrating from before v1 to v1+)
