### ISSUE TITLE
[CT-2425] [Bug] Not able to set `quiet: true` in `profiles.yml`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#7378]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Configuring `quiet: true` in `profiles.yml` has no effect.

Searching within `logs/dbt.log` for a line that includes "running dbt with arguments" shows:
```
'quiet': 'False'
```

### Side notes

Configuring `log_cache_events: true` also shows in the logs as:
```
'log_cache_events': 'False'
```

Configuring `introspect: false` shows in the logs as:
```
'introspect': 'True'
```

Setting true/false booleans within `profiles.yml` for all the rest of the keys below **do** show up as expected within the logs (whether they are set to `true` or `false`):

### The rest look good
All the rest of the keys in `profiles.yml` shown below seem to show the expected value within the `logs/dbt.log` (for both `true` or `false`):

`profiles.yml`
```yaml
config:
  write_json: true
  partial_parse: true
  cache_selected_only: true
  version_check: true
  fail_fast: true
  debug: true
  warn_error: true
  use_colors: true
  use_experimental_parser: true
  no_print: true
  static_parser: true
  send_anonymous_usage_stats: true
```

### Expected Behavior

That configuring `quiet: true` in `profiles.yml` works just as well as `-q` or `--quiet` or the `DBT_QUIET` environment variable as described here:
https://docs.getdbt.com/reference/global-configs#suppress-non-error-logs-in-output

`profiles.yml`
```yaml
config:
  quiet: true
```

If this is expected to be invalid within `profiles.yml`, then remove that section of the documentation on docs.getdbt.com.
☝️ I'm guessing updating the documentation is the thing to do, because I couldn't get it to work for any version of dbt between 1.0 and 1.5. I didn't try anything earlier than 1.0.

### Steps To Reproduce

1. `dbt ls` - to establish a baseline expectation
1. Edit `config` portion of `profiles.yml` to include `quiet: true`
1. `dbt ls` - see that it does the same thing as before
1. `dbt --quiet ls` - see that it does something different

Also search `logs/dbt.log` for "quiet" after each command to see its value.

### Relevant log output

```shell
{
  "cache_selected_only": "True",
  "debug": "True",
  "fail_fast": "True",
  "indirect_selection": "eager",
  "introspect": "True",
  "log_cache_events": "False",
  "log_format": "default",
  "log_path": "/my_path/bug_quiet/logs",
  "no_print": "None",
  "partial_parse": "True",
  "printer_width": "80",
  "profiles_dir": "my_path/bug_quiet",
  "quiet": "False",
  "send_anonymous_usage_stats": "True",
  "static_parser": "True",
  "target_path": "None",
  "use_colors": "True",
  "use_experimental_parser": "True",
  "version_check": "True",
  "warn_error": "True",
  "warn_error_options": "WarnErrorOptions(include=[], exclude=[])",
  "write_json": "True"
}
```

### Environment

```markdown
- OS:
- Python:
- dbt: 1.5.0-rc1
```

**Comment by dbeatty10** [comment]
Could you take a look at this one @jtcohen6 ?

I suspect the "fix" will be just to remove this section of the docs:
https://docs.getdbt.com/reference/global-configs#suppress-non-error-logs-in-output

**Comment by jtcohen6** [comment]
@dbeatty10 I'd like to fix this inconsistency!
- https://github.com/dbt-labs/dbt-core/issues/7036

(I don't even think it would be too tricky to do. Ideally, though, we'd come up with a way to define these parameters _once_ rather than _twice_.)

We should definitely update the docs in the meantime, wherever there's a specific example that definitely doesn't work
