### ISSUE TITLE
[CT-2434] [Feature] Create SemanticManifest artifact with every run

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-core#7404]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

With the introduction of semantic objects and metrics planned for 1.6 (eagle-eyed among you keep an eye out for a discussion), we should plan on creating another artifact that is a subset of the larger manifest.

This artifact should contain:
- semantic_models
- metrics

These nodes should also be contained in the larger manifest but the separate artifact makes it easier for MetricFlow to consume the information that it needs without needing to parse the entire manifest.

### Describe alternatives you've considered

Not doing this

### Who will this benefit?

The teams working on the integration with MetricFlow and anyone who wants to use the Semantic Layer!

### Are you interested in contributing this feature?

Yes!

**Comment by QMalcolm** [comment]
### Blocked by:

- #7501
- #7503
- https://github.com/dbt-labs/dbt-semantic-interfaces/issues/17

**Comment by jtcohen6** [comment]
We will want to use the serialization strategy defined in `dbt-semantic-interfaces` to produce this artifact
