### ISSUE TITLE
[CT-2435] [Feature] Display model versions with `dbt show`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#7407]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When using [model versioning](https://docs.getdbt.com/docs/collaborate/govern/model-versions#how-to-create-a-new-version-of-a-model) + [`dbt show`](https://docs.getdbt.com/reference/commands/show), it is not clear which output goes with which version.

For versioned models, maybe use naming similar to `dbt list`? So something like this:
```
Previewing node 'dim_customers.v1':
```

If possible, it would also be nice to sort them in their version order (either from latest to earliest or vice versa).
 
### Example
```shell
$ dbt list
my_dbt_project.dim_customers.v1
my_dbt_project.dim_customers.v2
```

```shell
$ dbt show -s dim_customers
22:51:55  Running with dbt=1.5.0-rc1

22:51:56  Previewing node 'dim_customers':
| customer_id | country_name | model_version |
| ----------- | ------------ | ------------- |
|           1 | Nauru        |             1 |

22:51:56  Previewing node 'dim_customers':
| customer_id | country_name | model_version |
| ----------- | ------------ | ------------- |
|           1 | Nauru        |             3 |

22:51:56  Previewing node 'dim_customers':
| customer_id | country_name | model_version |
| ----------- | ------------ | ------------- |
|           1 | Nauru        |             2 |
```

### Describe alternatives you've considered

Rather than all the versions of `dim_customers`, it might be more expected to specify the desired version in the selection syntax like this:

```shell
$ dbt show -s dim_customers.v2
23:04:45  Running with dbt=1.5.0-rc1

23:04:46  Previewing node 'dim_customers':
| customer_id | country_name | model_version |
| ----------- | ------------ | ------------- |
|           1 | Nauru        |             2 |
```

**Comment by jtcohen6** [comment]
Thanks @dbeatty10! I think it's a matter of updating this line, to include the `node.version` if available:

https://github.com/dbt-labs/dbt-core/blob/ada8860e48b32ac712d92e8b0977b2c3c9749981/core/dbt/task/show.py#L80

As an implementation detail, it would make sense to me to define a new node method, something like `pretty_name`, which would return `node.name` by default and `{node.name}.v{node.version}` if a version is defined.
