### ISSUE TITLE
[CT-2439] [Bug] dbt source freshness not using target-path specified in dbt_project.yml

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#7411]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt source freshness` will write to default running dir instead of being able to specify a target dir.

### Expected Behavior

When a target-path is specified in `dbt_project.yml`, dbt-core would write sources.json to that path.

### Steps To Reproduce

Specify a `target-path` in `dbt_project.yml` that's different from default path. Run source freshness. You will see `sources.json` being written to the target dir in the current path not the path specified in `dbt_project.yml`

**Comment by jtcohen6** [comment]
Should `--target-path` graduate to being a top-level / "global" config? i.e.
```
$ dbt --target-path source freshness
```

**Comment by ChenyuLInx** [comment]
@jtcohen6 Good question, I didn't touch `--target-path` in my change, all I did was to make `sources.json` write to `target-path` specified in `dbt_project.yml`.
`source freshness` doesn't support `--target-path` CLI arg since 1.4 at least. There's currently a community [issue](https://github.com/dbt-labs/dbt-core/issues/7418) and [PR](https://github.com/dbt-labs/dbt-core/pull/7419) regarding it. It is merged to main but TBD on whether this should be backported.
