### ISSUE TITLE
[CT-2456] [Feature] dbt deps tarball - certificate option

### ISSUE THREAD

**Issue by owl2** [dbt-labs/dbt-core#7427]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Hello,

I realized that using `dbt deps` to load an [internally hosted tarball URL](https://docs.getdbt.com/docs/build/packages#internally-hosted-tarball-url) (self hosted artifactory) generate a certification error. 
We have no possibility to pass a certifcate in parameter. I think it can be verified [here](https://github.com/dbt-labs/dbt-core/blob/1722079a43d1e3a94ffb73e66c8712ee0837e9fa/core/dbt/clients/system.py#L469). 

Can we imagine to pass a certificate parameter first in this download function used by the tarball option and then in the packages.yml file ? 

Thank you for your support.

### Who will this benefit?

Every company that use a certificate to have access to their artifactory.

### Are you interested in contributing this feature?

Yes

**Comment by dbeatty10** [comment]
Thanks for reaching out @owl2 !

Can you share the error you are seeing?

**Comment by owl2** [comment]
Yes of course.

I have a packages.yml that contains the following informations : 

``` yml
packages:
  - tarball: https://xxxx/artifactory/local-dbt/dbt-expectations/tar.gz/0.8.5
    name: 'dbt_expectations'
```
I put the release in artifactoy.

And when I'm running `dbt deps` command I have this error : 

![image](https://user-images.githubusercontent.com/16677525/233928433-fcdfb3cc-27ff-4939-9bef-c4bf4164981f.png)

I also tried to attach the certificate to pip config but I still have this error.

**Comment by owl2** [comment]
Hello @dbeatty10,

I tried to resolve this issue by setting up the env variable REQUESTS_CA_BUNDLE (yith Ubuntu), and it worked !

Thank you very much.

**Comment by dbeatty10** [comment]
🎉 That's great news @owl2 ! Thanks for sharing this roadblock you were running into, and I'm so glad it all works now.

**Comment by dbeatty10** [comment]
To make this more discoverable by Google searches, here's a lightly-edited text version of the error message from the screenshot [here](https://github.com/dbt-labs/dbt-core/issues/7427#issuecomment-1519538302):

```
$ dbt deps

Running with dbt=1.4.5
Installing dbt_expectations
Encountered an error:
External connection exception occurred: HTTPSConnectionPool(host='artifactory.*****', port=443): Max retries exceeded with url: /artifactory/local-dbt/dbt-expectations/tar.gz/0.8.5 (Caused by SSLError (SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))
```
