### ISSUE TITLE
[CT-2465] [Bug] `meta` field inheritance in sources works exactly the wrong way

### ISSUE THREAD

**Issue by Maayan-s** [dbt-labs/dbt-core#7440]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hi team 😁

According to the docs [here](https://docs.getdbt.com/reference/configs-and-properties#config-inheritance):
_"meta dictionaries are merged (a more specific key-value pair replaces a less specific value with the same key)"_

This indeed happens for models and tests. 
However in sources **the less specific value is replaces the more specific one**.

I played with configuring `meta` in different levels, and the priorities are:
1. dbt_project.yml meta
2. source level meta
3. table level meta

### Expected Behavior

Priorities should be:
3. dbt_project.yml meta
2. source level meta
1. table level meta
(exactly the other way around from current behavior)

### Steps To Reproduce

I'm using dbt latest release (1.4.6). 

In the `dbt_project.yml` I configured:
```
sources:
  +meta:
    debug: "project_level"
```

And for a specific source I configured:
```
sources:
  - name: source_name
    schema: source_schema
    meta:
      debug: "source_level"
    tables:
      - name: table_name
        meta:
          debug: "table_level"
```

When I extract the meta field from the graph, I get the `project_level` value under debug. 
When I remove the config from `dbt_project.yml` and extract the meta field from the graph, I get the `source_level` value under debug.
When I remove the config from the source and extract the meta field from the graph, I get the `table_level` value under debug.

### Environment

```markdown
- OS: macOS 13.3.1
- Python: 3.9.15
- dbt: 1.4.6
```

**Comment by dbeatty10** [comment]
Hi @Maayan-s 😁

### Something to try

What do the priorities look like if you try the following instead?

In the `dbt_project.yml`:

```yaml
sources:

  # for sources, it appears okay to put config up here, but I don't think it's okay for models
  # +meta:
  #   debug: "top_level_config"

  your_dbt_project_name:
    +meta:
      debug: "project_level_config"
```

And for a specific source:

```yaml
sources:
  - name: source_name
    schema: source_schema
    config:
      meta:
        debug: "source_level_config"
    tables:
      - name: table_name
        config:
          meta:
            debug: "table_level_config"
```

In `analyses/my_analysis.sql` (for examining all the details of each node):

```sql
{% set sources = [] -%}
{% for node in graph.sources.values() -%}
  {{ tojson(node) }}
{%- endfor %}
```

Compile and pretty-print the JSON for the source nodes:
```shell
dbt compile
jq . target/compiled/your_dbt_project_name/analyses/my_analysis.sql > source_nodes.json
```

### Maximum detail

To really see in detail how everything is affecting the `node` dictionary, I did the following:

In the `dbt_project.yml`:

```yaml
sources:
  +meta:
    debug: "top_level"
  config:
    +meta:
      debug: "top_level_config"
  my_dbt_project:
    +meta:
      debug: "project_level"
    config:
      +meta:
        debug: "project_level_config"
```

And for a specific source:

```yaml
sources:
  - name: source_name
    schema: source_schema

    meta:
      debug: "source_level"
    config:
      meta:
        debug: "source_level_config"

    tables:
      - name: table_name
        meta:
          debug: "table_level"
        config:
          meta:
            debug: "table_level_config"
```

Here's a subset of the JSON key/values:
```json
{
  "database": "postgres",
  "schema": "dbt_dbeatty",
  "name": "sample_model",
  "resource_type": "source",
  "package_name": "my_dbt_project",
  "path": "models/_sources.yml",
  "original_file_path": "models/_sources.yml",
  "unique_id": "source.my_dbt_project.dbt_dbeatty.sample_model",
  "fqn": [
    "my_dbt_project",
    "dbt_dbeatty",
    "sample_model"
  ],
  "source_name": "dbt_dbeatty",
  "identifier": "sample_model",
  "meta": {
    "debug": "table_level"
  },
  "source_meta": {
    "debug": "source_level"
  },
  "config": {
    "enabled": true,
    "meta": {
      "debug": "table_level_config"
    }
  },
  "unrendered_config": {
    "meta": {
      "debug": "table_level_config"
    }
  },
  "relation_name": "\"postgres\".\"dbt_dbeatty\".\"sample_model\"",
}
```

This looks like the priorities you expecting, but let me know either way!

**Comment by Maayan-s** [comment]
Hi @dbeatty10,
So I did what you suggested and learned that:

1. Config is not valid in the `dbt_project.yml`:
![image](https://user-images.githubusercontent.com/22072028/234304130-c3d4c9c9-16f4-4042-9a3a-699bf2b83c24.png)

2. When I placed `meta` under `config` I did get the priorities I expect:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/22072028/234306785-e2762197-5f5b-4d6f-8df7-adfba0de29da.png">

Whereas without `config` I get this:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/22072028/234307180-e20f66c1-90f8-4216-babe-7300a52b904b.png">

The thing is this is really inconsistent (and undocumented). 
On models - the priorities work with just `meta`.
On sources - put `meta` under config. 
Unless it's sources in dbt_project.yml, then don't use `config`.

**Comment by dbeatty10** [comment]
> The thing is this is really inconsistent (and undocumented).

😅 This feedback is fair, @Maayan-s

### Inconsistencies
I don't know for certain, but some or all of the inconsistency for sources might be covered by https://github.com/dbt-labs/dbt-core/issues/3662

### Documentation

At the very least, would some clear documentation within the docs for [`meta`](https://docs.getdbt.com/reference/resource-configs/meta) stating the following be helpful?

> In order for [`meta` dictionaries to merge](https://docs.getdbt.com/reference/configs-and-properties#config-inheritance) with a more specific key-value pair replacing a less specific value with the same key:
> - For all* resource types in `_properties.yml` files:
>     - put `meta` under `config`.
> - Within `dbt_project.yml` don't use `config`:
>     - use a top-level `meta` key instead.
> 
> \* For `models` - `meta` also works as a top-level key.
> 

Of course we'd also want to update all the examples within the [`meta`](https://docs.getdbt.com/reference/resource-configs/meta) docs to nest the `meta` key under the `config` key in the all right places.

**Comment by jtcohen6** [comment]
I agree this is quite inconsistent & confusing. The current complexity is there for two reasons:
- Backward compatibility when we switched `meta` from being a "property" to a "configuration," back in v0.21
- We only made that change for a subset of resource types, and `sources` were _not_ one of them

https://docs.getdbt.com/reference/resource-configs/meta#definition

> Depending on the resource you're configuring, meta may be available within the config property, or as a top-level key. (For backwards compatibility, meta is always supported as a top-level key, though without the capabilities of config inheritance.)

I would like to develop a general-purpose answer to the inconsistencies that exist today between "configurations" (which can be inherited & overridden) and "properties" (which cannot):
- #7157

**Comment by Maayan-s** [comment]
Thanks @jtcohen6 and @dbeatty10!

Changing the docs is for sure the immediate solution, and I understand the planned solution and think it's solid and will solve a lot of confusion!

**Comment by dbeatty10** [comment]
@alison985 I think this is a just a misunderstanding due to me using the phrase "top-level" too loosely in combination with `schema.yml` and `dbt_project.yml` behaving differently from each other 😅

Inside of `schema.yml` files, the `meta` configuration must be repeated underneath each model `name`, as you saw.

`dbt_project.yml` is the mechanism to use if you want to [configure a set of models](https://docs.getdbt.com/reference/model-configs#configuring-directories-of-models-in-dbt_projectyml). It requires organizing sets of models into a hierarchy of directories.

### Example

Suppose you put all your Richard/Alison models into a folder named `ra`. Then your `dbt_project.yml` would look something like this:

```yaml
name: "my_project"
profile: "my_profile"

models:
  my_project:

    +meta:
      owner: "@Default_Owner_Across_This_Project"
      dbt_builder: "@Default_dbt_Builder_Across_This_Project"

    # relative path: models/ra
    ra:
      +meta:
        owner: "@Richard"
        dbt_builder: "@Alison"
```

#### Explanation

In this example, all models within `models/ra` (and all its subdirectories) will have the @Richard / @Alison meta config (unless overridden by a `schema.yml` file or `{{ config(...) }}` within the model itself).

Otherwise, they will have the `@Default...` meta config that is directly under `my_project:`.
