### ISSUE TITLE
[CT-2483] Use depends_on.add_node instead of depends_on.nodes.append

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#7453]
In some circumstances we end up with multiple duplicated unique_ids in depends_on.nodes. Switch to using "add_node" instead of append so that duplicates are avoided. Fix the artifacts tests...

The place that needs to be fixed is in core/dbt/parser/manifest.py at the end of "_process_refs_for_node"

**Comment by jtcohen6** [comment]
Ooh! Might this also fix https://github.com/dbt-labs/dbt-core/issues/5877?
