### ISSUE TITLE
[CT-2485] [Bug] RunOperationResultsArtifact does not contained expected data with programmatic invocation 

### ISSUE THREAD

**Issue by ttusing** [dbt-labs/dbt-core#7454]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am attempting to get results from programmatic invocations of DBT operations.

As a toy, I am trying to get the output from dbt-codegen's generate_model_yaml macro (https://github.com/dbt-labs/dbt-codegen/blob/e24e5dc5daca47ba350415a59790d6b741be246b/macros/generate_model_yaml.sql#L50). I'm imagining a script that writes these schema YML files automatically.

The macro prints to the log in addition to the return command. I would expect that these would be included in the dbtRunnerResult class, specifically in the `results` item of  RunOperationResultsArtifact.

My script:
```
from dbt.cli.main import dbtRunner, dbtRunnerResult

# initialize
dbt = dbtRunner()

# create CLI args as a list of strings
cli_args = [
    "run-operation",
    "generate_model_yaml",
    "--args",
    """{"model_names": ["my_model"]}""",
]

res: dbtRunnerResult = dbt.invoke(cli_args)

print(res)
```

### Expected Behavior

Output from `return` function from codegen macro is returned in the dbtRunnerResult class.

### Steps To Reproduce

Run the script I posted in Python for a model with `dbt-codegen` installed.

### Relevant log output

```shell
DBT logs expected output, returned object is this (note results:[])

dbtRunnerResult(success=True, exception=None, result=RunOperationResultsArtifact(metadata=RunOperationResultMetadata(dbt_schema_version='https://schemas.getdbt.com/dbt/run-operation-result/v1.json', dbt_version='1.5.0rc2', generated_at=datetime.datetime(2023, 4, 24, 21, 22, 36, 550559), invocation_id='e239cd3c-4fdc-40a9-b39b-7707539ce014', env={}), results=[], elapsed_time=1.699451, success=True))
```

### Environment

```markdown
- OS: mac OS13.2.1 (22D68)
- Python: 3.9.11
- dbt: 1.5.0-rc2

- dbt-codegen: 0.9.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by ttusing** [comment]
Opened this ticket in response to Slack thread https://getdbt.slack.com/archives/C2JRRQDTL/p1682370679158779?thread_ts=1682368271.410369&cid=C2JRRQDTL

**Comment by jtcohen6** [comment]
@ttusing Very cool! Thanks for taking the v1.5 RC for a spin :)

The `run-operation` command doesn't include the value returned by the called macro to its result. **It probably should!** We get access to it [here](https://github.com/dbt-labs/dbt-core/blob/d2f963e20ea945355db57ff3d34a318429a8bf1e/core/dbt/task/run_operation.py#L37-L41). We just don't then include it in the `RunOperationResult` / `RunOperationResultsArtifact`.

The `codegen.generate_model_yaml` macro both [logs _and_ returns its contents]((https://github.com/dbt-labs/dbt-codegen/blob/main/macros/generate_model_yaml.sql#L49-L50)), so it's doing everything that it needs to.

---

In the meantime... what if we tried this with "interactive compile" instead?

```python
from dbt.cli.main import dbtRunner, dbtRunnerResult

# initialize
dbt = dbtRunner()

# create CLI args as a list of strings
cli_args = [
    "compile",
    "--inline",
    "{{ codegen.generate_model_yaml(model_names = ['my_model']) }}",
]

res: dbtRunnerResult = dbt.invoke(cli_args)

print(res.result.results[0].node.compiled_code)
```
```python
>>> print(res.result.results[0].node.compiled_code)
version: 2

models:
  - name: my_model
    description: ""
    columns:
      - name: id
        description: ""
```

I'll admit, `res.result.results` feels a little wonky to look at. This is a super-generic runner; here are the types involved:
```python
print(type(res))                        # dbtRunnerResult
print(type(res.result))                 # RunExecutionResult
print(type(res.result.results))         # List[RunResult]
print(type(res.result.results[0].node)) # SqlNode
```

**Comment by jtcohen6** [comment]
I'm going to change this from a bug to an enhancement. We can discuss & estimate this piece in particular:

> The `run-operation` command doesn't include the value returned by the called macro to its result. **It probably should!** We get access to it [here](https://github.com/dbt-labs/dbt-core/blob/d2f963e20ea945355db57ff3d34a318429a8bf1e/core/dbt/task/run_operation.py#L37-L41). We just don't then include it in the `RunOperationResult` / `RunOperationResultsArtifact`.

Since this use case is quite new (with programmatic invocations in v1.5), and has a valid workaround (maybe even better?), I don't think this is something we'd prioritize highly.

**Comment by iknox-fa** [comment]
per BLG 5/23:
@jtcohen6 We;d like to solve this for the general case-- specifically we'd like to have some sort of consistency in our task `RunResults` and we'd like to contract and document it for our users.  We can either expand this ticket to do that or start something new but we're going to need your input on that.
