### ISSUE TITLE
[CT-2486] Create files in Target directory as read only

### ISSUE THREAD

**Issue by gilcrest** [dbt-labs/dbt-core#7457]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

A number of times, while debugging, I've accidentally made changes to models in the target directory (`target/compiled` or `target/run`) instead of the models directory. I think it would be helpful if files generated in the various target subdirectories were marked as `read-only`.

### Describe alternatives you've considered

None.

### Who will this benefit?

I think this will benefit other users who will invariably make the same mistake as me. I don't know of a use case where these files need to be writable, but I'm a relatively new user, so there may be.

### Are you interested in contributing this feature?

Happy to help! I'm a Go developer, but I'll try and roll some python if need be.

### Anything else?

Thanks!

**Comment by dbeatty10** [comment]
Thanks for reaching out @gilcrest !

You're certainly not the first person this has happened to -- I think this has probably happened to all of us at some point 😅 

Your suggestion to make this read-only is intriguing 💡

We would like to compare it to other ways that folks have tried to prevent accidentally making changes to models in the target directory. But I don't know all those, so will need to seek additional insights from others.

#### Inviting others to join the discussion:
How do you avoid editing the files in the target directory?

**Comment by b-per** [comment]
In VSCode I used something similar to what is described [here](https://discourse.getdbt.com/t/setting-up-vscode-to-use-with-the-dbt-cli/3291#vscode-dbt-12).

That way, my SQL files under `target` don't get any SQL syntax color which tells me that they are not my dbt models. 
It could also be possible to say that the ones under `target` are `sql` files instead of `jinja-sql`, which would still give SQL syntax highlighting but would show a different icon for the target files.
