### ISSUE TITLE
[CT-2487] [ADAP-490] {{ This }} function doesn't show the right schema

### ISSUE THREAD

**Issue by ManuelKuehn** [dbt-labs/dbt-core#7458]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The {{this}} function doesn't work as exspected:

{{this}} ={{this.database}}.{{this.schema}}.{{this.table}}

I have created a post hook in a sql model.
```
{{config
	(
		post_hook= create_externall() 
	)
}}
```
The Makro:
I am not able to use the 
`select * from {{this}}` 
because it schows:
**DWH_DEV.DWH.EXT_MODEL**
i would have exspected another schema:
**DWH_DEV.DWH_EXTERNAL.EXT_MODEL**
That is the actual Version with the work around:
`select * from  {{this.database}}.DWH_EXTERNAL.{{this.table}}`
```
{%- macro create_externall() -%}
    {{- adapter.dispatch('create_externall')() -}}
{%- endmacro -%}


{%- macro default__create_externall() -%}
{#### Macro Variables ####}


{#### Macro Start ####}
insert into DWH_OPS.LOAD_TABLES_MONITORING 	(TABLE_NAMES,LOAD_STATUS,DAY_DIFF,HOUR_DIFF,MINUTE_DIFF)
with DATA_MONITORING as (
select * from  {{this.database}}.DWH_EXTERNAL.{{this.table}}

)
,
TIME_DIFF as(  
select      '{{this.table}}' AS FILENAME,
            MAX(FILE_TS) as MAX_TIME, 
            TIMEDIFF(DAY, Current_timestamp(),MAX_TIME) AS DAY_DIFF,  
            TIMEDIFF(HOUR, Current_timestamp(),MAX_TIME) AS HOUR_DIFF,
            TIMEDIFF(MINUTE, Current_timestamp(),MAX_TIME) AS MINUTE_DIFF     
from DATA_MONITORING 
Group by 1
)
,
Result as(
select *,
CASE WHEN HOUR_DIFF > -3 THEN 'OK'
ELSE 'ERROR'
END AS LOAD_STATUS
from TIME_DIFF s
)
select FILENAME, LOAD_STATUS, DAY_DIFF, HOUR_DIFF, MINUTE_DIFF
from Result
{%- endmacro -%}
{#### Macro End ####}
```

### Expected Behavior

The Makro:
I am not able to use the 
`select * from {{this}}` 
because it schows:
**DWH_DEV.DWH.EXT_MODEL**
i would have exspected another schema:
**DWH_DEV.DWH_EXTERNAL.EXT_MODEL**

### Steps To Reproduce

1. Dev Enviorment
2. Creeate Post_hook
3. Create Makro and use the {{this}} function

### Environment

```markdown
- OS: -
- Python:3.9.12
- dbt-core: 1.0.8
- dbt-snowflake: 1.0.0
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @ManuelKuehn !

When I tried this for myself, it appears to be working the way I would expect.

I wonder if you aren't [setting the schema](https://docs.getdbt.com/docs/build/custom-schemas#how-do-i-use-custom-schemas) correctly?

Could you try out this simplified example?

`models/my_model.sql`
```sql
{{ config(
    schema="dwh_external",
    post_hook=my_macro()
)}}

select 0 as id
```

`macros/my_macro.sql`
```sql

{%- macro my_macro() -%}
    {{- adapter.dispatch('my_macro')() -}}
{%- endmacro -%}

{%- macro default__my_macro() -%}
    {{ log("this: " ~ this, True) }}
    {{ log("this.database: " ~ this.database, True) }}
    {{ log("this.schema: " ~ this.schema, True) }}
    {{ log("this.table: " ~ this.table, True) }}
{%- endmacro -%}
```

When I do `dbt run`, I see output like this (which is the development schema that I would expect):
```
18:19:10  this: "postgres"."dbt_dbeatty_dwh_external"."sample_model"
18:19:10  this.database: postgres
18:19:10  this.schema: dbt_dbeatty_dwh_external
18:19:10  this.table: sample_model
```
