### ISSUE TITLE
[CT-2489] [Bug] [python models] dbt.config doesn't work in conditional statement

### ISSUE THREAD

**Issue by kalanyuz** [dbt-labs/dbt-core#7463]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I just found out that if else statement doesn’t work with dbt python models when it comes to dbt.config.materilized
```
if dbt.config.get("target_name") == "local_dev":
        dbt.config(materialized='table')
        print('dev')
else:
        dbt.config(
            materialized="incremental",
            submission_method="serverless"
        )
```

I’d get a print “dev”
but still tries to materialized in incremental, but won’t submit in serverless, which is absolutely strange.

Then, if I remove the bottom dbt.config then I’d get print “dev” and everything works normally.

Putting the condition as a ternary operator results in:
```
  In dbt python model, `dbt.ref`, `dbt.source`, `dbt.config`, `dbt.config.get` function args only support Python literal structures
  ```
  
  Which I assume that this particular statement isn’t processed as python but maybe jinja / something else.

### Expected Behavior

I can have multiple materialization configurations based on conditional statements.

### Steps To Reproduce

```
if dbt.config.get("target_name") == "local_dev":
        dbt.config(materialized='table')
        print('dev')
else:
        dbt.config(
            materialized="incremental",
            submission_method="serverless"
        )
```

It would try to materialized in incremental mode

### Environment

```markdown
- OS: macOS Ventura
- Python: 3.9
- dbt: 1.4.6
```

### Which database adapter are you using with dbt?

bigquery

**Comment by jtcohen6** [comment]
@kalanyuz Thanks for opening! You have the right idea here:

> this particular statement isn’t processed as python but maybe jinja / something else.

We use Python's AST to statically analyze the inputs ([source code](https://github.com/dbt-labs/dbt-core/blob/d2f963e20ea945355db57ff3d34a318429a8bf1e/core/dbt/parser/models.py#L183-L222) if you're interested). We're limited in what we've implemented support for — really just literals.

You could accomplish this conditional configuration with Jinja-in-yaml instead:
```yml
models:
  - name: your_python_model
    config:
      materialized: "{{ 'table' if target.name == 'local_dev' else 'incremental' }}"
      submission_method: "{{ 'serverless' if target.name != 'local_dev' else ... }}"
```

**Comment by jtcohen6** [comment]
@kalanyuz Just saw you opened an issue for those over in https://github.com/dbt-labs/dbt-bigquery/issues/680 - nice! That's less to do with parsing the configurations, and more to do with how we're submitting the Dataproc job to create the table, and needing to pass in those additional configurations.

**Comment by jtcohen6** [comment]
Going to close this in favor of an update to documentation for now, making clear that `dbt.config` supports _only_ literal inputs. Any more-complex expression (including ternary statements) are not supported.
