### ISSUE TITLE
[CT-2490] [Feature] Missing docblocks should raise a warning not break compilation

### ISSUE THREAD

**Issue by ian-lewis-d** [dbt-labs/dbt-core#7464]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

**As a** Data Engineer
**I am regularly building** new sets of schemas which include `{{ doc() }}` blocks inside the source or model yaml files
**As part of the process** I wish to run `dbt docs generate` periodically.

At present this process is difficult, and badly affects my workflow, because missing docblocks cause the compile phase to abort fatally with `dbt.exceptions.CompilationException`. 

There is currently no option (that I can find) to choose a compiler`WARNING` instead of abort.

In summary, I want to be able to run `dbt docs generate` and be warned about missing docblocks rather than have to leave them out. 

A simple config of `--compile-with-warnings true` would make it possible to see all compilation errors instead of encountering a fatal exception on every run.

### Describe alternatives you've considered

I have looked for ways to handle a `dbt.exceptions.CompilationException` gracefully when running `dbt docs generate` but I can't find any way to do it.

I have done some research into using Jinja to check for a missing file or handle a return code from the `doc` macro but have only found dead ends.

There might be a way to do something using `{% include 'something' ignore missing %}` but a solution started to look more and more 'hacky'.

### Who will this benefit?

This feature will be useful for everyone using dbt docs as it will permit the generation of interim documents during the initial development phase and allow it to happen without having to hack around. 

This would make it easier to demonstrate the current state of the work, in the form of documentation, to stakeholders and fellow engineers.

### Are you interested in contributing this feature?

I'd like to contribute if I can but do not have much Jinja knowledge (yet)

### Anything else?

This is why I encountered the issue mentioned above:

https://github.com/data-mie/dbt-profiler/issues/71 (I raised this)

**Comment by dbeatty10** [comment]
Thanks for reaching out @ian-lewis-d !

Is this only happening in workflows where you are automating the creation of [docs blocks](https://docs.getdbt.com/docs/collaborate/documentation#using-docs-blocks) Markdown files (with tools like `dbt-profiler`)? Or are you also running into this when you are creating docs blocks manually?

**Comment by ian-lewis-d** [comment]
Thanks for the response @dbeatty10 

I have so far been generating doc blocks with `dbt-profiler`, currently in my local dev environment. At the moment the compile errors mean that I would have to generate the files and commit them.

**Comment by dbeatty10** [comment]
If everything is in your local dev environment, would you actually need to commit them? Or could you just generate them (without also committing)?

My guess is that as long as you generate them, then you wouldn't have any compile errors (even if you don't commit the generated files).

**Comment by ian-lewis-d** [comment]
It's a hack but I have to look at generating the files in dev, or skeleton files, and then excluding the folder when committing.

Whilst this allows for `dbt compile` to run it doesn't solve the problem of dealing with a compile exception that could instead be a warning and allow for docs to be served.

Is there a way to get the macro parser to return an empty string instead of throwing an exception?

**Comment by dbeatty10** [comment]
We don't want ignore compilation errors since they are a crucial mechanism to ensure that the project files are in an expected state.

We would like to help discover if there's a workflow for your use-case that doesn't feel like a hack though.

I haven't used `dbt-profiler` before, so I don't know the possible workflows. It sounds like you're running into a [catch-22](https://github.com/data-mie/dbt-profiler/issues/71) / chicken vs. egg problem, but I don't know the best way to resolve it. Treating compilation errors as warnings won't be the path, so we'll have to find a different option.

Could you share the step-by-step process you would use for `dbt-profiler` when adding a new model (or source?) to your project? That might help us put our finger on the crux of the catch-22.

**Comment by dbeatty10** [comment]
@ian-lewis-d I took a closer look at the workflow you described and gave it a shot myself.

### The problem
After adding [`data-mie/dbt_profiler`](https://hub.getdbt.com/data-mie/dbt_profiler/latest/) to packages.yml and running `dbt deps`, I ran the [`update-relation-profile.sh`](https://github.com/data-mie/dbt-profiler/blob/main/update-relation-profile.sh) script like this:
```shell
./dbt_packages/dbt_profiler/update-relation-profile.sh my_model_alias my_model_schema
```

The output went into my `docs` directory:
```shell
$ tree docs

docs
└── dbt_profiler
    └── my_model_schema
        └── my_model_alias.md
```

Then I added it to my `models/_models.yml` like this:
```yaml
models:
  - name: my_model_alias
    description: |
      `dbt-profiler` results:

      {{ doc("dbt_profiler_results__my_model_schema_my_model_alias") }}
```

I got tripped up as well when running this:
```
dbt docs generate
```

### The solution

The solution for me was to update `dbt_project.yml` and specify either [`docs-paths`](https://docs.getdbt.com/reference/project-configs/docs-paths) or [`model-paths`](https://docs.getdbt.com/reference/project-configs/model-paths).

Like this:
```yaml
docs-paths: ["docs"]
```

Or this:
```yaml
model-paths: ["models", "docs"]
```

### Next steps

It looks to me like we have the right pieces in place within dbt-core, so I'm going to close this issue as `wont_fix`. Rather, I'd recommend just adding a little bit of documentation to https://github.com/data-mie/dbt-profiler that adds the relevant instructions related to specifing either [`docs-paths`](https://docs.getdbt.com/reference/project-configs/docs-paths) or [`model-paths`](https://docs.getdbt.com/reference/project-configs/model-paths) within `dbt_project.yml`.
