### ISSUE TITLE
[CT-2493] Create --publications-dir parameter

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#7467]
Create a new --publications-dir flag, accepted by any command that requires a manifest. This flag would indicate to dbt where to read publication artifacts from other projects in the running project, and eliminate the need to hardcode the path as we are doing [here](https://github.com/dbt-labs/dbt-core/pull/7276/files#diff-a25a77362db78f4ddc0675bcbd4775e158631076c9918ce5b64cfcd9f6db6bceR771). 

^ In case that link gets stale: 
```python
--- somewhere in parser/manifest.py
path = os.path.join("publications", publication_file_name)
```

**Comment by iknox-fa** [comment]
@MichelleArk What should the default value for said flag be?  We're assuming it should be the string "publications", but wanted to double check.

**Comment by jtcohen6** [comment]
Planning to close this as unneeded in the v1.6 implementation
