### ISSUE TITLE
[Regression] Empty `test` in a model's column enumeration within model config yml file not parsing correctly in 1.5.0

### ISSUE THREAD

**Issue by zackary-naas** [dbt-labs/dbt-core#7474]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

We run a CI job using GitHub actions that always pulls the latest version of dbt-core, and the version just switched over to 1.5.0 in the last hour or so. This job uses the manifest file from the previous successful run to drive the build/deferred build. 

We're experiencing a regression in the parsing process, specifically ` Invalid models config given...` that seems to be caused by an empty `tests` config on the given columns within this model's config `.yml` file. 
![image](https://user-images.githubusercontent.com/38761232/234956361-86b33a9c-c68e-444b-88e4-d2b9966358e4.png)

![image](https://user-images.githubusercontent.com/38761232/234956638-d29ac40f-3f2e-4b3b-afb3-201286837237.png)

This was working well even just roughly 1 hr before with version 1.4.6, and nothing else changed with this specific model's config file in this particular PR that triggered the CI job.

### Expected/Previous Behavior

Expecting the parsing process to complete without issue, as it had just around 1 hr previously with version 1.4.6

### Steps To Reproduce

1. Use dbt version 1.5.0 (`dbt=1.5.0`)
2. Have a model config file with a table's column details enumerated, including names, descriptions and tests.
3. Make sure one of the `test` configs is left blank (`test: `)
4. Run `dbt build`

### Relevant log output

```shell
Run dbt build --target prod --defer --select state:modified+ --state ./
17:53:46  Running with dbt=1.5.0
17:53:46  Unable to do partial parsing because saved manifest not found. Starting full parse.
17:53:56  [WARNING]: Did not find matching node for patch with name 'unit_daily_fact' in the 'models' section of file 'models/final/shared/shared_dims/_shared__models.yml'
17:53:56  Encountered an error:
Parsing Error
  Invalid models config given in models/final/analytics/project_deckster/_project_deckster__models.yml @ models: {'name': 'deckster_dataset_ebr_light', 'meta': {'owner':.....
```
```
.....'tests': None}], 'original_file_path': 'models/final/analytics/project_deckster/_project_deckster__models.yml', 'yaml_key': 'models', 'package_name': 'appfolio_analytics_dbt'} - at path ['columns'][0]['tests']: None is not of type 'array'
Error: Process completed with exit code 2.
```
```


### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- Python: 3.9.16
- dbt (working version): 1.4.6
- dbt (regression version): 1.5.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by benbenski** [comment]
Hey @zackary-naas , I had a similar issue on `1.5.0` and just removed any `tests:` that didn't actually have tests declared.

Seemed to resolve things + probably a good 'spring cleaning' activity (though I was lucky in that there were only about 5, all contained in one `.yml` file).

**Comment by jtcohen6** [comment]
Hey @zackary-naas, thanks for opening!

@benbenski is right on - it was never supported behavior to have an empty `tests:` list defined in your project's yaml files - but if this is causing you a big headache, or if you have a legitimate use case / reason for doing this, I'm open to hearing about it!

At the least, we can add it as a note to the migration guide: https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.5

**Comment by zackary-naas** [comment]
We're just getting started in our dbt journey and wanted to keep these empty `tests:` around as a sort of to-do item for our group. 

Good to know this is being more _officially_ unsupported in v1.5+. Should we close this regression issue then?

**Comment by jtcohen6** [comment]
ah, cool! welcome :)

You could replace the empty list (nothing) with _actual_ empty list, if you want to - even more explicit:
```yml
models:
  - name: my_model
    columns:
      - name: my_column
        tests: [] # todo!
```

That should work fine in any version of dbt

**Comment by zackary-naas** [comment]
resolved using the method described by @jtcohen6 above. (Thanks @jtcohen6 !)
