### ISSUE TITLE
[CT-2502] [Bug] Wrap `check` constraint expression in parens

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7480]
https://github.com/jwills/dbt-duckdb/issues/156

https://github.com/dbt-labs/dbt-core/blob/828d723512fced809c63e369a82c7eb570a74986/core/dbt/adapters/base/impl.py#L1310-L1311

https://github.com/dbt-labs/dbt-core/blob/828d723512fced809c63e369a82c7eb570a74986/core/dbt/adapters/base/impl.py#L1389-L1390

should both be

```python
 if constraint.type == ConstraintType.check and constraint.expression: 
     return f"check ({constraint.expression})" 
```

Parentheses are required on:
- Postgres
- Databricks
- DuckDB

---

Also:
- Add functional tests on all our adapters for all supported constraints types

**Comment by emmyoop** [comment]
Need to add tests in core/adapters

**Comment by emmyoop** [comment]
Do along with https://github.com/dbt-labs/dbt-core/issues/7417
