### ISSUE TITLE
[CT-2506] Accept a list of ProjectDependency in dbtRunner's constructor

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#7484]
When provided a list of `ProjectDependency`s in dbtRunner's constructor, plumb this through to create a manifest.

**Comment by iknox-fa** [comment]
Per BLG- May 15 23:
Currently `ProjectDependency` looks like this:

```
@dataclass
class ProjectDependency(dbtClassMixin):
    name: str
```

I think we'll need more information about how that becomes a `project` to estimate this ticket properly.

**Comment by MichelleArk** [comment]
Closing in favor of https://github.com/dbt-labs/dbt-core/issues/7736
