### ISSUE TITLE
[CT-2507] [Feature] Add parsed files (including sources or packages.yml) to the result of the 'compile' step

### ISSUE THREAD

**Issue by OatmealLick** [dbt-labs/dbt-core#7485]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like to see all of the files that can be templated (including sources, `packages.yml`, etc) with their macros resolved in the `target` directory.

Running `dbt compile` would produce, beside the compiled sqls for models, other files that use templating, such as `packages.yml`.

### Describe alternatives you've considered

Parsing the file on my side - but this means that different pieces of code will do the parsing and it may introduce discrepancies. Having only dbt doing the parsing would keep dbt as the single source of truth.

### Who will this benefit?

All of the developers trying to extend functionality of `dbt` programmatically. 

In my case:
In my sources, based on the environment variable `ENV` I select proper `database` for the source. This is written with jinja template `{{ env_var("ENV", "default_dev_environment") }}`. I want to parse this file and use the source information in a separate tool, that needs to know about the sources used in dbt. 

Currently I need to replace the jinja template myself but this means that different pieces of code will do the parsing and it may introduce discrepancies in place of an error. I'd like dbt to resolve the template and used the resolved file.

### Are you interested in contributing this feature?

Yes, with some pointers in the code where to look for it

**Comment by dbeatty10** [comment]
Thanks for reaching out @OatmealLick !

[`dbt ls`](https://docs.getdbt.com/reference/commands/list) or [manifest-json](https://docs.getdbt.com/reference/artifacts/) are two alternatives that might work well for your use-case. See more detail on each below.

Do you want to take a look at each of these and let us know if it does/doesn't meet your needs?

### `dbt ls`

```shell
dbt --quiet ls \
    --resource-type source \
    --output json \
    --output-keys name original_file_path version latest_version alias unique_id database schema relation_name \
| python -m json.tool
```

```json
{
  "database": "my_database",
  "schema": "my_schema",
  "name": "my_source_table",
  "original_file_path": "models/_sources.yml",
  "unique_id": "source.my_dbt_project.my_source.my_source_table",
  "relation_name": "\"my_database\".\"my_schema\".\"my_source_table\""
}
```

If you want to see all the properties that are available within `dbt ls` for sources and you have [`jq`](https://stedolan.github.io/jq/) installed, it's easy to pretty-print the `nodes` key within `manifest.json`:
```shell
cat target/manifest.json | jq '.sources'
```

### `manifest.json`

There's a ton of information in [`manifest.json`](https://docs.getdbt.com/reference/artifacts/) including the properties in `dbt ls` and more.

I prefer to pretty-print it to a separate file so I can read it and see what's in there:
```shell
cat target/manifest.json | python -m json.tool > target/manifest.pp.json
```

Then open up `target/manifest.pp.json` to see the pretty-printed version.

**Comment by OatmealLick** [comment]
Hello @dbeatty10 
Thank you for your response.

`manifest.json` is perfect solution for me, I was not aware that this information can be found there. Thank you :)

**Comment by dbeatty10** [comment]
You are welcome @OatmealLick ! Glad to hear `manifest.json` is a great solution for you 🎉
