### ISSUE TITLE
[CT-2508] [Bug] `dbt ls` unable to use table's `identifier` 

### ISSUE THREAD

**Issue by alexeyegorov** [dbt-labs/dbt-core#7486]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In our setup, we wanted to use the combination of `name` and `identifier` for a table in source to rename internally the table for DBT. In this example, we had `deployed_forecasts` table that should be named `demand_forecast` in DBT. We were able to execute all the pipelines so far, but `dbt ls` does not detect the correct table name. I attach the screenshot below.

<img width="871" alt="Bildschirmfoto 2023-05-02 um 10 10 43" src="https://user-images.githubusercontent.com/5102843/235614461-e301d041-2af8-4a0d-9fca-648bdd4834df.png">

The source file looks as followed:

<img width="283" alt="Bildschirmfoto 2023-05-02 um 10 14 36" src="https://user-images.githubusercontent.com/5102843/235614635-520b07d2-f421-4dcc-aebb-ea24ea7359f8.png">

### Expected Behavior

We expected this to work (detect the correct identifier).

### Steps To Reproduce

1. Declare `name` and `identifier` tags for a table in source.
2. Use it in other model (such as base).
3. Using `dbt run` should work, but `dbt ls` is expected to throw an error.

### Environment

```markdown
- OS: Mac OS 13.3
- Python: 3.11.2
- dbt: 1.4.5
```

### Which database adapter are you using with dbt?

spark

**Comment by jtcohen6** [comment]
@alexeyegorov I would also expect this to work, based on the screenshots you've included.

Does your `base_demand_forecast` model look something like this?
```sql
select * from {{ source('forecasts', 'demand_forecast') }}
```
If I define a model like that, and a source like the one in the screenshot:
```yml
sources:
  - name: forecasts
    schema: dev_forecast
    tables:
      - name: demand_forecast
        identifier: deployed_forecasts
```

That works just fine for me:
```
$ dbt --quiet list
my_dbt_project.base_demand_forecast
source:my_dbt_project.forecasts.demand_forecast
```
