### ISSUE TITLE
[CT-2510] [Bug] Raise an error if non-versioned model is defined with same name as existing versioned model

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7487]
Set up:
```sql
-- models/my_model_v1.sql
select 1 as id
```
```yml
# models/whatever.yml
models:
  - name: my_model
    versions:
      - v: 1
```

```
$ dbt parse
12:48:12  Running with dbt=1.5.0
12:48:14  Performance info: target/perf_info.json
```
Now:
- create `models/my_model.sql` (no version suffix)
- do not add any new versions to the `versions` block in the yaml file

Re-parse with partial parsing, and everything looks fine:
```
$ dbt parse
12:48:29  Running with dbt=1.5.0
12:48:30  Performance info: target/perf_info.json
```
And now without partial parsing, I see an error (good! I should!):
```
$ dbt --no-partial-parse parse
12:48:43  Running with dbt=1.5.0
12:48:46  Encountered an error:
Compilation Error
  dbt found two models with the name "my_model".

  Since these resources have the same name, dbt will be unable to find the correct resource
  when looking for ref("my_model").

  To fix this, change the name of one of these resources:
  - model.my_dbt_project.my_model (models/my_model.sql)
  - model.my_dbt_project.my_model.v1 (models/my_model_v1.sql)
```

**Comment by gshank** [comment]
This is not a partial parsing bug per se. I've created a test case which does not fail appropriately even with full parsing.

**Comment by gshank** [comment]
I haven't been able to recreate the compilation error. Whether I create the non-versioned model first or second, it never complains.

**Comment by dbeatty10** [comment]
I tried the same set of steps as outlined and was **not** able to produce the compilation error.

**Comment by gshank** [comment]
Commit 0de046dfbef53cfe754c87ec58a638c7a8962dc6 yesterday removed the code that was causing the error in the example to be thrown.

**Comment by gshank** [comment]
The error was thrown in the no-partial-parse case and not in the partial parse case because the order of the nodes encountered was different and the code was checking is_versioned for the previously encountered node.

**Comment by gwerbin-tive** [comment]
The error message says this:

```
  dbt found versioned and unversioned models with the name "...".

  Since these resources have the same name, dbt will be unable to find the correct resource
  when looking for ref('...').

  To fix this, change the name of the unversioned resource
  model.... (models/...)
  or add the unversioned model to the versions in ...
```

How does one add an unversioned model to the list of versions? I tried `-v: ''` but it produced the filename suffix `_v.sql`

I traced the error message back to this change, but I don't see an explanation in this thread, or the commit message, or the code. Does anyone know/remember what that message was supposed to mean?
