### ISSUE TITLE
[CT-2514] Allow models to run on different compute / target

### ISSUE THREAD

**Issue by mvdwielen** [dbt-labs/dbt-core#7492]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

With dbt core I would like to be able to configure different targets per model.
Example: my dbt project contains 10 models, 5 should run on a small compute cluster, 3 on a medium compute cluster and 2 on a heavy extra multi node cluster due to huge data volumes and complex logic.

I have read the documentation and consulted the community but it seems not to be possible to set a different target for specific models. It is a very common use case to run workloads on different kinds of computes so to me it is quite straightforward that this capability should be available within dbt.

### Describe alternatives you've considered

Running separate dbt run commands and specify a different target, the issue with this approach is that it won't take dependencies in to account and therefore this approach won't work.

### Who will this benefit?

Everybody who wants to run models an different compute sizes.

### Are you interested in contributing this feature?

no

**Comment by owenprough-sift** [comment]
This is already possible for Snowflake: https://docs.getdbt.com/reference/resource-configs/snowflake-configs#configuring-virtual-warehouses

Is this request for a different database platform?

**Comment by mvdwielen** [comment]
@owenprough-sift yes this request is for a different data platform, in this case the request is for Databricks / Spark. I can't find an adapter specific config to set a different warehouse via the config for this adapter or am I overlooking something?

**Comment by owenprough-sift** [comment]
This issue might therefore belong over in the [dbt-databricks](https://github.com/databricks/dbt-databricks) repo.
Presently, `dbt-databricks` does not support model-level compute specification:

> You can override the compute used for a specific Python model by setting the http_path property in model configuration. This can be useful if, for example, you want to run a Python model on an All Purpose cluster, while running SQL models on a SQL Warehouse. Note that this capability is only available for Python models.

**Comment by mvdwielen** [comment]
@owenprough-sift thanks, I created a feature request in the dbt-databricks repo!
