### ISSUE TITLE
[CT-2517] Graph selection for public models from dependency projects

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#7496]
Currently `dbt ls` does not include any models from publication artifacts (dependency projects). Should it? My inclination would be to output public model dependencies the same way that models from installed packages output. 

E.g, a project with `project_a.public_model` available s a dependency: 
```
❯ dbt ls
14:43:02  Running with dbt=1.6.0-a1
14:43:02  target not specified in profile 'postgres', using 'default'
14:43:02  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 307 macros, 0 operations, 0 seed files, 2 sources, 0 exposures, 0 metrics, 0 groups
consumer_project.cross_project_ref
consumer_project.model
source:consumer_project.jaffle_shop.customers
source:consumer_project.jaffle_shop.orders
```

**Comment by jtcohen6** [comment]
`dbt ls` should include upstream public models.

Let's make sure the **JSON output** of `dbt ls` has some sort of attribute to distinguish this as an upstream public model. (It will have the `package_name` which differs from the current project name, but wouldn't necessarily distinguish it from models from packages / installed as source code.)
