### ISSUE TITLE
[CT-2522] Redefine Metric node for the Manifest and update parsing

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#7500]
There are two new node types being added to the manifest as part of the MetricFlow integration work: SemanticModel nodes and Metric nodes. This ticket addresses the Metric nodes. In [dbt-semantic-interfaces](https://github.com/dbt-labs/dbt-semantic-interfaces) we're adding a protocol of a [Metric](https://github.com/dbt-labs/dbt-semantic-interfaces/issues/18), which will have the shared standard definition of a Metric. In dbt-core we need to compose this protocol with base node classes to define dbt-core's representation of a Metric. Additionally there are some additional fields we should expose as defined in #7456

### Blocked by:

- https://github.com/dbt-labs/dbt-core/issues/7470
- https://github.com/dbt-labs/dbt-semantic-interfaces/issues/18

**Comment by emmyoop** [comment]
This should be done along with the issue to parse the new metric node so that we don't start breaking tests - #7501

**Comment by QMalcolm** [comment]
An update on context. dbt-core already has a concept of a Metric Node from dbt-metrics. Thus instead removing and re-adding metric nodes, what we're really doing is redefining metric nodes to match the spec defined in [dbt-semantic-interfaces](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/0309f855a61121366f96e8be2af982d87483b218/dbt_semantic_interfaces/protocols/metric.py#L84). Additionally, since metric nodes already exist we don't need to build parsing for them, but instead just update the parsing. Thus #7501 is being wrapped into the work of this issue.
