### ISSUE TITLE
[CT-2527] Adapters allow for optionally installing MetricFlow

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#7505]
The packaging of the individual adapters need to allow for the optional installing of MetricFlow, e.g. `pip install dbt-snowflake[metricflow]`. This issue is likely just for tracking, as part of this project, issues on the adapter specific repositories for ensuring this functionality.

**Comment by jtcohen6** [comment]
We're going to take a different approach here, so I'm going to close this issue for now (cc @tlento)
