### ISSUE TITLE
[CT-2529] Migration tool for moving from dbt-metrics to new semantic layer specs

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#7507]
There are people currently using dbt-metrics, and thus have their metric definitions in that spec. With the move in dbt-core 1.6 to the [new semantic layer specifications](https://github.com/dbt-labs/dbt-core/discussions/7456), we'll want to provide a tool allowing for people to migrate their old metric definitions to the new semantic layer definitions. Luckily we already have a [prototype of this tool in MetricFlow](https://github.com/dbt-labs/metricflow/blob/main/metricflow/model/transformations/dbt_to_metricflow.py). This needs some updates, like supporting derived metrics. [There does exist an example of this also in MetricFlow](https://github.com/dbt-labs/metricflow/blob/main/metricflow/model/dbt_mapping_rules/dbt_metric_to_metrics_rules.py#L102), but would require some changes. Additionally, this tool should be moved to dbt-core as it's use will be needed even if MetricFlow isn't installed.

### Blocked by:

- #7499
- #7500

**Comment by jtcohen6** [comment]
Anyone who has (legacy) derived metrics defined in their project is going to see an error about the `{{ metric() }}` macro (context method) being undefined. E.g. in our internal analytics project:
```
$ dbt parse
14:04:31  Running with dbt=1.6.0-b4
...
14:04:55  Encountered an error:
Compilation Error
  Could not render coalesce( {{metric('abc')}}, 0) - coalesce( {{metric('xyz')}}, 0): 'metric' is undefined
```

**Comment by jtcohen6** [comment]
@Jstein77 Can we close this one, now that [`dbt-converter`](https://github.com/dbt-labs/dbt-converter) exists?
