### ISSUE TITLE
[CT-2530] [Feature] (bug?) YAML Selectors: Enable having `exclude` not apply to mutual parents

### ISSUE THREAD

**Issue by jaredx435k2d0** [dbt-labs/dbt-core#7510]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I notice in [the docs that it says](https://docs.getdbt.com/reference/node-selection/yaml-selectors#exclude):

    exclude … is always applied last within its scope.

Let’s say I have the following lineage for an output model used by a Tableau report:

inventory --------------------->
int_products_enhanced --------->
..........................................................---> rpt_tableau
sales ------------------------->

And the following lineage used by my sales model:

int_products_enhanced ----->
stg_brick_mortar_sales ---->
..........................................................---> sales
stg_ecommerce_sales ------->

You’ll notice that `int_products_enhanced` is used in both transformations.
The `sales` model, along with all it’s parents, is a heavy transformation I want to exclude from hourly runs (because I run the sales model daily).

That said, because the lineage for the `rpt_tableau` model also directly references `int_products_enhanced`, I do want `int_products_enhanced` to be re-run when `rpt_tableau` and it’s parents are run.

Given that exclude selectors apply last and the following selectors.yml, int_products_enhanced doesn’t get re-run, resulting in `rpt_tableau` having stale data.

```
selectors:
    - name: reporting_layer_refresh_excluding_daily_and_staging
      definition:
        union:
          - method: fqn
            value: rpt_tableau
            parents: true
            children: false
          - exclude:
                - method: fqn
                  value: sales
                  parents: true
                  children: false
```

I'm requesting some way to make exclude not apply to shared upstream models, so that it's less "greedy" and I can ensure freshness where needed.

### Describe alternatives you've considered

The only other solutions I can think of seem to me to be fragile / error prone:
1. Some sort of tagging solution, where I have hourly, daily, etc. subfolders for all of my current folders. This seems bad because someone could easily accidentally have a model in the wrong folder and not realize it.
2. Explicitly specifying every model I do want in a selector.

Both of those seem like poor solutions because they don't take advantage of one of dbt's biggest strengths / functions, `ref()`. I want to leverage the graph and run everything needed for my output models, but simply exclude things that should be daily and aren't mutual parents of my hourly models.

We have over 5k models. Our transformations are anywhere from 3 - 30 models each.

### Who will this benefit?

I would think this would benefit everyone, which is why I put "bug?" in the title.

The huge issues here for us are cost and latency. Our dbt runs take far, far longer than necessary, because we constantly have huge, daily models being re-run. The current setup is resulting in exorbitant Snowflake costs.

We've been forced to panic-address this by using `source()` instead of `ref()` for everything that's heavy and daily, so that we can effectively "cut off" their lineage, while still using the `+` operator in front of our models we want to run to still run their full lineage. Given that this isn't how dbt is meant to be used, it of course comes with a lot of cons.

### Are you interested in contributing this feature?

I would love to, but lack Python skills. Of course, I'm more than happy to test, answer questions, provide additional examples and screenshots, etc.

### Anything else?

I posted a very simple example set of files and screenshot in the dbt Slack [here](https://getdbt.slack.com/archives/CBSQTAPLG/p1682718245445779), which includes this highly simplified screenshot of what I'm having a hard time accomplishing with the current implementation:
![image](https://user-images.githubusercontent.com/111536894/236063150-0bc0539b-a92b-46ac-b2f3-3e789f6cc40b.png)

**Comment by jaredx435k2d0** [comment]
Hey, @b-per !

The issue here is the "direct is important here" part:
rpt_tableau may be the final output of a long lineage of models working up to that point. int_products_enhanced, for example, probably also has dependencies that would need to be refreshed in order for it to not be stale. And those dependencies may have other dependencies that'd need to be refreshed for them to not be stale.
They key here is really that I'd basically want to run everything upstream of a given model, **_except_** for the things upstream of some exception models.

I'll paste here our real example. Maybe we're just using dbt wrong or I'm misunderstanding something:
![image](https://user-images.githubusercontent.com/111536894/236503995-2d8b0e16-9b7a-4022-b972-01e64a8b1d34.png)


I believe there are multiple instances of the same problem in this image, but the one I'll point out relates to stg_amaczar_countries (highlighted node, middle left), RPT_DAILY_SALES (red box near middle), and report__ads_budget (top right).

You'll note that report__ads_budget indirectly relies on the other two. I want to refresh this report (and therefore it's parents) every hour.

I only want the RPT_DAILY_SALES transformation to run daily.

I want stg_amaczar_countries to be refreshed hourly in order for report__ads_budget to not be using stale data.

It seems like this isn't possible with the existing YAML selectors, unless I explicitly list out every individual model. It seems like the best recommendation I can find so far is to make "hourly" and "daily" subfolders inside every folder of my repo.

The problems I feel with both those approaches are:
1. They seem very "manual" and prone to breakage (or things not running as expected, especially when we have 10 Engineers and 5k+ models)
2. They seem to not take advantage of one of dbt's most powerful features, ref().

It seems like there'd have to be a way for us to take advantage of ref() and the therefore known lineage of a transformation (multiple models in a flow) to run just the transformations we want to. But that's where I wonder if I'm maybe understanding / viewing dbt incorrectly somehow.

**Comment by b-per** [comment]
Thanks for the details here.

OK, now that I get it a bit more, the rule you have might be able to be equivalent to: "I want to run everything upstream of `rpt_tableau` except the nodes that only flow through `sales`". And in that case, yes, I can't think of a possible combination of any selector that would work for this situation.

Would there be a logical way to implement that actually?

--- 

Talking more solution/workaround mode than the bug itself:
- you could maybe tag `run_often` the models that you want to be able to run often, and then `union` your initial selector with the `intersection` of `tag:run_often+` and `+rpt_tableau` 
- or you could try to avoid "loops" in your DAG (e.g. [rejoining of upstream concepts](https://dbt-labs.github.io/dbt-project-evaluator/0.5/rules/modeling/#rejoining-of-upstream-concepts)). By making a new model quite similar to `int_products_enhanced` but that isn't parent of `sales` you might be able to achieve a simpler scheduling (with the added cost of 1 extra model in your project)

**Comment by jaredx435k2d0** [comment]
> I want to run everything upstream of rpt_tableau except the nodes that only flow through sales
I think this sounds right.

> Would there be a logical way to implement that actually?
I would think so, given that looking at the graph, if I told a human that sentence, they could tell me which models should and should not be included.

> you could maybe tag run_often the models that you want to be able to run often, and then union your initial selector with the intersection of tag:run_often+ and +rpt_tableau
This could potentially work functionally, but any tagging solution seems to me to still not leverage the powerful `ref()` functionality. It seems like I could accomplish about the same thing with a traditional repo of SQL scripts that I run in a certain order at a certain time using a cron job (without dbt involved). Because of that, it sort of feels "wrong" to me, or like I'm missing a better way.

> or you could try to avoid "loops" in your DAG (e.g. [rejoining of upstream concepts](https://dbt-labs.github.io/dbt-project-evaluator/0.5/rules/modeling/#rejoining-of-upstream-concepts))
I don't think this applies here given:
> Only includes cases where the model "in between" the parent and child has NO other downstream dependencies.

What could potentially add clarity to this is that, right now, the hacky bandaid we've temporarily applied (which cut our compute cost by over 60% despite a significant increase in the number of models being added) is making all these "heavy, infrequent" models sources, and then using source() to reference them. This obviously is not how dbt should be used and comes with problems, but I think it illustrates well the logical equivalent of what we're trying to solve, which is to "cut off" the lineage at a certain point, but still run everything else.
So for now, all of our jobs are +my_model, and everything within that "transformation" uses `ref()`, up until something that lives "outside" that transformation (e.g., RPT_DAILY_SALES), which we `source()`.
I want to get away from this ASAP, but implemented it in a panic when we realized how much more money we were paying in Snowflake in compute costs after implementing dbt. Like I said above, we were previously paying 3x what we are now, even though we've since a decent number of new models (since we're still migrating).

**Comment by jaredx435k2d0** [comment]
Just got thinking that, due to this:

> What could potentially add clarity to this is that, right now, the hacky bandaid we've temporarily applied (which cut our compute cost by over 60% despite a significant increase in the number of models being added) is making all these "heavy, infrequent" models sources, and then using `source()` to reference them ... I think it illustrates well the logical equivalent of what we're trying to solve, which is to "cut off" the lineage at a certain point, but still run everything else.
, maybe the best way to represent this logically is a way to select "unique" upstream parents, which I could then exclude.

I think the issue right now is that I'm unable to identify "shared" parents if one of my nodes is a parent of the other. If I were able to identify nodes which were unique to my node's lineage, then I could confidently exclude those. This would enable me to build a selector that included all of my heavy, infrequent models (such as RPT_DAILY_SALES, and then say unique_parents: true). Unique parents would be identified simply as having 0 children that were not parents of the node in question.

So maybe my feature request should be:
add "unique parents" option for YAML selectors

Thoughts?

**Comment by dbeatty10** [comment]
Sorry for the slow response here @jaredx435k2d0 🙏 

My gut says that we'd be unlikely to implement a "unique parents selector" for this case since it feels relatively niche. I would advocate alternatives instead:
- curated [tags](https://docs.getdbt.com/reference/resource-configs/tags)
- curated [selectors](https://docs.getdbt.com/reference/node-selection/yaml-selectors)
- `source` instead of `ref`
- cross-project ref (Phase 2 [here](https://github.com/dbt-labs/dbt-core/discussions/6725))

For most of these, you could do your own parsing of `manifest.json` to make sure that your tags/selectors/sources include the precise models that you want.

### Tags or selectors
One alternative that you've already mentioned exploring is explicitly tagging your models so you can execute them on the desired frequency. I'm guessing most folks in similar situation to you are using tags or selectors.

### `source` instead of `ref`
This is a clever solution 🧠 and it seems like a pretty decent approach given your description. Additionally, it's similar to the final alternative listed below.

### Cross-project `ref`
Another alternative will be available later this year using dbt Cloud. Your current approach of make all the "heavy, infrequent" models a `sources` is similar to how you will be able to `ref`erence models _across projects_. i.e., you can separate out those heavy models into their own dbt projects and then still be able to `ref` them in other projects.

### Side note, for the far off future
If we were to enable more complex selectors like the one you proposed, I would vote for enabling something more general purpose like [PGQ or GQL](https://victor.marsault.xyz/resources/articles/GPMLSigmod.pdf) instead (both of which are on a standards track yet not yet available).
