### ISSUE TITLE
[CT-2533] [Feature] Support sqlparse 0.4.4

### ISSUE THREAD

**Issue by lukehsiao** [dbt-labs/dbt-core#7515]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

`sqlparse` <0.4.4 contains a moderate security vulnerability: https://github.com/advisories/GHSA-rrm6-wvj7-cwh2

dbt-core has started to pin to <0.4.4 in https://github.com/dbt-labs/dbt-core/pull/7394 which makes it difficult for packages using dbt to update to the fixed version.

Would it be possible for dbt to support v0.4.4? 

### Describe alternatives you've considered

The answer might just be "no". In which case we will have to wait until a new version of sqlparse addresses the issue. It does not seem like there is anything upstream sqlparse tracking work to resolve https://github.com/dbt-labs/dbt-core/issues/7396. So, if the answer is no, then I would hope the appropriate effort upstream can be made so we have a path forward eventually.

### Who will this benefit?

All users of dbt-core who want to update to a non-vulnerable sqlparse version.

**Comment by dimoschi** [comment]
+1 even a moderate security vulnerability can be a problem for some organizations.

**Comment by dimoschi** [comment]
Gonna try reproduce the issue and look if I can open a PR at `sqlparse`. Thanks for providing context @dbeatty10

**Comment by jtcohen6** [comment]
Another user just reported (#7521) seeing the same issue with `sqlparse==0.4.4` on `Debian GNU/Linux 11 (bullseye)`

**Comment by dbeatty10** [comment]
@MauroLuzzatto provided some very useful information [here](https://github.com/dbt-labs/dbt-core/issues/7595#issuecomment-1545263773), namely:

> I have also seen the error disappearing after retriggering the GHA run.

So maybe there's some kind of state that is available to subsequent executions that isn't available to the first one in a fresh environment?

This is the context reported by @MauroLuzzatto:

> So far, I have only seen the errors on
> - `python:3.8-slim-bullseye`
> - `Ubuntu: 22.04.2 LTS` 
> 
> And not in any local development environment:
> - `macOS Ventura Version 13.3.1`
> 
> However, that might also be connected to the fact that the dbt and other modules are installed there (CI and deployment) on every run.

**Comment by emmyoop** [comment]
We should replace `sqlparse` with a manual solution.

**Comment by dbeatty10** [comment]
💡 @emmyoop do we have an issue in GitHub to replace `sqlparse` with a manual solution? Or would that issue need to be created?

**Comment by emmyoop** [comment]
Closing in favor of #7791

**Comment by jtcohen6** [comment]
Reopening per https://github.com/dbt-labs/dbt-core/issues/7791#issuecomment-1609468046

**Comment by bdashrad** [comment]
Looks like #7919 has pivoted back to use sqlparse 0.4.4 as well

**Comment by gshank** [comment]
New fix in https://github.com/dbt-labs/dbt-core/pull/8215
