### ISSUE TITLE
[CT-2535] [Regression] Print flag inverted in dbt v1.5.0

### ISSUE THREAD

**Issue by thomasgjerdekog** [dbt-labs/dbt-core#7517]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

The print macro only seems to work with the `--no-print` flag set. While `--print` seems to disable printing.

### Expected/Previous Behavior

The print macro printing by default, and not when `--no-print` flag set

### Steps To Reproduce

Using dbt-core==1.5.0
Create a macro file print_test.sql with this code:
```jinja
{% macro print_test() -%}

    {{ print("Hello world") }}

{%- endmacro %}
```
Run the macro with `--print` flag set
```
dbt --print run-operation print_test
```
It produces no output

Run the macro with `--no-print` flag set
```
dbt --no-print run-operation print_test
```
It outputs "Hello world"

### Environment

```markdown
- OS: Windows 10 v21H2
- Python: 3.10.8
- dbt (working version): 1.4.5
- dbt (regression version): 1.5.0
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

It seems like this check might be inverted: https://github.com/dbt-labs/dbt-core/blob/fd7306643fd3a98e3232cbc15bf50eb2f3733603/core/dbt/context/base.py#L655

**Comment by dbeatty10** [comment]
Thanks for reporting this and isolating it the exact line of code @thomasgjerdekog 🏆

Thanks for the nice reproduction instructions -- I'm seeing the exact same thing as you for dbt-core 1.5.

Agreed the the fix is to just invert the check. I've opened up this PR as a result: https://github.com/dbt-labs/dbt-core/pull/7524
