### ISSUE TITLE
[CT-2542] [Feature] `dbt run` option to refresh tables including all dependencies

### ISSUE THREAD

**Issue by aBBDnGus** [dbt-labs/dbt-core#7542]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Our data models consist of views and tables. When we change the models, we execute `dbt run`. Also, we want to refresh the tables on regular basis, running `dbt run --select config.materialized:table`.
Now, we have the 3 models with the following dependencies: 
* model `table_1`: `materialized=table`
* model `view_2`: `materialized=view`, depends on `table_1`
* model `table_3`: `materialized=table`, depends on `view_2`

Executing `dbt run` works fine. But executing `dbt run --select config.materialized: table` yields an error at `creating sql table model table_3`: `relation view_2 does not exist`
When updating `table_1`, then `view_2` is deleted because it depends on `table_1`. As we select only tables, `view_2` is not created anymore and therefore creation of `table_3` fails.
Could you please create an option (or maybe there is already one?) with which we can refresh just the tables, but considering all dependencies for this.

### Describe alternatives you've considered

* Execute `dbt run` on regular basis instead of `dbt run --config.materialized:table`. This needs more database operations than necessary.
* Set a tag to `view_2` and specify that this is also refreshed regularly. This could always cause errors when forgetting the tag
* Materialize `view_2` as table. This also causes errors when forgetting.

### Who will this benefit?

Projects with
* materialized tables that should be refreshed regularly
* a complex structure, where views depend on tables and tables again depend on views

**Comment by dbeatty10** [comment]
Is the main issue you are running into that the relevant views will not exist yet the first time you run this command?

```shell
dbt run --config.materialized:table
```

If so, then I think there's a cold-start problem -- those views need to be built somehow.

Did you already consider [state-based selection](https://docs.getdbt.com/reference/node-selection/methods#the-state-method)?

**Comment by aBBDnGus** [comment]
I'm afraid that neither of them works for us.
* It is not a cold-start problem. We initially execute `dbt run`. After this, we execute `dbt run --config.materialized:table` and the command `drop table if exists table_1__dbt_backup cascade` drops also `view_2`, which depends on it. Due to the selection, `view_2` is not created anymore.
* State-based selection does not work: As far as I understood, the state checks whether the dbt models have changed. But with refreshing the tables, we would need to check whether the underlying data have changed.

**Comment by dbeatty10** [comment]
Thanks for that info @aBBDnGus -- I see what you are saying about the cascading drop statement that drops `view_2`.

What dbt adapter are you using?

**Comment by aBBDnGus** [comment]
> What dbt adapter are you using?
Which adapter do you mean? We are using `dbt-postgres`

**Comment by jtcohen6** [comment]
This is a Postgres thing! Most other data platforms support "late-binding" views for just this reason, whereby a view is not cascade-dropped every time an underlying table is recreated.

Wayyyy back when (~4 years ago), dbt supported "non-destructive" runs for this reason, whereby it would `truncate` + `insert` tables instead of dropping & recreating them. This caused issues any time the tables' column schema changed, of course. And then Redshift added support for late-binding views, and so it really became a (not-so-optimal) optimization for Postgres only.

Since this problem doesn't exist on other data platforms—and since Postgres tends to be pretty fast for creating views—I don't think the juice is worth the squeeze for this one.
