### ISSUE TITLE
[CT-2547] [Bug] `dbt docs` not finding compiled code with 1.5.0

### ISSUE THREAD

**Issue by gilcrest** [dbt-labs/dbt-core#7553]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I currently have 1.4.5 and 1.50 installed via virtual environments. If I run `dbt docs generate` followed by `dbt docs serve` using 1.5.0, every model, when I click on the Compiled Code view, has the following message:

<img width="1037" alt="Screenshot 2023-05-08 at 1 57 09 PM" src="https://user-images.githubusercontent.com/5226765/236897583-9b80f318-b98c-421a-a28a-13fb322cb1e0.png">

### Expected Behavior

If I run the exact same commands using 1.4.5, I am able to see the compiled code locally on my dbt docs site. 

### Steps To Reproduce

I have a really simple shell script that I run in both virtual environments (dbt 1.4.5 and dbt 1.5.0) and I would expect the behavior to be the same and see the compiled sql code on the dbt docs site.

```shell
#!/bin/zsh

dbt clean
dbt deps
dbt compile
dbt build
dbt docs generate
dbt docs serve
```

### Environment

```markdown
- OS: macOS 13.3.1 (a)
- Python: 3.10
- dbt: 1.5.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
@gilcrest Thanks for opening!

The `dbt docs serve` command currently expects to re-parse the project, and rewrite `manifest.json` (without the compile step). It really shouldn't do that.

I think we might be able to solve this simply by removing `@requires.manifest` from the `serve` task. Let me validate that quickly.
