### ISSUE TITLE
[CT-2548] [Feature] simplify definition of adapter inheritance

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-core#7556]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

as a result of my experiments with a multi-adapter dbt package in https://github.com/dbt-msft/dbt-tsql/pull/1

if you want to inhierit an adapter wholesale, but only change a few jinja-sql macros there's a lot of cruft to pull it off.

Consider the case of Azure SQL (`azsql`) and SQL Server (`sqlserver`) example. The only meaningful difference between these data platforms is that with SQL Server you may switch between databases with the `USE` command, but with an Azure SQL database, you cannot.

In order to make a `dbt-sqlserver` that inhierits from a `dbt-azsql` and uses 100% of Python code of the parent, you must define the following:

```py
from dataclasses import dataclass

from dbt.adapters.base import AdapterPlugin

from dbt.adapters.azsql import (AzureSQLAdapter, AzureSQLConnectionManager,
                                AzureSQLCredentials)

from dbt.include import sqlserver

class SQLServerConnectionManager(AzureSQLConnectionManager):
    TYPE = "sqlserver"

class SQLServerAdapter(AzureSQLAdapter):
    ConnectionManager = SQLServerConnectionManager

@dataclass
class SQLServerCredentials(AzureSQLCredentials):
    @property
    def type(self):
        return "sqlserver"

Plugin = AdapterPlugin(
    adapter=SQLServerAdapter,
    credentials=SQLServerCredentials,
    include_path=sqlserver.PACKAGE_PATH,
    dependencies=["azsql"]
)

__all__ = [
    "Plugin",
    "SQLServerAdapter",
    "SQLServerCredentials"
]
```

However, the only new information being defined is:
- the `type`, and
- the location of the macros to include in the package

Here's the simplest version I could envision.

```py
from dataclasses import dataclass

from dbt.adapters.base import AdapterPlugin

from dbt.include import sqlserver

class SQLServerAdapter(AzureSQLAdapter):
    include_path=sqlserver.PACKAGE_PATH,
    dependencies=["azsql"]
```

### Describe alternatives you've considered

1. copy and paste the code
2. use a new profile parameter and some jinja if logic to determine if the macro should be used
3. avoid the dispatch altogether?

### Who will this benefit?

the community of partner-adapter maintainers. this is not just a TSQL problem, but something we see come up in other data platforms such as Databricks with the Unity Catalog and Redshift with ra3 nodes etc

### Are you interested in contributing this feature?

sure?

**Comment by dbeatty10** [comment]
You are blazing new trails @dataders 🥇

Godspeed on the simplification.

There might not be the scale to justify it, but another alternative could be a `cookiecutter` template (or [cruft](https://cruft.github.io/cruft/) or [copier](https://copier.readthedocs.io/en/stable/), etc) that allows you to generate the boilerplate that you need to inherit and extend another adapter.

**Comment by ismailsimsek** [comment]
@dataders @dbeatty10 this is implemented in this package implemented in this package https://github.com/memiiso/opendbt feel free to give it a try 

PR https://github.com/dbt-labs/dbt-adapters/pull/261
example https://github.com/memiiso/opendbt/blob/main/docs/EXAMPLES.md#execute-python-model-locally
