### ISSUE TITLE
[CT-2551] Make State Selection Collectively Exhaustive

### ISSUE THREAD

**Issue by trouze** [dbt-labs/dbt-core#7564]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This is a follow on from prior art discussed in #2704.

The thinking here would be to create a selector method that would allow me to impart logic as follows:

```
dbt run --exclude config.materialized:view,state:unmodified
```

This is simply the converse of the `state:modified` selector.

### Describe alternatives you've considered

The converse of the above statement is less elegant. To gather the same selection I'd have to do something more like:

```
dbt run -s config.materialized:table config.materialized:incremental state:modified
```

But this is not preferred as a new custom materialization would require refactoring numerous jobs. My intuition tells me that there may be other issues with this as well.

### Who will this benefit?

We make heavy use of late-binding views in Redshift. For projects getting into the thousands of models, rerunning unchanged views that are late-binding doesn't really provide any value and, over a large number of models, slows down our build times. Ideally, I'd be able to exclude re-running late-binding views from all of my jobs with the addition of an exclusion flag `--exclude config.materialized:view,state:unmodified`.

### Are you interested in contributing this feature?

Sure! If it's confirmed this makes sense to add.

**Comment by dbeatty10** [comment]
Thanks for opening @trouze !

At a high level, it makes sense to me that that there would be a collection of `state`s that follow Barbara Minto's [MECE principle](https://en.wikipedia.org/wiki/MECE_principle).

e.g., `state:unmodified` / `state:unmodified`
and `state:new` / `state:old`

We also have a [collection of subselectors](https://docs.getdbt.com/reference/node-selection/methods#the-state-method):
- `state:modified.body`
- `state:modified.configs`
- `state:modified.relation`
- `state:modified.persisted_descriptions`
- `state:modified.macros`
- `state:modified. contract`

Have you given any thought if `state:unmodified.{subselector}`s should be added as well?

**Comment by trouze** [comment]
In short, no. If I were to, there's probably two approaches:

1. I'd think through use cases of subselectors and determine which would benefit from being able to select the converse. I'm just not that familiar with the subselectors at this moment to determine if any/all would benefit here. OR
2. We could just take the principled stance that all selectors/subselectors should be MECE

I don't have the intuition here as to how much bigger a lift it'd be to add this to all subselectors versus only `modified` and `new`. Might need to lean on others here.

**Comment by trouze** [comment]
Dug into this a bit over the weekend to see what this might look like and was able to get a [working prototype](https://github.com/dbt-labs/dbt-core/compare/main...trouze:dbt-core:main) going.

**Comment by dbeatty10** [comment]
That's awesome @trouze! 🤩

@jtcohen6 It seems like adding the following state selectors to complement `state:modified` and `state:new` would be [relatively simple](https://github.com/dbt-labs/dbt-core/compare/main...trouze:dbt-core:main) and useful:
- `state:unmodified`
- `state:old`

It also seems like we could defer adding any new [subselectors](https://docs.getdbt.com/reference/node-selection/methods#the-state-method) until some later date (assuming we get a request for them).

How does this sound to you @jtcohen6 ? Any concerns with going this direction?

**Comment by trouze** [comment]
@dbeatty10 @jtcohen6 made some [small updates](https://github.com/dbt-labs/dbt-core/compare/main...trouze:dbt-core:ct-2551-state-selection-mece) here to simplify. If we're comfortable with this then I'll go ahead and add some tests and open a PR.

**Comment by dbeatty10** [comment]
That turned out quite nicely @trouze 🤩 

I'm comfortable with this, and it would be great if you add some tests and open a PR.

### Summary of decision
Adding the following state selectors to complement `state:modified` and `state:new` should be useful and has an elegant proposed implementation:
- `state:unmodified`
- `state:old`

For now, we will defer adding any new [subselectors](https://docs.getdbt.com/reference/node-selection/methods#the-state-method) unless we get a request for them or otherwise determine that they would be useful enough.
