### ISSUE TITLE
[CT-2556] [Bug] urllib3 upgraded to 2.0, dropping support for OpenSSL < 1.1.1, breaking requests 2.29.0

### ISSUE THREAD

**Issue by mikealfare** [dbt-labs/dbt-core#7573]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Running functional tests produces an error when trying to import requests:
```
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168
```

### Expected Behavior

Functional tests run as expected.

### Steps To Reproduce

1. Rebuild your venv to pick up the latest versions of dependencies
2. Run functional tests

### Relevant log output

```shell
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168
```
```


### Environment

```markdown
- OS: any
- Python: any
- dbt: any that use urllib3 (likely via having no cap on urllib3)
```

### Additional Context

Related issues:
https://github.com/urllib3/urllib3/issues/2168
https://github.com/psf/requests/issues/6432
https://github.com/urllib3/urllib3/releases/tag/2.0.0

Proposed Solution:
We need to pin urllib3 to 1.x

**Comment by garfieldthesam** [comment]
How I fixed this issue on MacOS Ventura 13:

`python3 -m pip install --force-reinstall -v "urllib3~=1.0"`

**Comment by adamroyjones** [comment]
@mikealfare: As OpenSSL 1.1.1 has now reached [the end of its life (as of 2023-09-11)](https://www.openssl.org/blog/blog/2023/09/11/eol-111/), are there plans to unpin urllib3?
