### ISSUE TITLE
[CT-2559] [Feature] Remove unused `check_new` method

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#7586]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

It looks like `check_new` is unused after being removed in an earlier PR. If so, then could we remove `check_new` altogether?

https://github.com/dbt-labs/dbt-core/blob/43d949c5cc46da2e7c893f51fe4a35dc1486e3ac/core/dbt/graph/selector_methods.py#L539-L540

I didn't do a `git grep "check_new"` in dbt-core or any adapters, but didn't see any usage here:
https://github.com/search?q=repo%3Adbt-labs%2Fdbt-core+check_new&type=code

### Describe alternatives you've considered

We can leave dead code like this without creating problems, but always nice to do some spring cleaning.

### Who will this benefit?

Anyone reading or developing this portion of the code base.

**Comment by shivu2002a** [comment]
Hi @dbeatty10 ,
Can I take up this issue please? This method is to be removed, right?

**Comment by dbeatty10** [comment]
Yep you got it @shivu2002a 👍 Thanks for jumping in ❤️ 

During code review of your pull request, you and the reviewer can confirm/deny if it is safe to fully remove it. I think the answer is "yes", but I didn't try it out myself.

One other thing to note when you open a PR -- here are things I see forgotten most often for first-time contributors:
- [Running `changie new`](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-or-modifying-a-changelog-entry) and committing the file it creates
- Signing the [CLA](https://docs.getdbt.com/community/resources/contributor-license-agreements)

**Comment by shivu2002a** [comment]
@dbeatty10 Sure thing. I'll try submitting a pr. Thanks 😊
