### ISSUE TITLE
[CT-2568] Script to create jsonschemas includes unneeded definitions in the schema

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#7604]
When running the scripts/collect-artifact-schema.py script, if WriteableManifest shows up before the other schema classes in the list, the subsequent schemas include unnecessary definitions (such as ManifestMetadata, etc). It looks like the "definitions" in hologram are being persisted across calls to the jsons_schema method.

This was encountered in #7590. Another ticket was opened to specify a single artifact to build: #7599.

**Comment by emmyoop** [comment]
Closing in favor of #6776
