### ISSUE TITLE
[CT-2582] [Bug] Having issues installing some packages with dbt deps

### ISSUE THREAD

**Issue by antoniofranciscoandrade** [dbt-labs/dbt-core#7627]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The majority of packages are failing to install when running `dbt deps` (see log output for error). So far I've only had success installing `datalakehouse/dlh_quickbooks`, while having the same error message shown for the following:

```
fivetran/amazon_ads
Fleetio/dbt_segment
brooklyn-data/dbt_artifacts
calogica/dbt_date
cerebriumai/airbyte_facebook_ads
data-mie/dbt_profiler
cerebriumai/airbyte_facebook_ads
```

### Expected Behavior

Packages should be able to install.

### Steps To Reproduce

1. dbt init <project name>
2. create packages.yml and add fivetran/quickbooks dependency
3. run dbt deps

### Relevant log output

```shell
03:33:17  Running with dbt=1.5.0
03:33:24  Encountered an error:
External connection exception occurred: Unterminated string starting at: line 1 column 10213 (char 10212)
```

### Environment

```markdown
- OS: macOS monterey 12.3.1
- Python: 3.9.6
- dbt: 1.5.0
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

I'm not under any proxy.

**Comment by dbeatty10** [comment]
Thanks for reaching out @antoniofranciscoandrade!

Can you share the contents of your `packages.yml` file(s) that you are using?

**Comment by antoniofranciscoandrade** [comment]
Sure! 

```
packages:
  - package: fivetran/quickbooks
    version: 0.9.0
```

**Comment by antoniofranciscoandrade** [comment]
Update: I downgraded my python version to 3.7.13 and it worked!

 Happy to help if any further debugging is needed., but feel free to close this issue since the problem is solved.
