### ISSUE TITLE
[Bug] [WinError 3] The system cannot find the path specified after upgrade from dbt 1.3.0 to 1.5.0

### ISSUE THREAD

**Issue by pciepiela95** [dbt-labs/dbt-core#7658]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After running any data model I am getting an error that one of the models cannot be found.

[WinError 3] The system cannot find the path specified:` 'C:\\<REPO-PATH>\\common\\dbt\../../projects/PROJECT-A/dbt/models\\<MODEL-PATH>'`
(please notice mixed backslashes \\ and forward slashes/)

The command works when I change relative model path to the absolute one in dbt_project.yml:
`"../../projects/PROJECT-1"`
->
`C:/<REPO-PATH>/projects/PROJECT-1`

Problem is that other model-paths in dbt project are also configured as relative paths and this error is visible only for this
one catalog. Other projects/models are working even tough they are in the same structure in repository as above one.

- we have `dbt` monoproject within monorepo
- `dbt_project.yml` is placed in `/common/dbt` directory
- all model paths defined in `dbt_project.yml` look this way:
  ```yaml
  model-paths:
    - "../../common/dbt/models"
    - "../../projects/PROJECT-1/dbt/models"
    - "../../projects/PROJECT-2/dbt/models"
    - "../../projects/PROJECT-3/dbt/models"
    - "../../projects/PROJECT-4/dbt/models"
    - "../../projects/PROJECT-5/dbt/models"
  ```
- we ran `dbt clean` and verified there's no `target` directory with past artifacts anyway

This error appears only when running dbt core 
  - installed: 1.5.0
 Plugins:
  - postgres: 1.5.0 - Up to date!
  - redshift: 1.5.1 - Up to date!
  On version 1.3.0 the issue was not visible and I was able to run models

### Expected Behavior

dbt compile and dbt run of models can be executed without an error

### Steps To Reproduce

1. With dbt 1.3.0 I run dbt run -s [model name]
2. Model is compiling and running as expected
3. After upgrading the version of dbt to dbt 1.5.0 the same command returns an error
[WinError 3] The system cannot find the path specified:[path to model]

even tough configuration in project remained the same

4. the models are running when changing this one specific path in dbt_project from relative path to absolute path 

### Environment

```markdown
- OS:Microsoft Windows [Version 10.0.19044.2846]
- Python:3.10.9
- dbt:1.5.0
- git bash
```

### Which database adapter are you using with dbt?

redshift

**Comment by dbeatty10** [comment]
Thanks for opening this @pciepiela95 !

The mixed backslashes `\` and forward slashes `/` looks like is is mixing Windows file paths with Unix file paths.

Out of curiosity, what happens if you do something like this?
```
model-paths:
  - "..\..\common\dbt\models"
  - "..\..\projects\PROJECT-1\dbt\models"
  - "..\..\projects\PROJECT-2\dbt\models"
```

Unsurprisingly, I wasn't able to reproduce this using a Mac, but I'll provide the simple setup I used below anyways.

This _might_ (or might not!) have a solution similar to this one: https://github.com/dbt-labs/dbt-core/pull/7628


<details>
<summary>

### Reprex
</summary>

```
.
├── common
│   └── dbt
│       ├── dbt_project.yml
│       ├── models
│       │   └── my_model.sql
│       └── profiles.yml
└── projects
    ├── PROJECT-1
    │   └── dbt
    │       └── models
    │           └── my_model_1.sql
    └── PROJECT-2
        └── dbt
            └── models
                └── my_model_2.sql
```

`common/dbt/dbt_project.yml`
```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "sandcastle"

model-paths:
  - "../../common/dbt/models"
  - "../../projects/PROJECT-1/dbt/models"
  - "../../projects/PROJECT-2/dbt/models"
```

`common/dbt/models/my_model.sql`
```sql
select 0 as id
```

`projects/PROJECT-1/dbt/models/my_model_1.sql`
```sql
select 1 as id
```

`projects/PROJECT-1/dbt/models/my_model_2.sql`
```sql
select 2 as id
```

```shell
dbt ls --project-dir common/dbt
```

or
```shell
cd common/dbt
dbt ls
```

</details>
