### ISSUE TITLE
[Bug] dbt init not working

### ISSUE THREAD

**Issue by romanzdk** [dbt-labs/dbt-core#7659]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I run `dbt init` (https://docs.getdbt.com/reference/commands/init) or `dbt init jaffle_shop` (https://docs.getdbt.com/docs/quickstarts/dbt-core/manual-install#create-a-project) I get

```
Usage: dbt init [OPTIONS] [PROJECT_NAME]
Try 'dbt init -h' for help.
Error: Invalid value for '--profiles-dir': Path '/Users/username/.dbt' does not exist.
```

### Expected Behavior

created initial dbt project

### Steps To Reproduce

`pip install dbt-core`
`dbt init`

### Environment

```markdown
- OS: macOS 12.6
- Python: 3.10.0
- dbt: 1.5.0
```

**Comment by dbeatty10** [comment]
Thank you for reporting this @romanzdk!

This looks the same as https://github.com/dbt-labs/dbt-core/issues/7511, so I'm going to close this. Please let me know if you think this is distinct from that one.
