### ISSUE TITLE
[Bug] Integration test gives an error for the JST timezone

### ISSUE THREAD

**Issue by d-kaneshiro** [dbt-labs/dbt-core#7664]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Error at `dbt-core/tests/functional/simple_snapshot/test_hard_delete_snapshot.py:97` when running `make integration`.

### Expected Behavior

Integration tests complete successfully.

### Steps To Reproduce

I forked the repository and built the necessary environment according to “[CONTRIBUTING.md](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md)”.
Below is the command I executed.
1. Build venv environment
- python3 -m venv env
- source env/bin/activate
- pip install --upgrade pip
2. Build dbt environment
- make dev
3. Build DB environment
- make setup-db
4. Run unit tests
- make test
5. Run integration tests
- make integration

In addition, in “~/.dbt/profiles.yml”,
```
default:
   target: dev
   outputs:
     devs:
       type: postgres
       host: localhost
       user: root
       password: password
       port: 5432
       dbname: postgres
       schema: public
       threads: 4
```
### Relevant log output

```shell
>           assert result[-1].replace(tzinfo=currenttz()) >= invalidated_snapshot_datetime
E           AssertionError: assert datetime.datetime(2023, 5, 15, 7, 36, 0, 679815, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400), 'JST')) >= datetime.datetime(2023, 5, 15, 7, 36, 0, 58485, tzinfo=<UTC>)
E            +  where datetime.datetime(2023, 5, 15, 7, 36, 0, 679815, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400), 'JST')) = <built-in method replace of datetime.datetime object at 0x11a20f2a0>(tzinfo=datetime.timezone(datetime.timedelta(seconds=32400), 'JST'))
E            +    where <built-in method replace of datetime.datetime object at 0x11a20f2a0> = datetime.datetime(2023, 5, 15, 7, 36, 0, 679815).replace
E            +    and   datetime.timezone(datetime.timedelta(seconds=32400), 'JST') = currenttz()
```

### Environment

```markdown
- OS:macOS Catalina 10.15.7
- Python:3.10.5
- dbt:1.6.0-b1
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Thanks for looking into that @d-kaneshiro ! 🏅

I just wanted to gain an understanding of what was causing the issue. Your experiment gives some evidence that this integration test isn't working for timezones with a positive UTC offset, but does work for those with a negative UTC offset.

Unifying to UTC in your pull request might be the solution -- I'll comment further within your pull request.
