### ISSUE TITLE
Compilation Error in rpc request

### ISSUE THREAD

**Issue by JoniBeaulieu** [dbt-labs/dbt-core#7680]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We are seeing an error message come up randomly when we create a new source. 
Compilation Error in rpc request (from remote system) Rpc 'rpc.dhcg_analytics.request' (from remote system) depends on a source named 'MY_SCHEMA.MY_TABLE' which was not found

The Yml file for the source looks like this: 
version: 2
sources:
  - name: MY_SCHEMA
    database: MY_DATABASE
    schema: MY_SCHEMA
    tables:
      - name: MY_TABLE 

I create the staging sql in the staging/myschema folder that looks like this 

with 
    test as (
        select * from 
        {{ source('MY_SCHEMA', 'MY_TABLE')}}
    )

    select * from test

I can see the drop-down selections when I create the sql file. 

However, when I go to run it I get the error above. The logs just say "dbt runtime exception." However, the build is successful, if I do not have another script that needs to call this one.

### Expected Behavior

The expected behavior is to find the table in snowflake, and preview the data and be able to build the lineage.

### Steps To Reproduce

See the current behavior. 

### Environment

```markdown
Snowflake
DBT 1.0.0
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

This has happened two times thus far. But inbetween we have been able to add new sources without an issue. This seems to be random, but unsure why it is happening.

**Comment by dbeatty10** [comment]
Thanks for reaching out @JoniBeaulieu !

Are you using dbt Cloud, by any chance?

If you are a dbt Cloud user, please reach out to us by using the speech bubble (💬) in the dbt Cloud interface or at [support@getdbt.com](mailto:support@getdbt.com)

**Comment by balkrushnapatil** [comment]
I am also facing a similar issue. Do we have an update on this issue?

**Comment by JoniBeaulieu** [comment]
Hi @balkrushapatil, after working with DBT Support, we realized the solution was to upgrade to version 1.5. That was the latest version at the time. We were a few upgrades behind. Hope this helps.

**Comment by dbeatty10** [comment]
@balkrushnapatil if you are still experiencing this issue after upgrading to dbt-core 1.6, just let us know and we can take another look.

**Comment by balkrushnapatil** [comment]
> @balkrushnapatil if you are still experiencing this issue after upgrading to dbt-core 1.6, just let us know and we can take another look.

First and foremost, I would like to express my sincere gratitude to @dbeatty10  for promptly replying.

We are planning to upgrade dbt-core to version 1.6.3. Since it is completely random, we will continue to closely monitor the jobs. If any problems occur. We will certainly inform you without fail.

Thank You!
