### ISSUE TITLE
[CT-2594] [Regression] WarnErrorOptions in invocation_args_dict is not JSON serialisable 

### ISSUE THREAD

**Issue by jared-rimmer** [dbt-labs/dbt-core#7694]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

- In dbt 1.5.0 the value for the key `warn_error_options`  in the `invocation_arg_dict` object is a Python object which looks like `"warn_error_options": WarnErrorOptions(include=[], exclude=[]),`

### Expected Behavior

- In dbt 1.4.x and earlier the value for the key `warn_error_options` in the `invocation_arg_dict` object was a string of a dict object which looks like `"warn_error_options\": {\"exclude\":[],\"include\":[]}`

### Steps To Reproduce

1. Invoke dbt in 1.4.x with [the warn options flag ](https://github.com/dbt-labs/docs.getdbt.com/pull/2691/files?short_path=5282227#diff-52822271cc0a418238ec087115df4ef8b81bf2c5d5b2eb520efad49e1c62cb95)
2. Do the same in 1.5.0
3. Observe the difference `invocation_arg_dict` object

### Environment

```markdown
- OS: Mac
- Python: 3.8
- dbt: 1.5.0
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

All of them

**Comment by jtcohen6** [comment]
Thanks @jared-rimmer! This is similar to:
- https://github.com/dbt-labs/dbt-core/issues/7495.

I agree that we should serialize `WarnErrorOptions` somehow—whether to a real Python dictionary, or a JSON string—before exposing it to the Jinja context. The right spot to do that is probably in `args_to_dict`:

https://github.com/dbt-labs/dbt-core/blob/45d614533f0c7de81e20488c75c707262c9312e1/core/dbt/utils.py#L614-L656

Is that something you'd be interested in poking around with? Otherwise, we'll try to include this for a v1.5 patch, but I view it as lower priority relative to other bugs/regressions.

**Comment by QMalcolm** [comment]
Interesting the `WarnErrorOptions` class already uses the `dbtClassMixin` 🤔 Specifically [WarnErrorOptions inherits IncludeExclude](https://github.com/dbt-labs/dbt-core/blob/fb6c349677cd924d8013f46261620f89a13a7bfd/core/dbt/helper_types.py#L125) and [IncludeExclude inherits dbtClassMixin](https://github.com/dbt-labs/dbt-core/blob/fb6c349677cd924d8013f46261620f89a13a7bfd/core/dbt/helper_types.py#L93). So having `dbtClassMixin` as part of `WarnErrorOptions` doesn't resolve the issue. It appears to be more of an issue of dictifying nested objects.

**Comment by QMalcolm** [comment]
@jtcohen6 you said
> I agree that we should serialize WarnErrorOptions somehow
Does that mean we're not specifically aiming to give the exact previous output, but just that it is serialized in a more friendly way. I.e. it doesn't need to be `"warn_error_options\": {\"exclude\":[],\"include\":[]}` but could be `"warn_error_options": {"exclude": [], "include": []}`

@jared-rimmer how exactly are you going about inspecting the value of `invocation_arg_dict`? I'm trying to inspect the output of 1.4 to write a test for 1.5 and 1.6, but am finding it difficult to actually ensure the proper initial state is setup 🙃

**Comment by jtcohen6** [comment]
> I.e. it doesn't need to be `"warn_error_options\": {\"exclude\":[],\"include\":[]}` but could be `"warn_error_options": {"exclude": [], "include": []}`

I agree with this! Feels much more desirable to expose the information in this way
