### ISSUE TITLE
[CT-2602] [Bug] Encountered unknown tag 'break'

### ISSUE THREAD

**Issue by RichardHallgren** [dbt-labs/dbt-core#7708]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I get this issue when trying to run dbt build: 

09:11:32.564247 [error] [MainThread]: Encountered an error:
Compilation Error
Encountered unknown tag 'break'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
line 20
{%- break -%}

With dbt core 1.4.3 and dbt-sqlserver 1.4.3 i don't get the same with 1.3.1.

I think this is related to this file which containts break:

https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/models/table/columns_spec_ddl.sql

Specifically:

  {%- for sql_col in sql_columns -%}
    {%- set yaml_col = [] -%}
    {%- for this_col in yaml_columns -%}
      {%- if this_col['name'] == sql_col['name'] -%}
        {%- do yaml_col.append(this_col) -%}
        {%- break -%}
      {%- endif -%}
    {%- endfor -%}

When I do a search I see that break is not supported in Jinja2, but there seems to be somekind of extension to jinja to allow break? Is there something wrong with my environment?

https://stackoverflow.com/questions/22150273/how-can-i-break-a-for-loop-in-jinja2

### Expected Behavior

In dbt 1.3.1 I can build the same project without an issue, however the file that I believe causes the problem doesn't exist in that version.

### Steps To Reproduce

1. dbt-core with dbt-sqlserver 1.4.3
2. dbt build

### Relevant log output

```shell
09:11:32.564247 [error] [MainThread]: Encountered an error:
Compilation Error
Encountered unknown tag 'break'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
line 20
{%- break -%}
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.9.5
- dbt: 1.4.3
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

dbt-sqlserver 1.4.3

**Comment by RichardHallgren** [comment]
I added this to my local jinja.py file and then it worked.

![image](https://github.com/dbt-labs/dbt-core/assets/55056634/c608b6d1-ad4d-4085-9a48-08bf82ceb313)

**Comment by gshank** [comment]
You must be mixing dbt Core 1.5 code and an earlier version. That extension was added in dbt Core 1.5 in core/dbt/clients/jinja.py at the same time that the columns_spec_ddl.sql file used the "break" command. It looks like your columns_spec_ddl.sql and core/dbt/clients/jinja.py file are from different versions.

**Comment by RichardHallgren** [comment]
Yes that's probably the case, I installed dbt-sqlserver before and there was a bug I think for some reason it installed the latest dbt-core, and I had to downgrade to the same version 1.4.3, maybe when I did the downgrade with 

pip install --upgrade dbt-core==1.4.3

something didn't quite work out.
