### ISSUE TITLE
[CT-2606] [Bug] Contract enforcement checks do not sent SQL header

### ISSUE THREAD

**Issue by elyobo** [dbt-labs/dbt-core#7714]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Turning on the contract enforcement sends a `where false limit 0` query that does not include the SQL header. This can cause failures, e.g. when the sql header is used to declare a variable or temporary function which is referenced in the model query.

### Expected Behavior

The sql header should be sent.

### Steps To Reproduce

With dbt 1.5 and dbt-bigquery 1.5.1

A simple model with contract enforcement enabled

```yaml
version: 2
models:
  - name: demo
    contract:
      enforced: true
    columns:
      - name: demo_text
```

```sql
{% call set_sql_header(config) %}
DECLARE DEMO STRING DEFAULT 'hello world';
{% endcall %}

SELECT DEMO AS demo_text
```

results in a query being sent like this, which fails because the variable declared in the header does not exist

```sql

    select * from (
        

SELECT DEMO AS demo_text
    ) as __dbt_sbq
    where false
    limit 0
```

The model runs successfully without contract enforcement enabled.

Incidentally, the location of the failed SQL is not reported as with regular model / test failures, but the BQ adapter does drop in a link to the failed job in BQ's UI.

### Environment

```markdown
- OS: macOS Ventura
- Python: 3.9
- dbt: 1.5
- dbt-bigquery: 1.5.1
```

### Which database adapter are you using with dbt?

bigquery

**Comment by MichelleArk** [comment]
Thank you for opening and providing a reproduction case @elyobo! I've added it to https://github.com/dbt-labs/dbt-core/issues/7372 for tracking.

**Comment by elyobo** [comment]
Thanks @MichelleArk!
