### ISSUE TITLE
[CT-2607] [Bug] Invalid YAML dictionary error for warn-error-options references the `--vars` flag

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#7730]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Run `dbt --warn-error-options '' run -s doesntexist`
The error message is `  The --vars argument must be a YAML dictionary, but was of type 'NoneType'`- talking about the `--vars` argument instead of `--warn-error-options`. Looks like a lil copy-paste mistake. 

### Expected Behavior

The --warn-error-options argument must be a YAML dictionary, but was of type 'NoneType

### Steps To Reproduce

Above

### Environment

```markdown
- OS: MacOS
- Python: Yes
- dbt: 1.5.0
```

**Comment by jtcohen6** [comment]
Thanks @joellabes!

@MichelleArk beat us to it :)
