### ISSUE TITLE
[CT-2611] [Feature] support for `access` selection syntax 

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-core#7738]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As a dbt user, I want to be able to select my models according to their `access` property like I can with most (if not all!) other properties and configs. This is helpful if I need to operate on subsets of groups depending on their access

Sample usage:

```bash
# which members of my finance group are public?
$ dbt ls group:finance,access:public
```

### Describe alternatives you've considered

doing post-command filtering, going for a long walk outside

### Who will this benefit?

folks who want to operate or interact with resources using their access as a selection criteria. specifically, this simplifies some of the code we're writing in dbt-meshify! 

### Are you interested in contributing this feature?

yes

**Comment by jtcohen6** [comment]
Thanks @dave-connors-3 :)
