### ISSUE TITLE
[CT-2612] [Feature] Add Contract to Seeds

### ISSUE THREAD

**Issue by sanromeo** [dbt-labs/dbt-core#7742]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The proposed feature aims to enhance the functionality of Contract released in dbt Core 1.5 by introducing contracts to seeds. This feature will allow users to define contracts for SEED data, ensuring that the data adheres to specific rules or conditions before it is loaded into the database.

The implementation of this feature will involve adding a new contract attribute to the seed configuration in the dbt project file. Users will be able to define their contracts using this attribute, and dbt will validate the seed data against these contracts during the seed operation.

### Describe alternatives you've considered

```yaml
---
version: 2

seeds:
  - name: seed_name
    config:
      schema: seed_schema
      tags: seed
      column_types:
        seed_id: int
        seed_name: varchar(255)
      contract:
        enforced: true
```

Now that config returns error:
```
10:48:52  Completed with 1 error and 0 warnings:
10:48:52  
10:48:52  Compilation Error in seed seed_name (seeds/ref_sources/seed_name.csv)
10:48:52    expected string or bytes-like object, got 'Undefined'
10:48:52    
10:48:52    > in macro athena__get_empty_schema_sql (macros/adapters/columns.sql)
10:48:52    > called by macro get_empty_schema_sql (macros/adapters/columns.sql)
10:48:52    > called by macro assert_columns_equivalent (macros/materializations/models/table/columns_spec_ddl.sql)
10:48:52    > called by macro default__get_assert_columns_equivalent (macros/materializations/models/table/columns_spec_ddl.sql)
10:48:52    > called by macro get_assert_columns_equivalent (macros/materializations/models/table/columns_spec_ddl.sql)
10:48:52    > called by macro athena__create_table_as (macros/materializations/models/table/create_table_as.sql)
10:48:52    > called by macro create_table_as (macros/materializations/models/table/create_table_as.sql)
10:48:52    > called by macro athena__create_csv_table (macros/materializations/seeds/helpers.sql)
10:48:52    > called by macro create_csv_table (macros/materializations/seeds/helpers.sql)
10:48:52    > called by macro materialization_seed_default (macros/materializations/seeds/seed.sql)
10:48:52    > called by seed seed_name (seeds/ref_sources/seed_name.csv)
10:48:52  
```

### Who will this benefit?

Same `contract` functionality as we have for models now

**Comment by dbeatty10** [comment]
Thanks for raising this proposal @sanromeo !

Is there something about dbt [model contracts](https://docs.getdbt.com/docs/collaborate/govern/model-contracts) that you are hoping for dbt seeds that wouldn't be covered by using [`column_types`](https://docs.getdbt.com/reference/resource-configs/column_types) with those seeds?

**Comment by sanromeo** [comment]
@dbeatty10, thanks for your answer!

I hadn't noticed that I needed to specify data_type when using the contract. Now, it works well when I set data_type in the definition for seeds, as I've written below:

```yaml
seeds:
  - name: seed_name
    config:
      schema: seed_schema
      tags: seed
      column_types:
        seed_id: int
        seed_name: varchar(255)
      contract:
        enforced: true
    columns:
      - name: seed_id
        data_type: integer
      - name: seed_name
        data_type: varchar    
```
It works with `column_types` and without them. As written in documentation for [contracts](https://docs.getdbt.com/docs/collaborate/govern/model-contracts#how-to-define-a-contract):
>When enforced, your contract *must* include every column's `name` and `data_type` (where `data_type` matches one that your data platform understands).

I will be more attentive next time, thank you for your help! 🔥 ❤️

**Comment by dbeatty10** [comment]
You are very welcome @sanromeo ! 🔥 ❤️ 🙌

I'm going to close this, but please reach out if there's any other follow-up needed here.
