### ISSUE TITLE
[CT-2623] [Bug] Pre_hook calling procedure breaks mysql connection

### ISSUE THREAD

**Issue by Randyhall91** [dbt-labs/dbt-core#7757]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The issue I'm having is, after creating a procedure in mysql and then calling it in a pre_hook the rest of the dbt file fails with the message " mysql adapter: MySQL error: MySQL Connection not available." The pre_hook runs successfully but anything after it resolves crashes with mysql connection failure.

### Expected Behavior

I expect the pre_hook that uses a stored procedure to fire and the table to materialize as normal. 

### Steps To Reproduce

1. Created stored procedure in mysql. Testing with a test procedure shows it breaks regardless of procedures action.
DELIMITER //
CREATE PROCEDURE test(
  IN table_name VARCHAR(255),
)
BEGIN
  select(table_name);
END//

DELIMITER ;

2.  Use pre_hook to call the stored procedure
{{ config(
    pre_hook=[
      "use {{ var('schema') }};",
      "call test('work_order_notes');"
      ],
)}}
3. dbt run

### Relevant log output

```shell
19:22:49.053883 [debug] [Thread-1  ]: mysql adapter: MySQL error: MySQL Connection not available.
19:22:49.053883 [debug] [Thread-1  ]: On model.data.work_orders: ROLLBACK
19:22:49.053883 [debug] [Thread-1  ]: Failed to rollback 'model.data.work_orders'
19:22:49.054926 [debug] [Thread-1  ]: finished collecting timing info
19:22:49.054926 [debug] [Thread-1  ]: On model.data.work_orders: Close
19:22:49.055938 [debug] [Thread-1  ]: Database Error in model work_orders (models\marts\work_orders.sql)
  MySQL Connection not available.
```

### Environment

```markdown
- OS: Windows 11
- Python: 3.9
- dbt-core: 1.1.5
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

mysql: 1.1.0

I've tested this stored procedure in mysql workbench without any issues and this part of the code works fine but when added to the pre_hook in dbt the following table fails to be created. 

Without the pre_hook the table generates with no issues.

**Comment by dbeatty10** [comment]
Thanks for reaching out @Randyhall91 !

I don't think this is an issue with dbt-core, so I'm going to close it in favor of https://github.com/dbeatty10/dbt-mysql/issues/148 instead.

**Comment by Randyhall91** [comment]
> Thanks for reaching out @Randyhall91 !
> 
> I don't think this is an issue with dbt-core, so I'm going to close it in favor of [dbeatty10/dbt-mysql#148](https://github.com/dbeatty10/dbt-mysql/issues/148) instead.

Thank you.
