### ISSUE TITLE
[CT-2629] [Regression] 1.5 no longer supports --log-path CLI argument

### ISSUE THREAD

**Issue by Gwildor** [dbt-labs/dbt-core#7764]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

We have been using `--log-path` (and `--target-path`) in dbt 1.4. We are upgrading to 1.5, but we get the error that there is no `--log-path` option.

This is especially confusing because 1.5 deprecates log-path and target-path from dbt_project.yml, and the upgrade notes for 1.5 specifically mention using the CLI or environment variables instead.

### Expected/Previous Behavior

We expect all subcommands that support `--log-path` in 1.4 to also support them in 1.5, or have its deprecation documented and a warning raised.

### Steps To Reproduce

1. Activate dbt 1.4
2. Run `dbt run --log-path foo`
3. Activate dbt 1.5
4. Run `dbt run --log-path foo`

### Relevant log output

```shell
$ dbt --version
Core:
  - installed: 1.4.6
  - latest:    1.5.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.4.3 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
$ dbt run -h
  --target-path TARGET_PATH
                        Configure the 'target-path'. Only applies this setting for the current run. Overrides the 'DBT_TARGET_PATH' if it is set.
  --log-path LOG_PATH   Configure the 'log-path'. Only applies this setting for the current run. Overrides the 'DBT_LOG_PATH' if it is set.
$ dbt --debug run --log-path foo


============================== 2023-06-02 09:01:37.805433 | 9f38e3e9-e876-4092-9b2b-5b9b9570e436 ==============================
09:01:37.805433 [info ] [MainThread]: Running with dbt=1.4.6
09:01:37.808927 [debug] [MainThread]: running dbt with arguments {'debug': True, 'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '<path to my dbt project>', 'send_anonymous_usage_stats': True, 'quiet': False, 'no_print': False, 'cache_selected_only': False, 'log_path': 'foo', 'which': 'run', 'rpc_method': 'run', 'indirect_selection': 'eager'}
$ . venv-dbt-1.5/bin/activate
$ dbt --version
Core:
  - installed: 1.5.1
  - latest:    1.5.1 - Up to date!

Plugins:
  - bigquery: 1.5.1 - Up to date!
$ dbt run -h
  --target-path PATH              Configure the 'target-path'. Only applies
                                  this setting for the current run. Overrides
                                  the 'DBT_TARGET_PATH' if it is set.
$ dbt --debug run --log-path foo
Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.

Error: No such option: --log-path Did you mean --target-path?
```

### Environment

```markdown
- OS: macOS Big Sur 11.7.7
- Python: 3.11.2
- dbt (working version): 1.4.6
- dbt (regression version): 1.5, 1.5.1 and 1.6.0b2
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

I don't know all the subcommands that supported setting the log path. We use it for run, test, compile, seed, build and docs generate. I've checked the help output of the run, test, and compile subcommands with the different versions of dbt-core and all have `--log-path` in 1.4 but it's gone in 1.5.

I've tried with 1.6.0b2 as well, but that version also doesn't support it and gives the same output as 1.5.

### Workaround
Setting the `DBT_LOG_PATH` environment variable works as expected:

```
$ DBT_LOG_PATH=foo dbt --debug run
09:34:33  Running with dbt=1.5.1
09:34:33  running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'True', 'profiles_dir': '<path to my dbt project>', 'log_path': '<path to my dbt project>/foo', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
```

**Comment by dbeatty10** [comment]
Thank you for reaching out @Gwildor !

Could you try the following instead?
```shell
dbt --log-path foo run
```

### Explanation
Starting in 1.5, some options that could previously be specified before a sub-command can now only be specified afterward. For example, `dbt --profiles-dir . run` isn't valid anymore, and instead, you need to use `dbt run --profiles-dir .`

On the other hand, some options that could be previously specified _after_ a sub-command can now only be specified before. `--log-path` is one of those cases, and we should update that in our docs in these locations:
- https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.5
- https://docs.getdbt.com/reference/project-configs/log-path

I've opened a relevant issue to update our docs here:
- https://github.com/dbt-labs/docs.getdbt.com/issues/3470

**Comment by Gwildor** [comment]
Hi @dbeatty10 , thanks for the quick response.

Moving the argument to before the subcommand indeed works. I feel a bit silly I have not tried that myself before! I've tried with run, compile and test and they all work as expected.

I understand the change and I think it is a good one, as indeed some arguments are related to how dbt operates in general, and some are specific to the subcommands. I also read the discussions related to deprecating these settings from dbt_project.yml which led to this change.

I think this issue can be closed in favour of the issue you opened to document this in the two places you mentioned.

I have two closing remarks on this, though:

* This is still a breaking change as it requires changes to how other processes interact with dbt. Even though it is a minor one, I think this should have raised a warning first in 1.5, and then be fully moved in 1.6. Seeing as 1.5 is out already for a while and we're the first to report this (as far as I know), perhaps it is longer useful to still add backwards compatibility in a new patch release of 1.5, but I think that as dbt matures, going forward such migration steps would be necessary.
* I'm confused by the inconsistency with `--target-path`, because as I understand from the discussions the change related to log path and target path should be the same. So I think `--target-path` should also be only accepted before the subcommand. So this might require a change similar to what is done with the log path. I've tried this locally as well and indeed it is only accepted after the subcommand:

```
$ dbt --debug compile --target-path foo
08:45:25  Running with dbt=1.5.1
08:45:25  running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '<path to my dbt project>', 'log_path': '<path to my dbt project>/logs', 'fail_fast': 'False', 'debug': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'foo', 'send_anonymous_usage_stats': 'True'}
$ dbt --debug --target-path foo compile
Usage: dbt [OPTIONS] COMMAND [ARGS]...
Try 'dbt -h' for help.

Error: No such option: --target-path Did you mean --log-path?
```

Perhaps this issue should be reused to add a migration for target path to make it consistent with log path, or a new issue should be created? What do you think?

**Comment by dbeatty10** [comment]
Thank you for the thoughtful write-up and remarks @Gwildor 🧠

I'm going to respond to your two closing remarks in reverse order.

### Differences between `--log-path` and `--target-path`

I didn't actively participate in those particular discussions, so I'm guessing that the difference is that `--log-path` is _always_ relevant because every subcommand writes logs, whereas there are a few subcommands that don't write to the target directory (so `--target-path` would not be relevant to them).

e.g. none of the following subcommands allow the `--target-path` flag in dbt 1.5:
- [`dbt debug`](https://github.com/dbt-labs/dbt-core/blob/2d237828ae2a94f39e3ce8e4680a84ac22b6ead4/core/dbt/cli/main.py#L402)
- [`dbt deps`](https://github.com/dbt-labs/dbt-core/blob/2d237828ae2a94f39e3ce8e4680a84ac22b6ead4/core/dbt/cli/main.py#L428)
- [`dbt init`](https://github.com/dbt-labs/dbt-core/blob/2d237828ae2a94f39e3ce8e4680a84ac22b6ead4/core/dbt/cli/main.py#L448)

### Breaking changes

I'm sorry you were among the unlucky ones affected by this, and I agree whole-heartedly about everything you said about breaking changes and deprecation warnings prior to removal. 

Also agreed that as dbt matures, such migration steps are increasingly important. While this surely won't be the last time this happens, we are making our very best effort to keep these to a minimum.

### Next steps
To allow us to put our engineering efforts elsewhere, we're not planning to add backwards compatibility in a new patch release in this particular instance, and I'm going to close this in favor of docs updates in https://github.com/dbt-labs/docs.getdbt.com/issues/3470.

Despite our decision on this one,  your closing remarks about breaking changes remain valid.
