### ISSUE TITLE
[CT-2641] [Bug] Update link to adding a changelog entry

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#7788]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

To add a changelog entry, users need to install and use [changie](https://changie.dev/).

After [this](https://github.com/dbt-labs/dbt-core/pull/6374/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R204) change, there are two links that need to be updated:
1. With the table of contents for the contributing file
2. Within GitHub PR templates

[Here's](https://github.com/dbt-labs/dbt-core/blob/4dbc4a41c4642d258666946b634d0c20ee5db2cf/CONTRIBUTING.md#adding-or-modifying-a-changelog-entry) a current link to the relevant section of the contributing file.

Here is what the change was:
<img width="1042" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/03c6ca8c-7667-4345-a76c-b86819945024">

To fix the links, just update `#adding-a-changelog-entry` to `#adding-or-modifying-a-changelog-entry` anywhere the former appears in dbt-core (or elsewhere).

Someone should check if any adapters need a similar update.

### Expected Behavior

Clicking the link in the table of contents or PR template goes to the relevant section rather than just the beginning of the page.

### Steps To Reproduce

See above.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
Fixed by https://github.com/dbt-labs/dbt-core/pull/8017
