### ISSUE TITLE
[CT-2642] Redirect links to supported-data-platforms#adapter-installation

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#7789]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

❔ I don't yet know which page(s) would be most appropriate! 🤷

As a first pass, my intent here is document a recent mismatch so that we can figure out the best way to reconnect the dots. See "additional information" below for background context.

Primary impacted pages:
- https://docs.getdbt.com/docs/supported-data-platforms#adapter-installation
- https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli

Secondary related pages:
- https://docs.getdbt.com/docs/core/about-core-setup
- https://docs.getdbt.com/docs/core/installation
- https://docs.getdbt.com/docs/core/pip-install

### What part(s) of the page would you like to see updated?

@mirnawong1 Do you know if https://docs.getdbt.com/docs/supported-data-platforms#adapter-installation can be redirected to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli ?

Additionally and/or alternatively, the URL can be updated within dbt-core (see "additional information" below for context).

### Additional information

dbt-core logs the following [error message](https://github.com/dbt-labs/dbt-core/blob/7917bd5033f18a9accc262d2f242e4896d63068f/core/dbt/exceptions.py#L706
) when there is no adapter installed:
```
        msg = "No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/supported-data-platforms#adapter-installation"
```

After the [change in dbt-labs/docs.getdbt.com#3341](https://github.com/dbt-labs/docs.getdbt.com/pull/3341/files#diff-62079e0acc3b7a18922213102aa51ee81587898045332682f445453bace88142L43-L45), navigating to https://docs.getdbt.com/docs/supported-data-platforms#adapter-installation no longer goes to the intended location.

The [replacement location in dbt-labs/docs.getdbt.com#3341](https://github.com/dbt-labs/docs.getdbt.com/pull/3341/files#diff-b9b7ffa9310e2c9733168308a9450bc76974b6c20538cd721de4328f2bed14cbR16-R22) appears to be https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli

**Comment by dbeatty10** [comment]
@mirnawong1 I transferred this issue to dbt-core since that's where we are implementing the fix. Conveniently, it will allow you to reference this issue number when you create the changelog entry via changie 😎 

We can transfer it back to docs.getdbt.com if you deem that's better.

**Comment by mirnawong1** [comment]
resolved by pr https://github.com/dbt-labs/dbt-core/pull/7779 (forgot to link)
