### ISSUE TITLE
[SPIKE] [CT-2651] Add SemanticModels and Metrics to the DAG

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#7800]
We've added SemanticModel and Metric nodes to the manifest, but we haven't added them to the dag. We need to get them added to the dag so that visualizations based on the DAG include SemanticModels and Metrics.

Note that inclusion of the SemanticModel node in the dag should include tested support for partial parsing. After initial implementation, changes to the semantic_model section of schema files is not triggering partial (or any) re-parse, as it should.

**Comment by jtcohen6** [comment]
@QMalcolm Are you thinking about the visualization in `dbt-docs`? There & elsewhere, the main requirement from within `dbt-core` is that these resource types are included in `manifest.json` and the output of `dbt list`, with requisite information in their `depends_on.nodes`

**Comment by jtcohen6** [comment]
Should `metrics` and `semantic_models` land in the same top-level key (`semantic_nodes`) of the manifest + `graph` context var? I think maybe!
