### ISSUE TITLE
[CT-2652] Remove "Replaceable" class usage as much as possible

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#7802]
We pull in a Replaceable class which contains a "replace" method in a lot of our classes. This method is designed to replace the current object with a newly constructed one based on kwargs, and is in general not a very good idea. If we want to replace a current object it would be better to be a lot more explicit and intentional about what's happening.

Remove the usage Replaceable class where it's found in dbt-core, look for breakage, and determine if we really need to do this or could just update the current object.

**Comment by emmyoop** [comment]
Need to check that this isn't used in adapters as well.  Might be easier/better to move it to the dbtMixin class.

**Comment by MichelleArk** [comment]
Added this issue to the 'Stabilize External Interfaces' Epic under `Artifacts` since it plays nicely with our efforts to make the base artifact dataclasses 'plain old data'

**Comment by MichelleArk** [comment]
Updated this issue to be scoped to the _usage_ of Replaceable in dbt-core, since it is now defined in dbt-common. Its full deletion can be done as a separate issue in dbt-common, once dbt-adapters has gone through the same exercise.

**Comment by MichelleArk** [comment]
An initial pass was taken here: https://github.com/dbt-labs/dbt-core/pull/7844
