### ISSUE TITLE
[CT-2661] Release 1.5.2 (final) on June 22nd

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7814]

**Comment by jelstongreen** [comment]
Does this have an updated release date?

**Comment by jtcohen6** [comment]
@jelstongreen Good catch. We had more changes to go in, so we decided to put out a [second release candidate on June 16](https://github.com/dbt-labs/dbt-core/releases/tag/v1.5.2rc2). Assuming all goes well with RC testing, final release is planned for this week (June 22).

**Comment by jelstongreen** [comment]
Could the docker image for this be published please 🙏🏼 https://github.com/dbt-labs/dbt-core/pkgs/container/dbt-core
