### ISSUE TITLE
[CT-2666] Review Test Coverage of SemanticModels

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#7820]
During initial implementation of SemanticModels, we were moving quickly and did not add as much testing as is needed to fully verify functionality and prevent regressions. Let's use this issue to do that.

**Comment by jtcohen6** [comment]
This issue can be closed when:
- reviewed the set of capabilities (and tests) we've added since initial implementation
- created tickets for test cases that are still missing
- added to current sprint for execution, or put into backlog if lower-priority

**Comment by QMalcolm** [comment]
Semantic Model tests are a fair bit more sparse than Metric tests. We currently have 4 tests in `tests/functional/semantic_models/`. There are 2 additional which assert anything about `semantic_models` outside of `tests/functional/semantic_models`. Additionally, more testing needs to be done on the sub protocols of semantic models in [test_semantic_layer_nodes_satisfy_protocols.py](https://github.com/dbt-labs/dbt-core/blob/main/tests/unit/test_semantic_layer_nodes_satisfy_protocols.py).

- Test `SemanticModel.depends_on` is properly populated
- Test partial parsing in regards to SemanticModels (we have a [test_pp_semantic_models.py](https://github.com/dbt-labs/dbt-core/blob/main/tests/functional/partial_parsing/test_pp_semantic_models.py) but it's empty)
- Additional protocol satisfication tests
  - `SemanticModelDefaults`
  - `NodeRelation`
  - `MeasureAggregationParameters`
  - `DimensionTypeParams`
  - `DimensionValidityParams`
- Add tests to `test_contract_graph_parsed.py` specifically for semantic models

**Comment by QMalcolm** [comment]
Added #8139, #8140, #8141, and #8142. They are being tracked as part of the [Semantic Layer 1.7 Epic](https://github.com/dbt-labs/dbt-core/issues/8125)
