### ISSUE TITLE
[CT-2677] [BUG] Update SemanticModel definitions to match DSI 0.1.0dev3 protocols

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#7833]
In #7769 we added SemanticModel nodes in core. We started this work while pointed at [DSI 0.1.0dev2](https://pypi.org/project/dbt-semantic-interfaces/0.1.0.dev2/) but midway updated to depend on [DSI 0.1.0dev3](https://pypi.org/project/dbt-semantic-interfaces/0.1.0.dev3/). The main problem is that there are some protocol changes from DSI dev2 to DSI dev3, specifically `SemanticModel.dimensions[x].is_primary` has moved to `SemanticModel.defaults.agg_time_dimension`. Due to our serialization process, the semantic manifest artifact contains neither `is_primary` or `agg_time_dimension` 🙃 This issue was able to slip through because we don't check currently in core that our node implementations satisfy the protocol. Thus in solving this issue we should not only correct the nodes,  but also add tests to verify that our nodes satisfy the DSI protocols.

**Comment by emmyoop** [comment]
duplicates https://github.com/dbt-labs/dbt-core/issues/7827

**Comment by QMalcolm** [comment]
> duplicates #7827

I'm not sure this is so much a `duplicate` as it is just simply `related`. #7827 brings up that we need a way to ensure the nodes satisfy the protocol. This issue is specifically about fixing a bug which is that one of our nodes doesn't currently satisfy the protocol.
