### ISSUE TITLE
[CT-2686] Incorrectly set up tests in test_query_comment.py

### ISSUE THREAD

**Issue by damian3031** [dbt-labs/dbt-core#7845]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Tests in [test_query_comment.py](https://github.com/dbt-labs/dbt-core/blob/v1.6.0b3/tests/adapter/dbt/tests/adapter/query_comment/test_query_comment.py) are incorrectly set up. They are always passing, no matter if query comments are correctly implemented.

Assertions are placed in functions named `matches_comment`. As pytest run functions with names prefixed with `test`, these assertions are never checked.

The only thing which this tests are doing, is invoking [test_comments](https://github.com/dbt-labs/dbt-core/blob/v1.6.0b3/tests/adapter/dbt/tests/adapter/query_comment/test_query_comment.py#LL35C9-L35C22) function, which invokes [run_assert_comments](https://github.com/dbt-labs/dbt-core/blob/v1.6.0b3/tests/adapter/dbt/tests/adapter/query_comment/test_query_comment.py#LL31C9-L31C28), which invokes  [run_get_json](https://github.com/dbt-labs/dbt-core/blob/v1.6.0b3/tests/adapter/dbt/tests/adapter/query_comment/test_query_comment.py#LL22C9-L22C21), which is capturing logs. There are no assertions in any of above functions.

Additionally, I think that it would be better to check in dbt_run result query if query-comments were added, instead of checking in logs.

### Expected Behavior

Tests should detect bugs instead of always pass.

### Steps To Reproduce

1. In [test_query_comment.py](https://github.com/dbt-labs/dbt-core/blob/v1.6.0b3/tests/adapter/dbt/tests/adapter/query_comment/test_query_comment.py) Change any assertion from any `matches_comment`, to wrong assertion e.g. `assert 0 == 1`. Run tests, notice that they are still passing.
2. Add some wrong assertion in [test_comments](https://github.com/dbt-labs/dbt-core/blob/v1.6.0b3/tests/adapter/dbt/tests/adapter/query_comment/test_query_comment.py#L35) function. Run tests, notice that all tests from this file are failing

### Environment

```markdown
- OS: macOS
- Python: 3.10
- dbt: v1.6.0b3
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

I'm willing to create PR for this issue, as I already overwrote these tests in [dbt-trino](https://github.com/starburstdata/dbt-trino) to test `query-comments` properly on this adapter.

**Comment by dbeatty10** [comment]
Thank you for noticing and reporting this @damian3031 🏆 

That would be awesome if you are willing to raise a PR to fix this. When you open a PR for this, could you tag @dataders ? He won't be the final reviewer, but he can give initial feedback and help get it into our PR review queue.
