### ISSUE TITLE
[CT-2693] [Feature] Allow debug logs for dbt-databricks

### ISSUE THREAD

**Issue by susodapop** [dbt-labs/dbt-core#7859]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Add a mapping to enable `DEBUG` logs for log events from `databricks-sql-connector` similar to how `snowflake.connector` is handled today. This will assist in debuggin dbt-databricks issues.

### Describe alternatives you've considered

This must be set at the `dbt-core` level.

### Who will this benefit?

Anyone doing technical debugging of performance and behaviour of dbt-databricks.

### Are you interested in contributing this feature?

Yes. PR incoming.

**Comment by dbeatty10** [comment]
Sounds good @susodapop If you share a branch or open a PR with your proposed changes, then we can give it a look.

**Comment by jtcohen6** [comment]
The fact that this needs to be set within `dbt-core` doesn't feel right! And I'm not sure it actually has to be, versus doing it within the `dbt-databricks` adapter, if all we need to do is call `logging.getLogger(...).setLevel()`:

https://github.com/dbt-labs/dbt-core/blob/b947b2bc7e6513273398ea19fb1064ab8519f0be/core/dbt/logger.py#L500-L510

**Comment by susodapop** [comment]
I agree with your reasoning @jtcohen6. The reason to change it in dbt-core was primarily expediency, since this is where the log level is set for all the other connectors. I'm happy to move this into dbt-databricks assuming it will work that way.

**Comment by jtcohen6** [comment]
> assuming it will work that way

I don't know for sure. If you're able to give it a quick spin and try it out, I'd definitely prefer moving this platform-specific logic into the relevant adapter plugins. If it's too tricky to get working, we already have this (legacy) code in place; I won't stand in the way of adding a teensy bit more for expediency.

**Comment by colin-rogers-dbt** [comment]
Ran into this same problem for dbt-snowflake so figured we could use a more general solution.
