### ISSUE TITLE
[CT-2702] [Bug] `--selector` intersection not working as indicated in docs

### ISSUE THREAD

**Issue by nib-potato** [dbt-labs/dbt-core#7871]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The docs for `--selector` mentioned [here](https://docs.getdbt.com/reference/node-selection/set-operators) seem to indicate that we can intersect with selectors like below:

```sh
--selector shitty_selector_1,crappy_selector_2
```

But dbt seems to try to interpret this as one single ugly selector returning something like:

```sh
dbt run --selector shitty_selector_1,crappy_selector_2
07:32:41  Running with dbt=1.0.6
07:32:51  Found 873 models, 1061 tests, 0 snapshots, 4 analyses, 540 macros, 5 operations, 4 seed files, 265 sources, 0 exposures, 0 metrics
07:32:52  Encountered an error:
Runtime Error
  Could not find selector named shitty_selector_1,crappy_selector_2, expected one of ['x', 'y',... 'shitty_selector_1', 'crappy_selector_2']
```

### Expected Behavior

I would expect it to appropriately intersect the selectors as indicated in [the docs](https://docs.getdbt.com/reference/node-selection/set-operators) 

### Steps To Reproduce

1. Try to run variant of `--selector shitty_selector_1,crappy_selector_2` in `dbt-core == 1.0.6`

### Relevant log output

```shell
dbt run --selector shitty_selector_1,crappy_selector_2
07:32:41  Running with dbt=1.0.6
07:32:51  Found 873 models, 1061 tests, 0 snapshots, 4 analyses, 540 macros, 5 operations, 4 seed files, 265 sources, 0 exposures, 0 metrics
07:32:52  Encountered an error:
Runtime Error
  Could not find selector named shitty_selector_1,crappy_selector_2, expected one of ['x', 'y', 'z', 'shitty_selector_1', 'crappy_selector_2']
```

### Environment

```markdown
- OS: MacOS Ventura Version 13.2.1
- Python:3.9
- dbt:1.0.6
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks you for raising this @nib-potato ! And thank you for a link to the docs and examples where it wasn't working as expected.

dbt does not support the intersection or union set operators for selectors with the `--selector` flag, so I'm going to close this in favor of fixing the docs in https://github.com/dbt-labs/docs.getdbt.com/pull/3535.
