### ISSUE TITLE
[CT-2704] [Bug] When any of the unique keys is null incremental model duplicates data

### ISSUE THREAD

**Issue by alejandrofm** [dbt-labs/dbt-core#7873]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When one or more unique keys have NULL values on the table, the incremental model appends a row instead of replacing the existing one.
So:
1, NULL, 1 duplicates the record
1, 2, 1 works ok

### Expected Behavior

take null into account on unique keys of incremental models

### Steps To Reproduce

set a unique key that could have NULL values.
run the incremental model twice

### Environment

```markdown
- OS: Ubuntu
- Python: 3.8
- dbt-core: 1.4
```

**Comment by dbeatty10** [comment]
Thank you for reporting this @alejandrofm !

This looks like the same thing as https://github.com/dbt-labs/dbt-core/issues/7597, so I'm going to close this as a duplicate.

**Comment by dbeatty10** [comment]
### Solution

Add this to your `dbt_project.yml` (as described [here](https://docs.getdbt.com/reference/global-configs/snowflake-changes)) which is `false` by default:

```yaml
flags:
  enable_truthy_nulls_equals_macro: true
```

If you run into any similar problems, please open a new bug report 🙏
