### ISSUE TITLE
[Bug] In yml file referencing the source starting with the number results in dbt error

### ISSUE THREAD

**Issue by pavggit** [dbt-labs/dbt-core#7900]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt cannot handle the sources if the name starts with the number (as per the example below) 

dbt test returns the error:
Documentation for 'source.data_analytics_platform.**4db_source**.mytable' depends on doc '4db_source'  which was not found

_**yml file**_
version: 2

sources:
  - name: 4db_source
    description: '{{ doc("4db_source") }}'

_**md file**_
{% docs 4db_source %}

Doco text here ...

{% enddocs %}

Executing _dbt test -m 4db_ gives the error:
Documentation for 'source.data_analytics_platform.4db_source.mytable' depends on doc '4db_source'  which was not found

If I remove number 4 from both yml and md files it works fine.

### Expected Behavior

Expect it to work as per https://docs.getdbt.com/docs/collaborate/documentation#using-docs-blocks. There is no limitations on the doc source name mentioned in the article.  

### Steps To Reproduce

Described in Current Behavior above

### Environment

```markdown
- OS:Ubuntu 20.04.4 LTS
- Python:3.8.13
- dbt: 1.1.1
```

**Comment by gem7318** [comment]
Having the same issue.

That said and although I **do** have models beginning with a number (e.g. `0_source.data_infra_dbt.public.dim_date`), this does appears to be a bug for *all* docs blocks that begin with a number.

To get around this/verify, I just changed the doc naming convention to prepend a `desc_` as opposed to appending a `desc_`:

Pre (broken)

```
{% docs 2_latest__data_eng_dbt__bing__account_history_desc %}
# 2_latest - data_eng_dbt - bing - account_history
`{"created": "2023-06-20"}`

[some-description]

{% enddocs %}
```

Post (working)

```
{% docs desc_2_latest__data_eng_dbt__bing__account_history %}
# 2_latest - data_eng_dbt - bing - account_history
`{"created": "2023-06-20"}`

[some-description]

{% enddocs %}
```

**Comment by dbeatty10** [comment]
Thanks for raising this @pavggit and @gem7318 !

dbt docs blocks are built upon [blocks](https://jinja.palletsprojects.com/en/3.0.x/templates/#template-inheritance) in Jinja which can't begin with a number. This is just like how variable names in Python can't begin with a number. If you want to read discussions of _why_ this is, [here](https://stackoverflow.com/questions/342152/why-cant-variable-names-start-with-numbers) or [here](https://softwareengineering.stackexchange.com/questions/133381/why-should-identifiers-not-begin-with-a-number) are some options.

I'm going to mark this as "not planned" and close this in favor of adding some clarification to the documentation in https://github.com/dbt-labs/docs.getdbt.com/pull/3586.

Thanks for raising this so we can add more guidance on allowable names for docs blocks!

**Comment by pavggit** [comment]
Thank you @dbeatty10 and @gem7318,

This is pretty much what I expected, confirmation and why it is the case. I think it would pay off to update documentation to reflect this limitation.

**Comment by jtcohen6** [comment]
Nice @dbeatty10! This came up once before:
- https://github.com/dbt-labs/dbt-core/issues/4352 (still open - we could do nicer validation when we detect an invalid docs block name)
- https://github.com/dbt-labs/docs.getdbt.com/issues/1857
- https://github.com/dbt-labs/docs.getdbt.com/pull/3112
