### ISSUE TITLE
[CT-2718] [Bug] DBT Defer works locally but not on DBT Cloud IDE

### ISSUE THREAD

**Issue by franzoni315** [dbt-labs/dbt-core#7906]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am using the dbt's defer flags in order to get production tables while developing a new model. The defer works nicely on my local computer, but it does not work on DBT Cloud.

Note: I watched the video [Deferral in the IDE](https://www.loom.com/share/4ff09d9bf9e34d0fb09298d65953acbc?resume-anon-signup=true) from Doug Guthrie, and he seems to make the `defer` command to work in DBT cloud. However, he is using DBT 1.3, while I am using DBT 1.5. Therefore, I wonder whether this is a problem with the dbt version, or maybe even with the version of dbt container.

### Expected Behavior

I expected that the same command would produce the same results both locally and on DBT Cloud IDE.

### Steps To Reproduce

1. Run `dbt run --select <table_name> --defer --state <manifest_folder>` with dbt cli on a local computer.
2. Run `dbt run --select <table_name> --defer --state <manifest_folder>` with in DBT Cloud IDE.
3. Compare the compiled code and notice the difference.

### Environment

```markdown
- OS: macOS Ventura 13.3.1 (a)
- Python: 3.9.16
- dbt: 1.5.1
- DBT Cloud: 1.5 (latest)
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reaching out @franzoni315 !

This feature should work with dbt Cloud using v1.5.

Since this is something you are experiencing in the dbt Cloud IDE, could reach out by using the speech bubble (💬) in the dbt Cloud interface or at the support@getdbt.com email address?

I'm going to close the issue within this repository since dbt-core is working as expected for you.
