### ISSUE TITLE
[CT-2721] [Feature] support specify partial parsing file location

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#7911]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

All inputs for `dbt-core` should be configurable independently, with sane default when necessary. This makes running dbt-core on cloud easier to reason about. Because you can clearly configure all of your input for a `dbt` invocation.

Currently `dbt-core` will try to load up `partial_parse.msgpack` from the target dir([link](https://github.com/dbt-labs/dbt-core/blob/39e0c22353d2230fe1bc8b4852bbb0afa27fd2c0/core/dbt/parser/manifest.py#L949)). There's no way to configure it without configure target dir to the same place.

We should provide a parameter(for all commands that does parsing) to being able to specify location to load `partial_parse.msgpack`, and if not specified `dbt-core` will fall back to use the current target dir.

### Describe alternatives you've considered

Not do anything.

**Comment by jtcohen6** [comment]
@ChenyuLInx Given how internal this is to `dbt-core`, I'd love if there were a way to support configuring this without another flag/parameter. Ideas:
- Support passing this into `dbtRunner` &rarr; `@requires.manifest` programmatically
- Support this as an env var (without associated CLI flag) - similar to [configurable location for hub / package registry](https://github.com/dbt-labs/dbt-core/blob/de65697ff9e0746e0b7dec39880381decebd3a85/core/dbt/clients/registry.py#L20-L23)

**Comment by ChenyuLInx** [comment]
@jtcohen6  How does create [hidden parameter](https://github.com/dbt-labs/dbt-core/blob/4cdeff11cdeece7c6c28edb682477fd674cb9e04/core/dbt/cli/params.py#L272-L279) like what we do for `deprecated` params sounds?
