### ISSUE TITLE
[CT-2735] [Bug] Compile query error doesn't include node information

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#7940]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

This might be one symptom of a more general error handling problems in dbt-core.
The specific situation happened here is that when **compiling a inline dbt sql**, and **run into an execption**, dbt will fire an event that doesn't contain information about what node run into this issue. See Steps to Repro for command.

This is because uncatched exceptions are catched in `requires.postflight` linked below instead of in the place where we compile query.
https://github.com/dbt-labs/dbt-core/blob/38ca4fce2522aca496a72ccb704472d5bdf85908/core/dbt/cli/requires.py#L90

### Expected Behavior

I would expect the fired event contains information about which node run into issue.  for example, maybe the json log looks like
```json
{
    "data": {
            "exc": "Compilation Error in sql operation inline_query (from remote system.sql)\n  'a' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with \"dbt deps\"."
            "unique_id": "sqloperation.jaffle_shop.inline_query",
        },
    "info": {
            "category": "",
            "code": "Z002",
            "extra": {},
            "invocation_id": "780f6edf-c3f2-43a9-a742-eeefd1619c80",
            "level": "error",
            "msg": "Compilation Error in sql operation inline_query (from remote system.sql)\n  'a' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with \"dbt deps\".",
            "name": "compile error",
            "pid": 464,
            "thread": "somethread",
            "ts": "2023-06-16T19:58:11.410810Z"
    }
}
```

Current issue is because we do not have much exception handling logic in various tasks in general. This is a `dbt-core` general problem.
But specifically for this case, we can make sure we handle exception and fire proper event then re raise another exception at
https://github.com/dbt-labs/dbt-core/blob/aecbb4564cd8aee26deca1f381228f6006798c61/core/dbt/task/compile.py#L38
and 
https://github.com/dbt-labs/dbt-core/blob/aecbb4564cd8aee26deca1f381228f6006798c61/core/dbt/task/compile.py#L132
to fire event that contains node information in place.

### Steps To Reproduce

1. in a jaffle_shop project
2. run
    ```bash
    dbt --log-format json compile  --inline "select * from {{ref(1)}}"
    ```
    or 
    ```bash
    dbt --log-format json compile --inline "select * from {{ref("model_not_exisit")}}"
    ```
3. The last json formatted log is 
```json
{
    "data": {
        "exc": "Compilation Error in sqloperation inline_query (from remote system.sql)\n  The name argument to ref() must be a string, got <class 'int'>"
    },
    "info": {
        "category": "",
        "code": "Z002",
        "extra": {},
        "invocation_id": "dcbb5b3d-79f5-4a6d-85c2-65e589c09ae5",
        "level": "error",
        "msg": "Encountered an error:\nCompilation Error in sqloperation inline_query (from remote system.sql)\n  The name argument to ref() must be a string, got <class 'int'>",
        "name": "MainEncounteredError",
        "pid": 68385,
        "thread": "MainThread",
        "ts": "2023-06-23T16:47:56.709209Z"
    }
}
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @ChenyuLInx ! Do you have both the interest and bandwidth to tackle this, or are you hoping another member of the team can dive into it?

**Comment by jtcohen6** [comment]
The exception itself has an optional `node` property:

https://github.com/dbt-labs/dbt-core/blob/9836f7bdef00b7cb912ad88ab1bbbfbd4dc4b312/core/dbt/exceptions.py#L86

Not every exception will be associated with a node, but many of them will.

Currently, `MainEncounteredError` is just including the stringified representation of the exception:

https://github.com/dbt-labs/dbt-core/blob/38ca4fce2522aca496a72ccb704472d5bdf85908/core/dbt/cli/requires.py#L87-L96

We could also include other structured attributes of the node, above all its `unique_id`:
```python
        except DbtException as e:
            node_unique_id = None
            if hasattr(e, "node"):
                unique_id = e.node.unique_id
            fire_event(MainEncounteredError(exc=str(e), unique_id=unique_id))
            raise ExceptionExit(e)
```
(This also requires updating the proto contract of `MainEncounteredError`.)

```json
{
  "data": {
    "exc": "Compilation Error in sqloperation inline_query (from remote system.sql)\n  The name argument to ref() must be a string, got <class 'int'>",
    "unique_id": "sqloperation.my_dbt_project.inline_query"
  },
  "info": {
    "category": "",
    "code": "Z002",
    "extra": {},
    "invocation_id": "00255fea-e009-4830-8b46-417bb54fda67",
    "level": "error",
    "msg": "Encountered an error:\nCompilation Error in sqloperation inline_query (from remote system.sql)\n  The name argument to ref() must be a string, got <class 'int'>",
    "name": "MainEncounteredError",
    "pid": 79540,
    "thread": "MainThread",
    "ts": "2023-06-24T14:48:44.520796Z"
  }
}
```

---

https://github.com/dbt-labs/dbt-core/issues/5958#issuecomment-1487357502

We've talked before about surfacing _all_ structured attributes of the exception within log messages for those exceptions. Would we do that simply with a proto struct? I imagine that's a slightly bigger lift.

**Comment by ChenyuLInx** [comment]
I went with option 2 but opted for a even narrower fix to fire an event when error happens and re-raise a general error for use to handle later on. As I don't think we should be having main thread firing events that is for specific node. The thread running that node should be responsible.
