### ISSUE TITLE
[CT-2741] JSON logging: scrub `data` + `info.msg` (+ `info.env`), but do not scrub other `info` fields

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#7948]
When outputting JSON-formatting logging, we should scrub secret env var values from anything that might include user-specified output. That includes the `data` dictionary and `info.msg`. However, we should _not_ scrub other `info` fields, which are always provided by `dbt-core`.

Other `info` fields do not contain user-provided input, with the one exception of `info.extra`. That contains a dictionary of user-provided env vars prefixed with `DBT_ENV_CUSTOM_ENV_`, _explicitly_ for inclusion in metadata/logs. Users should not be putting any secrets in there... but just for safekeeping, it's not a bad idea to scrub it too.

https://github.com/dbt-labs/dbt-core/blob/9836f7bdef00b7cb912ad88ab1bbbfbd4dc4b312/core/dbt/events/eventmgr.py#L172-L179

---

This will avoid the odd situation if (e.g.) a secret env var value is set to `3`, causing `log_version` to appear as `*****` instead of `3`:
```
$ DBT_ENV_SECRET_TROIS=3 dbt --debug --log-format json parse
```
```json
{"data": {"log_version": *****, "version": "=1.6.0-b6"}, "info": {"category": "", "code": "A001", "extra": {}, "invocation_id": "bbcdfc89-1666-4122-9fe0-242b1d*****07ad7", "level": "info", "msg": "Running with dbt=1.6.0-b6", "name": "MainReportVersion", "pid": 1110, "thread": "MainThread", "ts": "202*****-06-26T12:14:2*****.86**********61Z"}}
```
This does not actually leak secrets, but the overly aggressive scrubbing makes it much more difficult to programmatically consume the structured log ouput. I imagine it would also cause issues if a secret's value were to collide with the `name` or `code` of an event type...

**Comment by jtcohen6** [comment]
Let's think about this one a bit more. Considerations:
- `log_version` is actually part of `data` (for just `MainReportVersion`), ever since we moved it out of `info` dict for every single event
- Should log consumers just use the `dbt-core` version instead of `log_version`?
- Doing the secret scrubbing earlier, before JSON serialization

**Comment by graciegoheen** [comment]
From refinement conversation:
- Most straightforward implementation is just to remove `log_version`
- to capture the full fix (from the issue title), easiest fix is to loop through and only do the scrubbing on the info part
- complication if we want to skip the `data`
- may need to work with Cloud to use `dbt-core` version instead of `log_version`
