### ISSUE TITLE
[CT-2748] [Feature] A single Structured Logging JSON dictionary per Exception

### ISSUE THREAD

**Issue by moltar** [dbt-labs/dbt-core#7963]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

_I am not 100% sure if this can be considered a bug. I am filing it as a bug, as the end user and a system admin._

It appears that the structured logging (as JSON) feature is splitting error messages coming from the database into separate entries.

Here's an example of one database error being represented by 6 separate JSON events:

<img width="702" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/491247/62a0b13e-5907-45b0-9cea-99fda97b3b35">

### Expected Behavior

One database error should be packed into a single JSON event.

### Steps To Reproduce

1. Use `dbt-postgres`
2. Set env `DBT_LOG_FORMAT=json`
3. Create a model that produces a database error (e.g. `select 1/0`)
4. Do a `dbt run`
5. Observe the log output

### Relevant log output

<img width="702" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/491247/62a0b13e-5907-45b0-9cea-99fda97b3b35">

### Environment

```markdown
- OS: Linux
- Python: 3.11
- dbt: 1.5.2
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

N/A

**Comment by peterallenwebb** [comment]
I agree that this is not a desirable behavior. It is an artifact of the initial move to structured logging, which took the approach of converting each log line to its own independent message. We have since abandoned that approach, but it lingers in this issue. We should adopt the behavior @moltar suggests.

**Comment by dbeatty10** [comment]
Thank you for raising this @moltar! And thanks for the insight @peterallenwebb 🧠

Per @gshank, here is the relevant section of code:
https://github.com/dbt-labs/dbt-core/blob/6a1e3a6db85f90c682ba5cd124ec28770ae9969a/core/dbt/task/printer.py#L120-L129

I'm going to re-categorize this as a feature in the meantime.

**Comment by graciegoheen** [comment]
Note: This is a fix to improve Cloud's ingestion of the structured logging

**Comment by peterallenwebb** [comment]
Noting that the Experience team has raised concerns about our plan to back-port this, and would like time to work with an RC first. That shouldn't stop us from merging to main, however.
