### ISSUE TITLE
[CT-2755] [Bug] Allow `on_schema_change = fail` for contracted incremental models

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#7975]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I add a contract to an incremental model with `on_schema_change = fail`, I get the following error message:
```
Invalid value for on_schema_change: fail. Models materialized as incremental with contracts enabled must set on_schema_change to 'append_new_columns'
```

### Expected Behavior

There's not a clear reason to prevent contracted incremental models from having `on_schema_change = fail` - which triggers an error message when the source and target schemas diverge. This config _forces_ you to execute a full-refresh if you add a new column or remove and old column from your incremental model. Removing an old column would _also_ break your "contract" - so there shouldn't be an issue with doubling up on errors here. 

I also don't see a strong reason to prevent `on_schema_change = ignore`, but at the minimum the "safest" incremental strategy (`on_schema_change = fail`) should be allowed for contracted models.

### Steps To Reproduce

1. Add a contact to an incremental model with `on_schema_change = fail`
2. Execute a `dbt build`

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by TianyiLi10** [comment]
Does python-model support on_schema_change feature ?
