### ISSUE TITLE
[CT-2768] [Regression] dbt-postgres 1.5.2 no longer supports the merge strategy for incremental models

### ISSUE THREAD

**Issue by JonahBreslow** [dbt-labs/dbt-core#7997]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

The incremental materialization strategy, `merge`, no longer works in dbt-postgres 1.5.2. Now, when running `merge` strategy based incremental materializations, one get the following error: 
 ``` The incremental strategy 'merge' is not valid for this adapter ```

despite [the documentation](https://docs.getdbt.com/docs/build/incremental-models#about-incremental_strategy) indicating that this is a valid strategy for the postgres adapter.

### Expected/Previous Behavior

The expected behavior is that the `merge` strategy will work for postgres models.

### Steps To Reproduce

1. I am using the following `pipfile` to define my virtual environment
```
[[source]]
url                    = "https://pypi.org/simple"
verify_ssl             = true
name                   = "pypi"

[packages]
dbt-core               = "==1.5.2"
dbt-postgres           = "==1.5.2"
newrelic               = "==8.8.0"
sqlfluff               = "==1.3.2"
sqlfluff-templater-dbt = "==1.3.2"
pytz                   = "==2023.3"

[dev-packages]

[requires]
python_version         = "3.9"
```

2. A basic reproducible model that showcases this issue, call it `/models/test.sql` in our toy dbt project.
```
{{
  config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='id'
  )
}}

WITH source_data AS (
  SELECT 1 AS id, 'John' AS column1, 'Doe' AS column2, 'New York' AS column3, '2023-06-27'::date AS updated_at UNION ALL
  SELECT 2, 'Jane', 'Smith', 'San Francisco', '2023-06-28'::date
)

SELECT
  id,
  column1,
  column2,
  column3,
  updated_at
FROM
  source_data
{% if is_incremental() %}
    WHERE
    updated_at > ( SELECT MAX(updated_at) from {{ this  }}) 
{% endif %}
```
3. Assuming you can create the pipenv using the above `pipfile`, then running the following command twice:
```pipenv run dbt run --select models/test.sql```

4. The first time the command is run, no errors, the second time:
```
Runtime Error in model test (models/test.sql)
The incremental strategy 'merge' is not valid for this adapter
```

### Environment

```markdown
- OS: Mac Ventura 13.4.1
- Python: 3.9
- dbt (working version): 1.2.0
- dbt (regression version): 1.5.2
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Thanks for raising this issue @JonahBreslow 💪 

The `merge` strategy won't be an option for dbt-postgres (and dbt-redshift) until dbt v1.6, so we need to update the documentation accordingly!

I'm going to close this issue in favor of updating the docs in https://github.com/dbt-labs/docs.getdbt.com/issues/3646. Please don't hesitate follow-up here (or there) with further questions or thoughts.
