### ISSUE TITLE
[CT-2780] [Docs] Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by gem7318** [dbt-labs/dbt-core#8018]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

There are a few broken links in `CONTRIBUTING.md` - [this PR](https://github.com/dbt-labs/dbt-core/pull/8017) fixes them.

`changie new` has a Docs section and isn't able to be completed without an issue number.

(apologies if `changie new` isn't needed for `.md` patches - new dbt-core contributor here😬)

### Expected Behavior

Working links.

### Steps To Reproduce

..

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

[This PR](https://github.com/dbt-labs/dbt-core/pull/8017) fixes the broken links.

**Comment by jtcohen6** [comment]
Resolved by https://github.com/dbt-labs/dbt-core/pull/8017
