### ISSUE TITLE
[CT-2781] [Bug] dbt compile process stucked when `generate_schema_name` return just raw `custom_schema_name`

### ISSUE THREAD

**Issue by rightx2** [dbt-labs/dbt-core#8019]
### Is this a new bug in dbt-core?

- [ ] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt compile process stucked when `generate_schema_name` return just raw `custom_schema_name`

### Expected Behavior

Can use `custom_schema_name` as it is

### Steps To Reproduce

1. `generate_schema_name.sql`

```
{% macro generate_schema_name(custom_schema_name, node) -%}
    {{ custom_schema_name | trim }}
{%- endmacro %}
```

2. `profiles.yaml`
```
data_dbt:
  target: dev
  outputs:
    dev:
     type: impala
     host: XXX.YYY.ZZ
     port: 12345
     schema: my_schema      
     threads: 4
```

3. `dbt_project.yml`
```
.
.
.
models:
  data_dbt:
    +materialized: table
    +post-hook:
      - "{{incremental_tmp_table_dropper(this)}}"
    dw:
      schema: dw
    stage:
      schema: stage
    ods:
      schema: ods
```

4. Run command
`$ dbt clean && dbt deps && dbt compile`

5. Result
```
05:08:21  Running with dbt=1.3.1
05:08:21  Checking target/*
05:08:21  Cleaned target/*
05:08:21  Checking dbt_packages/*
05:08:21  Cleaned dbt_packages/*
05:08:21  Finished cleaning all paths.
05:08:25  Running with dbt=1.3.1
05:08:25  Installing dbt-labs/codegen
05:08:26    Installed from version 0.9.0
05:08:26    Updated version available: 0.10.0
05:08:26  Installing dbt-labs/dbt_utils
05:08:26    Installed from version 1.1.1
05:08:26    Up to date!
05:08:26  
05:08:26  Updates available for packages: ['dbt-labs/codegen']                 
Update your versions in packages.yml, then run dbt deps
05:08:30  Running with dbt=1.3.1
05:08:30  Partial parse save file not found. Starting full parse.
05:08:32  Found 21 models, 0 tests, 0 snapshots, 0 analyses, 441 macros, 0 operations, 0 seed files, 14 sources, 0 exposures, 0 metrics
05:08:32
         (Stucked forever...)
```

Strangely, when I return `_{{ custom_schema_name | trim }}` (adding prefix) in `generate_schema_name.sql`, it works well.
```
{% macro generate_schema_name(custom_schema_name, node) -%}
    _{{ custom_schema_name | trim }}
{%- endmacro %}
```

### Environment

```markdown
OS: CentOS Linux 7 (Core)
dbt-core==1.3.1
dbt-extractor==0.4.1
dbt-impala==1.3.2
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

impala

**Comment by jtcohen6** [comment]
@rightx2 Could you look in the debug-level logs (`logs/dbt.log`) to see what dbt was doing while it was stuck? My guess would be, it was running metadata queries to populate the relational cache. You could try modifying/disabling that behavior with the [cache configurations](https://docs.getdbt.com/reference/global-configs/cache), e.g.
```
dbt --no-populate-cache compile
```
