### ISSUE TITLE
[CT-2784] [Feature] Add macro `drop_schema_named` as wrapper around `adapter.drop_schema`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#8025]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

_[internal slack thread for context](https://dbt-labs.slack.com/archives/C0131TY7EEA/p1687875528444359)_

Create a new macro to drop schemas that can be easily called from the CLI (via `run-operation`), by simply passing the schema name as a string, rather than requiring the prior construction of a `Relation` object.

```sql
{% macro drop_schema_named(schema_name) %}
  {% set schema_relation = api.Relation.create(schema=schema_name, database="", identifier="") %}
  {{ adapter.drop_schema(schema_relation) }}
{% endmacro %}
```
(This should be `adapter.drop_schema` to take advantage of [transaction handling](https://github.com/dbt-labs/dbt-core/blob/7fbfd53c3e68d05577c4d73eb562e0c96ac83778/core/dbt/adapters/sql/impl.py#L171) required for some databases)

Then, it can be called from the CLI, without requiring any customization to the global project:
```
dbt run-operation drop_schema_named --args 'schema_name: <schema_to_drop>'
```

### Describe alternatives you've considered

This works in v1.5+, but it feels pretty hacky:

```
dbt compile --inline "{{ adapter.drop_schema(api.Relation.create(schema="<schema_to_drop>", database="", identifier="")) }}"
```

### Who will this benefit?

Deployment & orchestration tools (e.g. dbt Cloud) that need to create temporary schemas, and then wish to leverage dbt's per-adapter capabilities for dropping them

### Are you interested in contributing this feature?

sure :)

**Comment by graciegoheen** [comment]
Hey @nathaniel-may - flagging this, as it may affect the adapters team

**Comment by colin-rogers-dbt** [comment]
@jtcohen6 / @graciegoheen ran into this while working on something else, raised a quick PR to add the macro
