### ISSUE TITLE
[CT-2785] [Feature] support .env file

### ISSUE THREAD

**Issue by RobbertDM** [dbt-labs/dbt-core#8026]
### Is this your first time submitting a feature request?

- [ ] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [ ] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

It would be cool if you could just drop a `.env` file in the directory next to `dbt_project.yml` and `profiles.yml` so you can do `dbt run --env_file=./.env` or even specify `env_file: .env` in your `profiles.yml`.

### Describe alternatives you've considered

I think many people are now doing `set -a; source .env; set +a` before `dbt run`.

### Who will this benefit?

Anyone who has their environment variables specified in a `.env` file.
Typically, that would contain db hostname and credentials, e.g. `POSTGRES_USER=my_postgres_user`.

**Comment by jtcohen6** [comment]
@RobbertDM I agree!

What do you think of the `dbt.env` file that I'm proposing in this related issue?
- https://github.com/dbt-labs/dbt-core/issues/6207#issuecomment-1433007301

**Comment by RobbertDM** [comment]
Looks good, for us it's mostly about not checking credentials into git but still being able to share the profiles.yml across team members, so atm we work with the above `set -a; source .env; set +a`. Your proposal would get rid of that, so I'm happy with it :)

We also use the same `.env` file to set environment variables for other software (custom python scripts), but we can always just `ln -s .env dbt.env`.

**Comment by jtcohen6** [comment]
Right on — I'm going to close this one in favor of https://github.com/dbt-labs/dbt-core/issues/6207

**Comment by sdebruyn** [comment]
Since the linked tickets have been closed and this has been kicked out of scope there, might be good to reopen this issue. Basically all we want is that dbt reads a .env file and that I can access those vars using `env_var()` in jinja.
