### ISSUE TITLE
[CT-2796] Conda forge still only has dbt-core 1.5.2 two weeks after it has been released.

### ISSUE THREAD

**Issue by nevdelap** [dbt-labs/dbt-core#8040]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt-core 1.5.2 release is tagged latest for two weeks, latest dbt-snowflake, sqlfluff docker images have it, but as I write this https://anaconda.org/search?q=dbt-core has 1.5.1.

I don't know how that is released, if it isn't you guys please say so, and maybe I can redirect the issue to the right place.

Thank you!

### Expected Behavior

https://anaconda.org/search?q=dbt-core has 1.5.2.

### Steps To Reproduce

Try to install 1.5.2 with `conda install --channel conda-forge`.

### Relevant log output

```shell
PackagesNotFoundError: The following packages are not available from current channels:

  - dbt-core=1.5.2*
```

### Environment

```markdown
- OS: Linux
- Python: 3.10
- dbt:
```

**Comment by jtcohen6** [comment]
Hey @nevdelap! We don't maintain the `conda-forge` distribution of `dbt-core`. I'm actually not sure who the maintainers are, or how it gets updated.

For the installation methods that we officially support, check out: https://docs.getdbt.com/docs/core/installation

**Comment by nevdelap** [comment]
Thank you @jtcohen6 and @dbeatty10!
