### ISSUE TITLE
[CT-2797] [Feature] Advanced logging feature in production env

### ISSUE THREAD

**Issue by cntwelve** [dbt-labs/dbt-core#8042]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Hi, everybody:

DBT has logging system, like run_result.json and "storing test failures". But more logging features are needed in production env.

1. "storing test failures" function is simple, In production env, run timestamp, run id and etc are needed, and it will be better if all result are keeped.
2. run_result.json is the only way that provides "computer readable" run result. If the result can be stored in DB, it will be more kind to maintainer.
3. run_result.json is generated only after the whole project finished. If the status of every model, like "start", "finished", "success", "fail", is present immediately after the status changes, the maintainer can take more action due to the status.

With functions listed above, it'll more helpful in the production env.

Thanks a lot!

**Comment by jtcohen6** [comment]
@cntwelve

Have you had a chance to check out the docs on dbt-core's structured logging? https://docs.getdbt.com/reference/events-logging

The appeal of using these logs is:
- [strongly typed schemas](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/types.proto)

**Comment by cntwelve** [comment]
@jtcohen6 OK, I'll check the doc and try it.
The events and logs function is a way writing logs to log file, and in this way the log collector/parser should be something like Logstash/loki, right?

**Comment by cntwelve** [comment]
And another case: using run_result.json file under dbt-server env, the log file is under the server file stucture. It is hard to deal with.
I think logging to DB can work better in this case.

Thanks.

**Comment by jtcohen6** [comment]
What you're asking for is effectively the `logging` package that we developed several years ago: https://github.com/dbt-labs/dbt-event-logging/tree/main

There are some real practical limitations to doing this kind of near-real-time "transactional" logging into an analytical database. Those limitations led us to preferring: (a) a rich structured logging system outside of the DWH; (b) batch-based approaches for uploading dbt metadata into the DWH.

Hence the README note in that package:
> ⛔🏚️ This package is obsolete and no longer developed; use [dbt_artifacts](https://hub.getdbt.com/brooklyn-data/dbt_artifacts/latest/) for a higher performance and richer view into your project.

> ⚠️ ADDING THIS PACKAGE TO YOUR DBT PROJECT CAN SIGNIFICANTLY SLOW DOWN YOUR DBT RUNS. This is due to the number of insert statements executed by this package, especially as a post-hook. Please consider if this package is appropriate for your use case before using it.

**Comment by cntwelve** [comment]
Hi,
The docs at [https://docs.getdbt.com/reference/programmatic-invocations#registering-callbacks](https://docs.getdbt.com/reference/programmatic-invocations#registering-callbacks) works. I can got the event and do some logging.
Thanks!
