### ISSUE TITLE
[CT-2811] [Bug] When adding `data_type` to a model `yml`, there is an error `KeyError: 'data_type'`

### ISSUE THREAD

**Issue by jan-benisek** [dbt-labs/dbt-core#8063]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am trying to use `contracts` in dbt and therefore adding `data_type`, however I am getting `KeyError: 'data_type'`

### Expected Behavior

The above should work, just like described in your [documentation](https://docs.getdbt.com/reference/resource-configs/contract#example).

### Steps To Reproduce

I have a simple model `my_model.sql`:
```sql
{{
    config(
        schema='tools',
        materialized='table',
        dist='all'
    )
}}


select
    lt.tool_raw,
    lt.tool

from {{ ref('foo') }} as lt -- this is a seed
```

This model has a description in `yml` file:
```yml
version: 2

models:
  - name: foo
    description: xyz
    columns:
      - name: abc
      
  - name: my_model
    description: foobar
    config:
      contract:
        enforced: true
    columns:
      - name: tool_raw
        data_type: varchar(20)
        constraints:
          - type: primary_key
            warn_unenforced: False 
        description: raw name of tool
      - name: tool
        description: tool name
```

When I run `dbt run -s my_model` I get an error (see below)

### Relevant log output

```shell
15:08:15  Running with dbt=1.5.1
15:08:16  Found 247 models, 471 tests, 0 snapshots, 0 analyses, 1020 macros, 2 operations, 11 seed files, 60 sources, 86 exposures, 8 metrics, 0 groups
15:08:16  
15:08:19  Concurrency: 12 threads (target='dev')
15:08:19  
15:08:19  1 of 1 START sql table model dev_j.my_model ................................. [RUN]
15:08:19  Unhandled error while executing 
'data_type'
15:08:19  1 of 1 ERROR creating sql table model dev_j.my_model ........................ [ERROR in 0.08s]
15:08:20  
15:08:20  Running 2 on-run-end hooks
15:08:20  1 of 2 START hook: smallpdf.on-run-end.0 ....................................... [RUN]
15:08:20  1 of 2 OK hook: smallpdf.on-run-end.0 .......................................... [OK in 0.00s]
15:08:20  2 of 2 START hook: smallpdf.on-run-end.1 ....................................... [RUN]
15:08:20  2 of 2 OK hook: smallpdf.on-run-end.1 .......................................... [OK in 0.00s]
15:08:20  
15:08:20  
15:08:20  Finished running 1 table model, 2 hooks in 0 hours 0 minutes and 3.24 seconds (3.24s).
15:08:20  
15:08:20  Completed with 1 error and 0 warnings:
15:08:20  
15:08:20  'data_type'
15:08:20  
15:08:20  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

In the `dbt.log`, I can see this:
```
File "/Users/j/.pyenv/versions/3.9.9/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 1342, in render_raw_columns_constraints
    rendered_column_constraint = [f"{v['name']} {v['data_type']}"]
KeyError: 'data_type'
```

### Environment

- OS: Mac
- Python: Python 3.9.9
- dbt: core: 1.5.1, dbt-redshift: 1.5.7

### Which database adapter are you using with dbt?

redshift

**Comment by dbeatty10** [comment]
Thanks for opening this @jan-benisek !

All columns will need to have `data_type` defined. Could you try giving the `tool` column a data type like this?

```yaml
      - name: tool
        description: tool name
        data_type: varchar(20)
```

That should solve the particular issue you are running into.

As a follow-up, dbt should raise a better error message when a `data_type` is missing for a column that is part of an enforced contract.

**Comment by jan-benisek** [comment]
Hi @dbeatty10 , should have thought of that, adding `data_type` to each column definitely works! I was probably confused with that error.
Thanks for the quick response.

**Comment by dbeatty10** [comment]
You are welcome @jan-benisek!

We opened https://github.com/dbt-labs/dbt-core/issues/8070 to raise a better error message in the future.
