### ISSUE TITLE
[CT-2812] Remove `create_metric` property from end user facing `Measure` spec

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#8064]
## Acceptance Criteria

- [create_metric property](https://github.com/dbt-labs/dbt-core/blob/15ef88d2ed36fd8bb6aad26325ee11789ff02ffe/core/dbt/contracts/graph/unparsed.py#L700) is removed from the [UnparsedMeasure](https://github.com/dbt-labs/dbt-core/blob/15ef88d2ed36fd8bb6aad26325ee11789ff02ffe/core/dbt/contracts/graph/unparsed.py#L696) definition

# Context
Currently we have [create_metric property](https://github.com/dbt-labs/dbt-core/blob/15ef88d2ed36fd8bb6aad26325ee11789ff02ffe/core/dbt/contracts/graph/unparsed.py#L700) defined on the [UnparsedMeasure](https://github.com/dbt-labs/dbt-core/blob/15ef88d2ed36fd8bb6aad26325ee11789ff02ffe/core/dbt/contracts/graph/unparsed.py#L696) for [UnparsedSemanticModel](https://github.com/dbt-labs/dbt-core/blob/15ef88d2ed36fd8bb6aad26325ee11789ff02ffe/core/dbt/contracts/graph/unparsed.py#L724)s. The `create_metric` property is incredibly useful, if it were hooked up. However, we haven't hooked it up, and don't have time to do so before the `1.6.0rc` release of core. Thus, for `1.6.x` of core we shouldn't allow users to specify this property.

**Comment by jtcohen6** [comment]
@QMalcolm Is this something we need to do before cutting the v1.6 RC on Thursday? The alternative seems like: leave it in place for now, knowing that we're planning to add in support for this in v1.7

**Comment by QMalcolm** [comment]
@jtcohen6 I think we don't want to allow users to specify it. It can be something that remains on the graph node, but should be removed from the unparsed version of the node. It's a two line change
