### ISSUE TITLE
[CT-2814] [Feature] Better error message when a column in a contracted model is missing a `data_type`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#8070]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We didn't provide a helpful error message [here](https://github.com/dbt-labs/dbt-core/issues/8063) which made it hard for the user to see what was going on.

We should provide a better error message. Maybe some like this:
> You have an enforced contract for model X, but column Y is missing a specified `data_type`

Of course replace X and Y with the actual model / column names! 😎

The relevant area of code is somewhere around here:
https://github.com/dbt-labs/dbt-core/blob/d8f38ca48bf75311bca113b76d447e613bb2d661/core/dbt/adapters/base/impl.py#L1350

### Describe alternatives you've considered

We could leave it as-is, but that wouldn't be the best 😢 

### Who will this benefit?

All of us that miss tiny little things and just need helpful direction of how to fix it.

**Comment by MichelleArk** [comment]
We should be able to raise the existing `[ColumnTypeMissingError](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/exceptions.py#L1923)` exception (via [column_type_missing](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/context/exceptions_jinja.py#L107)) here. Currently it's raised right before creating an empty sql statement (to get the model contract based on the schema.yml file). This check could be moved further up the chain, either in jinja where we check that a model is contracted or potentially during parsing when we [patch node properties](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/parser/schemas.py#L628).

Some related work: https://github.com/dbt-labs/dbt-core/commit/746ca7d149bd8baee37c476a2186232e797fb9e8

**Comment by jtcohen6** [comment]
> potentially during parsing when we [patch node properties](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/parser/schemas.py#L628)

IIRC, we're not able to do this during parsing because it's possible that we're patching node properties (`columns` before we know whether the model is actually configured with `contract: {enforced: true}`. (That is, until/unless we do the work described in #6511.)

So this change makes sense to me:

> This check could be moved further up the chain... in jinja where we check that a model is contracted

**Comment by emmyoop** [comment]
I believe this was done and released in 1.6 as part of commit https://github.com/dbt-labs/dbt-core/commit/814eb65d59ba71a0a200618021f35429dfba9da6.  Do we want to raise the error in another way?

**Comment by jtcohen6** [comment]
@emmyoop You're right!!

```
18:42:35  1 of 1 START sql view model dbt_jcohen.my_model ................................ [RUN]
18:42:35  1 of 1 ERROR creating sql view model dbt_jcohen.my_model ....................... [ERROR in 0.08s]
18:42:35
18:42:35  Finished running 1 view model in 0 hours 0 minutes and 0.20 seconds (0.20s).
18:42:35
18:42:35  Completed with 1 error and 0 warnings:
18:42:35
18:42:35    Compilation Error in model my_model (models/my_model.sql)
  Contracted models require data_type to be defined for each column. Please ensure that the column name and data_type are defined within the YAML configuration for the ['tool'] column(s).
```

I think this one can be closed :)

**Comment by yuna-tang** [comment]
Hi @jtcohen6, I find this post when we try to implement the contract configs for our models.
We are on dbg1.6, however, I see different error messages:

> 06:03:09  Completed with 1 error and 0 warnings:
> 06:03:09  
> 06:03:09    'data_type'
![image](https://github.com/dbt-labs/dbt-core/assets/129704116/63f44947-bb18-4382-b1c7-d7cf70154cd7)

We are using redshift and dbt1.6. I would prefer to see messages like below.
05:26:10  Running with dbt=1.6.5
05:26:10  Registered adapter: redshift=1.6.0


> 18:42:35    Compilation Error in model my_model (models/my_model.sql)
>   Contracted models require data_type to be defined for each column. Please ensure that the column name and data_type are defined within the YAML configuration for the ['tool'] column(s).
