### ISSUE TITLE
[CT-2824] Update unit tests so that when run individually we don't get args errors

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#8091]
The unit tests have been updated piecemeal to have something like:
```
from dbt.flags import set_from_args
from argparse import Namespace

set_from_args(Namespace(WARN_ERROR=False), None)
```

Come up with a common mechanism for updating the tests and ensure that all of the unit tests can be run individually.

**Comment by MichelleArk** [comment]
As a first stab, lets consolidate how we do this in tests/unit by creating a base test class or util method. Then we can reevaluate whether there are alternative / preferred mechanisms for setting args in unit tests.

**Comment by MichelleArk** [comment]
Let's re-evaluate the need for this once https://github.com/dbt-labs/dbt-core/issues/8627 is closed

**Comment by gshank** [comment]
We've added the set_args thing to all of the unit tests that need it, so closing this.
