### ISSUE TITLE
[CT-2825] [Bug] Executing ALTER ROLE in DBT macro

### ISSUE THREAD

**Issue by acherniak** [dbt-labs/dbt-core#8092]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I’m alternating between two schemas and in the final step of my DBT process have to change the user’s search_path.
It works fine in plain SQL:

> ALTER ROLE ci_api SET search_path TO ci_f, public;
> SELECT rolconfig FROM pg_roles WHERE rolname=‘ci_api’;

My macro supposed to do exactly the same:

> {% macro sp1() %}
> {% set sql %} ALTER ROLE ci_api SET search_path TO ci_x,public {% endset %}
> run_query(sql);
> {% do log(run_query(“SELECT rolconfig FROM pg_roles WHERE rolname=‘ci_api’”).columns[0].values()[0], info=True) %}
> {% endmacro %}

But does nothing. No errors, the log looks normal, but search_path doesn’t change.
What am I missing?

### Expected Behavior

the macro should ALTER ROLE

### Steps To Reproduce

Run the above macro

### Environment

```markdown
- OS: Max OS
- Python: 3.9.6
- dbt: 1.5.2
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Thanks for reaching out @acherniak!

Could you try this?

```sql
{% macro sp1() %}
{% set sql %} ALTER ROLE ci_api SET search_path TO ci_x,public {% endset %}
{{ run_query(sql) }}
{% do log(run_query("SELECT rolconfig FROM pg_roles WHERE rolname='ci_api'").columns[0].values()[0], info=True) %}
{% endmacro %}
```

Then run it:
```shell
dbt run-operation sp1
```

Otherwise, `run_query(sql);` will just be text (rather than executing the `run_query` Jinja macro).

**Comment by acherniak** [comment]
Thank you @dbeatty10! It works!
Completely my fault

**Comment by dbeatty10** [comment]
No prob @acherniak -- glad you got it all working! 🚀
