### ISSUE TITLE
[CT-2830] [Bug] Logs do not render EOF error from Snowflake

### ISSUE THREAD

**Issue by sophiad96** [dbt-labs/dbt-core#8124]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

An Enterprise customer reported receiving the following error on a job run:

![image001](https://github.com/dbt-labs/dbt-core/assets/68790165/df1cc812-d8bd-4ac7-90e7-3a8eb2644409)

Note the empty string at the end of the last line. When they checked their logs directly in Snowflake, they saw <EOF> rendered instead of the empty string:

![image001-1](https://github.com/dbt-labs/dbt-core/assets/68790165/8ba3b504-f7cd-4de4-8903-b678c76272fa)

### Expected Behavior

The run should fail, but the error message should say `  syntax error line 53 at position 27 unexpected ‘<EOF>' instead. It’s worth noting that when running this in the IDE, the error message returned does include the ‘<EOF>’ at the end.

### Steps To Reproduce

1. Navigate to the IDE and add the following two macros to your dbt project:
    [sf_create_edw_dl_sf_handshake_s.sql.zip](https://github.com/dbt-labs/dbt-core/files/12074165/sf_create_edw_dl_sf_handshake_s.sql.zip)
    [deployment_process.sql.zip](https://github.com/dbt-labs/dbt-core/files/12074167/deployment_process.sql.zip)

2. Go through both files and replace the database EDW_UTILITY with the database you’re connected to. Do the same with the ETL_STATUS schema and replace with your dev schema.

3. Find the $$ signs on lines 60 and 290 of the sf_create_edw_dl_sf_handshake_sp_20230710 macro. Delete those. Save and commit your changes.

4. Create a new job in an environment that runs on the branch you were developing on. Make sure the job has the following settings:

    dbt version: 1.4

    command: dbt run-operation deployment_process --args '{deployments: ['sf_create_edw_dl_sf_handshake_sp_20230710_b']}'

5. Run the job.

### Environment

```markdown
- OS:
- Python:
- dbt: 1.4
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

(https://dbtlabs.atlassian.net/browse/TRIAGE-551)

**Comment by dbeatty10** [comment]
Thanks for reporting this @sophiad96 !

It sounds like they expected this:
```
SQL compilation error: syntax error line 52 at position 142 unexpected '<EOF>'
```
but got this instead?
```
SQL compilation error: syntax error line 52 at position 142 unexpected ''
```

**Comment by sophiad96** [comment]
@dbeatty10 yep that's exactly right!

**Comment by dbeatty10** [comment]
@sophiad96 Could you try out the following in a test Snowflake database and see if it does (or doesn't) work for you in Cloud?

`macros/eof.sql`
```
{% macro eof() %}

  {% set query %}
    create or replace table sf_table_error (
        a1 double,
        failure int
  {% endset %}

  {% do run_query(query) %}
{% endmacro %}
```

Run it:
```shell
dbt run-operation eof
```

I get output like the following with dbt-core (which **does** have the `<EOF>` included:
```
23:39:53  Running with dbt=1.5.1
23:39:54  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 322 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
23:39:54  Encountered an error while running operation: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 3 at position 19 unexpected '<EOF>'.
```

**Comment by jtcohen6** [comment]
I believe these logs are being produced with `--log-format json`, so we should also investigate whether it's the JSON serialization logic within dbt-core that's causing `'<EOF>'` to be replaced with `''`

**Comment by dbeatty10** [comment]
The JSON output includes the `<EOF>` string in my environment:

```shell
dbt --log-format json run-operation eof
```

Output to terminal:
```
{"data": {"log_version": 3, "version": "=1.5.1"}, "info": {"category": "", "code": "A001", "extra": {}, "invocation_id": "005c952a-37c3-449e-845d-973a1f75b54d", "level": "info", "msg": "Running with dbt=1.5.1", "name": "MainReportVersion", "pid": 12515, "thread": "MainThread", "ts": "2023-07-19T15:10:20.045090Z"}}
{"data": {"stat_line": "2 models, 0 tests, 0 snapshots, 0 analyses, 322 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups"}, "info": {"category": "", "code": "W006", "extra": {}, "invocation_id": "005c952a-37c3-449e-845d-973a1f75b54d", "level": "info", "msg": "Found 2 models, 0 tests, 0 snapshots, 0 analyses, 322 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups", "name": "FoundStats", "pid": 12515, "thread": "MainThread", "ts": "2023-07-19T15:10:20.341774Z"}}
{"data": {"exc": "Database Error\n  001003 (42000): SQL compilation error:\n  syntax error line 3 at position 19 unexpected '<EOF>'."}, "info": {"category": "", "code": "Q001", "extra": {}, "invocation_id": "005c952a-37c3-449e-845d-973a1f75b54d", "level": "error", "msg": "Encountered an error while running operation: Database Error\n  001003 (42000): SQL compilation error:\n  syntax error line 3 at position 19 unexpected '<EOF>'.", "name": "RunningOperationCaughtError", "pid": 12515, "thread": "MainThread", "ts": "2023-07-19T15:10:21.110976Z"}}
```

Or pretty-printed JSON output using [`jq`](https://jqlang.github.io/jq/download/):
```shell
dbt --quiet --log-format json run-operation eof | jq .
```

```json
{
  "data": {
    "exc": "Database Error\n  001003 (42000): SQL compilation error:\n  syntax error line 3 at position 19 unexpected '<EOF>'."
  },
  "info": {
    "category": "",
    "code": "Q001",
    "extra": {},
    "invocation_id": "5a4a0b4b-34c1-4cf4-b910-1581f760e1d0",
    "level": "error",
    "msg": "Encountered an error while running operation: Database Error\n  001003 (42000): SQL compilation error:\n  syntax error line 3 at position 19 unexpected '<EOF>'.",
    "name": "RunningOperationCaughtError",
    "pid": 12732,
    "thread": "MainThread",
    "ts": "2023-07-19T15:12:39.700057Z"
  }
}
```
