### ISSUE TITLE
[CT-2838] Enabling deferral for metrics

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#8135]
I am working in a development environment, and I've built some (but not all!) models.

I want to hook up a development semantic layer environment to read from my development schema in the warehouse. But in instances where I need to be referencing models that I haven't built yet, I want to read from my production schema instead. 

We apply the failover replacement logic as one of the first steps of task execution after parsing has finished.

"deferral to a higher authority vs. deferral to a point in time"

When we enable deferral, we can stop skipping `test_metric_deferral`

We currently `@pytest.mark.skip` [test_metric_deferral](https://github.com/dbt-labs/dbt-core/blob/867534c1f49a3daccd6aae83dd32772173479f9d/tests/functional/metrics/test_metric_deferral.py#L63). We should at this time be able to un-skip this test with some minor tweaks. Additionally, if the test is broken for real reasons, this issue should be converted to fixing the functionality as well.

## Acceptance Criteria

- using `--defer` on the CLI command works with metrics
- `test_metric_deferral` is no longer skipped
- `test_metric_deferral` passes (and not because it's rigged)

**Comment by graciegoheen** [comment]
`deferral` likely doesn't work for metrics today because of order of parsing & deferral
