### ISSUE TITLE
[CT-2842] Add SemanticModel tests to `test_contracts_graph_parsed`

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#8139]
## Context
We have a bunch of tests in [test_contract_graph_parsed.py](https://github.com/dbt-labs/dbt-core/blob/main/tests/unit/test_contracts_graph_parsed.py) which check the symmetry of dict representation of objects and the actual python objects as well as checking the required properties of graph nodes. Currently we have none of these tests for `SemanticModel`s

## Acceptance Criteria
- Tests exist in `test_contract_graph_parsed.py` for checking symmetry and required graph node properties of `SemanticModel`s
- Tests do not require hand-rolling of objects and dictionaries

**Comment by graciegoheen** [comment]
Checking that when we dict-ify objects and de-dict-ify objects, we're getting what we'd expect. We don't currently have this type of test for `SemanticModel`s

These tests are brittle and incomplete - breaking everytime we make a change to the manifest schema, have to go in and manually fix them. We may want to think about what we can do overall with these tests to better implement them. Can we automate these in some way? Can we use this example as a way to try a different (and better!) testing implementation?
