### ISSUE TITLE
[CT-2846] Update dependency pins: `click<9` + `sqlparse<0.5`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#8145]
Unpin `click` now that a new version has been released that _should_ fix the typing issues:
- https://github.com/dbt-labs/dbt-core/issues/8048
- https://github.com/pallets/click/issues/2558#issuecomment-1640926299

---

We removed the `sqlparse` pin in https://github.com/dbt-labs/dbt-core/pull/7993 — but we should still have an upper bound since it's major-0 software. Previously we had the upper bound pinned to `<0.5`.

---

We should backport to `1.6.latest` (for inclusion in v1.6.0rc2/final) + `1.5.latest` (for inclusion in v1.5.4)

**Comment by jtcohen6** [comment]
Looks like there are still some issues with `mypy` + `click==8.1.6`: https://github.com/dbt-labs/dbt-core/pull/8146#issuecomment-1641859347

**Comment by emmyoop** [comment]
I don't know who these are combined.  sqlparse can get an upper bound without any issues so I split it out to #8236.

**Comment by emmyoop** [comment]
opening up the pin for click does still have some mypy failures.  specifically these just 3 in #8232.  Question is if we want to ignore them or just not upgrade yet.

```
core/dbt/cli/params.py:392: error: Argument 2 to "option" has incompatible type "**Dict[str, Union[Type[Tuple[Any, ...]], bool, Type[MultiOption], str, None]]"; expected "Optional[Type[Option]]"  [arg-type]
core/dbt/cli/params.py:393: error: Argument 2 to "option" has incompatible type "**Dict[str, Union[Type[Tuple[Any, ...]], bool, Type[MultiOption], str, None]]"; expected "Optional[Type[Option]]"  [arg-type]
core/dbt/cli/params.py:394: error: Argument 3 to "option" has incompatible type "**Dict[str, Union[Type[Tuple[Any, ...]], bool, Type[MultiOption], str, None]]"; expected "Optional[Type[Option]]"  [arg-type]
```
