### ISSUE TITLE
[CT-2849] [Bug] Giving key error snowflake

### ISSUE THREAD

**Issue by abdulrafey38** [dbt-labs/dbt-core#8154]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Throws key error snowflake in adapters, its not registering adapters as it do in previous versions

### Expected Behavior

it should run smoothly

### Steps To Reproduce

`macOS with dbt 1.5`

from dbt.config import RuntimeConfig
after importing RuntimeConfig i used this in one of my own package

==>running this (RuntimeConfig.from_args(args)<==) from my own package built on the top of dbt

### Environment

```markdown
- OS:mac os ventura 13.2.1
- Python:3.8.17
- dbt: 1.5.2
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

<img width="833" alt="Screenshot 2023-07-20 at 1 18 54 AM" src="https://github.com/dbt-labs/dbt-core/assets/41017154/18d4a9c4-5833-4a71-88df-cfd2f02d7169">

**Comment by abdulrafey38** [comment]
In previous version of dbt first register adapters in task/basy.py file but in dbt 1.5 they dont i beleive this might be the reason, as i did test it locally and it runs fine in dbt 1.5 as well if i register adapters in tasks/base.py first

**Comment by dbeatty10** [comment]
Thanks for reaching out @abdulrafey38!

The code you mentioned is a private implementation detail (changed in https://github.com/dbt-labs/dbt-core/pull/6565) that we don't intend to be a public interface.

Have you given our [programmatic invocations](https://docs.getdbt.com/reference/programmatic-invocations) entry points a try yet?

The intent is to expose the existing dbt CLI via a Python entry point, such that top-level commands are callable from within a Python script or application.

**Comment by abdulrafey38** [comment]
@dbeatty10 thank you issue resolved 🥳
