### ISSUE TITLE
[CT-2862] [Bug] Vars are passed by reference in models, which causes issues with compile+run steps

### ISSUE THREAD

**Issue by rlh1994** [dbt-labs/dbt-core#8191]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm not sure if this is by design, but I couldn't find any other issues relating to it and no docs on the topic, so it may just be this needs calling out somewhere to save people the trouble of discovering themselves.

Basically, it seems like dbt variables are passed to the environment by reference, rather than by value. For the vast majority of use cases this is probably fine and makes no difference, however in a case where the variable is a list and a model or macro alters this list, this is done both in the compile and the run steps of `dbt run`, which means the action is (incorrectly) taken twice.

Using the `.copy()` method avoids this issue, however I couldn't find it documented obviously anywhere.

### Expected Behavior

This variable would be passed by value, so that alterations done in the compile step are not impacting the run step.

### Steps To Reproduce

1. Start with a new project, create a model called `test.sql` with the following content:
    ```jinja2
    {% set x = var('test_list', []) %}
    {{ log('x: ' ~ x, info=True) }}
    {% do x.append(1) %}
    {% do x.append(2) %}
    
    {{ log('x: ' ~ x, info=True) }}
    
    
    {% set y = var('test_list2', []) %}
    
    {{ log('y: ' ~ y, info=True) }}
    {{ test_macro(y) }}
    {{ test_macro(y) }}
    
    {{ log('y: ' ~ y, info=True) }}
    
    {% set z = var('test_list3', []).copy() %}
    {{ log('z: ' ~ z, info=True) }}
    {% do z.append(1) %}
    {% do z.append(2) %}
    
    {{ log('z: ' ~ z, info=True) }}
    
    select 1 as a
    ```
2. Create a macro called test_macro with the following content:
    ```jinja2
    {% macro test_macro(my_list) %}
      {% do my_list.append('y') %}
    {% endmacro %}
    ```
3. Add the following to `dbt_project.yml`:
    ```yml
    vars:
      test_list: []
      test_list2: []
      test_list3: []
    ```
4. Do `dbt run`, see the first two variables are updated twice.

### Relevant log output

```shell
09:35:18  Running with dbt=1.5.1
09:35:18  Unable to do partial parsing because a project config has changed
09:35:19  x: []
09:35:19  x: [1, 2]
09:35:19  y: []
09:35:19  y: ['y', 'y']
09:35:19  z: []
09:35:19  z: [1, 2]
09:35:19  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 308 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
09:35:19  
09:35:19  Concurrency: 1 threads (target='postgres')
09:35:19  
09:35:19  1 of 1 START sql view model dbt_ryan.test ...................................... [RUN]
09:35:19  x: [1, 2]
09:35:19  x: [1, 2, 1, 2]
09:35:19  y: ['y', 'y']
09:35:19  y: ['y', 'y', 'y', 'y']
09:35:19  z: []
09:35:19  z: [1, 2]
09:35:19  1 of 1 OK created sql view model dbt_ryan.test ................................. [CREATE VIEW in 0.07s]
09:35:19  
09:35:19  Finished running 1 view model in 0 hours 0 minutes and 0.18 seconds (0.18s).
09:35:19  
09:35:19  Completed successfully
09:35:19  
09:35:19  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: MacOS
- Python: 3.9.13
- dbt: 1.5.1
```

### Additional Context

It may be this just would benefit from being documented with the `copy()` workaround, but I'm not sure if this is the intended behaviour or not. Another alternative workaround is to use the `{% if execute %}` block, but it wasn't clear you should do this for list variables.

**Comment by jtcohen6** [comment]
This is a fun one! Two things going on here:
1. dbt renders complex Jinja twice, once at parse time and again at "execute" time (hence why `if execute` works)
2. dbt returns the actual Python object for the variable to the Jinja context, rather than a copy of its value

https://github.com/dbt-labs/dbt-core/blob/6130a6e1d0d29b257fbcd1b17fcd730383d73ce0/core/dbt/context/base.py#L163-L173

If I update that to:
```python
    def get_rendered_var(self, var_name):
        from copy import copy
        raw = copy(self._merged[var_name])
```

It seems to resolve this issue:
```
$ dbt --no-partial-parse run
10:35:22  Running with dbt=1.7.0-a1
10:35:23  Registered adapter: postgres=1.7.0-a1
10:35:23  x: []
10:35:23  x: [1, 2]
10:35:23  y: []
10:35:23  y: ['y', 'y']
10:35:23  z: []
10:35:23  z: [1, 2]
10:35:23  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 353 macros, 0 groups, 0 semantic models
10:35:23
10:35:23  Concurrency: 5 threads (target='dev')
10:35:23
10:35:23  1 of 1 START sql view model dbt_jcohen.test .................................... [RUN]
10:35:23  x: []
10:35:23  x: [1, 2]
10:35:23  y: []
10:35:23  y: ['y', 'y']
10:35:23  z: []
10:35:23  z: [1, 2]
10:35:23  1 of 1 OK created sql view model dbt_jcohen.test ............................... [CREATE VIEW in 0.10s]
10:35:23
10:35:23  Finished running 1 view model in 0 hours 0 minutes and 0.23 seconds (0.23s).
10:35:23
10:35:23  Completed successfully
10:35:23
10:35:23  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

As a general practice, we should try to avoid having the special values that we add to the Jinja context be things that users can mutate with custom code.

@gshank feels like you might have a thought about this one :)

**Comment by rlh1994** [comment]
@gshank Did you get a chance to take a look at this please?

**Comment by graciegoheen** [comment]
I think the correct workaround is to use the `{% if execute %}` block, so I'm going to close this out.

We can certainly add better docs here, where do you think would be the best spot? Some ideas:
- https://docs.getdbt.com/reference/dbt-jinja-functions/execute
- https://docs.getdbt.com/docs/build/jinja-macros

If you have a specific spot in mind, feel free to open up an issue over in the docs site repo - https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose
