### ISSUE TITLE
[CT-2865] [Feature] Postgres: Support overwriting tables and views with materialized views

### ISSUE THREAD

**Issue by damian3031** [dbt-labs/dbt-core#8194]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Support overwriting tables and views with materialized views in Postgres adapter.

### Are you interested in contributing this feature?

Yes I am

**Comment by Fleid** [comment]
Hi @damian3031 - thanks so much for the quick intervention, but we're already planning to enable that in 1.7 ourselves (releasing it early in a beta somewhere in August).

Sadly we can't re-purpose your work, as we are currently refactoring the first internal implementation of MVs that your contribution is based of. We sincerely appreciate your efforts, and hopefully you'll be able to test the new iteration later this summer.
