### ISSUE TITLE
[CT-2867] [Feature] Supports non half width alphanumeric for generic test

### ISSUE THREAD

**Issue by d-kaneshiro** [dbt-labs/dbt-core#8204]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Double-byte characters in GenericTest should be displayed normally instead of "_".

### Who will this benefit?

Mainly Japanese users who use hiragana, katakana and kanji will be happy.
Also, this is great for other Asian users who use double-byte characters.

### Anything else?

I will try to solve it in the PR below.
https://github.com/dbt-labs/dbt-core/pull/8203

**Comment by dbeatty10** [comment]
Thanks for raising this @d-kaneshiro !

If it is practical, it seems reasonable to double-byte characters.

Was `GenericTest` the only thing you saw affected by this? Or were there others as well?

**Comment by d-kaneshiro** [comment]
@dbeatty10 
> Was GenericTest the only thing you saw affected by this? Or were there others as well?

As far as I have observed, only GenericTest.
For example, the `SingularTest` log outputs double-byte character file names as they are.
