### ISSUE TITLE
[Regression] Ephemeral Materializations not Compiling correctly

### ISSUE THREAD

**Issue by JoshuaHuntley** [dbt-labs/dbt-core#8217]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

dbt 1.5.3 is compiling models with ephemeral materializations differently than 1.5.2 and is causing jobs to fail. See code examples:
```
---- Compiled with 1.5.3 ----

with __dbt__cte__table as (

WITH source AS (
    SELECT
        *
    FROM DATABASE.schema.table
),
renamed AS (
    SELECT
         col1::number(10,0) as col1
        ,col2::number(10,0) as col2
        ,col3::number(10,0) as col3
        ,upper(trim(col4)::varchar) as col4
        ,col5
    FROM source
)
SELECT
    *
FROM renamed
)
with source as (             --<-<-<-<-<-<-<-<-<-<-<-<-<-<- This part now fails
    select *
    from __dbt__cte__table
)
select * from source
```

### Expected/Previous Behavior

Code sample from previous minor version:

```
---- Compiled with 1.5.2 ----

with  __dbt__cte__table as (

WITH source AS (
    SELECT
        *
    FROM DATABASE.schema.table
),
renamed AS (
    SELECT
         col1::number(10,0) as col1
        ,col2::number(10,0) as col2
        ,col3::number(10,0) as col3
        ,upper(trim(col4)::varchar) as col4
        ,col5
    FROM source
)
SELECT
    *
FROM renamed
),source as (
    select *
    from __dbt__cte__table
)
select * from source
```

### Steps To Reproduce

Compile with 1.5.2 and compare to 1.5.3

### Environment

```markdown
- OS:  MacOS
- Python: 3.11.4
- dbt (working version): 1.5.2
- dbt (regression version): 1.5.3
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dataders** [comment]
thanks @JoshuaHuntley! This is a strange error to be sure. I looked at the diff ([`v1.5.2...v1.5.3`](https://github.com/dbt-labs/dbt-core/compare/v1.5.2...v1.5.3?diff=split)) and couldn't distinguish any change what would affect this.

Can you share the output of `dbt --version`? does the version of dbt-snowflake change b/w each of these environments?

**Comment by JoshuaHuntley** [comment]
I compared these by compiling on my CLI after our PROD failure. Here is the out from both compile iterations:

`15:58:03  Running with dbt=1.5.2
15:58:03  Registered adapter: snowflake=1.5.2
15:58:04  Found 
15:58:04  
15:58:06  Concurrency: 
`


`16:01:41  Running with dbt=1.5.3
16:01:41  Registered adapter: snowflake=1.5.2
16:01:41  Unable to do partial parsing because of a version mismatch
16:01:44  Found 
16:01:45  
16:01:46  Concurrency: `

**Comment by gshank** [comment]
This is caused by a bug in sqlparse 0.4.4 for which we have just developed a fix in https://github.com/dbt-labs/dbt-core/pull/8215
