### ISSUE TITLE
[CT-2913] Run unit tests in packages that are not the root package

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#8285]
### Description

If we want to handle running unit tests in packages that are not the root package, we need to make a few changes in the unit testing code.
* Construct a unique_id that uses the non-root package name
* Set the package name in the constructed UnitTestNode

### Acceptance Criteria

Non-root package unit tests are executed if selected.

### Impact to Other Teams

None

### Will backports be required?

No 

### Context

**Comment by graciegoheen** [comment]
Notes from estimation:
- right now we're assuming it's just in the root package in the parsing code
- make sure the package of the unit test is included in the unit test node
- do we actually want these disabled by default? or provide a simple way to not select them?

**Comment by MichelleArk** [comment]
Resolved by: https://github.com/dbt-labs/dbt-core/pull/9184
