### ISSUE TITLE
[CT-2916] Use a distinct flavor of Manifest, such as UnitTestManifest instead of base Manifest

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#8289]
### Description

In the initial unit testing branch we use a Manifest object to contain the special unit tests and mocked models. It might be better to use a different manifest class (like the MacroManifest), which could potentially contain extra methods for generating unit testing artifacts or results.

This is still worth experimenting with, but with some refactoring it feels like less of an issue, since we're now selecting against a standard manifest and writing the unit test manifest to a different file.

### Acceptance Criteria

Unit testing manifest uses a special Manifest object

### Impact to Other Teams

None

### Will backports be required?

No 

### Context

**Comment by graciegoheen** [comment]
We need to think about how this metadata becomes available when you are and are not actually running unit tests (e.g. can we still get metadata about unit tests in production when you're not running unit tests in production).
