### ISSUE TITLE
[CT-2921] Create special unit testing Config object

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#8294]
The initial unit testing branch specifies TestConfig in model_config.py, but actually uses NodeConfig (from ParsedNode) in the UnitTestNode. Make a custom UnitTestConfig with appropriate fields and use in UnitTestNode.

Is this actually required?  We're now selecting against standard model nodes, and the database/schema/identifier is also coming from the model nodes. So it's not clear what we would need from a specialized Config object.

**Comment by graciegoheen** [comment]
Do we want to support these configs?
- tags (test specific markers -> "flaky" "exclude")
- meta (on every other resource type)

**Comment by MichelleArk** [comment]
From refinement: 
* this config (supporting tags & meta to start) should support jinja rendering for consistency 
* this config should apply at the node-level (from schema.yml files) and also be configurable hierarchically from dbt_project.yml, with a new top-level `unit` block in `dbt_project.yml`
