### ISSUE TITLE
[CT-2928] [Feature] Add a JSON Schema for the structured logging event

### ISSUE THREAD

**Issue by moltar** [dbt-labs/dbt-core#8303]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Various schemas for dbt data artifact formats are already published:

- https://next.docs.getdbt.com/reference/artifacts/dbt-artifacts
- https://schemas.getdbt.com/

However, the structured logging event schema is not published yet.

- https://docs.getdbt.com/reference/events-logging#structured-logging

### Describe alternatives you've considered

N/A

### Who will this benefit?

It will benefit the developers who are integrating other tooling with dbt.

In our case, we were relying on a certain log format for reporting and dashboarding.

But then in some version the logging format had changed and it broke our dashboarding.

We use codegen approach from JSON Schema to types, so that we can validate the data formats.

### Anything else?

N/A

**Comment by graciegoheen** [comment]
Hey there! Is [this](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/types.proto) what you're looking for? It's not in JSON format, but you should be able to convert it to JSON.

**Comment by moltar** [comment]
Thanks. Yes, that is the data type that I am looking for.

However, I think publishing them in universally accepted JSON Schema format is still beneficial for all. And also follows the established pattern of previously publishing the other schemas.
