### ISSUE TITLE
[CT-2947] [Bug] Ephemeral model should refresh when a new column is added

### ISSUE THREAD

**Issue by BrJan** [dbt-labs/dbt-core#8334]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Compiled code:
`with __dbt_cte_ephemeral_model as (
select * from some_source_model
)
with primary_upstream_model as (select * from upstream_model)
, ephemeral_model as (select * from __dbt_cte_ephemeral_model)
select
*
from primary_upstream_model`

### Expected Behavior

Compiled code:
`with __dbt_cte_ephemeral_model as (
select * from some_source_model
)
, primary_upstream_model as (select * from upstream_model)
, ephemeral_model as (select * from __dbt_cte_ephemeral_model)
select
*
from primary_upstream_model`

### Steps To Reproduce

Run this:
`with primary_upstream_model as (select * from upstream_model)
, ephemeral_model as (select * from ephemeral_model)
select
*
from primary_upstream_model`

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

The root seems to be that when DBT compiles an ephemeral model, it should adjust the rest of the model imports to account for the added CTE.

A full refresh should happen whenever a column is added; it also shouldn't fail as an invalid identifier.

**Comment by dbeatty10** [comment]
Thanks for reaching out @BrJan !

Could you share the following?
- an example source code for an ephemeral model that leads to this problem
- dbt commands you are using
- the database adapter you are using (e.g., bigquery, snowflake, databricks, etc)

**Comment by dbeatty10** [comment]
Also, which version of dbt are you seeing this in?

I just remembered this looks like https://github.com/dbt-labs/dbt-core/issues/8213 and https://github.com/dbt-labs/dbt-core/issues/8217 which were fixed in [dbt-core 1.5.4](https://github.com/dbt-labs/dbt-core/blob/1.5.latest/CHANGELOG.md#dbt-core-154---july-28-2023)

**Comment by jeremyyeo** [comment]
This is resolved - I think Brian opened up an accidental dupe since the customers ticket contained 2 issues (the first of which was this, which is fully resolved, the second of which is regarding contracts and thus has nothing to do with this whatsoever).
