### ISSUE TITLE
[CT-2949] [Feature] Graph operator for selecting parents / children, but not specified models

### ISSUE THREAD

**Issue by jaklan** [dbt-labs/dbt-core#8340]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Hi, I would like to figure out a local development flow utilising the new `dbt` feature - [`dbt clone`](https://docs.getdbt.com/reference/commands/clone). To mimic the behaviour of `--defer`, I need to run the `clone` command only for upstream dependencies of modified models to create views in my personal schemas in `dev` database (we overwrite the `generate_schema_name` macro for that).

To achieve it today, I have to run:

```
dbt clone --select +model_a +model_b --exclude model_a model_b --state path/to/artifacts
```
or
```
dbt clone --select +state:modified --exclude state:modified --state path/to/artifacts
```

which is pretty inconvenient. It would be much easier if we introduce a new graph operator not to include specified models, so we could run e.g.:
```
dbt clone --select ++model_a ++model_b --state path/to/artifacts
```
or
```
dbt clone --select ++state:modified --state path/to/artifacts
```

### Who will this benefit?

`dbt` users using `dbt clone` (but not only)

**Comment by dbeatty10** [comment]
> I would like to figure out a local development flow utilising the new `dbt` feature - [`dbt clone`](https://docs.getdbt.com/reference/commands/clone).

Hey @jaklan, it's great to see that you're exploring the `dbt clone` command! Thanks for sharing your thoughts on it and suggesting ways to make it even better 👑.

I see that the following command is a bit longer and includes an extra command-line option compared to what you suggested:
```
dbt clone --select +state:modified --exclude state:modified --state path/to/artifacts
```

However, I don't think it's too complicated. We're very interested in hearing more about any difficulties you might have with it and how it affects your development process. Let us know!

**Comment by jaklan** [comment]
Also regarding `dbt clone` - if we ask our users to use `dbt clone` as the default approach for local development, they would have to remember to use `exclude` every time they introduce a new model to avoid errors like:
```
17:05:25  Completed with 1 error and 0 warnings:
17:05:25
17:05:25  Database Error in model model (models/model.sql)
17:05:25    Could not find parent table for alias "database.schema.model".
17:05:25    compiled Code at target/run/project/models/model.sql
```
So as I mentioned above - it's not about an unresolvable issue, but simply about improving the UX.

**Comment by graciegoheen** [comment]
Hey @jaklan - totally understand why it's frustrating to remember to use `exclude` every time. Have you looked at all at adding a [YAML selector](https://docs.getdbt.com/reference/node-selection/yaml-selectors) to capture this logic? That way, you could define and name the selector that captures `--select +state:modified --exclude state:modified` which would simplify the command developers need to use on the command line.

**Comment by jaklan** [comment]
Hi @graciegoheen - yes, that would work for that concrete example, but wouldn't work when you want to specify the model you currently work on directly. The new operator (like proposed `++`) would simply cover all such use-cases, with no need to think about any workarounds.

**Comment by graciegoheen** [comment]
Got it! I don’t think this is something that we’re going to prioritize in the short term since there is a working solution (albeit verbose). Additionally, I don't think the `++` shorthand is clear enough for it to be worth the addition. 

If we can come up with a shorthand that feels simple and straightforward, then maybe we would pick this up in the future, but I'm going to close this out for now.

**Comment by jaklan** [comment]
>  I don't think the ++ shorthand is clear enough for it to be worth the addition.

Tbh I find it very "simple and straightforward" - it utilises the `+` operator which is commonly know and highlights the fact these two are very similar in behaviour, they just differ whether selected models should be included or excluded.

I'm pretty disappointed with the decision to close the issue - we really want to start utilising `dbt clone`, but without such operator it would just cause an additional support headache on our side. It's also especially disappointing because of the fact it's almost a no-brainer to add it to `dbt-core` - if you don't have manpower to implement that at the moment, let's just agree on the syntax, mark it as `help_wanted`, and allow us (as community) to provide the proper MR.

It's also about the lack of consistency, as I raised the MECE point previously:

> Hi @dbeatty10, that's all about the user experience. Recently new selectors were introduced to [make `state` selection MECE](https://github.com/dbt-labs/dbt-core/pull/7773), that's a similar issue - to apply MECE principle to model selection as well. And the moment it's not fulfilled, because there's no way to select a subset of models not including the specified models without using `exclude` - `dbt clone` is just a sample use-case when it could be useful.

**Comment by graciegoheen** [comment]
I appreciate the feedback and would not be opposed to re-opening if we can come up with a clearer syntax for this.

Let me attempt to explain why I don't feel that the `++` operator is straightforward.
Our `+` graph operator is currently defined as such: 
> The "plus" operator
If placed at the front of the model selector, + will select all parents of the selected model. If placed at the end of the string, + will select all children of the selected model.

Visually, I don't equate adding an additional + with "exclude the selected model". 

While I understand the desire to have a clear shorthand for "selecting parents / children, but not specified models" for folks who want to do this often, I also want to ensure it's not confusing for new users.

**Comment by jaklan** [comment]
@graciegoheen for me it's all about the docs. If we have a look at the current definition - imho it's not really clear, because it mentions `select all parents / children of the selected model`, but doesn't say anything if the model itself is included or excluded (I would even say it suggests it's not, because there's no phrase like "and" / "additionally" used there).

If we rephrase it e.g. this way:

> The "plus" (+) operator
If placed at the front of the model selector, + will select all parents of the selected model and the model itself. If placed at the end of the string, + will select all children of the selected model and the model itself.

> The "double plus" (++) operator
If placed at the front of the model selector, ++ will select all parents of the selected model, but not the model itself. If placed at the end of the string, ++ will select all children of the selected model, but not the model itself.

it should be pretty straightforward.

I proposed `++`, because it's pretty easy to remember and there's no need to introduce any new char to operator syntax. It's also quite obvious how to introduce it in another contexts, e.g. `@@`. It's also symmetrical - just compare:
`3++model`, `model++`, `model++2`  
to e.g. 
`3+!model`, `model+!`, `model+!2`  
the latter imho just looks much more confusing (and the similar feeling would be valid for any mix of two different chars).

**Comment by graciegoheen** [comment]
Apologies, I did not include the full documentation for the + operator, which includes a handful of examples that provide clarity on the + operator including the selected model as well as the parents / children.
<img width="822" alt="Screenshot 2023-08-25 at 12 12 42 PM" src="https://github.com/dbt-labs/dbt-core/assets/53586774/05da7827-5f74-4647-be46-c400cd2eaec0">

I'm more than happy to open an issue in the docs repo to clarify this behavior if you believe it's still unclear. 

While I greatly appreciate your opinion here, I am still not convinced that using the same operator (just doubled) to capture a different definition is straightforward.

**Comment by jaklan** [comment]
@graciegoheen yeah yeah, I was just referring to the description part, examples make it more clear, but imho these two (desc and examples) are a bit unaligned with each other.

About the operator - I would phrase it differently: "to capture a different variant of the same operator". But generally - `++` is just a proposal which I personally find quite logical, coherent, and easy to use, but at the end of the day - I don't care so much if it's gonna be `++`, `+!`, `+( ͡° ͜ʖ ͡°)` or whatever, I just wish we can agree on _anything_. As for now no alternatives were proposed anyway, it would be easier to come up with something else if you can give an example of syntax which makes more sense to you.
