### ISSUE TITLE
[CT-2951] [Feature] All nodes should be groupable

### ISSUE THREAD

**Issue by gwenwindflower** [dbt-labs/dbt-core#8343]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Community members brought up that it would be useful to group sources, while it's true this isn't really necessary for common patterns in a multi-project setting, in a monorepo it's actually a really useful safeguard to prevent something like this:

Monorepo, 2 teams
Platform group: owns staging models and handles landing data
Transformation group: can access staging models and builds marts

Transformation team could still `source()` something and totally bypass protections. I think it's reasonable to expect that you can control access to any node with groups.

### Describe alternatives you've considered

Again, in a multi-project setting where you have more separation I don't think this is critical, but a *lot* of people are going to sort out how they mesh stuff using groups first for some period of time if not perpetually.

### Who will this benefit?

People using groups/access/governance in a monorepo.

### Are you interested in contributing this feature?

Unfortunately no capacity for this right now.

### Anything else?

I love you all. ❤️

**Comment by gwenwindflower** [comment]
via this Community Slack discussion https://getdbt.slack.com/archives/C2JRRQDTL/p1691497125957839

**Comment by jtcohen6** [comment]
@gwenwindflower Thanks for opening! There's been some related conversation in this issue: https://github.com/dbt-labs/dbt-core/issues/7750

What do you think of consolidating the two conversations? The only node types that are intentionally ungroupable today are `sources` and `exposures`, and the focus of this issue seems to be `sources` as well.

**Comment by gwenwindflower** [comment]
closing to collapse into #7750
