### ISSUE TITLE
[CT-2961] Add flag to inform partial parsing to skip file diff computation

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#8363]
In cloud environments, computing the file diff prior to partial parsing may be a costly operation. Provide a flag to skip computing a file diff that can be used to speed up parsing if the execution environment knows that no files have changed between dbt invocations.

**Comment by jtcohen6** [comment]
Let's hide the flag from the CLI `--help` text, since I think it will be confusing clutter for 99% of end users. Same as we did for #7911
