### ISSUE TITLE
[CT-2977] Fix untyped functions in context/macro_resolver.py (mypy warning)

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#8393]
### Problem
When we hit a mypy error the console is flooded with mypy warnings as well.  Clean up the warning to improve developer experience. 

### Reproduction
Simply force a mypy error (change types) and the warnings will be generated.

### Relevant Output
```
core/dbt/context/macro_resolver.py:46: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]

```

**Comment by gshank** [comment]
Fixed in #8416
