### ISSUE TITLE
[CT-2984] Fix untyped functions in parser/common.py (mypy warning)

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#8400]
### Problem
When we hit a mypy error the console is flooded with mypy warnings as well.  Clean up the warning to improve developer experience. 

### Reproduction
Simply force a mypy error (change types) and the warnings will be generated.

### Relevant Output
```
core/dbt/parser/common.py:181: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]

```

**Comment by gshank** [comment]
Fixed in #8416
