### ISSUE TITLE
[CT-2989] [Bug] --log-format json should imply --no-use-colors

### ISSUE THREAD

**Issue by pdebelak** [dbt-labs/dbt-core#8405]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running `dbt --log-format json run` the json message's "msg" field can include terminal color escapes like the following:

```
{"data": {"keyboard_interrupt": false, "num_errors": 0, "num_warnings": 0}, "info": {"category": "", "code": "Z030", "extra": {}, "invocation_id": "b2cb1694-7afc-469f-af08-22c37c793426", "level": "info", "msg": "\u001b[32mCompleted successfully\u001b[0m", "name": "EndOfRunSummary", "pid": 1, "thread": "MainThread", "ts": "2023-08-14T20:53:17.931454Z"}}
```

### Expected Behavior

Given the log format is json, I would expect that terminal color escape codes shouldn't be present in the out as if `--no-use-colors` was passed so you get output like:

```
{"data": {"keyboard_interrupt": false, "num_errors": 0, "num_warnings": 0}, "info": {"category": "", "code": "Z030", "extra": {}, "invocation_id": "dc6bab70-e8b9-40aa-9328-e60b237eabd3", "level": "info", "msg": "Completed successfully", "name": "EndOfRunSummary", "pid": 1, "thread": "MainThread", "ts": "2023-08-14T20:59:29.702170Z"}}
```

### Steps To Reproduce

Run `dbt --log-format json run` and see color escapes like `\u001b[32m` included in some of the messages.

### Relevant log output

```shell
See above
```

### Environment

```markdown
- OS: debian buster
- Python: 3.8.17
- dbt: 1.6.0
```

### Which database adapter are you using with dbt?

redshift

**Comment by jtcohen6** [comment]
@pdebelak Thanks for opening!

I have two thoughts here:
- There is a legitimate use case for `--log-format json` while preserving `--use-colors`. We do this in dbt Cloud, to consume structured logs on the backend, while still presenting human-friendly colorized text-formatted logs in the UI.
- Creating implicit behavior that mixes multiple flags together feels like more confusion than it's worth. I'd rather keep the two things neatly separated. It doesn't seem like a big lift to set both configs (via flag or environment variable), if you're already setting one.

I'm going to close this as `wontfix`
