### ISSUE TITLE
[CT-3005] Support dictionary of additional configs in `dbt_project.yml`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#8438]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

Allow setting a dictionary of arbitrary configs in `dbt_project.yml`, which are to be read & used by dbt Cloud.

We don't need to validate the keys in this dictionary, nor store them in the project config class.

Let's call this dictionary `dbt-cloud`:
```yml
# dbt_project.yml
dbt-cloud:
  project-id: 1234
  ...
```

### Acceptance criteria

It is possible to set a dictionary of arbitrary configs in `dbt_project.yml`, as metadata for dbt Cloud.

### Impact to Other Teams

Cloud CLI impacted (see jira ink below), ensure this is completed within this sprint

### Context

[internal slack thread](https://dbt-labs.slack.com/archives/C044WU55X7Y/p1691671419131039)
[internal jira ticket](https://dbtlabs.atlassian.net/browse/CLI-9)

**Comment by graciegoheen** [comment]
Open question:
- how will they access these keys? are they intending on parsing these themselves?
