### ISSUE TITLE
[CT-3014] [Bug] Project-level config is Undefined and cannot be deepcopied

### ISSUE THREAD

**Issue by juliandelgados** [dbt-labs/dbt-core#8460]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

**Version**
Core:
  - installed: 1.6.0
  - latest:    1.6.0 - Up to date!
Plugins:
  - bigquery: 1.6.1 - Up to date!

**Location**
dbt_project.yml

The following dbt_project.yml configuration returns `TypeError: cannot pickle 'Undefined' object` after executing: `dbt run --target prod`

```
models:
  project_name:    
    +hours_to_expiration: "{{ 72 if target.name=='dev' else NULL}}"
    staging:
      +dataset: staging
      +materialized: view
```

While setting hours_to_expiration to NULL is completely valid

```models:
  project_name:    
    +hours_to_expiration: NULL
    staging:
      +dataset: staging
      +materialized: view
```

### Expected Behavior

Allow `+hours_to_expiration: "{{ 72 if target.name=='dev' else NULL }}"` to evaluate to NULL

### Steps To Reproduce

- Be connected to a BigQuery db
- Configure the dbt_project.yml accordingly
- Run `dbt run` using target.name=='dev' vs any other target name

### Relevant log output

```shell
TypeError: cannot pickle 'Undefined' object
```

### Environment

```markdown
- OS:macOS Ventura 13.5
- Python: 3.9.6
- dbt: 1.6.0 / bigquery plugin => bigquery: 1.6.1
```

### Which database adapter are you using with dbt?

bigquery

**Comment by jtcohen6** [comment]
Hey @juliandelgados, sorry you're running into this confusing error.

I recommend replacing your use of the word `NULL` (which means "no value" in SQL, JSON, and some other languages) with the word `none` (which means "no value" in Jinja, Python, etc).

This works for me locally:
```yml
# dbt_project.yml
models:
  my_dbt_project:    
    +hours_to_expiration: "{{ 72 if target.name=='dev' else none }}"
```
Though this also seems to work:
```yml
...
    +hours_to_expiration: "{{ 72 if target.name=='dev' else toyaml(null) }}"
```

How I'm testing:
```sql
-- models/my_model.sql
-- {{ config.get("hours_to_expiration") }}
-- {{ config.get("hours_to_expiration") is none }}
```
```
$ dbt compile -s my_model --target prod
...
09:07:29  Compiled node 'my_model' is:
-- models/my_model.sql
-- None
-- True
```
```bash
$ dbt --quiet list --select my_model --target prod --output json --output-keys config | jq .config.hours_to_expiration
null
```
