### ISSUE TITLE
[CT-3019] TestShow::test_numeric_values, TestShow::test_numeric_values_with_nulls are flaky

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#8470]
Full path: tests/functional/show/test_show.py::TestShow::test_numeric_values
Examples of flakiness:
- [Integration tests during 1.6.1 release](https://github.com/dbt-labs/dbt-core/actions/runs/5944306181/job/16121348922)
- [Integration tests during backport to 1.6.latest](https://github.com/dbt-labs/dbt-core/actions/runs/5943994522/job/16120344388)

**Note**: Thus far I've only seen this on branch 1.6.latest

**Comment by emmyoop** [comment]
This flaked on the nightly release test that runs off main https://github.com/dbt-labs/dbt-core/actions/runs/6122803796/job/16619476620

**Comment by emmyoop** [comment]
Tests still consistently fail on all releases on `main` and `1.6.latest`.

More details [on slack](https://dbt-labs.slack.com/archives/C044WU55X7Y/p1694619832348239)
