### ISSUE TITLE
[CT-3025] [Feature] Namespace pre/post hooks

### ISSUE THREAD

**Issue by gradyela** [dbt-labs/dbt-core#8484]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Similar to model pre/post hooks, it would be nice to add pre/post hooks to a given model namespace.  For example, when using redshift, users need to be granted `usage` on a schema in addition to being granted `select` on individual models within that schema.  By adding +schema: foo to a given model or model group, a new schema gets created.  Even though grants allow users to query that table, schema permissions haven't been granted, making for a somewhat clunky experience anytime a new schema gets created.

### Describe alternatives you've considered

I've added post-hook operations that run the grant using `{{ this.schema }}`, and it works, but that ends up being a little overkill as the command only ever needs to be run once.  Being run once per run is still more than necessary, but way less than once per model in that schema.

Additionally it opens the possibility of running bulk grants after the last model of a namespace runs, which could lead to some time savings (grants aren't super intensive, but running grants 5-10 times vs 100 has to yield some time savings I'd imagine).

### Who will this benefit?

This would benefit all DBT users, but specifically new DBT users, and organizations that use namespacing frequently.  If built and then configured by new DBT users, database users downstream of DBT can be automatically granted access to schemas and tables out of the box, making for a better, unified experience.

### Are you interested in contributing this feature?

Sure, why not.

**Comment by graciegoheen** [comment]
Hello! Thanks for opening this issue. 

I'm wondering if you might be able to use the `schemas` variable with an `on-run-end` hook to bulk apply grants. Docs linked [here](https://docs.getdbt.com/reference/dbt-jinja-functions/schemas). 

Let me know if that would fit your use case or if there's additional context I'm missing :)
