### ISSUE TITLE
[CT-3026] [Bug] Intermittent failure

### ISSUE THREAD

**Issue by fivetran-dmitryzelenov** [dbt-labs/dbt-core#8486]
### Is this a new bug in dbt-core?

- [ ] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Sometimes we face the following error in our jobs running on the regular schedule:
> dbt compile
```
Running with dbt=1.5.1
13:30:29  Unable to do partial parsing because saved manifest not found. Starting full parse.
13:34:43  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 13 unused configuration paths:
- models.analytics.marts.testing.hourly
- models.analytics.marts.accounting_finance.hourly
- models.analytics.marts.accounting_finance
- models.analytics.marts.pc_fivetran_db.threepn_public.hourly
- models.analytics.marts.advertising
- models.analytics.staging.pattern_db
- models.analytics.marts.pc_fivetran_db.amaczar_public.hourly
- models.analytics.marts.advertising.hourly
- models.analytics.marts.public
- models.analytics.marts.business_intelligence.hourly
- models.analytics.marts.testing
- models.analytics.marts.pattern_share_db.public
- seeds.dbt_project_evaluator.dbt_project_evaluator_exceptions
13:34:54  Found 4687 models, 69 tests, 5 snapshots, 0 analyses, 725 macros, 1 operation, 1 seed file, 4810 sources, 49 exposures, 0 metrics, 0 groups
13:34:55  
13:35:22  Encountered an error:
Database Error
  dictionary changed size during iteration
```

another job example:
> dbt run --selector hourly__selector
```
Running with dbt=1.5.1
10:32:52  Unable to do partial parsing because saved manifest not found. Starting full parse.
10:35:08  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 13 unused configuration paths:
- models.analytics.marts.public
- models.analytics.marts.accounting_finance.hourly
- models.analytics.marts.pc_fivetran_db.threepn_public.hourly
- models.analytics.marts.advertising
- models.analytics.marts.advertising.hourly
- models.analytics.marts.accounting_finance
- models.analytics.marts.pattern_share_db.public
- models.analytics.staging.pattern_db
- models.analytics.marts.business_intelligence.hourly
- models.analytics.marts.testing
- models.analytics.marts.pc_fivetran_db.amaczar_public.hourly
- models.analytics.marts.testing.hourly
- seeds.dbt_project_evaluator.dbt_project_evaluator_exceptions
10:35:22  Found 4699 models, 74 tests, 5 snapshots, 0 analyses, 725 macros, 1 operation, 1 seed file, 4820 sources, 49 exposures, 0 metrics, 0 groups
10:35:22  
10:35:51  
10:35:51  Finished running  in 0 hours 0 minutes and 28.62 seconds (28.62s).
10:35:51  Encountered an error:
Database Error
  dictionary changed size during iteration
```

### Expected Behavior

The dbt commands should never fail with the intermittent error

### Steps To Reproduce

The issue is reproduced very rarely.

### Environment

```markdown
- OS: Ubuntu 22.04
- Python: 3.10.12
- dbt: 1.5.1, snowflake: 1.5.2
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

The issue is reproduced very rarely, once per 3 days for hourly jobs, on different dbt commands: **dbt compile** and **dbt run**.

**Comment by dbeatty10** [comment]
Thanks for reaching out about this @fivetran-dmitryzelenov !

Doing some quick Googling, "dictionary changed size during iteration" looks like an error raised by Python rather than one by Snowflake.

Are you able to check your logs to see what dbt model, test, etc it is raising that error? From there, I'm wondering if there's a Jinja macro that's being executed that is mutating a Python dictionary during iteration. It could be a macro within your project, or it could be a macro within a package that you have installed. It might also be plain ol' Python in dbt too.

Could you check your logs to see if you can find more context that we can use to try to discover the root cause of this error? Any additional detail you can provide would be helpful.

**Comment by dbeatty10** [comment]
@rudeb0y we haven't been able to reproduce this error yet, and we don't have any leads for the possible root cause(s).

Any additional detail you or @fivetran-dmitryzelenov can provide would be helpful.

In particular:

> Are you able to check your logs to see what dbt model, test, etc it is raising that error? From there, I'm wondering if there's a Jinja macro that's being executed that is mutating a Python dictionary during iteration. It could be a macro within your project, or it could be a macro within a package that you have installed. It might also be plain ol' Python in dbt too.
> 
> Could you check your logs to see if you can find more context that we can use to try to discover the root cause of this error?
