### ISSUE TITLE
[CT-3048] [Feature] <schema.yml file to accept macro for dynamic test naming>

### ISSUE THREAD

**Issue by gautierdp** [dbt-labs/dbt-core#8519]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The generic test configuration parser currently does not support using custom macros to populate configuration values within the dbt schema.yml file.
 
This feature would allow that allowing the capability required for dynamic test naming using jinja/macros. Currently the only way to achieve this is by duplicating a code which makes the dbt project harder to maintain on a large scale.

### Describe alternatives you've considered

I have been forced to duplicated much of the schema.yml file code to simply run the tests with an other tag/name to achieve the desired result.

### Who will this benefit?

This with benefit anyone using dbt for analytics who are running tests with similar configurations.

**Comment by dbeatty10** [comment]
Thanks for raising this idea @gautierdp !

Could you give a more detailed example of your workaround as well as an example of how your proposal would solve it instead?

That will help us get a better look at the problem you are trying to solve.
