### ISSUE TITLE
[CT-3092] Support optional `label` property for semantic layer objects

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#8595]
## Context

We currently allow for specifying an optional label property on [metric nodes](https://github.com/dbt-labs/dbt-core/blob/b39eeb328c9a245f21b54fb48f2761ad03d4d6ad/core/dbt/contracts/graph/nodes.py#L1463). This wasn't defined in [dbt-semantic-interfaces](https://github.com/dbt-labs/dbt-semantic-interfaces) previously because it was not identified as need in [MetricFlow](https://github.com/dbt-labs/metricflow). MetricFlow would like to begin using this property, and would like it to exist on more objects. Thus labels are being added to a number of DSI protocols as defined in https://github.com/dbt-labs/dbt-semantic-interfaces/issues/143. To begin parsing and propagating this labels on `Metric` nodes, `SemanticModel` nodes, `Dimensions`, and `Measures`.

## Acceptance Criteria

- A label can be specified on `Metric` nodes, `SemanticModel` nodes, `Dimensions`, and `Measures`
- labels on `Metric` nodes, `SemanticModel` nodes, `Dimensions`, and `Measures` are serialized into the `semantic_manifest.json`

### Blocked By
https://github.com/dbt-labs/dbt-semantic-interfaces/issues/143.

**Comment by QMalcolm** [comment]
This "technically" isn't blocked. We could add the labels to the noted classes. However, we won't be able to serialize them to the `semantic_manifest.json` until the the DSI releases the changes.

**Comment by emmyoop** [comment]
@QMalcolm looking at the blocking issue, is it accurate that `Entity` should also support an optional label?
