### ISSUE TITLE
[CT-3098] [Bug] Columns are not exported in the json output of dbt list

### ISSUE THREAD

**Issue by frco9** [dbt-labs/dbt-core#8601]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have define a model with columns and an enforced contract. 
When using `dbt --quiet list --resource-types model --output json` it outputs models definition without its columns

### Expected Behavior

When using the list and has columns were defined, I was expecting to get the columns definition. 

### Steps To Reproduce

Given this model config : 
```
models:
  - name: dataset_test1
    config:
      materialized: table
      contract: { enforced: true }
    columns:
      - name: CTRY_C
        description: This is a column
        data_type: varchar
```

Then run the following command : 
`dbt --quiet list --resource-types model --output json`

### Relevant log output

```shell
{
	"name": "dataset_test1",
	"resource_type": "model",
	"package_name": "demo_dbt",
	"original_file_path": "models/example/dataset_test1.sql",
	"unique_id": "model.demo_dbt.dataset_test1",
	"alias": "dataset_test1",
	"config": {
		"enabled": true,
		"alias": null,
		"schema": null,
		"database": null,
		"tags": [],
		"meta": {},
		"group": null,
		"materialized": "table",
		"incremental_strategy": null,
		"persist_docs": {},
		"quoting": {},
		"column_types": {},
		"full_refresh": null,
		"unique_key": null,
		"on_schema_change": "ignore",
		"grants": {},
		"packages": [],
		"docs": {
			"show": true,
			"node_color": null
		},
		"contract": {
			"enforced": true
		},
		"post-hook": [],
		"pre-hook": []
	},
	"tags": [],
	"depends_on": {
		"macros": ["macro.demo_dbt.get_latest_snapshot", "macro.demo_dbt.get_reference_ts", "macro.dbt.dateadd"],
		"nodes": []
	}
}
```
```


### Environment

```markdown
- OS: MacOS 13.4
- Python: 3.9.9
- dbt: 1.5.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

athena: 1.5.1

**Comment by jtcohen6** [comment]
@frco9 Try:
```
dbt --quiet list --resource-types model --output json --output-keys name columns # whatever else you want
```
```json
{"name": "my_model", "columns": {"id": {"name": "id", "description": "This is my id column", "meta": {}, "data_type": null, "constraints": [], "quote": null, "tags": []}}}
```

(This is mentioned in [the docs](https://docs.getdbt.com/reference/commands/list#:~:text=Listing%20JSON%20output%20with%20custom%20keys), though only briefly)

**Comment by frco9** [comment]
It works Thanks ! I thought it would only apply to keys already shown, but indeed it is not !
