### ISSUE TITLE
[CT-3102] [Bug] semantic models don't support partial parsing

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-core#8609]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Semantic models don't appear to support partial parsing -- in working through #8589, once semantic models were added to the `dbt ls` command output, tests were failing related to partial parsing. It turns out that the `SemanticModel` [class](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/contracts/graph/nodes.py#L1568) does not contain any comparison methods to detect changes (namely `same_contents`) that allow for partial parsing

### Expected Behavior

SMs are parsed with consistent behavior to other node types

### Steps To Reproduce

1. create SM
2. update it
3. run dbt compile
4. notice no changes

### Environment

```markdown
- OS: TJ mac
- Python: 3.10
- dbt: 1.7.0b2
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Thanks for reporting this @dave-connors-3 !

@Jstein77 or @QMalcolm -- is there any reason why we wouldn't want to match the expected behavior that @dave-connors-3 described?

**Comment by jtcohen6** [comment]
> (namely `same_contents`) that allow for partial parsing

I was under the impression that this method is used for `state:modified` comparisons (Slim CI), but not for partial parsing. There may be something else afoot!

@dave-connors-3 Any chance you could include your full reproduction case? (yaml you started with, commands you ran, yaml you changed it to)

**Comment by dbeatty10** [comment]
@dave-connors-3 looking forward to seeing you at the San Diego edition of Coalesce!

Would you be willing to walk me though a more detailed reproduction case? We discovered a couple other issues related to partial parsing (https://github.com/dbt-labs/dbt-core/issues/8859 and https://github.com/dbt-labs/dbt-core/issues/8860), and it would good to tackle the issue you are reporting at the same time.

What we're going for a is a step-by-step set of instructions and engineer could use to both trigger the problem and then confirm it's fixed afterwards (like [this](https://github.com/dbt-labs/dbt-core/issues/8860#issuecomment-1764753405)).

I'm willing to write it up if you can walk me through it in-person.

**Comment by dbeatty10** [comment]
@dave-connors-3 thanks for jamming on this with me in San Diego! 🏖️

Based on what we looked at together, we agreed that the (lack of changes) you saw within `manifest.json` is likely  covered by https://github.com/dbt-labs/dbt-core/issues/8859, so I'm going to close this in favor of that issue.

Thanks again -- you rock 🎸
