### ISSUE TITLE
[CT-3116] [Feature] Try-catch syntax for macros

### ISSUE THREAD

**Issue by StevenGrzybowski** [dbt-labs/dbt-core#8633]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

allow for the use of try-catch  in macros - this is especially useful when using macros that are in a loop and requires  a single step to run hundreds of times. 

Instead of the entire macro crashing when a given iteration of a loop fails, it would be extremely helpful to be able to continue on with the loop and get all of the errors at the end. 

Right now , when adding something like a global test into all of my models, I end up having to keep running everything each time & can only find one failure each run, which can result in multiple hour+ long runs  to find a handful of errors.  This is especially bad when using a macro that executes queries

### Who will this benefit?

Anybody that wants to build better error handling for macros , anyone that wants to build global tests beyond what comes out of the box in dbt

**Comment by jtcohen6** [comment]
Throwback to a much older issue:
- https://github.com/dbt-labs/dbt-core/issues/1968

(not a final answer, just wanted to link the related conversation!)

**Comment by dbeatty10** [comment]
Thanks for bringing this suggestion @StevenGrzybowski !

Could you provide a more concrete example, ideally along with the relevant example model code + a custom global test that you mentioned? That would help us better consider the cases where your proposal is meant to address.

**Comment by kverburg** [comment]
I could write one:

I have this package that other teams can install. It builds some models, but there is also the option to add columns to the models. For that I use a macro and a variable which they can set in the project.yml. The variable should point to a model. If they don't provide the variable, that fine, the macro won't do much.  If they provide something will the marco use that value from that var as input and pass it to a ref function.

But if they provide something that is not a model in their project, the macro will fail on the ref error. I don't find that ref error very helpful in this case and would like to be able try-catch for the existence of that model and trow a custom error that gives more information to the user.

I can probably also achieve something similar by accessing the graph, but a try would be way simpler.

**Comment by dbeatty10** [comment]
Thanks for describing that use case @kverburg !

I can see the desire to catch that error within your package and then immediately re-raise with a more detailed error message for the user. But it probably isn't a use case that makes this a high-priority feature for us.

We're still open to hearing examples for try/catch though -- we'd just need some really compelling ones in order to prioritize this, which we haven't seen to-date.
