### ISSUE TITLE
[CT-3117] [Bug] Path to misconfigured snapshot file is missing in error message

### ISSUE THREAD

**Issue by osu-d** [dbt-labs/dbt-core#8634]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Using `dbt snapshot --models` targeting a correctly configured model while having a wrongly configure model *other* than the target model in the `/snapshots directory` produces an unhelpful error. For this issue *model_A* is the *correctly* configured target snapshot model and *model_B* is the *wrongly* configured model.

### Expected Behavior

`dbt snapshot --models model_A`
18:05:29  Running with dbt=1.6.1
18:05:29  Registered adapter: redshift=1.6.1
18:05:29  Encountered an error:
Parsing Error
  at path ["/snapshots/model_B"]: A snapshot configured with the check strategy must specify a check_cols configuration.

### Steps To Reproduce

1. Have one correctly configured model
2. Have one incorrectly configured model
3. `dbt snapshot --models model_A`
4. error

### Relevant log output

```shell
dbt snapshot --models model_A
18:05:29  Running with dbt=1.6.1
18:05:29  Registered adapter: redshift=1.6.1
18:05:29  Encountered an error:
Parsing Error
  at path []: A snapshot configured with the check strategy must specify a check_cols configuration.
```

### Environment

```markdown
- OS: macOS Ventura
- Python: Conda (Python 3.10.12
- dbt: 1.6.1
```

**Comment by dbeatty10** [comment]
Thanks for opening this up @osu-d !

dbt parses all the files in your project and makes sure they follow all the configuration rules _prior_ to focusing on a single node when you specify `--models model_A`.

So in that sense, dbt is behaving the way we expect.

But you bring up a very good point about the error message being unhelpful by not giving the path to the misconfigured file.

dbt 1.3 included the path to the relevant file:

```shell
$ dbt snapshot

22:52:10  Running with dbt=1.3.4
22:52:11  Encountered an error:
Parsing Error in snapshot model_b (snapshots/model_b.sql)
  at path []: A snapshot configured with the check strategy must specify a check_cols configuration.```
```

dbt 1.4 onwards doesn't:

```shell
$ dbt snapshot

22:50:55  Running with dbt=1.4.6
22:50:56  Encountered an error:
Parsing Error
  at path []: A snapshot configured with the check strategy must specify a check_cols configuration.
```

### Reprex

`snapshots/model_b.sql`

```sql
{% snapshot model_b %}

{{
    config(
      target_database='db',
      target_schema='main',
      unique_key='id',
      strategy='check',
    )
}}

select 1 as id, {{ dbt.current_timestamp() }} as now

{% endsnapshot %}
```

```shell
dbt snapshot
```

### Acceptance criteria

We should do either one of the following:
1. Restore the same / similar error message as was in dbt 1.3, or
2. Replace `at path []` with `at path ["snapshots/model_b.sql"]`

**Comment by dbeatty10** [comment]
Closing in favor of https://github.com/dbt-labs/dbt-core/issues/8276 since they report the same underlying issue.
