### ISSUE TITLE
[CT-3126] 1.6+ postgres failing randomly with views

### ISSUE THREAD

**Issue by patkearns10** [dbt-labs/dbt-core#8660]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

in 1.6 with Postgres only (in dbt Cloud), postgres view models are failing during rename_relation step. I don't think it is that macro per se, but either a view is cascade dropped or non-existent but dbt thinks it exists or something. 
https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1694488560329019
New video of views with no dependencies failing.
https://www.loom.com/share/0aa19aa5e84e4837ad6769b71884cd83

TL,DR: the screenshot I have above with SUCCESS/FAILURE shows what failures look like. No error message, just
```
Using postgres connection "model.my_new_project._0__10"
On model.my_new_project._0__10: alter table "postgres"."dbt_pkearns"."_0__10" rename to "_0__10__dbt_backup"
SQL status: ALTER TABLE in 0.0 seconds
Timing info for model.my_new_project._0__10 (execute): 00:53:34.469195 => 00:53:43.129619
On model.my_new_project._0__10: ROLLBACK
On model.my_new_project._0__10: Close
3 of 1001 ERROR creating sql view model dbt_pkearns._0__10 ..................... [ERROR in 8.82s]
```
it seems psuedo-random. Running 100 or 1000 models, every few runs a different model fails

### Expected Behavior

View is built normally.

### Steps To Reproduce

1.6+
dbt-postgres
create 100 views
hit run in the IDE a few times
25% of the runs, a few views will fail to build

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

![Uploading Screenshot 2023-09-12 at 1.30.53 PM.png…]()

**Comment by nathaniel-may** [comment]
I might be running into this with my personal dbt project. I was able to reproduce it if I did a successful dbt run with a model materialized as a table, then changed that model's materialization to a view. That second run will fail, but a third run will pass. I can try to record details of an example if that helpful.

**Comment by mikealfare** [comment]
> I might be running into this with my personal dbt project. I was able to reproduce it if I did a successful dbt run with a model materialized as a table, then changed that model's materialization to a view. That second run will fail, but a third run will pass. I can try to record details of an example if that helpful.

That already sounds pretty close to a functional test. Let me read it back as an example to make sure I'm not missing something:

- Create a seed (`my_seed`) with columns (id, name)
- Create a table model (`my_model`) that is `{{ config(materialized='table') }} select * from {{ ref('my_seed') }}`
- Run: `dbt seed`
- 🌞 
- Run: `dbt run`
- 🌞 
- Update `my_model`: `{{ config(materialized='view') }} select * from {{ ref('my_seed') }}`
- Run: `dbt run`
- 💥 
- Run: `dbt run`
- 🌞 

We wouldn't care about the last two steps in the test case as we should never get there. But I'm including them for completeness.

**Comment by amychen1776** [comment]
@patkearns10 This is a pretty old issue but I was curious if this is still happening?

**Comment by patkearns10** [comment]
> @patkearns10 This is a pretty old issue but I was curious if this is still happening? I'm curious if we can close this issue out

@amychen1776  I brought this up for a customer long ago. Definitely not relevant to me anymore. Unsure if it is still happening!

**Comment by amychen1776** [comment]
haha make sense - Okay I'm going to close this fo rnow @patkearns10
