### ISSUE TITLE
[CT-3136] Modify Jira Issues to only run when label is `Team:Adapters"

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#8681]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

The core team is no longer on Jira.  Modify the jira workflows to only run when the label is `Team:Adapters`.

### Acceptance criteria

- When an issue is opened with the `Team:Adapters` label the issue gets cloned in Jira in the correct project
- When an issue is opened without the `Team:Adapters` label the issue does not get cloned in Jira
- When an open issue is labeled with `Team:Adapters` the issue gets cloned in Jira in the correct project
-  When an open issue is unlabeled with `Team:Adapters` the issue gets closed in Jira

### Impact to Other Teams

Adapters

### Will backports be required?

no

### Context

Currently we create the Jira issue in the archived project for core and when it has the `Team:Adapters` label it gets moved into the adapters Jira Project on the Jira side.  Since the core project is archived, we should just create the issue directly in the Adapters Project.

**Comment by mikealfare** [comment]
This is no longer relevant
