### ISSUE TITLE
[CT-3138] [Bug] Error: Invalid value for '--warn-error-options'

### ISSUE THREAD

**Issue by dylan-murray** [dbt-labs/dbt-core#8683]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When installing `dbt-core` into an environment where an older version of click is installed, `dbt-core` will throw a vague error `Error: Invalid value for '--warn-error-options': Cannot load YAML from type <class 'dbt.helper_types.WarnErrorOptions'>`. It seems `dbt-core` is pinning `click<9` which allows it to use older versions of click that it seems no longer compatible with. I think `dbt-core` should be pinning a minimum version requirement of click that plays well with the library.

### Expected Behavior

No error.

### Steps To Reproduce

Install `click==8.0.0`
Install the latest `dbt-core`
Attempt to use the dbt cli w/ a command `dbt ls` or something

### Relevant log output

```shell
Error: Invalid value for '--warn-error-options': Cannot load YAML from type <class 'dbt.helper_types.WarnErrorOptions'>
```

### Environment

```markdown
- OS: 
- Python: 3.9.1
- dbt-core: 1.6.3

pip freeze output
agate==1.7.1
asn1crypto==1.5.1
attrs==23.1.0
Babel==2.12.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.0.0
colorama==0.4.6
cryptography==41.0.4
dbt-core==1.6.3
dbt-extractor==0.4.1
dbt-semantic-interfaces==0.2.0
filelock==3.12.4
hologram==0.0.16
idna==3.4
importlib-metadata==6.8.0
isodate==0.6.1
jaraco.classes==3.3.0
Jinja2==3.1.2
jsonschema==3.2.0
keyring==24.2.0
leather==0.3.4
Logbook==1.5.3
MarkupSafe==2.1.3
mashumaro==3.8.1
minimal-snowplow-tracker==0.0.2
more-itertools==8.14.0
msgpack==1.0.5
networkx==3.1
oscrypto==1.3.0
packaging==23.1
parsedatetime==2.6
pathspec==0.11.2
platformdirs==3.8.1
protobuf==4.24.3
pycparser==2.21
pycryptodomex==3.19.0
pydantic==1.10.12
PyJWT==2.8.0
pyOpenSSL==23.2.0
pyrsistent==0.19.3
python-dateutil==2.8.2
python-slugify==8.0.1
pytimeparse==1.1.8
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
six==1.16.0
snowflake-connector-python==3.2.0
sortedcontainers==2.4.0
sqlparse==0.4.4
text-unidecode==1.3
tomlkit==0.12.1
typing_extensions==4.8.0
urllib3==1.26.16
zipp==3.17.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for raising this @dylan-murray !

Do you happen to know the minimum version of `click` that works?

**Comment by dylan-murray** [comment]
The minimum version it appears to work with is `click==8.0.2`.

**Comment by dbeatty10** [comment]
@dylan-murray opened #8684 with you as a co-author.
