### ISSUE TITLE
[CT-3139] [Feature] Export lineage to Apache Atlas (Microsoft Purview)

### ISSUE THREAD

**Issue by MiguelElGallo** [dbt-labs/dbt-core#8685]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

There are companies using DBT and Purview as the data catalog.
DBT already has lineage, idea is to add to DBT the capability to export the lineage using the Atlas API
https://learn.microsoft.com/en-us/purview/tutorial-atlas-2-2-apis

### Who will this benefit?

Any company using DBT, and Apache Atlas or Atlas based data catalog

### Are you interested in contributing this feature?

Need to know the internals of DBT lineage

**Comment by jtcohen6** [comment]
Hi @MiguelElGallo - lineage information is available in the "manifest" artifact that `dbt-core` produces after parsing projects: https://docs.getdbt.com/reference/artifacts/manifest-json

Within `dbt-core`, we don't build/offer/support native integrations with other metadata platforms — but we do make commitments around the stability of the metadata that `dbt-core` produces, to ensure the stability of integrations that other people (partners & community members) might build.
