### ISSUE TITLE
[CT-3140] [Bug] Append not working when special character present in either database or schema name in snowflake

### ISSUE THREAD

**Issue by sudo-pradip** [dbt-labs/dbt-core#8688]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

- I have database and schema name which contains a special character.
- I have simple DBT project where didn't override any configs.
- when I run dbt model first time it creates the table and on second run it again create the table instead of appending.
- it happens either of cases when only database contains special character, when only schema name contains special characters, when both contains special characters

### Expected Behavior

- After second run it should not re-create table instead append the record to target table

### Steps To Reproduce

- profiles.yml (I can't use DBT quoting feature at project level to enable quote at all places, in case of snowflake all object become case sensitive, so i need to quoted  database and schema by my self)
````
 dbt_warm_snow:
  outputs:
    dev:
      account: <account>
      database: '"products&inventory"'
      password: <password>
      role: <role>
      schema: '"budget$2023"'
      threads: 1
      type: snowflake
      user: <user>
      warehouse: <warehouse>
  target: dev
 ````
- example/my_first_dbt_model.sql
````
{{ config(
    materialized = 'incremental',
    incremental_strategy = 'append'
) }}

with source_data as (

    select 33 as id
    union all
    select 44 as id

)

select *
from source_data
````
- first run `dbt run` logs
- second run `dbt run` logs 

### Relevant log output

```shell
## First run `dbt run`
[0m14:14:22.779730 [info ] [MainThread]: Running with dbt=1.6.2
[0m14:14:24.610158 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m14:14:24.611418 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_"products&inventory"'
[0m14:14:24.635207 [debug] [ThreadPool]: Using snowflake connection "list_"products&inventory""
[0m14:14:24.638705 [debug] [ThreadPool]: On list_"products&inventory": /* {"app": "dbt", "dbt_version": "1.6.2", "profile_name": "dbt_red_snow", "target_name": "dev", "connection_name": "list_\"products&inventory\""} */
show terse schemas in database "products&inventory"
    limit 10000
[0m14:14:29.956289 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_"products&inventory", now create_"products&inventory"_"budget$2023")
[0m14:14:29.964866 [debug] [ThreadPool]: Creating schema "database: "\"products&inventory\""
schema: "\"budget$2023\""
[0m14:14:36.852797 [debug] [Thread-1 (]: On model.dbt_red_snow.my_first_dbt_model: /* {"app": "dbt", "dbt_version": "1.6.2", "profile_name": "dbt_red_snow", "target_name": "dev", "node_id": "model.dbt_red_snow.my_first_dbt_model"} */
create or replace transient table "products&inventory"."budget$2023".my_first_dbt_model
         as
        (

with source_data as (

    select 33 as id
    union all
    select 44 as id

)

select *
from source_data
        );
## Second run `dbt run`
[0m14:15:52.639698 [info ] [MainThread]: Running with dbt=1.6.2
[0m14:15:53.072040 [debug] [ThreadPool]: On list_"products&inventory": /* {"app": "dbt", "dbt_version": "1.6.2", "profile_name": "dbt_red_snow", "target_name": "dev", "connection_name": "list_\"products&inventory\""} */
show terse schemas in database "products&inventory"
    limit 10000
create or replace transient table "products&inventory"."budget$2023".my_first_dbt_model
         as
        (

with source_data as (

    select 33 as id
    union all
    select 44 as id

)

select *
from source_data
        );
```

### Environment

```markdown
- OS: Ubuntu 22
- Python: 3.10.12
- dbt: 1.6.2
- dbt-snowflake: 1.6.2
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
@sudo-pradip Thanks for opening!

> I have database and schema name which contains a special character.

Do you have any control over this? Quoting & case-sensitivity on Snowflake is nearly guaranteed to be A Bad Time.

As you mention, if you absolutely must quote identifiers, dbt supports it in two ways:
- You can make _everything_ in your project quoted & case-sensitive (via [`quoting`](https://docs.getdbt.com/reference/project-configs/quoting) config), or nothing. Trying to support a mix of both patterns is very, very tricky.
- You can tell dbt to [quote specific sources](https://docs.getdbt.com/reference/resource-properties/quoting) while referencing them, with the understanding that you don't have the same degree of control over your sources, and dbt also isn't building them.

This combination never works:
- telling dbt that your identifiers are unquoted (`quoting: false` in `dbt_project.yml`, the default on Snowflake)
- manually quoting specific identifiers

**Comment by sudo-pradip** [comment]
Hi @jtcohen6 
thanks for confirmation, agree that combination never works, no issue,
I'm just curious (don't want to re-open issue here), 

My impression about DBT is that it respect users perspective and on top of that it apply it's logic, 
In this issue whenever database need to specified it just use what user has specified and top of that it can give feature such as fetch schema or fetch tables list etc.

That way DBT can be more transparent and DBT logic can be just add on for user perspective.
Happy to close thread. thanks for your time :)
