### ISSUE TITLE
[CT-3148] [Bug] `send_anonymous_usage_stats` config not working

### ISSUE THREAD

**Issue by mirnawong1** [dbt-labs/dbt-core#8702]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

At a big data london event, I spoke to Pablo Carrera, Bruno Campos, and their teammate where they shared that the `send_anonymous_usage_stats` config doesn't seem to work in their `profiles.yml` file. They have tried putting it in different parts in the file, without the outer part of the file and inside where you add the database info. They're on dbt v1.6.1. 

### Expected Behavior

dbt Core users can opt out of event tracking at any time by adding the following to your profiles.yml file:

```
config:
  send_anonymous_usage_stats: False
```

### Steps To Reproduce

Bruno and Pablo to fill out

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

Page: https://docs.getdbt.com/reference/global-configs/usage-stats

**Comment by dbeatty10** [comment]
Bruno and/or Pablo: could you try out the following and let us know if this still feels like a bug to you? I tried out a couple things using dbt-core==1.6.3, and it appeared to work correctly for me.

### Things to try


Run a simple dbt command to see the setting of `send_anonymous_usage_stats` within the logs:
```shell
dbt ls
```

Open `logs/dbt.log` and search for the following (in reverse order):
```
'send_anonymous_usage_stats':
```

Mine says this:
```
'send_anonymous_usage_stats': 'False'
```

If your says something different than you expected, check if you have any environmental variables set:
```
echo $DBT_SEND_ANONYMOUS_USAGE_STATS
echo $DO_NOT_TRACK
```

If they are set, they will take precedence over anything within `profiles.yml`.

One of these was set for me, so I unset both of them for troubleshooting purposes:
```shell
unset DBT_SEND_ANONYMOUS_USAGE_STATS
unset DO_NOT_TRACK
```

Then this `profiles.yml` worked exactly like I expected:
```yaml
config:
  send_anonymous_usage_stats: False
```

If it still isn't working for you, you can confirm that you are editing the `profiles.yml` that is being used by running this command to see where dbt is looking:
```shell
dbt debug  --config-dir 
```

Alternatively, to get more verbose output of where dbt is looking, you can do this:
```shell
dbt debug
```
