### ISSUE TITLE
[CT-3159] [spike] Globalize remaining Click flags

### ISSUE THREAD

**Issue by aranke** [dbt-labs/dbt-core#8715]
### Housekeeping

- [x] I am a maintainer of `dbt-core`

### Short description

Follow-up from https://github.com/dbt-labs/dbt-core/issues/8670, globalize the following flags so that they can be passed in after the sub command and still work:

- [ ] @p.warn_error
- [ ] @p.warn_error_options
- [ ] @p.log_format

### Acceptance Criteria

The flags above are part of the following method

https://github.com/dbt-labs/dbt-core/blob/549dbf3390885bbca5ed6b112cc88f74d7663b73/core/dbt/cli/main.py#L123

Capture issues related to globalizing these flags

### Impact to Other Teams

N/A

### Will backports be required?

No

**Comment by dbeatty10** [comment]
This covers 3 out of the 4 [UserConfig missing from global configs](https://github.com/dbt-labs/dbt-core/issues/7036) that showed up in a separate and independent audit.

What about `indirect_selection`? It is the only 1 of the 4 that showed up there but is not covered here.
