### ISSUE TITLE
[CT-3182] [Feature] Bump version of dbt-semantic-interfaces to include jsonschema>=4.19 for 1.6 compatibility with Airflow>=2.6.3

### ISSUE THREAD

**Issue by codecae** [dbt-labs/dbt-core#8767]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Airflow>=2.6.3 is *not* compatible with dbt-core~=1.6 due to a conflict in the version of jsonschema in dbt-semantic-interfaces 0.2.0.

The core issue is that jsonschema has deprecated the `jsonschema.RefResolver` in favor of `referencing.registry` after 4.18.  Unfortunately, the to-be-removed object intended to make it reverse compatible isn't entirely bug-free.  Consequently, this created a snag in the timeline for dbt-semantic-interfaces, on which dbt-core is dependent.

The issue in dbt-semantic-interfaces has seemingly been addressed in [this pull request](https://github.com/dbt-labs/dbt-semantic-interfaces/pull/160).  While I realize that requires a dependent release on the other repo I feel quite strongly that folks, such as myself that use dbt-core in the same venv as airflow, would be quite elated to be able to upgrade Airflow to more recent versions after this dependency update is resolved.

### Describe alternatives you've considered

There are no other viable alternatives at this time other than staying at dbt-core 1.5.

### Who will this benefit?

This will benefit all Airflow users that wish to upgrade to use dbt~=1.6 with Airflow>=2.6.3

### Are you interested in contributing this feature?

I have contributed to this feature by resolving the issue in the pull request referenced above.

**Comment by QMalcolm** [comment]
@codecae there is no work in `dbt-core` to be done to get 1.6.x to support this. We're backporting (https://github.com/dbt-labs/dbt-semantic-interfaces/pull/165) your work in dbt-semantic-interfaces (https://github.com/dbt-labs/dbt-semantic-interfaces/pull/160) to the [0.2.latest branch in dbt-semantic-interfaces](https://github.com/dbt-labs/dbt-semantic-interfaces/tree/0.2.latest). Once we merge that, we're going to do a release of dbt-semantic-interfaces `0.2.2`. In dbt-core 1.6.latest the dependency specification for DSI is `dbt-semantic-interfaces~=0.2.0` as seen [here](https://github.com/dbt-labs/dbt-core/blob/6946a206a8145848d57e696cf72044b18cec4604/core/setup.py#L78), which means the changes will automatically get picked up.

**Comment by QMalcolm** [comment]
Closing because there is no work to be done in core for this. I'll add another comment here though once DSI 0.2.2 is released.

**Comment by codecae** [comment]
@QMalcolm I opened this here for the version pin in pyproject.toml in dbt-core.  Sorry for any confusion.

**Comment by QMalcolm** [comment]
@codecae we've released 0.2.2 of DSI, if you fresh install your dbt environment it should be picked up 🙂

**Comment by codecae** [comment]
LGTM!
