### ISSUE TITLE
[CT-3212] [Feature] Can DBT support column level data lineage or can some other methods used?

### ISSUE THREAD

**Issue by colagy** [dbt-labs/dbt-core#8838]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

It seems that DBT does not support column level data lineage, but only support table level data lineage.
I want to know the fields in the metric come from which table and which field in the table.

**Comment by dbeatty10** [comment]
Thanks for reaching out @colagy !

Column level lineage is an intriguing feature that dbt doesn't currently support.

There's a popular Discussion here for it here https://github.com/dbt-labs/dbt-core/discussions/4458, so I'm going to close this issue as a duplicate.
