### ISSUE TITLE
[CT-3218] materialized: view is not respected in dbt_project.yml

### ISSUE THREAD

**Issue by doofin** [dbt-labs/dbt-core#8849]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

models under folders with config materialized: view will create tables in Athena database

### Expected Behavior

models under folders with config materialized: view shouldn't create tables

### Steps To Reproduce

dbt_project.yml : 

`
name: 'dbtModels'
version: '1.0.0'
config-version: 2

profile: 'dbtModels'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbtModels:
    prep_table:
      +materialized: table
      # Config indicated by + and applies to all files under models/example/
    prep_view:
      +materialized: view
`

then when you do dbt run, models under models/prep_view will create tables

### Environment

```markdown
- OS:macos
- Python:3.10

dbt Core:
  - installed: 1.6.5
Plugins:
  - athena: 1.6.2 - Ahead of latest version!
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

the database is Amazon athena with the dbt-athena plugin

**Comment by dbeatty10** [comment]
Hi @doofin -- I was not able to reproduce the error you reported.

Using the `dbt_project.yml` file you shared + the following files worked as expected for me.

Could you try out the set up below and see if it works for you?

### One idea
Maybe double-check that you aren't overriding the `config` within your SQL files for views?

`models/prep_view/my_view.sql`
```sql
{{ config(materialized="table") )}

select 1 as id
```

### Example that worked for me

`models/prep_table/my_table.sql`
```sql
select 1 as id
```

`models/prep_view/my_view.sql`
```sql
select 1 as id
```

Run the two relevant models:
```shell
dbt run --select my_table my_view
```

<details>
<summary>

#### Output</summary>

```shell
(duckdb_1.6) $ tree models 
models
├── prep_table
│   └── my_table.sql
└── prep_view
    └── my_view.sql

3 directories, 2 files

(duckdb_1.6) $ dbt run --select my_table my_view
13:03:00  Running with dbt=1.6.3
13:03:00  Registered adapter: duckdb=1.6.0
13:03:00  Found 2 models, 0 sources, 0 exposures, 0 metrics, 348 macros, 0 groups, 0 semantic models
13:03:00  
13:03:00  Concurrency: 1 threads (target='duckdb')
13:03:00  
13:03:00  1 of 2 START sql table model main.my_table ..................................... [RUN]
13:03:00  1 of 2 OK created sql table model main.my_table ................................ [OK in 0.11s]
13:03:00  2 of 2 START sql view model main.my_view ....................................... [RUN]
13:03:00  2 of 2 OK created sql view model main.my_view .................................. [OK in 0.05s]
13:03:01  
13:03:01  Finished running 1 table model, 1 view model in 0 hours 0 minutes and 0.34 seconds (0.34s).
13:03:01  
13:03:01  Completed successfully
13:03:01  
13:03:01  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```

</details>

**Comment by doofin** [comment]
thanks, It seems to work fine. Previously I probably didn't notice that Athena have a "view" tab
