### ISSUE TITLE
[CT-3220] [Bug] Published schema for manifest v10 cannot be used for validation with dbt-core v1.6.6

### ISSUE THREAD

**Issue by mars-lan** [dbt-labs/dbt-core#8851]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Looks like dbt-core v1.6.6 introduced new changes that are not reflected in the [published JSON schema](https://schemas.getdbt.com/dbt/manifest/v10/index.html) (see https://github.com/dbt-labs/dbt-core/issues/8328 & https://github.com/dbt-labs/dbt-core/issues/8763 for previous examples). Is it possible to ensure that new JSON schema is updated as part of the release process?  

### Expected Behavior

The generated `manifest.json` file fully conforms with the JSON schema.

### Steps To Reproduce

Using https://github.com/dbt-labs/jaffle-sl-template as an example, the generated `manifest.json` failed to validate with the following (subset of) errors:

```
metrics -> metric.jaffle_shop.locations -> type_params -> measure -> fill_nulls_with
  extra fields not permitted (type=value_error.extra)
metrics -> metric.jaffle_shop.locations -> type_params -> measure -> join_to_timespine
  extra fields not permitted (type=value_error.extra)
metrics -> metric.jaffle_shop.locations -> type_params -> input_measures -> 0 -> fill_nulls_with
  extra fields not permitted (type=value_error.extra)
metrics -> metric.jaffle_shop.locations -> type_params -> input_measures -> 0 -> join_to_timespine
  extra fields not permitted (type=value_error.extra)
metrics -> metric.jaffle_shop.customers_with_orders -> type_params -> measure -> fill_nulls_with
  extra fields not permitted (type=value_error.extra)
metrics -> metric.jaffle_shop.customers_with_orders -> type_params -> measure -> join_to_timespine
  extra fields not permitted (type=value_error.extra)
metrics -> metric.jaffle_shop.customers_with_orders -> type_params -> input_measures -> 0 -> fill_nulls_with
  extra fields not permitted (type=value_error.extra)
metrics -> metric.jaffle_shop.customers_with_orders -> type_params -> input_measures -> 0 -> join_to_timespine
  extra fields not permitted (type=value_error.extra)

```

### Environment

```markdown
- OS: macOS 13.5 
- Python: 3.9.6
- dbt: 1.6.6
```

**Comment by emmyoop** [comment]
Thanks for opening this issue @mars-lan.  I'm already working on getting it resolved over in https://github.com/dbt-labs/schemas.getdbt.com/pull/30.

**Comment by emmyoop** [comment]
We've merged the new version of the published schema for manifest v10.  Closing this as resolved as part of https://github.com/dbt-labs/schemas.getdbt.com/pull/30.

**Comment by mars-lan** [comment]
@emmyoop thanks. Confirmed that both this & https://github.com/dbt-labs/dbt-core/issues/8763 have been fixed by the latest JSON schema.
