### ISSUE TITLE
[CT-3224] [Regression] DBT 1.5.8 introduces breaking changes to incrementally materialized models

### ISSUE THREAD

**Issue by epgui** [dbt-labs/dbt-core#8857]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Prior to 1.5.8 (<= 1.5.7), incremental models would accept implicit type casts such as `VARCHAR(n) -> TEXT` (or the other way around). In other words, prior to 1.5.8, if the model's DDL / contract specification was `TEXT`, then source data of type `VARCHAR(n)` would get incrementally added to the table without issue and without any need for explicitly casting (ie.: `my_column::TEXT`).

With dbt-cloud not allowing users to pin down a minor version of DBT, this caused models to suddenly stop working for us.

### Expected/Previous Behavior

Prior to 1.5.8 (<= 1.5.7), incremental models would accept implicit type casts such as `VARCHAR(n) -> TEXT`.

### Steps To Reproduce

See problem description in "Current behaviour". This should be trivially reproducible.

### Relevant log output

```shell
20:42:22                     Source columns not in target: []
20:42:22                     Target columns not in source: []
20:42:22                     New column types: [{'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}, {'column_name': 'REDACTED', 'new_type': 'character varying(256)'}]
```

### Environment

```markdown
- OS: any (dbt-cloud)
- Python: any (dbt-cloud)
- dbt (working version): 1.5.7
- dbt (regression version): 1.5.8
```

### Which database adapter are you using with dbt?

postgres

**Comment by jtcohen6** [comment]
@epgui Thanks for opening! I am guessing that the root cause here must have been the fix to resolve this bug:
- https://github.com/dbt-labs/dbt-core/issues/8022
- https://github.com/dbt-labs/dbt-core/pull/8768

You could try "reverting" that fix, by adding an override of the `create_table_as` macro without [this line changed](https://github.com/dbt-labs/dbt-core/commit/543f87e17fc3c54af5d01a34484170b300f9bd59#diff-49fbdf0ee41b3d9ec139a881dfed1e9196c47ba014f946421f636bbf57703a6cR13), to see if it resolves the issue for you.

**Comment by jtcohen6** [comment]
After looking a bit more closely at that change, I believe it has a larger scope than the effect desired.

- Ideal: don't template _foreign-key_ constraints into `create temporary table` DDL statement, which aren't supported when creating temp tables
- Next-best: don't template _any_ constraints into `create temporary table` DDL statement (the constraints will be applied on `insert`)
- Acceptable [per [my comment here](https://github.com/dbt-labs/dbt-core/issues/8022#issuecomment-1629055570), though it doesn't resolve this issue]: don't include column schema (names, data types, constraints) in `create temporary table` DDL statement

Whereas, I believe the change implemented in #8768 disables all contract checks on incremental builds of incremental models, including the "pre-flight" check in `get_assert_columns_equivalent`. That's not right.

**Comment by emmyoop** [comment]
I opened another issue (#8896) for the related issue described by @jtcohen6.

**Comment by epgui** [comment]
Twofold apology:
- First, Github notifications don't really work for me, so I was not alerted to the fact that further input was requested from me.
- Second, this is an issue I've come across at work, and while it's not ideal we have an ad-hoc mitigation/workaround in place. I don't know if I will have time to look into this in greater detail.

I regret that I can't provide much more information at this time, and I hope my raising the issue was at least _somewhat_ helpful.

**Comment by dbeatty10** [comment]
No worries @epgui.

Can you describe the ad-hoc mitigation/workaround? That might help us figure out the characteristics causing the issue you experienced.

**Comment by epgui** [comment]
> No worries @epgui.
> 
> Can you describe the ad-hoc mitigation/workaround? That might help us figure out the characteristics causing the issue you experienced.

It is just as described in the original report: we must explicitly cast every `VARCHAR(n)` to `TEXT`. Additionally, we had to drop the entire table and rebuild it with these explicit casts in order to get past the error.

**Comment by dbeatty10** [comment]
@epgui we are looking for a detailed code example we could try running ourselves rather than a written description without code examples.

We don't have enough information right now to reproduce, so we can't re-open this issue until then.

[Here](https://github.com/dbt-labs/dbt-core/issues/8872) is the type of issue report we are looking for.
