### ISSUE TITLE
[CT-3228] [feature] dbt docs generate --defer should work on catalog.json

### ISSUE THREAD

**Issue by anshjain18** [dbt-labs/dbt-core#8861]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

1. In development environment, I run models in my own schema in the database. 
2. The models not present in my schema are deferred from a common schema public. We do this using `dbt run -s model --defer --state public-artifacts` (Assuming public-artifacts contain the public-schema's docs)

Now, running `dbt docs generate` will only add those nodes in catalog.json which are present in my schema. This is expected.
But I want the nodes not present in my schema to be deferred from public schema while generating docs as well. 
To do this, I tried `dbt docs generate --defer --state public-artifacts,` but the catalog generated was exactly the same as generated without supplying --defer

### Expected Behavior

dbt docs generate --defer --state DEFERRED_STATE should work for catalog.json as well.

### Steps To Reproduce

1. Run dbt docs generate, and store the catalog.json output.
2. Run dbt docs genreate --defer --state SOME_DEFERRED_STATE, and store the catalog.json output.
3. Compare both, they will be similar.

### Environment

```markdown
- OS MAC OS:
- Python 3.11:
- dbt 1.6.6:
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
@anshjain18 Thanks for opening!

With the latest changes in v1.7, this is the behavior of `dbt docs generate` + `--defer` + `--select/--exclude`:
1. If a model is _selected_, it is not _deferred_. (This is how `--defer` has always worked.)
2. If a model is _excluded_, it is not _catalogued_. (This is new behavior in v1.7)

I don't think we're going to support the use case as outlined. Instead, I'd recommend:
1. [happy path] Running `dbt clone` with deferral/state to create a full "dev" schema _first_, and then running `dbt docs generate`
2. [possible] Write some code to merge together `catalog.json` from different environments :)
