### ISSUE TITLE
[CT-3234] [Feature] Allow query-commenting for dbt test command

### ISSUE THREAD

**Issue by vrplentz** [dbt-labs/dbt-core#8870]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently in case you want to add labels to your BigQuery jobs, you can do it by using a query_commenter macro ([as in this docs](https://docs.getdbt.com/reference/project-configs/query-comment#bigquery-include-query-comment-items-as-job-labels)).

The problem is that apparently the query commenter it's not used when a `dbt test` command (it's called only for `dbt  run`).

Because of this, it's not possible to add job-labels for those tests (which also consume resources).

### Describe alternatives you've considered

Allowing dbt test command to use a query commenter  for custom and generic tests.

### Who will this benefit?

Anyone that's tracking BigQuery cost using job labeling.  

### Are you interested in contributing this feature?

Not sure where to start. But I can implement it.

**Comment by jtcohen6** [comment]
@vrplentz Thanks for opening!

I believe this already works:

```yml
# dbt_project.yml
query-comment:
  job-label: True
```

```
$ dbt --debug test
...
On test.my_dbt_project.unique_my_model_user_id.fd60587ca1: /* {"app": "dbt", "dbt_version": "1.6.7", "profile_name": "sandbox-bigquery", "target_name": "dev", "node_id": "test.my_dbt_project.unique_my_model_user_id.fd60587ca1"} */
select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
...
```

<img width="546" alt="Screenshot 2023-11-08 at 18 10 41" src="https://github.com/dbt-labs/dbt-core/assets/13897643/01fcc404-e427-4b79-adff-f2789d110447">

<img width="607" alt="Screenshot 2023-11-08 at 18 10 35" src="https://github.com/dbt-labs/dbt-core/assets/13897643/0114f0c0-9824-4bf8-a712-95cb95721503">

---

I'm going to close this issue as resolved — let us know if you give it a try & run into issues.
