### ISSUE TITLE
[CT-3239] [Feature] Add a `full_refresh` option to `on_schema_change `

### ISSUE THREAD

**Issue by paynecrl97** [dbt-labs/dbt-core#8873]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Add a `full_refresh` option to `on_schema_change `.

During an incremental load, any models that have this option set will automatically be fully refreshed if the schema of the model changes. Other models are unaffected (unless `--full-refresh` is applied, in which case all models are fully refreshed as usual).

### Describe alternatives you've considered

The only alternative is to specify `--full-refresh` during `dbt run`.

This has some drawbacks:

1. It's blunt - all models selected will be fully refreshed, but we may only need one model from those selected to be fully refreshed
2. It's hard to automate - in a CI/CD context where we have models that are materialized by a pipeline, it's hard to know when a full refresh is needed
3. It's prone to human error - devs need to recognise when they need to do a full-refresh, and possibly pass this information on to the release manager who is ultimately responsible for the deployment (and materialization) in downstream environments.

### Who will this benefit?

This is useful for those who meet at least one of the following criteria:
- those targetting a DB that can't drop columns from an existing table
- those who require new columns to be back filled

In our specific use case, we've got a transformation layer in DBT that targets Databricks (see https://docs.databricks.com/en/delta/delta-column-mapping.html for info on limitations for dropping columns). Once the incremental tables are materialized by DBT, we have a third party tool that loads the data into an external system (Salesforce). We use incremental tables so that we can maintain a last modified timestamp for each record, which allows us to do partial loads into the external system.

Whenever a column is added or removed from the materialized tables, we'd like to bulk update all the last modified timestamps so that all the data is re-loaded into Salesforce (thus back filling the new fields in Salesforce). If DBT could automatically do a full refresh whenever schemas change, this would alleviate three problems for us:

1. our target DB technology does not allow us to drop columns from existing tables
2. new columns are not back-filled by dbt
3. we want last modified timestamps (set to the time that the records are loaded into the materialized table) to be updated en whole so that all records are re-uploaded to our external system

### Are you interested in contributing this feature?

If it's an easy enough change, and someone points me in the right direction I could have a go at it

**Comment by jtcohen6** [comment]
Thanks for opening @paynecrl97! I agree with the thrust of what you've written above.

I believe this is a duplicate of an open issue, and an open PR. You can take a look at the PR for a sense of why this would be more complex to implement:
- https://github.com/dbt-labs/dbt-core/issues/4473
- https://github.com/dbt-labs/dbt-core/pull/6412

I'm going to close this issue, and reopen ("un-stale") the previous one, to keep the conversation centralized there.
