### ISSUE TITLE
[CT-3249] [Bug] Issue with ValidationError when enabling local package for a dbt project

### ISSUE THREAD

**Issue by srggrs** [dbt-labs/dbt-core#8882]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We have two local dbt packages (let's call them `local_package_a` and `local_package_b`) that holds data transformation logic for different functionality. One of them (`local_package_a`) is installed in every customer dbt project, and the other only in two of the customers. 

Currently when I added `local_package_b` (the second local dbt package) to another customer I get a Validation error that block the compilation of customer dbt project. This validation error points to a macro in the main local package `local_package_a`. See details of the stack trace below.

I am looking for how to debug this without pulling the whole dbt and hologram python packages locally, installing them and use the classic `pdb.set_trace()`.

### Expected Behavior

Adding the local module to the `packages.yml` should not block the installation of the module for any other dbt project.

### Steps To Reproduce

Not sure how to reproduce this without pasting the whole code of our local dbt packages, but I can paste the macro in question 

```sql
{% macro vacuum_model() %}
    {%- if model.config.materialized in [ "table", "incremental" ] -%}
        -- vacuum table
        vacuum {{ this }};
    {%- endif -%}
{% endmacro %}
```

### Relevant log output

```shell
23:32:25  Running with dbt=1.5.6
23:32:26  Registered adapter: databricks=1.5.5
23:32:26  Unable to do partial parsing because saved manifest not found. Starting full parse.
23:32:27  Encountered an error:
'{{ local_package_a.vacuum_model() }}' is not of type 'object'

Failed validating 'type' in schema['properties']['post-hook']['items']:
    {'additionalProperties': False,
     'description': 'Hook(sql: str, transaction: bool = True, index: '
                    'Optional[int] = None)',
     'properties': {'index': {'oneOf': [{'type': 'integer'},
                                        {'type': 'null'}]},
                    'sql': {'type': 'string'},
                    'transaction': {'default': True, 'type': 'boolean'}},
     'required': ['sql'],
     'type': 'object'}

On instance['post-hook'][0]:
    '{{ local_package_a.vacuum_model() }}'
23:32:27  jsonschema.exceptions.ValidationError: '{{ local_package_a.vacuum_model() }}' is not of type 'object'

Failed validating 'type' in schema['properties']['post-hook']['items']:
    {'additionalProperties': False,
     'description': 'Hook(sql: str, transaction: bool = True, index: '
                    'Optional[int] = None)',
     'properties': {'index': {'oneOf': [{'type': 'integer'},
                                        {'type': 'null'}]},
                    'sql': {'type': 'string'},
                    'transaction': {'default': True, 'type': 'boolean'}},
     'required': ['sql'],
     'type': 'object'}

On instance['post-hook'][0]:
    '{{ local_package_a.vacuum_model() }}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 215, in wrapper
    return func(*args, **kwargs)
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 242, in wrapper
    manifest = ManifestLoader.get_full_manifest(
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 227, in get_full_manifest
    manifest = loader.load()
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 386, in load
    self.parse_project(
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 515, in parse_project
    parser.parse_file(block)
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/parser/base.py", line 442, in parse_file
    self.parse_node(file_block)
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/parser/base.py", line 397, in parse_node
    node = self._create_parsetime_node(
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/parser/base.py", line 211, in _create_parsetime_node
    "config": self.config_dict(config),
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/parser/base.py", line 373, in config_dict
    config_dict = config.build_config_dict(base=True)
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/context/context_config.py", line 330, in build_config_dict
    return src.calculate_node_config_dict(
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/context/context_config.py", line 213, in calculate_node_config_dict
    finalized = config.finalize_and_validate()
  File "/path/to/my/venv/lib/python3.9/site-packages/dbt/contracts/graph/model_config.py", line 358, in finalize_and_validate
    self.validate(dct)
  File "/path/to/my/venv/lib/python3.9/site-packages/hologram/__init__.py", line 989, in validate
    raise ValidationError.create_from(error) from error
hologram.ValidationError: '{{ local_package_a.vacuum_model() }}' is not of type 'object'

Failed validating 'type' in schema['properties']['post-hook']['items']:
    {'additionalProperties': False,
     'description': 'Hook(sql: str, transaction: bool = True, index: '
                    'Optional[int] = None)',
     'properties': {'index': {'oneOf': [{'type': 'integer'},
                                        {'type': 'null'}]},
                    'sql': {'type': 'string'},
                    'transaction': {'default': True, 'type': 'boolean'}},
     'required': ['sql'],
     'type': 'object'}

On instance['post-hook'][0]:
    '{{ local_package_a.vacuum_model() }}'
```

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Python: Python 3.9.18
- dbt: 1.5.6
- dbt-databricks: 1.5.5
```

### Which database adapter are you using with dbt?

spark

### Additional Context

I am aware there is a similar issue marked as closed, but not relevant to my case, though the error is pretty much the same (stack trace) #6776 

_No response_

**Comment by graciegoheen** [comment]
Hey! I'm curious what indicates to you that this is a bug with dbt core, vs. a bug in your macro? 

What happens if your macro is empty? 
```
{% macro vacuum_model() %}

{% endmacro %}
```

Are you still getting this issue?

Is this macro in `local_package_a`? Or `local_package_b`? Sounds like these two packages aren't compatible with each other. Does `local_package_b` work independently of `local_package_a`?

Additionally, what dbt command did you run that cause this error? `dbt deps`, `dbt run`, `dbt compile`, something else?

**Comment by srggrs** [comment]
Ok I did some digging to answer your questions. Here are the dets:

* the macro belongs to `local_package_a`
* `local_package_b` works independently from `local_package_a`
* `local_package_a` is installed in `dbt_project_customer1` along side `local_package_b` and they work with no worries
* having the empty macro as suggested still give me the same issue (same stack trace as reported above). This happens when I install the package `local_package_b` to another customer (ie `dbt_project_customer2`)
* The command `dbt deps` install the packages correctly with no errors
* The errors is shown when running `dbt parse` or `dbt ls` or `dbt run` or `dbt build` (any dbt command that actually compile the project code base)
* the macro is called within `local_package_a` in some models as post hook (ie `post_hook=["OPTIMIZE " ~ this, "{{ vacuum_model() }}"]` in the model config
* the macro is called within `dbt_project_customer2` as follow `post_hook = ['OPTIMIZE ' ~ this, '{{ local_package_a.vacuum_model() }}' ],`
* no model in `dbt_project_customer2` calls the macro directly but it is defined as a general post hook for all models in the dbt project yaml (see below)

The only real difference between `dbt_project_customer1` and `dbt_project_customer2` with regards the macro is that the macro is used in some models in `dbt_project_customer1`, while the macro is defined as a general post hook for all the models in `dbt_project_customer2` with
```yaml
# dbt_project_customer1 dbt_project.yml
models:
  +post_hook:
    - "{{ local_package_a.vacuum_model() }}"
```

I found the issue: because the macro is added as post hook under models, I think it conflict with the `local_package_a` as the 
`dbt_project_customer2` dbt_project.yml has these lines:

```yaml
# dbt_project_customer1 dbt_project.yml
models:
  +post_hook:
    - "{{ local_package_a.vacuum_model() }}"

  customer1:
# confs for customer1 models

  local_package_a:
# confs for local_package_a models
    ...
```
I believe putting `local_package_a.vacuum_model()` under models conflicts with the vacuum_model in the local_package_a models. 

Funny things is that this issue comes out only when installing a new local dbt package.

**Comment by srggrs** [comment]
Moving the macro from under `models` to the customer name fix this issue
```yml
# dbt_project_customer2 dbt_project.yml
models:
  ...

  customer2:
# confs for customer2 models
    +post_hook:
      - "{{ local_package_a.vacuum_model() }}"

  local_package_a:
# confs for local_package_a models
    ...
```

**Comment by srggrs** [comment]
Thank you for replying to this :pray:
