### ISSUE TITLE
[CT-3251] [Feature] Ignore changes to Jinja comments as it relates to `state:modified`

### ISSUE THREAD

**Issue by dbrtly** [dbt-labs/dbt-core#8884]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Before:
```sql
-- my_model.sql
{# original comment. #}
select foo
```

After:
```sql
-- my_model.sql
{# modified comment. #}
select foo
```

(NB whitespace is unchanged)

In a project where only this file has been changed, state method identifies that my_model has changed

```shell
dbt list —select state:modified …
```

### Expected Behavior

These jinja files should compile to the same sql query. 

In a project where only this file has been changed, state method should identify zero models changed (NB whitespace is unchanged)

```shell
dbt list —select state:modified …
```

### Steps To Reproduce

before:
```sql
-- my_model.sql
{# original comment #}
select true

```

After:
```sql
-- my_model.sql
{# new comment #}
select true

``` 

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbrtly** [comment]
We’re trying to use the state method to run only modified models. It’s a noisy signal sometimes. 

Thanks for helping us understand.

**Comment by dbeatty10** [comment]
Is it very common for a model to _only_ have a changed Jinja comment without any other changes?

Are there any negative side-effects when these are included in `state:modified`?

I'd anticipate a non-trivial engineering effort to implement this feature, so trying to get a sense of the impact folks are experiencing here.
