### ISSUE TITLE
[CT-3264] [Feature] Persist docs from data platform to dbt 

### ISSUE THREAD

**Issue by bethanyhipple-dbtlabs** [dbt-labs/dbt-core#8905]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently we are able to persist documentation from dbt to the data platform with the `persist docs` config. However, if the source tables are already documented in the data platform, it would be great to have that documentation show up either in dbt yml (maybe through the generate_source macro in the code_gen package) or just show up in the doc site/explorer. 

### Who will this benefit?

Both dbt developers and stakeholders will benefit. Developers don't have to copy paste docs and stakeholders can have the documentation they need in the dbt docs. 

### Are you interested in contributing this feature?

no

**Comment by jtcohen6** [comment]
> just show up in the doc site/explorer

This is what I would expect — and I think it should already be possible!

Our catalog queries already ask for table/column comments (e.g. [here](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/catalog.sql#L45) & [here](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/catalog.sql#L82) in `dbt-snowflake`), and stick them in `catalog.json`, so it's just a matter of displaying them when a user-defined description isn't available.

It looks like this has already been tracked over in `dbt-docs` (although the issue + PR went stale):
- https://github.com/dbt-labs/dbt-docs/issues/251
- https://github.com/dbt-labs/dbt-docs/pull/263

Let's follow up with the team building Explorer :)

In the meantime, I'm going to close this one - I don't think there's a `dbt-core` change we need to make.
