### ISSUE TITLE
[CT-3266] [Feature] Add dbt_project configuration for packages.yml file

### ISSUE THREAD

**Issue by erikoxw** [dbt-labs/dbt-core#8908]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In our production environment, we use packages.yml with git packages
```
packages:
  - git: "https:// .. .. /separate_feature.git"
     revision: jf2osalceoisacs
```
While developing, we use a local version of that package
```
packages:
  - local: ~/work/separate_feature
```

I propose there be an extra dbt_project.yml config option just like target-path/log-path but for package-path.  The default would be `root-of-project/packages.yml` but, for example, you could change it to be `any/path/dev_packages.yml`

With this, you could have a line in dbt_project like:
```
package-path: "{{ 'any/path/dev_packages.yml' if target.name == 'dev' else 'root-of-project/packages.yml' }}"
```
and use the correct package file when `dbt deps` is run

### Describe alternatives you've considered

I am aware I could use jinja inline code in the packages.yml `git: {{ env("repo_url") }}` if I was trying to switch values within a yaml key.  I am instead trying to switch entire yaml blocks, aka switching between both (git and revision) and (local).  Jinja operator logic {% %} are not supported to do something like {% if condition %}git.. .. {% else %} local ... {% endif %}.

### Who will this benefit?

Anyone developing different packages in different environments, dev vs prod etc as in the above example

This could also be helpful for using different sets of packages that have different versions. For example, if v1.0 of my project needs some_other_package's v2.3 but v2.0 of my package needs some_other_package's v3.0, I could have packages_v1.0.yml and packages_v2.0.yml and choose between them in my dbt_project with a variable or the project version number

**Comment by dbeatty10** [comment]
Thanks for opening this @erikoxw !

How are y'all handing the switching currently?

**Comment by erikoxw** [comment]
Sure!

Well.. we are commenting out lines back and forth, or stashing the 'local version' of packages.yml before pulling and resolving the merge every time.  It's manual.

**Comment by graciegoheen** [comment]
Hey @erikoxw! Thanks for opening this up.

I'd like to understand more about your use case. It's not out best practice to be editing a package & a project in tandem. Likely, you'd want to edit your package, ensure your changes are valid, push those change to production, _then_ make your project changes. To do this, you'll want to make sure you have appropriate test coverage in your package - there's a handful of ways you can test your packages:
a) pytest (like [so](https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/4-testing-a-new-adapter))
b) integration tests via dbt commands (like [so](https://github.com/dbt-labs/dbt-project-evaluator/tree/main/integration_tests))

Do you have a current testing framework for your package?

Additionally, there could be issues if you reference a different package location in development vs. production. What if your changes work in development, but when pushed to production they fail. For that reason, we recommend using the same packages in development and production.

**Comment by erikoxw** [comment]
Hi Grace, thank you for chiming in.

We actually do have tests using seeds and dbt commands like your B) recommendation (big fan, really helps us).  Also helps with `if your changes work in development, but when pushed to production they fail`

We may be too far off the beaten path, but `edit your package, ensure your changes are valid, push those change to production, then make your project changes` is where the pain points lie.  
1. The production packages are accessed with time based, access restricted tokens, in development we'd have to keep getting new tokens or weaken our security with unexpiring dev tokens or unrestricted accounts

```
packages: 
-git: {{secret token}}@github.com/utility.git
  revision: 1.0.1
# -local: ~/../utility
```
2. Some package changes are 'functional' and can be tested in isolation with seeds, but most changes are hand-in-glove with the implementation in the primary project and it is just a far faster dev cycle to be working with everything locally (`change-run` instead of `change-commit-push-deps-run`)
3. Our use case has primary repos that each have multiple subsidiary/helper packages.  Depending on the feature, development in 3 different dbt projects can happen at the same time.  We are also a multi person team with branches swirling around--the packages file gets a lot of churn because it has to be specific to each set of currently functional package versions all the time.  A project might want commit hash of package1 and a hotfix branch of package2, but then another project might want master of package1 and dev of package2.  We think of them as package sets.  As we develop features in these packages, different package sets work together correctly.

For 1, we might be doing things strangely to fit our unique needs, which would not require a feature just for us.  I'd be sad to keep having to handle this manually, also for 2 with extra dev steps. 

3 is the case which convinced me to reach out with a ticket, as more people might be running into this.  You have functionality for dbt projects to serve other dbt projects as packages.  Handling version/revision dependency between them could be much easier with flexible packages.yml files.  I mentioned this above, you could have packages-v1.yml with a package set that is tested correct for your primary repo.  Then a packages-dev.yml for development, one for production, one for prior versions in case you need to regress, one for bleeding edge validation in prod for new package minor versions.  

This feature would leverage jinja, keep logical config in dbt_project.yml instead of package.yml, and be similar to other features.  It seems to me to be a small change (?) that could add a lot of flexibility.

**Comment by dbeatty10** [comment]
After discussing this further with @graciegoheen offline, we're going to close this as "not planned".

### Reasons

#### Primary reason

There's an existing workaround that doesn't have excessive friction. Namely, you can include as many files as you want in git, and then switch between them locally like this:

```shell
cp dependencies-editable.yml dependencies.yml
```
or
```shell
cp packages-v1.yml packages.yml 
```

#### Additional reasons

There's a non-trivial amount of overhead in terms of documentation & testing we'd need to do to support any new feature even with a community-contributed pull request, and this isn't a high-priority area we'd want to invest our finite bandwidth at this time.

Closing as "not planned" is also not a one-way door -- we can always re-open it later if we regret the decision as more information and insights come to light 💡

**Comment by erikoxw** [comment]
Thanks for the time and consideration! I'll cope for now c:  Keep up the great work
