### ISSUE TITLE
[CT-3317] [Regression] Source freshness disablement no longer works as expected

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [dbt-labs/dbt-core#8992]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

When leveraging the `config: enabled:` structure in the source.yml it will properly disable the sources at runtime (ie, `dbt run`) but does not seem to disable the sources with `dbt source freshness`.

![image](https://github.com/dbt-labs/dbt-core/assets/74217849/cbe11624-5421-41dd-a4a7-69bbdb0e95b4)

![image](https://github.com/dbt-labs/dbt-core/assets/74217849/803d3565-50c9-4194-bd3a-f3a42d6d2b46)

### Expected/Previous Behavior

When leveraging the `config: enabled:` configuration in the source.yml it will properly disable the source table on `dbt run` as well as `dbt source freshness`.

![image](https://github.com/dbt-labs/dbt-core/assets/74217849/e3ccb9a3-9b2a-4e22-8fdd-28296dcd0fcb)

### Steps To Reproduce

- Upgrade to dbt 1.7.0
- Disable a source in your source.yml
- Execute `dbt source freshness`
- See the error that the source was not found

### Relevant log output

```shell
20:05:39  12 of 12 START freshness of intercom.team_admin ................................ [RUN]
20:05:39  12 of 12 ERROR freshness of intercom.team_admin ................................ [ERROR in 0.33s]
20:05:40  9 of 12 ERROR STALE freshness of intercom.conversation_tag_history ............. [ERROR STALE in 1.26s]
20:05:40  11 of 12 ERROR STALE freshness of intercom.team ................................ [ERROR STALE in 1.28s]
20:05:40  10 of 12 ERROR STALE freshness of intercom.tag ................................. [ERROR STALE in 1.49s]
20:05:40  
20:05:40  
20:05:40  
20:05:40  
20:05:40  
20:05:40  
20:05:40  
20:05:40  
20:05:40  
20:05:40  Runtime Error in source team_admin (models/src_intercom.yml)
20:05:40    404 Not found: Table project:intercom_2.team_admin was not found in location US
20:05:40    
20:05:40    Location: US
20:05:40    Job ID: 38d47a6c-7713-485e-b159-939d4c15044f
20:05:40    
20:05:40  
20:05:40  
20:05:40  
20:05:40  Done.
```

### Environment

```markdown
- OS: MacOS
- Python: 3.10.11
- dbt (working version): 1.6.7
- dbt (regression version): 1.7.0
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

I tested on BigQuery and ran into this, but may be present in others.

**Comment by dbeatty10** [comment]
Thanks for reporting this @fivetran-joemarkiewicz !

I took a swing at reproducing this, and it worked for me with dbt-bigquery 1.7.0 🤔

Maybe you can take a look at my simple example below and help me figure what is different between my setup and yours?

Is there any chance that you changed that boolean within `dbt_project.yml` from `true` to `false` but didn't save it?

Here's my project files:

`dbt_project.yml`

```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "sandcastle-bigquery"

vars:
  intercom__using_team: false
```

`seeds/my_source.csv`

```csv
id,etl_loaded_at
1,"2023-11-05T00:00:00"
```

`seeds/_seeds.yml`
```
version: 2

seeds:
  - name: my_source
    config:
      column_types:
        etl_loaded_at: timestamp
```

`models/_sources.yml`
```yaml
version: 2

sources:
  - name: my_sources
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    loaded_at_field: etl_loaded_at
    config:
      enabled: "{{ var('intercom__using_team', false) }}"
    tables:
      - name: my_source
        freshness:
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
```

Load data into the seed (so it can be sourced), and then check freshness:
```shell
dbt seed
dbt source freshness
```

Look at the output:
```
(bigquery_1.7) $ dbt source freshness   
23:24:19  Running with dbt=1.7.0
23:24:19  Registered adapter: bigquery=1.7.0
23:24:20  Found 1 seed, 0 sources, 0 exposures, 0 metrics, 447 macros, 0 groups, 0 semantic models
23:24:20  
23:24:20  Nothing to do. Try checking your model configs and model specification args
23:24:20  Done.
```

**Comment by fivetran-joemarkiewicz** [comment]
Hi @dbeatty10 thanks for looking into this! In this case the issue is that when the `my_source` table in your example does not exist in the destination and you wish to disable it (something we offer in a lot of our packages for higher flexibility) you run into the "404 table not found in location" error.

So in your case if you try the same example, but don't seed the file into your destination I am curious if you get the same error I encountered.

**Comment by dbeatty10** [comment]
@fivetran-joemarkiewicz Gave it a try with `my_nonexistent_source`.

I got the following when `intercom__using_team: true`:

```
(bigquery_1.7) $ dbt source freshness
15:08:55  Running with dbt=1.7.0
15:08:56  Registered adapter: bigquery=1.7.0
15:08:57  Found 1 seed, 1 source, 0 exposures, 0 metrics, 447 macros, 0 groups, 0 semantic models
15:08:57  
15:08:57  Concurrency: 10 threads (target='bigquery-service-account-file')
15:08:57  
15:08:57  1 of 1 START freshness of my_sources.my_nonexistent_source ..................... [RUN]
15:08:58  1 of 1 ERROR freshness of my_sources.my_nonexistent_source ..................... [ERROR in 0.44s]
15:08:58  
15:08:58    Runtime Error in source my_nonexistent_source (models/_sources.yml)
  404 Not found: Table dbt-test-env:dbt_dbeatty.my_nonexistent_source was not found in location US
  
  Location: US
  Job ID: 5bd047de-cf4e-494f-b0d5-498417494aca
  
15:08:58  Done.
```

But then this when `intercom__using_team: false`:

```
(bigquery_1.7) $ dbt source freshness
15:09:15  Running with dbt=1.7.0
15:09:15  Registered adapter: bigquery=1.7.0
15:09:15  Unable to do partial parsing because a project config has changed
15:09:16  Found 1 seed, 0 sources, 0 exposures, 0 metrics, 447 macros, 0 groups, 0 semantic models
15:09:16  
15:09:16  Nothing to do. Try checking your model configs and model specification args
15:09:16  Done.
```

**Comment by fivetran-joemarkiewicz** [comment]
@dbeatty10 huh I am seeing the same results as you now. I wonder if there was some hidden version conflict or conflicting config that I had set previously which was resulting in the initial error. Since I can't recreate the error anymore I think this is a false regression and good to close out.

Thanks again!

**Comment by dbeatty10** [comment]
Thanks for reporting this @fivetran-joemarkiewicz -- we'll re-open this if you see it again or if someone else reports seeing it.
