### ISSUE TITLE
[CT-3322] [Bug] Incorrect behaviour described in docstring for get_custom_database macro

### ISSUE THREAD

**Issue by LeoTheGriff** [dbt-labs/dbt-core#9003]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Incorrect behaviour described in docstring for get_custom_database macro: describes postfix when it is replacement of database target.

### Expected Behavior

Docstring for get_custom_database macro describes replacement of database target.

### Steps To Reproduce

N/A

**Comment by dbeatty10** [comment]
Thanks for reaching out about this @LeoTheGriff !

Can you share more about what specifically you are seeing?

e.g., share a screenshot or a link to a website that highlights what looks incorrect to you.

Also, could you share what steps we can take to see it as well?

**Comment by LeoTheGriff** [comment]
Apologies, I used a GitHub reporting mechanic that said it would attach the permalink but didn’t.

“If a database override is specified, then the resulting database is the default database concatenated with the custom database.”

The default macro replaces the default database with custom, it doesn't concat them.
https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/get_custom_name/get_custom_database.sql

________________________________

**Comment by LeoTheGriff** [comment]
It is a minor fix, I proposed a solution in the linked PR

**Comment by dbeatty10** [comment]
No prob. Looks like there was copy-paste within https://github.com/dbt-labs/dbt-core/pull/2143 in which the comments didn't get fully updated for accuracy.

Thanks for opening that PR!
