### ISSUE TITLE
[CT-3328] [Regression] `dbt-databricks` fails on `dbt docs generate` in 1.7 due to lack of `table_database` column

### ISSUE THREAD

**Issue by mikealfare** [dbt-labs/dbt-core#9013]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Executing `dbt docs generate` on `dbt-databricks` causes an error (logs below) that identifies a missing column from the catalog query, `table_database`. `dbt-databricks` does not use a database, and only uses a schema and identifier. Other adapters may also do this, but this was discovered on `dbt-databricks`.

### Expected/Previous Behavior

Executing `dbt docs generate` should complete successfully, even with a catalog query that does not provide a `table_database` column.

### Steps To Reproduce

- Create a `dbt-databricks` project
- Run `dbt docs generate`
- Observe the error

### Relevant log output

```shell
18:59:54  Running with dbt=1.7.0
19:00:01  Registered adapter: databricks=1.7.0-rc1
19:00:02  Found 8 models, 1 snapshot, 6 seeds, 20 tests, 0 sources, 0 exposures, 0 metrics, 633 macros, 0 groups, 0 semantic models
19:00:02
19:00:04  Concurrency: 8 threads (target='token')
19:00:04
19:00:06  Building catalog
19:00:08  Encountered an error:
Internal Error
  Got a row without "table_database" column, columns: ('table_schema', 'table_name', 'table_type', 'table_owner', 'column_index', 'column_name', 'column_type')
```

### Environment

```markdown
- OS: ubuntu-latest
- Python: 3.8
- dbt (working version): 1.6
- dbt (regression version): 1.7
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

dbt-databricks

**Comment by benc-db** [comment]
Have you tested against main?  I believe this is fixed in my 1.7.0 work that came after rc1.

**Comment by mikealfare** [comment]
> Have you tested against main? I believe this is fixed in my 1.7.0 work that came after rc1.

I think this was from prior to the update. Let me take a look.

**Comment by mikealfare** [comment]
@benc-db This runs now on a non-UC enabled account. I believe that was where the issue occurred (due to the lack of a database component), correct?

**Comment by benc-db** [comment]
yes

**Comment by mikealfare** [comment]
Then I can confirm this is working in 1.7.
