### ISSUE TITLE
[CT-3329] [Bug] Unit testing errors with long CTE name given reasonable test name length

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#9015]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Long unit test names (in combination with long model name + input names) can lead to a "Relation name '{}' is longer than 63 characters" if the sum of lengths is > 63 (on postgres) characters.

### Expected Behavior

No error

### Steps To Reproduce

Changing the `test_my_model_incremental_yml` fixture from in `test_unit_testing.py`:
```
test_my_model_incremental_yml = """
unit_tests:
  - name: incremental_false
...
```
to: 
```
test_my_model_incremental_yml = """
unit_tests:
  - name: test_incremental_false
...
```

Results in: 
```
15:58:28  Completed with 1 error and 0 warnings:
15:58:28  
15:58:28    Runtime Error in unit_test my_incremental_model__test_incremental_false (models/test_my_incremental_model.yml)
  Relation name '__dbt__cte__my_incremental_model__test_incremental_false__events' is longer than 63 characters
15:58:28  
15:58:28  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

This is happening because the ephemeral fixture nodes are named based on the concatenation of: the model being tested, the name of the unit test, and the name of the input itself. This ensures they have globally unique names in the unit test manifest but is overkill for the purpose of naming the CTEs, which are local to a unit test case.

Options: 
Shorten the name of the ModelNode for input fixtures to only include the name of the original input node -- assuming that node names don't need to be unique within a DAG. - These aren't used in a DAG, so this shouldn't be a concern.
Consider hashing to add extra layer of caution to avoid name duplication.
These are ephemeral names only they are not executable.

### Testing Considerations:

- Test having 2 input models with same names and different packages.

**Comment by jtcohen6** [comment]
We have some prior art for this:

https://github.com/dbt-labs/dbt-core/blob/bb35b3eb87ab2543247fd6ea51f6043bb89a1f89/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L141-L178

**Comment by graciegoheen** [comment]
I ran into the same issue when testing this out, is there any way to make this CTE name shorter without requiring folks to have a shorter name for their unit test?

**Comment by dbeatty10** [comment]
@dave-connors-3 ran into this too.
