### ISSUE TITLE
[CT-3332] Remove usage of dbt.semver in dbt/adapters

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#9022]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

`dbt.semver.VersionSpecifier.from_version_string` and `dbt.semver.VersionSpecifier.to_version_string`

are used in the AdapterContainer to fire an event when registering adapters.

Implementation options:
1. semver module could be moved to new dbt/common directory, created in https://github.com/dbt-labs/dbt-core/pull/8906
2. adapter registration can be moved into core (https://github.com/dbt-labs/dbt-core/issues/9025)
3. functionality of VersionSpecifier.from_version_string and VersionSpecifier.to_version_string could be re-implemented in a standalone adapter version method defined in dbt/adapters
    * could use semantic-version package, which is used by dbt-core-bundles: https://github.com/dbt-labs/dbt-core-bundles/blob/main/requirements.txt#L3

(3) feels most practical given the limited amount of functionality from semver used in dbt/adapters.
### Acceptance criteria

dbt/adapters has no dependency on `dbt.semver` 

### Impact to Other Teams

1p adapter imports will need to be updated, but those can be done separately as part of a bundled migration of 1p for https://github.com/dbt-labs/dbt-core/issues/8917 if the work is done on a feature branch: https://github.com/dbt-labs/dbt-core/pull/8906

### Will backports be required?

No

**Comment by VersusFacit** [comment]
Progress

- [x] Redshift
- [ ] Snowflake
- [ ] Bigquery
- [ ] Spark
- [ ] Postgres

**Comment by VersusFacit** [comment]
Update. Waiting for some answers from Cloud config folks on safety to address this with a simple move. I have the code change for Core pretty much good to go. Just don't want to merge before I have a plan for downstream workflows.

**Comment by MichelleArk** [comment]
Resolved by: https://github.com/dbt-labs/dbt-core/pull/9166
