### ISSUE TITLE
[CT-3370] [implementation] ensure dbt retry works with unit tests

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9053]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Acceptance criteria

`dbt retry` re-executes the last dbt command from the node point of failure. 

Once we finish swapping over the `dbt unit-test` command to `dbt build` and `dbt test` with selectors  (https://github.com/dbt-labs/dbt-core/issues/8979), let's confirm `dbt retry` still works.

If a unit test fails in a `dbt test` or a `dbt build`, `dbt retry` should re-execute that dbt command from the failed unit test.

- check that this works for `dbt build` and `dbt test`
- add integration tests

### Impact to Other Teams

none

### Will backports be required?

no

**Comment by jtcohen6** [comment]
This appears to be working (in simple cases). I added an initial functional test for this in #9032:
https://github.com/dbt-labs/dbt-core/blob/cc942698a1062bf98b3118dcbcc277de0a1ca4d5/tests/functional/unit_testing/test_unit_testing.py#L172-L179

**Comment by graciegoheen** [comment]
Open question from refinement:
- how will this work given we have a separate manifest for unit testing

**Comment by MichelleArk** [comment]
@graciegoheen I believe this was resolved by: https://github.com/dbt-labs/dbt-core/pull/9032

test case here: 
https://github.com/dbt-labs/dbt-core/pull/9032/files#diff-0f0c14a88170fc0b4f9e86ec195ef3df5a15801b97ccca70dfcefe1c58210832R108

**Comment by graciegoheen** [comment]
I thought we changed the acceptance criteria to work on this ticket after we switched over the unit testing commands?
