### ISSUE TITLE
[CT-3376] [Bug] dbt snapshot throws "SSL connection has been closed unexpectedly"

### ISSUE THREAD

**Issue by rm-minus-r-star** [dbt-labs/dbt-core#9061]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Encountered problem similar to https://github.com/dbt-labs/dbt-core/issues/4853#issue-1165307353, except that snapshot did not succeed in spite of the error as it did in that report.

In each of 7 attempts, I get and ERROR with `"SSL connection has been closed unexpectedly"` after anywhere from 45-121 seconds.

Assuming this was some kind of connectivity issue, I tried, with no luck:
- increase max compute from 0.25 CPU to 1.0 in case resource limitation was causing the issue
- setting dbt profile option connect_timeout to 300
- setting dbt prfile option sslmode to 'require'

I also filed a ticket with the DB server host, hoping something in the logs on their end could help shed light on the issue.

Ultimately I realised that the dbt error and all subsequent reasoning based on it meaning something was inaccurate. 

I had specified the "unique_key" column in the config with single quotes instead of double. Fixing this allowed snapshot to run successfully.

### Expected Behavior

When this mistake is made in postgres, a fairly obvious exception is thrown. The dev says "doh", fixes it quickly, and moves on.

I would have expected dbt to pass through an error like this rather than lead one to believe the connection has problems.

### Steps To Reproduce

~Use single quotes for the unique_key column in a snapshot file.~

Update:

> I've tried going back and running dbt snapshot with both single and double quotes, and I get the same failure mode no matter what now. I've re-opened the case with my host provider, on the hope that their logs will enlighten.

### Relevant log output

```shell
21:10:48.267844 [debug] [Thread-2 (]: Postgres adapter: Postgres error: SSL connection has been closed unexpectedly

21:10:48.268563 [debug] [Thread-2 (]: On snapshot.dbt_ppi.snapshot_ppi: ROLLBACK
21:10:48.269575 [debug] [Thread-2 (]: Failed to rollback 'snapshot.dbt_ppi.snapshot_ppi'
21:10:48.270517 [debug] [Thread-2 (]: Timing info for snapshot.dbt_ppi.snapshot_ppi (execute): 21:09:49.896703 => 21:10:48.270209
21:10:48.271107 [debug] [Thread-2 (]: On snapshot.dbt_ppi.snapshot_ppi: Close
21:10:48.273701 [debug] [Thread-2 (]: Database Error in snapshot snapshot_ppi (snapshots/snapshot_ppi.sql)
  SSL connection has been closed unexpectedly
21:10:48.274393 [debug] [Thread-2 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '28fab020-c092-4c56-a996-9bd94d391f09', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f535ba24400>]}
21:10:48.275530 [error] [Thread-2 (]: 1 of 1 ERROR snapshotting snapshots.snapshot_ppi ............................... [ERROR in 58.39s]
21:10:48.276046 [debug] [Thread-2 (]: Finished running node snapshot.dbt_ppi.snapshot_ppi
21:10:48.277728 [debug] [MainThread]: Using postgres connection "master"
21:10:48.278359 [debug] [MainThread]: On master: BEGIN
21:10:48.278843 [debug] [MainThread]: Opening a new connection, currently in state closed
21:10:53.515085 [debug] [MainThread]: SQL status: BEGIN in 5.0 seconds
21:10:53.515698 [debug] [MainThread]: On master: COMMIT
21:10:53.516138 [debug] [MainThread]: Using postgres connection "master"
21:10:53.516569 [debug] [MainThread]: On master: COMMIT
21:10:53.664440 [debug] [MainThread]: SQL status: COMMIT in 0.0 seconds
21:10:53.664985 [debug] [MainThread]: On master: Close
21:10:53.665925 [debug] [MainThread]: Connection 'master' was properly closed.
21:10:53.666336 [debug] [MainThread]: Connection 'snapshot.dbt_ppi.snapshot_ppi' was properly closed.
21:10:53.666805 [info ] [MainThread]: 
21:10:53.667412 [info ] [MainThread]: Finished running 1 snapshot in 0 hours 1 minutes and 24.31 seconds (84.31s).
21:10:53.668224 [debug] [MainThread]: Command end result
21:10:53.746113 [info ] [MainThread]: 
21:10:53.746581 [info ] [MainThread]: Completed with 1 error and 0 warnings:
21:10:53.746870 [info ] [MainThread]: 
21:10:53.747172 [error] [MainThread]: Database Error in snapshot snapshot_ppi (snapshots/snapshot_ppi.sql)
21:10:53.747459 [error] [MainThread]:   SSL connection has been closed unexpectedly
21:10:53.747733 [info ] [MainThread]: 
21:10:53.748040 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
21:10:53.748546 [debug] [MainThread]: Command `dbt snapshot` failed at 21:10:53.748466 after 85.55 seconds
21:10:53.748832 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f53a3d12da0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f535ba13f70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5360a78490>]}
21:10:53.749111 [debug] [MainThread]: Flushing usage events
21:14:59.000519 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f33b5c71c00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f33b48c3940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f33b48c38b0>]}
```

### Environment

```markdown
- OS: Xubuntu 20.04
- Python: 3.10.13
- dbt: 1.5.4
```

### Which database adapter are you using with dbt?

postgres

**Comment by rm-minus-r-star** [comment]
It turns out the solution assumed above was not relevant. It is failing again today with the same error message with no further change to any code:

17:00:52.458833 [debug] [Thread-2 (]: Postgres adapter: Postgres error: SSL connection has been closed unexpectedly

17:00:52.459582 [debug] [Thread-2 (]: On snapshot.dbt_ppi.snapshot_ppi: ROLLBACK
17:00:52.460648 [debug] [Thread-2 (]: Failed to rollback 'snapshot.dbt_ppi.snapshot_ppi'
17:00:52.461531 [debug] [Thread-2 (]: Timing info for snapshot.dbt_ppi.snapshot_ppi (execute): 16:58:45.013617 => 17:00:52.461219
17:00:52.462079 [debug] [Thread-2 (]: On snapshot.dbt_ppi.snapshot_ppi: Close
17:00:52.464693 [debug] [Thread-2 (]: Database Error in snapshot snapshot_ppi (snapshots/snapshot_ppi.sql)
  SSL connection has been closed unexpectedly
17:00:52.465309 [debug] [Thread-2 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '55ee3e4c-9ead-4255-b045-db56de13cd6f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f311d14e8f0>]}
17:00:52.466386 [error] [Thread-2 (]: 1 of 1 ERROR snapshotting snapshots.snapshot_ppi ............................... [ERROR in 127.47s]
17:00:52.467235 [debug] [Thread-2 (]: Finished running node snapshot.dbt_ppi.snapshot_ppi
17:00:52.469002 [debug] [MainThread]: Using postgres connection "master"
17:00:52.469567 [debug] [MainThread]: On master: BEGIN
17:00:52.469982 [debug] [MainThread]: Opening a new connection, currently in state closed
17:01:01.046252 [debug] [MainThread]: SQL status: BEGIN in 9.0 seconds
17:01:01.047071 [debug] [MainThread]: On master: COMMIT
17:01:01.047387 [debug] [MainThread]: Using postgres connection "master"
17:01:01.047697 [debug] [MainThread]: On master: COMMIT
17:01:01.194217 [debug] [MainThread]: SQL status: COMMIT in 0.0 seconds
17:01:01.194864 [debug] [MainThread]: On master: Close
17:01:01.195894 [debug] [MainThread]: Connection 'master' was properly closed.
17:01:01.196327 [debug] [MainThread]: Connection 'snapshot.dbt_ppi.snapshot_ppi' was properly closed.
17:01:01.196787 [info ] [MainThread]: 
17:01:01.197493 [info ] [MainThread]: Finished running 1 snapshot in 0 hours 2 minutes and 35.49 seconds (155.49s).
17:01:01.198421 [debug] [MainThread]: Command end result
17:01:01.215562 [info ] [MainThread]: 
17:01:01.216033 [info ] [MainThread]: Completed with 1 error and 0 warnings:
17:01:01.216329 [info ] [MainThread]: 
17:01:01.216628 [error] [MainThread]: Database Error in snapshot snapshot_ppi (snapshots/snapshot_ppi.sql)
17:01:01.216914 [error] [MainThread]:   SSL connection has been closed unexpectedly
17:01:01.217231 [info ] [MainThread]: 
17:01:01.217549 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
17:01:01.218066 [debug] [MainThread]: Command `dbt snapshot` failed at 17:01:01.217981 after 156.55 seconds
17:01:01.218356 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f316144cfd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f311cff42b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f311cff40a0>]}
17:01:01.218637 [debug] [MainThread]: Flushing usage events

**Comment by dbeatty10** [comment]
Thanks for reporting this @rm-minus-r-star !

It sounds like this **does not** reproduce the issue for you after all?

> Use single quotes for the unique_key column in a snapshot file.

If not, do you know how to reliably reproduce this issue? We'll need to be able to reproduce it in order to try fixing it.

**Comment by rm-minus-r-star** [comment]
apologies @dbeatty10, that's now correct. I've tried going back and running `dbt snapshot` with both single and double quotes, and I get the same failure mode no matter what now. I've re-opened the case with my host provider, on the hope that their logs will enlighten. 

The only other thing I can offer is that snapshot worked flawlessly when each run was inserting entirely new data. This is the first occasion where I'm ingesting refreshed data -- one month's worth of new data, with revision on (I told) 4-7% of data already in DB. In the config, I've specified as composite column (defined in the SELECT statement) as the unique key, strategy is 'check', and then listed all columns that are not a component of the unique key in the check_cols. As mentioned, it apparently fluked that once (leading me to believe it was a quoting issue), but has failed perhaps 10 times now on a second tranche of refreshed/revised data.

**Comment by dbeatty10** [comment]
Okay, let us know what you hear back from your provider. In the meantime, I'm going to update the description to add the following:

> I've tried going back and running dbt snapshot with both single and double quotes, and I get the same failure mode no matter what now. I've re-opened the case with my host provider, on the hope that their logs will enlighten.
