### ISSUE TITLE
[CT-3380] [Implementation] Include file-based fixtures in parsed files during partial parsing

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#9067]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

If a file-based unit test fixture is modified between dbt invocations, this should be detected in partial parsing and trigger the scheduling of parsing UnitTestDefinition nodes that depend on the fixture. 

Otherwise, it's possible to make changes to a fixture file that won't be detected in state:modified when running unit tests. 

### Acceptance criteria

* remove `--no-partial-parse` flag from this test: TODO

### Impact to Other Teams

N/A

### Will backports be required?

nope - working off a net-new feature branch. 

### Context

Initial discussion: https://github.com/dbt-labs/dbt-core/pull/9032

**Comment by graciegoheen** [comment]
Notes from estimation:
- schema file, source file, this might be a new kind of file object
- links to every place it's used ?
