### ISSUE TITLE
[CT-3382] [Bug] `dbt deps --add-package` does not work

### ISSUE THREAD

**Issue by seub** [dbt-labs/dbt-core#9076]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The `dbt deps --add-package` command does not work. Unless I'm missing something, it's not doing anything.

Also, note that the [doc](https://docs.getdbt.com/reference/commands/deps) doesn't give the correct syntax:
-  `add --package` instead of `--add-package`
- an incorrect `--add` flag is mentioned

### Expected Behavior

Adds entry to `packages.yml`

### Steps To Reproduce

`dbt deps --add-package dbt-labs/dbt_utils --version 1.0.0`

### Environment

```markdown
- OS: Ubuntu 16.04
- Python: 3.9.16
- dbt: 1.7.1
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @seub !

I opened a PR to fix the documentation here: https://github.com/dbt-labs/docs.getdbt.com/pull/4470

Could you try out these examples and see if they work for you?

```shell
# add package from hub (--source arg defaults to "hub")
dbt deps --add-package dbt-labs/dbt_utils@1.0.0

# add package from hub with semantic version range
dbt deps --add-package dbt-labs/snowplow@">=0.7.0,<0.8.0"

# add package from git
dbt deps --add-package https://github.com/fivetran/dbt_amplitude@v0.3.0 --source git

# add package from local
dbt deps --add-package /opt/dbt/redshift --source local

# add package to packages.yml and package-lock.yml WITHOUT actually installing dependencies
dbt deps --add-package dbt-labs/dbt_utils@1.0.0 --dry-run
```

**Comment by seub** [comment]
Thanks @dbeatty10.

I tried these examples and they all result in a similar error:
```shell
dbt deps --add-package dbt-labs/dbt_utils@1.0.0

03:02:33  Running with dbt=1.7.1
03:02:34  Encountered an error:
argument of type 'bool' is not iterable
03:02:34  Traceback (most recent call last):
  File "/path/to/project/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
  File "/path/to/project/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/path/to/project/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 151, in wrapper
    return func(*args, **kwargs)
  File "/path/to/project/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 197, in wrapper
    return func(*args, **kwargs)
  File "/path/to/project/.venv/lib/python3.9/site-packages/dbt/cli/main.py", line 492, in deps
    results = task.run()
  File "/path/to/project/.venv/lib/python3.9/site-packages/dbt/task/deps.py", line 207, in run
    self.add()
  File "/path/to/project/.venv/lib/python3.9/site-packages/dbt/task/deps.py", line 160, in add
    packages_yml = self.check_for_duplicate_packages(packages_yml)
  File "/path/to/project/.venv/lib/python3.9/site-packages/dbt/task/deps.py", line 138, in check_for_duplicate_packages
    if self.args.add_package["name"] in val:
TypeError: argument of type 'bool' is not iterable
```

I used Python 3.9.16, dbt-core 1.7.1, dbt-snowflake 1.7.0.

**Comment by dbeatty10** [comment]
Oof.

What are the contents of `packages.yml`? If it exists, what are the contents of `package-lock.yml`?

If you start with no `packages.yml` at all and run that command, do you still get that same error?

**Comment by seub** [comment]
Ah, I see, it doesn't like `warn-unpinned: false`.

If I start with this packages.yml:
```yml
packages:
  - git: https://github.com/fivetran/dbt_amplitude
  ```
 then everything works fine, however I get the error with this:
 ```
 packages:
  - git: https://github.com/fivetran/dbt_amplitude
    warn-unpinned: false
 ```
 
 
 Looking at the code in dbt-core, it seems to me that the `in` on [line 138](https://github.com/dbt-labs/dbt-core/blob/017faf4bd18eefe030d87f61d6dd9e4a56cec020/core/dbt/task/deps.py#L138C1-L139C1) should be replaced by an `==`.

(Better yet, first find the correct value for `val`, i.e. the one where the key is `package`/`git`/`local`/`tarball`. Isn't there a method for that somewhere?)

**Comment by dbeatty10** [comment]
Thanks again for reporting this and helping get to the bottom of this @seub !

I just opened #9104, and I'm going to close this one in favor of it and https://github.com/dbt-labs/docs.getdbt.com/pull/4470.
