### ISSUE TITLE
[CT-3391] [Regression] dbt clean fails with "directories outside the project" error

### ISSUE THREAD

**Issue by katieclaiborne** [dbt-labs/dbt-core#9089]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

After upgrading to dbt-core v1.7.1, `dbt clean` fails with a runtime error. (See log output below.)

### Expected/Previous Behavior

In dbt-core v1.6.8, `dbt clean` executed smoothly, and I expected v1.7.1 to behave the same way.

```
19:02:25  Running with dbt=1.6.8
19:02:25  Checking target/*
19:02:25  Cleaned target/*
19:02:25  Checking dbt_packages/*
19:02:25  Cleaned dbt_packages/*
19:02:25  Finished cleaning all paths.
```

### Steps To Reproduce

1. Install dbt-core v1.7.1.
2. Initialize a dbt project in the `dbt` directory of a GitHub repository.
3. Set the `DBT_PROJECT_DIR` environment variable to `"dbt"`
4. Add packages to a `packages.yml` file (see example below).
5. From the root of the GitHub repo, execute `dbt deps` to install them.
6. From the root of the GitHub repo, execute `dbt clean` to generate the runtime error.

```yaml
packages:
  - package: dbt-labs/dbt_project_evaluator
    version: [">=0.8.0", "<0.9.0"]
```

### Relevant log output

```shell
19:02:51  Running with dbt=1.7.1
19:02:51  Encountered an error:
Runtime Error
  dbt will not clean the following directories outside the project: ['/Users/katie.claiborne/github-repos/cbh-member-appts/dbt/target', '/Users/katie.claiborne/github-repos/cbh-member-appts/dbt/dbt_packages']
```

### Environment

```markdown
- OS: macOS-13.6.1-arm64-arm-64bit
- Python: 3.9.10
- dbt (working version): 1.6.8
- dbt (regression version): 1.7.1
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

Our project uses the default `clean-targets` config.

```
clean-targets:
  - "target"
  - "dbt_packages"

**Comment by MichelleArk** [comment]
Thank you for opening this issue! I think this may have been intentionally introduced by https://github.com/dbt-labs/dbt-core/pull/8469.

A workaround may be to run [`dbt clean --no-clean-project-files-only`](f328aa466db7d10c562b1d34db497f911c05b6d1210988f127e07fa198a14763R427). Could you please give that a try @katieclaiborne?

**Comment by katieclaiborne** [comment]
Oh yes, that works!
```
(venv) CBM-FVFGRAA9Q05N:cbh-member-appts katie.claiborne$ dbt clean --no-clean-project-files-only
21:38:44  Running with dbt=1.7.1
21:38:44  Checking /Users/katie.claiborne/github-repos/cbh-member-appts/dbt/target/*
21:38:44  Cleaned /Users/katie.claiborne/github-repos/cbh-member-appts/dbt/target/*
21:38:44  Checking /Users/katie.claiborne/github-repos/cbh-member-appts/dbt/dbt_packages/*
21:38:44  Cleaned /Users/katie.claiborne/github-repos/cbh-member-appts/dbt/dbt_packages/*
21:38:44  Finished cleaning all paths.

**Comment by MichelleArk** [comment]
Nice! We should probably add this to the [1.7 upgrade guide](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.7#behavior-changes)

**Comment by dbeatty10** [comment]
> Nice! We should probably add this to the [1.7 upgrade guide](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.7#behavior-changes)

Per @MichelleArk's comment, closing this in favor of adding this to the upgrade guide: https://github.com/dbt-labs/docs.getdbt.com/issues/4482

Thanks again @katieclaiborne 🏆
