### ISSUE TITLE
[CT-3395] [Feature] Merge `--dry-run` and `--lock` into the same flag for dbt deps

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#9100]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

> I don't see the need for both the flags `--dry-run` and `--lock`, they could be merged into a same flag as far as I can tell.

_Originally posted by @seub in https://github.com/dbt-labs/docs.getdbt.com/issues/4470#issuecomment-1811769591_
            

### Describe alternatives you've considered

See https://github.com/dbt-labs/docs.getdbt.com/issues/4470#issuecomment-1811769591_ for context

### Who will this benefit?

See https://github.com/dbt-labs/docs.getdbt.com/issues/4470#issuecomment-1811769591_ for context

**Comment by jtcohen6** [comment]
This looks right:

https://github.com/dbt-labs/dbt-core/blob/09355701f6e04142085cb18d69e65e658d146f83/core/dbt/task/deps.py#L223-L225

I think I prefer `--lock` to `--dry-run`! It feels like a clearer description of what's happening, and it avoids potential confusion with other "dry run" type functionality in dbt, e.g. #8971 or #7839
