### ISSUE TITLE
[CT-3397] [Bug] agate pinned to 1.7.1 instead of 1.7.0

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#9107]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

agate pin in setup.py is `agate ~=1.7.1` on `1.7.latest`.  Other branches are pinned correctly.

### Expected Behavior

agate pin in setup.py is `agate ~=1.7.0` 

### Steps To Reproduce

n/a

### Relevant log output

```shell
n/a
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

This is due to a bug with our version bump during releases.  Ticket to fix root cause coming.

**Comment by dbeatty10** [comment]
resolved by #9106
