### ISSUE TITLE
[CT-3405] [SL] Upgrade to dbt-semantic-interfaces 0.5.x

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#9117]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

We're making a number of changes in https://github.com/dbt-labs/dbt-core/issues/9116. These should also be represented in a `0.5.0` release of [dbt-semantic-interfaces](https://github.com/dbt-labs/dbt-semantic-interfaces/). Once `0.5.0` is released of `dbt-semantic-interfaces`, we should upgraded the dep requirement in dbt-core's [setup.py](https://github.com/dbt-labs/dbt-core/blob/19f027b7a7174067ead9aa18029baad5510c57cc/core/setup.py#L76) to `dbt-semantic-interfaces>=0.5.0,<0.6`

### Acceptance criteria

dbt-core depends on non-prerelease `0.5.*` versions of dbt-semantic-interfaces

### Impact to Other Teams

This will be necessary for the SL team to upgrade MetricFlow appropriately for DSI 0.5 and dbt-core 1.8 support. Additionally dbt-core won't begin outputting to the semantic manifest artifact any new properties we've added which are DSI 0.5.x exclusive until core is actually using DSI 0.5.x

### Will backports be required?

No

### Context

Low risk change.

**Comment by aranke** [comment]
@QMalcolm I don't see `dbt-semantic-interfaces v0.5.0` on [PyPI](https://pypi.org/project/dbt-semantic-interfaces/#history) or [GitHub](https://github.com/dbt-labs/dbt-semantic-interfaces/tags), any idea when it might be released?
