### ISSUE TITLE
[CT-3453] [Feature] {% doc %} instead of {% docs %} for consistency with {{ doc() }}

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#9209]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

It is one of our cruelest tricks that you define a doc block as

```
{% docs table_events %}
This table contains clickstream events from the marketing website.
{% enddocs %}
```

and consume it as 

```
version: 2

models:
  - name: events
    description: '{{ doc("table_events") }}'
```

Because I can never remember whether there it's `docs` or `doc`, or which way around they go. 

We should change to `{% doc %}` (while retaining backwards compatibility with `{% docs %}`).

### Who will this benefit?

People who don't like looking at dbt documentation (but like... writing... dbt documentation 😅)

### Are you interested in contributing this feature?

/giphy coin flip

**Comment by graciegoheen** [comment]
Hey @joellabes thanks for opening! 

I agree if we had a time machine, we would go back and make this `doc` everywhere for consistency - it's definitely an annoying thing to remember. 

That being said, I don't think that the effort involved to update this (and ensure backwards compatibility, etc. etc.) is worth the benefit we'd get. I don't think this is actually _confusing_, it's just _annoying_. I'm going to close as not planned for now, but if we get more feedback on it we can reconsider.
