### ISSUE TITLE
[CT-3477] [OSS] OSS Standardization

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#9252]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

As part of #9221, there have been a few changes to how we want to format docs/templates in our OSS repos.

1. .github/TEMPLATES
    - remove mention of notion specifically in [implementation-ticket.yml](https://github.com/dbt-labs/dbt-core/blob/main/.github/ISSUE_TEMPLATE/implementation-ticket.yml) and just say "documentation"
2.  CONTRIBUTING.md
    - Add troubleshooting section to the bottom similar to the template in `dbt-docs` [here](https://github.com/dbt-labs/dbt-core/issues/9252)
    - Remove mention of Jira - we don't use it for `dbt-core` anymore
    - We don't have integration tests anymore, so remove their mention [here](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#unit-integration-functional)
3. README.md
    - Update the following line

```
Want to report a bug or request a feature? Let us know on [Slack](http://community.getdbt.com/), or open [an issue](https://github.com/dbt-labs/dbt-core/issues/new)
```

to

 ```
Want to report a bug or request a feature? Let us know and open [an issue](https://github.com/dbt-labs/dbt-core/issues/new/choose)
```

### Acceptance criteria

The docs in this repo meet the same formatting standards as `dbt-oss-template`

### Impact to Other Teams

None, this is just a docs change

### Will backports be required?

Nope

### Context

Any other changes to make it easier for contributors would be welcome!

**Comment by Tonayya** [comment]
[PR](https://github.com/dbt-labs/dbt-core/pull/9316) for issue 1.
Hey @emmyoop with issue 2, is there actually any troubleshooting steps I can add to this new section, or are we just creating the section and leaving blank? With removal of mention of JIRA, this was for the branch naming convention for internal contributors that said to use CT-XXXX, whats the replacement for this? Should I just say use your initials?
