### ISSUE TITLE
[CT-3479] [Bug] Failed custom generic test on `upstream` does not block `downstream_1` model from running if the custom generic test includes ref to `downstream_2`

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#9256]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If we have custom generic test on `upstream` that ref's another model `downstream_2` - it does not block `downstream_1` from running.

### Expected Behavior

If the custom generic test on `upstream` that ref's another model `downstream_2` fails, it SHOULD block `downstream_1` from running.

### Steps To Reproduce

1. Let's start with a pretty simple setup.

```yml
# dbt_project.yml
name: my_dbt_project
profile: all
config-version: 2
version: "1.0.0"

models:
  my_dbt_project:
    +materialized: table

# models/schema.yml
version: 2
models:
  - name: upstream
    tests:
      - test_custom
```

```sql
-- models/upstream.sql
select 1 id

-- models/downstream_1.sql
select * from {{ ref('upstream') }}

-- tests/generic/test_custom.sql
{% test test_custom(model) %}
select 1 as c
  from {{ model }}
{% endtest %}
```

^ The generic test is written to fail.

DAG:

```mermaid
flowchart LR
    upstream --> downstream_1
```

```sh
$ dbt build -s upstream downstream_1 --threads 1

02:58:38  Running with dbt=1.6.9
02:58:38  Registered adapter: postgres=1.6.9
02:58:40  Found 2 models, 1 test, 0 sources, 0 exposures, 0 metrics, 353 macros, 0 groups, 0 semantic models
02:58:40  
02:58:40  Concurrency: 1 threads (target='pg-local')
02:58:40  
02:58:40  1 of 3 START sql table model public.upstream ................................... [RUN]
02:58:40  1 of 3 OK created sql table model public.upstream .............................. [SELECT 1 in 0.30s]
02:58:40  2 of 3 START test test_custom_upstream_ ........................................ [RUN]
02:58:40  2 of 3 FAIL 1 test_custom_upstream_ ............................................ [FAIL 1 in 0.06s]
02:58:40  3 of 3 SKIP relation public.downstream_1 ....................................... [SKIP]
02:58:40  
02:58:40  Finished running 2 table models, 1 test in 0 hours 0 minutes and 0.59 seconds (0.59s).
02:58:40  
02:58:40  Completed with 1 error and 0 warnings:
02:58:40  
02:58:40  Failure in test test_custom_upstream_ (models/schema.yml)
02:58:40    Got 1 result, configured to fail if != 0
02:58:40  
02:58:40    compiled Code at target/compiled/my_dbt_project/models/schema.yml/test_custom_upstream_.sql
02:58:40  
02:58:40  Done. PASS=1 WARN=0 ERROR=1 SKIP=1 TOTAL=3
```

Here - things work as expected:

1. `upstream` is run.
2. `test_custom` on `upstream` executes and fails.
3. `downstream_1` skips.

Let's introduce another downstream model and reconfigure out custom test to ref that model:

```sql
-- models/upstream.sql
select 1 id

-- models/downstream_1.sql
select * from {{ ref('upstream') }}

-- models/downstream_2.sql
select * from {{ ref('upstream') }}

-- tests/generic/test_custom.sql
{% test test_custom(model) %}
select 1 as c
  from {{ model }}
  join {{ ref('downstream_2') }} using (id)
{% endtest %}
```

DAG:

```mermaid
flowchart LR
    upstream --> downstream_1
    upstream --> downstream_2
```

```sh
$ dbt build -s upstream downstream_1 --threads 1

03:07:10  Running with dbt=1.6.9
03:07:10  Registered adapter: postgres=1.6.9
03:07:12  Found 3 models, 1 test, 0 sources, 0 exposures, 0 metrics, 353 macros, 0 groups, 0 semantic models
03:07:12  
03:07:12  Concurrency: 1 threads (target='pg-local')
03:07:12  
03:07:12  1 of 3 START sql table model public.upstream ................................... [RUN]
03:07:12  1 of 3 OK created sql table model public.upstream .............................. [SELECT 1 in 0.20s]
03:07:12  2 of 3 START sql table model public.downstream_1 ............................... [RUN]
03:07:12  2 of 3 OK created sql table model public.downstream_1 .......................... [SELECT 1 in 0.16s]
03:07:12  3 of 3 START test test_custom_upstream_ ........................................ [RUN]
03:07:12  3 of 3 FAIL 1 test_custom_upstream_ ............................................ [FAIL 1 in 0.11s]
03:07:12  
03:07:12  Finished running 2 table models, 1 test in 0 hours 0 minutes and 0.68 seconds (0.68s).
03:07:12  
03:07:12  Completed with 1 error and 0 warnings:
03:07:12  
03:07:12  Failure in test test_custom_upstream_ (models/schema.yml)
03:07:12    Got 1 result, configured to fail if != 0
03:07:12  
03:07:12    compiled Code at target/compiled/my_dbt_project/models/schema.yml/test_custom_upstream_.sql
03:07:12  
03:07:12  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
```

Now we see something strange (not very intuitive) - i.e. the `test_custom` test is no longer blocking `downstream_1` from running because it is the final thing to be executed. From a DAG perspective, certainly `test_custom` depends on both `upstream` AND `downstream_2` to finish first so it apparently makes that be in a sequence AFTER `downstream_1` - we can see this if we simply run without selection:

```sh
$ dbt build --threads 1

03:10:48  Running with dbt=1.6.9
03:10:48  Registered adapter: postgres=1.6.9
03:10:49  Found 3 models, 1 test, 0 sources, 0 exposures, 0 metrics, 353 macros, 0 groups, 0 semantic models
03:10:49  
03:10:49  Concurrency: 1 threads (target='pg-local')
03:10:49  
03:10:49  1 of 4 START sql table model public.upstream ................................... [RUN]
03:10:50  1 of 4 OK created sql table model public.upstream .............................. [SELECT 1 in 0.17s]
03:10:50  2 of 4 START sql table model public.downstream_1 ............................... [RUN]
03:10:50  2 of 4 OK created sql table model public.downstream_1 .......................... [SELECT 1 in 0.08s]
03:10:50  3 of 4 START sql table model public.downstream_2 ............................... [RUN]
03:10:50  3 of 4 OK created sql table model public.downstream_2 .......................... [SELECT 1 in 0.07s]
03:10:50  4 of 4 START test test_custom_upstream_ ........................................ [RUN]
03:10:50  4 of 4 FAIL 1 test_custom_upstream_ ............................................ [FAIL 1 in 0.11s]
03:10:50  
03:10:50  Finished running 3 table models, 1 test in 0 hours 0 minutes and 0.63 seconds (0.63s).
03:10:50  
03:10:50  Completed with 1 error and 0 warnings:
03:10:50  
03:10:50  Failure in test test_custom_upstream_ (models/schema.yml)
03:10:50    Got 1 result, configured to fail if != 0
03:10:50  
03:10:50    compiled Code at target/compiled/my_dbt_project/models/schema.yml/test_custom_upstream_.sql
03:10:50  
03:10:50  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
```

In the 3 node DAG, if we think of only:
* `upstream` + `downstream_2` - it makes sense that the test should run AFTER `downstream_2` is built.
* `upstream` + `downstream_1` alone - does it make sense that the test be run only at the end? Kinda weird.

I think though, we should still want to block `downstream_1` from being executed - not too sure whats the right call to make here but there's certainly some unintuitive-ness going on. If a user is using many threads as well - it becomes kinda tricky to understand this situation. The following sequence makes sense to me:

If the selection was `dbt build`:
1. `upstream` runs.
2. `downstream_2` runs.
3. `test_custom` on `upstream` runs and fails.
4. `downstream_1` is skipped.

If the selection was `dbt build -s upstream downstream_1`:
1. `upstream` runs.
3. `test_custom` on `upstream` runs and fails.
4. `downstream_1` is skipped.

### Relevant log output

I don't think it's useful for this situation.

### Environment

```markdown
- OS: macOS
- Python: 3.9.13
- dbt: dbt-core==1.6.9 / dbt-postgres==1.6.9
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

I tested on dbt 1.4 as well.

**Comment by jtcohen6** [comment]
@jeremyyeo Thanks for the thorough write-up! I agree this is one of those edge cases where we need to make a trade-off, and either way it will be unintuitive for someone.

This issue from last year describes a very similar case:
- https://github.com/dbt-labs/dbt-core/issues/5277

The current behavior within the `dbt build` command is:
- If a test depends on both an `upstream` and a `downstream` model, where `upstream -> downstream`, it resolves the transitive dependency and effectively treats itself as a test on `downstream` only.
- Tests add edges between themselves and nodes downstream of their parents. But they do not _rewrite_ the edges between their parent nodes and other nodes in the DAG. `downstream_1` does not depend on `downstream_2`, independent of `test_custom`, and so `test_custom` does not add an edge from itself to `downstream_1`.

It should be possible to achieve the desired behavior here by "mocking" a dependency from `downstream_1` onto `downstream_2`:
```sql
-- models/downstream_1.sql

-- depends on: {{ ref('downstream_2') }}

select ...
```

**Comment by BPilippG** [comment]
Hey all,

Great issue description, @joevandyk ! 

I‘d love to give this topic new attention. Manually mocking dependencies won‘t work in projects at scale and would be exceptionally prone to errors.

Doesn‘t the failure of a test that references mutliple models indicate that sth. might be wrong with any of them? This means it isn‘t safe to build any model downstream that depends on at least one model involved in the test.

 @jtcohen6 , do you happen to know why dbt build behaves like this?

Thanks & best wishes!
