### ISSUE TITLE
[CT-3511] [Feature] Custom merge update expressions on incremental models

### ISSUE THREAD

**Issue by monti-python** [dbt-labs/dbt-core#9312]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The current implementation of the `merge` incremental strategy always overwrites all columns whenever there are new rows with an existing `unique_key`. However, in many cases custom update expressions are necessary, especially when the previous value of a particular column needs to be taken into account. 

As an example, consider the following table (`orders`):

|order_id|user_id|order_ts|
|---|---|---|
|1|A|2023-12-14 10:01:00|
|2|A|2023-12-14 10:02:00|
|3|B|2023-12-14 10:03:00|
|4|B|2023-12-14 10:04:00|
|5|B|2023-12-14 10:05:00|
|6|A|2023-12-15 10:06:00|
|7|A|2023-12-15 10:07:00|

<br>

Let's assume we want to keep track of the number of orders per user and the timestamp of the last order from each user. The naive approach would be to group by `user_id` and aggregate:

<br>

```sql
{{ config(materialized='table') }}

select
    user_id,
    count(order_id) as order_count,
    max(order_ts) as last_order_ts
from orders
group by user_id
order by user_id
```

|user_id|order_count|last_order_ts|
|---|---|---|
|A|4|2023-12-15 10:07:00|
|B|3|2023-12-14 10:05:00|

<br>

As the number of orders and users grows by orders of magnitude, aggregating the entire table becomes more and more expensive and redundant, in which case the most straightforward solution is to switch to an `incremental` materialization.

<br>

```sql
{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='user_id'
)}}

select
    user_id,
    count(order_id) as order_count,
    max(timestamp) as last_order_ts
from orders
{%- if is_incremental() %}
where order_ts > ( select max(last_order_ts) from {{this}} )
{%- endif %}
group by user_id
order by user_id
```

<br>

This approach would work well for the `last_order_ts` field but... how about the `order_count` field?

It's clear the `MERGE INTO` statement needs to add the existing value of `order_count` with the one from the incoming chunk, otherwise the field will be overwritten solely with the `order_count` from the incoming chunk, which won't reflect reality.

To tackle these use cases, I propose adding an extra config option `merge_update_expressions` that applies only to incremental models with the `merge` strategy:

```sql
{{ config(
    materialized='incremental',
    incremental_strategy='merge',
    unique_key='user_id',
    merge_update_expressions={
        'order_count': 'DBT_INTERNAL_DEST.order_count + DBT_INTERNAL_SOURCE.order_count'
    }
)}}

select
    user_id,
    count(order_id) as order_count,
    max(timestamp) as last_order_ts
from orders
{%- if is_incremental() %}
where order_ts > ( select max(last_order_ts) from {{this}} )
{%- endif %}
group by user_id
order by user_id
```

<br>

I concede referring to `DBT_INTERNAL_DEST` and `DBT_INTERNAL_SOURCE` directly might not be the most elegant syntax. Nonetheless, it would be consistent with the [incremental_predicates](https://docs.getdbt.com/docs/build/incremental-models#about-incremental_predicates) option where these internal variables are referred to as well.

### Are you interested in contributing this feature?

Yes

### Anything else?

Tangentially related to this, I've noticed https://github.com/dbt-labs/dbt-core/issues/9223
The latter seems to be more focused on the predicates/matching rather that the update expressions themselves, but both would be complementary

**Comment by monti-python** [comment]
I've created a draft PR to illustrate it: #9313

**Comment by florian-petersen** [comment]
Hi @monti-python, We have the same issue to update the columns with previous incremental values. We use some incremental logic in our models, but I see the benefit of shortening the code using the merge macro. I suggest to move DBT_INTERNAL_SOURCE and DBT_INTERNAL_DEST in the merge macro and write only the expression in the config dict. You then need a loop over the items.

**Comment by dbeatty10** [comment]
@monti-python Thanks for a nice write-up and opening a PR!

Rather than make changes to the built-in `merge` strategy, we think that the [custom incremental strategies](https://docs.getdbt.com/docs/build/incremental-models#custom-strategies) feature gives what you need to make customizations like this. So I'm going to close this issue and the associated PR as "not planned".

### Example using custom incremental strategies

If you are creating multiple custom strategies and want to be [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), then you can take a look at https://github.com/dbt-labs/dbt-core/issues/9223#issuecomment-1879865190.

See steps below for an easy (but less DRY) way for you to use this feature.

1. Copy-paste the `get_merge_sql` macro from your PR [here](https://github.com/dbt-labs/dbt-core/pull/9313/files) into your `macros` directory
1. Rename the macro to a different name (e.g .`customized_get_merge_sql`)
1. Create a `get_incremental_STRATEGY_sql` macro that calls your custom macro (e.g .`get_incremental_merge_update_expressions_sql`)


```sql
{% macro get_incremental_merge_update_expressions_sql(arg_dict) %}

  {% do return(customized_get_merge_sql(arg_dict["target_relation"], arg_dict["temp_relation"], arg_dict["unique_key"], arg_dict["dest_columns"], arg_dict["incremental_predicates"])) %}

{% endmacro %}
```

### Usage

Then you can use it like this:

```
{{ config(
    materialized="incremental",
    incremental_strategy="merge_update_expressions",
    unique_key="user_id",
    merge_update_expressions={
        'order_count': 'DBT_INTERNAL_DEST.order_count + DBT_INTERNAL_SOURCE.order_count'
    },
) }}
...
```

**Comment by monti-python** [comment]
Thanks a lot for taking the time to look into this @dbeatty10!

Looking forward to the outcome of #9223 👍
