### ISSUE TITLE
[CT-3516] [Feature] Add support for source table versions to source() function

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [dbt-labs/dbt-core#9321]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Add version parameters to the `source` function so that source tables can be versioned in a manner similar to model versions.

Example:
```
select * from {{ source('my_source', 'my_table', table_version=3) }}
```
This would read from a source table named `my_table_v3`, which would be defined in YAML in a versioned way similar to model versions.  This would be useful if tables within a single dataset are individually versioned.

Alternatively/additionally, entire sources could be versioned:
```
select * from {{ source('my_source', 'my_table', source_version=2) }}
```
This would read `my_table` from a source named `my_source_v2`.  This would be useful if the entire dataset/schema is versioned, and all tables within it are part of the same version.

References:
- ref function: see discussion about "Versioned refs": https://docs.getdbt.com/reference/dbt-jinja-functions/ref
- source function: no mention about source versioning being possible: https://docs.getdbt.com/reference/dbt-jinja-functions/source

### Describe alternatives you've considered

The existing model versioning functionality seems to be mostly syntactic sugar and not necessary to make up a versioning scheme.  In a similar fashion, source versioning can be handled manually using existing functionality.  For example:

```
select * from {{ source('my_source', 'my_table_v3') }}
```

would read version 3 of my_table.

### Who will this benefit?

Extraction and loading pipelines may have breaking changes in functionality / behavior that requires gradual migration of the transformations managed by dbt.  This is a similar rationale for why model versions exist: by versioning models it gives model owners the flexibility to make breaking changes while downstream models can still reference old versions during the migration.

As an example, consider the following pipeline, which writes data to a BigQuery table in near-real-time:

> Online PostgreSQL OLTP database --> write-ahead log --> Kafka Connect: Debezium connector (CDC) --> Kafka --> Kafka Connect: BigQuery sink --> BigQuery table

The Debezium connector take a snapshot of the underlying PG table(s), and then follows the write-ahead log.  The records are ultimately written to a BigQuery table.  The dbt project references the BigQuery table as a "source".

Now, suppose that a breaking change is going to be made to this pipeline.  For example, the Debezium configuration is changed so that PostgreSQL INTERVAL types are mapped to strings instead of floating points.  This leads to a change in the data types of the BigQuery table columns - clearly a breaking change.  Thus, in order to make this change, we would need to create a second copy of this entire pipeline ("version 2"), and then migrate all the users (i.e. transforms in dbt) of the BigQuery table to use the new version.

Step by step, here's how such a migration might look:
1.  Create new Kafka topic for "version 2" for an individual table, e.g. topic named `cdc.postgres.v2.mydb.myschema.mytable`
2.  Create new Debezium connector with the desired changes to configuration.  Write the output to the new "version 2" Kafka topic.
3.  Create new BigQuery connector that writes "version 2" Kafka topic to a "version 2" BigQuery table: `gcp-project.mydb.mytable_v2`
4.  Create new versioned source in dbt for `mydb.mytable_v2` BigQuery table.
5.  Update existing `source` function calls in dbt to reference version 2 instead of version 1.
6.  Delete old versioned source in dbt for version 1 of mytable.
7.  The old Debezium --> BigQuery pipeline for version 1 can be cleaned up.

This is but one example to hopefully make the usefulness more clear.  It's likely that other very different-looking extract/load tasks used by other users might also have breaking changes made to them.

### Are you interested in contributing this feature?

Potentially, but not immediately

**Comment by dbeatty10** [comment]
Thanks for reaching out @james-johnston-thumbtack !

The alternative you mentioned is the way to go here since it is already fully available in dbt today.

Referencing can look a couple different ways depending on how you [define your sources](https://docs.getdbt.com/docs/build/sources#declaring-a-source).

### Option 1

Same schema, but different table names.

`models/_sources.yml`

```yaml
version: 2

sources:
  - name: my_source
    tables:
      - name: my_table_v2
      - name: my_table_v3
```

Reference the source within a model:
```yaml
select * from {{ source('my_source', 'my_table_v3') }}
```

### Option 2

Same table names, but different schemas.

`models/_sources.yml`

```yaml
version: 2

sources:
  - name: my_source_v2
    tables:
      - name: my_table
  - name: my_source_v3
    tables:
      - name: my_table
```

Reference the source within a model:

```yaml
select * from {{ source('my_source_v3', 'my_table') }}
```

### Summary

If you really want to, you can always create a custom override of the `source` macro as well.

Since we already enable all the pieces you need for versioning sources, I'm going to close this as "not planned".

**Comment by james-johnston-thumbtack** [comment]
@dbeatty10 thank you for the detailed follow-up!

> If you really want to, you can always create a custom override of the source macro as well.

This is what I wound up doing anyway in the meantime... what seemed at the time like a hacky way to do it, but now maybe the best (???) long-term solution:

```
@@ -0,0 +1,23 @@
{# source_table_version

This macro is used to generate a source table name with a version suffix, in a manner similar to
what the ref() function does.  It could be removed if the proposal at
https://github.com/dbt-labs/dbt-core/issues/9321 is implemented.

Unlike the ref() function, the implementation here is very simple.  It works as follows:

 - Define your sources in YAML as normal, except add a "_v<version>" suffix to the table name.
   This is similar to how you would name a model version.
 - Pass in an integer to the macro to specify the version number.
 - The macro has no concept of the latest version.  A version number must always be provided.

Usage:
    {{ source_table_version('source_name', 'table_name', 1) }}

Output:
    The Relation object returned by {{ source('source_name', 'table_name_v1') }}
#}

{%- macro source_table_version(source_name, table_name, table_version) -%}
    {{- return(source(source_name, '{}_v{}'.format(table_name, table_version | int))) -}}
{%- endmacro -%}
```

Usage:
```
tt_utils.source_table_version('cdc_pg_featureflags', 'ffl_feature_flags', 1)
```

> The alternative you mentioned is the way to go here since it is already fully available in dbt today.

One of the concerns I have with the proposed options is that there could be inconsistency in naming.  One person's `my_table_v1` is another person's `my_table_3` or `my_table_v004` or .... you get the idea.  Demanding integers up-front brings consistency.  Solving that problem seems to me like one of the primary benefits of the existing model versioning feature?

**Comment by dbeatty10** [comment]
Thanks for sharing your definition for your custom `source` macro @james-johnston-thumbtack 🏆

> Solving that problem seems to me like one of the primary benefits of the existing model versioning feature?

Although we recommend sticking with whole numbers (`1`, `2`, `3`, ...) for model versioning, the version really [can be _any_ string](https://docs.getdbt.com/reference/resource-properties/versions#v) (`a`, `b`, `c`, `blue`, `yellow`, `green`, ...).
