### ISSUE TITLE
[CT-3518] [Bug] Retry should not print out warning when state path is not specified

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9327]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We decided to add a warning when `--state path` == `--target-path` https://github.com/dbt-labs/dbt-core/issues/8160 

This would cause dbt core raise a warning in retry when dbt tries to load the previous state. But actually dbt do not need to load all previous state in this case and should not raise such warning

### Expected Behavior

We should only load the previous run results, and not print out a warning.

### Steps To Reproduce

...

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by ChenyuLInx** [comment]
@graciegoheen after looking at the code closely, I realized my previous description was wrong. Retry would still function in that case but would just always print out an irrelevant warning and load stuff that it do not need.
I updated the issue to make sure it is correct. Hope you don't mind.

**Comment by ChenyuLInx** [comment]
Taking off sev 1 as it is only false alarm warning.
