### ISSUE TITLE
[CT-3524] Remove usage of dbt.adapters.factory in dbt/common

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#9334]

**Comment by christopherekfeldt** [comment]
When trying out:
dbt-core v1.8.0b1
dbt-bigquery v1.8.0b1
or
dbt-core v1.8.0b2
dbt-bigquery v1.8.0b2 

when i try to run a dbt command after installation in poetry I get this:
![image](https://github.com/dbt-labs/dbt-core/assets/17338299/abef37c7-584c-4576-b1ca-e3c4b6f54459)

Have I missed something, or is it a bug?

**Comment by graciegoheen** [comment]
Hi @christopherekfeldt can you share how you're installing dbt? Are you using `pip install`?

**Comment by QMalcolm** [comment]
@christopherekfeldt  If you could share your steps to installing dbt that'd be much appreciated. I tried to reproduce this with poetry (as it appears that is what you are using to install dependencies) but haven't been able to get it to error out

My steps for attempting to reproduce are as follows and was done in a clone of [jaffle_shop](https://github.com/dbt-labs/jaffle_shop)
```bash
$ python -m venv venv
$ source venv/bin/activate
$ pip install poetry
...lots of install logs...

$ deactivate && source venv/bin/activate    # re-sourcing my terminal instance to recognize the fresh poetry binary
$ poetry init
...initialization logs...

$ code .     # added `dbt-bigquery = "^1.8.0b2"` to my dependencies in `pyproject.toml`
$ poetry install
...more install logs...

$ deactivate && source venv/bin/activate    # re-sourcing my terminal instance to recognize the fresh dbt binary
$ dbt parse
...runs without error...

$ pip freeze | grep dbt
dbt-adapters==1.0.0
dbt-bigquery==1.8.0b2
dbt-common==1.0.0
dbt-core==1.8.0b2
dbt-extractor==0.5.1
dbt-semantic-interfaces==0.5.1
```

**Comment by christopherekfeldt** [comment]
We are using poetry, so we change the versions in pyproject.toml

our setup:

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
dbt-bigquery = "v1.8.0b2"
dbt-core = "v1.8.0b2"
sqlfluff = "3.0.1"
pre-commit = "3.6.2"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

then use cli commands:

poetry lock --no-update
poetry install --no-root

then I ran:

dbt --version

which evaluates to -> ModuleNotFoundError: No module named 'dbt.adapters.factory'
Can it have anything to do with us using python 3.12?

**Comment by christopherekfeldt** [comment]
Screenshot:

![image](https://github.com/dbt-labs/dbt-core/assets/17338299/b76a0eb9-cdf0-446c-8cba-7f614afee887)

**Comment by Arnellluke** [comment]
I have the same version of dbt packages
![image](https://github.com/dbt-labs/dbt-core/assets/33959400/3bfcc893-18b7-4a57-a557-c46867b4aa13)

and receive the same error:
![image](https://github.com/dbt-labs/dbt-core/assets/33959400/5f3e3f5f-3da7-44a3-a2c1-a0a471bb7ef7)

**Comment by Arnellluke** [comment]
To my above comment, I found that uninstalling all 6 of the dbt packages manually and reinstalling the core & adapter beta versions has worked. 
To note, the resultant versions of adapters, common, extractor, semantic-interfaces were still the same versions in fresh & upgraded install cases.

**Comment by benedikt-buchert** [comment]
Was able to fix this via:

`pip uninstall dbt-adapters
pip install dbt-adapters==1.1.1`

**Comment by brabster** [comment]
I also got caught out by this - pip --upgrade left me broken, clean and reinstall venv sorted it. Details https://tempered.works/posts/2024/05/12/dbt-18-breaks-on-update/
