### ISSUE TITLE
[CT-3537] [Feature] Provide surrounding tasks for `state:modified`

### ISSUE THREAD

**Issue by aBBDnGus** [dbt-labs/dbt-core#9356]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

On my productive system, I want to build only models that have changed since the last release. For this, I execute `dbt run -m state:modified --state artifacts`. For using this feature, I would like to have two features provided by dbt:
1. Work without existing `manifest.json` in the initial run: In the initial run, there is no old `manifest.json` to compare with. If this does not exist, dbt should build all models by default instead of throwing an error.
2. Copy current `manifest.json` after each run: After each run, the current `manifest.json` should be copied to the specified directory. Then, this can be used for the next release.

Currently, both steps have to be done manually or by a different script. It would be nice, if both steps can be (at least via an option) performed with dbt.

### Describe alternatives you've considered

Instead of `dbt run -m state:modified --state artifacts`, I execute a Python file like this:
```
if pathlib.Path('artifacts').is_dir():
    subprocess.run('dbt run -m state:modified --state artifacts')
else:
    subprocess.run('dbt run')
shutil.copy(pathlib.Path('target') / 'manifest.json', pathlib.Path('artifacts') / 'manifest.json')
```

### Who will this benefit?

Highly automated productive dbt systems

**Comment by dbeatty10** [comment]
Thanks for opening this @aBBDnGus !

> 2. Copy current `manifest.json` after each run: After each run, the current `manifest.json` should be copied to the specified directory. Then, this can be used for the next release.

After discussing with @graciegoheen, we're considering state management out of scope for dbt-core, so I'm going to close this as "not planned".

Could you open a separate feature request for this part so we can consider it further?

> 1. Work without existing `manifest.json` in the initial run: In the initial run, there is no old `manifest.json` to compare with. If this does not exist, dbt should build all models by default instead of throwing an error.

**Comment by aBBDnGus** [comment]
Thanks for the answer! I openend https://github.com/dbt-labs/dbt-core/issues/9403#issue-2087616918 for this.
