### ISSUE TITLE
[CT-3547] [Bug] setting source schema to empty string in sources.yaml has no effect on manifest.json

### ISSUE THREAD

**Issue by pulsar256** [dbt-labs/dbt-core#9375]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When setting the `schema` property of a source in `sources.yaml` to an empty string dbt will still use the source name as schema name instead of empty string for generating `manifest.json`

Given:

```yaml
version: 2
sources:
  - name: ingestion
    database: "test"
    schema: ""
```

will render `manifest.json` as:

```json
{
 (...)
 "sources": [
  "database": "test",
  "schema": "ingestion"
 ]
}
```

This is relevant as tools such as Datahub will parse the information from `manifest.json` and construct identifiers for resources in the lineage. Databases such as Clickhouse do not have/use the schema-concept and in this case Datahub won't be able to correlate the lineage correctly. Manually editing the `manifest.json` and setting the schema property to an empty string yields the correct behaviour in that regards.

### Expected Behavior

manifest.json is rendered as:

```json
{
 (...)
 "sources": [
  "database": "test",
  "schema": ""
 ]
}
```

### Steps To Reproduce

- set schema to an empty string for any source in `sources.yaml`
- run `dbt compile`
- check `target/manifest.json` still contains the schema derived from source name.

### Environment

```markdown
- OS: Linux
- Python: 3.11.6
- dbt: 1.7.4
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Used database: clickhouse / clickhouse-dbt integration

**Comment by dbeatty10** [comment]
@pulsar256 based on the docs [here](https://docs.getdbt.com/docs/core/connect-data-platform/clickhouse-setup), it looks like `dbt-clickhouse` uses `schema` rather then `database`.

So what if you do this instead?

```yaml
version: 2
sources:
  - name: ingestion
    database: ""
    schema: "test"
```

**Comment by dbeatty10** [comment]
@genzgd is the workaround [here](https://github.com/ClickHouse/dbt-clickhouse/blob/ca9da0b6ebacc14d67139b0b417e0d4083b68a9c/dbt/adapters/clickhouse/relation.py#L85-L89) related to what is reported within this issue?

**Comment by genzgd** [comment]
It's probably related, yes.  We definitely use `schema` as the clickhouse database in most contexts and normally expect `database` to be an empty string.

**Comment by pulsar256** [comment]
> @pulsar256 based on the docs [here](https://docs.getdbt.com/docs/core/connect-data-platform/clickhouse-setup), it looks like `dbt-clickhouse` uses `schema` rather then `database`.
> 
> So what if you do this instead?
> 
> ```yaml
> version: 2
> sources:
>   - name: ingestion
>     database: ""
>     schema: "test"
> ```

This solves the Datahub ingestion issue we were facing. Thank you!

From the documentation and principle of least astonishment perspective, I would not have expected that one creates a database in ClickHouse and later refers to it in configurations usually as database (connection strings, grants) and sometimes as schema.

**Comment by dbeatty10** [comment]
> This solves the Datahub ingestion issue we were facing. Thank you!

Awesome @pulsar256 !

In agreement with @genzgd's request, I'm going to close this in favor of open an issue in `dbt-clickhouse` regarding the schema/database distinction.
