### ISSUE TITLE
[CT-3566] [Feature] Execute `state:modified` in the initial run without existing `manifest.json`

### ISSUE THREAD

**Issue by aBBDnGus** [dbt-labs/dbt-core#9403]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

On my productive system, I want to build only models that have changed since the last release. For this, I execute `dbt run -m state:modified --state artifacts`. In the initial run, the `manifest.json` does not exist. In this case, dbt should build all models instead of throwing an error.

### Describe alternatives you've considered

Instead of `dbt run -m state:modified --state artifacts`, I execute a Python file like this:
```
if pathlib.Path('artifacts').is_dir():
    subprocess.run('dbt run -m state:modified --state artifacts')
else:
    subprocess.run('dbt run')
```

### Who will this benefit?

Highly automated productive dbt systems

**Comment by aBBDnGus** [comment]
https://github.com/dbt-labs/dbt-core/issues/9356#issuecomment-1896410520

**Comment by dbeatty10** [comment]
Thanks for opening this @aBBDnGus !

I can see why you'd want to dbt to build all your "modified" models even if it's the initial run and `artifacts/manifest.json` doesn't exist. It's got some similarities with running an incremental model or doing a dbt snapshot for the first time.

But this isn't something we're keen to adopt at this time.

Rather, we'd recommend using an alternative approach similar to what you are doing currently. You could also do something similar without python in `bash`, put it within a [`justfile`](https://github.com/casey/just?tab=readme-ov-file#just), etc.

Here's an example of a Python script that handles the case where the `artifacts` directory exists, but is missing the `manifest.json` file for some reason:

```python
from pathlib import Path
import subprocess

state_path = "artifacts"
file_path = Path(state_path) / "manifest.json"
command = f"dbt run --select state:modified --state {state_path}"

if not file_path.is_file():
    command = "dbt run"

print(command)
subprocess.run(command, shell=True, check=True)
```

**Comment by antonysouthworth-halter** [comment]
I am finding myself wanting the same behaviour. In my case we are using selectors.yml, it looks something like this:

```yaml
selectors:
  - name: deploy
    definition:
      intersection:
        - method: state
          value: modified
        - '+tag:my-tag=my-value
```

But this fails to run because I don't have the state yet. What's the recommended way to make this work?

By the way, this feels like a bit of an oversight in the design of the state management feature? How do you expect users to provide the initial state file?
