### ISSUE TITLE
[Feature] Option to override the default value of on_schema_change from dbt_project config

### ISSUE THREAD

**Issue by case-k-git** [dbt-labs/dbt-core#9449]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently on_schema_change default value is `ignore` . but we would like to make `on_schema_change='fail'` as a default value. So if we can override the default value of on_schema_change from dbt_project.yaml it will be convenient.
https://docs.getdbt.com/community/resources/oss-expectations

### Who will this benefit?

Currently on_schema_change default value is `ignore` so can not notice even if new coulum is missing. To solve this we have to add  `on_schema_change='fail'` for every columns. It will not convenient and avoid it.So want to set `on_schema_change` default value from dbt project config to apply entire model easily.

https://docs.getdbt.com/reference/dbt_project.yml

### Are you interested in contributing this feature?

Yes

### Anything else?
if  already have such a option please let me know it. I want to use it to avoid defining every SQL model.

**Comment by dbeatty10** [comment]
Thanks for reaching out @case-k-git !

Did you already try something like [this](https://docs.getdbt.com/docs/build/incremental-models#what-if-the-columns-of-my-incremental-model-change) within `dbt_project.yml`?

```
models:
  YOUR_DBT_PROJECT_NAME_HERE:
    +on_schema_change: "fail"
```

**Comment by case-k-git** [comment]
@dbeatty10  Thank you for your reply I did not notice. Let me try this thank you

**Comment by case-k-git** [comment]
It worked Thank you!
