### ISSUE TITLE
[Bug] Incorrect Vertica datatype parsing

### ISSUE THREAD

**Issue by igor-kramer** [dbt-labs/dbt-core#9462]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We have fields in Vertica with datatypes `interval hour to second`, `interval day to second`. In generated dbt docs we see datatypes `interval hour`, `interval day`

### Expected Behavior

Correct datatypes in generated docs

### Steps To Reproduce

Create model
```
{{
    config(
        materialized='view'
    )
}}
select cast('25 sec' as INTERVAL hour TO SECOND(6)) as duration;
```
Run `dbt docs generate`, `dbt docs serve`

### Environment

```markdown
- OS: Mac 14.2.1
- Python: 3.9
- dbt: 1.6.3
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @igor-kramer !

This looks like it is behavior that is specific to the dbt-vertica adapter (rather than dbt-core), so I'm going to close this in favor of you opening an issue within dbt-vertica instead:

https://github.com/vertica/dbt-vertica/issues
