### ISSUE TITLE
[Bug] Unable to use macros in schema.yml pre/post-hook

### ISSUE THREAD

**Issue by jtmcn** [dbt-labs/dbt-core#9482]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When a macro is added to a pre-hook or post in a model config block in yaml, it results in a Compilation Error.

### Expected Behavior

The macro should not be rendered when the yaml is parsed, causing an error. It should be rendered at run time.

### Steps To Reproduce

1) Create and define `some_macro.sql`
2) Add to model config:
```
- name: model_name
  config:
    +pre-hook: "{{ some_macro() }}"
```
3) `dbt compile` 

### Relevant log output

```shell
Compilation Error
  Could not render {{ some_macro() }}: 'some_macro' is undefined
```

### Environment

```markdown
- OS: macOS
- Python: 3.10.13
- dbt: 1.7.6
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Previously existing, but closed bug [7128](https://github.com/dbt-labs/dbt-core/issues/7128)

In a potentially related bug [6425](https://github.com/dbt-labs/dbt-core/issues/6411) @jtcohen6 refers to `renderer.py` where the `should_render_keypath` function was looking for `post-hook` rather than `post_hook`. I see that both are now accepted in the `late_rendered_hooks`. However, in my debugging it looks like the keypath is empty and thus returns True before reaching that `if` statement

**Comment by dbeatty10** [comment]
Thanks for doing that research and raising this issue @jtmcn !

#6411 looks like something different to me. But #7128 looks like _exactly_ the same thing, so I'm going close this issue in favor of re-opening it.

In the meantime, here's something that _should_ work for you -- add your pre hook to your model's `config` block instead:

```
{{ config(
    pre_hook="{{ some_macro() }}"
) }}

...
```

Let me know if that doesn't work for some reason!
