### ISSUE TITLE
Seed array type

### ISSUE THREAD

**Issue by yonatan-cohen8186** [dbt-labs/dbt-core#9497]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I'm trying to seed a csv file that contains an array field, but the dbt run doesn't seem to support it

### Describe alternatives you've considered

I've considered solving this by adding a post-hook to the seed

### Who will this benefit?

Anyone who wants to seed array fields

**Comment by dbeatty10** [comment]
Thanks for reaching out @yonatan-cohen8186 !

We don't plan to being able to seed arrays, json, or variants within CSV files, so I'm going to close this issue as "not planned".

https://github.com/dbt-labs/dbt-core/issues/2365 includes some workarounds that you could take a look at in the meantime.

If you need this capability for doing testing, then it would be covered by https://github.com/dbt-labs/dbt-core/issues/8423
