### ISSUE TITLE
[Feature] Support Prioritization of data-test's Execution Order

### ISSUE THREAD

**Issue by trouze** [dbt-labs/dbt-core#9530]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In dbt-core today, data-tests seem to be sorted alphabetically at the model level. Meaning, for a single model, if I have `not_null` and `unique` data-tests on my primary key column, and another model level test (e.g. custom test across multiple columns), the data-tests are *started* in alphabetical order.

What I'd like to be able to do is define the order in which tests for a model are started. I think the implementation of this could model after how the hierarchy works in dbt for other model configs. Being able to set a global priority in the `dbt_project.yml`, but then being able to override that in a `schema.yml` file for a specific model would be great. That being said, I think the minimalist solution here is to simply have data-tests execute in the order by which they're defined in the model yaml.

### Describe alternatives you've considered

Of course, we could just name our tests to have them execute in a desired order, but this is a global solution. Meaning, on one model I may want `unique` data-test to run before `not_null` whereas on another I don't. By overriding and renaming this test to be something like `1_unique` and `2_not_null`, I can set this order globally, but have no control at a more granular level.

### Who will this benefit?

The motivating use case here is that over time, one might find (as I've seen) that it is much more likely that their uniqueness tests fail than their null tests (for example). In really large projects where a reduction of "unnecessary" data-tests can decrease the load on your DB, being able to re-order data-tests such that we run the data-tests that more commonly fail (based on analysis of our historical run results) can mean we're more likely to prevent an unnecessary run of a data-test when a later data-test is more likely to fail.

Obviously your threading has an impact here too, but my assumption is that in large DAGs you can easily find yourself executing one model's test at a time while other, unconnected models are running or being tested.

### Are you interested in contributing this feature?

I would be, with a little bit of guidance on recommended implementation of this!

**Comment by dbeatty10** [comment]
Thanks for proposing this idea @trouze !

While we want to enable configurability where we can, we also want to keep the logic as simple as possible it relates to the execution order of models, tests, etc.

So I'm going to close this as "not planned".

**Comment by trouze** [comment]
@dbeatty10 no worries here- does it make sense to document the current behavior in the [dbt docs](https://docs.getdbt.com/docs/build/data-tests) at all? Totally understand if I'm the first person to even ask about this in the first place.

**Comment by dbeatty10** [comment]
It's a good question!

Are you thinking something like the following to the [docs for tests](https://docs.getdbt.com/docs/build/data-tests)?

> dbt ensures tests execute after their models without guaranteeing a specific order. Explicit configuration of execution order is not available.

Or:

> The order in which individual tests execute may vary. dbt ensures completing upstream model dependencies first before running the data tests. Explicit configuration of execution order is not available.
