### ISSUE TITLE
Saved queries should always include relation spec (`database.schema.alias`), and respect `generate_x_name` macros

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#9534]
### We should:
- always include `NodeRelation` objects for each export (including `database`, `schema_name`, `alias`)
- resolve the `database` / `schema_name` / `alias` with respect to `generate_x_name` macros (possibly by calling [this method](https://github.com/dbt-labs/dbt-core/blob/15dcb9a19d7549dbb5c4dbf250f6d915578cbfe9/core/dbt/parser/base.py#L285))

### Testing Considerations:

Will need a migration from previously saved manifests. 
Needs to be non-breaking change to artifacts.

### Considerations:
May not be able to backport these.

### Discussion Summarization:
* Might need to refactor `generate_x_name` functions to be usable outside of initial parsing
* Might not be able to _migrate_ existing manifests, i.e. they won't get regenerated until reparsed

**Comment by martynydbt** [comment]
Proposal that this is not required for 1.8

**Comment by aranke** [comment]
Update from estimation discussion:
1. We can potentially avoid modifying artifacts by only adding the `NodeRelation` object to the export internal object that is not written to disk.
2. Investigate whether this approach will satisfy A/C of resolving the `database` / `schema_name` / `alias` regarding `generate_x_name` macros.
