### ISSUE TITLE
[Bug] semantic models always included as part of state:modified

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#9548]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently, dbt always detects that semantic models have changed during state:modified, even if none of their model, description, defaults, entities, dimensions, measures, configs, primary entities, or groups have changed. 

### Expected Behavior

dbt only includes semantic models if one of the above listed properties has changed. 

### Steps To Reproduce

`dbt ls --select "state:modified"` on a project with unchanged semantic models

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by gshank** [comment]
I wasn't able to recreate this. Could you give me a brief reproduction test case?

**Comment by MichelleArk** [comment]
I think it was already resolved by the combination of https://github.com/dbt-labs/dbt-core/pull/9549 and https://github.com/dbt-labs/dbt-core/pull/9561
