### ISSUE TITLE
[macro] [false positives] environment-aware logic in config should not cause resources to Always selected by state:modified

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9564]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Many folks want to have logic in their dbt project that purposely differs by environment.

For example, let's say I want to materialize a model as a view in dev but as a table in prod.

To accomplish this, I use a macro in my config block:
```
{{
    config(
        materialized = set_materialized_config()
    )
}}
```
with the following macro:
```
{% macro set_materialized_config() %}
  {% if target.name == 'prod' %}
    {% set mat = 'table' %}
  {% else %}
    {% set mat = 'view' %}
  {% endif %}
  
  {{ return(mat) }}
{% endmacro %}
```

When selecting `--select state:modified` and comparing my `dev` environment to a manifest from `prod`, this model will ALWAYS be marked as modified. This is because, the materialized config appears different - in `prod` it's `table`, in `dev` it's `view`.

Instead, if I've changed nothing about this model OR macro, it shouldn't be marked as modified because the macro logic hasn't changed.

If I've changed the model OR the macro, it _should_ be marked as modified.

### Describe alternatives you've considered

A current work-around is to pull the raw jinja out of my macro and put all environment-based logic directly into my `dbt_project.yml` file (can't set configs to output of macros in `dbt_project.yml`).

If instead, I were to configure this model as so:
```
models:
  <path_to_my_model>:
    +materialized: "{{ 'table' if target.name == 'prod' else 'view' }}"
```
it would NOT be picked up when selecting `--select state:modified`.

But this is cumbersome (reduces DRY code), unexpected, and can lead to an unnecessarily massive `dbt_project.yml` file.

### Who will this benefit?

Anyone who wants to use `state:modified` and has environment-based logic in their dbt project.

See internal use case:
- [dynamically set my snowflake warehouse based on my environment](https://github.com/dbt-labs/internal-analytics/blob/666f16b999a85e8f10aa2184e17bd4c00a815ee3/macros/operations/set_warehouse_config.sql#L1)
- [slack thread](https://dbt-labs.slack.com/archives/C017GDLAF7D/p1707775240258699?thread_ts=1707770312.911859&cid=C017GDLAF7D)

### Anything else?

Potential solution https://github.com/dbt-labs/dbt-core/discussions/6170#discussioncomment-3993081

This is relevant for all resources that can be configured, not just models.

**Comment by jtcohen6** [comment]
Some historical context on why we've said that this is hard, at least in the past:
- https://github.com/dbt-labs/dbt-core/issues/3680
- https://github.com/dbt-labs/dbt-core/issues/2714

**Comment by graciegoheen** [comment]
Related to https://github.com/dbt-labs/dbt-core/issues/3277

**Comment by sasawatc** [comment]
Got a similar use case to @graciegoheen mentioned [dynamically set my snowflake warehouse based on my environment](https://github.com/dbt-labs/internal-analytics/blob/666f16b999a85e8f10aa2184e17bd4c00a815ee3/macros/operations/set_warehouse_config.sql#L1) (assuming from the title as I don't have access). Personally, having a way to specify all of the model-specific config override at the .sql file itself makes it intuitive on the override settings of that particular model.

**Comment by marius-sb1** [comment]
> If we do go down that route, we might want a different UX — [a "snippet"](https://github.com/dbt-labs/dbt-core/discussions/6170)? a ["pure macro"](https://github.com/dbt-labs/dbt-core/discussions/6280)? — to make clear that these macros can only be static input-output machines. They can reference vars + env vars + `target` values, but they _cannot_ make introspective queries against the data warehouse. This category already includes the "special" `generate_x_name` macros (for database/schema/alias), which dbt fully resolves at parse time instead of at runtime.

This might be a different issue, but it could also be related and the quoted paragraph touches on the generate_x_name-macros which definately are related to my problem. We have a set-up where we override generate_database_name to separate environments and projects into separate databases (it uses target.name from a dynamically generated profiles.yml + database/custom database).

While we have the exact same database config across our environments, it seems that only the output from get_database_name is stored in the manifest and therefore marks all our models as modified when comparing dev to prod. The use case here is slim CI.
