### ISSUE TITLE
Google protobuf 5 is incompatible

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#9566]
### Description

We specify google.protobuf: "protobuf>=4.0.0".  Google has come out with a release candidate for version 5 which is incompatible with our code because keyword parameters to MessageToJson and MessageToDict have been renamed. There may be other incompatibilities.  We need to either change our upper limit to < 5.0.0 or support google.protobuf 5 in our code.

This was seen internally because a pipeline uses `pip install --pre`.

### Acceptance Criteria

An incompatible version of google protobuf cannot be installed.

### Will backports be required?

Yes. We need to limit the protobuf version in all versions of dbt Core that use google protobuf functions.

**Comment by peterallenwebb** [comment]
dbt-common PR: https://github.com/dbt-labs/dbt-common/pull/81

**Comment by graciegoheen** [comment]
Reopening because https://github.com/dbt-labs/dbt-core/pull/9614 only did the dev-requirements.txt

**Comment by josezeta** [comment]
Thanks, this fixed some production issues we got due the proto compatiility.
