### ISSUE TITLE
[env_vars] [false positives] environment-aware logic for sources should not cause sources to always be marked as modified

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9573]
> To support this pattern with `sources` (and probably other "yaml-only" resource types), I believe we'd need to also do the work of treating `database` + `schema` + `identifier`/`alias` as configs, such that we can save their unrendered values when configs are calculated. In theory, that's happening [here](https://github.com/dbt-labs/dbt-core/blob/2411f93240a346961e6a965ad9cb5c766db275a0/core/dbt/parser/sources.py#L151-L154), but it doesn't work as I'd expect for the one actual source config we do support today, `enabled`.
> 
> Original issue for this:
> - https://github.com/dbt-labs/dbt-core/issues/2744

_Originally posted by @jtcohen6 in https://github.com/dbt-labs/dbt-core/issues/9563#issuecomment-1943635404_

I want to point to a different locations for my sources depending on the environment I am in (different database for `prod` vs. `dev`). To do so, I configure my sources as follows:
```
sources:
  - name: jaffle_shop
    database: "{{ env_var('DBT_DATABASE'}}"
    tables:
      - name: customers
``` 
But, this counts as a **modified** change everytime I do `--select state:modified` comparing two different environments. 

Instead, I tried putting this logic in `dbt_project.yml`:
```
sources:
  project:
    +database: ...
```
and that did not work, as it seems the only configuration that is available to sources in the `dbt_project.yml` is `enabled` - docs [here](https://docs.getdbt.com/reference/source-configs#general-configurations).

### Acceptance Criteria

- I want to use `env_var`s in my configuration, and the resource should not always be marked as modified

We should open a separate ticket to handle env_vars for other resources 

Relevant to https://github.com/dbt-labs/dbt-core/issues/4304

**Comment by ashleemtib** [comment]
Hi there, just curious if this is slotted for work any time soon?

**Comment by graciegoheen** [comment]
Hi @ashleemtib, yes! Currently, we're planning to tackle this work for 1.9
