### ISSUE TITLE
[Feature] Allow global config of specific tests

### ISSUE THREAD

**Issue by martanthony** [dbt-labs/dbt-core#9576]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Tests configurations can currently be defined in a few places:
1. globally, in `dbt_project.yml`
2. globally per-package, again in `dbt_project.yml`
3. within a specific test's `config()` block
4. in the yml of specific model where a specific test is implemented

3 does not feel practical for built-in tests or those from third-party packages. This leaves a gap in how tests can be configured: for example, I can globally set `severity` for all tests or all tests from a specific package, and I can set `severity` for a specific implementation of a specific test, but I can't globally set `severity` for a specific test such as `unique` or `dbt_utils.unique_combination_of_columns` independently from other built-in tests or tests within a given third-party package.

Ideally, this would be implemented in a way similar to `model` configs in `dbt_project.yml`, i.e.:
```yml
tests:
  - unique:
      +severity: error
  - accepted_values:
      +severity: warn
  dbt_utils:
    - unique_combination_of_columns:
        +severity: error
    ...
```

...however, I accept that this might not be compatible with how resource paths are declared, so there ought to be some discussion on the best way for this to be implemented.

### Describe alternatives you've considered

I've thought about doing the following, but neither is particularly palatable:
- forking the parent packages containing the tests I want to configure globally, and adding the desired configurations to the `sql` files directly: lots of refactoring, lots of maintenance overhead.
- applying the configs for a given test against every implementation of that test: lots of refactoring, lots of burden on developers to keep this consistent on an ongoing basis across a project.

### Who will this benefit?

Anyone who wants to apply configurations to specific built-in or third-party tests, without needing to apply those configurations to all current and future implementations of those tests. It will be particularly useful to those who want to set those configurations on a per-environment basis.

**Comment by jtcohen6** [comment]
Hey @martanthony! While this isn't _directly_ possible today, there's a reasonable-feeling workaround, which is to wrap the generic tests with your own overrides that implement the configs you want by default.

We had this exact issue a few years ago, and settled on this answer for now:
- https://github.com/dbt-labs/dbt-core/issues/3841

Following your example above:
```sql
-- macros/test_config_overrides.sql

{% test unique(model, column_name) %}
    {{ config(severity = "error") }}
    {{ dbt.default__test_unique(model, column_name) }}
{% endtest %}

{% test relationships(model, column_name, to, field) %}
    {{ config(severity = "warn") }}
    {{ dbt.default__test_relationships(model, column_name, to, field) }}
{% endtest %}

{% test unique_combination_of_columns(model, combination_of_columns) %}
    {{ config(severity = "error") }}
    {{ dbt_utils.unique_combination_of_columns(model, combination_of_columns) }}
{% endtest %}
```

I'm going to close this as a duplicate.

**Comment by martanthony** [comment]
Hey @jtcohen6, thanks for picking this up so quickly! Thanks for pointing out the workaround – I hadn't considered that.

I did note that there was a suggestion that this shouldn't be considered a 'long-term sustainable answer' for how to solve this problem. Given that workaround was proposed nearly 2.5 years ago, I'd be curious to understand when would be appropriate to re-raise this without the ask being regarding as a duplicate?

**Comment by jtcohen6** [comment]
@martanthony Good catch, and fair point. The mechanisms used in this workaround aren't at risk of changing anytime soon, so at this point, I wouldn't describe this as a long-term _unsustainable_ answer. Given that this hasn't posed a big problem in practice in the time since then, I don't think we're likely to prioritize a more elegant solution.
