### ISSUE TITLE
[Bug] dbt docker image are not available in GHCR

### ISSUE THREAD

**Issue by scauglog** [dbt-labs/dbt-core#9597]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The last docker image available on [github package](https://github.com/dbt-labs/dbt-core/pkgs/container/dbt-core) is dbt-core 1.7.5 but the last version available on [pypi](https://pypi.org/project/dbt-core/) is dbt-core 1.7.8

### Expected Behavior

For each release of dbt-core there should be a container available on github package. 

### Steps To Reproduce

```
docker pull ghcr.io/dbt-labs/dbt-core:1.7.8
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @scauglog 👍

I've added your report to https://github.com/dbt-labs/dbt-core/issues/7571

**Comment by scauglog** [comment]
Thank you. An image with the latest version of dbt is fine for me.
