### ISSUE TITLE
[Feature] Update urllib3 pin

### ISSUE THREAD

**Issue by cbini** [dbt-labs/dbt-core#9622]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As of `1.7.8`, the `urllib3` dependency is pinned to `~=1.0`. Looking through issues and pull requests, it looks like this was done to resolve an issue with `requests` requiring it due to an OpenSSL issue in previously released versions of `urllib3`.

`requests` currently pins `urllib3<3,>=1.21.1`, so I think it might be safe to update this constraint.

### Who will this benefit?

Users relying on other packages whose current versions use `urllib3>=2`

**Comment by dbeatty10** [comment]
Thanks for reaching out about this @cbini !

We did some refactoring in https://github.com/dbt-labs/dbt-core/pull/9368 and removed `urllib3` as an explicit dependency altogether, so I'm going to close this as resolved.

<img width="1076" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/77ef2ed7-95c3-4731-a81e-783cffd4f003"></br>

We're not planning on removing it as a dependency from dbt-core <=1.7, so the first version that will have `urllib3` removed as a dependency is v1.8.0.
