### ISSUE TITLE
[New Flaky] test_unit_test_ext_nodes

### ISSUE THREAD

**Issue by martynydbt** [dbt-labs/dbt-core#9623]
Error: `builtins.AssertionError: dbt exit state did not match expected`
First Flaked:
Feb 19, 2024, 10:28 am
1ec5e22
main
First Flaked on: https://github.com/dbt-labs/dbt-core/commit/1ec5e22e2bead70ba6503bdb8d2d371f70d9c13a

Test added here: https://github.com/dbt-labs/dbt-core/commit/eecaee1fe64f6daf7033aa4000f64d48f288c5bf

**Comment by martynydbt** [comment]
@QMalcolm and @emmyoop wondering if the 2 of you together could determine a fix for this faster than random assignment while it's more fresh?

**Comment by emmyoop** [comment]
Flaky test run: https://github.com/dbt-labs/dbt-core/actions/runs/7997092198

**Comment by emmyoop** [comment]
Everything passed in the previous run.  I ran again and it's still passing.

[Flaky Tester](https://github.com/dbt-labs/dbt-core/actions/runs/8005234305)
```
test_path: tests/functional/unit_testing/test_unit_testing.py::TestUnitTestExternalProjectNode::test_unit_test_ext_nodes
python_version: 3.9
os: ubuntu-latest
```
[Flaky Tester](https://github.com/dbt-labs/dbt-core/actions/runs/8005239505)
```
tests/functional/unit_testing/test_unit_testing.py
python_version: 3.9
os: ubuntu-latest
```

**Comment by emmyoop** [comment]
Circling back and this has still not flaked a single time since the original occurrence.  Closing as not flaky.
