### ISSUE TITLE
Rename `--include-saved-query` to `--export-saved-queries`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#9629]
See rationale in https://github.com/dbt-labs/dbt-core/issues/9237#issuecomment-1959861021

**Acceptance criteria:**
- Always include saved queries in the `build` command.
- Make them a `NO-OP` by default
    - https://github.com/dbt-labs/dbt-core/issues/9533
- Rename the flag to `--export-saved-queries`
- Rename the environment variable to `DBT_EXPORT_SAVED_QUERIES`
- Keep supporting the old names (`--include-saved-query`, CLI option + env var) for backwards compatibility

**Documentation to update:**
- https://docs.getdbt.com/docs/use-dbt-semantic-layer/exports#exports-in-production

**Comment by dbeatty10** [comment]
@jtcohen6 is there a project flag in `dbt_project.yml` for `--include-saved-query` that needs to be updated as well?

**Comment by jtcohen6** [comment]
@dbeatty10 Good ask. I don't _think_ so, since it doesn't actually change any existing functionality, unless you think the inclusion/exclusion of a saved query `NO-OP` is a `build` is a behavior change that could have real impact. Users could always exclude themselves using standard node selection, or our new proposed `--exclude-resource-type` flag.
