### ISSUE TITLE
[Feature] Graceful shutdown on KeyboardInterrupt event

### ISSUE THREAD

**Issue by gorandumic** [dbt-labs/dbt-core#9639]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Feature suggestion is about handling a graceful shutdown (using a on-run-end hook) in case of a `KeyboardInterrupt` event (e.g. Ctrl+c) or a --fail-fast run failure. 

Currently, during this event only connections are closed and dbt aborts the run, thus missing a chance to do some cleanup or logging actions as well. On the other hand, the `on-run-end` hook contains valuable information about dbt run details, such as execution status and error message(s) which is a valuable information for any custom logging solution. But if the dbt run interrupts, even if some models finish successfully the whole progress is lost, which is not a desirable action. Progress should be logged regardless of the outcome. In some cases, on-run-end hook should execute, regardless. 

So instead of a plain-old shutdown, an optional CLI flag could be set to finally execute an on-run-end hook, e.g. : `--on-interrupt-run-on-end-hook`, and depending of the overall run outcome, a user can decide what should hook do - nothing or something.

I tried to find where currently the event is captured, but I could be wrong:
![image](https://github.com/dbt-labs/dbt-core/assets/75610359/f179ac2f-7826-4866-b410-b89d210f9ee0)

### Describe alternatives you've considered

Implementing post-hooks for individual model, but it also doesn't get triggered on `KeyboardInterrupt` event.

### Who will this benefit?

Everyone that implements a custom logging of dbt runs in database.

**Comment by dbeatty10** [comment]
Thanks for opening this @gorandumic !

I think we'd like to keep things as simple as possible and keep the current behavior where dbt only closes the connections and aborts the run without attempting any other database actions.

So rather than making one last attempt of writing state to the database, we'd like dbt to terminate as expediently as possible. I realize that you're specifically targeting custom logging to the database, but as a fall-back there may be some logging in the `logs` or `target` directories that can be utilized instead.

**Comment by gorandumic** [comment]
@dbeatty10  I understand you wouldn't want to change anything but many people are requesting this feature. Because abruptly halted execution does not follow any software development standards, seems more like an unhandled exception scenario to me. You wouldn't even consider a conditional cli flag to support this feature? This way it would not be a breaking change and we could choose whether we ignore the interrupt or not.
