### ISSUE TITLE
Mypy should ignore `core_types_pb2.py`

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#9653]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

`core_types.pb2.py` is auto generated and does a bunch of meta magic. We should ignore the times from it

### Acceptance criteria

Imports of `core_types_pb2.py` ignore the types

### Suggested Tests

N/A

### Impact to Other Teams

None

### Will backports be required?

No

**Comment by martynydbt** [comment]
This was already fixed.
