### ISSUE TITLE
[Feature] Consider Boolean flag in python model dbt.config to conditionally delete Stored Procedure

### ISSUE THREAD

**Issue by noah-voltops** [dbt-labs/dbt-core#9658]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When configuring a Python model the user can pass in a Boolean value to control the deletion of the stored procedure used during the model provisioning SQL execution on the target data platform:
```
dbt.config(
        materialized='table'
        delete_procedure=False
    )
```

### Describe alternatives you've considered

None outside the configuration logic. The assumption would be that it would be set per-model based on the use case.

### Who will this benefit?

Data teams who have adopted Snowflake and Snowpark as their primary orchestration platform for scheduled jobs (or other data platforms that contain orchestration support). Instead of an external orchestrator like Airflow. Where a Snowflake Task is used to control the scheduling of the Procedure within the Snowflake compute layer.

By allowing to conditionally delete the Procedure it would allow the Snowflake Task to be version controlled and configured with a schedule targeting the stored procedure which corresponds to the `python-dbt`'s model name.

ie:
```
create or replace task process_sales_nightly
warehouse = 'small'
schedule = '1440 minute'
as
call <DBT_GENERATED_PROCEDURE_NAME>;
```

The <DBT_GENERATED_PROCEDURE_NAME> would have to resolve to the name of the procedure used in the model provisioning.

### Are you interested in contributing this feature?

Yes I'd be very happy to work on the implementation in dbt-core if it is considered.

### Anything else?

https://docs.snowflake.com/en/sql-reference/sql/create-task

https://docs.snowflake.com/en/user-guide/tasks-intro

https://www.snowflake.com/blog/snowpark-stored-procedures/

**Comment by dbeatty10** [comment]
Thanks for reaching out @noah-voltops !

Did you already try `use_anonymous_sproc`, by any chance?

```python
dbt.config(
        materialized='table',
        use_anonymous_sproc=False
    )
```

For Snowflake / Snowpark, dbt submits Python models to run as stored procedures (which some people call "sprocs" for short). By default, dbt will call a (temporary) [anonymous stored procedure](https://docs.snowflake.com/en/sql-reference/sql/call-with) containing your model's compiled Python code.

But you can create a (persistent) named stored procedure instead by disabling `use_anonymous_sproc`.

Relevant documentation is [here](https://docs.getdbt.com/docs/build/python-models#specific-data-platforms) and source code is [here](https://github.com/dbt-labs/dbt-snowflake/blob/2c0b16f73f5c56fbc5ec9c278f3716f09473c416/dbt/adapters/snowflake/impl.py#L240-L263).

**Comment by noah-voltops** [comment]
Thanks @dbeatty10 for the quick response!

I see, apologies for not linking to the correct project.. This is exactly what I was after, yes.

I tried building a model with the parameter you mentioned set to false (`use_anonymous_sproc=False`), however when I check my logs I see :
1. the non-anonymous style procedure query running ie: `CREATE OR REPLACE PROCEDURE...`; followed by
2. `drop procedure if exists ...`

I think the conditional on [line 257](https://github.com/dbt-labs/dbt-snowflake/blob/2c0b16f73f5c56fbc5ec9c278f3716f09473c416/dbt/adapters/snowflake/impl.py#L257) is my concern.

If the model configuration opts to not use an anonymous procedure, is it possible to still allow the procedure to persist without dropping it?

Maybe by using a secondary conditional to preserve the existing logic flow, or remove the following to enforce `use_anonymous_sproc=True` for the only solution for non-persistent procedures?

It's here:
```
        if not use_anonymous_sproc:
            self.execute(
                f"drop procedure if exists {proc_name}()",
                auto_begin=False,
                fetch=False,
            )
```

**Comment by dbeatty10** [comment]
> I think the conditional on [line 257](https://github.com/dbt-labs/dbt-snowflake/blob/2c0b16f73f5c56fbc5ec9c278f3716f09473c416/dbt/adapters/snowflake/impl.py#L257) is my concern.

Good eyes 👀 

After examining closer, this looks to me like something we'd consider out of scope for dbt-core. Namely, the sproc looks like an internal implementation detail for dbt-snowflake to enable dbt Python models rather than a persistent object that we'd want to support.

So I'm going to close it as "not planned".
