### ISSUE TITLE
Create unit tests for `SemanticManifest` supported by a `manifest` fixture and utility builders

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#9665]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

As part of our [Robust Testing Initiative](https://github.com/dbt-labs/dbt-core/issues/9649) we want to create generalized fixtures for our unit tests to make writing unit tests easier. To that end we want to add or update unit some unit tests to utilize the new fixture. Currently the `SemanticManifest` class is not unit tested at all, and it only requires a manifest (with some SL nodes). 

### Acceptance criteria

* There is a generic `manifest` unit test fixture
* There are builders to add `SemanticModels`, `Metrics`, and `SavedQueries` to a manifest
* There are unit tests for the `SemanticManifest`
* Reflect on test coverage of `SemanticManifest` during review

### Suggested Tests

The work is the tests

### Impact to Other Teams

None

### Will backports be required?

Narp

**Comment by ChenyuLInx** [comment]
Found lots of resusable things
https://github.com/dbt-labs/dbt-core/blame/ebc22fa26c9cb26b6deef86cc0a7ceb1ee3fb642/tests/unit/test_graph_selector_methods.py#L75
