### ISSUE TITLE
[Feature] regardless if the catalog query itself is pre-filtered or not, post-filter its results

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9666]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Originally from https://github.com/dbt-labs/dbt-core/issues/9394

If I use a selector with `dbt docs generate`, I expect only the selected nodes to be returned in the catalog.json

### Acceptance criteria

- regardless if the catalog query itself is pre-filtered or not, post-filter its results
- i.e., `dbt docs generate -s a b c tag:one_hundred_models` should only include those 103 models within `catalog.json`, even if there are 2000 models within the project.

**Comment by MichelleArk** [comment]
I ended up addressing this as part of https://github.com/dbt-labs/dbt-core/issues/9755!

Tests here: https://github.com/dbt-labs/dbt-mantle/blob/main/tests/functional/docs/test_generate.py#L156
