### ISSUE TITLE
[Feature] I want my unit tests to optionally execute pre/post hooks

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9683]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Some folks use pre/post-hooks do define DML they want to be executed on their model (`merge` statements, etc.). 

Currently, if folks unit test a model that has a pre/post-hook the hook is ignored (not executed) for the unit test.

This prevents some people from accurately testing the output of their model.

We should allow folks to optionally execute the pre/post-hooks on their unit test. The default should continue to be - we don't execute pre/post-hooks.

Likely blocked by this investigation https://github.com/dbt-labs/dbt-core/issues/8499

### Describe alternatives you've considered

Folks are unable to accurately unit test models with pre/post-hooks

**Comment by graciegoheen** [comment]
I'm going to close this out for now - but if you're interested leave a comment and we may re-open in the future!

**Comment by calleo** [comment]
Yes please! 👍

**Comment by jbsca2** [comment]
This would be really useful...

**Comment by JaredCross** [comment]
This feature would still be useful in 2026.

We create a Snowflake python UDTF that the model needs in the pre-hook. Having this functionality would let that function be created during unit testing, without having to do a dbt run on the model first.
