### ISSUE TITLE
[Feature] dbt init add package-lock.yml to .gitignore

### ISSUE THREAD

**Issue by tphillip33** [dbt-labs/dbt-core#9696]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Please add "package-lock.yml" to core/dbt/include/starter_project/.gitignore.  This file should not be checked into source control.  When creating a new project, it should be excluded.

### Who will this benefit?

All users

### Are you interested in contributing this feature?

Yes

**Comment by dbeatty10** [comment]
Thanks for reaching out @tphillip33 !

[Our recommendation](https://docs.getdbt.com/reference/commands/deps#predictable-package-installs) is to check `package-lock.yml` into version control, so we're going to leave the default `.gitignore` as-is.

**Comment by tphillip33** [comment]
@dbeatty10   I don't understand why you would check this into source control when you don't check in dbt_packages/.  The data in package-lock.yml is directly related to dbt_packages installed.  If you start clean without dbt_packages populated, what is the point of having package-lock.yml?  

In fact, I was going to suggest you move this file to dbt_packages, instead of the root.  Since it is directly related to the installed packages in dbt_packages.
