### ISSUE TITLE
[Bug] When executing the "dbt test" command, the database and schema of the source were not dynamically replaced.

### ISSUE THREAD

**Issue by analytics-jabori** [dbt-labs/dbt-core#9728]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a source named "tracking," with the database and schema switching depending on whether it's in prod or dev.
<img width="670" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/162086253/7ef3b7b0-f7fa-498a-b256-9b8114de5453">
When I run the "dbt compile" command, the result is correct.

<img width="990" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/162086253/ea9b10da-74f5-4f3d-9ef3-d8611417ec34">
But when I run the "dbt test" command, the database and schema do not switch according to the environment.

<img width="1387" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/162086253/ae0b7fd4-f819-48be-8e7b-2aba00f87e43">

### Expected Behavior

When I run dbt test, the database and schema should also switch according to the environment.

So, `superex_dev`.`tracking_dev`.`dws_tracking_app_page_viewed` is my expected behavior.

### Steps To Reproduce

1. switch dev environment or prod environment.
2. set source as 
    database: |
      {%- if  target.name == "dev" -%} {whatever}_dev
      {%- elif target.name == "prod"  -%} {whatever}_prod
      {%- else -%} invalid_database
      {%- endif -%}
3. create a model.
    select * from {this source}
4. run dbt test

### Environment

```markdown
- OS:macOs
- Python:3.12
- dbt:1.7.8
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

databricks

**Comment by dbeatty10** [comment]
Thanks for reaching out @analytics-jabori !

I tried what you described, and it seemed to work as expected for me (when using dbt-duckdb).

What happens if you execute each of these commands?

```shell
dbt test --target dev
dbt test --target prod
```

Here's what I get within `target/compiled/my_project/models/tracking/properties.yml/not_null_my_model_id.sql` after running the first command:
```sql
select id
from "superex_dev"."tracking_dev"."my_model"
where id is null
```

And here's what I see in the same file after the second command:
```sql
select id
from "superex"."tracking"."my_model"
where id is null
```

**Comment by analytics-jabori** [comment]
thanks a lot ! It worked!
I couldn't find this command in the documentation, so I didn't add the --target dev command.
<img width="775" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/162086253/dc95b554-e193-4ea4-91f6-977cec55b02a">

**Comment by dbeatty10** [comment]
That's great news @analytics-jabori !

Since it sounds like you're issue is resolved, I'm going to close out this issue. If I misinterpreted, just let me know and I can re-open it.
