### ISSUE TITLE
[Feature] better error message when running disabled model

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9747]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When you run a disabled model you get this error

```
21:53:02  Found 468 models, 5 analyses, 720 tests, 6 seeds, 2 operations, 149 sources, 0 exposures, 0 metrics, 954 macros, 0 groups, 0 semantic models
21:53:02  The selection criterion 'log__user_table' does not match any nodes
21:53:02  
21:53:02  Nothing to do. Try checking your model configs and model specification args
```

Would be better if this model read

```
21:53:02  Found 468 models, 5 analyses, 720 tests, 6 seeds, 2 operations, 149 sources, 0 exposures, 0 metrics, 954 macros, 0 groups, 0 semantic models
21:53:02  The selection criterion 'log__user_table' matches a disabled node
21:53:02  
21:53:02  Nothing to do. Try checking your model configs and model specification args
```

**Comment by dbeatty10** [comment]
Idea from @dataders -- just add the single word `enabled` to the log output:

```
21:53:02  The selection criterion 'log__user_table' does not match any enabled nodes
```

After discussing with @graciegoheen and @dataders, let's adopt this simple language.

**Comment by SamuelBFavarin** [comment]
Hi @dbeatty10, I'm looking forward to starting to contribute to `dbt-core`, and this issue looks like a good opportunity to begin. Would you mind if I open a PR updating this log message?

**Comment by dataders** [comment]
@SamuelBFavarin here's the offending line. Check out our [`contributing.md`](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) to get started!
https://github.com/dbt-labs/dbt-core/blob/ebc22fa26c9cb26b6deef86cc0a7ceb1ee3fb642/core/dbt/events/types.py#L1102
