### ISSUE TITLE
[Bug] Periodically getting macro initialization error for incremental models within ClickHouse

### ISSUE THREAD

**Issue by gurjotd23** [dbt-labs/dbt-core#9757]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently when the last dbt model in a long chain of dbt is models is running, it will sometimes produce an error that reads as so:

`Compilation Error in model dex (models/dex.sql)
19:26:52    __init__() missing 1 required positional argument: 'msg'
19:26:52    
19:26:52    > in macro materialization_incremental_clickhouse (macros/materializations/incremental.sql)
19:26:52    > called by model dex (models/dex.sql)
19:26:52  
19:26:52  Done. PASS=241 WARN=0 ERROR=1 SKIP=0 TOTAL=242`

What is weird is that those models do not use any macros explicitly, they just combine the output from several different feeder tables into one unified schema. The error comes in periodically and will often go away on its own and come back again, with little consistency.

### Expected Behavior

Since the model uses no macros, I would expect it to run without a macro error.

### Steps To Reproduce

Cannot currently reproduce because the error happens randomly on a full dbt run that takes place 144 times a day, about 20 times in a day this error tends to show up in one of two final dbt models.

### Environment

```markdown
- OS: macos-12
- Python:
- dbt: 1.4.5
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

We run on a Clickhouse database adapters.

**Comment by dbeatty10** [comment]
Thanks for reaching out @gurjotd23.

Can you check your `logs/dbt.log` file to see if there is more detail (like a Python stacktrace)?

Based on what you shared it looks like something is periodically going wrong within the [Clickhouse `incremental` materialization](https://github.com/ClickHouse/dbt-clickhouse/blob/d811e90be42c27390a1510a2434633aaaea5b85a/dbt/include/clickhouse/macros/materializations/incremental/incremental.sql) (which dbt compiles to a macro named `materialization_incremental_clickhouse`).

Depending on what you find in the logs, we may ask you to re-open this issue within [dbt-clickhouse](https://github.com/ClickHouse/dbt-clickhouse) instead.

**Comment by gurjotd23** [comment]
Hello @dbeatty10 thank you very much for responding. This might be a noob question but would you know how I can get the logs for the runs that take place on the github actions? Currently there is a logs folder and file but no logs to speak of. I can only think of maybe exporting workflow artifacts using this, but not sure it will support clickhouse: https://hub.getdbt.com/brooklyn-data/dbt_artifacts/latest/

**Comment by dbeatty10** [comment]
> would you know how I can get the logs for the runs that take place on the github actions? Currently there is a logs folder and file but no logs to speak of.

I don't know, sorry. But we'll definitely need to examine those to know how to proceed, so good luck! 🙏
