### ISSUE TITLE
[Bug] Exclude password-like fields (missing from `_connection_keys`) in partial parsing state check

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#9795]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

A change in the value of a "hidden" (password-like) field will trigger a full re-parse — but it shouldn't, because that field is not accessible in the `{{ target }}` Jinja variable, and therefore cannot be used as an input to parse-time configurations. That's the whole motivation for including profile information in the partial parse state check in the first place.

--

Instead of hashing the full contents of the active profile, we should only hash the ["connection keys"](https://github.com/dbt-labs/dbt-adapters/blob/59cb168bbb0f7b01591016ab64f3fa1f2f3716cd/dbt/adapters/contracts/connection.py#L159) of the active profile. This is equivalent to what the user sees in the output of `dbt debug`, and what they can access in the `{{ target }}` Jinja variable.

So instead of:

https://github.com/dbt-labs/dbt-core/blob/c6c0c79216a3c8032d5ea5ed608ca2ef7bdacc9a/core/dbt/parser/manifest.py#L991-L994

A simple solution would be something like:
```python
connection_keys = config.credentials._connection_keys()
profile_hash = FileHash.from_contents(pprint.pformat(connection_keys))
```

**However**, I think this would _undo_ a workaround that's existing for a long time to avoid full re-parses for _non-credential_ values by setting them to a "secret" env var. This behavior isn't yet documented, but that's more our oversight than an intentional choice to leave it undocumented:
- https://github.com/dbt-labs/docs.getdbt.com/issues/1066

### Expected Behavior

**Acceptance criteria:**

1. A change to the `password` profile field (or similar) should not trigger a full re-parse
2. Users should retan the ability to "opt" out additional fields by setting them to "secret" env vars, the values of which dbt does not track 

### Steps To Reproduce

1. Create a profile that has a `password` field and another field set to `{{ env_var('DBT_SECRET_MYSECRET') }}`
1. Full parse (`dbt parse`)
2. Change password field
3. Rerun `dbt parse`, this is a full parse but it shouldn't be
4. Change value of `DBT_SECRET_MYSECRET`
5. This should not be a full reparse

### Environment

```markdown
- OS: macOS 14.3
- Python: 3.10.11
- dbt: 1.7.10
```

### Additional Context

[internal thread](https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1711046660026059)

**Comment by graciegoheen** [comment]
@jtcohen6 What does this mean "However, I think this would undo the longtime . "?

**Comment by ChenyuLInx** [comment]
Check the corresponding snowflake issue

**Comment by will-sargent-dbtlabs** [comment]
@ChenyuLInx For single tenants on 1.7 and 1.8, do you think the updated image is available now and will deploy during next weeks release? Is this live in MT on 1.8?
