### ISSUE TITLE
[Bug] Issue with table with capital letters (postgres)

### ISSUE THREAD

**Issue by qmoret** [dbt-labs/dbt-core#9818]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm trying to add a source table which has a name with capital letters. When running dbt after adding the source config, I get the following error :
```
 Snapshot (...) depends on a source named 'airtable_airbyte.transport_dossiers_tblxtZqELdrIqdcUq' which was not found
```
I believe this is because postgres requires double quoting when table has capital letters

### Expected Behavior

I expect the source to be detected normally, even though it has capital letters in the name

### Steps To Reproduce

1. With dbt 1.7, using postgres
2. Create a table with capital letters in the name
3. Try to add it to a model and run it

### Environment

```markdown
- OS: MacOs 14.2
- Python: Python 3.11.2
- dbt: 1.7.7
```

### Which database adapter are you using with dbt?

postgres

**Comment by graciegoheen** [comment]
Hi @qmoret - I think you should be able to solve this by using the `quoting:` config in your source yml file. Here is a link to the [documentation](https://docs.getdbt.com/reference/resource-properties/quoting).

If this still doesn't work, could you share an example of your yml file?

Thanks!

**Comment by qmoret** [comment]
Hi @graciegoheen , that works like a charm, thanks !
