### ISSUE TITLE
dbt-athena adapter plugin issue 

### ISSUE THREAD

**Issue by Siddharth545** [dbt-labs/dbt-core#9822]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

 ERROR: Runtime Error
  Credentials in profile "athena", target "default" invalid: Runtime Error
    Could not find adapter type athena!Defined profiles:
 - analytics_engineering - relational_data_warehouse - impala - athena
For more information on configuring profiles, please consult the dbt docs:

https://docs.getdbt.com/docs/configure-your-profile

### Expected Behavior

I want athena plugin to be installed properly, I am installing it properly but still cant see athena adapter in dbt --version

### Steps To Reproduce

pip install dbt-athena-community

### Environment

```markdown
- OS:mac
- Python:3.11
- dbt:1.4*
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

athena

**Comment by graciegoheen** [comment]
Hi - can you confirm that:
- you're installing an athena version that is compatible with your version of dbt-core? Note: The most recent version of `dbt-athena` is compatible with `dbt-core` version `1.7.*`
- your `athena` profile is setup like [this example](https://github.com/dbt-athena/dbt-athena#:~:text=Example%20profiles.yml%20entry%3A)?
