### ISSUE TITLE
[Bug] <Issue with running dbt connected to bigquery>

### ISSUE THREAD

**Issue by elijamuel** [dbt-labs/dbt-core#9832]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When deploying my changes to dagster cloud prod, the parsing of the project fails due top this traceback

01:44:29  Running with dbt=1.7.10
01:44:29  Encountered an error:
pyarrow package not found. Install pyarrow version >= 3.0.0.
01:44:29  Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/google/cloud/bigquery/_versions_helpers.py", line 75, in try_import
    import pyarrow
ModuleNotFoundError: No module named 'pyarrow'

### Expected Behavior

Running this module should not really result to any error at all
![image](https://github.com/dbt-labs/dbt-core/assets/145998552/9742b12c-e17d-412a-9d6c-556dedd2cc37)

### Steps To Reproduce

Deploying any changes from my GitHub repository to our prod dagster cloud triggers the error.

### Relevant log output

```shell
01:44:29  Running with dbt=1.7.10
01:44:29  Encountered an error:
pyarrow package not found. Install pyarrow version >= 3.0.0.
01:44:29  Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/google/cloud/bigquery/_versions_helpers.py", line 75, in try_import
    import pyarrow
ModuleNotFoundError: No module named 'pyarrow'
```

### Environment

```markdown
- OS: 
- Python:
- dbt:dbt=1.7.10
```

### Which database adapter are you using with dbt?

bigquery

**Comment by jaypeedevlin** [comment]
This being tracked in the bigquery adapter https://github.com/dbt-labs/dbt-bigquery/issues/1152

**Comment by elijamuel** [comment]
Thank you for this, @jaypeedevlin!

It seems like its working now too after rerunning it.
