### ISSUE TITLE
[Feature] [Spike+] scope the warning on tests directory to just the root package

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9835]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

[From slack thread](https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1711633239641279)

Anybody who has `dbt-utils` installed right now (or any other package with `tests:`) is going to get this warning on every command and potentially Be Confused

Imagine you go into your project, change every `tests:` to `data_tests:` and then still see that warning since you’re installing a package that’s using the deprecated functionality - ultimately that’s on the package maintainer to fix, not you.

We should scope the warning on `tests:` -> `data_tests:` to just look at the root project.

### Acceptance Criteria
- Spike + - Reflect on how we want to go about doing this and run it by the team to discuss the pros/cons. then fix 
- `tests:` -> `data_tests:` warning should only be issued when using `tests:` configuration in the root project

**Comment by gwenwindflower** [comment]
Closing this as a non-issue, I was misreading the warning and misinterpreted the problem. Can confirm now that I understand and updated accordingly, the warning is gone. We are not in fact bubbling up warnings from packages.

**Comment by roman-segador** [comment]
@gwenwindflower are we sure about it? I'm updating to 1.8 and I'm getting the warning each single time. The only way I have to get rid of the warning is to manually update the config of the packages in the `dbt_packages` folder from `tests` to `data_tests`.

Please check the following example where:
1. I get the warning
2. I manually update the config on the dbt_packages folder (only manual update done outside of the console log in the screenshot)
3. I run dbt clean to remove dbt_packages folder
4. dbt deps to re-create the code from the packages
5. I get the warning again at compile time. 

![image](https://github.com/dbt-labs/dbt-core/assets/98087901/69d6a3bb-f981-4348-8449-78774b8b819d)


Is there anything else outside of the warning being triggered from the packages I may be missing?
Thanks!

**Comment by gwenwindflower** [comment]
@roman-segador any chance you were updating the directory name and/or `dbt_project.yml` path and not the YAML config key names? that's what i was doing that had me confused.

**Comment by roman-segador** [comment]
@gwenwindflower not really. I did update everything in my project, so there is not a single `test` config there either in the `dbt_project.yml` or in the other yaml files where the tests are defined. 

Only place were `tests:` exists is inside `dbt_packages` folder, it is, the packages code. In the tests that the packages have defined.

only way to get rid of that warning is by replacing inside dbt_packages all `tests:` by `data_tests:` which, of course, is just to confirm my hypothesis as that code shouldn't be modified.

**Comment by emmyoop** [comment]
@gwenwindflower I just verified this is happening when you run without partial parsing.  It's actually the integration tests that get shipped with the package that are causing the deprecation warning.

**Comment by dbeatty10** [comment]
> @gwenwindflower I just verified this is happening when you run without partial parsing. It's actually the integration tests that get shipped with the package that are causing the deprecation warning.

To expand on this further, the warning will disappear if dbt is able to do partial parsing -- since it skips over parsing the YAML in that case, it won't "see" the deprecated name... 🙈 🙉 🙉.

You'll be able to get the warning back by adding the `--no-partial-parse` flag to any dbt command 🐵
