### ISSUE TITLE
[Bug] <can't upgrade to 1.8>

### ISSUE THREAD

**Issue by mrmarvisfrancesco** [dbt-labs/dbt-core#9847]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

can't upgrade to 1.8

### Expected Behavior

should be able to?

### Steps To Reproduce

/

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @mrmarvisfrancesco.

We haven't released v1.8 yet, so that explains why!

We do have a [beta available on PyPI](https://pypi.org/project/dbt-core/1.8.0b1/), and if you are using `pip`, you can install it by adding the `--pre` flag to your installation command. See [here](https://github.com/dbt-labs/docs.getdbt.com/issues/2144) for examples.

**Comment by mrmarvisfrancesco** [comment]
Hi Doug, thanks. I got confused with the beta version. Thank you
Francesco AngileriData & Analytics Manager


Stores: Amsterdam
<https://www.mrmarvis.com/pchooftstraat-amsterdam?utm_source=signature&utm_medium=email&utm_campaign=signature>
 | The Hague
<https://www.mrmarvis.com/hoogstraat-thehague?utm_source=signature&utm_medium=email&utm_campaign=signature>
 | Laren
<https://www.mrmarvis.com/sintjanstraat-laren?utm_source=signature&utm_medium=email&utm_campaign=signature>
 | Maastricht
<https://www.mrmarvis.com/kleinestaat-maastricht?utm_source=signature&utm_medium=email&utm_campaign=signature>
 | Antwerp
<https://www.mrmarvis.com/schuttershofstraat-antwerp?utm_source=signature&utm_medium=email&utm_campaign=signature>
 | Munich
<https://www.mrmarvis.com/odeonsplatz-munich?utm_source=signature&utm_medium=email&utm_campaign=signature>
Office: Huddestraat 3, 1018 HB Amsterdam
<https://goo.gl/maps/6yFC3PRPerknNGMm6>
Instagram <https://www.instagram.com/mrmarvis/> | Facebook
<https://www.facebook.com/MRMARVIS.official> | LinkedIn
<https://www.linkedin.com/company/mrmarvis>

<https://www.mrmarvis.com/?utm_source=signature&utm_medium=email&utm_campaign=signature>

<https://www.mrmarvis.com/blog/we-are-a-certified-b-corp?utm_source=signature&utm_medium=email&utm_campaign=signature>


The information contained in this message is of a confidential nature and
legally protected under applicable law. The message is intended solely for
the addressee(s). If you are not the intended addressee, you are hereby
notified that any use, forwarding, dissemination, or reproduction of this
message is strictly prohibited and may be unlawful. If you are not the
intended addressee, please contact the sender by return e-mail and destroy
all copies of the original message.
