### ISSUE TITLE
DBT snapshot with user defined `dbt_valid_from` and `dbt_valid_to`  and `dbt_updated_at`

### ISSUE THREAD

**Issue by ashwintastic** [dbt-labs/dbt-core#9848]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently dbt snapshot generates table where time dimension columns are  `dbt_valid_from` and `dbt_valid_to`.
The ask is to give the flexibility to dbt snapshot wherein a user can pass their columns name like instead of `dbt_valid_from` could have `start_date` and `dbt_valid_to` => `end_date`.

**Comment by dbeatty10** [comment]
Thanks for proposing this idea @ashwintastic ! 💡

We aren't planning on allowing custom configuration of the column names produced by snapshots. But you can still achieve your goal of changing into any column names you like by creating a pass-through view like this:

`models/your_snapshot_passthru.sql`

```sql
{{ config(materialized="view") }}

select
  -- the rest of your columns here
  dbt_valid_from as start_date,
  dbt_valid_to as end_date

from {{ ref("your_snapshot") }}
```

**Comment by ashwintastic** [comment]
If user-defined column names are not allowed,  database column names become dependent on `DBT`. Imagine in the future, there could be a scenario where we receive an update from `DBT` stating that from `XYZ` version onwards, DBT doesn't support certain column names (`dbt_valid_from `, `dbt_valid_to ` . This could potentially have a significant impact on the product using `DBT`.

**Comment by graciegoheen** [comment]
Hi @ashwintastic just as a heads up we opened up a new issue for this feature request https://github.com/dbt-labs/dbt-core/issues/10185
