### ISSUE TITLE
[Feature] Allow the use of Multiple SQL Statments (enabling the use of temporary tables to allowing greater ability to performance tune queries without having to break a transform into multiple models)

### ISSUE THREAD

**Issue by IS-Josh** [dbt-labs/dbt-core#9869]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Our use case.

**Multi-tenant platform**
Postgres  - Sharded by Partitions(each tenant has their own partition) 
DBT Transforms are incremental -(we have modified the default incremental template to better allow for partition pruning. Otherwise sub-optimal query plans are produced.

**Complex Queries**
Some transformations are not straightforward forward and no matter what indexing is applied, the Database may not make the best decision.  We currently use Pre-hooks (creation of temporary tables  -  to break queries down into smaller parts and add  indexing  (we don't want to create incremental models for all interim steps  - this would slow our processes down to a halt  - too much logging) 

We do leverage Materialization hints but that has limits.

The downside of using pre-hooks for this is that we no longer have lineage available to us for the processes run inside these steps. It also makes editing more difficult as all code needs to be escaped and the UI experience degrades.,

If we were scripting these outside of DBT we achieve the best performance by breaking down the query into multiple temporary tables that are dropped at the end of the transaction.  Each temporary table can be indexed before it's used, allowing for simpler, query plans.  Also as these are non-logged operations, the speed is fast.   

We Leverage DBT to process each tenant's data after their data has been ingested, This happens concurrently, loading into a partitioned table via incremental transforms

The Table model isn't something we can use as it would impact a concurrent run from another parallel processes. and Incremental transforms are not great option for transient data sets.

We would like the ability to have multiple SQL statements in a model, with the final statement being the one used in the transformation.  Each of these steps would need to happen within the same transaction. It would be even better if the lineage was preserved for the whole script.

The statements would need to be separated by semi colon and loaded into an array.

Each query in the array should be run in order in the same transaction, with the final one being used as per normal in the DBT materialization.

ie

```sql
{{ config(materialized='incremental'

,unique_key = 'tnt_uuid'
,tags=["analytics"] 
,schema = 'analytics'
) }}
```

Stmt1:
```sql
Create temporary table t1 as select from {{ref('table')}} a 
```
etc..

Stmt2:
```sql
create index tmp_idx_t1 on t1 (colA, colB);
```

Stmt3:
```sql
create temporary table t2 as select x.*
from {src('mytable)}} x inner join 
t1 on t1.ColA = x.ColA
and t1.ColB = x.ColB
```

Stmt4:
```sql
create index tmp_idx_t2 on (ColA,ColB)
```

Final Stmt:(Used in Transform )

```sql
select t2.*, z.val
from t2 inner join 
{{src('table3')}} z
on t2.colA = z.ColA
and colB = z.ColB
```

### Describe alternatives you've considered

WE considered using pre_hooks - it works but is awkward to debug as the code can't be run without modification easilyWe

### Who will this benefit?

Anyone trying to tune large complex queries.

### Are you interested in contributing this feature?

If i can be of assistance i will. I'm not a python programmer by trade but have been able to dive into the inner workings of DBT.  However i get a bit lost in the transaction handling.

**Comment by dbeatty10** [comment]
Thanks for reaching out with a thoughtful write-up @IS-Josh ! 🧠

Directly supporting the use-case you described is out-of-scope for dbt-core. But [custom materializations](https://docs.getdbt.com/guides/create-new-materializations?step=2) are great for these types use-cases where you need to do execute multiple statements.
