### ISSUE TITLE
Create `DiGraph` fixtured and unit test `Graph` Class

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#9871]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

As part of our [Robust Testing Initiative](https://github.com/dbt-labs/dbt-core/issues/9649) we want to create generalized fixtures for our unit tests to make writing unit tests easier. To that end we want to add or update unit some unit tests to utilize the new fixture. Currently the [Graph class](https://github.com/dbt-labs/dbt-core/blob/e81f7fdbd5b248d7cc24847da1ac6eee453f9d1a/core/dbt/graph/graph.py#L11) is not unit tested at all. We could unit test a majority of the the class by having a `DiGraph` fixture. Additionally there are other parts of the code base, such as the `GraphQueue` which also need a `DiGraph` fixture. Thus creating the fixture would make it easier to create unit tests for other parts of the codebase.

### Acceptance criteria

* There is a generic `DiGraph` unit test fixture
* There are unit tests for the config [Graph class](https://github.com/dbt-labs/dbt-core/blob/e81f7fdbd5b248d7cc24847da1ac6eee453f9d1a/core/dbt/graph/graph.py#L11)

### Suggested Tests

The work is the tests

### Impact to Other Teams

None

### Will backports be required?

Narp

**Comment by QMalcolm** [comment]
I believe a graph fixture could be created by taking the manifest fixture created from a manifest fixture (perhaps the one created during https://github.com/dbt-labs/dbt-core/issues/9665), and running it through a linker as is done in the [compile function](https://github.com/dbt-labs/dbt-core/blob/e81f7fdbd5b248d7cc24847da1ac6eee453f9d1a/core/dbt/compilation.py#L446)

**Comment by ChenyuLInx** [comment]
@QMalcolm sync up with @peterallenwebb about how this ties to removing networkx(potentially).
