### ISSUE TITLE
Unit test `GraphQueue` class

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#9872]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

As part of our [Robust Testing Initiative](https://github.com/dbt-labs/dbt-core/issues/9649) we want to create generalized fixtures for our unit tests to make writing unit tests easier. To that end we want to add or update unit some unit tests to utilize the new fixture. Currently the [GraphQueue class](https://github.com/dbt-labs/dbt-core/blob/e81f7fdbd5b248d7cc24847da1ac6eee453f9d1a/core/dbt/graph/queue.py#L18) is not unit tested at all. We could unit test by reusing the `DiGraph` fixture created in https://github.com/dbt-labs/dbt-core/issues/9871.

### Acceptance criteria

* There are unit tests for the [GraphQueue class](https://github.com/dbt-labs/dbt-core/blob/e81f7fdbd5b248d7cc24847da1ac6eee453f9d1a/core/dbt/graph/queue.py#L18)

### Suggested Tests

The work is the tests

### Impact to Other Teams

None

### Will backports be required?

Narp

**Comment by ChenyuLInx** [comment]
This include testing the public interfaces.

**Comment by ChenyuLInx** [comment]
The work @MichelleArk(Thanks!) did in #10129 accomplished this ticket.
