### ISSUE TITLE
DBT Test returns None for columns mapped to config.get in a model

### ISSUE THREAD

**Issue by mrcool4** [dbt-labs/dbt-core#9890]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In a model where metadata is configured as described below, the config.get function returns 'None' instead of the actual value specified in the dbt_project.yml. Interestingly, dbt run operates smoothly, but the problem arises specifically during test execution. Also, when I set a default value using config.get('custom_delta_dtm', 'current_timestamp'), the test retrieves the default value. I would like to know the differences between running tests and models to understand this discrepancy.

```sql
{%- set custom_delta_dtm1 = config.get('custom_delta_dtm') -%}


{%- set yaml_metadata -%}

include_source_columns: false
source_model:
  test_data: reg_test_employee
derived_columns:
  custom_delta_dtm: ({{ custom_delta_dtm1 }})
```

```sql
  create temporary table
    "stg_reg_test_employee_dmt_00760477083600779393"
    
    
    
  as (
    

with staging as (
    -- Generated by AutomateDV (formerly known as dbtvault)

    

WITH source_data AS (

    SELECT

    employee_id,
    first_name,
    last_name,
    mobile,
    store_id,
    location_id,
    update_date

    FROM "dev"."vault_dev"."reg_test_employee"
),

derived_columns AS (

    SELECT

    employee_id,
    store_id,
    location_id,
     first_name AS first_name,
    last_name AS last_name,
    mobile AS mobile,
    update_date AS src_extract_dts,
    update_date AS update_date,
    **(None) AS custom_delta_dtm**

    FROM source_data
),
```

### Expected Behavior

I am expecting the dbt test to resolve the config.get('custom_delta_dtm') defined in the dbt_project.yml but it returns 'None'
```sql
  create temporary table
    "stg_reg_test_employee_dmt_00760477083600779393"
    
    
    
  as (
    

with staging as (
    -- Generated by AutomateDV (formerly known as dbtvault)

    

WITH source_data AS (

    SELECT

    employee_id,
    first_name,
    last_name,
    mobile,
    store_id,
    location_id,
    update_date

    FROM "dev"."vault_dev"."reg_test_employee"
),

derived_columns AS (

    SELECT

    employee_id,
    store_id,
    location_id,
     first_name AS first_name,
    last_name AS last_name,
    mobile AS mobile,
    update_date AS src_extract_dts,
    update_date AS update_date,
    **update_date AS custom_delta_dtm**

    FROM source_data
),
```

### Steps To Reproduce

I cannot share the entire code but the error can be reproduced on any model with tests defined on it.

### Relevant log output

```shell
[0m08:36:00.885851 [debug] [Thread-1 (]: Redshift adapter: Redshift error: column "none" does not exist in source_data
```

### Environment

```markdown
- OS: Windows
- Python: 3.10
- dbt:1.7.9
```

### Which database adapter are you using with dbt?

redshift

**Comment by dbeatty10** [comment]
Thanks for reaching out @mrcool4 !

I'm not quite following. Could you create a simple example and provide all the code and commands required to execute it?

That will help us see what you are talking about.

**Comment by mrcool4** [comment]
Hi @dbeatty10, Sure, I will as soon as I can. Thanks.
