### ISSUE TITLE
[Bug] dbt run stuck at python models

### ISSUE THREAD

**Issue by irisschen** [dbt-labs/dbt-core#9935]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running dbt with duckdb, I face an issue where the model execution process freezes indefinitely when it encounters a Python model during `dbt run`. No error messages are shown, and I can't stop it using ctrl+c.
However, if I run the Python model separately using `dbt run -m python_model` before running `dbt run`, then dbt mysteriously completes the execution without any problems.

### Expected Behavior

dbt can successfully finish running without any errors

### Steps To Reproduce

1. `dbt run`

### Environment

```markdown
- OS: Mac OSX
- Python: Python 3.11.5
- dbt: 1.7.11
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

**Comment by dbeatty10** [comment]
Thanks for reaching out @irisschen.

Can you provide an example dbt python model that you are having problems with so that we can try to reproduce it?

And can you also share the version of dbt-duckdb that you are using?

**Comment by irisschen** [comment]
* dbt-duckdb version: 1.7.3
* Here is an example of my dbt Python model, thanks for your support.

```
def model(dbt, session):
    metadata_df = dbt.ref("src_base_persons").df()
    args = dbt.config.get("not_run_models")
    if str(dbt.this).split(".")[-1][1:-1] in args:
        metadata_df["translation"] = metadata_df["name"]
        return metadata_df

    metadata_df["translation"] = metadata_df["name"].map(translation)
    return metadata_df


def translation(artist):
    translator = kakasi()
    new_artist = ""
    translate = translator.convert(artist)
    for item in translate:
        new_artist += item["kana"]
    return new_artist

```

**Comment by dbeatty10** [comment]
Thanks for sharing that @irisschen.

We'd still need a bit more information in order to try reproducing it. Could you also share the the following:
- Simple model (or seed) for `src_base_persons` that has necessary columns like `name` and `translation`
- Code or import statement for `kakasi`
- Config details that includes how you are using the `not_run_models` config
- Example command(s) that you are using and their output

### For example

Here's the files I'm using currently:

`models/src_base_persons.sql`

```
select 'A' as name, '1' as translation
```

`models/my_python_model.py`

```
def model(dbt, session):
    metadata_df = dbt.ref("src_base_persons").df()
    return metadata_df
```

And here's a command that works fine for me:

```shell
dbt build -s +my_python_model
```

Here's the output:

```
$ dbt build -s +my_python_model
12:39:28  Running with dbt=1.7.10
12:39:28  Registered adapter: duckdb=1.7.3
12:39:28  Found 3 models, 0 sources, 0 exposures, 0 metrics, 391 macros, 0 groups, 0 semantic models
12:39:28  
12:39:28  Concurrency: 1 threads (target='duckdb')
12:39:28  
12:39:28  1 of 2 START sql view model dbt_dbeatty.src_base_persons ....................... [RUN]
12:39:28  1 of 2 OK created sql view model dbt_dbeatty.src_base_persons .................. [OK in 0.09s]
12:39:28  2 of 2 START python table model dbt_dbeatty.my_python_model .................... [RUN]
12:39:29  2 of 2 OK created python table model dbt_dbeatty.my_python_model ............... [OK in 0.74s]
12:39:29  
12:39:29  Finished running 1 view model, 1 table model in 0 hours 0 minutes and 0.99 seconds (0.99s).
12:39:29  
12:39:29  Completed successfully
12:39:29  
12:39:29  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```
