### ISSUE TITLE
Add security policy to project

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#9970]
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

Publish our security policy on GitHub by linking to https://docs.getdbt.com/docs/dbt-versions/core

### Acceptance criteria

a `SECURITY.md` exists in the root with a link to supported versions in the dbt docs page

### Suggested Tests

visual tests that it works

### Impact to Other Teams

None

### Will backports be required?

No

### Context

https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by MichelleArk** [comment]
@aranke to pick up as part of support rotation!
