### ISSUE TITLE
[Feature] Incremental model logic fails when initial loaded table is empty

### ISSUE THREAD

**Issue by BenameurZyad** [dbt-labs/dbt-core#9997]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently, the is_incremental() macro checks different conditions in a model before activating the where clause to increment the load.
There is a case where, for any given reason (the source table was empty for example), the first build of a model results in an empty table.

The macro will check correctly all the conditions :

1- The model must already exist in the database
2- The destination table already exists in the database
3- The full-refresh flag is not passed
4- The running model is configured with materialized='incremental'

and activate the where clause :
where event_time >= (select max(event_time) from {{ this }})

Unfortunately, the where clause will not work because the returned max(event_time) will be null, consequence of the destination table in the database being empty. This causes the incremental model to be blocked by the empty table, and never increment the table, even when the data becomes available in the source ref.

### Expected Behavior

The is_incremental() macro should include an additional condition :
5- The destination table is not empty

This should correct the faulty behaviour in the where clause introduced by the empty destination table in the database.
Whenever the data becomes available (after a fix for example) the model will build correctly.

### Steps To Reproduce

1- Create an incremental model
2- Make sure the first run results in an empty table in the destination
3- Fix the model and make the data available again
4- Run the incremental model

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

snowflake

**Comment by b-per** [comment]
If you expect this use case of an empty initial table, can't you do a:

```
where event_time >= (select coalesce(max(event_time),'1900-01-01') from {{ this }})
```

**Comment by BenameurZyad** [comment]
This was not an expected case on our side. We had to spend time to find out that the root cause was an empty table.
We tought something didn't work as expected with the incremental config, as in our pipeline, nothing showed that the table was empty.
The solution you proposed is exactly what we implemented to fix it.

I imagine this could happen to others. Maybe it is worth being known as a use case for incremental models.
I guess it is not exactly a bug. More like an unexpected behavior if you are not warned.

It could easily be taken care of by adding this check in the is_inremental() macro:
5- The destination table is not empty

It should act as a fix and also a highlight of this possible case.

**Comment by dbeatty10** [comment]
Thanks for these insight @b-per and @BenameurZyad. I'm going to re-categorize this a feature request for further consideration:
- add a check in the `is_incremental()` macro for an empty table.

**Comment by BenameurZyad** [comment]
Thanks a bunch. You guys are awsome.

**Comment by dbeatty10** [comment]
In the meantime, I opened this issue to improve our documentation:
- https://github.com/dbt-labs/docs.getdbt.com/issues/5321

**Comment by dbeatty10** [comment]
@BenameurZyad I've updated the documentation within https://github.com/dbt-labs/docs.getdbt.com/pull/5326 so that it includes an example that will work when the incremental table is empty.

I'm going to close this issue in favor of that update to the documentation. If we get additional feedback that this is not sufficient, we can consider re-opening this.
